In [1]:
import pandas as pd
from pandas import MultiIndex, Int16Dtype
Ref=pd.read_csv('Ref.csv')
Ref["CO"] = 1000 * Ref["CO"]
Ref['Date'] = pd.to_datetime(Ref['Date_Time'])
Ref=Ref.set_index('Date')
Ref.drop('Date_Time',axis = 1, inplace = True)
Ref=Ref.resample('5min').mean()
Ref=Ref[76463:137376]
Ref_CO=Ref['CO'].to_list()
Ref_NO2=Ref['NO2'].to_list()
Ref_SO2=Ref['SO2'].to_list()
Ref_O3=Ref['O3'].to_list()

In [2]:
from platform import python_version
 
 
print("Current Python Version-", python_version())

Current Python Version- 3.8.6

In [3]:
import numpy
numpy.version.version

'1.23.5'

In [4]:
import random
import pandas as pd
import scipy.io
import numpy as np
data = pd.read_csv('CO.txt', header = None,low_memory=False)
data.columns=['WE','AE','Temp','RH','Time']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_CO=data
Data_CO['Ref']=Ref_CO
index_names = Data_CO[ (Data_CO['WE'] >1000)].index
Data_CO.drop(index_names, inplace = True)
WE=Data_CO['WE'].to_list()
AE=Data_CO['AE'].to_list()
signal=np.array(WE)-np.array(AE)
Data_CO['Net Signal']=signal
Data_CO['Month']=Data_CO.index.month
Data_CO['Day_of_week']=Data_CO.index.dayofweek
Data_CO['Day']=Data_CO.index.day
Data_CO['Hour']=Data_CO.index.hour
CO_Data=Data_CO
CO_Data=CO_Data[(CO_Data[CO_Data.columns] >= 0).all(axis=1)]
CO_Data=CO_Data.dropna()
data = pd.read_csv('Conc_CO.txt', header = None,low_memory=False)
data.columns=['Lab1','Temp','RH','Time','Ref']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_CO=data
Data_CO.drop(index_names, inplace = True)
signal=np.array(WE)-np.array(AE)
Data_CO['Net Signal']=signal
Data_CO['Month']=Data_CO.index.month
Data_CO['Day_of_week']=Data_CO.index.dayofweek
Data_CO['Day']=Data_CO.index.day
Data_CO['Hour']=Data_CO.index.hour
CO_Data=Data_CO
CO_Data=CO_Data[(CO_Data[CO_Data.columns] >= 0).all(axis=1)]
CO_Data=CO_Data.dropna()
CO_Data=CO_Data.resample('h').mean()
CO_Data=CO_Data.dropna()
CO_Data.tail()

,Lab1,Temp,RH,Ref,Net Signal,Month,Day_of_week,Day,Hour
Date,,,,,,,,,
2020-04-30 19:00:00,242.060716,18.870796,71.072939,188.915151,91.471325,4.0,3.0,30.0,19.0
2020-04-30 20:00:00,218.655079,18.056864,75.132153,178.704750,84.176485,4.0,3.0,30.0,20.0
2020-04-30 21:00:00,194.147868,17.090891,81.315038,161.421792,73.858294,4.0,3.0,30.0,21.0
2020-04-30 22:00:00,206.432889,16.714085,82.568155,197.744043,83.279611,4.0,3.0,30.0,22.0
2020-04-30 23:00:00,173.577429,16.365121,83.662401,162.157636,68.669099,4.0,3.0,30.0,23.0

In [5]:
import pandas as pd
import scipy.io
import numpy as np
data = pd.read_csv('O3.txt', header = None,low_memory=False)
data.columns=['AE','WE','Temp','RH','Time']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_O3=data
Data_O3['Ref']=Ref_O3
WE=Data_O3['WE'].to_list()
AE=Data_O3['AE'].to_list()
signal=np.array(WE)-np.array(AE)
Data_O3['Net Signal']=signal
Data_O3['Month']=Data_O3.index.month
Data_O3['Day_of_week']=Data_O3.index.dayofweek
Data_O3['Day']=Data_O3.index.day
Data_O3['Hour']=Data_O3.index.hour
O3_Data=Data_O3
O3_Data=O3_Data[(O3_Data[O3_Data.columns] >= 0).all(axis=1)]
O3_Data=O3_Data.dropna()
data = pd.read_csv('Conc_O3.txt', header = None,low_memory=False)
data.columns=['Lab1','Temp','RH','Time','Ref']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_O3=data
signal=np.array(WE)-np.array(AE)
Data_O3['Net Signal']=signal
Data_O3['Month']=Data_O3.index.month
Data_O3['Day_of_week']=Data_O3.index.dayofweek
Data_O3['Day']=Data_O3.index.day
Data_O3['Hour']=Data_O3.index.hour
O3_Data=Data_O3
O3_Data=O3_Data[(O3_Data[O3_Data.columns] >= 0).all(axis=1)]
O3_Data=O3_Data.dropna() 
O3_Data=O3_Data.resample('h').mean()
O3_Data=O3_Data.dropna()
O3_Data.head()

ref_O3=Data_O3['Ref'].to_list()
len(ref_O3)

60913

In [6]:
import pandas as pd
import scipy.io
import numpy as np
data = pd.read_csv('NO2.txt', header = None,low_memory=False)
data.columns=['WE','AE','Temp','RH','Time']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_NO2=data
Data_NO2['Ref']=Ref_NO2
WE=Data_NO2['WE'].to_list()
AE=Data_NO2['AE'].to_list()
signal=np.array(WE)-np.array(AE)
Data_NO2['Net Signal']=signal
Data_NO2['Month']=Data_NO2.index.month
Data_NO2['Day_of_week']=Data_NO2.index.dayofweek
Data_NO2['Day']=Data_NO2.index.day
Data_NO2['Hour']=Data_NO2.index.hour
NO2_Data=Data_NO2
NO2_Data=NO2_Data[(NO2_Data[NO2_Data.columns] >= 0).all(axis=1)]
NO2_Data=NO2_Data.dropna()
data = pd.read_csv('Conc_NO2.txt', header = None,low_memory=False)
data.columns=['Lab1','Temp','RH','Time','Ref']
Time=data['Time'].to_list()
time=[]
subscript = str.maketrans("0123456789", "₀₁₂₃₄₅₆₇₈₉") 
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_NO2=data
signal=np.array(WE)-np.array(AE)
Data_NO2['Net Signal']=signal
Data_NO2['Month']=Data_NO2.index.month
Data_NO2['Day_of_week']=Data_NO2.index.dayofweek
Data_NO2['Day']=Data_NO2.index.day
Data_NO2['Hour']=Data_NO2.index.hour
Data_NO2['Ref_O3']=ref_O3
NO2_Data=Data_NO2
NO2_Data=NO2_Data[(NO2_Data[NO2_Data.columns] >= 0).all(axis=1)]
NO2_Data=NO2_Data.dropna()
NO2_Data=NO2_Data.resample('h').mean()
NO2_Data=NO2_Data.dropna()

In [7]:
import pandas as pd
import scipy.io
import numpy as np
data = pd.read_csv('O3.txt', header = None,low_memory=False)
data.columns=['AE','WE','Temp','RH','Time']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_O3=data
Data_O3['Ref']=Ref_O3
WE=Data_O3['WE'].to_list()
AE=Data_O3['AE'].to_list()
signal=np.array(WE)-np.array(AE)
Data_O3['Net Signal']=signal
Data_O3['Month']=Data_O3.index.month
Data_O3['Day_of_week']=Data_O3.index.dayofweek
Data_O3['Day']=Data_O3.index.day
Data_O3['Hour']=Data_O3.index.hour
O3_Data=Data_O3
O3_Data=O3_Data[(O3_Data[O3_Data.columns] >= 0).all(axis=1)]
O3_Data=O3_Data.dropna()
data = pd.read_csv('Conc_O3.txt', header = None,low_memory=False)
data.columns=['Lab1','Temp','RH','Time','Ref']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_O3=data
signal=np.array(WE)-np.array(AE)
Data_O3['Net Signal']=signal
Data_O3['Month']=Data_O3.index.month
Data_O3['Day_of_week']=Data_O3.index.dayofweek
Data_O3['Day']=Data_O3.index.day
Data_O3['Hour']=Data_O3.index.hour
ref_NO2=Data_NO2['Ref'].to_list()
Data_O3['Ref_NO2']=ref_NO2
O3_Data=Data_O3
O3_Data=O3_Data[(O3_Data[O3_Data.columns] >= 0).all(axis=1)]
O3_Data=O3_Data.dropna()
O3_Data=O3_Data.resample('h').mean()
O3_Data=O3_Data.dropna()
O3_Data.head()

,Lab1,Temp,RH,Ref,Net Signal,Month,Day_of_week,Day,Hour,Ref_NO2
Date,,,,,,,,,,
2019-10-02 11:00:00,621.625704,26.378438,58.063437,46.094860,3.605625,10.0,2.0,2.0,11.0,15.230400
2019-10-02 12:00:00,725.154408,25.795055,48.256857,57.532808,13.865109,10.0,2.0,2.0,12.0,5.384051
2019-10-07 10:00:00,108.196313,32.344264,37.260757,47.259008,11.447809,10.0,0.0,7.0,10.0,4.255772
2019-10-07 11:00:00,135.822676,34.926112,35.013036,42.114260,10.075221,10.0,0.0,7.0,11.0,16.268034
2019-10-07 12:00:00,203.757758,36.201221,31.829282,45.701366,7.624153,10.0,0.0,7.0,12.0,12.770444

# CO DATA

In [8]:
from sktime.performance_metrics.forecasting import sMAPE, smape_loss
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error as mae
import sklearn.metrics as sm
import matplotlib.pyplot as plt
from flaml import AutoML
from sklearn.datasets import fetch_california_housing
#'Ref_NO2','Ref_SO2','Ref_O3',
#,'Month','Day_of_week','Day','Hour'

#train_test_split(X, y, test_size = 0.2)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/xgboost/compat.py:93: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index

In [9]:
from flaml.model import SKLearnEstimator
# SKLearnEstimator is derived from BaseEstimator

In [10]:
df1=[x for _, x in CO_Data.groupby('Month')]
data_oct=df1[4]
#data_oct=data_oct.sample(frac=1)
data_nov=df1[5]
#data_nov=data_nov.sample(frac=1)
data_dec=df1[6]
#data_dec=data_dec.sample(frac=1)
data_jan=df1[0]
#data_jan=data_jan.sample(frac=1)
data_feb=df1[1]
#data_feb=data_feb.sample(frac=1)
data_mar=df1[2]
#data_mar=data_mar.sample(frac=1)
data_apr=df1[3]
#data_apr=data_apr.sample(frac=1)
data=[data_oct,data_nov,data_dec,data_jan,data_feb,data_mar]

In [11]:
data_Oct=data_oct.resample('60min').mean()
data_Oct=data_Oct.dropna()
data_Nov=data_nov.resample('60min').mean()
data_Nov=data_Nov.dropna()
data_Dec=data_dec.resample('60min').mean()
data_Dec=data_Dec.dropna()
data_Jan=data_jan.resample('60min').mean()
data_Jan=data_Jan.dropna()
data_Feb=data_feb.resample('60min').mean()
data_Feb=data_Feb.dropna()
data_Mar=data_mar.resample('60min').mean()
data_Mar=data_Mar.dropna()
data_Apr=data_apr.resample('60min').mean()
data_Apr=data_Apr.dropna()

In [12]:
co_data=CO_Data
co_data=co_data.resample('60min').mean()
co_data=co_data.dropna()
X=co_data[['Net Signal','Temp','RH','Month','Day_of_week','Hour']]
y=co_data['Ref']
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=1)
from flaml import AutoML
from sklearn.datasets import fetch_california_housing

# Initialize an AutoML instance
automl = AutoML()
# Specify automl goal and constraint
automl_settings = {
    "time_budget": 60,  # in seconds
    "metric": 'rmse',
    "eval_method":'holdout',
    "task": 'regression',
    "log_file_name": "california.log",
}

# Train with labeled input data
automl.fit(X_train=X_train, y_train=y_train,
           **automl_settings,estimator_list=["rf"])#,estimator_list=["xgboost"]
pred=automl.predict(X_test)
rmse_r=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y_test),2)

[flaml.automl: 04-23 11:13:48] {2599} INFO - task = regression
[flaml.automl: 04-23 11:13:48] {2601} INFO - Data split method: uniform
[flaml.automl: 04-23 11:13:48] {2604} INFO - Evaluation method: holdout
[flaml.automl: 04-23 11:13:48] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 04-23 11:13:48] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 04-23 11:13:48] {3166} INFO - iteration 0, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:48] {3296} INFO - Estimated sufficient time budget=673s. Estimated necessary time budget=1s.
[flaml.automl: 04-23 11:13:48] {3343} INFO -  at 0.1s,	estimator rf's best error=157.3513,	best estimator rf's best error=157.3513
[flaml.automl: 04-23 11:13:48] {3166} INFO - iteration 1, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:48] {3343} INFO -  at 0.1s,	estimator rf's best error=135.8043,	best estimator rf's best error=135.8043
[flaml.automl: 04-23 11:13:48] {3166} INFO - iteration 2, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:48] {3343} INFO -  at 0.2s,	estimator rf's best error=135.8043,	best estimator rf's best error=135.8043
[flaml.automl: 04-23 11:13:48] {3166} INFO - iteration 3, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:48] {3343} INFO -  at 0.2s,	estimator rf's best error=130.7587,	best estimator rf's best error=130.7587
[flaml.automl: 04-23 11:13:48] {3166} INFO - iteration 4, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:48] {3343} INFO -  at 0.3s,	estimator rf's best error=128.5756,	best estimator rf's best error=128.5756
[flaml.automl: 04-23 11:13:48] {3166} INFO - iteration 5, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:48] {3343} INFO -  at 0.4s,	estimator rf's best error=128.1225,	best estimator rf's best error=128.1225
[flaml.automl: 04-23 11:13:48] {3166} INFO - iteration 6, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:48] {3343} INFO -  at 0.4s,	estimator rf's best error=128.1225,	best estimator rf's best error=128.1225
[flaml.automl: 04-23 11:13:48] {3166} INFO - iteration 7, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:48] {3343} INFO -  at 0.5s,	estimator rf's best error=128.1225,	best estimator rf's best error=128.1225
[flaml.automl: 04-23 11:13:48] {3166} INFO - iteration 8, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:48] {3343} INFO -  at 0.6s,	estimator rf's best error=127.2525,	best estimator rf's best error=127.2525
[flaml.automl: 04-23 11:13:48] {3166} INFO - iteration 9, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:48] {3343} INFO -  at 0.6s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:48] {3166} INFO - iteration 10, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:48] {3343} INFO -  at 0.7s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:48] {3166} INFO - iteration 11, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:48] {3343} INFO -  at 0.8s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288

[flaml.automl: 04-23 11:13:48] {3166} INFO - iteration 12, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 0.8s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 13, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 0.9s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 14, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 0.9s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 15, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 1.0s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 16, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 1.1s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 17, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 1.2s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 18, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 1.2s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 19, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 1.3s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 20, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 1.3s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 21, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 1.3s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 22, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 1.4s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 23, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 1.5s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 24, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 1.5s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 25, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 1.6s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 26, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 1.7s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 27, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 1.7s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 28, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:49] {3343} INFO -  at 1.8s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:49] {3166} INFO - iteration 29, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:50] {3343} INFO -  at 1.8s,	estimator rf's best error=124.2288,	best estimator rf's best error=124.2288
[flaml.automl: 04-23 11:13:50] {3166} INFO - iteration 30, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:50] {3343} INFO -  at 1.9s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:50] {3166} INFO - iteration 31, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:50] {3343} INFO -  at 1.9s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:50] {3166} INFO - iteration 32, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:50] {3343} INFO -  at 2.0s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:50] {3166} INFO - iteration 33, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:50] {3343} INFO -  at 2.1s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:50] {3166} INFO - iteration 34, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:50] {3343} INFO -  at 2.2s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:50] {3166} INFO - iteration 35, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:50] {3343} INFO -  at 2.3s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:50] {3166} INFO - iteration 36, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:50] {3343} INFO -  at 2.3s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:50] {3166} INFO - iteration 37, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:13:50] {3343} INFO -  at 2.4s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:50] {3166} INFO - iteration 38, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:50] {3343} INFO -  at 2.5s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:50] {3166} INFO - iteration 39, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:50] {3343} INFO -  at 2.6s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:50] {3166} INFO - iteration 40, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:50] {3343} INFO -  at 2.7s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:50] {3166} INFO - iteration 41, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:50] {3343} INFO -  at 2.8s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:50] {3166} INFO - iteration 42, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:51] {3343} INFO -  at 2.9s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:51] {3166} INFO - iteration 43, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:51] {3343} INFO -  at 3.0s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:51] {3166} INFO - iteration 44, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:51] {3343} INFO -  at 3.1s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:51] {3166} INFO - iteration 45, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:51] {3343} INFO -  at 3.1s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:51] {3166} INFO - iteration 46, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:51] {3343} INFO -  at 3.2s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:51] {3166} INFO - iteration 47, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:51] {3343} INFO -  at 3.3s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:51] {3166} INFO - iteration 48, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:51] {3343} INFO -  at 3.4s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:51] {3166} INFO - iteration 49, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:51] {3343} INFO -  at 3.4s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:51] {3166} INFO - iteration 50, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:13:51] {3343} INFO -  at 3.5s,	estimator rf's best error=122.2711,	best estimator rf's best error=122.2711
[flaml.automl: 04-23 11:13:51] {3166} INFO - iteration 51, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:51] {3343} INFO -  at 3.6s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:51] {3166} INFO - iteration 52, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:51] {3343} INFO -  at 3.6s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:51] {3166} INFO - iteration 53, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:51] {3343} INFO -  at 3.7s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:51] {3166} INFO - iteration 54, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:52] {3343} INFO -  at 3.8s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:52] {3166} INFO - iteration 55, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:52] {3343} INFO -  at 3.9s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:52] {3166} INFO - iteration 56, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:52] {3343} INFO -  at 4.0s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:52] {3166} INFO - iteration 57, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:52] {3343} INFO -  at 4.1s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:52] {3166} INFO - iteration 58, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:52] {3343} INFO -  at 4.2s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:52] {3166} INFO - iteration 59, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:52] {3343} INFO -  at 4.3s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:52] {3166} INFO - iteration 60, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:52] {3343} INFO -  at 4.4s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:52] {3166} INFO - iteration 61, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:52] {3343} INFO -  at 4.6s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:52] {3166} INFO - iteration 62, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:52] {3343} INFO -  at 4.7s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:52] {3166} INFO - iteration 63, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:52] {3343} INFO -  at 4.7s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289

[flaml.automl: 04-23 11:13:52] {3166} INFO - iteration 64, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:53] {3343} INFO -  at 4.8s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:53] {3166} INFO - iteration 65, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:53] {3343} INFO -  at 4.9s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:53] {3166} INFO - iteration 66, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:53] {3343} INFO -  at 5.1s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:53] {3166} INFO - iteration 67, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:53] {3343} INFO -  at 5.2s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:53] {3166} INFO - iteration 68, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:53] {3343} INFO -  at 5.3s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:53] {3166} INFO - iteration 69, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:53] {3343} INFO -  at 5.4s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:53] {3166} INFO - iteration 70, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:53] {3343} INFO -  at 5.5s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:53] {3166} INFO - iteration 71, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:53] {3343} INFO -  at 5.6s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:53] {3166} INFO - iteration 72, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:53] {3343} INFO -  at 5.7s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:53] {3166} INFO - iteration 73, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:54] {3343} INFO -  at 5.8s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:54] {3166} INFO - iteration 74, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:54] {3343} INFO -  at 5.9s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:54] {3166} INFO - iteration 75, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:54] {3343} INFO -  at 6.0s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:54] {3166} INFO - iteration 76, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:13:54] {3343} INFO -  at 6.1s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:54] {3166} INFO - iteration 77, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:54] {3343} INFO -  at 6.2s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:54] {3166} INFO - iteration 78, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:54] {3343} INFO -  at 6.3s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:54] {3166} INFO - iteration 79, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:54] {3343} INFO -  at 6.4s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:54] {3166} INFO - iteration 80, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:54] {3343} INFO -  at 6.5s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:54] {3166} INFO - iteration 81, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:54] {3343} INFO -  at 6.5s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:54] {3166} INFO - iteration 82, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:54] {3343} INFO -  at 6.6s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:54] {3166} INFO - iteration 83, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:54] {3343} INFO -  at 6.7s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:54] {3166} INFO - iteration 84, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:55] {3343} INFO -  at 6.8s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:55] {3166} INFO - iteration 85, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:55] {3343} INFO -  at 6.9s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:55] {3166} INFO - iteration 86, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:55] {3343} INFO -  at 7.0s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:55] {3166} INFO - iteration 87, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:55] {3343} INFO -  at 7.1s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:55] {3166} INFO - iteration 88, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:55] {3343} INFO -  at 7.2s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:55] {3166} INFO - iteration 89, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:13:55] {3343} INFO -  at 7.3s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:55] {3166} INFO - iteration 90, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:55] {3343} INFO -  at 7.4s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:55] {3166} INFO - iteration 91, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:55] {3343} INFO -  at 7.4s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:55] {3166} INFO - iteration 92, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:55] {3343} INFO -  at 7.5s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:55] {3166} INFO - iteration 93, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:55] {3343} INFO -  at 7.6s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:55] {3166} INFO - iteration 94, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:55] {3343} INFO -  at 7.6s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:55] {3166} INFO - iteration 95, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:55] {3343} INFO -  at 7.7s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:55] {3166} INFO - iteration 96, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:55] {3343} INFO -  at 7.8s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:55] {3166} INFO - iteration 97, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:56] {3343} INFO -  at 7.9s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:56] {3166} INFO - iteration 98, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:56] {3343} INFO -  at 7.9s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:56] {3166} INFO - iteration 99, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:56] {3343} INFO -  at 8.0s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:56] {3166} INFO - iteration 100, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:56] {3343} INFO -  at 8.1s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:56] {3166} INFO - iteration 101, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:56] {3343} INFO -  at 8.2s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:56] {3166} INFO - iteration 102, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:13:56] {3343} INFO -  at 8.3s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:56] {3166} INFO - iteration 103, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:56] {3343} INFO -  at 8.4s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:56] {3166} INFO - iteration 104, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:56] {3343} INFO -  at 8.5s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:56] {3166} INFO - iteration 105, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:56] {3343} INFO -  at 8.6s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:56] {3166} INFO - iteration 106, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:56] {3343} INFO -  at 8.7s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:56] {3166} INFO - iteration 107, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:57] {3343} INFO -  at 8.8s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:57] {3166} INFO - iteration 108, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:57] {3343} INFO -  at 8.9s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:57] {3166} INFO - iteration 109, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:57] {3343} INFO -  at 9.0s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:57] {3166} INFO - iteration 110, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:57] {3343} INFO -  at 9.1s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:57] {3166} INFO - iteration 111, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:57] {3343} INFO -  at 9.2s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:57] {3166} INFO - iteration 112, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:57] {3343} INFO -  at 9.3s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:57] {3166} INFO - iteration 113, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:57] {3343} INFO -  at 9.4s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:57] {3166} INFO - iteration 114, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:57] {3343} INFO -  at 9.5s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:57] {3166} INFO - iteration 115, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:13:57] {3343} INFO -  at 9.6s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:57] {3166} INFO - iteration 116, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:57] {3343} INFO -  at 9.7s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:57] {3166} INFO - iteration 117, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:57] {3343} INFO -  at 9.8s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:57] {3166} INFO - iteration 118, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:58] {3343} INFO -  at 9.9s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:58] {3166} INFO - iteration 119, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:58] {3343} INFO -  at 10.0s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:58] {3166} INFO - iteration 120, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:58] {3343} INFO -  at 10.1s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:58] {3166} INFO - iteration 121, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:58] {3343} INFO -  at 10.1s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:58] {3166} INFO - iteration 122, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:58] {3343} INFO -  at 10.2s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:58] {3166} INFO - iteration 123, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:58] {3343} INFO -  at 10.3s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:58] {3166} INFO - iteration 124, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:58] {3343} INFO -  at 10.3s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:58] {3166} INFO - iteration 125, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:58] {3343} INFO -  at 10.4s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:58] {3166} INFO - iteration 126, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:58] {3343} INFO -  at 10.5s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:58] {3166} INFO - iteration 127, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:58] {3343} INFO -  at 10.6s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:58] {3166} INFO - iteration 128, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:13:58] {3343} INFO -  at 10.7s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:58] {3166} INFO - iteration 129, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:58] {3343} INFO -  at 10.8s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:58] {3166} INFO - iteration 130, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:59] {3343} INFO -  at 10.8s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:59] {3166} INFO - iteration 131, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:59] {3343} INFO -  at 10.9s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:59] {3166} INFO - iteration 132, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:59] {3343} INFO -  at 11.0s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:59] {3166} INFO - iteration 133, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:59] {3343} INFO -  at 11.0s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:59] {3166} INFO - iteration 134, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:59] {3343} INFO -  at 11.1s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:59] {3166} INFO - iteration 135, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:59] {3343} INFO -  at 11.2s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:59] {3166} INFO - iteration 136, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:59] {3343} INFO -  at 11.2s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:59] {3166} INFO - iteration 137, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:59] {3343} INFO -  at 11.3s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:59] {3166} INFO - iteration 138, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:59] {3343} INFO -  at 11.4s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:59] {3166} INFO - iteration 139, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:59] {3343} INFO -  at 11.5s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:59] {3166} INFO - iteration 140, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:59] {3343} INFO -  at 11.5s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:59] {3166} INFO - iteration 141, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:13:59] {3343} INFO -  at 11.6s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:59] {3166} INFO - iteration 142, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:59] {3343} INFO -  at 11.7s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:59] {3166} INFO - iteration 143, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:13:59] {3343} INFO -  at 11.8s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:13:59] {3166} INFO - iteration 144, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:00] {3343} INFO -  at 11.9s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:14:00] {3166} INFO - iteration 145, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:00] {3343} INFO -  at 11.9s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:14:00] {3166} INFO - iteration 146, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:00] {3343} INFO -  at 12.0s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:14:00] {3166} INFO - iteration 147, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:00] {3343} INFO -  at 12.1s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:14:00] {3166} INFO - iteration 148, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:00] {3343} INFO -  at 12.2s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:14:00] {3166} INFO - iteration 149, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:00] {3343} INFO -  at 12.3s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:14:00] {3166} INFO - iteration 150, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:00] {3343} INFO -  at 12.5s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:14:00] {3166} INFO - iteration 151, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:00] {3343} INFO -  at 12.6s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:14:00] {3166} INFO - iteration 152, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:00] {3343} INFO -  at 12.7s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:14:00] {3166} INFO - iteration 153, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:00] {3343} INFO -  at 12.8s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:14:00] {3166} INFO - iteration 154, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:01] {3343} INFO -  at 12.9s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:14:01] {3166} INFO - iteration 155, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:01] {3343} INFO -  at 13.0s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:14:01] {3166} INFO - iteration 156, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:01] {3343} INFO -  at 13.0s,	estimator rf's best error=120.9289,	best estimator rf's best error=120.9289
[flaml.automl: 04-23 11:14:01] {3166} INFO - iteration 157, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:01] {3343} INFO -  at 13.1s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:01] {3166} INFO - iteration 158, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:01] {3343} INFO -  at 13.2s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:01] {3166} INFO - iteration 159, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:01] {3343} INFO -  at 13.2s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:01] {3166} INFO - iteration 160, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:01] {3343} INFO -  at 13.3s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:01] {3166} INFO - iteration 161, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:01] {3343} INFO -  at 13.4s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:01] {3166} INFO - iteration 162, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:01] {3343} INFO -  at 13.4s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:01] {3166} INFO - iteration 163, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:01] {3343} INFO -  at 13.5s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:01] {3166} INFO - iteration 164, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:01] {3343} INFO -  at 13.6s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:01] {3166} INFO - iteration 165, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:01] {3343} INFO -  at 13.7s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:01] {3166} INFO - iteration 166, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:01] {3343} INFO -  at 13.7s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:01] {3166} INFO - iteration 167, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:02] {3343} INFO -  at 13.8s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:02] {3166} INFO - iteration 168, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:02] {3343} INFO -  at 13.9s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:02] {3166} INFO - iteration 169, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:02] {3343} INFO -  at 13.9s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:02] {3166} INFO - iteration 170, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:02] {3343} INFO -  at 14.0s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:02] {3166} INFO - iteration 171, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:02] {3343} INFO -  at 14.1s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:02] {3166} INFO - iteration 172, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:02] {3343} INFO -  at 14.2s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:02] {3166} INFO - iteration 173, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:02] {3343} INFO -  at 14.3s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:02] {3166} INFO - iteration 174, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:02] {3343} INFO -  at 14.4s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:02] {3166} INFO - iteration 175, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:02] {3343} INFO -  at 14.5s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:02] {3166} INFO - iteration 176, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:02] {3343} INFO -  at 14.7s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:02] {3166} INFO - iteration 177, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:02] {3343} INFO -  at 14.8s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:02] {3166} INFO - iteration 178, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 14.8s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 179, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 14.9s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 180, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 15.0s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 181, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 15.0s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 182, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 15.1s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 183, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 15.2s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 184, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 15.2s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 185, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 15.3s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 186, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 15.4s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 187, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 15.4s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 188, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 15.5s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 189, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 15.6s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 190, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 15.6s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 191, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 15.7s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 192, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:03] {3343} INFO -  at 15.8s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:03] {3166} INFO - iteration 193, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:04] {3343} INFO -  at 15.8s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:04] {3166} INFO - iteration 194, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:04] {3343} INFO -  at 15.9s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:04] {3166} INFO - iteration 195, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:04] {3343} INFO -  at 16.0s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:04] {3166} INFO - iteration 196, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:04] {3343} INFO -  at 16.0s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:04] {3166} INFO - iteration 197, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:04] {3343} INFO -  at 16.1s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:04] {3166} INFO - iteration 198, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:04] {3343} INFO -  at 16.2s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:04] {3166} INFO - iteration 199, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:04] {3343} INFO -  at 16.2s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:04] {3166} INFO - iteration 200, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:04] {3343} INFO -  at 16.3s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:04] {3166} INFO - iteration 201, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:04] {3343} INFO -  at 16.4s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:04] {3166} INFO - iteration 202, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:04] {3343} INFO -  at 16.4s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:04] {3166} INFO - iteration 203, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:04] {3343} INFO -  at 16.5s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:04] {3166} INFO - iteration 204, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:04] {3343} INFO -  at 16.6s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:04] {3166} INFO - iteration 205, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:04] {3343} INFO -  at 16.6s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:04] {3166} INFO - iteration 206, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:04] {3343} INFO -  at 16.7s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:04] {3166} INFO - iteration 207, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:05] {3343} INFO -  at 16.8s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:05] {3166} INFO - iteration 208, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:05] {3343} INFO -  at 16.9s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:05] {3166} INFO - iteration 209, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:05] {3343} INFO -  at 16.9s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:05] {3166} INFO - iteration 210, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:05] {3343} INFO -  at 17.0s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:05] {3166} INFO - iteration 211, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:05] {3343} INFO -  at 17.1s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:05] {3166} INFO - iteration 212, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:05] {3343} INFO -  at 17.1s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:05] {3166} INFO - iteration 213, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:05] {3343} INFO -  at 17.2s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:05] {3166} INFO - iteration 214, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:05] {3343} INFO -  at 17.3s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:05] {3166} INFO - iteration 215, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:05] {3343} INFO -  at 17.4s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:05] {3166} INFO - iteration 216, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:05] {3343} INFO -  at 17.5s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:05] {3166} INFO - iteration 217, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:05] {3343} INFO -  at 17.6s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:05] {3166} INFO - iteration 218, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:05] {3343} INFO -  at 17.7s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:05] {3166} INFO - iteration 219, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:05] {3343} INFO -  at 17.8s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:05] {3166} INFO - iteration 220, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:06] {3343} INFO -  at 17.9s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:06] {3166} INFO - iteration 221, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:06] {3343} INFO -  at 17.9s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:06] {3166} INFO - iteration 222, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:06] {3343} INFO -  at 18.0s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:06] {3166} INFO - iteration 223, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:06] {3343} INFO -  at 18.1s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:06] {3166} INFO - iteration 224, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:06] {3343} INFO -  at 18.2s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:06] {3166} INFO - iteration 225, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:06] {3343} INFO -  at 18.3s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:06] {3166} INFO - iteration 226, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:06] {3343} INFO -  at 18.4s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:06] {3166} INFO - iteration 227, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:06] {3343} INFO -  at 18.5s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:06] {3166} INFO - iteration 228, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:06] {3343} INFO -  at 18.6s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:06] {3166} INFO - iteration 229, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:06] {3343} INFO -  at 18.7s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:06] {3166} INFO - iteration 230, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:06] {3343} INFO -  at 18.8s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:06] {3166} INFO - iteration 231, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 18.8s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 232, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 18.9s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978

[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 233, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 19.0s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 234, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 19.0s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 235, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 19.1s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 236, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 19.2s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 237, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 19.2s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 238, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 19.3s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 239, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 19.3s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 240, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 19.4s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 241, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 19.5s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 242, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 19.6s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 243, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 19.6s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 244, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 19.7s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 245, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:07] {3343} INFO -  at 19.8s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:07] {3166} INFO - iteration 246, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:08] {3343} INFO -  at 19.8s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:08] {3166} INFO - iteration 247, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:08] {3343} INFO -  at 19.9s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:08] {3166} INFO - iteration 248, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:08] {3343} INFO -  at 20.0s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:08] {3166} INFO - iteration 249, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:08] {3343} INFO -  at 20.1s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:08] {3166} INFO - iteration 250, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:08] {3343} INFO -  at 20.2s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:08] {3166} INFO - iteration 251, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:08] {3343} INFO -  at 20.3s,	estimator rf's best error=119.8978,	best estimator rf's best error=119.8978
[flaml.automl: 04-23 11:14:08] {3166} INFO - iteration 252, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:08] {3343} INFO -  at 20.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:08] {3166} INFO - iteration 253, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:08] {3343} INFO -  at 20.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:08] {3166} INFO - iteration 254, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:08] {3343} INFO -  at 20.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:08] {3166} INFO - iteration 255, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:08] {3343} INFO -  at 20.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:08] {3166} INFO - iteration 256, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:08] {3343} INFO -  at 20.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:08] {3166} INFO - iteration 257, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:08] {3343} INFO -  at 20.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:08] {3166} INFO - iteration 258, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:09] {3343} INFO -  at 20.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:09] {3166} INFO - iteration 259, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:09] {3343} INFO -  at 20.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:09] {3166} INFO - iteration 260, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:09] {3343} INFO -  at 21.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:09] {3166} INFO - iteration 261, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:09] {3343} INFO -  at 21.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:09] {3166} INFO - iteration 262, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:09] {3343} INFO -  at 21.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:09] {3166} INFO - iteration 263, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:09] {3343} INFO -  at 21.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:09] {3166} INFO - iteration 264, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:09] {3343} INFO -  at 21.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:09] {3166} INFO - iteration 265, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:09] {3343} INFO -  at 21.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:09] {3166} INFO - iteration 266, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:09] {3343} INFO -  at 21.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:09] {3166} INFO - iteration 267, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:09] {3343} INFO -  at 21.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:09] {3166} INFO - iteration 268, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:09] {3343} INFO -  at 21.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:09] {3166} INFO - iteration 269, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:09] {3343} INFO -  at 21.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:09] {3166} INFO - iteration 270, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:10] {3343} INFO -  at 21.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:10] {3166} INFO - iteration 271, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:10] {3343} INFO -  at 21.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:10] {3166} INFO - iteration 272, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:10] {3343} INFO -  at 22.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:10] {3166} INFO - iteration 273, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:10] {3343} INFO -  at 22.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:10] {3166} INFO - iteration 274, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:10] {3343} INFO -  at 22.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:10] {3166} INFO - iteration 275, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:10] {3343} INFO -  at 22.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:10] {3166} INFO - iteration 276, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:10] {3343} INFO -  at 22.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:10] {3166} INFO - iteration 277, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:10] {3343} INFO -  at 22.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:10] {3166} INFO - iteration 278, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:10] {3343} INFO -  at 22.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:10] {3166} INFO - iteration 279, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:10] {3343} INFO -  at 22.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:10] {3166} INFO - iteration 280, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:10] {3343} INFO -  at 22.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:10] {3166} INFO - iteration 281, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:10] {3343} INFO -  at 22.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:10] {3166} INFO - iteration 282, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:11] {3343} INFO -  at 22.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:11] {3166} INFO - iteration 283, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:11] {3343} INFO -  at 22.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:11] {3166} INFO - iteration 284, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:11] {3343} INFO -  at 22.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:11] {3166} INFO - iteration 285, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:11] {3343} INFO -  at 23.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:11] {3166} INFO - iteration 286, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:11] {3343} INFO -  at 23.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:11] {3166} INFO - iteration 287, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:11] {3343} INFO -  at 23.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:11] {3166} INFO - iteration 288, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:11] {3343} INFO -  at 23.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:11] {3166} INFO - iteration 289, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:11] {3343} INFO -  at 23.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:11] {3166} INFO - iteration 290, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:11] {3343} INFO -  at 23.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:11] {3166} INFO - iteration 291, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:11] {3343} INFO -  at 23.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:11] {3166} INFO - iteration 292, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:11] {3343} INFO -  at 23.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:11] {3166} INFO - iteration 293, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:12] {3343} INFO -  at 23.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:12] {3166} INFO - iteration 294, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:12] {3343} INFO -  at 23.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:12] {3166} INFO - iteration 295, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:12] {3343} INFO -  at 24.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:12] {3166} INFO - iteration 296, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:12] {3343} INFO -  at 24.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:12] {3166} INFO - iteration 297, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:12] {3343} INFO -  at 24.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:12] {3166} INFO - iteration 298, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:12] {3343} INFO -  at 24.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:12] {3166} INFO - iteration 299, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:12] {3343} INFO -  at 24.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:12] {3166} INFO - iteration 300, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:12] {3343} INFO -  at 24.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:12] {3166} INFO - iteration 301, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:12] {3343} INFO -  at 24.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:12] {3166} INFO - iteration 302, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:12] {3343} INFO -  at 24.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:12] {3166} INFO - iteration 303, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:13] {3343} INFO -  at 24.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:13] {3166} INFO - iteration 304, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:13] {3343} INFO -  at 25.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:13] {3166} INFO - iteration 305, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:13] {3343} INFO -  at 25.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:13] {3166} INFO - iteration 306, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:13] {3343} INFO -  at 25.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:13] {3166} INFO - iteration 307, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:13] {3343} INFO -  at 25.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:13] {3166} INFO - iteration 308, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:13] {3343} INFO -  at 25.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:13] {3166} INFO - iteration 309, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:13] {3343} INFO -  at 25.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:13] {3166} INFO - iteration 310, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:13] {3343} INFO -  at 25.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:13] {3166} INFO - iteration 311, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:13] {3343} INFO -  at 25.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:13] {3166} INFO - iteration 312, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:13] {3343} INFO -  at 25.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:13] {3166} INFO - iteration 313, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:14] {3343} INFO -  at 25.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:14] {3166} INFO - iteration 314, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:14] {3343} INFO -  at 26.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:14] {3166} INFO - iteration 315, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:14] {3343} INFO -  at 26.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:14] {3166} INFO - iteration 316, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:14] {3343} INFO -  at 26.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:14] {3166} INFO - iteration 317, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:14] {3343} INFO -  at 26.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:14] {3166} INFO - iteration 318, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:14] {3343} INFO -  at 26.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:14] {3166} INFO - iteration 319, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:14] {3343} INFO -  at 26.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:14] {3166} INFO - iteration 320, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:14] {3343} INFO -  at 26.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:14] {3166} INFO - iteration 321, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:14] {3343} INFO -  at 26.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:14] {3166} INFO - iteration 322, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:15] {3343} INFO -  at 27.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:15] {3166} INFO - iteration 323, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:15] {3343} INFO -  at 27.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:15] {3166} INFO - iteration 324, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:15] {3343} INFO -  at 27.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:15] {3166} INFO - iteration 325, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:16] {3343} INFO -  at 27.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:16] {3166} INFO - iteration 326, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:16] {3343} INFO -  at 27.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:16] {3166} INFO - iteration 327, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:16] {3343} INFO -  at 28.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:16] {3166} INFO - iteration 328, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:16] {3343} INFO -  at 28.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:16] {3166} INFO - iteration 329, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:16] {3343} INFO -  at 28.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:16] {3166} INFO - iteration 330, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:16] {3343} INFO -  at 28.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:16] {3166} INFO - iteration 331, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:16] {3343} INFO -  at 28.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:16] {3166} INFO - iteration 332, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:17] {3343} INFO -  at 29.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:17] {3166} INFO - iteration 333, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:17] {3343} INFO -  at 29.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:17] {3166} INFO - iteration 334, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:17] {3343} INFO -  at 29.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:17] {3166} INFO - iteration 335, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:17] {3343} INFO -  at 29.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:17] {3166} INFO - iteration 336, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:17] {3343} INFO -  at 29.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:17] {3166} INFO - iteration 337, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:17] {3343} INFO -  at 29.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:17] {3166} INFO - iteration 338, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:18] {3343} INFO -  at 29.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:18] {3166} INFO - iteration 339, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:18] {3343} INFO -  at 30.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:18] {3166} INFO - iteration 340, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:18] {3343} INFO -  at 30.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:18] {3166} INFO - iteration 341, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:18] {3343} INFO -  at 30.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:18] {3166} INFO - iteration 342, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:18] {3343} INFO -  at 30.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:18] {3166} INFO - iteration 343, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:18] {3343} INFO -  at 30.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:18] {3166} INFO - iteration 344, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:18] {3343} INFO -  at 30.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:18] {3166} INFO - iteration 345, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:18] {3343} INFO -  at 30.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:18] {3166} INFO - iteration 346, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:18] {3343} INFO -  at 30.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:18] {3166} INFO - iteration 347, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:19] {3343} INFO -  at 30.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:19] {3166} INFO - iteration 348, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:19] {3343} INFO -  at 30.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:19] {3166} INFO - iteration 349, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:19] {3343} INFO -  at 31.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:19] {3166} INFO - iteration 350, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:19] {3343} INFO -  at 31.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:19] {3166} INFO - iteration 351, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:19] {3343} INFO -  at 31.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:19] {3166} INFO - iteration 352, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:19] {3343} INFO -  at 31.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:19] {3166} INFO - iteration 353, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:19] {3343} INFO -  at 31.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:19] {3166} INFO - iteration 354, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:19] {3343} INFO -  at 31.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:19] {3166} INFO - iteration 355, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:19] {3343} INFO -  at 31.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:19] {3166} INFO - iteration 356, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:19] {3343} INFO -  at 31.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:19] {3166} INFO - iteration 357, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:19] {3343} INFO -  at 31.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:19] {3166} INFO - iteration 358, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:19] {3343} INFO -  at 31.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:19] {3166} INFO - iteration 359, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:20] {3343} INFO -  at 31.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:20] {3166} INFO - iteration 360, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:20] {3343} INFO -  at 31.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:20] {3166} INFO - iteration 361, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:20] {3343} INFO -  at 32.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:20] {3166} INFO - iteration 362, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:20] {3343} INFO -  at 32.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:20] {3166} INFO - iteration 363, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:20] {3343} INFO -  at 32.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:20] {3166} INFO - iteration 364, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:20] {3343} INFO -  at 32.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:20] {3166} INFO - iteration 365, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:20] {3343} INFO -  at 32.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:20] {3166} INFO - iteration 366, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:20] {3343} INFO -  at 32.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:20] {3166} INFO - iteration 367, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:20] {3343} INFO -  at 32.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:20] {3166} INFO - iteration 368, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:20] {3343} INFO -  at 32.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:20] {3166} INFO - iteration 369, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:20] {3343} INFO -  at 32.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:20] {3166} INFO - iteration 370, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:20] {3343} INFO -  at 32.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:20] {3166} INFO - iteration 371, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:21] {3343} INFO -  at 32.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:21] {3166} INFO - iteration 372, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:21] {3343} INFO -  at 32.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:21] {3166} INFO - iteration 373, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:21] {3343} INFO -  at 33.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:21] {3166} INFO - iteration 374, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:21] {3343} INFO -  at 33.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:21] {3166} INFO - iteration 375, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:21] {3343} INFO -  at 33.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:21] {3166} INFO - iteration 376, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:21] {3343} INFO -  at 33.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:21] {3166} INFO - iteration 377, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:21] {3343} INFO -  at 33.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:21] {3166} INFO - iteration 378, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:21] {3343} INFO -  at 33.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:21] {3166} INFO - iteration 379, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:21] {3343} INFO -  at 33.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:21] {3166} INFO - iteration 380, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:21] {3343} INFO -  at 33.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:21] {3166} INFO - iteration 381, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:21] {3343} INFO -  at 33.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:22] {3166} INFO - iteration 382, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:22] {3343} INFO -  at 33.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:22] {3166} INFO - iteration 383, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:22] {3343} INFO -  at 34.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:22] {3166} INFO - iteration 384, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:22] {3343} INFO -  at 34.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:22] {3166} INFO - iteration 385, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:22] {3343} INFO -  at 34.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:22] {3166} INFO - iteration 386, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:22] {3343} INFO -  at 34.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:22] {3166} INFO - iteration 387, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:22] {3343} INFO -  at 34.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:22] {3166} INFO - iteration 388, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:22] {3343} INFO -  at 34.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:22] {3166} INFO - iteration 389, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:22] {3343} INFO -  at 34.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:22] {3166} INFO - iteration 390, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:22] {3343} INFO -  at 34.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:22] {3166} INFO - iteration 391, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:22] {3343} INFO -  at 34.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:22] {3166} INFO - iteration 392, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:23] {3343} INFO -  at 34.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:23] {3166} INFO - iteration 393, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:23] {3343} INFO -  at 34.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:23] {3166} INFO - iteration 394, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:23] {3343} INFO -  at 35.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:23] {3166} INFO - iteration 395, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:23] {3343} INFO -  at 35.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:23] {3166} INFO - iteration 396, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:23] {3343} INFO -  at 35.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:23] {3166} INFO - iteration 397, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:23] {3343} INFO -  at 35.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:23] {3166} INFO - iteration 398, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:23] {3343} INFO -  at 35.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:23] {3166} INFO - iteration 399, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:23] {3343} INFO -  at 35.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:23] {3166} INFO - iteration 400, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:23] {3343} INFO -  at 35.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:23] {3166} INFO - iteration 401, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:23] {3343} INFO -  at 35.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:23] {3166} INFO - iteration 402, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:24] {3343} INFO -  at 35.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:24] {3166} INFO - iteration 403, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:24] {3343} INFO -  at 36.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:24] {3166} INFO - iteration 404, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:24] {3343} INFO -  at 36.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:24] {3166} INFO - iteration 405, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:24] {3343} INFO -  at 36.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:24] {3166} INFO - iteration 406, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:24] {3343} INFO -  at 36.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:24] {3166} INFO - iteration 407, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:24] {3343} INFO -  at 36.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:24] {3166} INFO - iteration 408, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:24] {3343} INFO -  at 36.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:24] {3166} INFO - iteration 409, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:24] {3343} INFO -  at 36.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:24] {3166} INFO - iteration 410, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:25] {3343} INFO -  at 36.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:25] {3166} INFO - iteration 411, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:25] {3343} INFO -  at 37.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:25] {3166} INFO - iteration 412, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:25] {3343} INFO -  at 37.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:25] {3166} INFO - iteration 413, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:25] {3343} INFO -  at 37.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:25] {3166} INFO - iteration 414, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:25] {3343} INFO -  at 37.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:25] {3166} INFO - iteration 415, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:26] {3343} INFO -  at 37.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:26] {3166} INFO - iteration 416, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:26] {3343} INFO -  at 38.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:26] {3166} INFO - iteration 417, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:26] {3343} INFO -  at 38.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:26] {3166} INFO - iteration 418, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:26] {3343} INFO -  at 38.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:26] {3166} INFO - iteration 419, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:26] {3343} INFO -  at 38.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:26] {3166} INFO - iteration 420, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:26] {3343} INFO -  at 38.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:26] {3166} INFO - iteration 421, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:26] {3343} INFO -  at 38.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:26] {3166} INFO - iteration 422, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:27] {3343} INFO -  at 39.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:27] {3166} INFO - iteration 423, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:27] {3343} INFO -  at 39.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:27] {3166} INFO - iteration 424, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:27] {3343} INFO -  at 39.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:27] {3166} INFO - iteration 425, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:27] {3343} INFO -  at 39.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:27] {3166} INFO - iteration 426, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:27] {3343} INFO -  at 39.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:27] {3166} INFO - iteration 427, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:27] {3343} INFO -  at 39.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:27] {3166} INFO - iteration 428, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:27] {3343} INFO -  at 39.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:27] {3166} INFO - iteration 429, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:27] {3343} INFO -  at 39.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:27] {3166} INFO - iteration 430, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:28] {3343} INFO -  at 39.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:28] {3166} INFO - iteration 431, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:28] {3343} INFO -  at 40.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:28] {3166} INFO - iteration 432, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:28] {3343} INFO -  at 40.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:28] {3166} INFO - iteration 433, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:28] {3343} INFO -  at 40.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:28] {3166} INFO - iteration 434, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:28] {3343} INFO -  at 40.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:28] {3166} INFO - iteration 435, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:28] {3343} INFO -  at 40.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:28] {3166} INFO - iteration 436, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:29] {3343} INFO -  at 41.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:29] {3166} INFO - iteration 437, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:29] {3343} INFO -  at 41.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:29] {3166} INFO - iteration 438, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:29] {3343} INFO -  at 41.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:29] {3166} INFO - iteration 439, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:29] {3343} INFO -  at 41.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:29] {3166} INFO - iteration 440, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:30] {3343} INFO -  at 41.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:30] {3166} INFO - iteration 441, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:30] {3343} INFO -  at 42.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:30] {3166} INFO - iteration 442, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:30] {3343} INFO -  at 42.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:30] {3166} INFO - iteration 443, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:30] {3343} INFO -  at 42.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:30] {3166} INFO - iteration 444, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:30] {3343} INFO -  at 42.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:30] {3166} INFO - iteration 445, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:31] {3343} INFO -  at 43.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:31] {3166} INFO - iteration 446, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:31] {3343} INFO -  at 43.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:31] {3166} INFO - iteration 447, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:31] {3343} INFO -  at 43.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:31] {3166} INFO - iteration 448, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:31] {3343} INFO -  at 43.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:31] {3166} INFO - iteration 449, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:32] {3343} INFO -  at 44.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:32] {3166} INFO - iteration 450, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:32] {3343} INFO -  at 44.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:32] {3166} INFO - iteration 451, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:32] {3343} INFO -  at 44.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:32] {3166} INFO - iteration 452, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:32] {3343} INFO -  at 44.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:32] {3166} INFO - iteration 453, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:32] {3343} INFO -  at 44.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:32] {3166} INFO - iteration 454, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:33] {3343} INFO -  at 44.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:33] {3166} INFO - iteration 455, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:33] {3343} INFO -  at 45.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:33] {3166} INFO - iteration 456, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:33] {3343} INFO -  at 45.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:33] {3166} INFO - iteration 457, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:33] {3343} INFO -  at 45.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:33] {3166} INFO - iteration 458, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:34] {3343} INFO -  at 46.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:34] {3166} INFO - iteration 459, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:34] {3343} INFO -  at 46.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:34] {3166} INFO - iteration 460, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:34] {3343} INFO -  at 46.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:34] {3166} INFO - iteration 461, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:34] {3343} INFO -  at 46.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:34] {3166} INFO - iteration 462, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:34] {3343} INFO -  at 46.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:34] {3166} INFO - iteration 463, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:35] {3343} INFO -  at 46.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:35] {3166} INFO - iteration 464, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:35] {3343} INFO -  at 47.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:35] {3166} INFO - iteration 465, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:35] {3343} INFO -  at 47.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:35] {3166} INFO - iteration 466, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:35] {3343} INFO -  at 47.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:35] {3166} INFO - iteration 467, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:36] {3343} INFO -  at 47.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:36] {3166} INFO - iteration 468, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:36] {3343} INFO -  at 48.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:36] {3166} INFO - iteration 469, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:36] {3343} INFO -  at 48.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:36] {3166} INFO - iteration 470, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:36] {3343} INFO -  at 48.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:36] {3166} INFO - iteration 471, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:37] {3343} INFO -  at 48.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:37] {3166} INFO - iteration 472, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:37] {3343} INFO -  at 49.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:37] {3166} INFO - iteration 473, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:37] {3343} INFO -  at 49.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:37] {3166} INFO - iteration 474, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:37] {3343} INFO -  at 49.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:37] {3166} INFO - iteration 475, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:38] {3343} INFO -  at 50.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:38] {3166} INFO - iteration 476, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:38] {3343} INFO -  at 50.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:38] {3166} INFO - iteration 477, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:38] {3343} INFO -  at 50.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:38] {3166} INFO - iteration 478, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:38] {3343} INFO -  at 50.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:38] {3166} INFO - iteration 479, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:38] {3343} INFO -  at 50.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:38] {3166} INFO - iteration 480, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:39] {3343} INFO -  at 50.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:39] {3166} INFO - iteration 481, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:39] {3343} INFO -  at 51.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:39] {3166} INFO - iteration 482, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:39] {3343} INFO -  at 51.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:39] {3166} INFO - iteration 483, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:39] {3343} INFO -  at 51.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:39] {3166} INFO - iteration 484, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:39] {3343} INFO -  at 51.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:39] {3166} INFO - iteration 485, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:39] {3343} INFO -  at 51.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:39] {3166} INFO - iteration 486, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:39] {3343} INFO -  at 51.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:39] {3166} INFO - iteration 487, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:39] {3343} INFO -  at 51.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:39] {3166} INFO - iteration 488, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:40] {3343} INFO -  at 51.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:40] {3166} INFO - iteration 489, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:40] {3343} INFO -  at 52.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:40] {3166} INFO - iteration 490, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:40] {3343} INFO -  at 52.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:40] {3166} INFO - iteration 491, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:40] {3343} INFO -  at 52.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:40] {3166} INFO - iteration 492, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:40] {3343} INFO -  at 52.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:40] {3166} INFO - iteration 493, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:40] {3343} INFO -  at 52.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:40] {3166} INFO - iteration 494, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:40] {3343} INFO -  at 52.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:40] {3166} INFO - iteration 495, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:40] {3343} INFO -  at 52.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:40] {3166} INFO - iteration 496, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:41] {3343} INFO -  at 52.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:41] {3166} INFO - iteration 497, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:41] {3343} INFO -  at 53.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:41] {3166} INFO - iteration 498, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:41] {3343} INFO -  at 53.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:41] {3166} INFO - iteration 499, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:41] {3343} INFO -  at 53.3s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:41] {3166} INFO - iteration 500, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:41] {3343} INFO -  at 53.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:41] {3166} INFO - iteration 501, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:41] {3343} INFO -  at 53.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:41] {3166} INFO - iteration 502, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:41] {3343} INFO -  at 53.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:41] {3166} INFO - iteration 503, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:41] {3343} INFO -  at 53.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:41] {3166} INFO - iteration 504, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:42] {3343} INFO -  at 53.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:42] {3166} INFO - iteration 505, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:42] {3343} INFO -  at 54.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:42] {3166} INFO - iteration 506, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:42] {3343} INFO -  at 54.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:42] {3166} INFO - iteration 507, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:42] {3343} INFO -  at 54.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:42] {3166} INFO - iteration 508, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:42] {3343} INFO -  at 54.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:42] {3166} INFO - iteration 509, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:42] {3343} INFO -  at 54.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:42] {3166} INFO - iteration 510, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:42] {3343} INFO -  at 54.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:42] {3166} INFO - iteration 511, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:43] {3343} INFO -  at 54.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:43] {3166} INFO - iteration 512, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:43] {3343} INFO -  at 55.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:43] {3166} INFO - iteration 513, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:43] {3343} INFO -  at 55.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:43] {3166} INFO - iteration 514, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:43] {3343} INFO -  at 55.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:43] {3166} INFO - iteration 515, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:43] {3343} INFO -  at 55.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:43] {3166} INFO - iteration 516, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:43] {3343} INFO -  at 55.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:43] {3166} INFO - iteration 517, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:44] {3343} INFO -  at 55.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:44] {3166} INFO - iteration 518, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:44] {3343} INFO -  at 56.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:44] {3166} INFO - iteration 519, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:44] {3343} INFO -  at 56.4s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:44] {3166} INFO - iteration 520, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:44] {3343} INFO -  at 56.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:44] {3166} INFO - iteration 521, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:45] {3343} INFO -  at 57.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:45] {3166} INFO - iteration 522, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:45] {3343} INFO -  at 57.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:45] {3166} INFO - iteration 523, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:45] {3343} INFO -  at 57.7s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:45] {3166} INFO - iteration 524, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:46] {3343} INFO -  at 57.9s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:46] {3166} INFO - iteration 525, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:46] {3343} INFO -  at 58.2s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:46] {3166} INFO - iteration 526, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:46] {3343} INFO -  at 58.6s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:46] {3166} INFO - iteration 527, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:46] {3343} INFO -  at 58.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:46] {3166} INFO - iteration 528, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:47] {3343} INFO -  at 59.1s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:47] {3166} INFO - iteration 529, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:47] {3343} INFO -  at 59.5s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:47] {3166} INFO - iteration 530, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:48] {3343} INFO -  at 59.8s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708
[flaml.automl: 04-23 11:14:48] {3166} INFO - iteration 531, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:48] {3343} INFO -  at 60.0s,	estimator rf's best error=119.8708,	best estimator rf's best error=119.8708

[flaml.automl: 04-23 11:14:48] {3602} INFO - retrain rf for 0.3s
[flaml.automl: 04-23 11:14:48] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.794058201864398, max_leaf_nodes=123,
                      n_estimators=13, n_jobs=-1)
[flaml.automl: 04-23 11:14:48] {2901} INFO - fit succeeded
[flaml.automl: 04-23 11:14:48] {2902} INFO - Time taken to find the best model: 20.42247486114502

In [13]:
from sklearn.neighbors import LocalOutlierFactor
A=['Net Signal','Temp','RH','Month','Day_of_week','Hour']
B='Ref'
frame1=[data_Oct,data_Nov,data_Dec,data_Jan,data_Feb,data_Mar]#,data_feb
Train1=pd.concat(frame1)
train1=Train1.sample(frac=1)
lof = LocalOutlierFactor()
yhat = lof.fit_predict(train1)
mask = yhat != -1
train1= train1[mask]
test1=data_Apr
yhat = lof.fit_predict(test1)
mask = yhat != -1
test1= test1[mask]

frame2=[data_Oct,data_Nov,data_Dec,data_Jan,data_Feb,data_Apr]#,data_feb
Train2=pd.concat(frame2)
train2=Train2.sample(frac=1)
yhat = lof.fit_predict(train2)
mask = yhat != -1
train2= train2[mask]
test2=data_Mar
yhat = lof.fit_predict(test2)
mask = yhat != -1
test2= test2[mask]

frame3=[data_Oct,data_Nov,data_Dec,data_Jan,data_Mar,data_Apr]#,data_feb
Train3=pd.concat(frame3)
train3=Train3.sample(frac=1)
yhat = lof.fit_predict(train3)
mask = yhat != -1
train3= train3[mask]
test3=data_Feb
yhat = lof.fit_predict(test3)
mask = yhat != -1
test3= test3[mask]

frame4=[data_Oct,data_Nov,data_Dec,data_Feb,data_Mar,data_Apr]#,data_feb
Train4=pd.concat(frame4)
train4=Train4.sample(frac=1)
yhat = lof.fit_predict(train4)
mask = yhat != -1
train4= train4[mask]
test4=data_Jan
yhat = lof.fit_predict(test4)
mask = yhat != -1
test4= test4[mask]

frame5=[data_Oct,data_Nov,data_Jan,data_Feb,data_Mar,data_Apr]#,data_feb
Train5=pd.concat(frame5)
train5=Train5.sample(frac=1)
yhat = lof.fit_predict(train5)
mask = yhat != -1
train5= train5[mask]
test5=data_Dec
yhat = lof.fit_predict(test5)
mask = yhat != -1
test5= test5[mask]

frame6=[data_Oct,data_Dec,data_Jan,data_Feb,data_Mar,data_Apr]#,data_feb
Train6=pd.concat(frame6)
train6=Train6.sample(frac=1)
yhat = lof.fit_predict(train6)
mask = yhat != -1
train6= train6[mask]
test6=data_Nov
yhat = lof.fit_predict(test6)
mask = yhat != -1
test6= test6[mask]

frame7=[data_Nov,data_Dec,data_Jan,data_Feb,data_Mar,data_Apr]#,data_feb
Train7=pd.concat(frame7)
train7=Train7.sample(frac=1)
yhat = lof.fit_predict(train7)
mask = yhat != -1
train7= train7[mask]
test7=data_Oct
yhat = lof.fit_predict(test7)
mask = yhat != -1
test7= test7[mask]


Train=[train1,train2,train3,train4,train5,train6,train7]
Test=[test1,test2,test3,test4,test5,test6,test7]

In [ ]:
from flaml import AutoML
from sklearn.datasets import fetch_california_housing

# Initialize an AutoML instance
automl = AutoML()
# Specify automl goal and constraint
automl_settings = {
    "time_budget": 300,  # in seconds
    "metric": 'rmse',
    "eval_method":'holdout',
    "task": 'regression',
    "log_file_name": "california.log",
}

rmse=[]

# Train with labeled input data
for i in range(7):
    automl.fit(X_train=Train[i][A], y_train=Train[i][B],
           **automl_settings,estimator_list=["rf"])#,estimator_list=["xgboost"]
    pred=automl.predict(Test[i][A])
    R2=round(sm.r2_score(Test[i][B], pred), 2)
    r=round(np.corrcoef(Test[i][B], pred)[0, 1],2)
    RMSE=round(np.sqrt(sm.mean_squared_error(Test[i][B], pred))/np.mean(Test[i][B]),2)
    rmse.append(RMSE)
    print(r,R2,RMSE)
# Predict
#print(automl.predict(X_test))
# Print the best model
#print(automl.model.estimator)

[flaml.automl: 04-23 11:14:50] {2599} INFO - task = regression
[flaml.automl: 04-23 11:14:50] {2601} INFO - Data split method: uniform
[flaml.automl: 04-23 11:14:50] {2604} INFO - Evaluation method: holdout
[flaml.automl: 04-23 11:14:50] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 04-23 11:14:50] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 04-23 11:14:50] {3166} INFO - iteration 0, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:50] {3296} INFO - Estimated sufficient time budget=2059s. Estimated necessary time budget=2s.
[flaml.automl: 04-23 11:14:50] {3343} INFO -  at 0.5s,	estimator rf's best error=141.2826,	best estimator rf's best error=141.2826
[flaml.automl: 04-23 11:14:50] {3166} INFO - iteration 1, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:50] {3343} INFO -  at 0.7s,	estimator rf's best error=116.4705,	best estimator rf's best error=116.4705
[flaml.automl: 04-23 11:14:50] {3166} INFO - iteration 2, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:50] {3343} INFO -  at 0.9s,	estimator rf's best error=116.4705,	best estimator rf's best error=116.4705
[flaml.automl: 04-23 11:14:50] {3166} INFO - iteration 3, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:51] {3343} INFO -  at 1.3s,	estimator rf's best error=103.8984,	best estimator rf's best error=103.8984
[flaml.automl: 04-23 11:14:51] {3166} INFO - iteration 4, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:51] {3343} INFO -  at 1.6s,	estimator rf's best error=103.8984,	best estimator rf's best error=103.8984
[flaml.automl: 04-23 11:14:51] {3166} INFO - iteration 5, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:51] {3343} INFO -  at 1.9s,	estimator rf's best error=103.8984,	best estimator rf's best error=103.8984
[flaml.automl: 04-23 11:14:51] {3166} INFO - iteration 6, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:52] {3343} INFO -  at 2.2s,	estimator rf's best error=103.5786,	best estimator rf's best error=103.5786
[flaml.automl: 04-23 11:14:52] {3166} INFO - iteration 7, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:52] {3343} INFO -  at 2.4s,	estimator rf's best error=99.6798,	best estimator rf's best error=99.6798
[flaml.automl: 04-23 11:14:52] {3166} INFO - iteration 8, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:52] {3343} INFO -  at 2.6s,	estimator rf's best error=99.6798,	best estimator rf's best error=99.6798
[flaml.automl: 04-23 11:14:52] {3166} INFO - iteration 9, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:52] {3343} INFO -  at 2.8s,	estimator rf's best error=97.7071,	best estimator rf's best error=97.7071
[flaml.automl: 04-23 11:14:52] {3166} INFO - iteration 10, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:52] {3343} INFO -  at 3.0s,	estimator rf's best error=97.7071,	best estimator rf's best error=97.7071
[flaml.automl: 04-23 11:14:52] {3166} INFO - iteration 11, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:53] {3343} INFO -  at 3.1s,	estimator rf's best error=97.7071,	best estimator rf's best error=97.7071
[flaml.automl: 04-23 11:14:53] {3166} INFO - iteration 12, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:53] {3343} INFO -  at 3.3s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:53] {3166} INFO - iteration 13, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:53] {3343} INFO -  at 3.6s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:53] {3166} INFO - iteration 14, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:54] {3343} INFO -  at 4.0s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:54] {3166} INFO - iteration 15, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:54] {3343} INFO -  at 4.3s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:54] {3166} INFO - iteration 16, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:54] {3343} INFO -  at 4.7s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:54] {3166} INFO - iteration 17, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:55] {3343} INFO -  at 5.0s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:55] {3166} INFO - iteration 18, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:55] {3343} INFO -  at 5.4s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:55] {3166} INFO - iteration 19, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:55] {3343} INFO -  at 5.7s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:55] {3166} INFO - iteration 20, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:55] {3343} INFO -  at 6.0s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:55] {3166} INFO - iteration 21, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:56] {3343} INFO -  at 6.3s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:56] {3166} INFO - iteration 22, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:56] {3343} INFO -  at 6.6s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:56] {3166} INFO - iteration 23, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:56] {3343} INFO -  at 6.9s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:56] {3166} INFO - iteration 24, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:57] {3343} INFO -  at 7.2s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:57] {3166} INFO - iteration 25, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:57] {3343} INFO -  at 7.4s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:57] {3166} INFO - iteration 26, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:57] {3343} INFO -  at 7.6s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:57] {3166} INFO - iteration 27, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:57] {3343} INFO -  at 7.7s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:57] {3166} INFO - iteration 28, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:57] {3343} INFO -  at 7.9s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:57] {3166} INFO - iteration 29, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:58] {3343} INFO -  at 8.1s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:58] {3166} INFO - iteration 30, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:58] {3343} INFO -  at 8.2s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:58] {3166} INFO - iteration 31, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:58] {3343} INFO -  at 8.3s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:58] {3166} INFO - iteration 32, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:58] {3343} INFO -  at 8.4s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:58] {3166} INFO - iteration 33, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:58] {3343} INFO -  at 8.6s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:58] {3166} INFO - iteration 34, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:58] {3343} INFO -  at 8.7s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:58] {3166} INFO - iteration 35, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:58] {3343} INFO -  at 8.8s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:58] {3166} INFO - iteration 36, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:58] {3343} INFO -  at 9.0s,	estimator rf's best error=92.6048,	best estimator rf's best error=92.6048
[flaml.automl: 04-23 11:14:58] {3166} INFO - iteration 37, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:14:59] {3343} INFO -  at 9.3s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:14:59] {3166} INFO - iteration 38, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:59] {3343} INFO -  at 9.6s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:14:59] {3166} INFO - iteration 39, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:59] {3343} INFO -  at 9.8s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:14:59] {3166} INFO - iteration 40, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:14:59] {3343} INFO -  at 9.9s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:14:59] {3166} INFO - iteration 41, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:00] {3343} INFO -  at 10.2s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:00] {3166} INFO - iteration 42, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:00] {3343} INFO -  at 10.3s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:00] {3166} INFO - iteration 43, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:00] {3343} INFO -  at 10.6s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:00] {3166} INFO - iteration 44, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:00] {3343} INFO -  at 11.0s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:00] {3166} INFO - iteration 45, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:01] {3343} INFO -  at 11.2s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:01] {3166} INFO - iteration 46, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:01] {3343} INFO -  at 11.6s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:01] {3166} INFO - iteration 47, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:01] {3343} INFO -  at 12.0s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:01] {3166} INFO - iteration 48, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:02] {3343} INFO -  at 12.3s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:02] {3166} INFO - iteration 49, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:02] {3343} INFO -  at 12.4s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:02] {3166} INFO - iteration 50, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:02] {3343} INFO -  at 12.7s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:02] {3166} INFO - iteration 51, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:02] {3343} INFO -  at 12.8s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:02] {3166} INFO - iteration 52, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:02] {3343} INFO -  at 13.0s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:03] {3166} INFO - iteration 53, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:03] {3343} INFO -  at 13.3s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:03] {3166} INFO - iteration 54, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:03] {3343} INFO -  at 13.6s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:03] {3166} INFO - iteration 55, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:03] {3343} INFO -  at 13.7s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:03] {3166} INFO - iteration 56, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:03] {3343} INFO -  at 13.9s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:03] {3166} INFO - iteration 57, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:04] {3343} INFO -  at 14.1s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:04] {3166} INFO - iteration 58, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:04] {3343} INFO -  at 14.2s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:04] {3166} INFO - iteration 59, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:04] {3343} INFO -  at 14.4s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:04] {3166} INFO - iteration 60, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:04] {3343} INFO -  at 14.7s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:04] {3166} INFO - iteration 61, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:04] {3343} INFO -  at 14.8s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:04] {3166} INFO - iteration 62, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:04] {3343} INFO -  at 15.0s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:05] {3166} INFO - iteration 63, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:05] {3343} INFO -  at 15.2s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:05] {3166} INFO - iteration 64, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:05] {3343} INFO -  at 15.4s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:05] {3166} INFO - iteration 65, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:05] {3343} INFO -  at 15.6s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:05] {3166} INFO - iteration 66, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:05] {3343} INFO -  at 15.8s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:05] {3166} INFO - iteration 67, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:05] {3343} INFO -  at 16.0s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:05] {3166} INFO - iteration 68, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:06] {3343} INFO -  at 16.2s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:06] {3166} INFO - iteration 69, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:06] {3343} INFO -  at 16.4s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:06] {3166} INFO - iteration 70, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:06] {3343} INFO -  at 16.6s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:06] {3166} INFO - iteration 71, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:06] {3343} INFO -  at 16.8s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:06] {3166} INFO - iteration 72, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:07] {3343} INFO -  at 17.0s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:07] {3166} INFO - iteration 73, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:07] {3343} INFO -  at 17.2s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:07] {3166} INFO - iteration 74, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:07] {3343} INFO -  at 17.4s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:07] {3166} INFO - iteration 75, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:07] {3343} INFO -  at 17.6s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:07] {3166} INFO - iteration 76, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:07] {3343} INFO -  at 17.7s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:07] {3166} INFO - iteration 77, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:07] {3343} INFO -  at 18.0s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:07] {3166} INFO - iteration 78, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:08] {3343} INFO -  at 18.2s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:08] {3166} INFO - iteration 79, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:08] {3343} INFO -  at 18.4s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:08] {3166} INFO - iteration 80, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:08] {3343} INFO -  at 18.6s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:08] {3166} INFO - iteration 81, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:08] {3343} INFO -  at 18.8s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:08] {3166} INFO - iteration 82, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:08] {3343} INFO -  at 18.9s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:08] {3166} INFO - iteration 83, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:09] {3343} INFO -  at 19.1s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:09] {3166} INFO - iteration 84, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:09] {3343} INFO -  at 19.4s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:09] {3166} INFO - iteration 85, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:09] {3343} INFO -  at 19.5s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:09] {3166} INFO - iteration 86, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:09] {3343} INFO -  at 19.7s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:09] {3166} INFO - iteration 87, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:09] {3343} INFO -  at 19.9s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:09] {3166} INFO - iteration 88, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:10] {3343} INFO -  at 20.0s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:10] {3166} INFO - iteration 89, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:10] {3343} INFO -  at 20.2s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:10] {3166} INFO - iteration 90, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:10] {3343} INFO -  at 20.4s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:10] {3166} INFO - iteration 91, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:10] {3343} INFO -  at 20.6s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:10] {3166} INFO - iteration 92, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:10] {3343} INFO -  at 20.8s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:10] {3166} INFO - iteration 93, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:10] {3343} INFO -  at 21.0s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:10] {3166} INFO - iteration 94, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:11] {3343} INFO -  at 21.2s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:11] {3166} INFO - iteration 95, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:11] {3343} INFO -  at 21.4s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:11] {3166} INFO - iteration 96, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:11] {3343} INFO -  at 21.5s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:11] {3166} INFO - iteration 97, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:11] {3343} INFO -  at 21.8s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:11] {3166} INFO - iteration 98, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:11] {3343} INFO -  at 21.9s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:11] {3166} INFO - iteration 99, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:12] {3343} INFO -  at 22.1s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:12] {3166} INFO - iteration 100, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:12] {3343} INFO -  at 22.5s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:12] {3166} INFO - iteration 101, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:12] {3343} INFO -  at 22.7s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:12] {3166} INFO - iteration 102, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:12] {3343} INFO -  at 23.0s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:12] {3166} INFO - iteration 103, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:13] {3343} INFO -  at 23.2s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:13] {3166} INFO - iteration 104, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:13] {3343} INFO -  at 23.4s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:13] {3166} INFO - iteration 105, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:13] {3343} INFO -  at 23.8s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:13] {3166} INFO - iteration 106, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:14] {3343} INFO -  at 24.1s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:14] {3166} INFO - iteration 107, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:14] {3343} INFO -  at 24.6s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:14] {3166} INFO - iteration 108, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:14] {3343} INFO -  at 25.0s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:14] {3166} INFO - iteration 109, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:15] {3343} INFO -  at 25.5s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:15] {3166} INFO - iteration 110, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:15] {3343} INFO -  at 26.0s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:15] {3166} INFO - iteration 111, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:16] {3343} INFO -  at 26.3s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:16] {3166} INFO - iteration 112, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:16] {3343} INFO -  at 26.7s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:16] {3166} INFO - iteration 113, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:16] {3343} INFO -  at 26.8s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:16] {3166} INFO - iteration 114, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:16] {3343} INFO -  at 26.9s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:16] {3166} INFO - iteration 115, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:17] {3343} INFO -  at 27.1s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:17] {3166} INFO - iteration 116, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:17] {3343} INFO -  at 27.4s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:17] {3166} INFO - iteration 117, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:17] {3343} INFO -  at 27.6s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:17] {3166} INFO - iteration 118, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:17] {3343} INFO -  at 27.8s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:17] {3166} INFO - iteration 119, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:17] {3343} INFO -  at 28.0s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:17] {3166} INFO - iteration 120, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:18] {3343} INFO -  at 28.2s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:18] {3166} INFO - iteration 121, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:18] {3343} INFO -  at 28.4s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:18] {3166} INFO - iteration 122, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:18] {3343} INFO -  at 28.6s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:18] {3166} INFO - iteration 123, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:18] {3343} INFO -  at 28.7s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:18] {3166} INFO - iteration 124, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:18] {3343} INFO -  at 28.9s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:18] {3166} INFO - iteration 125, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:19] {3343} INFO -  at 29.1s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:19] {3166} INFO - iteration 126, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:19] {3343} INFO -  at 29.3s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:19] {3166} INFO - iteration 127, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:19] {3343} INFO -  at 29.5s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:19] {3166} INFO - iteration 128, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:19] {3343} INFO -  at 29.7s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835

[flaml.automl: 04-23 11:15:19] {3166} INFO - iteration 129, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:19] {3343} INFO -  at 29.8s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:19] {3166} INFO - iteration 130, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:19] {3343} INFO -  at 30.0s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:19] {3166} INFO - iteration 131, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:20] {3343} INFO -  at 30.1s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:20] {3166} INFO - iteration 132, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:20] {3343} INFO -  at 30.2s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:20] {3166} INFO - iteration 133, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:20] {3343} INFO -  at 30.5s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:20] {3166} INFO - iteration 134, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:20] {3343} INFO -  at 30.8s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:20] {3166} INFO - iteration 135, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:20] {3343} INFO -  at 30.9s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:20] {3166} INFO - iteration 136, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:21] {3343} INFO -  at 31.2s,	estimator rf's best error=90.0835,	best estimator rf's best error=90.0835
[flaml.automl: 04-23 11:15:21] {3166} INFO - iteration 137, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:21] {3343} INFO -  at 31.4s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:21] {3166} INFO - iteration 138, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:21] {3343} INFO -  at 31.6s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:21] {3166} INFO - iteration 139, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:21] {3343} INFO -  at 31.7s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:21] {3166} INFO - iteration 140, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:21] {3343} INFO -  at 31.8s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:21] {3166} INFO - iteration 141, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:21] {3343} INFO -  at 32.0s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:21] {3166} INFO - iteration 142, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:22] {3343} INFO -  at 32.1s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:22] {3166} INFO - iteration 143, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:22] {3343} INFO -  at 32.3s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:22] {3166} INFO - iteration 144, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:22] {3343} INFO -  at 32.4s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:22] {3166} INFO - iteration 145, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:22] {3343} INFO -  at 32.6s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:22] {3166} INFO - iteration 146, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:22] {3343} INFO -  at 32.8s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:22] {3166} INFO - iteration 147, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:22] {3343} INFO -  at 32.9s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:22] {3166} INFO - iteration 148, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:23] {3343} INFO -  at 33.1s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:23] {3166} INFO - iteration 149, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:23] {3343} INFO -  at 33.5s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:23] {3166} INFO - iteration 150, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:23] {3343} INFO -  at 33.8s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:23] {3166} INFO - iteration 151, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:23] {3343} INFO -  at 34.0s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:24] {3166} INFO - iteration 152, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:24] {3343} INFO -  at 34.2s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:24] {3166} INFO - iteration 153, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:24] {3343} INFO -  at 34.3s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:24] {3166} INFO - iteration 154, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:24] {3343} INFO -  at 34.5s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:24] {3166} INFO - iteration 155, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:24] {3343} INFO -  at 34.7s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:24] {3166} INFO - iteration 156, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:24] {3343} INFO -  at 34.8s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:24] {3166} INFO - iteration 157, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:24] {3343} INFO -  at 34.9s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:24] {3166} INFO - iteration 158, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:25] {3343} INFO -  at 35.1s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:25] {3166} INFO - iteration 159, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:25] {3343} INFO -  at 35.2s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:25] {3166} INFO - iteration 160, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:25] {3343} INFO -  at 35.3s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:25] {3166} INFO - iteration 161, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:25] {3343} INFO -  at 35.4s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:25] {3166} INFO - iteration 162, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:25] {3343} INFO -  at 35.6s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:25] {3166} INFO - iteration 163, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:25] {3343} INFO -  at 35.7s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:25] {3166} INFO - iteration 164, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:25] {3343} INFO -  at 35.9s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:25] {3166} INFO - iteration 165, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:26] {3343} INFO -  at 36.0s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:26] {3166} INFO - iteration 166, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:26] {3343} INFO -  at 36.2s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:26] {3166} INFO - iteration 167, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:26] {3343} INFO -  at 36.3s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:26] {3166} INFO - iteration 168, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:26] {3343} INFO -  at 36.6s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:26] {3166} INFO - iteration 169, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:26] {3343} INFO -  at 36.7s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:26] {3166} INFO - iteration 170, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:26] {3343} INFO -  at 36.9s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:26] {3166} INFO - iteration 171, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:27] {3343} INFO -  at 37.1s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:27] {3166} INFO - iteration 172, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:27] {3343} INFO -  at 37.2s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:27] {3166} INFO - iteration 173, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:27] {3343} INFO -  at 37.3s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:27] {3166} INFO - iteration 174, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:27] {3343} INFO -  at 37.4s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:27] {3166} INFO - iteration 175, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:27] {3343} INFO -  at 37.5s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:27] {3166} INFO - iteration 176, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:27] {3343} INFO -  at 37.6s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:27] {3166} INFO - iteration 177, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:27] {3343} INFO -  at 37.9s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:27] {3166} INFO - iteration 178, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:28] {3343} INFO -  at 38.1s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:28] {3166} INFO - iteration 179, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:28] {3343} INFO -  at 38.3s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:28] {3166} INFO - iteration 180, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:28] {3343} INFO -  at 38.4s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:28] {3166} INFO - iteration 181, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:28] {3343} INFO -  at 38.6s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:28] {3166} INFO - iteration 182, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:28] {3343} INFO -  at 38.7s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:28] {3166} INFO - iteration 183, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:28] {3343} INFO -  at 38.9s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:28] {3166} INFO - iteration 184, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:29] {3343} INFO -  at 39.1s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:29] {3166} INFO - iteration 185, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:29] {3343} INFO -  at 39.3s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:29] {3166} INFO - iteration 186, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:29] {3343} INFO -  at 39.4s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:29] {3166} INFO - iteration 187, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:29] {3343} INFO -  at 39.6s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:29] {3166} INFO - iteration 188, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:29] {3343} INFO -  at 39.8s,	estimator rf's best error=88.7035,	best estimator rf's best error=88.7035
[flaml.automl: 04-23 11:15:29] {3166} INFO - iteration 189, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:30] {3343} INFO -  at 40.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:30] {3166} INFO - iteration 190, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:30] {3343} INFO -  at 40.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:30] {3166} INFO - iteration 191, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:30] {3343} INFO -  at 40.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:30] {3166} INFO - iteration 192, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:30] {3343} INFO -  at 40.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:30] {3166} INFO - iteration 193, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:30] {3343} INFO -  at 40.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324

[flaml.automl: 04-23 11:15:30] {3166} INFO - iteration 194, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:31] {3343} INFO -  at 41.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:31] {3166} INFO - iteration 195, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:31] {3343} INFO -  at 41.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:31] {3166} INFO - iteration 196, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:31] {3343} INFO -  at 41.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:31] {3166} INFO - iteration 197, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:31] {3343} INFO -  at 41.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:31] {3166} INFO - iteration 198, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:31] {3343} INFO -  at 41.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:31] {3166} INFO - iteration 199, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:31] {3343} INFO -  at 42.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:31] {3166} INFO - iteration 200, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:32] {3343} INFO -  at 42.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:32] {3166} INFO - iteration 201, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:32] {3343} INFO -  at 42.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:32] {3166} INFO - iteration 202, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:32] {3343} INFO -  at 42.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:32] {3166} INFO - iteration 203, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:32] {3343} INFO -  at 42.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:32] {3166} INFO - iteration 204, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:32] {3343} INFO -  at 42.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:32] {3166} INFO - iteration 205, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:32] {3343} INFO -  at 42.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:32] {3166} INFO - iteration 206, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:32] {3343} INFO -  at 43.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:32] {3166} INFO - iteration 207, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:33] {3343} INFO -  at 43.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:33] {3166} INFO - iteration 208, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:33] {3343} INFO -  at 43.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:33] {3166} INFO - iteration 209, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:33] {3343} INFO -  at 43.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:33] {3166} INFO - iteration 210, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:33] {3343} INFO -  at 43.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:33] {3166} INFO - iteration 211, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:33] {3343} INFO -  at 43.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:33] {3166} INFO - iteration 212, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:34] {3343} INFO -  at 44.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:34] {3166} INFO - iteration 213, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:34] {3343} INFO -  at 44.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:34] {3166} INFO - iteration 214, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:34] {3343} INFO -  at 44.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:34] {3166} INFO - iteration 215, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:34] {3343} INFO -  at 44.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:34] {3166} INFO - iteration 216, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:34] {3343} INFO -  at 44.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:34] {3166} INFO - iteration 217, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:34] {3343} INFO -  at 45.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:34] {3166} INFO - iteration 218, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:35] {3343} INFO -  at 45.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:35] {3166} INFO - iteration 219, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:35] {3343} INFO -  at 45.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:35] {3166} INFO - iteration 220, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:35] {3343} INFO -  at 45.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:35] {3166} INFO - iteration 221, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:35] {3343} INFO -  at 45.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:35] {3166} INFO - iteration 222, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:35] {3343} INFO -  at 45.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:35] {3166} INFO - iteration 223, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:36] {3343} INFO -  at 46.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:36] {3166} INFO - iteration 224, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:36] {3343} INFO -  at 46.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:36] {3166} INFO - iteration 225, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:36] {3343} INFO -  at 46.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:36] {3166} INFO - iteration 226, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:36] {3343} INFO -  at 46.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:36] {3166} INFO - iteration 227, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:36] {3343} INFO -  at 46.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:36] {3166} INFO - iteration 228, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:36] {3343} INFO -  at 46.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:36] {3166} INFO - iteration 229, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:36] {3343} INFO -  at 47.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:36] {3166} INFO - iteration 230, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:37] {3343} INFO -  at 47.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:37] {3166} INFO - iteration 231, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:37] {3343} INFO -  at 47.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:37] {3166} INFO - iteration 232, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:37] {3343} INFO -  at 47.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:37] {3166} INFO - iteration 233, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:37] {3343} INFO -  at 47.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:37] {3166} INFO - iteration 234, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:37] {3343} INFO -  at 47.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:37] {3166} INFO - iteration 235, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:38] {3343} INFO -  at 48.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:38] {3166} INFO - iteration 236, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:38] {3343} INFO -  at 48.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:38] {3166} INFO - iteration 237, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:38] {3343} INFO -  at 48.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:38] {3166} INFO - iteration 238, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:38] {3343} INFO -  at 48.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:38] {3166} INFO - iteration 239, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:38] {3343} INFO -  at 48.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:38] {3166} INFO - iteration 240, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:38] {3343} INFO -  at 49.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:38] {3166} INFO - iteration 241, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:39] {3343} INFO -  at 49.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:39] {3166} INFO - iteration 242, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:39] {3343} INFO -  at 49.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:39] {3166} INFO - iteration 243, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:39] {3343} INFO -  at 49.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:39] {3166} INFO - iteration 244, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:39] {3343} INFO -  at 49.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:39] {3166} INFO - iteration 245, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:39] {3343} INFO -  at 49.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:39] {3166} INFO - iteration 246, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:40] {3343} INFO -  at 50.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:40] {3166} INFO - iteration 247, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:40] {3343} INFO -  at 50.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:40] {3166} INFO - iteration 248, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:40] {3343} INFO -  at 50.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:40] {3166} INFO - iteration 249, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:40] {3343} INFO -  at 50.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:40] {3166} INFO - iteration 250, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:41] {3343} INFO -  at 51.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:41] {3166} INFO - iteration 251, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:41] {3343} INFO -  at 51.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:41] {3166} INFO - iteration 252, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:41] {3343} INFO -  at 51.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:41] {3166} INFO - iteration 253, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:42] {3343} INFO -  at 52.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:42] {3166} INFO - iteration 254, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:42] {3343} INFO -  at 52.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:42] {3166} INFO - iteration 255, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:42] {3343} INFO -  at 52.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:42] {3166} INFO - iteration 256, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:42] {3343} INFO -  at 52.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:42] {3166} INFO - iteration 257, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:43] {3343} INFO -  at 53.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:43] {3166} INFO - iteration 258, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:43] {3343} INFO -  at 53.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:43] {3166} INFO - iteration 259, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:43] {3343} INFO -  at 53.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:43] {3166} INFO - iteration 260, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:43] {3343} INFO -  at 53.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:43] {3166} INFO - iteration 261, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:43] {3343} INFO -  at 53.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:43] {3166} INFO - iteration 262, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:44] {3343} INFO -  at 54.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:44] {3166} INFO - iteration 263, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:44] {3343} INFO -  at 54.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:44] {3166} INFO - iteration 264, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:44] {3343} INFO -  at 54.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:44] {3166} INFO - iteration 265, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:44] {3343} INFO -  at 54.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:44] {3166} INFO - iteration 266, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:44] {3343} INFO -  at 54.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:44] {3166} INFO - iteration 267, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:45] {3343} INFO -  at 55.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:45] {3166} INFO - iteration 268, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:45] {3343} INFO -  at 55.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:45] {3166} INFO - iteration 269, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:45] {3343} INFO -  at 55.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:45] {3166} INFO - iteration 270, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:45] {3343} INFO -  at 55.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:45] {3166} INFO - iteration 271, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:45] {3343} INFO -  at 55.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:45] {3166} INFO - iteration 272, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:45] {3343} INFO -  at 55.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:45] {3166} INFO - iteration 273, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:46] {3343} INFO -  at 56.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:46] {3166} INFO - iteration 274, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:46] {3343} INFO -  at 56.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:46] {3166} INFO - iteration 275, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:46] {3343} INFO -  at 56.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:46] {3166} INFO - iteration 276, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:46] {3343} INFO -  at 56.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:46] {3166} INFO - iteration 277, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:46] {3343} INFO -  at 57.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:46] {3166} INFO - iteration 278, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:47] {3343} INFO -  at 57.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:47] {3166} INFO - iteration 279, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:47] {3343} INFO -  at 57.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:47] {3166} INFO - iteration 280, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:47] {3343} INFO -  at 57.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:47] {3166} INFO - iteration 281, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:48] {3343} INFO -  at 58.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:48] {3166} INFO - iteration 282, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:48] {3343} INFO -  at 58.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:48] {3166} INFO - iteration 283, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:48] {3343} INFO -  at 58.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:48] {3166} INFO - iteration 284, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:48] {3343} INFO -  at 58.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:48] {3166} INFO - iteration 285, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:49] {3343} INFO -  at 59.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:49] {3166} INFO - iteration 286, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:49] {3343} INFO -  at 59.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:49] {3166} INFO - iteration 287, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:49] {3343} INFO -  at 59.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:49] {3166} INFO - iteration 288, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:49] {3343} INFO -  at 60.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:49] {3166} INFO - iteration 289, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:50] {3343} INFO -  at 60.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:50] {3166} INFO - iteration 290, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:50] {3343} INFO -  at 60.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:50] {3166} INFO - iteration 291, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:50] {3343} INFO -  at 60.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:50] {3166} INFO - iteration 292, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:51] {3343} INFO -  at 61.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:51] {3166} INFO - iteration 293, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:51] {3343} INFO -  at 61.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:51] {3166} INFO - iteration 294, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:51] {3343} INFO -  at 61.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:51] {3166} INFO - iteration 295, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:51] {3343} INFO -  at 61.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:51] {3166} INFO - iteration 296, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:51] {3343} INFO -  at 61.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:51] {3166} INFO - iteration 297, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:51] {3343} INFO -  at 62.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:51] {3166} INFO - iteration 298, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:52] {3343} INFO -  at 62.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:52] {3166} INFO - iteration 299, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:52] {3343} INFO -  at 62.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:52] {3166} INFO - iteration 300, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:52] {3343} INFO -  at 62.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:52] {3166} INFO - iteration 301, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:52] {3343} INFO -  at 62.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:52] {3166} INFO - iteration 302, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:52] {3343} INFO -  at 62.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:52] {3166} INFO - iteration 303, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:52] {3343} INFO -  at 62.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:52] {3166} INFO - iteration 304, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:53] {3343} INFO -  at 63.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:53] {3166} INFO - iteration 305, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:53] {3343} INFO -  at 63.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:53] {3166} INFO - iteration 306, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:53] {3343} INFO -  at 63.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:53] {3166} INFO - iteration 307, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:53] {3343} INFO -  at 63.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:53] {3166} INFO - iteration 308, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:53] {3343} INFO -  at 63.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:53] {3166} INFO - iteration 309, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:54] {3343} INFO -  at 64.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:54] {3166} INFO - iteration 310, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:54] {3343} INFO -  at 64.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:54] {3166} INFO - iteration 311, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:54] {3343} INFO -  at 64.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:54] {3166} INFO - iteration 312, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:54] {3343} INFO -  at 64.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:54] {3166} INFO - iteration 313, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:54] {3343} INFO -  at 64.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:54] {3166} INFO - iteration 314, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:54] {3343} INFO -  at 65.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:54] {3166} INFO - iteration 315, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:55] {3343} INFO -  at 65.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:55] {3166} INFO - iteration 316, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:55] {3343} INFO -  at 65.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:55] {3166} INFO - iteration 317, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:55] {3343} INFO -  at 65.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:55] {3166} INFO - iteration 318, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:55] {3343} INFO -  at 65.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:55] {3166} INFO - iteration 319, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:55] {3343} INFO -  at 65.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:55] {3166} INFO - iteration 320, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:55] {3343} INFO -  at 65.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:55] {3166} INFO - iteration 321, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:56] {3343} INFO -  at 66.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:56] {3166} INFO - iteration 322, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:56] {3343} INFO -  at 66.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:56] {3166} INFO - iteration 323, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:56] {3343} INFO -  at 66.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:56] {3166} INFO - iteration 324, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:56] {3343} INFO -  at 66.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:56] {3166} INFO - iteration 325, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:56] {3343} INFO -  at 66.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:56] {3166} INFO - iteration 326, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:56] {3343} INFO -  at 66.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:56] {3166} INFO - iteration 327, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:57] {3343} INFO -  at 67.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:57] {3166} INFO - iteration 328, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:57] {3343} INFO -  at 67.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:57] {3166} INFO - iteration 329, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:57] {3343} INFO -  at 67.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:57] {3166} INFO - iteration 330, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:57] {3343} INFO -  at 67.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:57] {3166} INFO - iteration 331, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:57] {3343} INFO -  at 67.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:57] {3166} INFO - iteration 332, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:57] {3343} INFO -  at 67.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:57] {3166} INFO - iteration 333, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:57] {3343} INFO -  at 67.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:57] {3166} INFO - iteration 334, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:58] {3343} INFO -  at 68.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:58] {3166} INFO - iteration 335, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:58] {3343} INFO -  at 68.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:58] {3166} INFO - iteration 336, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:58] {3343} INFO -  at 68.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:58] {3166} INFO - iteration 337, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:58] {3343} INFO -  at 68.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:58] {3166} INFO - iteration 338, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:58] {3343} INFO -  at 68.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:58] {3166} INFO - iteration 339, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:58] {3343} INFO -  at 68.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:58] {3166} INFO - iteration 340, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:58] {3343} INFO -  at 68.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:58] {3166} INFO - iteration 341, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:58] {3343} INFO -  at 68.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:58] {3166} INFO - iteration 342, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:59] {3343} INFO -  at 69.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:59] {3166} INFO - iteration 343, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:59] {3343} INFO -  at 69.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:59] {3166} INFO - iteration 344, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:59] {3343} INFO -  at 69.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:59] {3166} INFO - iteration 345, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:59] {3343} INFO -  at 69.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:59] {3166} INFO - iteration 346, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:59] {3343} INFO -  at 69.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:59] {3166} INFO - iteration 347, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:59] {3343} INFO -  at 69.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:59] {3166} INFO - iteration 348, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:15:59] {3343} INFO -  at 69.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:59] {3166} INFO - iteration 349, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:15:59] {3343} INFO -  at 69.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:15:59] {3166} INFO - iteration 350, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:00] {3343} INFO -  at 70.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:00] {3166} INFO - iteration 351, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:00] {3343} INFO -  at 70.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:00] {3166} INFO - iteration 352, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:00] {3343} INFO -  at 70.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:00] {3166} INFO - iteration 353, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:00] {3343} INFO -  at 70.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:00] {3166} INFO - iteration 354, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:00] {3343} INFO -  at 70.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:00] {3166} INFO - iteration 355, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:00] {3343} INFO -  at 70.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:00] {3166} INFO - iteration 356, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:00] {3343} INFO -  at 70.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:00] {3166} INFO - iteration 357, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:00] {3343} INFO -  at 70.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:00] {3166} INFO - iteration 358, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:01] {3343} INFO -  at 71.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:01] {3166} INFO - iteration 359, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:01] {3343} INFO -  at 71.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:01] {3166} INFO - iteration 360, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:01] {3343} INFO -  at 71.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:01] {3166} INFO - iteration 361, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:01] {3343} INFO -  at 71.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:01] {3166} INFO - iteration 362, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:01] {3343} INFO -  at 71.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:01] {3166} INFO - iteration 363, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:01] {3343} INFO -  at 71.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:01] {3166} INFO - iteration 364, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:01] {3343} INFO -  at 71.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:01] {3166} INFO - iteration 365, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:01] {3343} INFO -  at 72.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:01] {3166} INFO - iteration 366, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:02] {3343} INFO -  at 72.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:02] {3166} INFO - iteration 367, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:02] {3343} INFO -  at 72.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:02] {3166} INFO - iteration 368, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:02] {3343} INFO -  at 72.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:02] {3166} INFO - iteration 369, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:02] {3343} INFO -  at 72.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:02] {3166} INFO - iteration 370, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:02] {3343} INFO -  at 72.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:02] {3166} INFO - iteration 371, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:02] {3343} INFO -  at 73.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:02] {3166} INFO - iteration 372, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:03] {3343} INFO -  at 73.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:03] {3166} INFO - iteration 373, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:03] {3343} INFO -  at 73.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:03] {3166} INFO - iteration 374, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:03] {3343} INFO -  at 73.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:03] {3166} INFO - iteration 375, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:03] {3343} INFO -  at 73.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:03] {3166} INFO - iteration 376, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:03] {3343} INFO -  at 73.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:03] {3166} INFO - iteration 377, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:03] {3343} INFO -  at 74.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:03] {3166} INFO - iteration 378, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:04] {3343} INFO -  at 74.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:04] {3166} INFO - iteration 379, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:04] {3343} INFO -  at 74.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:04] {3166} INFO - iteration 380, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:04] {3343} INFO -  at 74.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:04] {3166} INFO - iteration 381, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:04] {3343} INFO -  at 74.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:04] {3166} INFO - iteration 382, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:05] {3343} INFO -  at 75.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:05] {3166} INFO - iteration 383, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:05] {3343} INFO -  at 75.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:05] {3166} INFO - iteration 384, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:05] {3343} INFO -  at 75.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:05] {3166} INFO - iteration 385, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:05] {3343} INFO -  at 75.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:05] {3166} INFO - iteration 386, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:05] {3343} INFO -  at 75.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:05] {3166} INFO - iteration 387, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:05] {3343} INFO -  at 76.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:05] {3166} INFO - iteration 388, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:06] {3343} INFO -  at 76.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:06] {3166} INFO - iteration 389, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:06] {3343} INFO -  at 76.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:06] {3166} INFO - iteration 390, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:06] {3343} INFO -  at 76.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:06] {3166} INFO - iteration 391, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:06] {3343} INFO -  at 76.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:06] {3166} INFO - iteration 392, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:06] {3343} INFO -  at 76.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:06] {3166} INFO - iteration 393, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:06] {3343} INFO -  at 76.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:06] {3166} INFO - iteration 394, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:06] {3343} INFO -  at 76.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:06] {3166} INFO - iteration 395, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:07] {3343} INFO -  at 77.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:07] {3166} INFO - iteration 396, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:07] {3343} INFO -  at 77.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:07] {3166} INFO - iteration 397, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:07] {3343} INFO -  at 77.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:07] {3166} INFO - iteration 398, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:07] {3343} INFO -  at 77.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:07] {3166} INFO - iteration 399, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:07] {3343} INFO -  at 77.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:07] {3166} INFO - iteration 400, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:07] {3343} INFO -  at 77.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:07] {3166} INFO - iteration 401, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:07] {3343} INFO -  at 77.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:07] {3166} INFO - iteration 402, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:08] {3343} INFO -  at 78.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:08] {3166} INFO - iteration 403, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:08] {3343} INFO -  at 78.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:08] {3166} INFO - iteration 404, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:08] {3343} INFO -  at 78.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:08] {3166} INFO - iteration 405, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:08] {3343} INFO -  at 78.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:08] {3166} INFO - iteration 406, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:08] {3343} INFO -  at 78.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:08] {3166} INFO - iteration 407, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:08] {3343} INFO -  at 78.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:08] {3166} INFO - iteration 408, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:08] {3343} INFO -  at 79.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:08] {3166} INFO - iteration 409, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:09] {3343} INFO -  at 79.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:09] {3166} INFO - iteration 410, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:09] {3343} INFO -  at 79.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:09] {3166} INFO - iteration 411, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:09] {3343} INFO -  at 79.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:09] {3166} INFO - iteration 412, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:09] {3343} INFO -  at 79.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:09] {3166} INFO - iteration 413, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:10] {3343} INFO -  at 80.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:10] {3166} INFO - iteration 414, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:10] {3343} INFO -  at 80.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:10] {3166} INFO - iteration 415, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:10] {3343} INFO -  at 80.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:10] {3166} INFO - iteration 416, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:10] {3343} INFO -  at 81.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:10] {3166} INFO - iteration 417, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:11] {3343} INFO -  at 81.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:11] {3166} INFO - iteration 418, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:11] {3343} INFO -  at 81.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:11] {3166} INFO - iteration 419, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:11] {3343} INFO -  at 81.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:11] {3166} INFO - iteration 420, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:11] {3343} INFO -  at 81.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:11] {3166} INFO - iteration 421, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:11] {3343} INFO -  at 81.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:11] {3166} INFO - iteration 422, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:12] {3343} INFO -  at 82.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:12] {3166} INFO - iteration 423, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:12] {3343} INFO -  at 82.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:12] {3166} INFO - iteration 424, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:12] {3343} INFO -  at 82.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:12] {3166} INFO - iteration 425, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:12] {3343} INFO -  at 82.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:12] {3166} INFO - iteration 426, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:12] {3343} INFO -  at 82.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:12] {3166} INFO - iteration 427, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:12] {3343} INFO -  at 82.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:12] {3166} INFO - iteration 428, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:12] {3343} INFO -  at 82.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:12] {3166} INFO - iteration 429, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:13] {3343} INFO -  at 83.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:13] {3166} INFO - iteration 430, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:13] {3343} INFO -  at 83.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:13] {3166} INFO - iteration 431, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:13] {3343} INFO -  at 83.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:13] {3166} INFO - iteration 432, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:13] {3343} INFO -  at 84.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:13] {3166} INFO - iteration 433, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:14] {3343} INFO -  at 84.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:14] {3166} INFO - iteration 434, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:14] {3343} INFO -  at 84.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:14] {3166} INFO - iteration 435, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:14] {3343} INFO -  at 84.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:14] {3166} INFO - iteration 436, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:14] {3343} INFO -  at 84.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:14] {3166} INFO - iteration 437, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:15] {3343} INFO -  at 85.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:15] {3166} INFO - iteration 438, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:15] {3343} INFO -  at 85.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:15] {3166} INFO - iteration 439, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:15] {3343} INFO -  at 85.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:15] {3166} INFO - iteration 440, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:16] {3343} INFO -  at 86.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:16] {3166} INFO - iteration 441, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:16] {3343} INFO -  at 86.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:16] {3166} INFO - iteration 442, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:16] {3343} INFO -  at 86.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:16] {3166} INFO - iteration 443, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:16] {3343} INFO -  at 86.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:16] {3166} INFO - iteration 444, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:17] {3343} INFO -  at 87.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:17] {3166} INFO - iteration 445, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:17] {3343} INFO -  at 87.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:17] {3166} INFO - iteration 446, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:17] {3343} INFO -  at 87.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:17] {3166} INFO - iteration 447, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:17] {3343} INFO -  at 87.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:17] {3166} INFO - iteration 448, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:18] {3343} INFO -  at 88.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:18] {3166} INFO - iteration 449, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:18] {3343} INFO -  at 88.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:18] {3166} INFO - iteration 450, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:18] {3343} INFO -  at 88.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:18] {3166} INFO - iteration 451, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:18] {3343} INFO -  at 88.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:18] {3166} INFO - iteration 452, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:18] {3343} INFO -  at 88.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:18] {3166} INFO - iteration 453, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:18] {3343} INFO -  at 88.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:18] {3166} INFO - iteration 454, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:19] {3343} INFO -  at 89.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:19] {3166} INFO - iteration 455, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:19] {3343} INFO -  at 89.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:19] {3166} INFO - iteration 456, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:19] {3343} INFO -  at 89.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:19] {3166} INFO - iteration 457, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:19] {3343} INFO -  at 89.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:19] {3166} INFO - iteration 458, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:19] {3343} INFO -  at 89.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:19] {3166} INFO - iteration 459, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:19] {3343} INFO -  at 89.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:19] {3166} INFO - iteration 460, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:19] {3343} INFO -  at 90.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:20] {3166} INFO - iteration 461, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:20] {3343} INFO -  at 90.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:20] {3166} INFO - iteration 462, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:20] {3343} INFO -  at 90.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:20] {3166} INFO - iteration 463, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:20] {3343} INFO -  at 90.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:20] {3166} INFO - iteration 464, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:20] {3343} INFO -  at 90.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:20] {3166} INFO - iteration 465, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:20] {3343} INFO -  at 90.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:20] {3166} INFO - iteration 466, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:20] {3343} INFO -  at 90.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:20] {3166} INFO - iteration 467, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:21] {3343} INFO -  at 91.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:21] {3166} INFO - iteration 468, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:21] {3343} INFO -  at 91.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:21] {3166} INFO - iteration 469, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:21] {3343} INFO -  at 91.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:21] {3166} INFO - iteration 470, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:21] {3343} INFO -  at 91.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:21] {3166} INFO - iteration 471, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:21] {3343} INFO -  at 91.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:21] {3166} INFO - iteration 472, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:22] {3343} INFO -  at 92.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:22] {3166} INFO - iteration 473, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:22] {3343} INFO -  at 92.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:22] {3166} INFO - iteration 474, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:22] {3343} INFO -  at 92.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:22] {3166} INFO - iteration 475, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:22] {3343} INFO -  at 92.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:22] {3166} INFO - iteration 476, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:22] {3343} INFO -  at 92.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:22] {3166} INFO - iteration 477, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:22] {3343} INFO -  at 92.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:22] {3166} INFO - iteration 478, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:22] {3343} INFO -  at 93.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:22] {3166} INFO - iteration 479, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:23] {3343} INFO -  at 93.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:23] {3166} INFO - iteration 480, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:23] {3343} INFO -  at 93.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:23] {3166} INFO - iteration 481, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:23] {3343} INFO -  at 93.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:23] {3166} INFO - iteration 482, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:23] {3343} INFO -  at 93.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:23] {3166} INFO - iteration 483, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:24] {3343} INFO -  at 94.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:24] {3166} INFO - iteration 484, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:24] {3343} INFO -  at 94.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:24] {3166} INFO - iteration 485, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:24] {3343} INFO -  at 94.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:24] {3166} INFO - iteration 486, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:24] {3343} INFO -  at 94.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:24] {3166} INFO - iteration 487, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:24] {3343} INFO -  at 94.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:24] {3166} INFO - iteration 488, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:24] {3343} INFO -  at 95.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:24] {3166} INFO - iteration 489, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:25] {3343} INFO -  at 95.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:25] {3166} INFO - iteration 490, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:25] {3343} INFO -  at 95.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:25] {3166} INFO - iteration 491, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:25] {3343} INFO -  at 95.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:25] {3166} INFO - iteration 492, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:25] {3343} INFO -  at 95.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:25] {3166} INFO - iteration 493, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:25] {3343} INFO -  at 95.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:25] {3166} INFO - iteration 494, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:25] {3343} INFO -  at 95.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:25] {3166} INFO - iteration 495, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:26] {3343} INFO -  at 96.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:26] {3166} INFO - iteration 496, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:26] {3343} INFO -  at 96.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:26] {3166} INFO - iteration 497, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:26] {3343} INFO -  at 96.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:26] {3166} INFO - iteration 498, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:26] {3343} INFO -  at 96.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:26] {3166} INFO - iteration 499, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:26] {3343} INFO -  at 96.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:26] {3166} INFO - iteration 500, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:26] {3343} INFO -  at 97.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:26] {3166} INFO - iteration 501, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:27] {3343} INFO -  at 97.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:27] {3166} INFO - iteration 502, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:27] {3343} INFO -  at 97.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:27] {3166} INFO - iteration 503, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:27] {3343} INFO -  at 97.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:27] {3166} INFO - iteration 504, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:27] {3343} INFO -  at 97.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:27] {3166} INFO - iteration 505, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:27] {3343} INFO -  at 97.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:27] {3166} INFO - iteration 506, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:27] {3343} INFO -  at 97.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:27] {3166} INFO - iteration 507, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:28] {3343} INFO -  at 98.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:28] {3166} INFO - iteration 508, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:28] {3343} INFO -  at 98.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:28] {3166} INFO - iteration 509, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:28] {3343} INFO -  at 98.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:28] {3166} INFO - iteration 510, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:28] {3343} INFO -  at 98.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:28] {3166} INFO - iteration 511, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:28] {3343} INFO -  at 98.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:28] {3166} INFO - iteration 512, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:29] {3343} INFO -  at 99.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:29] {3166} INFO - iteration 513, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:29] {3343} INFO -  at 99.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:29] {3166} INFO - iteration 514, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:29] {3343} INFO -  at 99.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:29] {3166} INFO - iteration 515, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:29] {3343} INFO -  at 99.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:29] {3166} INFO - iteration 516, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:29] {3343} INFO -  at 99.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:29] {3166} INFO - iteration 517, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:29] {3343} INFO -  at 99.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:29] {3166} INFO - iteration 518, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:29] {3343} INFO -  at 99.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:29] {3166} INFO - iteration 519, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:30] {3343} INFO -  at 100.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:30] {3166} INFO - iteration 520, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:30] {3343} INFO -  at 100.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:30] {3166} INFO - iteration 521, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:30] {3343} INFO -  at 100.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:30] {3166} INFO - iteration 522, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:30] {3343} INFO -  at 100.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:30] {3166} INFO - iteration 523, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:30] {3343} INFO -  at 100.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:30] {3166} INFO - iteration 524, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:30] {3343} INFO -  at 100.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:30] {3166} INFO - iteration 525, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:30] {3343} INFO -  at 100.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:30] {3166} INFO - iteration 526, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:31] {3343} INFO -  at 101.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:31] {3166} INFO - iteration 527, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:31] {3343} INFO -  at 101.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:31] {3166} INFO - iteration 528, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:31] {3343} INFO -  at 101.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:31] {3166} INFO - iteration 529, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:31] {3343} INFO -  at 101.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:31] {3166} INFO - iteration 530, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:31] {3343} INFO -  at 101.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:31] {3166} INFO - iteration 531, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:31] {3343} INFO -  at 101.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:31] {3166} INFO - iteration 532, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:31] {3343} INFO -  at 101.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:31] {3166} INFO - iteration 533, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:32] {3343} INFO -  at 102.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:32] {3166} INFO - iteration 534, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:32] {3343} INFO -  at 102.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:32] {3166} INFO - iteration 535, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:32] {3343} INFO -  at 102.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:32] {3166} INFO - iteration 536, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:32] {3343} INFO -  at 102.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:32] {3166} INFO - iteration 537, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:32] {3343} INFO -  at 102.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:32] {3166} INFO - iteration 538, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:32] {3343} INFO -  at 102.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:32] {3166} INFO - iteration 539, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:32] {3343} INFO -  at 102.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:32] {3166} INFO - iteration 540, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:32] {3343} INFO -  at 103.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:32] {3166} INFO - iteration 541, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:33] {3343} INFO -  at 103.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:33] {3166} INFO - iteration 542, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:33] {3343} INFO -  at 103.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:33] {3166} INFO - iteration 543, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:33] {3343} INFO -  at 103.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:33] {3166} INFO - iteration 544, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:33] {3343} INFO -  at 103.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:33] {3166} INFO - iteration 545, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:33] {3343} INFO -  at 103.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:33] {3166} INFO - iteration 546, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:34] {3343} INFO -  at 104.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:34] {3166} INFO - iteration 547, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:34] {3343} INFO -  at 104.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:34] {3166} INFO - iteration 548, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:34] {3343} INFO -  at 104.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:34] {3166} INFO - iteration 549, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:34] {3343} INFO -  at 104.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:34] {3166} INFO - iteration 550, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:35] {3343} INFO -  at 105.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:35] {3166} INFO - iteration 551, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:35] {3343} INFO -  at 105.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:35] {3166} INFO - iteration 552, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:36] {3343} INFO -  at 106.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:36] {3166} INFO - iteration 553, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:36] {3343} INFO -  at 106.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:36] {3166} INFO - iteration 554, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:36] {3343} INFO -  at 106.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:36] {3166} INFO - iteration 555, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:37] {3343} INFO -  at 107.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:37] {3166} INFO - iteration 556, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:37] {3343} INFO -  at 107.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:37] {3166} INFO - iteration 557, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:37] {3343} INFO -  at 107.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324

[flaml.automl: 04-23 11:16:37] {3166} INFO - iteration 558, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:37] {3343} INFO -  at 107.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:37] {3166} INFO - iteration 559, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:37] {3343} INFO -  at 107.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:37] {3166} INFO - iteration 560, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:38] {3343} INFO -  at 108.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:38] {3166} INFO - iteration 561, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:38] {3343} INFO -  at 108.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:38] {3166} INFO - iteration 562, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:38] {3343} INFO -  at 108.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:38] {3166} INFO - iteration 563, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:38] {3343} INFO -  at 108.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:38] {3166} INFO - iteration 564, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:38] {3343} INFO -  at 108.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:38] {3166} INFO - iteration 565, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:39] {3343} INFO -  at 109.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:39] {3166} INFO - iteration 566, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:39] {3343} INFO -  at 109.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:39] {3166} INFO - iteration 567, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:39] {3343} INFO -  at 109.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:39] {3166} INFO - iteration 568, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:39] {3343} INFO -  at 109.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:39] {3166} INFO - iteration 569, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:39] {3343} INFO -  at 109.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:39] {3166} INFO - iteration 570, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:39] {3343} INFO -  at 109.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:39] {3166} INFO - iteration 571, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:40] {3343} INFO -  at 110.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:40] {3166} INFO - iteration 572, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:40] {3343} INFO -  at 110.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:40] {3166} INFO - iteration 573, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:40] {3343} INFO -  at 110.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:40] {3166} INFO - iteration 574, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:40] {3343} INFO -  at 110.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:40] {3166} INFO - iteration 575, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:40] {3343} INFO -  at 110.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:40] {3166} INFO - iteration 576, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:40] {3343} INFO -  at 110.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:40] {3166} INFO - iteration 577, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:40] {3343} INFO -  at 111.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:40] {3166} INFO - iteration 578, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:41] {3343} INFO -  at 111.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:41] {3166} INFO - iteration 579, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:41] {3343} INFO -  at 111.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:41] {3166} INFO - iteration 580, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:41] {3343} INFO -  at 111.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:41] {3166} INFO - iteration 581, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:41] {3343} INFO -  at 111.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:41] {3166} INFO - iteration 582, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:41] {3343} INFO -  at 111.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:41] {3166} INFO - iteration 583, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:41] {3343} INFO -  at 111.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:41] {3166} INFO - iteration 584, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:42] {3343} INFO -  at 112.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:42] {3166} INFO - iteration 585, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:42] {3343} INFO -  at 112.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:42] {3166} INFO - iteration 586, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:42] {3343} INFO -  at 112.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:42] {3166} INFO - iteration 587, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:42] {3343} INFO -  at 112.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:42] {3166} INFO - iteration 588, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:43] {3343} INFO -  at 113.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:43] {3166} INFO - iteration 589, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:43] {3343} INFO -  at 113.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:43] {3166} INFO - iteration 590, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:43] {3343} INFO -  at 113.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:43] {3166} INFO - iteration 591, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:43] {3343} INFO -  at 113.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:43] {3166} INFO - iteration 592, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:44] {3343} INFO -  at 114.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:44] {3166} INFO - iteration 593, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:44] {3343} INFO -  at 114.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:44] {3166} INFO - iteration 594, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:44] {3343} INFO -  at 114.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:44] {3166} INFO - iteration 595, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:44] {3343} INFO -  at 114.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:44] {3166} INFO - iteration 596, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:44] {3343} INFO -  at 115.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:44] {3166} INFO - iteration 597, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:45] {3343} INFO -  at 115.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:45] {3166} INFO - iteration 598, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:45] {3343} INFO -  at 115.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:45] {3166} INFO - iteration 599, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:45] {3343} INFO -  at 115.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:45] {3166} INFO - iteration 600, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:45] {3343} INFO -  at 115.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:45] {3166} INFO - iteration 601, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:45] {3343} INFO -  at 115.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:45] {3166} INFO - iteration 602, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:45] {3343} INFO -  at 115.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:45] {3166} INFO - iteration 603, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:46] {3343} INFO -  at 116.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:46] {3166} INFO - iteration 604, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:46] {3343} INFO -  at 116.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:46] {3166} INFO - iteration 605, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:46] {3343} INFO -  at 116.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:46] {3166} INFO - iteration 606, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:46] {3343} INFO -  at 116.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:46] {3166} INFO - iteration 607, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:46] {3343} INFO -  at 116.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:46] {3166} INFO - iteration 608, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:46] {3343} INFO -  at 116.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:46] {3166} INFO - iteration 609, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:47] {3343} INFO -  at 117.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:47] {3166} INFO - iteration 610, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:47] {3343} INFO -  at 117.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:47] {3166} INFO - iteration 611, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:47] {3343} INFO -  at 117.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:47] {3166} INFO - iteration 612, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:47] {3343} INFO -  at 117.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:47] {3166} INFO - iteration 613, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:47] {3343} INFO -  at 117.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:47] {3166} INFO - iteration 614, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:47] {3343} INFO -  at 117.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:47] {3166} INFO - iteration 615, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:48] {3343} INFO -  at 118.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:48] {3166} INFO - iteration 616, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:48] {3343} INFO -  at 118.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:48] {3166} INFO - iteration 617, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:48] {3343} INFO -  at 118.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:48] {3166} INFO - iteration 618, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:48] {3343} INFO -  at 118.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:48] {3166} INFO - iteration 619, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:48] {3343} INFO -  at 118.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:48] {3166} INFO - iteration 620, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:48] {3343} INFO -  at 118.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:48] {3166} INFO - iteration 621, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:49] {3343} INFO -  at 119.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:49] {3166} INFO - iteration 622, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:49] {3343} INFO -  at 119.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:49] {3166} INFO - iteration 623, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:49] {3343} INFO -  at 119.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:49] {3166} INFO - iteration 624, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:49] {3343} INFO -  at 119.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:49] {3166} INFO - iteration 625, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:49] {3343} INFO -  at 119.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:49] {3166} INFO - iteration 626, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:49] {3343} INFO -  at 119.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:49] {3166} INFO - iteration 627, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:50] {3343} INFO -  at 120.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:50] {3166} INFO - iteration 628, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:50] {3343} INFO -  at 120.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:50] {3166} INFO - iteration 629, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:50] {3343} INFO -  at 120.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:50] {3166} INFO - iteration 630, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:50] {3343} INFO -  at 120.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:50] {3166} INFO - iteration 631, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:50] {3343} INFO -  at 120.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:50] {3166} INFO - iteration 632, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:50] {3343} INFO -  at 120.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:50] {3166} INFO - iteration 633, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:51] {3343} INFO -  at 121.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:51] {3166} INFO - iteration 634, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:51] {3343} INFO -  at 121.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:51] {3166} INFO - iteration 635, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:51] {3343} INFO -  at 121.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:51] {3166} INFO - iteration 636, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:51] {3343} INFO -  at 121.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:51] {3166} INFO - iteration 637, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:51] {3343} INFO -  at 121.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:51] {3166} INFO - iteration 638, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:51] {3343} INFO -  at 121.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:51] {3166} INFO - iteration 639, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:51] {3343} INFO -  at 122.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:51] {3166} INFO - iteration 640, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:52] {3343} INFO -  at 122.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:52] {3166} INFO - iteration 641, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:52] {3343} INFO -  at 122.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:52] {3166} INFO - iteration 642, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:52] {3343} INFO -  at 122.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:52] {3166} INFO - iteration 643, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:52] {3343} INFO -  at 122.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:52] {3166} INFO - iteration 644, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:53] {3343} INFO -  at 123.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:53] {3166} INFO - iteration 645, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:53] {3343} INFO -  at 123.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:53] {3166} INFO - iteration 646, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:53] {3343} INFO -  at 123.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:53] {3166} INFO - iteration 647, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:53] {3343} INFO -  at 123.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:53] {3166} INFO - iteration 648, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:53] {3343} INFO -  at 123.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324

[flaml.automl: 04-23 11:16:53] {3166} INFO - iteration 649, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:54] {3343} INFO -  at 124.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:54] {3166} INFO - iteration 650, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:54] {3343} INFO -  at 124.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:54] {3166} INFO - iteration 651, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:54] {3343} INFO -  at 124.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:54] {3166} INFO - iteration 652, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:54] {3343} INFO -  at 124.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:54] {3166} INFO - iteration 653, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:54] {3343} INFO -  at 124.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:54] {3166} INFO - iteration 654, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:54] {3343} INFO -  at 124.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:54] {3166} INFO - iteration 655, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:55] {3343} INFO -  at 125.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:55] {3166} INFO - iteration 656, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:55] {3343} INFO -  at 125.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:55] {3166} INFO - iteration 657, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:55] {3343} INFO -  at 125.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:55] {3166} INFO - iteration 658, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:55] {3343} INFO -  at 125.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:55] {3166} INFO - iteration 659, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:55] {3343} INFO -  at 125.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:55] {3166} INFO - iteration 660, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:56] {3343} INFO -  at 126.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:56] {3166} INFO - iteration 661, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:56] {3343} INFO -  at 126.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:56] {3166} INFO - iteration 662, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:56] {3343} INFO -  at 126.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:56] {3166} INFO - iteration 663, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:56] {3343} INFO -  at 126.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:56] {3166} INFO - iteration 664, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:56] {3343} INFO -  at 126.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:56] {3166} INFO - iteration 665, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:56] {3343} INFO -  at 127.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:57] {3166} INFO - iteration 666, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:57] {3343} INFO -  at 127.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:57] {3166} INFO - iteration 667, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:57] {3343} INFO -  at 127.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:57] {3166} INFO - iteration 668, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:57] {3343} INFO -  at 127.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:57] {3166} INFO - iteration 669, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:57] {3343} INFO -  at 127.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:57] {3166} INFO - iteration 670, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:58] {3343} INFO -  at 128.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:58] {3166} INFO - iteration 671, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:58] {3343} INFO -  at 128.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:58] {3166} INFO - iteration 672, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:58] {3343} INFO -  at 128.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:58] {3166} INFO - iteration 673, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:58] {3343} INFO -  at 128.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:58] {3166} INFO - iteration 674, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:16:58] {3343} INFO -  at 128.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:58] {3166} INFO - iteration 675, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:58] {3343} INFO -  at 128.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:58] {3166} INFO - iteration 676, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:58] {3343} INFO -  at 128.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:58] {3166} INFO - iteration 677, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:59] {3343} INFO -  at 129.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:59] {3166} INFO - iteration 678, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:59] {3343} INFO -  at 129.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:59] {3166} INFO - iteration 679, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:59] {3343} INFO -  at 129.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:59] {3166} INFO - iteration 680, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:59] {3343} INFO -  at 129.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:59] {3166} INFO - iteration 681, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:59] {3343} INFO -  at 129.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:59] {3166} INFO - iteration 682, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:59] {3343} INFO -  at 129.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:59] {3166} INFO - iteration 683, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:16:59] {3343} INFO -  at 129.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:16:59] {3166} INFO - iteration 684, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:00] {3343} INFO -  at 130.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:00] {3166} INFO - iteration 685, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:00] {3343} INFO -  at 130.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:00] {3166} INFO - iteration 686, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:00] {3343} INFO -  at 130.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:00] {3166} INFO - iteration 687, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:00] {3343} INFO -  at 130.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:00] {3166} INFO - iteration 688, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:00] {3343} INFO -  at 130.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:00] {3166} INFO - iteration 689, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:00] {3343} INFO -  at 130.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:00] {3166} INFO - iteration 690, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:01] {3343} INFO -  at 131.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:01] {3166} INFO - iteration 691, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:01] {3343} INFO -  at 131.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:01] {3166} INFO - iteration 692, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:01] {3343} INFO -  at 131.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:01] {3166} INFO - iteration 693, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:01] {3343} INFO -  at 131.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:01] {3166} INFO - iteration 694, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:01] {3343} INFO -  at 131.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:01] {3166} INFO - iteration 695, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:01] {3343} INFO -  at 132.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:01] {3166} INFO - iteration 696, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:02] {3343} INFO -  at 132.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:02] {3166} INFO - iteration 697, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:02] {3343} INFO -  at 132.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:02] {3166} INFO - iteration 698, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:02] {3343} INFO -  at 132.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:02] {3166} INFO - iteration 699, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:02] {3343} INFO -  at 132.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:02] {3166} INFO - iteration 700, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:02] {3343} INFO -  at 132.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:02] {3166} INFO - iteration 701, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:02] {3343} INFO -  at 132.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:02] {3166} INFO - iteration 702, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:02] {3343} INFO -  at 132.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:02] {3166} INFO - iteration 703, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:03] {3343} INFO -  at 133.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:03] {3166} INFO - iteration 704, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:03] {3343} INFO -  at 133.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:03] {3166} INFO - iteration 705, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:03] {3343} INFO -  at 133.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:03] {3166} INFO - iteration 706, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:03] {3343} INFO -  at 133.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:03] {3166} INFO - iteration 707, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:03] {3343} INFO -  at 133.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:03] {3166} INFO - iteration 708, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:03] {3343} INFO -  at 133.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:03] {3166} INFO - iteration 709, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:03] {3343} INFO -  at 133.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:03] {3166} INFO - iteration 710, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:04] {3343} INFO -  at 134.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:04] {3166} INFO - iteration 711, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:04] {3343} INFO -  at 134.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:04] {3166} INFO - iteration 712, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:04] {3343} INFO -  at 134.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:04] {3166} INFO - iteration 713, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:04] {3343} INFO -  at 134.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:04] {3166} INFO - iteration 714, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:04] {3343} INFO -  at 134.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:04] {3166} INFO - iteration 715, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:04] {3343} INFO -  at 134.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:04] {3166} INFO - iteration 716, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:04] {3343} INFO -  at 134.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:04] {3166} INFO - iteration 717, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:05] {3343} INFO -  at 135.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:05] {3166} INFO - iteration 718, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:05] {3343} INFO -  at 135.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:05] {3166} INFO - iteration 719, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:05] {3343} INFO -  at 135.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:05] {3166} INFO - iteration 720, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:05] {3343} INFO -  at 135.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:05] {3166} INFO - iteration 721, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:05] {3343} INFO -  at 135.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:05] {3166} INFO - iteration 722, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:05] {3343} INFO -  at 135.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:05] {3166} INFO - iteration 723, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:05] {3343} INFO -  at 135.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:05] {3166} INFO - iteration 724, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:05] {3343} INFO -  at 136.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:05] {3166} INFO - iteration 725, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:06] {3343} INFO -  at 136.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:06] {3166} INFO - iteration 726, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:06] {3343} INFO -  at 136.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:06] {3166} INFO - iteration 727, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:06] {3343} INFO -  at 136.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:06] {3166} INFO - iteration 728, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:06] {3343} INFO -  at 136.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:06] {3166} INFO - iteration 729, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:06] {3343} INFO -  at 136.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:06] {3166} INFO - iteration 730, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:06] {3343} INFO -  at 136.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:06] {3166} INFO - iteration 731, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:06] {3343} INFO -  at 137.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:06] {3166} INFO - iteration 732, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:07] {3343} INFO -  at 137.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:07] {3166} INFO - iteration 733, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:07] {3343} INFO -  at 137.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:07] {3166} INFO - iteration 734, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:07] {3343} INFO -  at 137.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:07] {3166} INFO - iteration 735, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:07] {3343} INFO -  at 137.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:07] {3166} INFO - iteration 736, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:07] {3343} INFO -  at 137.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:07] {3166} INFO - iteration 737, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:07] {3343} INFO -  at 137.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:07] {3166} INFO - iteration 738, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:08] {3343} INFO -  at 138.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:08] {3166} INFO - iteration 739, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:08] {3343} INFO -  at 138.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:08] {3166} INFO - iteration 740, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:08] {3343} INFO -  at 138.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:08] {3166} INFO - iteration 741, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:08] {3343} INFO -  at 138.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:08] {3166} INFO - iteration 742, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:08] {3343} INFO -  at 138.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:08] {3166} INFO - iteration 743, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:08] {3343} INFO -  at 138.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:08] {3166} INFO - iteration 744, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:08] {3343} INFO -  at 138.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:08] {3166} INFO - iteration 745, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:09] {3343} INFO -  at 139.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:09] {3166} INFO - iteration 746, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:09] {3343} INFO -  at 139.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:09] {3166} INFO - iteration 747, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:09] {3343} INFO -  at 139.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:09] {3166} INFO - iteration 748, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:09] {3343} INFO -  at 139.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:09] {3166} INFO - iteration 749, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:09] {3343} INFO -  at 139.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:09] {3166} INFO - iteration 750, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:09] {3343} INFO -  at 139.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:09] {3166} INFO - iteration 751, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:09] {3343} INFO -  at 139.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:09] {3166} INFO - iteration 752, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:10] {3343} INFO -  at 140.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:10] {3166} INFO - iteration 753, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:10] {3343} INFO -  at 140.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:10] {3166} INFO - iteration 754, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:10] {3343} INFO -  at 140.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:10] {3166} INFO - iteration 755, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:10] {3343} INFO -  at 140.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:10] {3166} INFO - iteration 756, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:10] {3343} INFO -  at 140.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:10] {3166} INFO - iteration 757, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:10] {3343} INFO -  at 140.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:10] {3166} INFO - iteration 758, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:10] {3343} INFO -  at 140.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:10] {3166} INFO - iteration 759, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:11] {3343} INFO -  at 141.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:11] {3166} INFO - iteration 760, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:11] {3343} INFO -  at 141.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:11] {3166} INFO - iteration 761, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:11] {3343} INFO -  at 141.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:11] {3166} INFO - iteration 762, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:11] {3343} INFO -  at 141.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:11] {3166} INFO - iteration 763, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:11] {3343} INFO -  at 141.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:11] {3166} INFO - iteration 764, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:11] {3343} INFO -  at 141.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:11] {3166} INFO - iteration 765, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:11] {3343} INFO -  at 141.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:11] {3166} INFO - iteration 766, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:12] {3343} INFO -  at 142.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:12] {3166} INFO - iteration 767, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:12] {3343} INFO -  at 142.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:12] {3166} INFO - iteration 768, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:12] {3343} INFO -  at 142.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:12] {3166} INFO - iteration 769, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:12] {3343} INFO -  at 142.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:12] {3166} INFO - iteration 770, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:12] {3343} INFO -  at 142.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:12] {3166} INFO - iteration 771, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:12] {3343} INFO -  at 142.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:12] {3166} INFO - iteration 772, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:12] {3343} INFO -  at 142.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:12] {3166} INFO - iteration 773, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:12] {3343} INFO -  at 143.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:12] {3166} INFO - iteration 774, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:13] {3343} INFO -  at 143.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:13] {3166} INFO - iteration 775, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:13] {3343} INFO -  at 143.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:13] {3166} INFO - iteration 776, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:13] {3343} INFO -  at 143.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:13] {3166} INFO - iteration 777, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:13] {3343} INFO -  at 143.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:13] {3166} INFO - iteration 778, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:13] {3343} INFO -  at 143.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:13] {3166} INFO - iteration 779, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:13] {3343} INFO -  at 143.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:13] {3166} INFO - iteration 780, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:13] {3343} INFO -  at 144.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:13] {3166} INFO - iteration 781, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:14] {3343} INFO -  at 144.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:14] {3166} INFO - iteration 782, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:14] {3343} INFO -  at 144.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:14] {3166} INFO - iteration 783, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:14] {3343} INFO -  at 144.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:14] {3166} INFO - iteration 784, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:14] {3343} INFO -  at 144.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:14] {3166} INFO - iteration 785, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:14] {3343} INFO -  at 144.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:14] {3166} INFO - iteration 786, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:14] {3343} INFO -  at 144.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:14] {3166} INFO - iteration 787, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:14] {3343} INFO -  at 144.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:14] {3166} INFO - iteration 788, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:15] {3343} INFO -  at 145.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:15] {3166} INFO - iteration 789, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:15] {3343} INFO -  at 145.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:15] {3166} INFO - iteration 790, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:15] {3343} INFO -  at 145.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:15] {3166} INFO - iteration 791, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:15] {3343} INFO -  at 145.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:15] {3166} INFO - iteration 792, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:15] {3343} INFO -  at 145.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:15] {3166} INFO - iteration 793, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:15] {3343} INFO -  at 145.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:15] {3166} INFO - iteration 794, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:15] {3343} INFO -  at 145.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:15] {3166} INFO - iteration 795, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:16] {3343} INFO -  at 146.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:16] {3166} INFO - iteration 796, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:16] {3343} INFO -  at 146.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:16] {3166} INFO - iteration 797, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:16] {3343} INFO -  at 146.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:16] {3166} INFO - iteration 798, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:16] {3343} INFO -  at 146.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:16] {3166} INFO - iteration 799, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:16] {3343} INFO -  at 146.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:16] {3166} INFO - iteration 800, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:16] {3343} INFO -  at 147.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:16] {3166} INFO - iteration 801, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:17] {3343} INFO -  at 147.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:17] {3166} INFO - iteration 802, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:17] {3343} INFO -  at 147.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:17] {3166} INFO - iteration 803, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:17] {3343} INFO -  at 147.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:17] {3166} INFO - iteration 804, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:17] {3343} INFO -  at 147.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:17] {3166} INFO - iteration 805, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:17] {3343} INFO -  at 147.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:17] {3166} INFO - iteration 806, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:17] {3343} INFO -  at 147.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:17] {3166} INFO - iteration 807, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:18] {3343} INFO -  at 148.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:18] {3166} INFO - iteration 808, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:18] {3343} INFO -  at 148.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:18] {3166} INFO - iteration 809, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:18] {3343} INFO -  at 148.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:18] {3166} INFO - iteration 810, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:18] {3343} INFO -  at 148.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:18] {3166} INFO - iteration 811, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:18] {3343} INFO -  at 148.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:18] {3166} INFO - iteration 812, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:18] {3343} INFO -  at 148.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:18] {3166} INFO - iteration 813, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:18] {3343} INFO -  at 149.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:18] {3166} INFO - iteration 814, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:19] {3343} INFO -  at 149.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:19] {3166} INFO - iteration 815, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:19] {3343} INFO -  at 149.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:19] {3166} INFO - iteration 816, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:19] {3343} INFO -  at 149.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:19] {3166} INFO - iteration 817, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:19] {3343} INFO -  at 149.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:19] {3166} INFO - iteration 818, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:19] {3343} INFO -  at 149.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:19] {3166} INFO - iteration 819, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:19] {3343} INFO -  at 149.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:19] {3166} INFO - iteration 820, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:19] {3343} INFO -  at 150.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:19] {3166} INFO - iteration 821, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:20] {3343} INFO -  at 150.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:20] {3166} INFO - iteration 822, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:20] {3343} INFO -  at 150.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:20] {3166} INFO - iteration 823, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:20] {3343} INFO -  at 150.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:20] {3166} INFO - iteration 824, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:20] {3343} INFO -  at 150.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:20] {3166} INFO - iteration 825, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:20] {3343} INFO -  at 150.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:20] {3166} INFO - iteration 826, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:20] {3343} INFO -  at 150.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:20] {3166} INFO - iteration 827, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:21] {3343} INFO -  at 151.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:21] {3166} INFO - iteration 828, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:21] {3343} INFO -  at 151.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:21] {3166} INFO - iteration 829, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:21] {3343} INFO -  at 151.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:21] {3166} INFO - iteration 830, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:21] {3343} INFO -  at 151.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:21] {3166} INFO - iteration 831, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:21] {3343} INFO -  at 151.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:21] {3166} INFO - iteration 832, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:21] {3343} INFO -  at 151.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:21] {3166} INFO - iteration 833, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:21] {3343} INFO -  at 152.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:21] {3166} INFO - iteration 834, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:22] {3343} INFO -  at 152.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:22] {3166} INFO - iteration 835, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:22] {3343} INFO -  at 152.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:22] {3166} INFO - iteration 836, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:22] {3343} INFO -  at 152.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:22] {3166} INFO - iteration 837, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:22] {3343} INFO -  at 152.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:22] {3166} INFO - iteration 838, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:22] {3343} INFO -  at 152.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:22] {3166} INFO - iteration 839, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:22] {3343} INFO -  at 152.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:22] {3166} INFO - iteration 840, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:23] {3343} INFO -  at 153.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:23] {3166} INFO - iteration 841, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:23] {3343} INFO -  at 153.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:23] {3166} INFO - iteration 842, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:23] {3343} INFO -  at 153.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:23] {3166} INFO - iteration 843, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:23] {3343} INFO -  at 153.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:23] {3166} INFO - iteration 844, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:23] {3343} INFO -  at 153.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:23] {3166} INFO - iteration 845, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:23] {3343} INFO -  at 153.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:23] {3166} INFO - iteration 846, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:23] {3343} INFO -  at 153.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:23] {3166} INFO - iteration 847, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:24] {3343} INFO -  at 154.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:24] {3166} INFO - iteration 848, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:24] {3343} INFO -  at 154.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:24] {3166} INFO - iteration 849, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:24] {3343} INFO -  at 154.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:24] {3166} INFO - iteration 850, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:24] {3343} INFO -  at 154.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:24] {3166} INFO - iteration 851, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:24] {3343} INFO -  at 154.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:24] {3166} INFO - iteration 852, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:24] {3343} INFO -  at 154.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:24] {3166} INFO - iteration 853, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:24] {3343} INFO -  at 154.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:24] {3166} INFO - iteration 854, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:25] {3343} INFO -  at 155.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:25] {3166} INFO - iteration 855, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:25] {3343} INFO -  at 155.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:25] {3166} INFO - iteration 856, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:25] {3343} INFO -  at 155.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:25] {3166} INFO - iteration 857, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:25] {3343} INFO -  at 155.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:25] {3166} INFO - iteration 858, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:25] {3343} INFO -  at 155.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:25] {3166} INFO - iteration 859, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:25] {3343} INFO -  at 155.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:25] {3166} INFO - iteration 860, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:25] {3343} INFO -  at 155.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:25] {3166} INFO - iteration 861, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:26] {3343} INFO -  at 156.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:26] {3166} INFO - iteration 862, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:26] {3343} INFO -  at 156.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:26] {3166} INFO - iteration 863, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:26] {3343} INFO -  at 156.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:26] {3166} INFO - iteration 864, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:26] {3343} INFO -  at 156.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:26] {3166} INFO - iteration 865, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:26] {3343} INFO -  at 156.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:26] {3166} INFO - iteration 866, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:26] {3343} INFO -  at 156.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:26] {3166} INFO - iteration 867, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:26] {3343} INFO -  at 156.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:26] {3166} INFO - iteration 868, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:27] {3343} INFO -  at 157.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:27] {3166} INFO - iteration 869, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:27] {3343} INFO -  at 157.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:27] {3166} INFO - iteration 870, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:27] {3343} INFO -  at 157.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:27] {3166} INFO - iteration 871, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:27] {3343} INFO -  at 157.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:27] {3166} INFO - iteration 872, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:27] {3343} INFO -  at 157.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:27] {3166} INFO - iteration 873, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:27] {3343} INFO -  at 157.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:27] {3166} INFO - iteration 874, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:27] {3343} INFO -  at 157.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:27] {3166} INFO - iteration 875, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:28] {3343} INFO -  at 158.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:28] {3166} INFO - iteration 876, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:28] {3343} INFO -  at 158.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:28] {3166} INFO - iteration 877, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:28] {3343} INFO -  at 158.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:28] {3166} INFO - iteration 878, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:28] {3343} INFO -  at 158.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:28] {3166} INFO - iteration 879, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:28] {3343} INFO -  at 158.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:28] {3166} INFO - iteration 880, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:28] {3343} INFO -  at 158.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:28] {3166} INFO - iteration 881, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:28] {3343} INFO -  at 158.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:28] {3166} INFO - iteration 882, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:28] {3343} INFO -  at 159.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:28] {3166} INFO - iteration 883, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:29] {3343} INFO -  at 159.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:29] {3166} INFO - iteration 884, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:29] {3343} INFO -  at 159.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:29] {3166} INFO - iteration 885, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:29] {3343} INFO -  at 159.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:29] {3166} INFO - iteration 886, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:29] {3343} INFO -  at 159.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:29] {3166} INFO - iteration 887, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:29] {3343} INFO -  at 159.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:29] {3166} INFO - iteration 888, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:29] {3343} INFO -  at 159.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:29] {3166} INFO - iteration 889, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:29] {3343} INFO -  at 159.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:29] {3166} INFO - iteration 890, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:30] {3343} INFO -  at 160.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:30] {3166} INFO - iteration 891, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:30] {3343} INFO -  at 160.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:30] {3166} INFO - iteration 892, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:30] {3343} INFO -  at 160.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:30] {3166} INFO - iteration 893, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:30] {3343} INFO -  at 160.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:30] {3166} INFO - iteration 894, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:30] {3343} INFO -  at 160.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:30] {3166} INFO - iteration 895, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:30] {3343} INFO -  at 160.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:30] {3166} INFO - iteration 896, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:30] {3343} INFO -  at 160.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:30] {3166} INFO - iteration 897, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:31] {3343} INFO -  at 161.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:31] {3166} INFO - iteration 898, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:31] {3343} INFO -  at 161.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:31] {3166} INFO - iteration 899, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:31] {3343} INFO -  at 161.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:31] {3166} INFO - iteration 900, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:31] {3343} INFO -  at 161.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:31] {3166} INFO - iteration 901, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:31] {3343} INFO -  at 161.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:31] {3166} INFO - iteration 902, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:31] {3343} INFO -  at 161.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:31] {3166} INFO - iteration 903, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:31] {3343} INFO -  at 161.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:31] {3166} INFO - iteration 904, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:31] {3343} INFO -  at 162.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:31] {3166} INFO - iteration 905, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:32] {3343} INFO -  at 162.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:32] {3166} INFO - iteration 906, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:32] {3343} INFO -  at 162.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:32] {3166} INFO - iteration 907, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:32] {3343} INFO -  at 162.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:32] {3166} INFO - iteration 908, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:32] {3343} INFO -  at 162.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:32] {3166} INFO - iteration 909, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:32] {3343} INFO -  at 162.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:32] {3166} INFO - iteration 910, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:32] {3343} INFO -  at 162.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:32] {3166} INFO - iteration 911, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:33] {3343} INFO -  at 163.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:33] {3166} INFO - iteration 912, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:33] {3343} INFO -  at 163.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:33] {3166} INFO - iteration 913, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:33] {3343} INFO -  at 163.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:33] {3166} INFO - iteration 914, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:33] {3343} INFO -  at 163.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:33] {3166} INFO - iteration 915, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:33] {3343} INFO -  at 163.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:33] {3166} INFO - iteration 916, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:33] {3343} INFO -  at 163.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:33] {3166} INFO - iteration 917, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:33] {3343} INFO -  at 163.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:33] {3166} INFO - iteration 918, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:34] {3343} INFO -  at 164.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:34] {3166} INFO - iteration 919, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:34] {3343} INFO -  at 164.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:34] {3166} INFO - iteration 920, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:34] {3343} INFO -  at 164.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:34] {3166} INFO - iteration 921, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:34] {3343} INFO -  at 164.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:34] {3166} INFO - iteration 922, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:34] {3343} INFO -  at 164.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:34] {3166} INFO - iteration 923, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:34] {3343} INFO -  at 164.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:34] {3166} INFO - iteration 924, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:34] {3343} INFO -  at 165.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:34] {3166} INFO - iteration 925, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:35] {3343} INFO -  at 165.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:35] {3166} INFO - iteration 926, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:35] {3343} INFO -  at 165.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:35] {3166} INFO - iteration 927, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:35] {3343} INFO -  at 165.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:35] {3166} INFO - iteration 928, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:35] {3343} INFO -  at 165.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:35] {3166} INFO - iteration 929, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:35] {3343} INFO -  at 165.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:35] {3166} INFO - iteration 930, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:35] {3343} INFO -  at 165.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:35] {3166} INFO - iteration 931, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:35] {3343} INFO -  at 166.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:35] {3166} INFO - iteration 932, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:36] {3343} INFO -  at 166.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:36] {3166} INFO - iteration 933, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:36] {3343} INFO -  at 166.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:36] {3166} INFO - iteration 934, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:36] {3343} INFO -  at 166.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:36] {3166} INFO - iteration 935, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:36] {3343} INFO -  at 166.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:36] {3166} INFO - iteration 936, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:36] {3343} INFO -  at 166.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:36] {3166} INFO - iteration 937, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:36] {3343} INFO -  at 166.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:36] {3166} INFO - iteration 938, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:37] {3343} INFO -  at 167.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:37] {3166} INFO - iteration 939, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:37] {3343} INFO -  at 167.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:37] {3166} INFO - iteration 940, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:37] {3343} INFO -  at 167.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:37] {3166} INFO - iteration 941, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:37] {3343} INFO -  at 167.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:37] {3166} INFO - iteration 942, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:37] {3343} INFO -  at 167.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:37] {3166} INFO - iteration 943, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:37] {3343} INFO -  at 167.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:37] {3166} INFO - iteration 944, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:37] {3343} INFO -  at 167.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:37] {3166} INFO - iteration 945, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:37] {3343} INFO -  at 168.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:37] {3166} INFO - iteration 946, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:38] {3343} INFO -  at 168.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:38] {3166} INFO - iteration 947, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:38] {3343} INFO -  at 168.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:38] {3166} INFO - iteration 948, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:38] {3343} INFO -  at 168.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:38] {3166} INFO - iteration 949, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:38] {3343} INFO -  at 168.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:38] {3166} INFO - iteration 950, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:38] {3343} INFO -  at 168.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:38] {3166} INFO - iteration 951, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:38] {3343} INFO -  at 168.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:38] {3166} INFO - iteration 952, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:39] {3343} INFO -  at 169.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:39] {3166} INFO - iteration 953, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:39] {3343} INFO -  at 169.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:39] {3166} INFO - iteration 954, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:39] {3343} INFO -  at 169.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:39] {3166} INFO - iteration 955, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:39] {3343} INFO -  at 169.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:39] {3166} INFO - iteration 956, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:39] {3343} INFO -  at 169.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:39] {3166} INFO - iteration 957, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:39] {3343} INFO -  at 169.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:39] {3166} INFO - iteration 958, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:40] {3343} INFO -  at 170.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:40] {3166} INFO - iteration 959, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:40] {3343} INFO -  at 170.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:40] {3166} INFO - iteration 960, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:40] {3343} INFO -  at 170.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:40] {3166} INFO - iteration 961, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:40] {3343} INFO -  at 170.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:40] {3166} INFO - iteration 962, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:40] {3343} INFO -  at 170.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:40] {3166} INFO - iteration 963, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:41] {3343} INFO -  at 171.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:41] {3166} INFO - iteration 964, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:41] {3343} INFO -  at 171.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:41] {3166} INFO - iteration 965, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:41] {3343} INFO -  at 171.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:41] {3166} INFO - iteration 966, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:41] {3343} INFO -  at 171.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:41] {3166} INFO - iteration 967, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:41] {3343} INFO -  at 171.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:41] {3166} INFO - iteration 968, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:41] {3343} INFO -  at 171.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:41] {3166} INFO - iteration 969, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:41] {3343} INFO -  at 171.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:41] {3166} INFO - iteration 970, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:42] {3343} INFO -  at 172.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:42] {3166} INFO - iteration 971, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:42] {3343} INFO -  at 172.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:42] {3166} INFO - iteration 972, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:42] {3343} INFO -  at 172.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:42] {3166} INFO - iteration 973, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:42] {3343} INFO -  at 172.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:42] {3166} INFO - iteration 974, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:42] {3343} INFO -  at 172.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:42] {3166} INFO - iteration 975, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:42] {3343} INFO -  at 172.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:42] {3166} INFO - iteration 976, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:42] {3343} INFO -  at 172.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:42] {3166} INFO - iteration 977, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:43] {3343} INFO -  at 173.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:43] {3166} INFO - iteration 978, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:43] {3343} INFO -  at 173.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:43] {3166} INFO - iteration 979, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:43] {3343} INFO -  at 173.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:43] {3166} INFO - iteration 980, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:43] {3343} INFO -  at 173.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:43] {3166} INFO - iteration 981, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:43] {3343} INFO -  at 173.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:43] {3166} INFO - iteration 982, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:43] {3343} INFO -  at 173.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:43] {3166} INFO - iteration 983, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:43] {3343} INFO -  at 173.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:43] {3166} INFO - iteration 984, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:44] {3343} INFO -  at 174.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:44] {3166} INFO - iteration 985, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:44] {3343} INFO -  at 174.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:44] {3166} INFO - iteration 986, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:44] {3343} INFO -  at 174.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:44] {3166} INFO - iteration 987, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:44] {3343} INFO -  at 174.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:44] {3166} INFO - iteration 988, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:44] {3343} INFO -  at 174.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:44] {3166} INFO - iteration 989, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:44] {3343} INFO -  at 174.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:44] {3166} INFO - iteration 990, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:45] {3343} INFO -  at 175.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:45] {3166} INFO - iteration 991, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:45] {3343} INFO -  at 175.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:45] {3166} INFO - iteration 992, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:45] {3343} INFO -  at 175.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:45] {3166} INFO - iteration 993, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:45] {3343} INFO -  at 175.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:45] {3166} INFO - iteration 994, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:45] {3343} INFO -  at 175.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:45] {3166} INFO - iteration 995, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:45] {3343} INFO -  at 175.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:45] {3166} INFO - iteration 996, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:45] {3343} INFO -  at 176.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:45] {3166} INFO - iteration 997, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:46] {3343} INFO -  at 176.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:46] {3166} INFO - iteration 998, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:46] {3343} INFO -  at 176.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:46] {3166} INFO - iteration 999, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:46] {3343} INFO -  at 176.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:46] {3166} INFO - iteration 1000, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:46] {3343} INFO -  at 176.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:46] {3166} INFO - iteration 1001, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:46] {3343} INFO -  at 176.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:46] {3166} INFO - iteration 1002, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:46] {3343} INFO -  at 176.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:46] {3166} INFO - iteration 1003, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:47] {3343} INFO -  at 177.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:47] {3166} INFO - iteration 1004, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:47] {3343} INFO -  at 177.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:47] {3166} INFO - iteration 1005, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:47] {3343} INFO -  at 177.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:47] {3166} INFO - iteration 1006, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:47] {3343} INFO -  at 177.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:47] {3166} INFO - iteration 1007, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:47] {3343} INFO -  at 177.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:47] {3166} INFO - iteration 1008, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:48] {3343} INFO -  at 178.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:48] {3166} INFO - iteration 1009, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:48] {3343} INFO -  at 178.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:48] {3166} INFO - iteration 1010, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:48] {3343} INFO -  at 178.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:48] {3166} INFO - iteration 1011, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:48] {3343} INFO -  at 179.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:48] {3166} INFO - iteration 1012, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:49] {3343} INFO -  at 179.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:49] {3166} INFO - iteration 1013, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:49] {3343} INFO -  at 179.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:49] {3166} INFO - iteration 1014, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:49] {3343} INFO -  at 179.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:49] {3166} INFO - iteration 1015, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:49] {3343} INFO -  at 179.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:49] {3166} INFO - iteration 1016, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:49] {3343} INFO -  at 179.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:49] {3166} INFO - iteration 1017, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:49] {3343} INFO -  at 180.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:49] {3166} INFO - iteration 1018, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:50] {3343} INFO -  at 180.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:50] {3166} INFO - iteration 1019, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:50] {3343} INFO -  at 180.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:50] {3166} INFO - iteration 1020, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:50] {3343} INFO -  at 180.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:50] {3166} INFO - iteration 1021, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:50] {3343} INFO -  at 180.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:50] {3166} INFO - iteration 1022, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:50] {3343} INFO -  at 180.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:50] {3166} INFO - iteration 1023, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:50] {3343} INFO -  at 181.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:50] {3166} INFO - iteration 1024, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:51] {3343} INFO -  at 181.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:51] {3166} INFO - iteration 1025, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:51] {3343} INFO -  at 181.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:51] {3166} INFO - iteration 1026, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:51] {3343} INFO -  at 181.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:51] {3166} INFO - iteration 1027, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:51] {3343} INFO -  at 181.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:51] {3166} INFO - iteration 1028, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:51] {3343} INFO -  at 181.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:51] {3166} INFO - iteration 1029, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:51] {3343} INFO -  at 181.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:51] {3166} INFO - iteration 1030, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:52] {3343} INFO -  at 182.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:52] {3166} INFO - iteration 1031, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:52] {3343} INFO -  at 182.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:52] {3166} INFO - iteration 1032, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:52] {3343} INFO -  at 182.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:52] {3166} INFO - iteration 1033, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:52] {3343} INFO -  at 182.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:52] {3166} INFO - iteration 1034, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:52] {3343} INFO -  at 182.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:52] {3166} INFO - iteration 1035, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:52] {3343} INFO -  at 182.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:52] {3166} INFO - iteration 1036, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:53] {3343} INFO -  at 183.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:53] {3166} INFO - iteration 1037, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:53] {3343} INFO -  at 183.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:53] {3166} INFO - iteration 1038, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:53] {3343} INFO -  at 183.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:53] {3166} INFO - iteration 1039, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:53] {3343} INFO -  at 183.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:53] {3166} INFO - iteration 1040, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:53] {3343} INFO -  at 183.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:53] {3166} INFO - iteration 1041, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:53] {3343} INFO -  at 183.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:53] {3166} INFO - iteration 1042, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:53] {3343} INFO -  at 184.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:53] {3166} INFO - iteration 1043, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:54] {3343} INFO -  at 184.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:54] {3166} INFO - iteration 1044, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:54] {3343} INFO -  at 184.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:54] {3166} INFO - iteration 1045, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:54] {3343} INFO -  at 184.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:54] {3166} INFO - iteration 1046, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:54] {3343} INFO -  at 184.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:54] {3166} INFO - iteration 1047, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:54] {3343} INFO -  at 184.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:54] {3166} INFO - iteration 1048, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:54] {3343} INFO -  at 184.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:54] {3166} INFO - iteration 1049, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:55] {3343} INFO -  at 185.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:55] {3166} INFO - iteration 1050, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:55] {3343} INFO -  at 185.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:55] {3166} INFO - iteration 1051, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:55] {3343} INFO -  at 185.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:55] {3166} INFO - iteration 1052, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:55] {3343} INFO -  at 185.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:55] {3166} INFO - iteration 1053, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:55] {3343} INFO -  at 185.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:55] {3166} INFO - iteration 1054, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:55] {3343} INFO -  at 185.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:55] {3166} INFO - iteration 1055, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:55] {3343} INFO -  at 186.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:55] {3166} INFO - iteration 1056, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:56] {3343} INFO -  at 186.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:56] {3166} INFO - iteration 1057, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:56] {3343} INFO -  at 186.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:56] {3166} INFO - iteration 1058, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:56] {3343} INFO -  at 186.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:56] {3166} INFO - iteration 1059, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:56] {3343} INFO -  at 186.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:56] {3166} INFO - iteration 1060, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:56] {3343} INFO -  at 186.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:56] {3166} INFO - iteration 1061, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:57] {3343} INFO -  at 187.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:57] {3166} INFO - iteration 1062, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:57] {3343} INFO -  at 187.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:57] {3166} INFO - iteration 1063, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:57] {3343} INFO -  at 187.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:57] {3166} INFO - iteration 1064, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:57] {3343} INFO -  at 187.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:57] {3166} INFO - iteration 1065, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:57] {3343} INFO -  at 187.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:57] {3166} INFO - iteration 1066, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:57] {3343} INFO -  at 187.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:57] {3166} INFO - iteration 1067, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:58] {3343} INFO -  at 188.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:58] {3166} INFO - iteration 1068, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:58] {3343} INFO -  at 188.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:58] {3166} INFO - iteration 1069, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:58] {3343} INFO -  at 188.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:58] {3166} INFO - iteration 1070, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:58] {3343} INFO -  at 188.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:58] {3166} INFO - iteration 1071, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:58] {3343} INFO -  at 188.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:58] {3166} INFO - iteration 1072, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:58] {3343} INFO -  at 188.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:58] {3166} INFO - iteration 1073, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:58] {3343} INFO -  at 188.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:58] {3166} INFO - iteration 1074, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:58] {3343} INFO -  at 189.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:58] {3166} INFO - iteration 1075, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:59] {3343} INFO -  at 189.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:59] {3166} INFO - iteration 1076, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:59] {3343} INFO -  at 189.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:59] {3166} INFO - iteration 1077, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:17:59] {3343} INFO -  at 189.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:59] {3166} INFO - iteration 1078, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:59] {3343} INFO -  at 189.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:59] {3166} INFO - iteration 1079, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:59] {3343} INFO -  at 189.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:59] {3166} INFO - iteration 1080, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:59] {3343} INFO -  at 189.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:59] {3166} INFO - iteration 1081, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:17:59] {3343} INFO -  at 190.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:17:59] {3166} INFO - iteration 1082, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:00] {3343} INFO -  at 190.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:00] {3166} INFO - iteration 1083, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:00] {3343} INFO -  at 190.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:00] {3166} INFO - iteration 1084, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:00] {3343} INFO -  at 190.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:00] {3166} INFO - iteration 1085, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:00] {3343} INFO -  at 190.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:00] {3166} INFO - iteration 1086, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:00] {3343} INFO -  at 190.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:00] {3166} INFO - iteration 1087, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:00] {3343} INFO -  at 190.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:00] {3166} INFO - iteration 1088, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:00] {3343} INFO -  at 190.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:00] {3166} INFO - iteration 1089, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:01] {3343} INFO -  at 191.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:01] {3166} INFO - iteration 1090, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:01] {3343} INFO -  at 191.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:01] {3166} INFO - iteration 1091, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:01] {3343} INFO -  at 191.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:01] {3166} INFO - iteration 1092, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:01] {3343} INFO -  at 191.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:01] {3166} INFO - iteration 1093, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:01] {3343} INFO -  at 191.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:01] {3166} INFO - iteration 1094, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:01] {3343} INFO -  at 191.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:01] {3166} INFO - iteration 1095, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:01] {3343} INFO -  at 191.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:01] {3166} INFO - iteration 1096, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:02] {3343} INFO -  at 192.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:02] {3166} INFO - iteration 1097, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:02] {3343} INFO -  at 192.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:02] {3166} INFO - iteration 1098, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:02] {3343} INFO -  at 192.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:02] {3166} INFO - iteration 1099, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:02] {3343} INFO -  at 192.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:02] {3166} INFO - iteration 1100, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:02] {3343} INFO -  at 192.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:02] {3166} INFO - iteration 1101, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:02] {3343} INFO -  at 192.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:02] {3166} INFO - iteration 1102, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:02] {3343} INFO -  at 192.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:02] {3166} INFO - iteration 1103, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:03] {3343} INFO -  at 193.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:03] {3166} INFO - iteration 1104, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:03] {3343} INFO -  at 193.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:03] {3166} INFO - iteration 1105, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:03] {3343} INFO -  at 193.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:03] {3166} INFO - iteration 1106, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:03] {3343} INFO -  at 193.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:03] {3166} INFO - iteration 1107, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:03] {3343} INFO -  at 193.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:03] {3166} INFO - iteration 1108, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:03] {3343} INFO -  at 193.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:03] {3166} INFO - iteration 1109, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:04] {3343} INFO -  at 194.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:04] {3166} INFO - iteration 1110, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:04] {3343} INFO -  at 194.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:04] {3166} INFO - iteration 1111, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:04] {3343} INFO -  at 194.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:04] {3166} INFO - iteration 1112, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:04] {3343} INFO -  at 194.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:04] {3166} INFO - iteration 1113, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:04] {3343} INFO -  at 194.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:04] {3166} INFO - iteration 1114, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:04] {3343} INFO -  at 194.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:04] {3166} INFO - iteration 1115, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:04] {3343} INFO -  at 194.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:04] {3166} INFO - iteration 1116, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:05] {3343} INFO -  at 195.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:05] {3166} INFO - iteration 1117, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:05] {3343} INFO -  at 195.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:05] {3166} INFO - iteration 1118, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:05] {3343} INFO -  at 195.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:05] {3166} INFO - iteration 1119, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:05] {3343} INFO -  at 195.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:05] {3166} INFO - iteration 1120, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:05] {3343} INFO -  at 195.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:05] {3166} INFO - iteration 1121, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:05] {3343} INFO -  at 195.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:05] {3166} INFO - iteration 1122, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:05] {3343} INFO -  at 195.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:05] {3166} INFO - iteration 1123, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:06] {3343} INFO -  at 196.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:06] {3166} INFO - iteration 1124, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:06] {3343} INFO -  at 196.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:06] {3166} INFO - iteration 1125, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:06] {3343} INFO -  at 196.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:06] {3166} INFO - iteration 1126, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:06] {3343} INFO -  at 196.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:06] {3166} INFO - iteration 1127, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:06] {3343} INFO -  at 196.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:06] {3166} INFO - iteration 1128, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:06] {3343} INFO -  at 196.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:06] {3166} INFO - iteration 1129, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:06] {3343} INFO -  at 196.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:06] {3166} INFO - iteration 1130, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:07] {3343} INFO -  at 197.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:07] {3166} INFO - iteration 1131, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:07] {3343} INFO -  at 197.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:07] {3166} INFO - iteration 1132, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:07] {3343} INFO -  at 197.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:07] {3166} INFO - iteration 1133, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:07] {3343} INFO -  at 197.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:07] {3166} INFO - iteration 1134, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:07] {3343} INFO -  at 197.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:07] {3166} INFO - iteration 1135, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:07] {3343} INFO -  at 197.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:07] {3166} INFO - iteration 1136, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:07] {3343} INFO -  at 197.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:07] {3166} INFO - iteration 1137, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:07] {3343} INFO -  at 197.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:07] {3166} INFO - iteration 1138, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:08] {3343} INFO -  at 198.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:08] {3166} INFO - iteration 1139, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:08] {3343} INFO -  at 198.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:08] {3166} INFO - iteration 1140, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:08] {3343} INFO -  at 198.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:08] {3166} INFO - iteration 1141, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:08] {3343} INFO -  at 198.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:08] {3166} INFO - iteration 1142, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:08] {3343} INFO -  at 198.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:08] {3166} INFO - iteration 1143, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:08] {3343} INFO -  at 198.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:08] {3166} INFO - iteration 1144, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:08] {3343} INFO -  at 198.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:08] {3166} INFO - iteration 1145, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:09] {3343} INFO -  at 199.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:09] {3166} INFO - iteration 1146, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:09] {3343} INFO -  at 199.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:09] {3166} INFO - iteration 1147, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:09] {3343} INFO -  at 199.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:09] {3166} INFO - iteration 1148, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:09] {3343} INFO -  at 199.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:09] {3166} INFO - iteration 1149, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:09] {3343} INFO -  at 199.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:09] {3166} INFO - iteration 1150, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:09] {3343} INFO -  at 199.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:09] {3166} INFO - iteration 1151, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:09] {3343} INFO -  at 199.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:09] {3166} INFO - iteration 1152, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:10] {3343} INFO -  at 200.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:10] {3166} INFO - iteration 1153, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:10] {3343} INFO -  at 200.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:10] {3166} INFO - iteration 1154, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:10] {3343} INFO -  at 200.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:10] {3166} INFO - iteration 1155, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:10] {3343} INFO -  at 200.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:10] {3166} INFO - iteration 1156, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:10] {3343} INFO -  at 200.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:10] {3166} INFO - iteration 1157, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:10] {3343} INFO -  at 200.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:10] {3166} INFO - iteration 1158, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:10] {3343} INFO -  at 201.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:10] {3166} INFO - iteration 1159, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:11] {3343} INFO -  at 201.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:11] {3166} INFO - iteration 1160, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:11] {3343} INFO -  at 201.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:11] {3166} INFO - iteration 1161, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:11] {3343} INFO -  at 201.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:11] {3166} INFO - iteration 1162, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:11] {3343} INFO -  at 201.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:11] {3166} INFO - iteration 1163, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:11] {3343} INFO -  at 201.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:11] {3166} INFO - iteration 1164, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:11] {3343} INFO -  at 201.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:11] {3166} INFO - iteration 1165, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:11] {3343} INFO -  at 202.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:11] {3166} INFO - iteration 1166, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:12] {3343} INFO -  at 202.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:12] {3166} INFO - iteration 1167, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:12] {3343} INFO -  at 202.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:12] {3166} INFO - iteration 1168, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:12] {3343} INFO -  at 202.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:12] {3166} INFO - iteration 1169, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:12] {3343} INFO -  at 202.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:12] {3166} INFO - iteration 1170, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:12] {3343} INFO -  at 202.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:12] {3166} INFO - iteration 1171, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:12] {3343} INFO -  at 202.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:12] {3166} INFO - iteration 1172, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:13] {3343} INFO -  at 203.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:13] {3166} INFO - iteration 1173, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:13] {3343} INFO -  at 203.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:13] {3166} INFO - iteration 1174, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:13] {3343} INFO -  at 203.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:13] {3166} INFO - iteration 1175, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:13] {3343} INFO -  at 203.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:13] {3166} INFO - iteration 1176, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:13] {3343} INFO -  at 203.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:13] {3166} INFO - iteration 1177, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:13] {3343} INFO -  at 203.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:13] {3166} INFO - iteration 1178, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:13] {3343} INFO -  at 203.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:13] {3166} INFO - iteration 1179, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:13] {3343} INFO -  at 204.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:14] {3166} INFO - iteration 1180, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:14] {3343} INFO -  at 204.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:14] {3166} INFO - iteration 1181, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:14] {3343} INFO -  at 204.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:14] {3166} INFO - iteration 1182, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:14] {3343} INFO -  at 204.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:14] {3166} INFO - iteration 1183, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:14] {3343} INFO -  at 204.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:14] {3166} INFO - iteration 1184, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:14] {3343} INFO -  at 204.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:14] {3166} INFO - iteration 1185, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:14] {3343} INFO -  at 204.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:14] {3166} INFO - iteration 1186, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:14] {3343} INFO -  at 205.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:14] {3166} INFO - iteration 1187, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:15] {3343} INFO -  at 205.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:15] {3166} INFO - iteration 1188, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:15] {3343} INFO -  at 205.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:15] {3166} INFO - iteration 1189, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:15] {3343} INFO -  at 205.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:15] {3166} INFO - iteration 1190, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:15] {3343} INFO -  at 205.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:15] {3166} INFO - iteration 1191, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:15] {3343} INFO -  at 205.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:15] {3166} INFO - iteration 1192, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:15] {3343} INFO -  at 205.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:15] {3166} INFO - iteration 1193, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:15] {3343} INFO -  at 206.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:15] {3166} INFO - iteration 1194, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:16] {3343} INFO -  at 206.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:16] {3166} INFO - iteration 1195, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:16] {3343} INFO -  at 206.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:16] {3166} INFO - iteration 1196, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:16] {3343} INFO -  at 206.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:16] {3166} INFO - iteration 1197, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:16] {3343} INFO -  at 206.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:16] {3166} INFO - iteration 1198, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:16] {3343} INFO -  at 206.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:16] {3166} INFO - iteration 1199, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:16] {3343} INFO -  at 206.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:16] {3166} INFO - iteration 1200, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:16] {3343} INFO -  at 206.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:16] {3166} INFO - iteration 1201, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:17] {3343} INFO -  at 207.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:17] {3166} INFO - iteration 1202, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:17] {3343} INFO -  at 207.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:17] {3166} INFO - iteration 1203, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:17] {3343} INFO -  at 207.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:17] {3166} INFO - iteration 1204, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:17] {3343} INFO -  at 207.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:17] {3166} INFO - iteration 1205, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:17] {3343} INFO -  at 207.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:17] {3166} INFO - iteration 1206, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:17] {3343} INFO -  at 207.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:17] {3166} INFO - iteration 1207, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:17] {3343} INFO -  at 207.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:17] {3166} INFO - iteration 1208, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:17] {3343} INFO -  at 208.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:17] {3166} INFO - iteration 1209, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:18] {3343} INFO -  at 208.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:18] {3166} INFO - iteration 1210, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:18] {3343} INFO -  at 208.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:18] {3166} INFO - iteration 1211, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:18] {3343} INFO -  at 208.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:18] {3166} INFO - iteration 1212, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:18] {3343} INFO -  at 208.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:18] {3166} INFO - iteration 1213, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:18] {3343} INFO -  at 208.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:18] {3166} INFO - iteration 1214, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:18] {3343} INFO -  at 208.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:18] {3166} INFO - iteration 1215, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:18] {3343} INFO -  at 208.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:18] {3166} INFO - iteration 1216, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:18] {3343} INFO -  at 209.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:18] {3166} INFO - iteration 1217, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:19] {3343} INFO -  at 209.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:19] {3166} INFO - iteration 1218, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:19] {3343} INFO -  at 209.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:19] {3166} INFO - iteration 1219, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:19] {3343} INFO -  at 209.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:19] {3166} INFO - iteration 1220, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:19] {3343} INFO -  at 209.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:19] {3166} INFO - iteration 1221, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:19] {3343} INFO -  at 209.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:19] {3166} INFO - iteration 1222, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:19] {3343} INFO -  at 209.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:19] {3166} INFO - iteration 1223, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:19] {3343} INFO -  at 210.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:19] {3166} INFO - iteration 1224, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:20] {3343} INFO -  at 210.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:20] {3166} INFO - iteration 1225, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:20] {3343} INFO -  at 210.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:20] {3166} INFO - iteration 1226, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:20] {3343} INFO -  at 210.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:20] {3166} INFO - iteration 1227, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:20] {3343} INFO -  at 210.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:20] {3166} INFO - iteration 1228, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:20] {3343} INFO -  at 210.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:20] {3166} INFO - iteration 1229, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:20] {3343} INFO -  at 210.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:20] {3166} INFO - iteration 1230, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:20] {3343} INFO -  at 210.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:20] {3166} INFO - iteration 1231, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:21] {3343} INFO -  at 211.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:21] {3166} INFO - iteration 1232, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:21] {3343} INFO -  at 211.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:21] {3166} INFO - iteration 1233, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:21] {3343} INFO -  at 211.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:21] {3166} INFO - iteration 1234, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:21] {3343} INFO -  at 211.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:21] {3166} INFO - iteration 1235, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:21] {3343} INFO -  at 211.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:21] {3166} INFO - iteration 1236, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:21] {3343} INFO -  at 211.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:21] {3166} INFO - iteration 1237, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:21] {3343} INFO -  at 211.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:21] {3166} INFO - iteration 1238, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:21] {3343} INFO -  at 211.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:21] {3166} INFO - iteration 1239, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:22] {3343} INFO -  at 212.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:22] {3166} INFO - iteration 1240, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:22] {3343} INFO -  at 212.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:22] {3166} INFO - iteration 1241, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:22] {3343} INFO -  at 212.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:22] {3166} INFO - iteration 1242, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:22] {3343} INFO -  at 212.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:22] {3166} INFO - iteration 1243, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:22] {3343} INFO -  at 212.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:22] {3166} INFO - iteration 1244, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:22] {3343} INFO -  at 212.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:22] {3166} INFO - iteration 1245, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:22] {3343} INFO -  at 212.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:22] {3166} INFO - iteration 1246, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:23] {3343} INFO -  at 213.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:23] {3166} INFO - iteration 1247, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:23] {3343} INFO -  at 213.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:23] {3166} INFO - iteration 1248, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:23] {3343} INFO -  at 213.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:23] {3166} INFO - iteration 1249, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:23] {3343} INFO -  at 213.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:23] {3166} INFO - iteration 1250, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:23] {3343} INFO -  at 213.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:23] {3166} INFO - iteration 1251, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:23] {3343} INFO -  at 213.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:23] {3166} INFO - iteration 1252, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:23] {3343} INFO -  at 213.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:23] {3166} INFO - iteration 1253, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:24] {3343} INFO -  at 214.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:24] {3166} INFO - iteration 1254, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:24] {3343} INFO -  at 214.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:24] {3166} INFO - iteration 1255, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:24] {3343} INFO -  at 214.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:24] {3166} INFO - iteration 1256, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:24] {3343} INFO -  at 214.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:24] {3166} INFO - iteration 1257, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:24] {3343} INFO -  at 214.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:24] {3166} INFO - iteration 1258, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:24] {3343} INFO -  at 214.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:24] {3166} INFO - iteration 1259, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:24] {3343} INFO -  at 215.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:24] {3166} INFO - iteration 1260, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:25] {3343} INFO -  at 215.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:25] {3166} INFO - iteration 1261, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:25] {3343} INFO -  at 215.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:25] {3166} INFO - iteration 1262, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:25] {3343} INFO -  at 215.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:25] {3166} INFO - iteration 1263, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:25] {3343} INFO -  at 215.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:25] {3166} INFO - iteration 1264, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:25] {3343} INFO -  at 215.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:25] {3166} INFO - iteration 1265, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:25] {3343} INFO -  at 215.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:25] {3166} INFO - iteration 1266, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:25] {3343} INFO -  at 215.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:25] {3166} INFO - iteration 1267, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:26] {3343} INFO -  at 216.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:26] {3166} INFO - iteration 1268, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:26] {3343} INFO -  at 216.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:26] {3166} INFO - iteration 1269, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:26] {3343} INFO -  at 216.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:26] {3166} INFO - iteration 1270, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:26] {3343} INFO -  at 216.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:26] {3166} INFO - iteration 1271, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:26] {3343} INFO -  at 216.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:26] {3166} INFO - iteration 1272, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:27] {3343} INFO -  at 217.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:27] {3166} INFO - iteration 1273, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:27] {3343} INFO -  at 217.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:27] {3166} INFO - iteration 1274, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:27] {3343} INFO -  at 217.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:27] {3166} INFO - iteration 1275, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:27] {3343} INFO -  at 217.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:27] {3166} INFO - iteration 1276, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:27] {3343} INFO -  at 217.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:27] {3166} INFO - iteration 1277, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:28] {3343} INFO -  at 218.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:28] {3166} INFO - iteration 1278, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:28] {3343} INFO -  at 218.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:28] {3166} INFO - iteration 1279, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:28] {3343} INFO -  at 218.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:28] {3166} INFO - iteration 1280, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:28] {3343} INFO -  at 218.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:28] {3166} INFO - iteration 1281, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:28] {3343} INFO -  at 218.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:28] {3166} INFO - iteration 1282, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:28] {3343} INFO -  at 218.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:28] {3166} INFO - iteration 1283, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:29] {3343} INFO -  at 219.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:29] {3166} INFO - iteration 1284, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:29] {3343} INFO -  at 219.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:29] {3166} INFO - iteration 1285, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:29] {3343} INFO -  at 219.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:29] {3166} INFO - iteration 1286, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:29] {3343} INFO -  at 219.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:29] {3166} INFO - iteration 1287, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:29] {3343} INFO -  at 219.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:29] {3166} INFO - iteration 1288, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:29] {3343} INFO -  at 219.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:29] {3166} INFO - iteration 1289, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:29] {3343} INFO -  at 219.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:29] {3166} INFO - iteration 1290, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:30] {3343} INFO -  at 220.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:30] {3166} INFO - iteration 1291, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:30] {3343} INFO -  at 220.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:30] {3166} INFO - iteration 1292, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:30] {3343} INFO -  at 220.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:30] {3166} INFO - iteration 1293, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:30] {3343} INFO -  at 220.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:30] {3166} INFO - iteration 1294, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:30] {3343} INFO -  at 220.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:30] {3166} INFO - iteration 1295, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:30] {3343} INFO -  at 220.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:30] {3166} INFO - iteration 1296, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:30] {3343} INFO -  at 220.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:30] {3166} INFO - iteration 1297, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:31] {3343} INFO -  at 221.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:31] {3166} INFO - iteration 1298, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:31] {3343} INFO -  at 221.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:31] {3166} INFO - iteration 1299, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:31] {3343} INFO -  at 221.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:31] {3166} INFO - iteration 1300, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:31] {3343} INFO -  at 221.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:31] {3166} INFO - iteration 1301, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:31] {3343} INFO -  at 221.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:31] {3166} INFO - iteration 1302, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:31] {3343} INFO -  at 221.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:31] {3166} INFO - iteration 1303, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:31] {3343} INFO -  at 221.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:31] {3166} INFO - iteration 1304, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:32] {3343} INFO -  at 222.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:32] {3166} INFO - iteration 1305, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:32] {3343} INFO -  at 222.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:32] {3166} INFO - iteration 1306, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:32] {3343} INFO -  at 222.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:32] {3166} INFO - iteration 1307, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:32] {3343} INFO -  at 222.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:32] {3166} INFO - iteration 1308, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:32] {3343} INFO -  at 222.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:32] {3166} INFO - iteration 1309, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:32] {3343} INFO -  at 223.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:32] {3166} INFO - iteration 1310, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:33] {3343} INFO -  at 223.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:33] {3166} INFO - iteration 1311, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:33] {3343} INFO -  at 223.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:33] {3166} INFO - iteration 1312, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:33] {3343} INFO -  at 223.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:33] {3166} INFO - iteration 1313, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:33] {3343} INFO -  at 223.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:33] {3166} INFO - iteration 1314, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:33] {3343} INFO -  at 223.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:33] {3166} INFO - iteration 1315, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:33] {3343} INFO -  at 224.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:33] {3166} INFO - iteration 1316, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:34] {3343} INFO -  at 224.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:34] {3166} INFO - iteration 1317, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:34] {3343} INFO -  at 224.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:34] {3166} INFO - iteration 1318, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:34] {3343} INFO -  at 224.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:34] {3166} INFO - iteration 1319, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:34] {3343} INFO -  at 224.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:34] {3166} INFO - iteration 1320, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:34] {3343} INFO -  at 224.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:34] {3166} INFO - iteration 1321, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:34] {3343} INFO -  at 224.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:34] {3166} INFO - iteration 1322, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:35] {3343} INFO -  at 225.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:35] {3166} INFO - iteration 1323, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:35] {3343} INFO -  at 225.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:35] {3166} INFO - iteration 1324, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:35] {3343} INFO -  at 225.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:35] {3166} INFO - iteration 1325, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:35] {3343} INFO -  at 225.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:35] {3166} INFO - iteration 1326, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:35] {3343} INFO -  at 225.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:35] {3166} INFO - iteration 1327, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:35] {3343} INFO -  at 225.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:35] {3166} INFO - iteration 1328, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:35] {3343} INFO -  at 225.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:35] {3166} INFO - iteration 1329, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:36] {3343} INFO -  at 226.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:36] {3166} INFO - iteration 1330, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:36] {3343} INFO -  at 226.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:36] {3166} INFO - iteration 1331, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:36] {3343} INFO -  at 226.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:36] {3166} INFO - iteration 1332, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:36] {3343} INFO -  at 226.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:36] {3166} INFO - iteration 1333, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:36] {3343} INFO -  at 226.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:36] {3166} INFO - iteration 1334, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:37] {3343} INFO -  at 227.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:37] {3166} INFO - iteration 1335, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:37] {3343} INFO -  at 227.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:37] {3166} INFO - iteration 1336, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:37] {3343} INFO -  at 227.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:37] {3166} INFO - iteration 1337, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:37] {3343} INFO -  at 227.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324

[flaml.automl: 04-23 11:18:37] {3166} INFO - iteration 1338, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:37] {3343} INFO -  at 227.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:37] {3166} INFO - iteration 1339, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:38] {3343} INFO -  at 228.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:38] {3166} INFO - iteration 1340, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:38] {3343} INFO -  at 228.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:38] {3166} INFO - iteration 1341, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:38] {3343} INFO -  at 228.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:38] {3166} INFO - iteration 1342, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:38] {3343} INFO -  at 228.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:38] {3166} INFO - iteration 1343, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:38] {3343} INFO -  at 228.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:38] {3166} INFO - iteration 1344, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:38] {3343} INFO -  at 228.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:38] {3166} INFO - iteration 1345, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:38] {3343} INFO -  at 228.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:38] {3166} INFO - iteration 1346, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:39] {3343} INFO -  at 229.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:39] {3166} INFO - iteration 1347, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:39] {3343} INFO -  at 229.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:39] {3166} INFO - iteration 1348, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:39] {3343} INFO -  at 229.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:39] {3166} INFO - iteration 1349, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:39] {3343} INFO -  at 229.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:39] {3166} INFO - iteration 1350, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:39] {3343} INFO -  at 229.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:39] {3166} INFO - iteration 1351, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:39] {3343} INFO -  at 229.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:39] {3166} INFO - iteration 1352, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:40] {3343} INFO -  at 230.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:40] {3166} INFO - iteration 1353, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:40] {3343} INFO -  at 230.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:40] {3166} INFO - iteration 1354, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:40] {3343} INFO -  at 230.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:40] {3166} INFO - iteration 1355, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:40] {3343} INFO -  at 230.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:40] {3166} INFO - iteration 1356, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:40] {3343} INFO -  at 230.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:40] {3166} INFO - iteration 1357, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:40] {3343} INFO -  at 230.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:40] {3166} INFO - iteration 1358, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:41] {3343} INFO -  at 231.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:41] {3166} INFO - iteration 1359, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:41] {3343} INFO -  at 231.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:41] {3166} INFO - iteration 1360, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:41] {3343} INFO -  at 231.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:41] {3166} INFO - iteration 1361, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:41] {3343} INFO -  at 231.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:41] {3166} INFO - iteration 1362, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:41] {3343} INFO -  at 231.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:41] {3166} INFO - iteration 1363, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:41] {3343} INFO -  at 231.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:41] {3166} INFO - iteration 1364, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:42] {3343} INFO -  at 232.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:42] {3166} INFO - iteration 1365, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:42] {3343} INFO -  at 232.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:42] {3166} INFO - iteration 1366, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:42] {3343} INFO -  at 232.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:42] {3166} INFO - iteration 1367, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:42] {3343} INFO -  at 232.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:42] {3166} INFO - iteration 1368, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:42] {3343} INFO -  at 232.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:42] {3166} INFO - iteration 1369, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:43] {3343} INFO -  at 233.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:43] {3166} INFO - iteration 1370, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:43] {3343} INFO -  at 233.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:43] {3166} INFO - iteration 1371, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:43] {3343} INFO -  at 233.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:43] {3166} INFO - iteration 1372, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:43] {3343} INFO -  at 233.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:43] {3166} INFO - iteration 1373, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:44] {3343} INFO -  at 234.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:44] {3166} INFO - iteration 1374, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:44] {3343} INFO -  at 234.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:44] {3166} INFO - iteration 1375, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:44] {3343} INFO -  at 234.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:44] {3166} INFO - iteration 1376, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:44] {3343} INFO -  at 234.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324

[flaml.automl: 04-23 11:18:44] {3166} INFO - iteration 1377, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:44] {3343} INFO -  at 234.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:44] {3166} INFO - iteration 1378, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:45] {3343} INFO -  at 235.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:45] {3166} INFO - iteration 1379, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:45] {3343} INFO -  at 235.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:45] {3166} INFO - iteration 1380, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:45] {3343} INFO -  at 235.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:45] {3166} INFO - iteration 1381, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:45] {3343} INFO -  at 235.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:45] {3166} INFO - iteration 1382, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:45] {3343} INFO -  at 235.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:45] {3166} INFO - iteration 1383, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:45] {3343} INFO -  at 235.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:45] {3166} INFO - iteration 1384, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:45] {3343} INFO -  at 236.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:45] {3166} INFO - iteration 1385, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:46] {3343} INFO -  at 236.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:46] {3166} INFO - iteration 1386, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:46] {3343} INFO -  at 236.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:46] {3166} INFO - iteration 1387, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:46] {3343} INFO -  at 236.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:46] {3166} INFO - iteration 1388, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:46] {3343} INFO -  at 236.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:46] {3166} INFO - iteration 1389, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:46] {3343} INFO -  at 236.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:46] {3166} INFO - iteration 1390, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:46] {3343} INFO -  at 236.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:46] {3166} INFO - iteration 1391, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:47] {3343} INFO -  at 237.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:47] {3166} INFO - iteration 1392, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:47] {3343} INFO -  at 237.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:47] {3166} INFO - iteration 1393, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:47] {3343} INFO -  at 237.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:47] {3166} INFO - iteration 1394, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:47] {3343} INFO -  at 237.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:47] {3166} INFO - iteration 1395, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:47] {3343} INFO -  at 237.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:47] {3166} INFO - iteration 1396, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:47] {3343} INFO -  at 237.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:47] {3166} INFO - iteration 1397, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:47] {3343} INFO -  at 237.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:47] {3166} INFO - iteration 1398, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:48] {3343} INFO -  at 238.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:48] {3166} INFO - iteration 1399, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:48] {3343} INFO -  at 238.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:48] {3166} INFO - iteration 1400, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:48] {3343} INFO -  at 238.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:48] {3166} INFO - iteration 1401, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:48] {3343} INFO -  at 238.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:48] {3166} INFO - iteration 1402, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:48] {3343} INFO -  at 238.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:48] {3166} INFO - iteration 1403, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:48] {3343} INFO -  at 238.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:48] {3166} INFO - iteration 1404, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:48] {3343} INFO -  at 238.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:48] {3166} INFO - iteration 1405, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:48] {3343} INFO -  at 239.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:48] {3166} INFO - iteration 1406, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:49] {3343} INFO -  at 239.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:49] {3166} INFO - iteration 1407, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:49] {3343} INFO -  at 239.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:49] {3166} INFO - iteration 1408, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:49] {3343} INFO -  at 239.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:49] {3166} INFO - iteration 1409, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:49] {3343} INFO -  at 239.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:49] {3166} INFO - iteration 1410, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:49] {3343} INFO -  at 239.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:49] {3166} INFO - iteration 1411, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:49] {3343} INFO -  at 239.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:49] {3166} INFO - iteration 1412, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:49] {3343} INFO -  at 239.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:49] {3166} INFO - iteration 1413, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:50] {3343} INFO -  at 240.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:50] {3166} INFO - iteration 1414, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:50] {3343} INFO -  at 240.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:50] {3166} INFO - iteration 1415, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:50] {3343} INFO -  at 240.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:50] {3166} INFO - iteration 1416, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:50] {3343} INFO -  at 240.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:50] {3166} INFO - iteration 1417, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:50] {3343} INFO -  at 240.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:50] {3166} INFO - iteration 1418, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:50] {3343} INFO -  at 240.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:50] {3166} INFO - iteration 1419, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:50] {3343} INFO -  at 241.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:50] {3166} INFO - iteration 1420, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:51] {3343} INFO -  at 241.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:51] {3166} INFO - iteration 1421, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:51] {3343} INFO -  at 241.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:51] {3166} INFO - iteration 1422, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:51] {3343} INFO -  at 241.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:51] {3166} INFO - iteration 1423, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:51] {3343} INFO -  at 241.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:51] {3166} INFO - iteration 1424, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:51] {3343} INFO -  at 241.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:51] {3166} INFO - iteration 1425, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:51] {3343} INFO -  at 241.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:51] {3166} INFO - iteration 1426, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:51] {3343} INFO -  at 242.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:51] {3166} INFO - iteration 1427, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:52] {3343} INFO -  at 242.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:52] {3166} INFO - iteration 1428, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:52] {3343} INFO -  at 242.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:52] {3166} INFO - iteration 1429, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:52] {3343} INFO -  at 242.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:52] {3166} INFO - iteration 1430, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:52] {3343} INFO -  at 242.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:52] {3166} INFO - iteration 1431, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:52] {3343} INFO -  at 242.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:52] {3166} INFO - iteration 1432, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:52] {3343} INFO -  at 242.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:52] {3166} INFO - iteration 1433, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:52] {3343} INFO -  at 242.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:52] {3166} INFO - iteration 1434, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:52] {3343} INFO -  at 242.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:52] {3166} INFO - iteration 1435, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:53] {3343} INFO -  at 243.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:53] {3166} INFO - iteration 1436, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:53] {3343} INFO -  at 243.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:53] {3166} INFO - iteration 1437, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:53] {3343} INFO -  at 243.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:53] {3166} INFO - iteration 1438, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:53] {3343} INFO -  at 243.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:53] {3166} INFO - iteration 1439, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:53] {3343} INFO -  at 243.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:53] {3166} INFO - iteration 1440, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:53] {3343} INFO -  at 243.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:53] {3166} INFO - iteration 1441, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:53] {3343} INFO -  at 243.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:53] {3166} INFO - iteration 1442, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:54] {3343} INFO -  at 244.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:54] {3166} INFO - iteration 1443, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:54] {3343} INFO -  at 244.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:54] {3166} INFO - iteration 1444, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:54] {3343} INFO -  at 244.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:54] {3166} INFO - iteration 1445, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:54] {3343} INFO -  at 244.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:54] {3166} INFO - iteration 1446, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:54] {3343} INFO -  at 244.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:54] {3166} INFO - iteration 1447, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:54] {3343} INFO -  at 244.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:54] {3166} INFO - iteration 1448, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:54] {3343} INFO -  at 244.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:54] {3166} INFO - iteration 1449, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:55] {3343} INFO -  at 245.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:55] {3166} INFO - iteration 1450, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:55] {3343} INFO -  at 245.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:55] {3166} INFO - iteration 1451, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:55] {3343} INFO -  at 245.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:55] {3166} INFO - iteration 1452, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:55] {3343} INFO -  at 245.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:55] {3166} INFO - iteration 1453, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:55] {3343} INFO -  at 245.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:55] {3166} INFO - iteration 1454, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:55] {3343} INFO -  at 245.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:55] {3166} INFO - iteration 1455, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:55] {3343} INFO -  at 245.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:55] {3166} INFO - iteration 1456, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:55] {3343} INFO -  at 245.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:55] {3166} INFO - iteration 1457, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:56] {3343} INFO -  at 246.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:56] {3166} INFO - iteration 1458, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:56] {3343} INFO -  at 246.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:56] {3166} INFO - iteration 1459, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:56] {3343} INFO -  at 246.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:56] {3166} INFO - iteration 1460, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:56] {3343} INFO -  at 246.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:56] {3166} INFO - iteration 1461, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:56] {3343} INFO -  at 246.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:56] {3166} INFO - iteration 1462, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:56] {3343} INFO -  at 246.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:56] {3166} INFO - iteration 1463, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:56] {3343} INFO -  at 246.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:56] {3166} INFO - iteration 1464, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:56] {3343} INFO -  at 246.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:56] {3166} INFO - iteration 1465, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:57] {3343} INFO -  at 247.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:57] {3166} INFO - iteration 1466, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:57] {3343} INFO -  at 247.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:57] {3166} INFO - iteration 1467, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:57] {3343} INFO -  at 247.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:57] {3166} INFO - iteration 1468, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:57] {3343} INFO -  at 247.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:57] {3166} INFO - iteration 1469, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:57] {3343} INFO -  at 247.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:57] {3166} INFO - iteration 1470, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:57] {3343} INFO -  at 247.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:57] {3166} INFO - iteration 1471, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:57] {3343} INFO -  at 247.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:57] {3166} INFO - iteration 1472, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:57] {3343} INFO -  at 247.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:57] {3166} INFO - iteration 1473, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:58] {3343} INFO -  at 248.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:58] {3166} INFO - iteration 1474, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:58] {3343} INFO -  at 248.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:58] {3166} INFO - iteration 1475, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:58] {3343} INFO -  at 248.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:58] {3166} INFO - iteration 1476, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:58] {3343} INFO -  at 248.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:58] {3166} INFO - iteration 1477, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:58] {3343} INFO -  at 248.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:58] {3166} INFO - iteration 1478, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:58] {3343} INFO -  at 248.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:58] {3166} INFO - iteration 1479, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:58] {3343} INFO -  at 249.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:58] {3166} INFO - iteration 1480, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:18:59] {3343} INFO -  at 249.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:59] {3166} INFO - iteration 1481, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:59] {3343} INFO -  at 249.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:59] {3166} INFO - iteration 1482, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:59] {3343} INFO -  at 249.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:59] {3166} INFO - iteration 1483, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:59] {3343} INFO -  at 249.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:59] {3166} INFO - iteration 1484, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:59] {3343} INFO -  at 249.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:59] {3166} INFO - iteration 1485, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:59] {3343} INFO -  at 249.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:59] {3166} INFO - iteration 1486, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:18:59] {3343} INFO -  at 250.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:18:59] {3166} INFO - iteration 1487, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:00] {3343} INFO -  at 250.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:00] {3166} INFO - iteration 1488, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:00] {3343} INFO -  at 250.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:00] {3166} INFO - iteration 1489, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:00] {3343} INFO -  at 250.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:00] {3166} INFO - iteration 1490, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:00] {3343} INFO -  at 250.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:00] {3166} INFO - iteration 1491, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:00] {3343} INFO -  at 250.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:00] {3166} INFO - iteration 1492, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:00] {3343} INFO -  at 250.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:00] {3166} INFO - iteration 1493, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:00] {3343} INFO -  at 250.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:00] {3166} INFO - iteration 1494, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:01] {3343} INFO -  at 251.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:01] {3166} INFO - iteration 1495, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:01] {3343} INFO -  at 251.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:01] {3166} INFO - iteration 1496, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:01] {3343} INFO -  at 251.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:01] {3166} INFO - iteration 1497, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:01] {3343} INFO -  at 251.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:01] {3166} INFO - iteration 1498, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:01] {3343} INFO -  at 251.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:01] {3166} INFO - iteration 1499, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:01] {3343} INFO -  at 251.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:01] {3166} INFO - iteration 1500, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:01] {3343} INFO -  at 251.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:01] {3166} INFO - iteration 1501, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:01] {3343} INFO -  at 252.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:01] {3166} INFO - iteration 1502, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:02] {3343} INFO -  at 252.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:02] {3166} INFO - iteration 1503, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:02] {3343} INFO -  at 252.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:02] {3166} INFO - iteration 1504, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:02] {3343} INFO -  at 252.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:02] {3166} INFO - iteration 1505, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:02] {3343} INFO -  at 252.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:02] {3166} INFO - iteration 1506, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:02] {3343} INFO -  at 252.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:02] {3166} INFO - iteration 1507, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:02] {3343} INFO -  at 252.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:02] {3166} INFO - iteration 1508, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:02] {3343} INFO -  at 252.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:02] {3166} INFO - iteration 1509, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:03] {3343} INFO -  at 253.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:03] {3166} INFO - iteration 1510, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:03] {3343} INFO -  at 253.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:03] {3166} INFO - iteration 1511, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:03] {3343} INFO -  at 253.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:03] {3166} INFO - iteration 1512, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:03] {3343} INFO -  at 253.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:03] {3166} INFO - iteration 1513, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:03] {3343} INFO -  at 253.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:03] {3166} INFO - iteration 1514, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:03] {3343} INFO -  at 253.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:03] {3166} INFO - iteration 1515, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:03] {3343} INFO -  at 254.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:03] {3166} INFO - iteration 1516, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:04] {3343} INFO -  at 254.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:04] {3166} INFO - iteration 1517, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:04] {3343} INFO -  at 254.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:04] {3166} INFO - iteration 1518, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:04] {3343} INFO -  at 254.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:04] {3166} INFO - iteration 1519, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:04] {3343} INFO -  at 254.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:04] {3166} INFO - iteration 1520, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:04] {3343} INFO -  at 254.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:04] {3166} INFO - iteration 1521, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:04] {3343} INFO -  at 254.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:04] {3166} INFO - iteration 1522, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:05] {3343} INFO -  at 255.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:05] {3166} INFO - iteration 1523, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:05] {3343} INFO -  at 255.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:05] {3166} INFO - iteration 1524, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:05] {3343} INFO -  at 255.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:05] {3166} INFO - iteration 1525, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:05] {3343} INFO -  at 255.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:05] {3166} INFO - iteration 1526, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:05] {3343} INFO -  at 255.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:05] {3166} INFO - iteration 1527, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:05] {3343} INFO -  at 255.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:05] {3166} INFO - iteration 1528, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:06] {3343} INFO -  at 256.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:06] {3166} INFO - iteration 1529, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:06] {3343} INFO -  at 256.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:06] {3166} INFO - iteration 1530, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:06] {3343} INFO -  at 256.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:06] {3166} INFO - iteration 1531, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:06] {3343} INFO -  at 256.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:06] {3166} INFO - iteration 1532, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:06] {3343} INFO -  at 256.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:06] {3166} INFO - iteration 1533, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:06] {3343} INFO -  at 256.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:06] {3166} INFO - iteration 1534, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:06] {3343} INFO -  at 257.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:06] {3166} INFO - iteration 1535, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:07] {3343} INFO -  at 257.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:07] {3166} INFO - iteration 1536, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:07] {3343} INFO -  at 257.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:07] {3166} INFO - iteration 1537, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:07] {3343} INFO -  at 257.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:07] {3166} INFO - iteration 1538, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:07] {3343} INFO -  at 257.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:07] {3166} INFO - iteration 1539, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:07] {3343} INFO -  at 257.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:07] {3166} INFO - iteration 1540, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:07] {3343} INFO -  at 257.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:07] {3166} INFO - iteration 1541, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:07] {3343} INFO -  at 258.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:07] {3166} INFO - iteration 1542, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:08] {3343} INFO -  at 258.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:08] {3166} INFO - iteration 1543, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:08] {3343} INFO -  at 258.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:08] {3166} INFO - iteration 1544, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:08] {3343} INFO -  at 258.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:08] {3166} INFO - iteration 1545, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:08] {3343} INFO -  at 258.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:08] {3166} INFO - iteration 1546, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:08] {3343} INFO -  at 258.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:08] {3166} INFO - iteration 1547, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:08] {3343} INFO -  at 258.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:08] {3166} INFO - iteration 1548, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:09] {3343} INFO -  at 259.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:09] {3166} INFO - iteration 1549, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:09] {3343} INFO -  at 259.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:09] {3166} INFO - iteration 1550, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:09] {3343} INFO -  at 259.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:09] {3166} INFO - iteration 1551, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:09] {3343} INFO -  at 259.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:09] {3166} INFO - iteration 1552, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:09] {3343} INFO -  at 259.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:09] {3166} INFO - iteration 1553, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:09] {3343} INFO -  at 259.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:09] {3166} INFO - iteration 1554, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:10] {3343} INFO -  at 260.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:10] {3166} INFO - iteration 1555, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:10] {3343} INFO -  at 260.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:10] {3166} INFO - iteration 1556, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:10] {3343} INFO -  at 260.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:10] {3166} INFO - iteration 1557, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:10] {3343} INFO -  at 260.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:10] {3166} INFO - iteration 1558, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:11] {3343} INFO -  at 261.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:11] {3166} INFO - iteration 1559, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:11] {3343} INFO -  at 261.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:11] {3166} INFO - iteration 1560, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:11] {3343} INFO -  at 261.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:11] {3166} INFO - iteration 1561, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:11] {3343} INFO -  at 261.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:11] {3166} INFO - iteration 1562, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:11] {3343} INFO -  at 261.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:11] {3166} INFO - iteration 1563, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:11] {3343} INFO -  at 261.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:11] {3166} INFO - iteration 1564, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:11] {3343} INFO -  at 261.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:11] {3166} INFO - iteration 1565, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:12] {3343} INFO -  at 262.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:12] {3166} INFO - iteration 1566, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:12] {3343} INFO -  at 262.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:12] {3166} INFO - iteration 1567, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:12] {3343} INFO -  at 262.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:12] {3166} INFO - iteration 1568, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:12] {3343} INFO -  at 262.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:12] {3166} INFO - iteration 1569, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:12] {3343} INFO -  at 262.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:12] {3166} INFO - iteration 1570, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:12] {3343} INFO -  at 263.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:12] {3166} INFO - iteration 1571, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:13] {3343} INFO -  at 263.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:13] {3166} INFO - iteration 1572, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:13] {3343} INFO -  at 263.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:13] {3166} INFO - iteration 1573, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:13] {3343} INFO -  at 263.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:13] {3166} INFO - iteration 1574, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:13] {3343} INFO -  at 263.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:13] {3166} INFO - iteration 1575, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:13] {3343} INFO -  at 263.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:13] {3166} INFO - iteration 1576, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:14] {3343} INFO -  at 264.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:14] {3166} INFO - iteration 1577, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:14] {3343} INFO -  at 264.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:14] {3166} INFO - iteration 1578, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:14] {3343} INFO -  at 264.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:14] {3166} INFO - iteration 1579, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:14] {3343} INFO -  at 264.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:14] {3166} INFO - iteration 1580, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:14] {3343} INFO -  at 264.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:14] {3166} INFO - iteration 1581, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:14] {3343} INFO -  at 264.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:14] {3166} INFO - iteration 1582, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:15] {3343} INFO -  at 265.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:15] {3166} INFO - iteration 1583, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:15] {3343} INFO -  at 265.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:15] {3166} INFO - iteration 1584, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:15] {3343} INFO -  at 265.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324

[flaml.automl: 04-23 11:19:15] {3166} INFO - iteration 1585, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:15] {3343} INFO -  at 265.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:15] {3166} INFO - iteration 1586, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:15] {3343} INFO -  at 266.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:15] {3166} INFO - iteration 1587, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:16] {3343} INFO -  at 266.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:16] {3166} INFO - iteration 1588, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:16] {3343} INFO -  at 266.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:16] {3166} INFO - iteration 1589, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:16] {3343} INFO -  at 266.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:16] {3166} INFO - iteration 1590, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:16] {3343} INFO -  at 266.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:16] {3166} INFO - iteration 1591, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:17] {3343} INFO -  at 267.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:17] {3166} INFO - iteration 1592, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:17] {3343} INFO -  at 267.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:17] {3166} INFO - iteration 1593, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:17] {3343} INFO -  at 267.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:17] {3166} INFO - iteration 1594, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:17] {3343} INFO -  at 267.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:17] {3166} INFO - iteration 1595, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:17] {3343} INFO -  at 267.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:17] {3166} INFO - iteration 1596, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:17] {3343} INFO -  at 267.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:17] {3166} INFO - iteration 1597, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:18] {3343} INFO -  at 268.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:18] {3166} INFO - iteration 1598, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:18] {3343} INFO -  at 268.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:18] {3166} INFO - iteration 1599, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:18] {3343} INFO -  at 268.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:18] {3166} INFO - iteration 1600, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:18] {3343} INFO -  at 268.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:18] {3166} INFO - iteration 1601, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:18] {3343} INFO -  at 268.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:18] {3166} INFO - iteration 1602, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:18] {3343} INFO -  at 269.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:18] {3166} INFO - iteration 1603, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:19] {3343} INFO -  at 269.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:19] {3166} INFO - iteration 1604, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:19] {3343} INFO -  at 269.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:19] {3166} INFO - iteration 1605, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:19] {3343} INFO -  at 269.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:19] {3166} INFO - iteration 1606, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:19] {3343} INFO -  at 269.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:19] {3166} INFO - iteration 1607, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:19] {3343} INFO -  at 269.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:19] {3166} INFO - iteration 1608, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:19] {3343} INFO -  at 270.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:19] {3166} INFO - iteration 1609, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:20] {3343} INFO -  at 270.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:20] {3166} INFO - iteration 1610, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:20] {3343} INFO -  at 270.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:20] {3166} INFO - iteration 1611, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:20] {3343} INFO -  at 270.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:20] {3166} INFO - iteration 1612, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:20] {3343} INFO -  at 270.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:20] {3166} INFO - iteration 1613, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:20] {3343} INFO -  at 270.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:20] {3166} INFO - iteration 1614, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:21] {3343} INFO -  at 271.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:21] {3166} INFO - iteration 1615, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:21] {3343} INFO -  at 271.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:21] {3166} INFO - iteration 1616, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:21] {3343} INFO -  at 271.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:21] {3166} INFO - iteration 1617, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:21] {3343} INFO -  at 271.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:21] {3166} INFO - iteration 1618, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:21] {3343} INFO -  at 271.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:21] {3166} INFO - iteration 1619, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:22] {3343} INFO -  at 272.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:22] {3166} INFO - iteration 1620, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:22] {3343} INFO -  at 272.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:22] {3166} INFO - iteration 1621, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:22] {3343} INFO -  at 272.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:22] {3166} INFO - iteration 1622, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:22] {3343} INFO -  at 272.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:22] {3166} INFO - iteration 1623, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:22] {3343} INFO -  at 272.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324

[flaml.automl: 04-23 11:19:22] {3166} INFO - iteration 1624, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:23] {3343} INFO -  at 273.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:23] {3166} INFO - iteration 1625, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:23] {3343} INFO -  at 273.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:23] {3166} INFO - iteration 1626, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:23] {3343} INFO -  at 273.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:23] {3166} INFO - iteration 1627, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:23] {3343} INFO -  at 273.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:23] {3166} INFO - iteration 1628, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:23] {3343} INFO -  at 273.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:23] {3166} INFO - iteration 1629, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:24] {3343} INFO -  at 274.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:24] {3166} INFO - iteration 1630, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:24] {3343} INFO -  at 274.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:24] {3166} INFO - iteration 1631, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:24] {3343} INFO -  at 274.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:24] {3166} INFO - iteration 1632, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:24] {3343} INFO -  at 274.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:24] {3166} INFO - iteration 1633, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:24] {3343} INFO -  at 274.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:24] {3166} INFO - iteration 1634, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:24] {3343} INFO -  at 274.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:24] {3166} INFO - iteration 1635, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:25] {3343} INFO -  at 275.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:25] {3166} INFO - iteration 1636, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:25] {3343} INFO -  at 275.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:25] {3166} INFO - iteration 1637, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:25] {3343} INFO -  at 275.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:25] {3166} INFO - iteration 1638, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:25] {3343} INFO -  at 275.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:25] {3166} INFO - iteration 1639, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:25] {3343} INFO -  at 275.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:25] {3166} INFO - iteration 1640, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:25] {3343} INFO -  at 276.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:25] {3166} INFO - iteration 1641, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:26] {3343} INFO -  at 276.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:26] {3166} INFO - iteration 1642, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:26] {3343} INFO -  at 276.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:26] {3166} INFO - iteration 1643, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:26] {3343} INFO -  at 276.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:26] {3166} INFO - iteration 1644, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:26] {3343} INFO -  at 276.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:26] {3166} INFO - iteration 1645, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:26] {3343} INFO -  at 277.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:26] {3166} INFO - iteration 1646, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:27] {3343} INFO -  at 277.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:27] {3166} INFO - iteration 1647, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:27] {3343} INFO -  at 277.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:27] {3166} INFO - iteration 1648, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:27] {3343} INFO -  at 277.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:27] {3166} INFO - iteration 1649, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:27] {3343} INFO -  at 277.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324

[flaml.automl: 04-23 11:19:27] {3166} INFO - iteration 1650, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:28] {3343} INFO -  at 278.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:28] {3166} INFO - iteration 1651, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:28] {3343} INFO -  at 278.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:28] {3166} INFO - iteration 1652, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:28] {3343} INFO -  at 278.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:28] {3166} INFO - iteration 1653, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:29] {3343} INFO -  at 279.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:29] {3166} INFO - iteration 1654, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:29] {3343} INFO -  at 279.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:29] {3166} INFO - iteration 1655, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:29] {3343} INFO -  at 279.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:29] {3166} INFO - iteration 1656, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:29] {3343} INFO -  at 279.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:29] {3166} INFO - iteration 1657, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:29] {3343} INFO -  at 279.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:29] {3166} INFO - iteration 1658, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:30] {3343} INFO -  at 280.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:30] {3166} INFO - iteration 1659, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:30] {3343} INFO -  at 280.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:30] {3166} INFO - iteration 1660, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:30] {3343} INFO -  at 280.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:30] {3166} INFO - iteration 1661, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:30] {3343} INFO -  at 280.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:30] {3166} INFO - iteration 1662, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:30] {3343} INFO -  at 281.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:30] {3166} INFO - iteration 1663, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:31] {3343} INFO -  at 281.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:31] {3166} INFO - iteration 1664, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:31] {3343} INFO -  at 281.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:31] {3166} INFO - iteration 1665, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:31] {3343} INFO -  at 281.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:31] {3166} INFO - iteration 1666, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:31] {3343} INFO -  at 281.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:31] {3166} INFO - iteration 1667, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:32] {3343} INFO -  at 282.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:32] {3166} INFO - iteration 1668, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:32] {3343} INFO -  at 282.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:32] {3166} INFO - iteration 1669, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:32] {3343} INFO -  at 282.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:32] {3166} INFO - iteration 1670, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:32] {3343} INFO -  at 282.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:32] {3166} INFO - iteration 1671, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:33] {3343} INFO -  at 283.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:33] {3166} INFO - iteration 1672, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:33] {3343} INFO -  at 283.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:33] {3166} INFO - iteration 1673, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:33] {3343} INFO -  at 283.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:33] {3166} INFO - iteration 1674, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:33] {3343} INFO -  at 283.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:33] {3166} INFO - iteration 1675, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:33] {3343} INFO -  at 283.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:33] {3166} INFO - iteration 1676, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:34] {3343} INFO -  at 284.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:34] {3166} INFO - iteration 1677, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:34] {3343} INFO -  at 284.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:34] {3166} INFO - iteration 1678, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:34] {3343} INFO -  at 284.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:34] {3166} INFO - iteration 1679, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:34] {3343} INFO -  at 284.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:34] {3166} INFO - iteration 1680, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:34] {3343} INFO -  at 284.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:34] {3166} INFO - iteration 1681, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:35] {3343} INFO -  at 285.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:35] {3166} INFO - iteration 1682, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:35] {3343} INFO -  at 285.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:35] {3166} INFO - iteration 1683, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:35] {3343} INFO -  at 285.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:35] {3166} INFO - iteration 1684, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:35] {3343} INFO -  at 285.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:35] {3166} INFO - iteration 1685, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:35] {3343} INFO -  at 285.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:35] {3166} INFO - iteration 1686, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:36] {3343} INFO -  at 286.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:36] {3166} INFO - iteration 1687, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:36] {3343} INFO -  at 286.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:36] {3166} INFO - iteration 1688, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:36] {3343} INFO -  at 286.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:36] {3166} INFO - iteration 1689, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:36] {3343} INFO -  at 286.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:36] {3166} INFO - iteration 1690, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:36] {3343} INFO -  at 286.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:36] {3166} INFO - iteration 1691, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:36] {3343} INFO -  at 287.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:36] {3166} INFO - iteration 1692, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:37] {3343} INFO -  at 287.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:37] {3166} INFO - iteration 1693, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:37] {3343} INFO -  at 287.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:37] {3166} INFO - iteration 1694, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:37] {3343} INFO -  at 287.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:37] {3166} INFO - iteration 1695, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:37] {3343} INFO -  at 287.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:37] {3166} INFO - iteration 1696, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:37] {3343} INFO -  at 288.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:37] {3166} INFO - iteration 1697, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:38] {3343} INFO -  at 288.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:38] {3166} INFO - iteration 1698, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:38] {3343} INFO -  at 288.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:38] {3166} INFO - iteration 1699, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:38] {3343} INFO -  at 288.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:38] {3166} INFO - iteration 1700, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:38] {3343} INFO -  at 288.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:38] {3166} INFO - iteration 1701, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:39] {3343} INFO -  at 289.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:39] {3166} INFO - iteration 1702, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:39] {3343} INFO -  at 289.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:39] {3166} INFO - iteration 1703, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:39] {3343} INFO -  at 289.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:39] {3166} INFO - iteration 1704, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:39] {3343} INFO -  at 289.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:39] {3166} INFO - iteration 1705, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:39] {3343} INFO -  at 289.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:39] {3166} INFO - iteration 1706, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:40] {3343} INFO -  at 290.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:40] {3166} INFO - iteration 1707, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:40] {3343} INFO -  at 290.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:40] {3166} INFO - iteration 1708, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:40] {3343} INFO -  at 290.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:40] {3166} INFO - iteration 1709, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:40] {3343} INFO -  at 290.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:40] {3166} INFO - iteration 1710, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:41] {3343} INFO -  at 291.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:41] {3166} INFO - iteration 1711, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:41] {3343} INFO -  at 291.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:41] {3166} INFO - iteration 1712, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:41] {3343} INFO -  at 291.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:41] {3166} INFO - iteration 1713, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:41] {3343} INFO -  at 291.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:41] {3166} INFO - iteration 1714, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:41] {3343} INFO -  at 291.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:41] {3166} INFO - iteration 1715, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:42] {3343} INFO -  at 292.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:42] {3166} INFO - iteration 1716, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:42] {3343} INFO -  at 292.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:42] {3166} INFO - iteration 1717, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:42] {3343} INFO -  at 292.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:42] {3166} INFO - iteration 1718, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:42] {3343} INFO -  at 292.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:42] {3166} INFO - iteration 1719, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:42] {3343} INFO -  at 292.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:42] {3166} INFO - iteration 1720, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:42] {3343} INFO -  at 292.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:42] {3166} INFO - iteration 1721, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:43] {3343} INFO -  at 293.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:43] {3166} INFO - iteration 1722, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:43] {3343} INFO -  at 293.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:43] {3166} INFO - iteration 1723, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:43] {3343} INFO -  at 293.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:43] {3166} INFO - iteration 1724, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:43] {3343} INFO -  at 293.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:43] {3166} INFO - iteration 1725, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:43] {3343} INFO -  at 293.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:43] {3166} INFO - iteration 1726, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:44] {3343} INFO -  at 294.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:44] {3166} INFO - iteration 1727, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:44] {3343} INFO -  at 294.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324

[flaml.automl: 04-23 11:19:44] {3166} INFO - iteration 1728, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:44] {3343} INFO -  at 294.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:44] {3166} INFO - iteration 1729, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:44] {3343} INFO -  at 294.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:44] {3166} INFO - iteration 1730, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:44] {3343} INFO -  at 294.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:44] {3166} INFO - iteration 1731, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:44] {3343} INFO -  at 295.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:44] {3166} INFO - iteration 1732, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:45] {3343} INFO -  at 295.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:45] {3166} INFO - iteration 1733, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:45] {3343} INFO -  at 295.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:45] {3166} INFO - iteration 1734, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:45] {3343} INFO -  at 295.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:45] {3166} INFO - iteration 1735, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:45] {3343} INFO -  at 295.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:45] {3166} INFO - iteration 1736, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:45] {3343} INFO -  at 295.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:45] {3166} INFO - iteration 1737, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:46] {3343} INFO -  at 296.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:46] {3166} INFO - iteration 1738, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:46] {3343} INFO -  at 296.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:46] {3166} INFO - iteration 1739, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:46] {3343} INFO -  at 296.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:46] {3166} INFO - iteration 1740, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:46] {3343} INFO -  at 296.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:46] {3166} INFO - iteration 1741, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:46] {3343} INFO -  at 296.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:46] {3166} INFO - iteration 1742, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:47] {3343} INFO -  at 297.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:47] {3166} INFO - iteration 1743, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:47] {3343} INFO -  at 297.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:47] {3166} INFO - iteration 1744, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:47] {3343} INFO -  at 297.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:47] {3166} INFO - iteration 1745, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:47] {3343} INFO -  at 297.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:47] {3166} INFO - iteration 1746, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:47] {3343} INFO -  at 297.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:47] {3166} INFO - iteration 1747, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:47] {3343} INFO -  at 298.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:47] {3166} INFO - iteration 1748, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:48] {3343} INFO -  at 298.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:48] {3166} INFO - iteration 1749, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:48] {3343} INFO -  at 298.3s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:48] {3166} INFO - iteration 1750, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:48] {3343} INFO -  at 298.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:48] {3166} INFO - iteration 1751, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:48] {3343} INFO -  at 298.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:48] {3166} INFO - iteration 1752, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:48] {3343} INFO -  at 298.7s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:48] {3166} INFO - iteration 1753, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:48] {3343} INFO -  at 298.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:48] {3166} INFO - iteration 1754, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:48] {3343} INFO -  at 299.0s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:48] {3166} INFO - iteration 1755, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:49] {3343} INFO -  at 299.1s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:49] {3166} INFO - iteration 1756, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:49] {3343} INFO -  at 299.2s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:49] {3166} INFO - iteration 1757, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:49] {3343} INFO -  at 299.4s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:49] {3166} INFO - iteration 1758, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:49] {3343} INFO -  at 299.5s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:49] {3166} INFO - iteration 1759, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:49] {3343} INFO -  at 299.6s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:49] {3166} INFO - iteration 1760, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:49] {3343} INFO -  at 299.8s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:49] {3166} INFO - iteration 1761, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:49] {3343} INFO -  at 299.9s,	estimator rf's best error=87.9324,	best estimator rf's best error=87.9324
[flaml.automl: 04-23 11:19:49] {3602} INFO - retrain rf for 0.1s
[flaml.automl: 04-23 11:19:49] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.5790869690535811, max_leaf_nodes=338,
                      n_estimators=32, n_jobs=-1)
[flaml.automl: 04-23 11:19:49] {2901} INFO - fit succeeded
[flaml.automl: 04-23 11:19:49] {2902} INFO - Time taken to find the best model: 40.05058574676514
[flaml.automl: 04-23 11:19:50] {2599} INFO - task = regression
[flaml.automl: 04-23 11:19:50] {2601} INFO - Data split method: uniform
[flaml.automl: 04-23 11:19:50] {2604} INFO - Evaluation method: holdout
[flaml.automl: 04-23 11:19:50] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 04-23 11:19:50] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 04-23 11:19:50] {3166} INFO - iteration 0, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:50] {3296} INFO - Estimated sufficient time budget=358s. Estimated necessary time budget=0s.
[flaml.automl: 04-23 11:19:50] {3343} INFO -  at 0.1s,	estimator rf's best error=145.1238,	best estimator rf's best error=145.1238
[flaml.automl: 04-23 11:19:50] {3166} INFO - iteration 1, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:50] {3343} INFO -  at 0.1s,	estimator rf's best error=121.8461,	best estimator rf's best error=121.8461
[flaml.automl: 04-23 11:19:50] {3166} INFO - iteration 2, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:50] {3343} INFO -  at 0.1s,	estimator rf's best error=121.8461,	best estimator rf's best error=121.8461

[flaml.automl: 04-23 11:19:50] {3166} INFO - iteration 3, current learner rf

0.63 -1.86 0.37

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:50] {3343} INFO -  at 0.2s,	estimator rf's best error=98.8819,	best estimator rf's best error=98.8819
[flaml.automl: 04-23 11:19:50] {3166} INFO - iteration 4, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:50] {3343} INFO -  at 0.3s,	estimator rf's best error=91.8720,	best estimator rf's best error=91.8720
[flaml.automl: 04-23 11:19:50] {3166} INFO - iteration 5, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:50] {3343} INFO -  at 0.3s,	estimator rf's best error=91.8720,	best estimator rf's best error=91.8720
[flaml.automl: 04-23 11:19:50] {3166} INFO - iteration 6, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:50] {3343} INFO -  at 0.4s,	estimator rf's best error=91.8720,	best estimator rf's best error=91.8720
[flaml.automl: 04-23 11:19:50] {3166} INFO - iteration 7, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:50] {3343} INFO -  at 0.5s,	estimator rf's best error=91.8720,	best estimator rf's best error=91.8720
[flaml.automl: 04-23 11:19:50] {3166} INFO - iteration 8, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:50] {3343} INFO -  at 0.6s,	estimator rf's best error=88.2123,	best estimator rf's best error=88.2123
[flaml.automl: 04-23 11:19:50] {3166} INFO - iteration 9, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:50] {3343} INFO -  at 0.6s,	estimator rf's best error=88.2123,	best estimator rf's best error=88.2123
[flaml.automl: 04-23 11:19:50] {3166} INFO - iteration 10, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:50] {3343} INFO -  at 0.7s,	estimator rf's best error=88.2123,	best estimator rf's best error=88.2123
[flaml.automl: 04-23 11:19:50] {3166} INFO - iteration 11, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:50] {3343} INFO -  at 0.8s,	estimator rf's best error=88.2123,	best estimator rf's best error=88.2123
[flaml.automl: 04-23 11:19:50] {3166} INFO - iteration 12, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:50] {3343} INFO -  at 0.9s,	estimator rf's best error=88.2123,	best estimator rf's best error=88.2123
[flaml.automl: 04-23 11:19:50] {3166} INFO - iteration 13, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:51] {3343} INFO -  at 1.0s,	estimator rf's best error=87.5492,	best estimator rf's best error=87.5492
[flaml.automl: 04-23 11:19:51] {3166} INFO - iteration 14, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:51] {3343} INFO -  at 1.1s,	estimator rf's best error=87.5492,	best estimator rf's best error=87.5492
[flaml.automl: 04-23 11:19:51] {3166} INFO - iteration 15, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:51] {3343} INFO -  at 1.4s,	estimator rf's best error=86.3469,	best estimator rf's best error=86.3469
[flaml.automl: 04-23 11:19:51] {3166} INFO - iteration 16, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:51] {3343} INFO -  at 1.5s,	estimator rf's best error=85.7314,	best estimator rf's best error=85.7314
[flaml.automl: 04-23 11:19:51] {3166} INFO - iteration 17, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:51] {3343} INFO -  at 1.8s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:51] {3166} INFO - iteration 18, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:52] {3343} INFO -  at 2.3s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:52] {3166} INFO - iteration 19, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:52] {3343} INFO -  at 2.5s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:52] {3166} INFO - iteration 20, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:53] {3343} INFO -  at 3.0s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:53] {3166} INFO - iteration 21, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:53] {3343} INFO -  at 3.2s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:53] {3166} INFO - iteration 22, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:53] {3343} INFO -  at 3.4s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:53] {3166} INFO - iteration 23, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:53] {3343} INFO -  at 3.8s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:53] {3166} INFO - iteration 24, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:54] {3343} INFO -  at 4.1s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:54] {3166} INFO - iteration 25, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:54] {3343} INFO -  at 4.3s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:54] {3166} INFO - iteration 26, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:54] {3343} INFO -  at 4.8s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:54] {3166} INFO - iteration 27, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:54] {3343} INFO -  at 4.9s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:54] {3166} INFO - iteration 28, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:55] {3343} INFO -  at 5.2s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:55] {3166} INFO - iteration 29, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:55] {3343} INFO -  at 5.4s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:55] {3166} INFO - iteration 30, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:55] {3343} INFO -  at 5.5s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:55] {3166} INFO - iteration 31, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:56] {3343} INFO -  at 6.1s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:56] {3166} INFO - iteration 32, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:56] {3343} INFO -  at 6.5s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:56] {3166} INFO - iteration 33, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:56] {3343} INFO -  at 6.8s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:56] {3166} INFO - iteration 34, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:57] {3343} INFO -  at 7.3s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:57] {3166} INFO - iteration 35, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:57] {3343} INFO -  at 7.4s,	estimator rf's best error=84.6713,	best estimator rf's best error=84.6713
[flaml.automl: 04-23 11:19:57] {3166} INFO - iteration 36, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:57] {3343} INFO -  at 7.6s,	estimator rf's best error=84.0426,	best estimator rf's best error=84.0426
[flaml.automl: 04-23 11:19:57] {3166} INFO - iteration 37, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:57] {3343} INFO -  at 7.9s,	estimator rf's best error=84.0426,	best estimator rf's best error=84.0426
[flaml.automl: 04-23 11:19:57] {3166} INFO - iteration 38, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:58] {3343} INFO -  at 8.1s,	estimator rf's best error=84.0426,	best estimator rf's best error=84.0426
[flaml.automl: 04-23 11:19:58] {3166} INFO - iteration 39, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:58] {3343} INFO -  at 8.2s,	estimator rf's best error=84.0426,	best estimator rf's best error=84.0426
[flaml.automl: 04-23 11:19:58] {3166} INFO - iteration 40, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:58] {3343} INFO -  at 8.4s,	estimator rf's best error=84.0426,	best estimator rf's best error=84.0426
[flaml.automl: 04-23 11:19:58] {3166} INFO - iteration 41, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:19:58] {3343} INFO -  at 8.5s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:19:58] {3166} INFO - iteration 42, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:58] {3343} INFO -  at 8.6s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:19:58] {3166} INFO - iteration 43, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:58] {3343} INFO -  at 8.8s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:19:58] {3166} INFO - iteration 44, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:58] {3343} INFO -  at 8.9s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:19:58] {3166} INFO - iteration 45, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:59] {3343} INFO -  at 9.0s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:19:59] {3166} INFO - iteration 46, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:59] {3343} INFO -  at 9.2s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:19:59] {3166} INFO - iteration 47, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:59] {3343} INFO -  at 9.2s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:19:59] {3166} INFO - iteration 48, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:59] {3343} INFO -  at 9.3s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:19:59] {3166} INFO - iteration 49, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:59] {3343} INFO -  at 9.5s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:19:59] {3166} INFO - iteration 50, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:59] {3343} INFO -  at 9.6s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:19:59] {3166} INFO - iteration 51, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:59] {3343} INFO -  at 9.7s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:19:59] {3166} INFO - iteration 52, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:59] {3343} INFO -  at 9.8s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:19:59] {3166} INFO - iteration 53, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:19:59] {3343} INFO -  at 9.9s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:19:59] {3166} INFO - iteration 54, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:00] {3343} INFO -  at 10.0s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837

[flaml.automl: 04-23 11:20:00] {3166} INFO - iteration 55, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:00] {3343} INFO -  at 10.1s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:00] {3166} INFO - iteration 56, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:00] {3343} INFO -  at 10.3s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:00] {3166} INFO - iteration 57, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:00] {3343} INFO -  at 10.4s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:00] {3166} INFO - iteration 58, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:00] {3343} INFO -  at 10.5s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:00] {3166} INFO - iteration 59, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:00] {3343} INFO -  at 10.6s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:00] {3166} INFO - iteration 60, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:00] {3343} INFO -  at 10.7s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:00] {3166} INFO - iteration 61, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:00] {3343} INFO -  at 10.8s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:00] {3166} INFO - iteration 62, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:01] {3343} INFO -  at 11.0s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:01] {3166} INFO - iteration 63, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:01] {3343} INFO -  at 11.0s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:01] {3166} INFO - iteration 64, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:01] {3343} INFO -  at 11.1s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:01] {3166} INFO - iteration 65, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:01] {3343} INFO -  at 11.3s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:01] {3166} INFO - iteration 66, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:01] {3343} INFO -  at 11.4s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:01] {3166} INFO - iteration 67, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:01] {3343} INFO -  at 11.5s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:01] {3166} INFO - iteration 68, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:01] {3343} INFO -  at 11.6s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:01] {3166} INFO - iteration 69, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:01] {3343} INFO -  at 11.7s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:01] {3166} INFO - iteration 70, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:01] {3343} INFO -  at 11.8s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:01] {3166} INFO - iteration 71, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:01] {3343} INFO -  at 11.9s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:01] {3166} INFO - iteration 72, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:02] {3343} INFO -  at 12.0s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:02] {3166} INFO - iteration 73, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:02] {3343} INFO -  at 12.2s,	estimator rf's best error=83.6837,	best estimator rf's best error=83.6837
[flaml.automl: 04-23 11:20:02] {3166} INFO - iteration 74, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:02] {3343} INFO -  at 12.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:02] {3166} INFO - iteration 75, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:02] {3343} INFO -  at 12.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:02] {3166} INFO - iteration 76, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:02] {3343} INFO -  at 12.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:02] {3166} INFO - iteration 77, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:02] {3343} INFO -  at 12.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:02] {3166} INFO - iteration 78, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:02] {3343} INFO -  at 12.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:02] {3166} INFO - iteration 79, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:02] {3343} INFO -  at 12.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:02] {3166} INFO - iteration 80, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:02] {3343} INFO -  at 12.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:02] {3166} INFO - iteration 81, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:03] {3343} INFO -  at 13.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:03] {3166} INFO - iteration 82, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:03] {3343} INFO -  at 13.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:03] {3166} INFO - iteration 83, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:03] {3343} INFO -  at 13.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:03] {3166} INFO - iteration 84, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:03] {3343} INFO -  at 13.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:03] {3166} INFO - iteration 85, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:03] {3343} INFO -  at 13.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:03] {3166} INFO - iteration 86, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:03] {3343} INFO -  at 13.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:03] {3166} INFO - iteration 87, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:03] {3343} INFO -  at 13.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:03] {3166} INFO - iteration 88, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:04] {3343} INFO -  at 14.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:04] {3166} INFO - iteration 89, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:04] {3343} INFO -  at 14.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:04] {3166} INFO - iteration 90, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:04] {3343} INFO -  at 14.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:04] {3166} INFO - iteration 91, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:04] {3343} INFO -  at 14.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:04] {3166} INFO - iteration 92, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:04] {3343} INFO -  at 14.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:04] {3166} INFO - iteration 93, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:04] {3343} INFO -  at 14.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:04] {3166} INFO - iteration 94, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:04] {3343} INFO -  at 14.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:04] {3166} INFO - iteration 95, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:04] {3343} INFO -  at 14.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:04] {3166} INFO - iteration 96, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:05] {3343} INFO -  at 15.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:05] {3166} INFO - iteration 97, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:05] {3343} INFO -  at 15.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:05] {3166} INFO - iteration 98, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:05] {3343} INFO -  at 15.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:05] {3166} INFO - iteration 99, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:05] {3343} INFO -  at 15.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:05] {3166} INFO - iteration 100, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:05] {3343} INFO -  at 15.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:05] {3166} INFO - iteration 101, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:05] {3343} INFO -  at 15.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:05] {3166} INFO - iteration 102, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:05] {3343} INFO -  at 15.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:05] {3166} INFO - iteration 103, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:05] {3343} INFO -  at 15.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:05] {3166} INFO - iteration 104, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:05] {3343} INFO -  at 15.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:05] {3166} INFO - iteration 105, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:05] {3343} INFO -  at 15.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:05] {3166} INFO - iteration 106, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:05] {3343} INFO -  at 15.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:05] {3166} INFO - iteration 107, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:06] {3343} INFO -  at 16.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:06] {3166} INFO - iteration 108, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:06] {3343} INFO -  at 16.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:06] {3166} INFO - iteration 109, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:06] {3343} INFO -  at 16.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:06] {3166} INFO - iteration 110, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:06] {3343} INFO -  at 16.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:06] {3166} INFO - iteration 111, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:06] {3343} INFO -  at 16.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:06] {3166} INFO - iteration 112, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:06] {3343} INFO -  at 16.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:06] {3166} INFO - iteration 113, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:06] {3343} INFO -  at 16.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:06] {3166} INFO - iteration 114, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:06] {3343} INFO -  at 16.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:06] {3166} INFO - iteration 115, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:06] {3343} INFO -  at 16.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:06] {3166} INFO - iteration 116, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:07] {3343} INFO -  at 17.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:07] {3166} INFO - iteration 117, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:07] {3343} INFO -  at 17.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:07] {3166} INFO - iteration 118, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:07] {3343} INFO -  at 17.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:07] {3166} INFO - iteration 119, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:07] {3343} INFO -  at 17.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:07] {3166} INFO - iteration 120, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:07] {3343} INFO -  at 17.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:07] {3166} INFO - iteration 121, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:07] {3343} INFO -  at 17.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:07] {3166} INFO - iteration 122, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:07] {3343} INFO -  at 17.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:07] {3166} INFO - iteration 123, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:07] {3343} INFO -  at 17.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:07] {3166} INFO - iteration 124, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:07] {3343} INFO -  at 17.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:07] {3166} INFO - iteration 125, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:08] {3343} INFO -  at 18.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:08] {3166} INFO - iteration 126, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:08] {3343} INFO -  at 18.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:08] {3166} INFO - iteration 127, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:08] {3343} INFO -  at 18.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:08] {3166} INFO - iteration 128, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:08] {3343} INFO -  at 18.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:08] {3166} INFO - iteration 129, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:08] {3343} INFO -  at 18.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:08] {3166} INFO - iteration 130, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:08] {3343} INFO -  at 18.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:08] {3166} INFO - iteration 131, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:08] {3343} INFO -  at 18.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:08] {3166} INFO - iteration 132, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:08] {3343} INFO -  at 18.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:08] {3166} INFO - iteration 133, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:08] {3343} INFO -  at 18.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:08] {3166} INFO - iteration 134, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:09] {3343} INFO -  at 19.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:09] {3166} INFO - iteration 135, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:09] {3343} INFO -  at 19.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:09] {3166} INFO - iteration 136, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:09] {3343} INFO -  at 19.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:09] {3166} INFO - iteration 137, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:09] {3343} INFO -  at 19.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:09] {3166} INFO - iteration 138, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:09] {3343} INFO -  at 19.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:09] {3166} INFO - iteration 139, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:09] {3343} INFO -  at 19.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:09] {3166} INFO - iteration 140, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:09] {3343} INFO -  at 19.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:09] {3166} INFO - iteration 141, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:09] {3343} INFO -  at 19.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:09] {3166} INFO - iteration 142, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:09] {3343} INFO -  at 19.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:09] {3166} INFO - iteration 143, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:10] {3343} INFO -  at 20.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:10] {3166} INFO - iteration 144, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:10] {3343} INFO -  at 20.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:10] {3166} INFO - iteration 145, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:10] {3343} INFO -  at 20.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:10] {3166} INFO - iteration 146, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:10] {3343} INFO -  at 20.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:10] {3166} INFO - iteration 147, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:10] {3343} INFO -  at 20.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:10] {3166} INFO - iteration 148, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:10] {3343} INFO -  at 20.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:10] {3166} INFO - iteration 149, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:10] {3343} INFO -  at 20.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:10] {3166} INFO - iteration 150, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:10] {3343} INFO -  at 20.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:10] {3166} INFO - iteration 151, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:10] {3343} INFO -  at 20.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:10] {3166} INFO - iteration 152, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:11] {3343} INFO -  at 21.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:11] {3166} INFO - iteration 153, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:11] {3343} INFO -  at 21.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:11] {3166} INFO - iteration 154, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:11] {3343} INFO -  at 21.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:11] {3166} INFO - iteration 155, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:11] {3343} INFO -  at 21.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:11] {3166} INFO - iteration 156, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:11] {3343} INFO -  at 21.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:11] {3166} INFO - iteration 157, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:11] {3343} INFO -  at 21.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:11] {3166} INFO - iteration 158, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:11] {3343} INFO -  at 21.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:11] {3166} INFO - iteration 159, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:11] {3343} INFO -  at 21.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:11] {3166} INFO - iteration 160, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:12] {3343} INFO -  at 22.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:12] {3166} INFO - iteration 161, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:12] {3343} INFO -  at 22.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:12] {3166} INFO - iteration 162, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:12] {3343} INFO -  at 22.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:12] {3166} INFO - iteration 163, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:12] {3343} INFO -  at 22.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:12] {3166} INFO - iteration 164, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:12] {3343} INFO -  at 22.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:12] {3166} INFO - iteration 165, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:12] {3343} INFO -  at 22.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:12] {3166} INFO - iteration 166, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:12] {3343} INFO -  at 22.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:12] {3166} INFO - iteration 167, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:12] {3343} INFO -  at 22.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:12] {3166} INFO - iteration 168, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:13] {3343} INFO -  at 23.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:13] {3166} INFO - iteration 169, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:13] {3343} INFO -  at 23.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:13] {3166} INFO - iteration 170, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:13] {3343} INFO -  at 23.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:13] {3166} INFO - iteration 171, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:13] {3343} INFO -  at 23.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:13] {3166} INFO - iteration 172, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:13] {3343} INFO -  at 23.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:13] {3166} INFO - iteration 173, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:13] {3343} INFO -  at 23.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:13] {3166} INFO - iteration 174, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:13] {3343} INFO -  at 23.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:13] {3166} INFO - iteration 175, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:13] {3343} INFO -  at 23.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:13] {3166} INFO - iteration 176, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:13] {3343} INFO -  at 23.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:13] {3166} INFO - iteration 177, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:14] {3343} INFO -  at 24.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:14] {3166} INFO - iteration 178, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:14] {3343} INFO -  at 24.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:14] {3166} INFO - iteration 179, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:14] {3343} INFO -  at 24.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:14] {3166} INFO - iteration 180, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:14] {3343} INFO -  at 24.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:14] {3166} INFO - iteration 181, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:14] {3343} INFO -  at 24.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:14] {3166} INFO - iteration 182, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:14] {3343} INFO -  at 24.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:14] {3166} INFO - iteration 183, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:14] {3343} INFO -  at 24.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:14] {3166} INFO - iteration 184, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:14] {3343} INFO -  at 24.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:14] {3166} INFO - iteration 185, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:14] {3343} INFO -  at 24.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:15] {3166} INFO - iteration 186, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:15] {3343} INFO -  at 25.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:15] {3166} INFO - iteration 187, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:15] {3343} INFO -  at 25.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:15] {3166} INFO - iteration 188, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:15] {3343} INFO -  at 25.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:15] {3166} INFO - iteration 189, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:15] {3343} INFO -  at 25.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:15] {3166} INFO - iteration 190, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:15] {3343} INFO -  at 25.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:15] {3166} INFO - iteration 191, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:15] {3343} INFO -  at 25.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:15] {3166} INFO - iteration 192, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:15] {3343} INFO -  at 25.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:15] {3166} INFO - iteration 193, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:15] {3343} INFO -  at 25.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:15] {3166} INFO - iteration 194, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:15] {3343} INFO -  at 25.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:15] {3166} INFO - iteration 195, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:16] {3343} INFO -  at 26.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:16] {3166} INFO - iteration 196, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:16] {3343} INFO -  at 26.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:16] {3166} INFO - iteration 197, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:16] {3343} INFO -  at 26.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632

[flaml.automl: 04-23 11:20:16] {3166} INFO - iteration 198, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:16] {3343} INFO -  at 26.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:16] {3166} INFO - iteration 199, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:16] {3343} INFO -  at 26.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:16] {3166} INFO - iteration 200, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:16] {3343} INFO -  at 26.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:16] {3166} INFO - iteration 201, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:16] {3343} INFO -  at 26.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:16] {3166} INFO - iteration 202, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:16] {3343} INFO -  at 26.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:16] {3166} INFO - iteration 203, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:16] {3343} INFO -  at 26.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:16] {3166} INFO - iteration 204, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:16] {3343} INFO -  at 26.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:16] {3166} INFO - iteration 205, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:17] {3343} INFO -  at 27.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:17] {3166} INFO - iteration 206, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:17] {3343} INFO -  at 27.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:17] {3166} INFO - iteration 207, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:17] {3343} INFO -  at 27.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:17] {3166} INFO - iteration 208, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:17] {3343} INFO -  at 27.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:17] {3166} INFO - iteration 209, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:17] {3343} INFO -  at 27.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:17] {3166} INFO - iteration 210, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:17] {3343} INFO -  at 27.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:17] {3166} INFO - iteration 211, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:17] {3343} INFO -  at 27.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:17] {3166} INFO - iteration 212, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:17] {3343} INFO -  at 27.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:17] {3166} INFO - iteration 213, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:17] {3343} INFO -  at 27.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:17] {3166} INFO - iteration 214, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:17] {3343} INFO -  at 27.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:17] {3166} INFO - iteration 215, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:18] {3343} INFO -  at 28.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:18] {3166} INFO - iteration 216, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:18] {3343} INFO -  at 28.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:18] {3166} INFO - iteration 217, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:18] {3343} INFO -  at 28.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:18] {3166} INFO - iteration 218, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:18] {3343} INFO -  at 28.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:18] {3166} INFO - iteration 219, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:18] {3343} INFO -  at 28.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:18] {3166} INFO - iteration 220, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:18] {3343} INFO -  at 28.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:18] {3166} INFO - iteration 221, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:18] {3343} INFO -  at 28.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:18] {3166} INFO - iteration 222, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:18] {3343} INFO -  at 28.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:18] {3166} INFO - iteration 223, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:18] {3343} INFO -  at 28.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632

[flaml.automl: 04-23 11:20:18] {3166} INFO - iteration 224, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:18] {3343} INFO -  at 28.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:18] {3166} INFO - iteration 225, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:19] {3343} INFO -  at 29.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:19] {3166} INFO - iteration 226, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:19] {3343} INFO -  at 29.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:19] {3166} INFO - iteration 227, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:19] {3343} INFO -  at 29.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:19] {3166} INFO - iteration 228, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:19] {3343} INFO -  at 29.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:19] {3166} INFO - iteration 229, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:19] {3343} INFO -  at 29.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:19] {3166} INFO - iteration 230, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:19] {3343} INFO -  at 29.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:19] {3166} INFO - iteration 231, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:19] {3343} INFO -  at 29.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:19] {3166} INFO - iteration 232, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:19] {3343} INFO -  at 29.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:19] {3166} INFO - iteration 233, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:19] {3343} INFO -  at 29.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:19] {3166} INFO - iteration 234, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:19] {3343} INFO -  at 29.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:19] {3166} INFO - iteration 235, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:20] {3343} INFO -  at 30.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:20] {3166} INFO - iteration 236, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:20] {3343} INFO -  at 30.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:20] {3166} INFO - iteration 237, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:20] {3343} INFO -  at 30.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:20] {3166} INFO - iteration 238, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:20] {3343} INFO -  at 30.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:20] {3166} INFO - iteration 239, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:20] {3343} INFO -  at 30.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:20] {3166} INFO - iteration 240, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:20] {3343} INFO -  at 30.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:20] {3166} INFO - iteration 241, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:20] {3343} INFO -  at 30.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:20] {3166} INFO - iteration 242, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:20] {3343} INFO -  at 30.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:20] {3166} INFO - iteration 243, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:20] {3343} INFO -  at 30.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:20] {3166} INFO - iteration 244, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:20] {3343} INFO -  at 30.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:20] {3166} INFO - iteration 245, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:21] {3343} INFO -  at 31.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:21] {3166} INFO - iteration 246, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:21] {3343} INFO -  at 31.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:21] {3166} INFO - iteration 247, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:21] {3343} INFO -  at 31.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:21] {3166} INFO - iteration 248, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:21] {3343} INFO -  at 31.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:21] {3166} INFO - iteration 249, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:21] {3343} INFO -  at 31.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:21] {3166} INFO - iteration 250, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:21] {3343} INFO -  at 31.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:21] {3166} INFO - iteration 251, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:21] {3343} INFO -  at 31.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:21] {3166} INFO - iteration 252, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:21] {3343} INFO -  at 31.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:21] {3166} INFO - iteration 253, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:21] {3343} INFO -  at 31.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:21] {3166} INFO - iteration 254, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:22] {3343} INFO -  at 32.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:22] {3166} INFO - iteration 255, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:22] {3343} INFO -  at 32.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:22] {3166} INFO - iteration 256, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:22] {3343} INFO -  at 32.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:22] {3166} INFO - iteration 257, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:22] {3343} INFO -  at 32.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:22] {3166} INFO - iteration 258, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:22] {3343} INFO -  at 32.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:22] {3166} INFO - iteration 259, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:22] {3343} INFO -  at 32.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:22] {3166} INFO - iteration 260, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:22] {3343} INFO -  at 32.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:22] {3166} INFO - iteration 261, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:22] {3343} INFO -  at 32.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:22] {3166} INFO - iteration 262, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:22] {3343} INFO -  at 32.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632

[flaml.automl: 04-23 11:20:22] {3166} INFO - iteration 263, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:23] {3343} INFO -  at 32.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:23] {3166} INFO - iteration 264, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:23] {3343} INFO -  at 33.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:23] {3166} INFO - iteration 265, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:23] {3343} INFO -  at 33.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:23] {3166} INFO - iteration 266, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:23] {3343} INFO -  at 33.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:23] {3166} INFO - iteration 267, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:23] {3343} INFO -  at 33.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:23] {3166} INFO - iteration 268, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:23] {3343} INFO -  at 33.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:23] {3166} INFO - iteration 269, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:23] {3343} INFO -  at 33.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:23] {3166} INFO - iteration 270, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:23] {3343} INFO -  at 33.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:23] {3166} INFO - iteration 271, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:23] {3343} INFO -  at 33.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:23] {3166} INFO - iteration 272, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:23] {3343} INFO -  at 33.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:23] {3166} INFO - iteration 273, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:24] {3343} INFO -  at 34.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:24] {3166} INFO - iteration 274, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:24] {3343} INFO -  at 34.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:24] {3166} INFO - iteration 275, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:24] {3343} INFO -  at 34.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:24] {3166} INFO - iteration 276, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:24] {3343} INFO -  at 34.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:24] {3166} INFO - iteration 277, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:24] {3343} INFO -  at 34.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:24] {3166} INFO - iteration 278, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:24] {3343} INFO -  at 34.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:24] {3166} INFO - iteration 279, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:24] {3343} INFO -  at 34.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:24] {3166} INFO - iteration 280, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:24] {3343} INFO -  at 34.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:24] {3166} INFO - iteration 281, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:24] {3343} INFO -  at 34.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:24] {3166} INFO - iteration 282, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:24] {3343} INFO -  at 34.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:24] {3166} INFO - iteration 283, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:25] {3343} INFO -  at 35.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:25] {3166} INFO - iteration 284, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:25] {3343} INFO -  at 35.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:25] {3166} INFO - iteration 285, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:25] {3343} INFO -  at 35.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:25] {3166} INFO - iteration 286, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:25] {3343} INFO -  at 35.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:25] {3166} INFO - iteration 287, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:25] {3343} INFO -  at 35.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:25] {3166} INFO - iteration 288, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:25] {3343} INFO -  at 35.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:25] {3166} INFO - iteration 289, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:25] {3343} INFO -  at 35.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:25] {3166} INFO - iteration 290, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:25] {3343} INFO -  at 35.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:25] {3166} INFO - iteration 291, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:25] {3343} INFO -  at 35.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:25] {3166} INFO - iteration 292, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:25] {3343} INFO -  at 35.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:25] {3166} INFO - iteration 293, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:26] {3343} INFO -  at 36.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:26] {3166} INFO - iteration 294, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:26] {3343} INFO -  at 36.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:26] {3166} INFO - iteration 295, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:26] {3343} INFO -  at 36.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:26] {3166} INFO - iteration 296, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:26] {3343} INFO -  at 36.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:26] {3166} INFO - iteration 297, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:26] {3343} INFO -  at 36.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:26] {3166} INFO - iteration 298, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:26] {3343} INFO -  at 36.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:26] {3166} INFO - iteration 299, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:26] {3343} INFO -  at 36.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:26] {3166} INFO - iteration 300, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:26] {3343} INFO -  at 36.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:26] {3166} INFO - iteration 301, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:26] {3343} INFO -  at 36.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:26] {3166} INFO - iteration 302, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:26] {3343} INFO -  at 36.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:26] {3166} INFO - iteration 303, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:27] {3343} INFO -  at 36.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:27] {3166} INFO - iteration 304, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:27] {3343} INFO -  at 37.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:27] {3166} INFO - iteration 305, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:27] {3343} INFO -  at 37.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:27] {3166} INFO - iteration 306, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:27] {3343} INFO -  at 37.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:27] {3166} INFO - iteration 307, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:27] {3343} INFO -  at 37.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:27] {3166} INFO - iteration 308, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:27] {3343} INFO -  at 37.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:27] {3166} INFO - iteration 309, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:27] {3343} INFO -  at 37.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:27] {3166} INFO - iteration 310, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:27] {3343} INFO -  at 37.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:27] {3166} INFO - iteration 311, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:27] {3343} INFO -  at 37.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:27] {3166} INFO - iteration 312, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:27] {3343} INFO -  at 37.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:27] {3166} INFO - iteration 313, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:27] {3343} INFO -  at 37.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:27] {3166} INFO - iteration 314, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:28] {3343} INFO -  at 38.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:28] {3166} INFO - iteration 315, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:28] {3343} INFO -  at 38.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:28] {3166} INFO - iteration 316, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:28] {3343} INFO -  at 38.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:28] {3166} INFO - iteration 317, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:28] {3343} INFO -  at 38.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:28] {3166} INFO - iteration 318, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:28] {3343} INFO -  at 38.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:28] {3166} INFO - iteration 319, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:28] {3343} INFO -  at 38.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:28] {3166} INFO - iteration 320, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:28] {3343} INFO -  at 38.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:28] {3166} INFO - iteration 321, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:28] {3343} INFO -  at 38.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:28] {3166} INFO - iteration 322, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:28] {3343} INFO -  at 38.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:28] {3166} INFO - iteration 323, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:28] {3343} INFO -  at 38.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:28] {3166} INFO - iteration 324, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:29] {3343} INFO -  at 39.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:29] {3166} INFO - iteration 325, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:29] {3343} INFO -  at 39.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:29] {3166} INFO - iteration 326, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:29] {3343} INFO -  at 39.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:29] {3166} INFO - iteration 327, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:29] {3343} INFO -  at 39.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:29] {3166} INFO - iteration 328, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:29] {3343} INFO -  at 39.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:29] {3166} INFO - iteration 329, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:29] {3343} INFO -  at 39.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:29] {3166} INFO - iteration 330, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:29] {3343} INFO -  at 39.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:29] {3166} INFO - iteration 331, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:29] {3343} INFO -  at 39.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:29] {3166} INFO - iteration 332, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:29] {3343} INFO -  at 39.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:29] {3166} INFO - iteration 333, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:29] {3343} INFO -  at 39.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:29] {3166} INFO - iteration 334, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:30] {3343} INFO -  at 40.0s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:30] {3166} INFO - iteration 335, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:30] {3343} INFO -  at 40.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:30] {3166} INFO - iteration 336, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:30] {3343} INFO -  at 40.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:30] {3166} INFO - iteration 337, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:30] {3343} INFO -  at 40.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:30] {3166} INFO - iteration 338, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:30] {3343} INFO -  at 40.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:30] {3166} INFO - iteration 339, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:30] {3343} INFO -  at 40.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:30] {3166} INFO - iteration 340, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:30] {3343} INFO -  at 40.7s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:30] {3166} INFO - iteration 341, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:30] {3343} INFO -  at 40.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:30] {3166} INFO - iteration 342, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:30] {3343} INFO -  at 40.9s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:30] {3166} INFO - iteration 343, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:31] {3343} INFO -  at 41.1s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:31] {3166} INFO - iteration 344, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:31] {3343} INFO -  at 41.2s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:31] {3166} INFO - iteration 345, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:31] {3343} INFO -  at 41.3s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:31] {3166} INFO - iteration 346, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:31] {3343} INFO -  at 41.4s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:31] {3166} INFO - iteration 347, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:31] {3343} INFO -  at 41.5s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:31] {3166} INFO - iteration 348, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:31] {3343} INFO -  at 41.6s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:31] {3166} INFO - iteration 349, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:31] {3343} INFO -  at 41.8s,	estimator rf's best error=82.6632,	best estimator rf's best error=82.6632
[flaml.automl: 04-23 11:20:31] {3166} INFO - iteration 350, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:31] {3343} INFO -  at 41.9s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:31] {3166} INFO - iteration 351, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:32] {3343} INFO -  at 42.0s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:32] {3166} INFO - iteration 352, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:32] {3343} INFO -  at 42.2s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:32] {3166} INFO - iteration 353, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:32] {3343} INFO -  at 42.2s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:32] {3166} INFO - iteration 354, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:32] {3343} INFO -  at 42.3s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:32] {3166} INFO - iteration 355, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:32] {3343} INFO -  at 42.5s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:32] {3166} INFO - iteration 356, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:32] {3343} INFO -  at 42.6s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:32] {3166} INFO - iteration 357, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:32] {3343} INFO -  at 42.7s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:32] {3166} INFO - iteration 358, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:32] {3343} INFO -  at 42.8s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:32] {3166} INFO - iteration 359, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:33] {3343} INFO -  at 43.0s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:33] {3166} INFO - iteration 360, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:33] {3343} INFO -  at 43.0s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:33] {3166} INFO - iteration 361, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:33] {3343} INFO -  at 43.1s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:33] {3166} INFO - iteration 362, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:33] {3343} INFO -  at 43.2s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:33] {3166} INFO - iteration 363, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:33] {3343} INFO -  at 43.3s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:33] {3166} INFO - iteration 364, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:33] {3343} INFO -  at 43.5s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:33] {3166} INFO - iteration 365, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:33] {3343} INFO -  at 43.6s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:33] {3166} INFO - iteration 366, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:33] {3343} INFO -  at 43.7s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:33] {3166} INFO - iteration 367, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:33] {3343} INFO -  at 43.9s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:33] {3166} INFO - iteration 368, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:34] {3343} INFO -  at 43.9s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:34] {3166} INFO - iteration 369, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:34] {3343} INFO -  at 44.1s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:34] {3166} INFO - iteration 370, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:34] {3343} INFO -  at 44.2s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:34] {3166} INFO - iteration 371, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:34] {3343} INFO -  at 44.3s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:34] {3166} INFO - iteration 372, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:34] {3343} INFO -  at 44.4s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:34] {3166} INFO - iteration 373, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:34] {3343} INFO -  at 44.5s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:34] {3166} INFO - iteration 374, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:34] {3343} INFO -  at 44.7s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:34] {3166} INFO - iteration 375, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:34] {3343} INFO -  at 44.8s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:34] {3166} INFO - iteration 376, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:35] {3343} INFO -  at 44.9s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:35] {3166} INFO - iteration 377, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:35] {3343} INFO -  at 45.1s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:35] {3166} INFO - iteration 378, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:35] {3343} INFO -  at 45.2s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:35] {3166} INFO - iteration 379, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:35] {3343} INFO -  at 45.3s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:35] {3166} INFO - iteration 380, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:35] {3343} INFO -  at 45.4s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:35] {3166} INFO - iteration 381, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:35] {3343} INFO -  at 45.5s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:35] {3166} INFO - iteration 382, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:35] {3343} INFO -  at 45.6s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:35] {3166} INFO - iteration 383, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:36] {3343} INFO -  at 45.9s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:36] {3166} INFO - iteration 384, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:36] {3343} INFO -  at 46.1s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:36] {3166} INFO - iteration 385, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:36] {3343} INFO -  at 46.3s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:36] {3166} INFO - iteration 386, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:36] {3343} INFO -  at 46.5s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:36] {3166} INFO - iteration 387, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:36] {3343} INFO -  at 46.7s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:36] {3166} INFO - iteration 388, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:36] {3343} INFO -  at 46.9s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:36] {3166} INFO - iteration 389, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:37] {3343} INFO -  at 47.1s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:37] {3166} INFO - iteration 390, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:37] {3343} INFO -  at 47.2s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:37] {3166} INFO - iteration 391, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:37] {3343} INFO -  at 47.3s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:37] {3166} INFO - iteration 392, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:37] {3343} INFO -  at 47.4s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:37] {3166} INFO - iteration 393, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:37] {3343} INFO -  at 47.5s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:37] {3166} INFO - iteration 394, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:37] {3343} INFO -  at 47.6s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:37] {3166} INFO - iteration 395, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:37] {3343} INFO -  at 47.7s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:37] {3166} INFO - iteration 396, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:37] {3343} INFO -  at 47.8s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:37] {3166} INFO - iteration 397, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:37] {3343} INFO -  at 47.9s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:37] {3166} INFO - iteration 398, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:38] {3343} INFO -  at 48.0s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:38] {3166} INFO - iteration 399, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:38] {3343} INFO -  at 48.0s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:38] {3166} INFO - iteration 400, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:38] {3343} INFO -  at 48.1s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:38] {3166} INFO - iteration 401, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:38] {3343} INFO -  at 48.2s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:38] {3166} INFO - iteration 402, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:38] {3343} INFO -  at 48.3s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:38] {3166} INFO - iteration 403, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:38] {3343} INFO -  at 48.4s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:38] {3166} INFO - iteration 404, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:38] {3343} INFO -  at 48.5s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:38] {3166} INFO - iteration 405, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:38] {3343} INFO -  at 48.5s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:38] {3166} INFO - iteration 406, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:38] {3343} INFO -  at 48.6s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:38] {3166} INFO - iteration 407, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:38] {3343} INFO -  at 48.7s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:38] {3166} INFO - iteration 408, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:38] {3343} INFO -  at 48.8s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:38] {3166} INFO - iteration 409, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:38] {3343} INFO -  at 48.9s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:38] {3166} INFO - iteration 410, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:39] {3343} INFO -  at 49.0s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:39] {3166} INFO - iteration 411, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:39] {3343} INFO -  at 49.1s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:39] {3166} INFO - iteration 412, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:39] {3343} INFO -  at 49.2s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:39] {3166} INFO - iteration 413, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:39] {3343} INFO -  at 49.4s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:39] {3166} INFO - iteration 414, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:39] {3343} INFO -  at 49.4s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:39] {3166} INFO - iteration 415, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:39] {3343} INFO -  at 49.5s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:39] {3166} INFO - iteration 416, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:39] {3343} INFO -  at 49.6s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:39] {3166} INFO - iteration 417, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:39] {3343} INFO -  at 49.7s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:39] {3166} INFO - iteration 418, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:39] {3343} INFO -  at 49.8s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:39] {3166} INFO - iteration 419, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:39] {3343} INFO -  at 49.9s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:39] {3166} INFO - iteration 420, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:40] {3343} INFO -  at 50.0s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:40] {3166} INFO - iteration 421, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:40] {3343} INFO -  at 50.1s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:40] {3166} INFO - iteration 422, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:40] {3343} INFO -  at 50.2s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:40] {3166} INFO - iteration 423, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:40] {3343} INFO -  at 50.3s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:40] {3166} INFO - iteration 424, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:40] {3343} INFO -  at 50.4s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:40] {3166} INFO - iteration 425, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:40] {3343} INFO -  at 50.5s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:40] {3166} INFO - iteration 426, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:40] {3343} INFO -  at 50.6s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:40] {3166} INFO - iteration 427, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:40] {3343} INFO -  at 50.7s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:40] {3166} INFO - iteration 428, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:40] {3343} INFO -  at 50.8s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:40] {3166} INFO - iteration 429, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:40] {3343} INFO -  at 50.9s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:40] {3166} INFO - iteration 430, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:41] {3343} INFO -  at 51.0s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:41] {3166} INFO - iteration 431, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:41] {3343} INFO -  at 51.1s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472

[flaml.automl: 04-23 11:20:41] {3166} INFO - iteration 432, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:41] {3343} INFO -  at 51.2s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:41] {3166} INFO - iteration 433, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:41] {3343} INFO -  at 51.3s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:41] {3166} INFO - iteration 434, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:41] {3343} INFO -  at 51.4s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:41] {3166} INFO - iteration 435, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:41] {3343} INFO -  at 51.6s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:41] {3166} INFO - iteration 436, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:41] {3343} INFO -  at 51.7s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:41] {3166} INFO - iteration 437, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:41] {3343} INFO -  at 51.8s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:41] {3166} INFO - iteration 438, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:42] {3343} INFO -  at 52.0s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:42] {3166} INFO - iteration 439, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:42] {3343} INFO -  at 52.1s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:42] {3166} INFO - iteration 440, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:42] {3343} INFO -  at 52.2s,	estimator rf's best error=82.4472,	best estimator rf's best error=82.4472
[flaml.automl: 04-23 11:20:42] {3166} INFO - iteration 441, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:42] {3343} INFO -  at 52.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:42] {3166} INFO - iteration 442, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:42] {3343} INFO -  at 52.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:42] {3166} INFO - iteration 443, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:42] {3343} INFO -  at 52.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:42] {3166} INFO - iteration 444, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:42] {3343} INFO -  at 52.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:42] {3166} INFO - iteration 445, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:42] {3343} INFO -  at 52.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:42] {3166} INFO - iteration 446, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:43] {3343} INFO -  at 53.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:43] {3166} INFO - iteration 447, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:43] {3343} INFO -  at 53.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:43] {3166} INFO - iteration 448, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:43] {3343} INFO -  at 53.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:43] {3166} INFO - iteration 449, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:43] {3343} INFO -  at 53.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:43] {3166} INFO - iteration 450, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:44] {3343} INFO -  at 54.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:44] {3166} INFO - iteration 451, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:44] {3343} INFO -  at 54.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:44] {3166} INFO - iteration 452, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:44] {3343} INFO -  at 54.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:44] {3166} INFO - iteration 453, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:44] {3343} INFO -  at 54.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:44] {3166} INFO - iteration 454, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:45] {3343} INFO -  at 55.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:45] {3166} INFO - iteration 455, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:45] {3343} INFO -  at 55.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:45] {3166} INFO - iteration 456, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:45] {3343} INFO -  at 55.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:45] {3166} INFO - iteration 457, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:45] {3343} INFO -  at 55.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:45] {3166} INFO - iteration 458, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:45] {3343} INFO -  at 55.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:45] {3166} INFO - iteration 459, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:45] {3343} INFO -  at 55.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:45] {3166} INFO - iteration 460, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:45] {3343} INFO -  at 55.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:45] {3166} INFO - iteration 461, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:45] {3343} INFO -  at 55.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:45] {3166} INFO - iteration 462, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:46] {3343} INFO -  at 56.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:46] {3166} INFO - iteration 463, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:46] {3343} INFO -  at 56.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:46] {3166} INFO - iteration 464, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:46] {3343} INFO -  at 56.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:46] {3166} INFO - iteration 465, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:46] {3343} INFO -  at 56.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:46] {3166} INFO - iteration 466, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:46] {3343} INFO -  at 56.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:46] {3166} INFO - iteration 467, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:46] {3343} INFO -  at 56.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:46] {3166} INFO - iteration 468, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:46] {3343} INFO -  at 56.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:46] {3166} INFO - iteration 469, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:46] {3343} INFO -  at 56.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:46] {3166} INFO - iteration 470, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:46] {3343} INFO -  at 56.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:46] {3166} INFO - iteration 471, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:47] {3343} INFO -  at 57.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:47] {3166} INFO - iteration 472, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:47] {3343} INFO -  at 57.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:47] {3166} INFO - iteration 473, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:47] {3343} INFO -  at 57.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:47] {3166} INFO - iteration 474, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:47] {3343} INFO -  at 57.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:47] {3166} INFO - iteration 475, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:47] {3343} INFO -  at 57.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:47] {3166} INFO - iteration 476, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:47] {3343} INFO -  at 57.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:47] {3166} INFO - iteration 477, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:47] {3343} INFO -  at 57.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:47] {3166} INFO - iteration 478, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:47] {3343} INFO -  at 57.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:47] {3166} INFO - iteration 479, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:47] {3343} INFO -  at 57.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:47] {3166} INFO - iteration 480, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:48] {3343} INFO -  at 57.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:48] {3166} INFO - iteration 481, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:48] {3343} INFO -  at 58.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:48] {3166} INFO - iteration 482, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:48] {3343} INFO -  at 58.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:48] {3166} INFO - iteration 483, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:48] {3343} INFO -  at 58.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:48] {3166} INFO - iteration 484, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:48] {3343} INFO -  at 58.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:48] {3166} INFO - iteration 485, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:48] {3343} INFO -  at 58.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:48] {3166} INFO - iteration 486, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:48] {3343} INFO -  at 58.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:48] {3166} INFO - iteration 487, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:48] {3343} INFO -  at 58.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:48] {3166} INFO - iteration 488, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:48] {3343} INFO -  at 58.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:48] {3166} INFO - iteration 489, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:48] {3343} INFO -  at 58.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:48] {3166} INFO - iteration 490, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:48] {3343} INFO -  at 58.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:48] {3166} INFO - iteration 491, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:49] {3343} INFO -  at 59.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:49] {3166} INFO - iteration 492, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:49] {3343} INFO -  at 59.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:49] {3166} INFO - iteration 493, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:49] {3343} INFO -  at 59.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:49] {3166} INFO - iteration 494, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:49] {3343} INFO -  at 59.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:49] {3166} INFO - iteration 495, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:49] {3343} INFO -  at 59.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:49] {3166} INFO - iteration 496, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:49] {3343} INFO -  at 59.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:49] {3166} INFO - iteration 497, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:49] {3343} INFO -  at 59.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:49] {3166} INFO - iteration 498, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:49] {3343} INFO -  at 59.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:49] {3166} INFO - iteration 499, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:49] {3343} INFO -  at 59.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:49] {3166} INFO - iteration 500, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:49] {3343} INFO -  at 59.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:49] {3166} INFO - iteration 501, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:50] {3343} INFO -  at 60.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:50] {3166} INFO - iteration 502, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:50] {3343} INFO -  at 60.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:50] {3166} INFO - iteration 503, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:50] {3343} INFO -  at 60.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:50] {3166} INFO - iteration 504, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:50] {3343} INFO -  at 60.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:50] {3166} INFO - iteration 505, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:50] {3343} INFO -  at 60.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:50] {3166} INFO - iteration 506, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:50] {3343} INFO -  at 60.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:50] {3166} INFO - iteration 507, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:50] {3343} INFO -  at 60.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:50] {3166} INFO - iteration 508, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:50] {3343} INFO -  at 60.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:50] {3166} INFO - iteration 509, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:51] {3343} INFO -  at 61.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:51] {3166} INFO - iteration 510, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:51] {3343} INFO -  at 61.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:51] {3166} INFO - iteration 511, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:51] {3343} INFO -  at 61.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:51] {3166} INFO - iteration 512, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:51] {3343} INFO -  at 61.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:51] {3166} INFO - iteration 513, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:51] {3343} INFO -  at 61.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:51] {3166} INFO - iteration 514, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:51] {3343} INFO -  at 61.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:51] {3166} INFO - iteration 515, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:52] {3343} INFO -  at 61.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:52] {3166} INFO - iteration 516, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:52] {3343} INFO -  at 62.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:52] {3166} INFO - iteration 517, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:52] {3343} INFO -  at 62.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:52] {3166} INFO - iteration 518, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:52] {3343} INFO -  at 62.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:52] {3166} INFO - iteration 519, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:52] {3343} INFO -  at 62.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:52] {3166} INFO - iteration 520, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:52] {3343} INFO -  at 62.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:52] {3166} INFO - iteration 521, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:52] {3343} INFO -  at 62.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:52] {3166} INFO - iteration 522, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:52] {3343} INFO -  at 62.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:52] {3166} INFO - iteration 523, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:53] {3343} INFO -  at 63.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:53] {3166} INFO - iteration 524, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:53] {3343} INFO -  at 63.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:53] {3166} INFO - iteration 525, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:53] {3343} INFO -  at 63.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:53] {3166} INFO - iteration 526, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:53] {3343} INFO -  at 63.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:53] {3166} INFO - iteration 527, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:53] {3343} INFO -  at 63.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:53] {3166} INFO - iteration 528, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:53] {3343} INFO -  at 63.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:53] {3166} INFO - iteration 529, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:53] {3343} INFO -  at 63.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:53] {3166} INFO - iteration 530, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:53] {3343} INFO -  at 63.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:53] {3166} INFO - iteration 531, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:54] {3343} INFO -  at 64.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:54] {3166} INFO - iteration 532, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:54] {3343} INFO -  at 64.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:54] {3166} INFO - iteration 533, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:54] {3343} INFO -  at 64.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:54] {3166} INFO - iteration 534, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:54] {3343} INFO -  at 64.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:54] {3166} INFO - iteration 535, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:54] {3343} INFO -  at 64.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331

[flaml.automl: 04-23 11:20:54] {3166} INFO - iteration 536, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:54] {3343} INFO -  at 64.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:54] {3166} INFO - iteration 537, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:54] {3343} INFO -  at 64.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:54] {3166} INFO - iteration 538, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:55] {3343} INFO -  at 65.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:55] {3166} INFO - iteration 539, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:55] {3343} INFO -  at 65.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:55] {3166} INFO - iteration 540, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:55] {3343} INFO -  at 65.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:55] {3166} INFO - iteration 541, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:55] {3343} INFO -  at 65.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:55] {3166} INFO - iteration 542, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:55] {3343} INFO -  at 65.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:55] {3166} INFO - iteration 543, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:55] {3343} INFO -  at 65.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:55] {3166} INFO - iteration 544, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:55] {3343} INFO -  at 65.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:55] {3166} INFO - iteration 545, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:55] {3343} INFO -  at 65.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:55] {3166} INFO - iteration 546, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:55] {3343} INFO -  at 65.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:55] {3166} INFO - iteration 547, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:56] {3343} INFO -  at 66.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:56] {3166} INFO - iteration 548, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:56] {3343} INFO -  at 66.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:56] {3166} INFO - iteration 549, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:56] {3343} INFO -  at 66.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:56] {3166} INFO - iteration 550, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:56] {3343} INFO -  at 66.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:56] {3166} INFO - iteration 551, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:56] {3343} INFO -  at 66.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:56] {3166} INFO - iteration 552, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:56] {3343} INFO -  at 66.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:56] {3166} INFO - iteration 553, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:56] {3343} INFO -  at 66.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:56] {3166} INFO - iteration 554, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:57] {3343} INFO -  at 67.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:57] {3166} INFO - iteration 555, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:57] {3343} INFO -  at 67.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:57] {3166} INFO - iteration 556, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:57] {3343} INFO -  at 67.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:57] {3166} INFO - iteration 557, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:57] {3343} INFO -  at 67.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:57] {3166} INFO - iteration 558, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:57] {3343} INFO -  at 67.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:57] {3166} INFO - iteration 559, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:57] {3343} INFO -  at 67.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:57] {3166} INFO - iteration 560, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:57] {3343} INFO -  at 67.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:57] {3166} INFO - iteration 561, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:58] {3343} INFO -  at 68.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:58] {3166} INFO - iteration 562, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:58] {3343} INFO -  at 68.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:58] {3166} INFO - iteration 563, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:58] {3343} INFO -  at 68.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:58] {3166} INFO - iteration 564, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:58] {3343} INFO -  at 68.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:58] {3166} INFO - iteration 565, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:58] {3343} INFO -  at 68.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:58] {3166} INFO - iteration 566, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:58] {3343} INFO -  at 68.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:58] {3166} INFO - iteration 567, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:58] {3343} INFO -  at 68.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:58] {3166} INFO - iteration 568, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:59] {3343} INFO -  at 69.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:59] {3166} INFO - iteration 569, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:59] {3343} INFO -  at 69.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:59] {3166} INFO - iteration 570, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:59] {3343} INFO -  at 69.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:59] {3166} INFO - iteration 571, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:59] {3343} INFO -  at 69.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:59] {3166} INFO - iteration 572, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:59] {3343} INFO -  at 69.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:59] {3166} INFO - iteration 573, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:59] {3343} INFO -  at 69.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:59] {3166} INFO - iteration 574, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:20:59] {3343} INFO -  at 69.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:59] {3166} INFO - iteration 575, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:59] {3343} INFO -  at 69.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:59] {3166} INFO - iteration 576, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:59] {3343} INFO -  at 69.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:59] {3166} INFO - iteration 577, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:20:59] {3343} INFO -  at 69.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:20:59] {3166} INFO - iteration 578, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:00] {3343} INFO -  at 70.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:00] {3166} INFO - iteration 579, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:00] {3343} INFO -  at 70.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:00] {3166} INFO - iteration 580, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:00] {3343} INFO -  at 70.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:00] {3166} INFO - iteration 581, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:00] {3343} INFO -  at 70.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:00] {3166} INFO - iteration 582, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:00] {3343} INFO -  at 70.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:00] {3166} INFO - iteration 583, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:00] {3343} INFO -  at 70.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:00] {3166} INFO - iteration 584, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:00] {3343} INFO -  at 70.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:00] {3166} INFO - iteration 585, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:00] {3343} INFO -  at 70.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:00] {3166} INFO - iteration 586, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:00] {3343} INFO -  at 70.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:00] {3166} INFO - iteration 587, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:00] {3343} INFO -  at 70.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:00] {3166} INFO - iteration 588, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:01] {3343} INFO -  at 71.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:01] {3166} INFO - iteration 589, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:01] {3343} INFO -  at 71.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:01] {3166} INFO - iteration 590, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:01] {3343} INFO -  at 71.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:01] {3166} INFO - iteration 591, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:01] {3343} INFO -  at 71.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:01] {3166} INFO - iteration 592, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:01] {3343} INFO -  at 71.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:01] {3166} INFO - iteration 593, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:01] {3343} INFO -  at 71.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:01] {3166} INFO - iteration 594, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:01] {3343} INFO -  at 71.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:01] {3166} INFO - iteration 595, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:01] {3343} INFO -  at 71.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:01] {3166} INFO - iteration 596, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:02] {3343} INFO -  at 72.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:02] {3166} INFO - iteration 597, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:02] {3343} INFO -  at 72.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:02] {3166} INFO - iteration 598, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:02] {3343} INFO -  at 72.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:02] {3166} INFO - iteration 599, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:02] {3343} INFO -  at 72.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:02] {3166} INFO - iteration 600, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:02] {3343} INFO -  at 72.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:02] {3166} INFO - iteration 601, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:02] {3343} INFO -  at 72.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:02] {3166} INFO - iteration 602, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:02] {3343} INFO -  at 72.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:02] {3166} INFO - iteration 603, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:03] {3343} INFO -  at 73.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:03] {3166} INFO - iteration 604, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:03] {3343} INFO -  at 73.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:03] {3166} INFO - iteration 605, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:03] {3343} INFO -  at 73.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:03] {3166} INFO - iteration 606, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:03] {3343} INFO -  at 73.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:03] {3166} INFO - iteration 607, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:03] {3343} INFO -  at 73.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:03] {3166} INFO - iteration 608, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:03] {3343} INFO -  at 73.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:03] {3166} INFO - iteration 609, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:03] {3343} INFO -  at 73.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:03] {3166} INFO - iteration 610, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:04] {3343} INFO -  at 74.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:04] {3166} INFO - iteration 611, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:04] {3343} INFO -  at 74.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:04] {3166} INFO - iteration 612, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:04] {3343} INFO -  at 74.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:04] {3166} INFO - iteration 613, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:04] {3343} INFO -  at 74.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:04] {3166} INFO - iteration 614, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:04] {3343} INFO -  at 74.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:04] {3166} INFO - iteration 615, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:04] {3343} INFO -  at 74.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:04] {3166} INFO - iteration 616, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:04] {3343} INFO -  at 74.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:04] {3166} INFO - iteration 617, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:04] {3343} INFO -  at 74.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:04] {3166} INFO - iteration 618, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:05] {3343} INFO -  at 75.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:05] {3166} INFO - iteration 619, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:05] {3343} INFO -  at 75.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:05] {3166} INFO - iteration 620, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:05] {3343} INFO -  at 75.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:05] {3166} INFO - iteration 621, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:05] {3343} INFO -  at 75.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:05] {3166} INFO - iteration 622, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:05] {3343} INFO -  at 75.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:05] {3166} INFO - iteration 623, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:05] {3343} INFO -  at 75.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:05] {3166} INFO - iteration 624, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:05] {3343} INFO -  at 75.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:05] {3166} INFO - iteration 625, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:06] {3343} INFO -  at 75.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:06] {3166} INFO - iteration 626, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:06] {3343} INFO -  at 76.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:06] {3166} INFO - iteration 627, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:06] {3343} INFO -  at 76.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:06] {3166} INFO - iteration 628, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:06] {3343} INFO -  at 76.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:06] {3166} INFO - iteration 629, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:06] {3343} INFO -  at 76.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:06] {3166} INFO - iteration 630, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:06] {3343} INFO -  at 76.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:06] {3166} INFO - iteration 631, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:06] {3343} INFO -  at 76.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:06] {3166} INFO - iteration 632, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:06] {3343} INFO -  at 76.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:06] {3166} INFO - iteration 633, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:07] {3343} INFO -  at 77.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:07] {3166} INFO - iteration 634, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:07] {3343} INFO -  at 77.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:07] {3166} INFO - iteration 635, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:07] {3343} INFO -  at 77.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:07] {3166} INFO - iteration 636, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:07] {3343} INFO -  at 77.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:07] {3166} INFO - iteration 637, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:07] {3343} INFO -  at 77.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:07] {3166} INFO - iteration 638, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:07] {3343} INFO -  at 77.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:07] {3166} INFO - iteration 639, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:07] {3343} INFO -  at 77.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:07] {3166} INFO - iteration 640, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:07] {3343} INFO -  at 77.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:07] {3166} INFO - iteration 641, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:08] {3343} INFO -  at 78.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:08] {3166} INFO - iteration 642, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:08] {3343} INFO -  at 78.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:08] {3166} INFO - iteration 643, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:08] {3343} INFO -  at 78.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:08] {3166} INFO - iteration 644, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:08] {3343} INFO -  at 78.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:08] {3166} INFO - iteration 645, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:08] {3343} INFO -  at 78.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:08] {3166} INFO - iteration 646, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:08] {3343} INFO -  at 78.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:08] {3166} INFO - iteration 647, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:08] {3343} INFO -  at 78.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:08] {3166} INFO - iteration 648, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:08] {3343} INFO -  at 78.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:08] {3166} INFO - iteration 649, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:09] {3343} INFO -  at 79.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:09] {3166} INFO - iteration 650, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:09] {3343} INFO -  at 79.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:09] {3166} INFO - iteration 651, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:09] {3343} INFO -  at 79.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:09] {3166} INFO - iteration 652, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:09] {3343} INFO -  at 79.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:09] {3166} INFO - iteration 653, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:09] {3343} INFO -  at 79.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:09] {3166} INFO - iteration 654, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:09] {3343} INFO -  at 79.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:09] {3166} INFO - iteration 655, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:09] {3343} INFO -  at 79.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:09] {3166} INFO - iteration 656, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:09] {3343} INFO -  at 79.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:09] {3166} INFO - iteration 657, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:10] {3343} INFO -  at 80.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:10] {3166} INFO - iteration 658, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:10] {3343} INFO -  at 80.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:10] {3166} INFO - iteration 659, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:10] {3343} INFO -  at 80.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:10] {3166} INFO - iteration 660, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:10] {3343} INFO -  at 80.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:10] {3166} INFO - iteration 661, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:10] {3343} INFO -  at 80.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:10] {3166} INFO - iteration 662, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:10] {3343} INFO -  at 80.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:10] {3166} INFO - iteration 663, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:10] {3343} INFO -  at 80.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:10] {3166} INFO - iteration 664, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:10] {3343} INFO -  at 80.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:10] {3166} INFO - iteration 665, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:11] {3343} INFO -  at 81.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:11] {3166} INFO - iteration 666, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:11] {3343} INFO -  at 81.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:11] {3166} INFO - iteration 667, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:11] {3343} INFO -  at 81.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:11] {3166} INFO - iteration 668, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:11] {3343} INFO -  at 81.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:11] {3166} INFO - iteration 669, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:11] {3343} INFO -  at 81.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:11] {3166} INFO - iteration 670, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:11] {3343} INFO -  at 81.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:11] {3166} INFO - iteration 671, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:11] {3343} INFO -  at 81.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:11] {3166} INFO - iteration 672, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:12] {3343} INFO -  at 82.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:12] {3166} INFO - iteration 673, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:12] {3343} INFO -  at 82.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:12] {3166} INFO - iteration 674, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:12] {3343} INFO -  at 82.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:12] {3166} INFO - iteration 675, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:12] {3343} INFO -  at 82.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:12] {3166} INFO - iteration 676, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:12] {3343} INFO -  at 82.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:12] {3166} INFO - iteration 677, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:12] {3343} INFO -  at 82.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:12] {3166} INFO - iteration 678, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:12] {3343} INFO -  at 82.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:12] {3166} INFO - iteration 679, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:12] {3343} INFO -  at 82.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:12] {3166} INFO - iteration 680, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:13] {3343} INFO -  at 83.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:13] {3166} INFO - iteration 681, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:13] {3343} INFO -  at 83.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:13] {3166} INFO - iteration 682, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:13] {3343} INFO -  at 83.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:13] {3166} INFO - iteration 683, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:13] {3343} INFO -  at 83.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:13] {3166} INFO - iteration 684, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:13] {3343} INFO -  at 83.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:13] {3166} INFO - iteration 685, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:13] {3343} INFO -  at 83.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:13] {3166} INFO - iteration 686, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:13] {3343} INFO -  at 83.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:13] {3166} INFO - iteration 687, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:13] {3343} INFO -  at 83.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:13] {3166} INFO - iteration 688, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:14] {3343} INFO -  at 84.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:14] {3166} INFO - iteration 689, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:14] {3343} INFO -  at 84.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:14] {3166} INFO - iteration 690, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:14] {3343} INFO -  at 84.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:14] {3166} INFO - iteration 691, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:14] {3343} INFO -  at 84.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:14] {3166} INFO - iteration 692, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:14] {3343} INFO -  at 84.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:14] {3166} INFO - iteration 693, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:14] {3343} INFO -  at 84.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:14] {3166} INFO - iteration 694, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:15] {3343} INFO -  at 85.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:15] {3166} INFO - iteration 695, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:15] {3343} INFO -  at 85.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:15] {3166} INFO - iteration 696, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:15] {3343} INFO -  at 85.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:15] {3166} INFO - iteration 697, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:15] {3343} INFO -  at 85.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:15] {3166} INFO - iteration 698, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:15] {3343} INFO -  at 85.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:15] {3166} INFO - iteration 699, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:15] {3343} INFO -  at 85.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:15] {3166} INFO - iteration 700, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:15] {3343} INFO -  at 85.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:15] {3166} INFO - iteration 701, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:15] {3343} INFO -  at 85.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:15] {3166} INFO - iteration 702, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:16] {3343} INFO -  at 86.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:16] {3166} INFO - iteration 703, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:16] {3343} INFO -  at 86.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:16] {3166} INFO - iteration 704, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:16] {3343} INFO -  at 86.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:16] {3166} INFO - iteration 705, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:16] {3343} INFO -  at 86.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:16] {3166} INFO - iteration 706, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:16] {3343} INFO -  at 86.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:16] {3166} INFO - iteration 707, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:16] {3343} INFO -  at 86.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:16] {3166} INFO - iteration 708, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:16] {3343} INFO -  at 86.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:16] {3166} INFO - iteration 709, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:16] {3343} INFO -  at 86.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:16] {3166} INFO - iteration 710, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:17] {3343} INFO -  at 87.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:17] {3166} INFO - iteration 711, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:17] {3343} INFO -  at 87.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:17] {3166} INFO - iteration 712, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:17] {3343} INFO -  at 87.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:17] {3166} INFO - iteration 713, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:17] {3343} INFO -  at 87.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:17] {3166} INFO - iteration 714, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:17] {3343} INFO -  at 87.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:17] {3166} INFO - iteration 715, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:17] {3343} INFO -  at 87.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:17] {3166} INFO - iteration 716, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:17] {3343} INFO -  at 87.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:17] {3166} INFO - iteration 717, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:17] {3343} INFO -  at 87.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:17] {3166} INFO - iteration 718, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:18] {3343} INFO -  at 88.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:18] {3166} INFO - iteration 719, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:18] {3343} INFO -  at 88.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:18] {3166} INFO - iteration 720, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:18] {3343} INFO -  at 88.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:18] {3166} INFO - iteration 721, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:18] {3343} INFO -  at 88.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:18] {3166} INFO - iteration 722, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:18] {3343} INFO -  at 88.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:18] {3166} INFO - iteration 723, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:18] {3343} INFO -  at 88.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:18] {3166} INFO - iteration 724, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:18] {3343} INFO -  at 88.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:18] {3166} INFO - iteration 725, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:19] {3343} INFO -  at 89.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:19] {3166} INFO - iteration 726, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:19] {3343} INFO -  at 89.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:19] {3166} INFO - iteration 727, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:19] {3343} INFO -  at 89.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:19] {3166} INFO - iteration 728, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:19] {3343} INFO -  at 89.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:19] {3166} INFO - iteration 729, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:19] {3343} INFO -  at 89.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:19] {3166} INFO - iteration 730, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:19] {3343} INFO -  at 89.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:19] {3166} INFO - iteration 731, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:19] {3343} INFO -  at 89.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:19] {3166} INFO - iteration 732, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:19] {3343} INFO -  at 89.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:19] {3166} INFO - iteration 733, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:20] {3343} INFO -  at 90.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:20] {3166} INFO - iteration 734, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:20] {3343} INFO -  at 90.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:20] {3166} INFO - iteration 735, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:20] {3343} INFO -  at 90.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:20] {3166} INFO - iteration 736, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:20] {3343} INFO -  at 90.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:20] {3166} INFO - iteration 737, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:20] {3343} INFO -  at 90.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:20] {3166} INFO - iteration 738, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:20] {3343} INFO -  at 90.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:20] {3166} INFO - iteration 739, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:20] {3343} INFO -  at 90.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:20] {3166} INFO - iteration 740, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:20] {3343} INFO -  at 90.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:20] {3166} INFO - iteration 741, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:21] {3343} INFO -  at 91.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:21] {3166} INFO - iteration 742, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:21] {3343} INFO -  at 91.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:21] {3166} INFO - iteration 743, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:21] {3343} INFO -  at 91.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:21] {3166} INFO - iteration 744, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:21] {3343} INFO -  at 91.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:21] {3166} INFO - iteration 745, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:21] {3343} INFO -  at 91.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:21] {3166} INFO - iteration 746, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:21] {3343} INFO -  at 91.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:21] {3166} INFO - iteration 747, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:21] {3343} INFO -  at 91.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:21] {3166} INFO - iteration 748, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:22] {3343} INFO -  at 92.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:22] {3166} INFO - iteration 749, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:22] {3343} INFO -  at 92.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:22] {3166} INFO - iteration 750, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:22] {3343} INFO -  at 92.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:22] {3166} INFO - iteration 751, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:22] {3343} INFO -  at 92.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:22] {3166} INFO - iteration 752, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:22] {3343} INFO -  at 92.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:22] {3166} INFO - iteration 753, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:22] {3343} INFO -  at 92.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:22] {3166} INFO - iteration 754, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:22] {3343} INFO -  at 92.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:22] {3166} INFO - iteration 755, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:22] {3343} INFO -  at 92.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:22] {3166} INFO - iteration 756, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:23] {3343} INFO -  at 93.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:23] {3166} INFO - iteration 757, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:23] {3343} INFO -  at 93.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:23] {3166} INFO - iteration 758, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:23] {3343} INFO -  at 93.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:23] {3166} INFO - iteration 759, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:23] {3343} INFO -  at 93.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:23] {3166} INFO - iteration 760, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:23] {3343} INFO -  at 93.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:23] {3166} INFO - iteration 761, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:23] {3343} INFO -  at 93.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:23] {3166} INFO - iteration 762, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:23] {3343} INFO -  at 93.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:23] {3166} INFO - iteration 763, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:23] {3343} INFO -  at 93.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:23] {3166} INFO - iteration 764, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:24] {3343} INFO -  at 94.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:24] {3166} INFO - iteration 765, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:24] {3343} INFO -  at 94.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:24] {3166} INFO - iteration 766, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:24] {3343} INFO -  at 94.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:24] {3166} INFO - iteration 767, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:24] {3343} INFO -  at 94.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:24] {3166} INFO - iteration 768, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:24] {3343} INFO -  at 94.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:24] {3166} INFO - iteration 769, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:24] {3343} INFO -  at 94.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:24] {3166} INFO - iteration 770, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:24] {3343} INFO -  at 94.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:24] {3166} INFO - iteration 771, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:25] {3343} INFO -  at 94.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:25] {3166} INFO - iteration 772, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:25] {3343} INFO -  at 95.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:25] {3166} INFO - iteration 773, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:25] {3343} INFO -  at 95.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:25] {3166} INFO - iteration 774, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:25] {3343} INFO -  at 95.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:25] {3166} INFO - iteration 775, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:25] {3343} INFO -  at 95.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:25] {3166} INFO - iteration 776, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:25] {3343} INFO -  at 95.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:25] {3166} INFO - iteration 777, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:25] {3343} INFO -  at 95.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:25] {3166} INFO - iteration 778, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:25] {3343} INFO -  at 95.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:25] {3166} INFO - iteration 779, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:26] {3343} INFO -  at 96.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:26] {3166} INFO - iteration 780, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:26] {3343} INFO -  at 96.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:26] {3166} INFO - iteration 781, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:26] {3343} INFO -  at 96.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:26] {3166} INFO - iteration 782, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:26] {3343} INFO -  at 96.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:26] {3166} INFO - iteration 783, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:26] {3343} INFO -  at 96.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:26] {3166} INFO - iteration 784, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:26] {3343} INFO -  at 96.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:26] {3166} INFO - iteration 785, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:26] {3343} INFO -  at 96.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:26] {3166} INFO - iteration 786, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:26] {3343} INFO -  at 96.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:26] {3166} INFO - iteration 787, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:27] {3343} INFO -  at 97.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:27] {3166} INFO - iteration 788, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:27] {3343} INFO -  at 97.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:27] {3166} INFO - iteration 789, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:27] {3343} INFO -  at 97.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:27] {3166} INFO - iteration 790, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:27] {3343} INFO -  at 97.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:27] {3166} INFO - iteration 791, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:27] {3343} INFO -  at 97.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:27] {3166} INFO - iteration 792, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:27] {3343} INFO -  at 97.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:27] {3166} INFO - iteration 793, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:27] {3343} INFO -  at 97.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:27] {3166} INFO - iteration 794, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:27] {3343} INFO -  at 97.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:27] {3166} INFO - iteration 795, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:28] {3343} INFO -  at 98.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:28] {3166} INFO - iteration 796, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:28] {3343} INFO -  at 98.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:28] {3166} INFO - iteration 797, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:28] {3343} INFO -  at 98.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:28] {3166} INFO - iteration 798, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:28] {3343} INFO -  at 98.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:28] {3166} INFO - iteration 799, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:28] {3343} INFO -  at 98.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:28] {3166} INFO - iteration 800, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:28] {3343} INFO -  at 98.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:28] {3166} INFO - iteration 801, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:28] {3343} INFO -  at 98.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:28] {3166} INFO - iteration 802, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:28] {3343} INFO -  at 98.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:28] {3166} INFO - iteration 803, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:29] {3343} INFO -  at 99.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:29] {3166} INFO - iteration 804, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:29] {3343} INFO -  at 99.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:29] {3166} INFO - iteration 805, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:29] {3343} INFO -  at 99.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:29] {3166} INFO - iteration 806, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:29] {3343} INFO -  at 99.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:29] {3166} INFO - iteration 807, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:29] {3343} INFO -  at 99.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:29] {3166} INFO - iteration 808, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:29] {3343} INFO -  at 99.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:29] {3166} INFO - iteration 809, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:29] {3343} INFO -  at 99.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:29] {3166} INFO - iteration 810, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:29] {3343} INFO -  at 99.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:29] {3166} INFO - iteration 811, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:30] {3343} INFO -  at 100.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:30] {3166} INFO - iteration 812, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:30] {3343} INFO -  at 100.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:30] {3166} INFO - iteration 813, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:30] {3343} INFO -  at 100.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:30] {3166} INFO - iteration 814, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:30] {3343} INFO -  at 100.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:30] {3166} INFO - iteration 815, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:30] {3343} INFO -  at 100.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:30] {3166} INFO - iteration 816, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:30] {3343} INFO -  at 100.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:30] {3166} INFO - iteration 817, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:30] {3343} INFO -  at 100.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:30] {3166} INFO - iteration 818, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:30] {3343} INFO -  at 100.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:30] {3166} INFO - iteration 819, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:31] {3343} INFO -  at 101.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:31] {3166} INFO - iteration 820, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:31] {3343} INFO -  at 101.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:31] {3166} INFO - iteration 821, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:31] {3343} INFO -  at 101.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:31] {3166} INFO - iteration 822, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:31] {3343} INFO -  at 101.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:31] {3166} INFO - iteration 823, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:31] {3343} INFO -  at 101.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:31] {3166} INFO - iteration 824, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:31] {3343} INFO -  at 101.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:31] {3166} INFO - iteration 825, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:32] {3343} INFO -  at 101.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:32] {3166} INFO - iteration 826, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:32] {3343} INFO -  at 102.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:32] {3166} INFO - iteration 827, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:32] {3343} INFO -  at 102.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:32] {3166} INFO - iteration 828, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:32] {3343} INFO -  at 102.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:32] {3166} INFO - iteration 829, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:32] {3343} INFO -  at 102.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:32] {3166} INFO - iteration 830, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:32] {3343} INFO -  at 102.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:32] {3166} INFO - iteration 831, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:32] {3343} INFO -  at 102.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:32] {3166} INFO - iteration 832, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:32] {3343} INFO -  at 102.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:32] {3166} INFO - iteration 833, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:33] {3343} INFO -  at 103.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:33] {3166} INFO - iteration 834, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:33] {3343} INFO -  at 103.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:33] {3166} INFO - iteration 835, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:33] {3343} INFO -  at 103.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:33] {3166} INFO - iteration 836, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:33] {3343} INFO -  at 103.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:33] {3166} INFO - iteration 837, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:33] {3343} INFO -  at 103.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:33] {3166} INFO - iteration 838, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:33] {3343} INFO -  at 103.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:33] {3166} INFO - iteration 839, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:33] {3343} INFO -  at 103.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:33] {3166} INFO - iteration 840, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:33] {3343} INFO -  at 103.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:33] {3166} INFO - iteration 841, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:34] {3343} INFO -  at 104.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:34] {3166} INFO - iteration 842, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:34] {3343} INFO -  at 104.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:34] {3166} INFO - iteration 843, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:34] {3343} INFO -  at 104.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:34] {3166} INFO - iteration 844, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:34] {3343} INFO -  at 104.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:34] {3166} INFO - iteration 845, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:34] {3343} INFO -  at 104.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:34] {3166} INFO - iteration 846, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:34] {3343} INFO -  at 104.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:34] {3166} INFO - iteration 847, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:34] {3343} INFO -  at 104.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:34] {3166} INFO - iteration 848, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:35] {3343} INFO -  at 105.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:35] {3166} INFO - iteration 849, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:35] {3343} INFO -  at 105.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:35] {3166} INFO - iteration 850, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:35] {3343} INFO -  at 105.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:35] {3166} INFO - iteration 851, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:35] {3343} INFO -  at 105.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:35] {3166} INFO - iteration 852, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:35] {3343} INFO -  at 105.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:35] {3166} INFO - iteration 853, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:35] {3343} INFO -  at 105.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:35] {3166} INFO - iteration 854, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:35] {3343} INFO -  at 105.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:35] {3166} INFO - iteration 855, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:35] {3343} INFO -  at 105.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:35] {3166} INFO - iteration 856, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:36] {3343} INFO -  at 106.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:36] {3166} INFO - iteration 857, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:36] {3343} INFO -  at 106.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:36] {3166} INFO - iteration 858, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:36] {3343} INFO -  at 106.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:36] {3166} INFO - iteration 859, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:36] {3343} INFO -  at 106.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:36] {3166} INFO - iteration 860, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:36] {3343} INFO -  at 106.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:36] {3166} INFO - iteration 861, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:36] {3343} INFO -  at 106.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:36] {3166} INFO - iteration 862, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:36] {3343} INFO -  at 106.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:36] {3166} INFO - iteration 863, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:36] {3343} INFO -  at 106.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:36] {3166} INFO - iteration 864, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:37] {3343} INFO -  at 107.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:37] {3166} INFO - iteration 865, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:37] {3343} INFO -  at 107.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:37] {3166} INFO - iteration 866, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:37] {3343} INFO -  at 107.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:37] {3166} INFO - iteration 867, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:37] {3343} INFO -  at 107.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:37] {3166} INFO - iteration 868, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:37] {3343} INFO -  at 107.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:37] {3166} INFO - iteration 869, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:37] {3343} INFO -  at 107.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:37] {3166} INFO - iteration 870, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:37] {3343} INFO -  at 107.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:37] {3166} INFO - iteration 871, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:37] {3343} INFO -  at 107.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:37] {3166} INFO - iteration 872, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:38] {3343} INFO -  at 108.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:38] {3166} INFO - iteration 873, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:38] {3343} INFO -  at 108.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:38] {3166} INFO - iteration 874, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:38] {3343} INFO -  at 108.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:38] {3166} INFO - iteration 875, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:38] {3343} INFO -  at 108.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:38] {3166} INFO - iteration 876, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:38] {3343} INFO -  at 108.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:38] {3166} INFO - iteration 877, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:38] {3343} INFO -  at 108.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:38] {3166} INFO - iteration 878, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:38] {3343} INFO -  at 108.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:38] {3166} INFO - iteration 879, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:38] {3343} INFO -  at 108.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:38] {3166} INFO - iteration 880, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:38] {3343} INFO -  at 108.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:38] {3166} INFO - iteration 881, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:39] {3343} INFO -  at 109.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:39] {3166} INFO - iteration 882, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:39] {3343} INFO -  at 109.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:39] {3166} INFO - iteration 883, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:39] {3343} INFO -  at 109.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:39] {3166} INFO - iteration 884, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:39] {3343} INFO -  at 109.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:39] {3166} INFO - iteration 885, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:39] {3343} INFO -  at 109.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:39] {3166} INFO - iteration 886, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:39] {3343} INFO -  at 109.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:39] {3166} INFO - iteration 887, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:39] {3343} INFO -  at 109.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:39] {3166} INFO - iteration 888, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:40] {3343} INFO -  at 110.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:40] {3166} INFO - iteration 889, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:40] {3343} INFO -  at 110.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:40] {3166} INFO - iteration 890, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:40] {3343} INFO -  at 110.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:40] {3166} INFO - iteration 891, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:40] {3343} INFO -  at 110.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:40] {3166} INFO - iteration 892, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:40] {3343} INFO -  at 110.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:40] {3166} INFO - iteration 893, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:40] {3343} INFO -  at 110.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:40] {3166} INFO - iteration 894, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:40] {3343} INFO -  at 110.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:40] {3166} INFO - iteration 895, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:40] {3343} INFO -  at 110.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:40] {3166} INFO - iteration 896, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:40] {3343} INFO -  at 110.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:40] {3166} INFO - iteration 897, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:41] {3343} INFO -  at 111.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:41] {3166} INFO - iteration 898, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:41] {3343} INFO -  at 111.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:41] {3166} INFO - iteration 899, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:41] {3343} INFO -  at 111.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:41] {3166} INFO - iteration 900, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:41] {3343} INFO -  at 111.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:41] {3166} INFO - iteration 901, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:41] {3343} INFO -  at 111.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:41] {3166} INFO - iteration 902, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:41] {3343} INFO -  at 111.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:41] {3166} INFO - iteration 903, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:41] {3343} INFO -  at 111.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:41] {3166} INFO - iteration 904, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:41] {3343} INFO -  at 111.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:41] {3166} INFO - iteration 905, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:42] {3343} INFO -  at 112.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:42] {3166} INFO - iteration 906, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:42] {3343} INFO -  at 112.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:42] {3166} INFO - iteration 907, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:42] {3343} INFO -  at 112.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:42] {3166} INFO - iteration 908, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:42] {3343} INFO -  at 112.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:42] {3166} INFO - iteration 909, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:42] {3343} INFO -  at 112.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:42] {3166} INFO - iteration 910, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:42] {3343} INFO -  at 112.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:42] {3166} INFO - iteration 911, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:42] {3343} INFO -  at 112.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:42] {3166} INFO - iteration 912, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:42] {3343} INFO -  at 112.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:42] {3166} INFO - iteration 913, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:43] {3343} INFO -  at 113.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:43] {3166} INFO - iteration 914, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:43] {3343} INFO -  at 113.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:43] {3166} INFO - iteration 915, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:43] {3343} INFO -  at 113.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:43] {3166} INFO - iteration 916, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:43] {3343} INFO -  at 113.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:43] {3166} INFO - iteration 917, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:43] {3343} INFO -  at 113.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:43] {3166} INFO - iteration 918, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:43] {3343} INFO -  at 113.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:43] {3166} INFO - iteration 919, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:43] {3343} INFO -  at 113.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:43] {3166} INFO - iteration 920, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:43] {3343} INFO -  at 113.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:43] {3166} INFO - iteration 921, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:44] {3343} INFO -  at 114.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:44] {3166} INFO - iteration 922, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:44] {3343} INFO -  at 114.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:44] {3166} INFO - iteration 923, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:44] {3343} INFO -  at 114.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:44] {3166} INFO - iteration 924, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:44] {3343} INFO -  at 114.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:44] {3166} INFO - iteration 925, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:44] {3343} INFO -  at 114.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:44] {3166} INFO - iteration 926, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:44] {3343} INFO -  at 114.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:44] {3166} INFO - iteration 927, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:44] {3343} INFO -  at 114.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:44] {3166} INFO - iteration 928, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:44] {3343} INFO -  at 114.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:44] {3166} INFO - iteration 929, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:45] {3343} INFO -  at 115.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:45] {3166} INFO - iteration 930, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:45] {3343} INFO -  at 115.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:45] {3166} INFO - iteration 931, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:45] {3343} INFO -  at 115.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:45] {3166} INFO - iteration 932, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:45] {3343} INFO -  at 115.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:45] {3166} INFO - iteration 933, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:45] {3343} INFO -  at 115.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:45] {3166} INFO - iteration 934, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:45] {3343} INFO -  at 115.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:45] {3166} INFO - iteration 935, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:45] {3343} INFO -  at 115.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:45] {3166} INFO - iteration 936, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:46] {3343} INFO -  at 116.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:46] {3166} INFO - iteration 937, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:46] {3343} INFO -  at 116.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:46] {3166} INFO - iteration 938, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:46] {3343} INFO -  at 116.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:46] {3166} INFO - iteration 939, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:46] {3343} INFO -  at 116.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:46] {3166} INFO - iteration 940, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:46] {3343} INFO -  at 116.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:46] {3166} INFO - iteration 941, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:46] {3343} INFO -  at 116.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:46] {3166} INFO - iteration 942, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:46] {3343} INFO -  at 116.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:46] {3166} INFO - iteration 943, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:47] {3343} INFO -  at 117.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:47] {3166} INFO - iteration 944, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:47] {3343} INFO -  at 117.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:47] {3166} INFO - iteration 945, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:47] {3343} INFO -  at 117.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:47] {3166} INFO - iteration 946, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:47] {3343} INFO -  at 117.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:47] {3166} INFO - iteration 947, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:47] {3343} INFO -  at 117.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:47] {3166} INFO - iteration 948, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:47] {3343} INFO -  at 117.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:47] {3166} INFO - iteration 949, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:47] {3343} INFO -  at 117.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:47] {3166} INFO - iteration 950, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:47] {3343} INFO -  at 117.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:47] {3166} INFO - iteration 951, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:47] {3343} INFO -  at 117.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:47] {3166} INFO - iteration 952, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:48] {3343} INFO -  at 118.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:48] {3166} INFO - iteration 953, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:48] {3343} INFO -  at 118.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:48] {3166} INFO - iteration 954, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:48] {3343} INFO -  at 118.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:48] {3166} INFO - iteration 955, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:48] {3343} INFO -  at 118.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:48] {3166} INFO - iteration 956, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:48] {3343} INFO -  at 118.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:48] {3166} INFO - iteration 957, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:48] {3343} INFO -  at 118.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:48] {3166} INFO - iteration 958, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:48] {3343} INFO -  at 118.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:48] {3166} INFO - iteration 959, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:48] {3343} INFO -  at 118.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:48] {3166} INFO - iteration 960, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:49] {3343} INFO -  at 119.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:49] {3166} INFO - iteration 961, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:49] {3343} INFO -  at 119.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:49] {3166} INFO - iteration 962, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:49] {3343} INFO -  at 119.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:49] {3166} INFO - iteration 963, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:49] {3343} INFO -  at 119.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:49] {3166} INFO - iteration 964, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:49] {3343} INFO -  at 119.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:49] {3166} INFO - iteration 965, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:49] {3343} INFO -  at 119.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:49] {3166} INFO - iteration 966, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:49] {3343} INFO -  at 119.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:49] {3166} INFO - iteration 967, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:49] {3343} INFO -  at 119.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:49] {3166} INFO - iteration 968, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:50] {3343} INFO -  at 120.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:50] {3166} INFO - iteration 969, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:50] {3343} INFO -  at 120.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:50] {3166} INFO - iteration 970, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:50] {3343} INFO -  at 120.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:50] {3166} INFO - iteration 971, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:50] {3343} INFO -  at 120.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:50] {3166} INFO - iteration 972, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:50] {3343} INFO -  at 120.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:50] {3166} INFO - iteration 973, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:50] {3343} INFO -  at 120.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:50] {3166} INFO - iteration 974, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:50] {3343} INFO -  at 120.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:50] {3166} INFO - iteration 975, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:51] {3343} INFO -  at 120.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:51] {3166} INFO - iteration 976, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:51] {3343} INFO -  at 121.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:51] {3166} INFO - iteration 977, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:51] {3343} INFO -  at 121.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:51] {3166} INFO - iteration 978, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:51] {3343} INFO -  at 121.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:51] {3166} INFO - iteration 979, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:51] {3343} INFO -  at 121.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:51] {3166} INFO - iteration 980, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:51] {3343} INFO -  at 121.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:51] {3166} INFO - iteration 981, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:51] {3343} INFO -  at 121.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:51] {3166} INFO - iteration 982, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:51] {3343} INFO -  at 121.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:51] {3166} INFO - iteration 983, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:52] {3343} INFO -  at 122.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:52] {3166} INFO - iteration 984, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:52] {3343} INFO -  at 122.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:52] {3166} INFO - iteration 985, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:52] {3343} INFO -  at 122.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:52] {3166} INFO - iteration 986, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:52] {3343} INFO -  at 122.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:52] {3166} INFO - iteration 987, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:52] {3343} INFO -  at 122.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:52] {3166} INFO - iteration 988, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:52] {3343} INFO -  at 122.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:52] {3166} INFO - iteration 989, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:52] {3343} INFO -  at 122.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:52] {3166} INFO - iteration 990, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:52] {3343} INFO -  at 122.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:52] {3166} INFO - iteration 991, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:52] {3343} INFO -  at 122.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:52] {3166} INFO - iteration 992, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:53] {3343} INFO -  at 123.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:53] {3166} INFO - iteration 993, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:53] {3343} INFO -  at 123.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:53] {3166} INFO - iteration 994, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:53] {3343} INFO -  at 123.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:53] {3166} INFO - iteration 995, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:53] {3343} INFO -  at 123.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:53] {3166} INFO - iteration 996, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:53] {3343} INFO -  at 123.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:53] {3166} INFO - iteration 997, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:53] {3343} INFO -  at 123.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:53] {3166} INFO - iteration 998, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:53] {3343} INFO -  at 123.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:53] {3166} INFO - iteration 999, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:53] {3343} INFO -  at 123.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:53] {3166} INFO - iteration 1000, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:53] {3343} INFO -  at 123.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:53] {3166} INFO - iteration 1001, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:54] {3343} INFO -  at 124.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:54] {3166} INFO - iteration 1002, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:54] {3343} INFO -  at 124.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:54] {3166} INFO - iteration 1003, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:54] {3343} INFO -  at 124.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:54] {3166} INFO - iteration 1004, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:54] {3343} INFO -  at 124.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:54] {3166} INFO - iteration 1005, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:54] {3343} INFO -  at 124.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:54] {3166} INFO - iteration 1006, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:54] {3343} INFO -  at 124.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:54] {3166} INFO - iteration 1007, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:54] {3343} INFO -  at 124.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:54] {3166} INFO - iteration 1008, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:54] {3343} INFO -  at 124.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:54] {3166} INFO - iteration 1009, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:54] {3343} INFO -  at 124.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:54] {3166} INFO - iteration 1010, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:54] {3343} INFO -  at 124.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:54] {3166} INFO - iteration 1011, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:55] {3343} INFO -  at 125.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:55] {3166} INFO - iteration 1012, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:55] {3343} INFO -  at 125.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:55] {3166} INFO - iteration 1013, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:55] {3343} INFO -  at 125.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:55] {3166} INFO - iteration 1014, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:55] {3343} INFO -  at 125.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:55] {3166} INFO - iteration 1015, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:55] {3343} INFO -  at 125.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:55] {3166} INFO - iteration 1016, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:55] {3343} INFO -  at 125.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:55] {3166} INFO - iteration 1017, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:55] {3343} INFO -  at 125.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:55] {3166} INFO - iteration 1018, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:55] {3343} INFO -  at 125.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:55] {3166} INFO - iteration 1019, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:55] {3343} INFO -  at 125.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:55] {3166} INFO - iteration 1020, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:55] {3343} INFO -  at 125.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:55] {3166} INFO - iteration 1021, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:56] {3343} INFO -  at 126.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:56] {3166} INFO - iteration 1022, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:56] {3343} INFO -  at 126.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:56] {3166} INFO - iteration 1023, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:56] {3343} INFO -  at 126.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:56] {3166} INFO - iteration 1024, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:56] {3343} INFO -  at 126.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:56] {3166} INFO - iteration 1025, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:56] {3343} INFO -  at 126.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:56] {3166} INFO - iteration 1026, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:56] {3343} INFO -  at 126.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:56] {3166} INFO - iteration 1027, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:56] {3343} INFO -  at 126.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:56] {3166} INFO - iteration 1028, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:56] {3343} INFO -  at 126.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:56] {3166} INFO - iteration 1029, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:57] {3343} INFO -  at 127.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331

[flaml.automl: 04-23 11:21:57] {3166} INFO - iteration 1030, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:57] {3343} INFO -  at 127.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:57] {3166} INFO - iteration 1031, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:57] {3343} INFO -  at 127.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:57] {3166} INFO - iteration 1032, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:57] {3343} INFO -  at 127.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:57] {3166} INFO - iteration 1033, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:57] {3343} INFO -  at 127.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:57] {3166} INFO - iteration 1034, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:57] {3343} INFO -  at 127.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:57] {3166} INFO - iteration 1035, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:57] {3343} INFO -  at 127.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:57] {3166} INFO - iteration 1036, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:57] {3343} INFO -  at 127.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:57] {3166} INFO - iteration 1037, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:57] {3343} INFO -  at 127.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:57] {3166} INFO - iteration 1038, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:57] {3343} INFO -  at 127.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:57] {3166} INFO - iteration 1039, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:58] {3343} INFO -  at 128.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:58] {3166} INFO - iteration 1040, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:58] {3343} INFO -  at 128.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:58] {3166} INFO - iteration 1041, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:58] {3343} INFO -  at 128.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:58] {3166} INFO - iteration 1042, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:58] {3343} INFO -  at 128.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331

[flaml.automl: 04-23 11:21:58] {3166} INFO - iteration 1043, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:58] {3343} INFO -  at 128.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:58] {3166} INFO - iteration 1044, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:58] {3343} INFO -  at 128.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:58] {3166} INFO - iteration 1045, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:58] {3343} INFO -  at 128.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:58] {3166} INFO - iteration 1046, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:58] {3343} INFO -  at 128.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:58] {3166} INFO - iteration 1047, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:58] {3343} INFO -  at 128.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:58] {3166} INFO - iteration 1048, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:58] {3343} INFO -  at 128.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:58] {3166} INFO - iteration 1049, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:59] {3343} INFO -  at 129.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:59] {3166} INFO - iteration 1050, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:59] {3343} INFO -  at 129.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:59] {3166} INFO - iteration 1051, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:59] {3343} INFO -  at 129.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:59] {3166} INFO - iteration 1052, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:59] {3343} INFO -  at 129.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:59] {3166} INFO - iteration 1053, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:59] {3343} INFO -  at 129.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:59] {3166} INFO - iteration 1054, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:59] {3343} INFO -  at 129.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:59] {3166} INFO - iteration 1055, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:21:59] {3343} INFO -  at 129.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:59] {3166} INFO - iteration 1056, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:59] {3343} INFO -  at 129.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:59] {3166} INFO - iteration 1057, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:59] {3343} INFO -  at 129.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:59] {3166} INFO - iteration 1058, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:59] {3343} INFO -  at 129.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:59] {3166} INFO - iteration 1059, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:21:59] {3343} INFO -  at 129.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:21:59] {3166} INFO - iteration 1060, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:00] {3343} INFO -  at 130.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:00] {3166} INFO - iteration 1061, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:00] {3343} INFO -  at 130.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:00] {3166} INFO - iteration 1062, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:00] {3343} INFO -  at 130.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:00] {3166} INFO - iteration 1063, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:00] {3343} INFO -  at 130.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:00] {3166} INFO - iteration 1064, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:00] {3343} INFO -  at 130.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:00] {3166} INFO - iteration 1065, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:00] {3343} INFO -  at 130.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:00] {3166} INFO - iteration 1066, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:00] {3343} INFO -  at 130.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:00] {3166} INFO - iteration 1067, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:00] {3343} INFO -  at 130.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:00] {3166} INFO - iteration 1068, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:00] {3343} INFO -  at 130.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:00] {3166} INFO - iteration 1069, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:01] {3343} INFO -  at 130.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:01] {3166} INFO - iteration 1070, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:01] {3343} INFO -  at 131.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:01] {3166} INFO - iteration 1071, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:01] {3343} INFO -  at 131.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:01] {3166} INFO - iteration 1072, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:01] {3343} INFO -  at 131.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:01] {3166} INFO - iteration 1073, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:01] {3343} INFO -  at 131.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:01] {3166} INFO - iteration 1074, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:01] {3343} INFO -  at 131.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:01] {3166} INFO - iteration 1075, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:01] {3343} INFO -  at 131.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:01] {3166} INFO - iteration 1076, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:02] {3343} INFO -  at 132.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:02] {3166} INFO - iteration 1077, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:02] {3343} INFO -  at 132.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:02] {3166} INFO - iteration 1078, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:02] {3343} INFO -  at 132.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:02] {3166} INFO - iteration 1079, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:02] {3343} INFO -  at 132.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:02] {3166} INFO - iteration 1080, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:02] {3343} INFO -  at 132.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:02] {3166} INFO - iteration 1081, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:02] {3343} INFO -  at 132.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:02] {3166} INFO - iteration 1082, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:02] {3343} INFO -  at 132.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:02] {3166} INFO - iteration 1083, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:02] {3343} INFO -  at 132.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:02] {3166} INFO - iteration 1084, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:03] {3343} INFO -  at 133.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:03] {3166} INFO - iteration 1085, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:03] {3343} INFO -  at 133.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:03] {3166} INFO - iteration 1086, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:03] {3343} INFO -  at 133.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:03] {3166} INFO - iteration 1087, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:03] {3343} INFO -  at 133.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:03] {3166} INFO - iteration 1088, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:03] {3343} INFO -  at 133.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:03] {3166} INFO - iteration 1089, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:03] {3343} INFO -  at 133.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:03] {3166} INFO - iteration 1090, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:03] {3343} INFO -  at 133.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:03] {3166} INFO - iteration 1091, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:03] {3343} INFO -  at 133.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:03] {3166} INFO - iteration 1092, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:04] {3343} INFO -  at 134.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:04] {3166} INFO - iteration 1093, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:04] {3343} INFO -  at 134.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:04] {3166} INFO - iteration 1094, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:04] {3343} INFO -  at 134.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:04] {3166} INFO - iteration 1095, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:04] {3343} INFO -  at 134.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:04] {3166} INFO - iteration 1096, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:04] {3343} INFO -  at 134.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:04] {3166} INFO - iteration 1097, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:04] {3343} INFO -  at 134.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:04] {3166} INFO - iteration 1098, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:04] {3343} INFO -  at 134.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:05] {3166} INFO - iteration 1099, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:05] {3343} INFO -  at 135.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:05] {3166} INFO - iteration 1100, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:05] {3343} INFO -  at 135.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:05] {3166} INFO - iteration 1101, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:05] {3343} INFO -  at 135.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:05] {3166} INFO - iteration 1102, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:05] {3343} INFO -  at 135.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:05] {3166} INFO - iteration 1103, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:05] {3343} INFO -  at 135.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:05] {3166} INFO - iteration 1104, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:05] {3343} INFO -  at 135.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:05] {3166} INFO - iteration 1105, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:05] {3343} INFO -  at 135.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:05] {3166} INFO - iteration 1106, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:06] {3343} INFO -  at 136.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:06] {3166} INFO - iteration 1107, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:06] {3343} INFO -  at 136.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:06] {3166} INFO - iteration 1108, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:06] {3343} INFO -  at 136.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:06] {3166} INFO - iteration 1109, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:06] {3343} INFO -  at 136.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:06] {3166} INFO - iteration 1110, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:06] {3343} INFO -  at 136.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:06] {3166} INFO - iteration 1111, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:06] {3343} INFO -  at 136.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:06] {3166} INFO - iteration 1112, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:06] {3343} INFO -  at 136.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:06] {3166} INFO - iteration 1113, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:06] {3343} INFO -  at 136.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:06] {3166} INFO - iteration 1114, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:07] {3343} INFO -  at 137.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:07] {3166} INFO - iteration 1115, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:07] {3343} INFO -  at 137.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:07] {3166} INFO - iteration 1116, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:07] {3343} INFO -  at 137.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:07] {3166} INFO - iteration 1117, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:07] {3343} INFO -  at 137.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:07] {3166} INFO - iteration 1118, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:07] {3343} INFO -  at 137.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:07] {3166} INFO - iteration 1119, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:07] {3343} INFO -  at 137.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:07] {3166} INFO - iteration 1120, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:07] {3343} INFO -  at 137.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:07] {3166} INFO - iteration 1121, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:07] {3343} INFO -  at 137.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:07] {3166} INFO - iteration 1122, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:07] {3343} INFO -  at 137.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:07] {3166} INFO - iteration 1123, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:07] {3343} INFO -  at 137.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:07] {3166} INFO - iteration 1124, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:07] {3343} INFO -  at 137.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:07] {3166} INFO - iteration 1125, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:08] {3343} INFO -  at 138.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:08] {3166} INFO - iteration 1126, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:08] {3343} INFO -  at 138.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:08] {3166} INFO - iteration 1127, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:08] {3343} INFO -  at 138.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:08] {3166} INFO - iteration 1128, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:08] {3343} INFO -  at 138.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:08] {3166} INFO - iteration 1129, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:08] {3343} INFO -  at 138.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:08] {3166} INFO - iteration 1130, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:08] {3343} INFO -  at 138.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:08] {3166} INFO - iteration 1131, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:08] {3343} INFO -  at 138.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:08] {3166} INFO - iteration 1132, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:08] {3343} INFO -  at 138.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:08] {3166} INFO - iteration 1133, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:08] {3343} INFO -  at 138.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:08] {3166} INFO - iteration 1134, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:09] {3343} INFO -  at 139.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:09] {3166} INFO - iteration 1135, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:09] {3343} INFO -  at 139.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:09] {3166} INFO - iteration 1136, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:09] {3343} INFO -  at 139.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:09] {3166} INFO - iteration 1137, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:09] {3343} INFO -  at 139.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:09] {3166} INFO - iteration 1138, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:09] {3343} INFO -  at 139.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:09] {3166} INFO - iteration 1139, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:09] {3343} INFO -  at 139.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:09] {3166} INFO - iteration 1140, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:09] {3343} INFO -  at 139.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:09] {3166} INFO - iteration 1141, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:10] {3343} INFO -  at 139.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:10] {3166} INFO - iteration 1142, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:10] {3343} INFO -  at 140.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:10] {3166} INFO - iteration 1143, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:10] {3343} INFO -  at 140.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:10] {3166} INFO - iteration 1144, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:10] {3343} INFO -  at 140.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:10] {3166} INFO - iteration 1145, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:10] {3343} INFO -  at 140.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:10] {3166} INFO - iteration 1146, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:10] {3343} INFO -  at 140.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:10] {3166} INFO - iteration 1147, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:10] {3343} INFO -  at 140.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:10] {3166} INFO - iteration 1148, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:11] {3343} INFO -  at 141.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:11] {3166} INFO - iteration 1149, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:11] {3343} INFO -  at 141.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:11] {3166} INFO - iteration 1150, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:11] {3343} INFO -  at 141.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:11] {3166} INFO - iteration 1151, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:11] {3343} INFO -  at 141.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:11] {3166} INFO - iteration 1152, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:11] {3343} INFO -  at 141.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:11] {3166} INFO - iteration 1153, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:11] {3343} INFO -  at 141.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:11] {3166} INFO - iteration 1154, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:11] {3343} INFO -  at 141.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:11] {3166} INFO - iteration 1155, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:12] {3343} INFO -  at 141.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:12] {3166} INFO - iteration 1156, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:12] {3343} INFO -  at 142.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:12] {3166} INFO - iteration 1157, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:12] {3343} INFO -  at 142.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:12] {3166} INFO - iteration 1158, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:12] {3343} INFO -  at 142.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:12] {3166} INFO - iteration 1159, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:12] {3343} INFO -  at 142.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:12] {3166} INFO - iteration 1160, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:12] {3343} INFO -  at 142.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:12] {3166} INFO - iteration 1161, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:12] {3343} INFO -  at 142.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:12] {3166} INFO - iteration 1162, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:12] {3343} INFO -  at 142.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:12] {3166} INFO - iteration 1163, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:13] {3343} INFO -  at 143.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:13] {3166} INFO - iteration 1164, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:13] {3343} INFO -  at 143.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:13] {3166} INFO - iteration 1165, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:13] {3343} INFO -  at 143.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:13] {3166} INFO - iteration 1166, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:13] {3343} INFO -  at 143.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:13] {3166} INFO - iteration 1167, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:13] {3343} INFO -  at 143.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:13] {3166} INFO - iteration 1168, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:13] {3343} INFO -  at 143.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:13] {3166} INFO - iteration 1169, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:13] {3343} INFO -  at 143.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:13] {3166} INFO - iteration 1170, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:14] {3343} INFO -  at 144.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:14] {3166} INFO - iteration 1171, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:14] {3343} INFO -  at 144.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:14] {3166} INFO - iteration 1172, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:14] {3343} INFO -  at 144.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:14] {3166} INFO - iteration 1173, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:14] {3343} INFO -  at 144.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:14] {3166} INFO - iteration 1174, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:14] {3343} INFO -  at 144.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:14] {3166} INFO - iteration 1175, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:14] {3343} INFO -  at 144.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:14] {3166} INFO - iteration 1176, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:14] {3343} INFO -  at 144.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:14] {3166} INFO - iteration 1177, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:14] {3343} INFO -  at 144.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:14] {3166} INFO - iteration 1178, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:15] {3343} INFO -  at 145.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:15] {3166} INFO - iteration 1179, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:15] {3343} INFO -  at 145.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:15] {3166} INFO - iteration 1180, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:15] {3343} INFO -  at 145.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:15] {3166} INFO - iteration 1181, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:15] {3343} INFO -  at 145.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:15] {3166} INFO - iteration 1182, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:15] {3343} INFO -  at 145.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:15] {3166} INFO - iteration 1183, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:15] {3343} INFO -  at 145.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:15] {3166} INFO - iteration 1184, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:15] {3343} INFO -  at 145.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:15] {3166} INFO - iteration 1185, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:15] {3343} INFO -  at 145.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:15] {3166} INFO - iteration 1186, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:16] {3343} INFO -  at 146.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:16] {3166} INFO - iteration 1187, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:16] {3343} INFO -  at 146.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:16] {3166} INFO - iteration 1188, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:16] {3343} INFO -  at 146.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:16] {3166} INFO - iteration 1189, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:16] {3343} INFO -  at 146.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:16] {3166} INFO - iteration 1190, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:16] {3343} INFO -  at 146.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:16] {3166} INFO - iteration 1191, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:16] {3343} INFO -  at 146.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:16] {3166} INFO - iteration 1192, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:17] {3343} INFO -  at 147.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:17] {3166} INFO - iteration 1193, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:17] {3343} INFO -  at 147.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:17] {3166} INFO - iteration 1194, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:17] {3343} INFO -  at 147.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:17] {3166} INFO - iteration 1195, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:17] {3343} INFO -  at 147.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:17] {3166} INFO - iteration 1196, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:17] {3343} INFO -  at 147.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:17] {3166} INFO - iteration 1197, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:17] {3343} INFO -  at 147.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:17] {3166} INFO - iteration 1198, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:17] {3343} INFO -  at 147.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:17] {3166} INFO - iteration 1199, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:18] {3343} INFO -  at 148.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:18] {3166} INFO - iteration 1200, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:18] {3343} INFO -  at 148.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:18] {3166} INFO - iteration 1201, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:18] {3343} INFO -  at 148.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:18] {3166} INFO - iteration 1202, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:18] {3343} INFO -  at 148.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:18] {3166} INFO - iteration 1203, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:18] {3343} INFO -  at 148.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:18] {3166} INFO - iteration 1204, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:18] {3343} INFO -  at 148.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:18] {3166} INFO - iteration 1205, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:18] {3343} INFO -  at 148.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:18] {3166} INFO - iteration 1206, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:19] {3343} INFO -  at 149.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:19] {3166} INFO - iteration 1207, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:19] {3343} INFO -  at 149.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:19] {3166} INFO - iteration 1208, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:19] {3343} INFO -  at 149.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:19] {3166} INFO - iteration 1209, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:19] {3343} INFO -  at 149.3s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:19] {3166} INFO - iteration 1210, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:19] {3343} INFO -  at 149.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:19] {3166} INFO - iteration 1211, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:19] {3343} INFO -  at 149.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:19] {3166} INFO - iteration 1212, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:19] {3343} INFO -  at 149.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:19] {3166} INFO - iteration 1213, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:19] {3343} INFO -  at 149.8s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:19] {3166} INFO - iteration 1214, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:20] {3343} INFO -  at 150.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:20] {3166} INFO - iteration 1215, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:20] {3343} INFO -  at 150.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:20] {3166} INFO - iteration 1216, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:20] {3343} INFO -  at 150.2s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:20] {3166} INFO - iteration 1217, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:20] {3343} INFO -  at 150.4s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:20] {3166} INFO - iteration 1218, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:20] {3343} INFO -  at 150.5s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:20] {3166} INFO - iteration 1219, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:20] {3343} INFO -  at 150.6s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:20] {3166} INFO - iteration 1220, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:20] {3343} INFO -  at 150.7s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:20] {3166} INFO - iteration 1221, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:20] {3343} INFO -  at 150.9s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:20] {3166} INFO - iteration 1222, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:21] {3343} INFO -  at 151.0s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:21] {3166} INFO - iteration 1223, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:21] {3343} INFO -  at 151.1s,	estimator rf's best error=82.3331,	best estimator rf's best error=82.3331
[flaml.automl: 04-23 11:22:21] {3166} INFO - iteration 1224, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:21] {3343} INFO -  at 151.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:21] {3166} INFO - iteration 1225, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:21] {3343} INFO -  at 151.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:21] {3166} INFO - iteration 1226, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:21] {3343} INFO -  at 151.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:21] {3166} INFO - iteration 1227, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:21] {3343} INFO -  at 151.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:21] {3166} INFO - iteration 1228, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:21] {3343} INFO -  at 151.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:21] {3166} INFO - iteration 1229, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:22] {3343} INFO -  at 152.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:22] {3166} INFO - iteration 1230, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:22] {3343} INFO -  at 152.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:22] {3166} INFO - iteration 1231, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:22] {3343} INFO -  at 152.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:22] {3166} INFO - iteration 1232, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:22] {3343} INFO -  at 152.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:22] {3166} INFO - iteration 1233, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:22] {3343} INFO -  at 152.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:22] {3166} INFO - iteration 1234, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:22] {3343} INFO -  at 152.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:22] {3166} INFO - iteration 1235, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:22] {3343} INFO -  at 152.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:22] {3166} INFO - iteration 1236, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:23] {3343} INFO -  at 153.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:23] {3166} INFO - iteration 1237, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:23] {3343} INFO -  at 153.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:23] {3166} INFO - iteration 1238, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:23] {3343} INFO -  at 153.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:23] {3166} INFO - iteration 1239, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:23] {3343} INFO -  at 153.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:23] {3166} INFO - iteration 1240, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:23] {3343} INFO -  at 153.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:23] {3166} INFO - iteration 1241, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:23] {3343} INFO -  at 153.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:23] {3166} INFO - iteration 1242, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:23] {3343} INFO -  at 153.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:23] {3166} INFO - iteration 1243, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:24] {3343} INFO -  at 154.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:24] {3166} INFO - iteration 1244, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:24] {3343} INFO -  at 154.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:24] {3166} INFO - iteration 1245, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:24] {3343} INFO -  at 154.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:24] {3166} INFO - iteration 1246, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:24] {3343} INFO -  at 154.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:24] {3166} INFO - iteration 1247, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:24] {3343} INFO -  at 154.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:24] {3166} INFO - iteration 1248, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:24] {3343} INFO -  at 154.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:24] {3166} INFO - iteration 1249, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:24] {3343} INFO -  at 154.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:24] {3166} INFO - iteration 1250, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:25] {3343} INFO -  at 154.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:25] {3166} INFO - iteration 1251, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:25] {3343} INFO -  at 155.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:25] {3166} INFO - iteration 1252, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:25] {3343} INFO -  at 155.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:25] {3166} INFO - iteration 1253, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:25] {3343} INFO -  at 155.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:25] {3166} INFO - iteration 1254, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:25] {3343} INFO -  at 155.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:25] {3166} INFO - iteration 1255, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:25] {3343} INFO -  at 155.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:25] {3166} INFO - iteration 1256, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:25] {3343} INFO -  at 155.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:25] {3166} INFO - iteration 1257, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:25] {3343} INFO -  at 155.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:25] {3166} INFO - iteration 1258, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:25] {3343} INFO -  at 155.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:25] {3166} INFO - iteration 1259, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:26] {3343} INFO -  at 156.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:26] {3166} INFO - iteration 1260, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:26] {3343} INFO -  at 156.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:26] {3166} INFO - iteration 1261, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:26] {3343} INFO -  at 156.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:26] {3166} INFO - iteration 1262, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:26] {3343} INFO -  at 156.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:26] {3166} INFO - iteration 1263, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:26] {3343} INFO -  at 156.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:26] {3166} INFO - iteration 1264, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:26] {3343} INFO -  at 156.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:26] {3166} INFO - iteration 1265, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:26] {3343} INFO -  at 156.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:26] {3166} INFO - iteration 1266, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:27] {3343} INFO -  at 157.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:27] {3166} INFO - iteration 1267, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:27] {3343} INFO -  at 157.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:27] {3166} INFO - iteration 1268, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:27] {3343} INFO -  at 157.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:27] {3166} INFO - iteration 1269, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:27] {3343} INFO -  at 157.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:27] {3166} INFO - iteration 1270, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:27] {3343} INFO -  at 157.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:27] {3166} INFO - iteration 1271, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:27] {3343} INFO -  at 157.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:27] {3166} INFO - iteration 1272, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:27] {3343} INFO -  at 157.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:27] {3166} INFO - iteration 1273, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:28] {3343} INFO -  at 158.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:28] {3166} INFO - iteration 1274, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:28] {3343} INFO -  at 158.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:28] {3166} INFO - iteration 1275, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:28] {3343} INFO -  at 158.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:28] {3166} INFO - iteration 1276, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:28] {3343} INFO -  at 158.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:28] {3166} INFO - iteration 1277, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:28] {3343} INFO -  at 158.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:28] {3166} INFO - iteration 1278, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:28] {3343} INFO -  at 158.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:28] {3166} INFO - iteration 1279, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:28] {3343} INFO -  at 158.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:28] {3166} INFO - iteration 1280, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:29] {3343} INFO -  at 159.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:29] {3166} INFO - iteration 1281, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:29] {3343} INFO -  at 159.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:29] {3166} INFO - iteration 1282, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:29] {3343} INFO -  at 159.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:29] {3166} INFO - iteration 1283, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:29] {3343} INFO -  at 159.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:29] {3166} INFO - iteration 1284, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:29] {3343} INFO -  at 159.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:29] {3166} INFO - iteration 1285, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:29] {3343} INFO -  at 159.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:29] {3166} INFO - iteration 1286, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:29] {3343} INFO -  at 159.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:29] {3166} INFO - iteration 1287, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:30] {3343} INFO -  at 159.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:30] {3166} INFO - iteration 1288, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:30] {3343} INFO -  at 160.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:30] {3166} INFO - iteration 1289, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:30] {3343} INFO -  at 160.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:30] {3166} INFO - iteration 1290, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:30] {3343} INFO -  at 160.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:30] {3166} INFO - iteration 1291, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:30] {3343} INFO -  at 160.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:30] {3166} INFO - iteration 1292, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:30] {3343} INFO -  at 160.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:30] {3166} INFO - iteration 1293, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:30] {3343} INFO -  at 160.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:30] {3166} INFO - iteration 1294, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:30] {3343} INFO -  at 160.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:30] {3166} INFO - iteration 1295, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:31] {3343} INFO -  at 161.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:31] {3166} INFO - iteration 1296, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:31] {3343} INFO -  at 161.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:31] {3166} INFO - iteration 1297, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:31] {3343} INFO -  at 161.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:31] {3166} INFO - iteration 1298, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:31] {3343} INFO -  at 161.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:31] {3166} INFO - iteration 1299, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:31] {3343} INFO -  at 161.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:31] {3166} INFO - iteration 1300, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:31] {3343} INFO -  at 161.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:31] {3166} INFO - iteration 1301, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:31] {3343} INFO -  at 161.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:31] {3166} INFO - iteration 1302, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:31] {3343} INFO -  at 161.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:31] {3166} INFO - iteration 1303, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:32] {3343} INFO -  at 162.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:32] {3166} INFO - iteration 1304, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:32] {3343} INFO -  at 162.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:32] {3166} INFO - iteration 1305, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:32] {3343} INFO -  at 162.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:32] {3166} INFO - iteration 1306, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:32] {3343} INFO -  at 162.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:32] {3166} INFO - iteration 1307, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:32] {3343} INFO -  at 162.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:32] {3166} INFO - iteration 1308, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:32] {3343} INFO -  at 162.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:32] {3166} INFO - iteration 1309, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:32] {3343} INFO -  at 162.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:32] {3166} INFO - iteration 1310, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:33] {3343} INFO -  at 163.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:33] {3166} INFO - iteration 1311, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:33] {3343} INFO -  at 163.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:33] {3166} INFO - iteration 1312, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:33] {3343} INFO -  at 163.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:33] {3166} INFO - iteration 1313, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:33] {3343} INFO -  at 163.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:33] {3166} INFO - iteration 1314, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:33] {3343} INFO -  at 163.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:33] {3166} INFO - iteration 1315, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:33] {3343} INFO -  at 163.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:33] {3166} INFO - iteration 1316, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:33] {3343} INFO -  at 163.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:33] {3166} INFO - iteration 1317, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:33] {3343} INFO -  at 163.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:33] {3166} INFO - iteration 1318, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:34] {3343} INFO -  at 164.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:34] {3166} INFO - iteration 1319, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:34] {3343} INFO -  at 164.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:34] {3166} INFO - iteration 1320, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:34] {3343} INFO -  at 164.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:34] {3166} INFO - iteration 1321, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:34] {3343} INFO -  at 164.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:34] {3166} INFO - iteration 1322, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:34] {3343} INFO -  at 164.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:34] {3166} INFO - iteration 1323, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:34] {3343} INFO -  at 164.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:34] {3166} INFO - iteration 1324, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:34] {3343} INFO -  at 164.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:34] {3166} INFO - iteration 1325, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:35] {3343} INFO -  at 165.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:35] {3166} INFO - iteration 1326, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:35] {3343} INFO -  at 165.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:35] {3166} INFO - iteration 1327, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:35] {3343} INFO -  at 165.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:35] {3166} INFO - iteration 1328, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:35] {3343} INFO -  at 165.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:35] {3166} INFO - iteration 1329, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:35] {3343} INFO -  at 165.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:35] {3166} INFO - iteration 1330, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:35] {3343} INFO -  at 165.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:35] {3166} INFO - iteration 1331, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:35] {3343} INFO -  at 165.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:35] {3166} INFO - iteration 1332, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:36] {3343} INFO -  at 166.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:36] {3166} INFO - iteration 1333, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:36] {3343} INFO -  at 166.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:36] {3166} INFO - iteration 1334, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:36] {3343} INFO -  at 166.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:36] {3166} INFO - iteration 1335, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:36] {3343} INFO -  at 166.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:36] {3166} INFO - iteration 1336, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:36] {3343} INFO -  at 166.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:36] {3166} INFO - iteration 1337, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:36] {3343} INFO -  at 166.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:36] {3166} INFO - iteration 1338, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:37] {3343} INFO -  at 167.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:37] {3166} INFO - iteration 1339, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:37] {3343} INFO -  at 167.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:37] {3166} INFO - iteration 1340, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:37] {3343} INFO -  at 167.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:37] {3166} INFO - iteration 1341, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:37] {3343} INFO -  at 167.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:37] {3166} INFO - iteration 1342, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:37] {3343} INFO -  at 167.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:37] {3166} INFO - iteration 1343, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:37] {3343} INFO -  at 167.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:37] {3166} INFO - iteration 1344, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:37] {3343} INFO -  at 167.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:37] {3166} INFO - iteration 1345, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:37] {3343} INFO -  at 167.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:37] {3166} INFO - iteration 1346, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:38] {3343} INFO -  at 168.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:38] {3166} INFO - iteration 1347, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:38] {3343} INFO -  at 168.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:38] {3166} INFO - iteration 1348, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:38] {3343} INFO -  at 168.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:38] {3166} INFO - iteration 1349, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:38] {3343} INFO -  at 168.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:38] {3166} INFO - iteration 1350, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:38] {3343} INFO -  at 168.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:38] {3166} INFO - iteration 1351, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:38] {3343} INFO -  at 168.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:38] {3166} INFO - iteration 1352, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:38] {3343} INFO -  at 168.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:38] {3166} INFO - iteration 1353, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:38] {3343} INFO -  at 168.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:38] {3166} INFO - iteration 1354, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:39] {3343} INFO -  at 169.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:39] {3166} INFO - iteration 1355, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:39] {3343} INFO -  at 169.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:39] {3166} INFO - iteration 1356, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:39] {3343} INFO -  at 169.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:39] {3166} INFO - iteration 1357, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:39] {3343} INFO -  at 169.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:39] {3166} INFO - iteration 1358, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:39] {3343} INFO -  at 169.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:39] {3166} INFO - iteration 1359, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:39] {3343} INFO -  at 169.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:39] {3166} INFO - iteration 1360, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:39] {3343} INFO -  at 169.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:39] {3166} INFO - iteration 1361, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:40] {3343} INFO -  at 169.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:40] {3166} INFO - iteration 1362, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:40] {3343} INFO -  at 170.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:40] {3166} INFO - iteration 1363, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:40] {3343} INFO -  at 170.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:40] {3166} INFO - iteration 1364, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:40] {3343} INFO -  at 170.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:40] {3166} INFO - iteration 1365, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:40] {3343} INFO -  at 170.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:40] {3166} INFO - iteration 1366, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:40] {3343} INFO -  at 170.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:40] {3166} INFO - iteration 1367, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:40] {3343} INFO -  at 170.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:40] {3166} INFO - iteration 1368, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:40] {3343} INFO -  at 170.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:40] {3166} INFO - iteration 1369, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:41] {3343} INFO -  at 171.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:41] {3166} INFO - iteration 1370, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:41] {3343} INFO -  at 171.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:41] {3166} INFO - iteration 1371, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:41] {3343} INFO -  at 171.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:41] {3166} INFO - iteration 1372, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:41] {3343} INFO -  at 171.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:41] {3166} INFO - iteration 1373, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:41] {3343} INFO -  at 171.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:41] {3166} INFO - iteration 1374, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:41] {3343} INFO -  at 171.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:41] {3166} INFO - iteration 1375, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:42] {3343} INFO -  at 172.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:42] {3166} INFO - iteration 1376, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:42] {3343} INFO -  at 172.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:42] {3166} INFO - iteration 1377, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:42] {3343} INFO -  at 172.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:42] {3166} INFO - iteration 1378, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:42] {3343} INFO -  at 172.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:42] {3166} INFO - iteration 1379, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:42] {3343} INFO -  at 172.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:42] {3166} INFO - iteration 1380, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:42] {3343} INFO -  at 172.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:42] {3166} INFO - iteration 1381, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:42] {3343} INFO -  at 172.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:42] {3166} INFO - iteration 1382, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:42] {3343} INFO -  at 172.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:42] {3166} INFO - iteration 1383, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:43] {3343} INFO -  at 173.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:43] {3166} INFO - iteration 1384, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:43] {3343} INFO -  at 173.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:43] {3166} INFO - iteration 1385, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:43] {3343} INFO -  at 173.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:43] {3166} INFO - iteration 1386, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:43] {3343} INFO -  at 173.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:43] {3166} INFO - iteration 1387, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:43] {3343} INFO -  at 173.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:43] {3166} INFO - iteration 1388, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:43] {3343} INFO -  at 173.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:43] {3166} INFO - iteration 1389, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:43] {3343} INFO -  at 173.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:43] {3166} INFO - iteration 1390, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:44] {3343} INFO -  at 174.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:44] {3166} INFO - iteration 1391, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:44] {3343} INFO -  at 174.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:44] {3166} INFO - iteration 1392, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:44] {3343} INFO -  at 174.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:44] {3166} INFO - iteration 1393, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:44] {3343} INFO -  at 174.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:44] {3166} INFO - iteration 1394, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:44] {3343} INFO -  at 174.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:44] {3166} INFO - iteration 1395, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:44] {3343} INFO -  at 174.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:44] {3166} INFO - iteration 1396, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:44] {3343} INFO -  at 174.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:44] {3166} INFO - iteration 1397, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:44] {3343} INFO -  at 174.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:44] {3166} INFO - iteration 1398, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:45] {3343} INFO -  at 175.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:45] {3166} INFO - iteration 1399, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:45] {3343} INFO -  at 175.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:45] {3166} INFO - iteration 1400, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:45] {3343} INFO -  at 175.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:45] {3166} INFO - iteration 1401, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:45] {3343} INFO -  at 175.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:45] {3166} INFO - iteration 1402, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:45] {3343} INFO -  at 175.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:45] {3166} INFO - iteration 1403, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:45] {3343} INFO -  at 175.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:45] {3166} INFO - iteration 1404, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:45] {3343} INFO -  at 175.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:45] {3166} INFO - iteration 1405, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:46] {3343} INFO -  at 175.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:46] {3166} INFO - iteration 1406, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:46] {3343} INFO -  at 176.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:46] {3166} INFO - iteration 1407, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:46] {3343} INFO -  at 176.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:46] {3166} INFO - iteration 1408, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:46] {3343} INFO -  at 176.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:46] {3166} INFO - iteration 1409, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:46] {3343} INFO -  at 176.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:46] {3166} INFO - iteration 1410, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:46] {3343} INFO -  at 176.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:46] {3166} INFO - iteration 1411, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:46] {3343} INFO -  at 176.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:46] {3166} INFO - iteration 1412, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:46] {3343} INFO -  at 176.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:46] {3166} INFO - iteration 1413, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:47] {3343} INFO -  at 177.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:47] {3166} INFO - iteration 1414, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:47] {3343} INFO -  at 177.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:47] {3166} INFO - iteration 1415, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:47] {3343} INFO -  at 177.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:47] {3166} INFO - iteration 1416, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:47] {3343} INFO -  at 177.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:47] {3166} INFO - iteration 1417, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:47] {3343} INFO -  at 177.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:47] {3166} INFO - iteration 1418, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:47] {3343} INFO -  at 177.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:47] {3166} INFO - iteration 1419, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:47] {3343} INFO -  at 177.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:47] {3166} INFO - iteration 1420, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:48] {3343} INFO -  at 178.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:48] {3166} INFO - iteration 1421, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:48] {3343} INFO -  at 178.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:48] {3166} INFO - iteration 1422, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:48] {3343} INFO -  at 178.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:48] {3166} INFO - iteration 1423, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:48] {3343} INFO -  at 178.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:48] {3166} INFO - iteration 1424, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:48] {3343} INFO -  at 178.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:48] {3166} INFO - iteration 1425, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:48] {3343} INFO -  at 178.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:48] {3166} INFO - iteration 1426, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:48] {3343} INFO -  at 178.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:48] {3166} INFO - iteration 1427, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:49] {3343} INFO -  at 179.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:49] {3166} INFO - iteration 1428, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:49] {3343} INFO -  at 179.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:49] {3166} INFO - iteration 1429, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:49] {3343} INFO -  at 179.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:49] {3166} INFO - iteration 1430, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:49] {3343} INFO -  at 179.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:49] {3166} INFO - iteration 1431, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:49] {3343} INFO -  at 179.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:49] {3166} INFO - iteration 1432, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:49] {3343} INFO -  at 179.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:49] {3166} INFO - iteration 1433, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:49] {3343} INFO -  at 179.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:49] {3166} INFO - iteration 1434, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:50] {3343} INFO -  at 180.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:50] {3166} INFO - iteration 1435, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:50] {3343} INFO -  at 180.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:50] {3166} INFO - iteration 1436, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:50] {3343} INFO -  at 180.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:50] {3166} INFO - iteration 1437, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:50] {3343} INFO -  at 180.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:50] {3166} INFO - iteration 1438, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:50] {3343} INFO -  at 180.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:50] {3166} INFO - iteration 1439, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:50] {3343} INFO -  at 180.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:50] {3166} INFO - iteration 1440, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:50] {3343} INFO -  at 180.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:50] {3166} INFO - iteration 1441, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:51] {3343} INFO -  at 180.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:51] {3166} INFO - iteration 1442, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:51] {3343} INFO -  at 181.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:51] {3166} INFO - iteration 1443, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:51] {3343} INFO -  at 181.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:51] {3166} INFO - iteration 1444, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:51] {3343} INFO -  at 181.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:51] {3166} INFO - iteration 1445, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:51] {3343} INFO -  at 181.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:51] {3166} INFO - iteration 1446, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:51] {3343} INFO -  at 181.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:51] {3166} INFO - iteration 1447, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:51] {3343} INFO -  at 181.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:51] {3166} INFO - iteration 1448, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:51] {3343} INFO -  at 181.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:51] {3166} INFO - iteration 1449, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:52] {3343} INFO -  at 182.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:52] {3166} INFO - iteration 1450, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:52] {3343} INFO -  at 182.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:52] {3166} INFO - iteration 1451, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:52] {3343} INFO -  at 182.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:52] {3166} INFO - iteration 1452, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:52] {3343} INFO -  at 182.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:52] {3166} INFO - iteration 1453, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:52] {3343} INFO -  at 182.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:52] {3166} INFO - iteration 1454, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:52] {3343} INFO -  at 182.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:52] {3166} INFO - iteration 1455, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:52] {3343} INFO -  at 182.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:52] {3166} INFO - iteration 1456, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:53] {3343} INFO -  at 183.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:53] {3166} INFO - iteration 1457, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:53] {3343} INFO -  at 183.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:53] {3166} INFO - iteration 1458, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:53] {3343} INFO -  at 183.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:53] {3166} INFO - iteration 1459, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:53] {3343} INFO -  at 183.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:53] {3166} INFO - iteration 1460, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:53] {3343} INFO -  at 183.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:53] {3166} INFO - iteration 1461, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:53] {3343} INFO -  at 183.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:53] {3166} INFO - iteration 1462, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:53] {3343} INFO -  at 183.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:53] {3166} INFO - iteration 1463, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:53] {3343} INFO -  at 183.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:53] {3166} INFO - iteration 1464, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:54] {3343} INFO -  at 184.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:54] {3166} INFO - iteration 1465, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:54] {3343} INFO -  at 184.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:54] {3166} INFO - iteration 1466, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:54] {3343} INFO -  at 184.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:54] {3166} INFO - iteration 1467, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:54] {3343} INFO -  at 184.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:54] {3166} INFO - iteration 1468, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:54] {3343} INFO -  at 184.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:54] {3166} INFO - iteration 1469, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:54] {3343} INFO -  at 184.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:54] {3166} INFO - iteration 1470, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:54] {3343} INFO -  at 184.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:54] {3166} INFO - iteration 1471, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:54] {3343} INFO -  at 184.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:54] {3166} INFO - iteration 1472, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:55] {3343} INFO -  at 184.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:55] {3166} INFO - iteration 1473, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:55] {3343} INFO -  at 185.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:55] {3166} INFO - iteration 1474, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:55] {3343} INFO -  at 185.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:55] {3166} INFO - iteration 1475, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:55] {3343} INFO -  at 185.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:55] {3166} INFO - iteration 1476, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:55] {3343} INFO -  at 185.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:55] {3166} INFO - iteration 1477, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:55] {3343} INFO -  at 185.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:55] {3166} INFO - iteration 1478, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:55] {3343} INFO -  at 185.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:55] {3166} INFO - iteration 1479, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:55] {3343} INFO -  at 185.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:55] {3166} INFO - iteration 1480, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:55] {3343} INFO -  at 185.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:55] {3166} INFO - iteration 1481, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:56] {3343} INFO -  at 186.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:56] {3166} INFO - iteration 1482, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:56] {3343} INFO -  at 186.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:56] {3166} INFO - iteration 1483, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:56] {3343} INFO -  at 186.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:56] {3166} INFO - iteration 1484, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:56] {3343} INFO -  at 186.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:56] {3166} INFO - iteration 1485, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:56] {3343} INFO -  at 186.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:56] {3166} INFO - iteration 1486, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:56] {3343} INFO -  at 186.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:56] {3166} INFO - iteration 1487, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:56] {3343} INFO -  at 186.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:56] {3166} INFO - iteration 1488, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:56] {3343} INFO -  at 186.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:56] {3166} INFO - iteration 1489, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:57] {3343} INFO -  at 187.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:57] {3166} INFO - iteration 1490, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:57] {3343} INFO -  at 187.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:57] {3166} INFO - iteration 1491, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:57] {3343} INFO -  at 187.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:57] {3166} INFO - iteration 1492, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:57] {3343} INFO -  at 187.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:57] {3166} INFO - iteration 1493, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:57] {3343} INFO -  at 187.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:57] {3166} INFO - iteration 1494, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:57] {3343} INFO -  at 187.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:57] {3166} INFO - iteration 1495, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:57] {3343} INFO -  at 187.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:57] {3166} INFO - iteration 1496, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:57] {3343} INFO -  at 187.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:57] {3166} INFO - iteration 1497, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:22:57] {3343} INFO -  at 187.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:57] {3166} INFO - iteration 1498, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:58] {3343} INFO -  at 188.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:58] {3166} INFO - iteration 1499, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:58] {3343} INFO -  at 188.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:58] {3166} INFO - iteration 1500, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:58] {3343} INFO -  at 188.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:58] {3166} INFO - iteration 1501, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:58] {3343} INFO -  at 188.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:58] {3166} INFO - iteration 1502, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:58] {3343} INFO -  at 188.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:58] {3166} INFO - iteration 1503, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:58] {3343} INFO -  at 188.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:58] {3166} INFO - iteration 1504, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:58] {3343} INFO -  at 188.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:58] {3166} INFO - iteration 1505, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:58] {3343} INFO -  at 188.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:58] {3166} INFO - iteration 1506, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:59] {3343} INFO -  at 189.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:59] {3166} INFO - iteration 1507, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:59] {3343} INFO -  at 189.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:59] {3166} INFO - iteration 1508, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:59] {3343} INFO -  at 189.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:59] {3166} INFO - iteration 1509, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:59] {3343} INFO -  at 189.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:59] {3166} INFO - iteration 1510, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:59] {3343} INFO -  at 189.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269

[flaml.automl: 04-23 11:22:59] {3166} INFO - iteration 1511, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:59] {3343} INFO -  at 189.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:59] {3166} INFO - iteration 1512, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:59] {3343} INFO -  at 189.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:59] {3166} INFO - iteration 1513, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:59] {3343} INFO -  at 189.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:59] {3166} INFO - iteration 1514, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:22:59] {3343} INFO -  at 189.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:22:59] {3166} INFO - iteration 1515, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:00] {3343} INFO -  at 190.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:00] {3166} INFO - iteration 1516, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:00] {3343} INFO -  at 190.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:00] {3166} INFO - iteration 1517, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:00] {3343} INFO -  at 190.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:00] {3166} INFO - iteration 1518, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:00] {3343} INFO -  at 190.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:00] {3166} INFO - iteration 1519, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:00] {3343} INFO -  at 190.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:00] {3166} INFO - iteration 1520, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:00] {3343} INFO -  at 190.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:00] {3166} INFO - iteration 1521, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:00] {3343} INFO -  at 190.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:00] {3166} INFO - iteration 1522, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:01] {3343} INFO -  at 190.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:01] {3166} INFO - iteration 1523, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:01] {3343} INFO -  at 191.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:01] {3166} INFO - iteration 1524, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:01] {3343} INFO -  at 191.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:01] {3166} INFO - iteration 1525, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:01] {3343} INFO -  at 191.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:01] {3166} INFO - iteration 1526, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:01] {3343} INFO -  at 191.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:01] {3166} INFO - iteration 1527, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:01] {3343} INFO -  at 191.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:01] {3166} INFO - iteration 1528, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:01] {3343} INFO -  at 191.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:01] {3166} INFO - iteration 1529, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:01] {3343} INFO -  at 191.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:01] {3166} INFO - iteration 1530, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:01] {3343} INFO -  at 191.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:01] {3166} INFO - iteration 1531, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:01] {3343} INFO -  at 191.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:01] {3166} INFO - iteration 1532, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:02] {3343} INFO -  at 192.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:02] {3166} INFO - iteration 1533, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:02] {3343} INFO -  at 192.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:02] {3166} INFO - iteration 1534, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:02] {3343} INFO -  at 192.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:02] {3166} INFO - iteration 1535, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:02] {3343} INFO -  at 192.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:02] {3166} INFO - iteration 1536, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:02] {3343} INFO -  at 192.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:02] {3166} INFO - iteration 1537, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:02] {3343} INFO -  at 192.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:02] {3166} INFO - iteration 1538, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:02] {3343} INFO -  at 192.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:02] {3166} INFO - iteration 1539, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:02] {3343} INFO -  at 192.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:02] {3166} INFO - iteration 1540, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:02] {3343} INFO -  at 192.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:02] {3166} INFO - iteration 1541, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:02] {3343} INFO -  at 192.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:02] {3166} INFO - iteration 1542, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:03] {3343} INFO -  at 193.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:03] {3166} INFO - iteration 1543, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:03] {3343} INFO -  at 193.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:03] {3166} INFO - iteration 1544, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:03] {3343} INFO -  at 193.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:03] {3166} INFO - iteration 1545, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:03] {3343} INFO -  at 193.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:03] {3166} INFO - iteration 1546, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:03] {3343} INFO -  at 193.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:03] {3166} INFO - iteration 1547, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:03] {3343} INFO -  at 193.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:03] {3166} INFO - iteration 1548, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:03] {3343} INFO -  at 193.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:03] {3166} INFO - iteration 1549, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:03] {3343} INFO -  at 193.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:03] {3166} INFO - iteration 1550, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:04] {3343} INFO -  at 194.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:04] {3166} INFO - iteration 1551, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:04] {3343} INFO -  at 194.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:04] {3166} INFO - iteration 1552, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:04] {3343} INFO -  at 194.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:04] {3166} INFO - iteration 1553, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:04] {3343} INFO -  at 194.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:04] {3166} INFO - iteration 1554, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:04] {3343} INFO -  at 194.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:04] {3166} INFO - iteration 1555, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:05] {3343} INFO -  at 195.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:05] {3166} INFO - iteration 1556, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:05] {3343} INFO -  at 195.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:05] {3166} INFO - iteration 1557, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:05] {3343} INFO -  at 195.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:05] {3166} INFO - iteration 1558, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:05] {3343} INFO -  at 195.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:05] {3166} INFO - iteration 1559, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:05] {3343} INFO -  at 195.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:05] {3166} INFO - iteration 1560, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:05] {3343} INFO -  at 195.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:05] {3166} INFO - iteration 1561, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:06] {3343} INFO -  at 196.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:06] {3166} INFO - iteration 1562, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:06] {3343} INFO -  at 196.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:06] {3166} INFO - iteration 1563, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:06] {3343} INFO -  at 196.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:06] {3166} INFO - iteration 1564, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:06] {3343} INFO -  at 196.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:06] {3166} INFO - iteration 1565, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:06] {3343} INFO -  at 196.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:06] {3166} INFO - iteration 1566, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:06] {3343} INFO -  at 196.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:06] {3166} INFO - iteration 1567, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:06] {3343} INFO -  at 196.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:06] {3166} INFO - iteration 1568, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:07] {3343} INFO -  at 196.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:07] {3166} INFO - iteration 1569, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:07] {3343} INFO -  at 197.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:07] {3166} INFO - iteration 1570, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:07] {3343} INFO -  at 197.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:07] {3166} INFO - iteration 1571, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:07] {3343} INFO -  at 197.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:07] {3166} INFO - iteration 1572, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:07] {3343} INFO -  at 197.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:07] {3166} INFO - iteration 1573, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:07] {3343} INFO -  at 197.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:07] {3166} INFO - iteration 1574, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:07] {3343} INFO -  at 197.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:07] {3166} INFO - iteration 1575, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:08] {3343} INFO -  at 198.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:08] {3166} INFO - iteration 1576, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:08] {3343} INFO -  at 198.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:08] {3166} INFO - iteration 1577, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:08] {3343} INFO -  at 198.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:08] {3166} INFO - iteration 1578, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:08] {3343} INFO -  at 198.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:08] {3166} INFO - iteration 1579, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:08] {3343} INFO -  at 198.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:08] {3166} INFO - iteration 1580, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:08] {3343} INFO -  at 198.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:08] {3166} INFO - iteration 1581, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:08] {3343} INFO -  at 198.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:08] {3166} INFO - iteration 1582, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:09] {3343} INFO -  at 199.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:09] {3166} INFO - iteration 1583, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:09] {3343} INFO -  at 199.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:09] {3166} INFO - iteration 1584, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:09] {3343} INFO -  at 199.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:09] {3166} INFO - iteration 1585, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:09] {3343} INFO -  at 199.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:09] {3166} INFO - iteration 1586, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:09] {3343} INFO -  at 199.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:09] {3166} INFO - iteration 1587, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:09] {3343} INFO -  at 199.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:09] {3166} INFO - iteration 1588, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:09] {3343} INFO -  at 199.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:09] {3166} INFO - iteration 1589, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:10] {3343} INFO -  at 200.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:10] {3166} INFO - iteration 1590, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:10] {3343} INFO -  at 200.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:10] {3166} INFO - iteration 1591, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:10] {3343} INFO -  at 200.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:10] {3166} INFO - iteration 1592, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:10] {3343} INFO -  at 200.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:10] {3166} INFO - iteration 1593, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:10] {3343} INFO -  at 200.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:10] {3166} INFO - iteration 1594, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:11] {3343} INFO -  at 201.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:11] {3166} INFO - iteration 1595, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:11] {3343} INFO -  at 201.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:11] {3166} INFO - iteration 1596, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:11] {3343} INFO -  at 201.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:11] {3166} INFO - iteration 1597, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:11] {3343} INFO -  at 201.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:11] {3166} INFO - iteration 1598, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:11] {3343} INFO -  at 201.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:11] {3166} INFO - iteration 1599, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:12] {3343} INFO -  at 202.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:12] {3166} INFO - iteration 1600, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:12] {3343} INFO -  at 202.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:12] {3166} INFO - iteration 1601, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:12] {3343} INFO -  at 202.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:12] {3166} INFO - iteration 1602, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:12] {3343} INFO -  at 202.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:12] {3166} INFO - iteration 1603, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:12] {3343} INFO -  at 202.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:12] {3166} INFO - iteration 1604, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:12] {3343} INFO -  at 202.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:12] {3166} INFO - iteration 1605, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:13] {3343} INFO -  at 203.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:13] {3166} INFO - iteration 1606, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:13] {3343} INFO -  at 203.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:13] {3166} INFO - iteration 1607, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:13] {3343} INFO -  at 203.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:13] {3166} INFO - iteration 1608, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:13] {3343} INFO -  at 203.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:13] {3166} INFO - iteration 1609, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:13] {3343} INFO -  at 203.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:13] {3166} INFO - iteration 1610, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:13] {3343} INFO -  at 203.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:13] {3166} INFO - iteration 1611, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:13] {3343} INFO -  at 203.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:13] {3166} INFO - iteration 1612, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:14] {3343} INFO -  at 204.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:14] {3166} INFO - iteration 1613, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:14] {3343} INFO -  at 204.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:14] {3166} INFO - iteration 1614, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:14] {3343} INFO -  at 204.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:14] {3166} INFO - iteration 1615, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:14] {3343} INFO -  at 204.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:14] {3166} INFO - iteration 1616, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:14] {3343} INFO -  at 204.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:14] {3166} INFO - iteration 1617, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:15] {3343} INFO -  at 205.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:15] {3166} INFO - iteration 1618, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:15] {3343} INFO -  at 205.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:15] {3166} INFO - iteration 1619, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:15] {3343} INFO -  at 205.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:15] {3166} INFO - iteration 1620, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:15] {3343} INFO -  at 205.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:15] {3166} INFO - iteration 1621, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:15] {3343} INFO -  at 205.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:15] {3166} INFO - iteration 1622, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:15] {3343} INFO -  at 205.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:15] {3166} INFO - iteration 1623, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:15] {3343} INFO -  at 205.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:15] {3166} INFO - iteration 1624, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:16] {3343} INFO -  at 206.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:16] {3166} INFO - iteration 1625, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:16] {3343} INFO -  at 206.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:16] {3166} INFO - iteration 1626, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:16] {3343} INFO -  at 206.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:16] {3166} INFO - iteration 1627, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:16] {3343} INFO -  at 206.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:16] {3166} INFO - iteration 1628, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:16] {3343} INFO -  at 206.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:16] {3166} INFO - iteration 1629, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:16] {3343} INFO -  at 206.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:16] {3166} INFO - iteration 1630, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:16] {3343} INFO -  at 206.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:16] {3166} INFO - iteration 1631, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:17] {3343} INFO -  at 207.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:17] {3166} INFO - iteration 1632, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:17] {3343} INFO -  at 207.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:17] {3166} INFO - iteration 1633, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:17] {3343} INFO -  at 207.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:17] {3166} INFO - iteration 1634, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:17] {3343} INFO -  at 207.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:17] {3166} INFO - iteration 1635, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:17] {3343} INFO -  at 207.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:17] {3166} INFO - iteration 1636, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:17] {3343} INFO -  at 207.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:17] {3166} INFO - iteration 1637, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:17] {3343} INFO -  at 207.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:17] {3166} INFO - iteration 1638, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:17] {3343} INFO -  at 207.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:17] {3166} INFO - iteration 1639, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:17] {3343} INFO -  at 207.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:17] {3166} INFO - iteration 1640, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:17] {3343} INFO -  at 207.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:17] {3166} INFO - iteration 1641, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:17] {3343} INFO -  at 207.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:17] {3166} INFO - iteration 1642, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:18] {3343} INFO -  at 208.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:18] {3166} INFO - iteration 1643, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:18] {3343} INFO -  at 208.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:18] {3166} INFO - iteration 1644, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:18] {3343} INFO -  at 208.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:18] {3166} INFO - iteration 1645, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:18] {3343} INFO -  at 208.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:18] {3166} INFO - iteration 1646, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:18] {3343} INFO -  at 208.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:18] {3166} INFO - iteration 1647, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:18] {3343} INFO -  at 208.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:18] {3166} INFO - iteration 1648, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:18] {3343} INFO -  at 208.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:18] {3166} INFO - iteration 1649, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:18] {3343} INFO -  at 208.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:18] {3166} INFO - iteration 1650, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:18] {3343} INFO -  at 208.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:18] {3166} INFO - iteration 1651, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:18] {3343} INFO -  at 208.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:18] {3166} INFO - iteration 1652, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:19] {3343} INFO -  at 209.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:19] {3166} INFO - iteration 1653, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:19] {3343} INFO -  at 209.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:19] {3166} INFO - iteration 1654, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:19] {3343} INFO -  at 209.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:19] {3166} INFO - iteration 1655, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:19] {3343} INFO -  at 209.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:19] {3166} INFO - iteration 1656, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:19] {3343} INFO -  at 209.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:19] {3166} INFO - iteration 1657, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:19] {3343} INFO -  at 209.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:19] {3166} INFO - iteration 1658, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:19] {3343} INFO -  at 209.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:19] {3166} INFO - iteration 1659, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:19] {3343} INFO -  at 209.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:19] {3166} INFO - iteration 1660, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:19] {3343} INFO -  at 209.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:19] {3166} INFO - iteration 1661, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:19] {3343} INFO -  at 209.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:19] {3166} INFO - iteration 1662, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:20] {3343} INFO -  at 210.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:20] {3166} INFO - iteration 1663, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:20] {3343} INFO -  at 210.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:20] {3166} INFO - iteration 1664, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:20] {3343} INFO -  at 210.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:20] {3166} INFO - iteration 1665, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:20] {3343} INFO -  at 210.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:20] {3166} INFO - iteration 1666, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:20] {3343} INFO -  at 210.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:20] {3166} INFO - iteration 1667, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:20] {3343} INFO -  at 210.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:20] {3166} INFO - iteration 1668, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:20] {3343} INFO -  at 210.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:20] {3166} INFO - iteration 1669, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:20] {3343} INFO -  at 210.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:20] {3166} INFO - iteration 1670, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:20] {3343} INFO -  at 210.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:20] {3166} INFO - iteration 1671, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:20] {3343} INFO -  at 210.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:20] {3166} INFO - iteration 1672, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:21] {3343} INFO -  at 211.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:21] {3166} INFO - iteration 1673, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:21] {3343} INFO -  at 211.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:21] {3166} INFO - iteration 1674, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:21] {3343} INFO -  at 211.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:21] {3166} INFO - iteration 1675, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:21] {3343} INFO -  at 211.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:21] {3166} INFO - iteration 1676, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:21] {3343} INFO -  at 211.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:21] {3166} INFO - iteration 1677, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:21] {3343} INFO -  at 211.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:21] {3166} INFO - iteration 1678, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:21] {3343} INFO -  at 211.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:21] {3166} INFO - iteration 1679, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:21] {3343} INFO -  at 211.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:21] {3166} INFO - iteration 1680, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:21] {3343} INFO -  at 211.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:21] {3166} INFO - iteration 1681, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:21] {3343} INFO -  at 211.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:21] {3166} INFO - iteration 1682, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:21] {3343} INFO -  at 211.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:21] {3166} INFO - iteration 1683, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:21] {3343} INFO -  at 211.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:21] {3166} INFO - iteration 1684, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:22] {3343} INFO -  at 212.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:22] {3166} INFO - iteration 1685, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:22] {3343} INFO -  at 212.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:22] {3166} INFO - iteration 1686, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:22] {3343} INFO -  at 212.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:22] {3166} INFO - iteration 1687, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:22] {3343} INFO -  at 212.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:22] {3166} INFO - iteration 1688, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:22] {3343} INFO -  at 212.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:22] {3166} INFO - iteration 1689, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:22] {3343} INFO -  at 212.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:22] {3166} INFO - iteration 1690, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:22] {3343} INFO -  at 212.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:22] {3166} INFO - iteration 1691, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:22] {3343} INFO -  at 212.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:22] {3166} INFO - iteration 1692, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:22] {3343} INFO -  at 212.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:22] {3166} INFO - iteration 1693, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:22] {3343} INFO -  at 212.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:22] {3166} INFO - iteration 1694, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:23] {3343} INFO -  at 213.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:23] {3166} INFO - iteration 1695, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:23] {3343} INFO -  at 213.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:23] {3166} INFO - iteration 1696, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:23] {3343} INFO -  at 213.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:23] {3166} INFO - iteration 1697, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:23] {3343} INFO -  at 213.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:23] {3166} INFO - iteration 1698, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:23] {3343} INFO -  at 213.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:23] {3166} INFO - iteration 1699, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:23] {3343} INFO -  at 213.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:23] {3166} INFO - iteration 1700, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:23] {3343} INFO -  at 213.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:23] {3166} INFO - iteration 1701, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:23] {3343} INFO -  at 213.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:23] {3166} INFO - iteration 1702, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:23] {3343} INFO -  at 213.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:23] {3166} INFO - iteration 1703, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:24] {3343} INFO -  at 214.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:24] {3166} INFO - iteration 1704, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:24] {3343} INFO -  at 214.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:24] {3166} INFO - iteration 1705, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:24] {3343} INFO -  at 214.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:24] {3166} INFO - iteration 1706, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:24] {3343} INFO -  at 214.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:24] {3166} INFO - iteration 1707, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:24] {3343} INFO -  at 214.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:24] {3166} INFO - iteration 1708, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:24] {3343} INFO -  at 214.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:24] {3166} INFO - iteration 1709, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:24] {3343} INFO -  at 214.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:24] {3166} INFO - iteration 1710, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:24] {3343} INFO -  at 214.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:24] {3166} INFO - iteration 1711, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:24] {3343} INFO -  at 214.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:24] {3166} INFO - iteration 1712, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:24] {3343} INFO -  at 214.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:24] {3166} INFO - iteration 1713, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:25] {3343} INFO -  at 215.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:25] {3166} INFO - iteration 1714, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:25] {3343} INFO -  at 215.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:25] {3166} INFO - iteration 1715, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:25] {3343} INFO -  at 215.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:25] {3166} INFO - iteration 1716, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:25] {3343} INFO -  at 215.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:25] {3166} INFO - iteration 1717, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:25] {3343} INFO -  at 215.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:25] {3166} INFO - iteration 1718, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:25] {3343} INFO -  at 215.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269

[flaml.automl: 04-23 11:23:25] {3166} INFO - iteration 1719, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:25] {3343} INFO -  at 215.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:25] {3166} INFO - iteration 1720, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:25] {3343} INFO -  at 215.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:25] {3166} INFO - iteration 1721, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:25] {3343} INFO -  at 215.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:25] {3166} INFO - iteration 1722, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:26] {3343} INFO -  at 216.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:26] {3166} INFO - iteration 1723, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:26] {3343} INFO -  at 216.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:26] {3166} INFO - iteration 1724, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:26] {3343} INFO -  at 216.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:26] {3166} INFO - iteration 1725, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:26] {3343} INFO -  at 216.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:26] {3166} INFO - iteration 1726, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:26] {3343} INFO -  at 216.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:26] {3166} INFO - iteration 1727, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:26] {3343} INFO -  at 216.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:26] {3166} INFO - iteration 1728, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:26] {3343} INFO -  at 216.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:26] {3166} INFO - iteration 1729, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:27] {3343} INFO -  at 216.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:27] {3166} INFO - iteration 1730, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:27] {3343} INFO -  at 217.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:27] {3166} INFO - iteration 1731, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:27] {3343} INFO -  at 217.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:27] {3166} INFO - iteration 1732, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:27] {3343} INFO -  at 217.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:27] {3166} INFO - iteration 1733, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:27] {3343} INFO -  at 217.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:27] {3166} INFO - iteration 1734, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:27] {3343} INFO -  at 217.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:27] {3166} INFO - iteration 1735, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:27] {3343} INFO -  at 217.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:27] {3166} INFO - iteration 1736, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:27] {3343} INFO -  at 217.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:27] {3166} INFO - iteration 1737, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:27] {3343} INFO -  at 217.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:27] {3166} INFO - iteration 1738, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:28] {3343} INFO -  at 218.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:28] {3166} INFO - iteration 1739, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:28] {3343} INFO -  at 218.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:28] {3166} INFO - iteration 1740, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:28] {3343} INFO -  at 218.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:28] {3166} INFO - iteration 1741, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:28] {3343} INFO -  at 218.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:28] {3166} INFO - iteration 1742, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:28] {3343} INFO -  at 218.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:28] {3166} INFO - iteration 1743, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:28] {3343} INFO -  at 218.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:28] {3166} INFO - iteration 1744, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:28] {3343} INFO -  at 218.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:28] {3166} INFO - iteration 1745, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:29] {3343} INFO -  at 219.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:29] {3166} INFO - iteration 1746, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:29] {3343} INFO -  at 219.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:29] {3166} INFO - iteration 1747, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:29] {3343} INFO -  at 219.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:29] {3166} INFO - iteration 1748, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:29] {3343} INFO -  at 219.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:29] {3166} INFO - iteration 1749, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:29] {3343} INFO -  at 219.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:29] {3166} INFO - iteration 1750, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:29] {3343} INFO -  at 219.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:29] {3166} INFO - iteration 1751, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:30] {3343} INFO -  at 219.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:30] {3166} INFO - iteration 1752, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:30] {3343} INFO -  at 220.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:30] {3166} INFO - iteration 1753, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:30] {3343} INFO -  at 220.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:30] {3166} INFO - iteration 1754, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:30] {3343} INFO -  at 220.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:30] {3166} INFO - iteration 1755, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:30] {3343} INFO -  at 220.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:30] {3166} INFO - iteration 1756, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:30] {3343} INFO -  at 220.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:30] {3166} INFO - iteration 1757, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:30] {3343} INFO -  at 220.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:30] {3166} INFO - iteration 1758, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:30] {3343} INFO -  at 220.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:30] {3166} INFO - iteration 1759, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:30] {3343} INFO -  at 220.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:30] {3166} INFO - iteration 1760, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:30] {3343} INFO -  at 220.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:30] {3166} INFO - iteration 1761, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:31] {3343} INFO -  at 221.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:31] {3166} INFO - iteration 1762, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:31] {3343} INFO -  at 221.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:31] {3166} INFO - iteration 1763, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:31] {3343} INFO -  at 221.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:31] {3166} INFO - iteration 1764, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:31] {3343} INFO -  at 221.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:31] {3166} INFO - iteration 1765, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:31] {3343} INFO -  at 221.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:31] {3166} INFO - iteration 1766, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:31] {3343} INFO -  at 221.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:31] {3166} INFO - iteration 1767, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:32] {3343} INFO -  at 222.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:32] {3166} INFO - iteration 1768, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:32] {3343} INFO -  at 222.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:32] {3166} INFO - iteration 1769, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:32] {3343} INFO -  at 222.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:32] {3166} INFO - iteration 1770, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:32] {3343} INFO -  at 222.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:32] {3166} INFO - iteration 1771, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:32] {3343} INFO -  at 222.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:32] {3166} INFO - iteration 1772, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:32] {3343} INFO -  at 222.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:32] {3166} INFO - iteration 1773, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:33] {3343} INFO -  at 223.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:33] {3166} INFO - iteration 1774, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:33] {3343} INFO -  at 223.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:33] {3166} INFO - iteration 1775, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:33] {3343} INFO -  at 223.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:33] {3166} INFO - iteration 1776, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:33] {3343} INFO -  at 223.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:33] {3166} INFO - iteration 1777, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:33] {3343} INFO -  at 223.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:33] {3166} INFO - iteration 1778, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:33] {3343} INFO -  at 223.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:33] {3166} INFO - iteration 1779, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:34] {3343} INFO -  at 224.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:34] {3166} INFO - iteration 1780, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:34] {3343} INFO -  at 224.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:34] {3166} INFO - iteration 1781, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:34] {3343} INFO -  at 224.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:34] {3166} INFO - iteration 1782, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:34] {3343} INFO -  at 224.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:34] {3166} INFO - iteration 1783, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:34] {3343} INFO -  at 224.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269

[flaml.automl: 04-23 11:23:34] {3166} INFO - iteration 1784, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:35] {3343} INFO -  at 225.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:35] {3166} INFO - iteration 1785, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:35] {3343} INFO -  at 225.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:35] {3166} INFO - iteration 1786, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:35] {3343} INFO -  at 225.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:35] {3166} INFO - iteration 1787, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:35] {3343} INFO -  at 225.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:35] {3166} INFO - iteration 1788, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:35] {3343} INFO -  at 225.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:35] {3166} INFO - iteration 1789, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:35] {3343} INFO -  at 225.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:35] {3166} INFO - iteration 1790, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:36] {3343} INFO -  at 226.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:36] {3166} INFO - iteration 1791, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:36] {3343} INFO -  at 226.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:36] {3166} INFO - iteration 1792, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:36] {3343} INFO -  at 226.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:36] {3166} INFO - iteration 1793, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:36] {3343} INFO -  at 226.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:36] {3166} INFO - iteration 1794, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:36] {3343} INFO -  at 226.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:36] {3166} INFO - iteration 1795, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:37] {3343} INFO -  at 227.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:37] {3166} INFO - iteration 1796, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:37] {3343} INFO -  at 227.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:37] {3166} INFO - iteration 1797, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:37] {3343} INFO -  at 227.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:37] {3166} INFO - iteration 1798, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:38] {3343} INFO -  at 228.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:38] {3166} INFO - iteration 1799, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:38] {3343} INFO -  at 228.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:38] {3166} INFO - iteration 1800, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:38] {3343} INFO -  at 228.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:38] {3166} INFO - iteration 1801, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:38] {3343} INFO -  at 228.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:38] {3166} INFO - iteration 1802, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:38] {3343} INFO -  at 228.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:38] {3166} INFO - iteration 1803, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:38] {3343} INFO -  at 228.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:38] {3166} INFO - iteration 1804, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:38] {3343} INFO -  at 228.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:38] {3166} INFO - iteration 1805, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:39] {3343} INFO -  at 229.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:39] {3166} INFO - iteration 1806, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:39] {3343} INFO -  at 229.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:39] {3166} INFO - iteration 1807, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:39] {3343} INFO -  at 229.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:39] {3166} INFO - iteration 1808, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:39] {3343} INFO -  at 229.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:39] {3166} INFO - iteration 1809, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:39] {3343} INFO -  at 229.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:39] {3166} INFO - iteration 1810, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:39] {3343} INFO -  at 229.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:39] {3166} INFO - iteration 1811, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:39] {3343} INFO -  at 229.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:39] {3166} INFO - iteration 1812, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:40] {3343} INFO -  at 229.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:40] {3166} INFO - iteration 1813, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:40] {3343} INFO -  at 230.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:40] {3166} INFO - iteration 1814, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:40] {3343} INFO -  at 230.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:40] {3166} INFO - iteration 1815, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:40] {3343} INFO -  at 230.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:40] {3166} INFO - iteration 1816, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:40] {3343} INFO -  at 230.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:40] {3166} INFO - iteration 1817, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:40] {3343} INFO -  at 230.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:40] {3166} INFO - iteration 1818, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:41] {3343} INFO -  at 231.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:41] {3166} INFO - iteration 1819, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:41] {3343} INFO -  at 231.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:41] {3166} INFO - iteration 1820, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:41] {3343} INFO -  at 231.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:41] {3166} INFO - iteration 1821, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:41] {3343} INFO -  at 231.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:41] {3166} INFO - iteration 1822, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:41] {3343} INFO -  at 231.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:41] {3166} INFO - iteration 1823, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:42] {3343} INFO -  at 232.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:42] {3166} INFO - iteration 1824, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:42] {3343} INFO -  at 232.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:42] {3166} INFO - iteration 1825, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:42] {3343} INFO -  at 232.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:42] {3166} INFO - iteration 1826, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:42] {3343} INFO -  at 232.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:42] {3166} INFO - iteration 1827, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:42] {3343} INFO -  at 232.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:42] {3166} INFO - iteration 1828, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:43] {3343} INFO -  at 233.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:43] {3166} INFO - iteration 1829, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:43] {3343} INFO -  at 233.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:43] {3166} INFO - iteration 1830, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:43] {3343} INFO -  at 233.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:43] {3166} INFO - iteration 1831, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:43] {3343} INFO -  at 233.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:43] {3166} INFO - iteration 1832, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:43] {3343} INFO -  at 233.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:43] {3166} INFO - iteration 1833, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:43] {3343} INFO -  at 233.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:43] {3166} INFO - iteration 1834, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:43] {3343} INFO -  at 233.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:43] {3166} INFO - iteration 1835, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:43] {3343} INFO -  at 233.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269

[flaml.automl: 04-23 11:23:43] {3166} INFO - iteration 1836, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:43] {3343} INFO -  at 233.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:43] {3166} INFO - iteration 1837, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:44] {3343} INFO -  at 234.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:44] {3166} INFO - iteration 1838, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:44] {3343} INFO -  at 234.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:44] {3166} INFO - iteration 1839, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:44] {3343} INFO -  at 234.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:44] {3166} INFO - iteration 1840, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:44] {3343} INFO -  at 234.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:44] {3166} INFO - iteration 1841, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:44] {3343} INFO -  at 234.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:44] {3166} INFO - iteration 1842, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:44] {3343} INFO -  at 234.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:44] {3166} INFO - iteration 1843, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:44] {3343} INFO -  at 234.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:44] {3166} INFO - iteration 1844, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:44] {3343} INFO -  at 234.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:44] {3166} INFO - iteration 1845, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:45] {3343} INFO -  at 235.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:45] {3166} INFO - iteration 1846, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:45] {3343} INFO -  at 235.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:45] {3166} INFO - iteration 1847, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:45] {3343} INFO -  at 235.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:45] {3166} INFO - iteration 1848, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:45] {3343} INFO -  at 235.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:45] {3166} INFO - iteration 1849, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:45] {3343} INFO -  at 235.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:45] {3166} INFO - iteration 1850, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:45] {3343} INFO -  at 235.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:45] {3166} INFO - iteration 1851, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:45] {3343} INFO -  at 235.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:45] {3166} INFO - iteration 1852, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:46] {3343} INFO -  at 235.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:46] {3166} INFO - iteration 1853, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:46] {3343} INFO -  at 236.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:46] {3166} INFO - iteration 1854, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:46] {3343} INFO -  at 236.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:46] {3166} INFO - iteration 1855, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:46] {3343} INFO -  at 236.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:46] {3166} INFO - iteration 1856, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:46] {3343} INFO -  at 236.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:46] {3166} INFO - iteration 1857, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:46] {3343} INFO -  at 236.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:46] {3166} INFO - iteration 1858, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:46] {3343} INFO -  at 236.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:46] {3166} INFO - iteration 1859, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:47] {3343} INFO -  at 237.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:47] {3166} INFO - iteration 1860, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:47] {3343} INFO -  at 237.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:47] {3166} INFO - iteration 1861, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:47] {3343} INFO -  at 237.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:47] {3166} INFO - iteration 1862, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:47] {3343} INFO -  at 237.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:47] {3166} INFO - iteration 1863, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:47] {3343} INFO -  at 237.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:47] {3166} INFO - iteration 1864, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:47] {3343} INFO -  at 237.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:47] {3166} INFO - iteration 1865, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:48] {3343} INFO -  at 238.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:48] {3166} INFO - iteration 1866, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:48] {3343} INFO -  at 238.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:48] {3166} INFO - iteration 1867, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:48] {3343} INFO -  at 238.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:48] {3166} INFO - iteration 1868, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:48] {3343} INFO -  at 238.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:48] {3166} INFO - iteration 1869, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:48] {3343} INFO -  at 238.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:48] {3166} INFO - iteration 1870, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:48] {3343} INFO -  at 238.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:49] {3166} INFO - iteration 1871, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:49] {3343} INFO -  at 239.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:49] {3166} INFO - iteration 1872, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:49] {3343} INFO -  at 239.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:49] {3166} INFO - iteration 1873, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:49] {3343} INFO -  at 239.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:49] {3166} INFO - iteration 1874, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:49] {3343} INFO -  at 239.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:49] {3166} INFO - iteration 1875, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:49] {3343} INFO -  at 239.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:49] {3166} INFO - iteration 1876, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:49] {3343} INFO -  at 239.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:50] {3166} INFO - iteration 1877, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:50] {3343} INFO -  at 240.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:50] {3166} INFO - iteration 1878, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:50] {3343} INFO -  at 240.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:50] {3166} INFO - iteration 1879, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:50] {3343} INFO -  at 240.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:50] {3166} INFO - iteration 1880, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:50] {3343} INFO -  at 240.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:50] {3166} INFO - iteration 1881, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:50] {3343} INFO -  at 240.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:50] {3166} INFO - iteration 1882, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:50] {3343} INFO -  at 240.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:50] {3166} INFO - iteration 1883, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:50] {3343} INFO -  at 240.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:50] {3166} INFO - iteration 1884, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:51] {3343} INFO -  at 241.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:51] {3166} INFO - iteration 1885, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:51] {3343} INFO -  at 241.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:51] {3166} INFO - iteration 1886, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:51] {3343} INFO -  at 241.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:51] {3166} INFO - iteration 1887, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:51] {3343} INFO -  at 241.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:51] {3166} INFO - iteration 1888, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:51] {3343} INFO -  at 241.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:51] {3166} INFO - iteration 1889, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:51] {3343} INFO -  at 241.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:51] {3166} INFO - iteration 1890, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:51] {3343} INFO -  at 241.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:51] {3166} INFO - iteration 1891, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:51] {3343} INFO -  at 241.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:51] {3166} INFO - iteration 1892, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:52] {3343} INFO -  at 242.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:52] {3166} INFO - iteration 1893, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:52] {3343} INFO -  at 242.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:52] {3166} INFO - iteration 1894, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:52] {3343} INFO -  at 242.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:52] {3166} INFO - iteration 1895, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:52] {3343} INFO -  at 242.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:52] {3166} INFO - iteration 1896, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:52] {3343} INFO -  at 242.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:52] {3166} INFO - iteration 1897, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:52] {3343} INFO -  at 242.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:52] {3166} INFO - iteration 1898, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:53] {3343} INFO -  at 242.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:53] {3166} INFO - iteration 1899, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:53] {3343} INFO -  at 243.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:53] {3166} INFO - iteration 1900, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:53] {3343} INFO -  at 243.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:53] {3166} INFO - iteration 1901, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:53] {3343} INFO -  at 243.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:53] {3166} INFO - iteration 1902, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:53] {3343} INFO -  at 243.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:53] {3166} INFO - iteration 1903, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:53] {3343} INFO -  at 243.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:53] {3166} INFO - iteration 1904, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:53] {3343} INFO -  at 243.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:53] {3166} INFO - iteration 1905, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:53] {3343} INFO -  at 243.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:53] {3166} INFO - iteration 1906, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:54] {3343} INFO -  at 244.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:54] {3166} INFO - iteration 1907, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:54] {3343} INFO -  at 244.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:54] {3166} INFO - iteration 1908, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:54] {3343} INFO -  at 244.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:54] {3166} INFO - iteration 1909, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:54] {3343} INFO -  at 244.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:54] {3166} INFO - iteration 1910, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:54] {3343} INFO -  at 244.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:54] {3166} INFO - iteration 1911, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:54] {3343} INFO -  at 244.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:54] {3166} INFO - iteration 1912, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:54] {3343} INFO -  at 244.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:54] {3166} INFO - iteration 1913, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:55] {3343} INFO -  at 245.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:55] {3166} INFO - iteration 1914, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:55] {3343} INFO -  at 245.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:55] {3166} INFO - iteration 1915, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:55] {3343} INFO -  at 245.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:55] {3166} INFO - iteration 1916, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:55] {3343} INFO -  at 245.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:55] {3166} INFO - iteration 1917, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:55] {3343} INFO -  at 245.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:55] {3166} INFO - iteration 1918, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:55] {3343} INFO -  at 245.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:55] {3166} INFO - iteration 1919, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:55] {3343} INFO -  at 245.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:55] {3166} INFO - iteration 1920, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:55] {3343} INFO -  at 245.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:55] {3166} INFO - iteration 1921, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:56] {3343} INFO -  at 246.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:56] {3166} INFO - iteration 1922, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:56] {3343} INFO -  at 246.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:56] {3166} INFO - iteration 1923, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:56] {3343} INFO -  at 246.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:56] {3166} INFO - iteration 1924, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:56] {3343} INFO -  at 246.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:56] {3166} INFO - iteration 1925, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:56] {3343} INFO -  at 246.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:56] {3166} INFO - iteration 1926, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:56] {3343} INFO -  at 246.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:56] {3166} INFO - iteration 1927, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:56] {3343} INFO -  at 246.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:56] {3166} INFO - iteration 1928, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:57] {3343} INFO -  at 246.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:57] {3166} INFO - iteration 1929, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:57] {3343} INFO -  at 247.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:57] {3166} INFO - iteration 1930, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:57] {3343} INFO -  at 247.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:57] {3166} INFO - iteration 1931, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:57] {3343} INFO -  at 247.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:57] {3166} INFO - iteration 1932, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:57] {3343} INFO -  at 247.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:57] {3166} INFO - iteration 1933, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:57] {3343} INFO -  at 247.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:57] {3166} INFO - iteration 1934, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:57] {3343} INFO -  at 247.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:57] {3166} INFO - iteration 1935, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:57] {3343} INFO -  at 247.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:57] {3166} INFO - iteration 1936, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:58] {3343} INFO -  at 248.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:58] {3166} INFO - iteration 1937, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:58] {3343} INFO -  at 248.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:58] {3166} INFO - iteration 1938, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:58] {3343} INFO -  at 248.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:58] {3166} INFO - iteration 1939, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:23:58] {3343} INFO -  at 248.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:58] {3166} INFO - iteration 1940, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:58] {3343} INFO -  at 248.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:58] {3166} INFO - iteration 1941, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:58] {3343} INFO -  at 248.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:58] {3166} INFO - iteration 1942, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:58] {3343} INFO -  at 248.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:58] {3166} INFO - iteration 1943, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:58] {3343} INFO -  at 248.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:58] {3166} INFO - iteration 1944, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:59] {3343} INFO -  at 249.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:59] {3166} INFO - iteration 1945, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:59] {3343} INFO -  at 249.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:59] {3166} INFO - iteration 1946, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:59] {3343} INFO -  at 249.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:59] {3166} INFO - iteration 1947, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:59] {3343} INFO -  at 249.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:59] {3166} INFO - iteration 1948, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:59] {3343} INFO -  at 249.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:59] {3166} INFO - iteration 1949, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:59] {3343} INFO -  at 249.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:59] {3166} INFO - iteration 1950, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:59] {3343} INFO -  at 249.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:59] {3166} INFO - iteration 1951, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:23:59] {3343} INFO -  at 249.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:23:59] {3166} INFO - iteration 1952, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:00] {3343} INFO -  at 250.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:00] {3166} INFO - iteration 1953, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:00] {3343} INFO -  at 250.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:00] {3166} INFO - iteration 1954, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:00] {3343} INFO -  at 250.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:00] {3166} INFO - iteration 1955, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:00] {3343} INFO -  at 250.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:00] {3166} INFO - iteration 1956, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:00] {3343} INFO -  at 250.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:00] {3166} INFO - iteration 1957, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:00] {3343} INFO -  at 250.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:00] {3166} INFO - iteration 1958, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:00] {3343} INFO -  at 250.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:00] {3166} INFO - iteration 1959, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:01] {3343} INFO -  at 251.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:01] {3166} INFO - iteration 1960, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:01] {3343} INFO -  at 251.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:01] {3166} INFO - iteration 1961, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:01] {3343} INFO -  at 251.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:01] {3166} INFO - iteration 1962, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:01] {3343} INFO -  at 251.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:01] {3166} INFO - iteration 1963, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:01] {3343} INFO -  at 251.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:01] {3166} INFO - iteration 1964, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:01] {3343} INFO -  at 251.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:01] {3166} INFO - iteration 1965, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:01] {3343} INFO -  at 251.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:01] {3166} INFO - iteration 1966, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:02] {3343} INFO -  at 252.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:02] {3166} INFO - iteration 1967, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:02] {3343} INFO -  at 252.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:02] {3166} INFO - iteration 1968, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:02] {3343} INFO -  at 252.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:02] {3166} INFO - iteration 1969, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:02] {3343} INFO -  at 252.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:02] {3166} INFO - iteration 1970, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:02] {3343} INFO -  at 252.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:02] {3166} INFO - iteration 1971, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:02] {3343} INFO -  at 252.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:02] {3166} INFO - iteration 1972, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:02] {3343} INFO -  at 252.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:02] {3166} INFO - iteration 1973, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:02] {3343} INFO -  at 252.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:02] {3166} INFO - iteration 1974, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:03] {3343} INFO -  at 253.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:03] {3166} INFO - iteration 1975, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:03] {3343} INFO -  at 253.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:03] {3166} INFO - iteration 1976, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:03] {3343} INFO -  at 253.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:03] {3166} INFO - iteration 1977, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:03] {3343} INFO -  at 253.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:03] {3166} INFO - iteration 1978, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:03] {3343} INFO -  at 253.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:03] {3166} INFO - iteration 1979, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:03] {3343} INFO -  at 253.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:03] {3166} INFO - iteration 1980, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:03] {3343} INFO -  at 253.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:03] {3166} INFO - iteration 1981, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:04] {3343} INFO -  at 254.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:04] {3166} INFO - iteration 1982, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:04] {3343} INFO -  at 254.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:04] {3166} INFO - iteration 1983, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:04] {3343} INFO -  at 254.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:04] {3166} INFO - iteration 1984, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:04] {3343} INFO -  at 254.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:04] {3166} INFO - iteration 1985, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:04] {3343} INFO -  at 254.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:04] {3166} INFO - iteration 1986, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:04] {3343} INFO -  at 254.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:04] {3166} INFO - iteration 1987, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:04] {3343} INFO -  at 254.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:04] {3166} INFO - iteration 1988, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:04] {3343} INFO -  at 254.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:04] {3166} INFO - iteration 1989, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:05] {3343} INFO -  at 255.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:05] {3166} INFO - iteration 1990, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:05] {3343} INFO -  at 255.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:05] {3166} INFO - iteration 1991, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:05] {3343} INFO -  at 255.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:05] {3166} INFO - iteration 1992, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:05] {3343} INFO -  at 255.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:05] {3166} INFO - iteration 1993, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:05] {3343} INFO -  at 255.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:05] {3166} INFO - iteration 1994, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:06] {3343} INFO -  at 255.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:06] {3166} INFO - iteration 1995, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:06] {3343} INFO -  at 256.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:06] {3166} INFO - iteration 1996, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:06] {3343} INFO -  at 256.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:06] {3166} INFO - iteration 1997, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:06] {3343} INFO -  at 256.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:06] {3166} INFO - iteration 1998, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:06] {3343} INFO -  at 256.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:06] {3166} INFO - iteration 1999, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:06] {3343} INFO -  at 256.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:06] {3166} INFO - iteration 2000, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:06] {3343} INFO -  at 256.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:06] {3166} INFO - iteration 2001, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:06] {3343} INFO -  at 256.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:06] {3166} INFO - iteration 2002, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:07] {3343} INFO -  at 257.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:07] {3166} INFO - iteration 2003, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:07] {3343} INFO -  at 257.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:07] {3166} INFO - iteration 2004, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:07] {3343} INFO -  at 257.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:07] {3166} INFO - iteration 2005, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:07] {3343} INFO -  at 257.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:07] {3166} INFO - iteration 2006, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:07] {3343} INFO -  at 257.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:07] {3166} INFO - iteration 2007, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:07] {3343} INFO -  at 257.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:07] {3166} INFO - iteration 2008, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:07] {3343} INFO -  at 257.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:07] {3166} INFO - iteration 2009, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:08] {3343} INFO -  at 258.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:08] {3166} INFO - iteration 2010, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:08] {3343} INFO -  at 258.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:08] {3166} INFO - iteration 2011, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:08] {3343} INFO -  at 258.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:08] {3166} INFO - iteration 2012, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:08] {3343} INFO -  at 258.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:08] {3166} INFO - iteration 2013, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:08] {3343} INFO -  at 258.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:08] {3166} INFO - iteration 2014, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:08] {3343} INFO -  at 258.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:08] {3166} INFO - iteration 2015, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:08] {3343} INFO -  at 258.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:08] {3166} INFO - iteration 2016, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:09] {3343} INFO -  at 259.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:09] {3166} INFO - iteration 2017, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:09] {3343} INFO -  at 259.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:09] {3166} INFO - iteration 2018, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:09] {3343} INFO -  at 259.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:09] {3166} INFO - iteration 2019, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:09] {3343} INFO -  at 259.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:09] {3166} INFO - iteration 2020, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:09] {3343} INFO -  at 259.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:09] {3166} INFO - iteration 2021, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:09] {3343} INFO -  at 259.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:09] {3166} INFO - iteration 2022, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:10] {3343} INFO -  at 260.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:10] {3166} INFO - iteration 2023, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:10] {3343} INFO -  at 260.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:10] {3166} INFO - iteration 2024, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:10] {3343} INFO -  at 260.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:10] {3166} INFO - iteration 2025, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:10] {3343} INFO -  at 260.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:10] {3166} INFO - iteration 2026, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:10] {3343} INFO -  at 260.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:10] {3166} INFO - iteration 2027, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:10] {3343} INFO -  at 260.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:10] {3166} INFO - iteration 2028, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:10] {3343} INFO -  at 260.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:10] {3166} INFO - iteration 2029, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:11] {3343} INFO -  at 260.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:11] {3166} INFO - iteration 2030, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:11] {3343} INFO -  at 261.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:11] {3166} INFO - iteration 2031, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:11] {3343} INFO -  at 261.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:11] {3166} INFO - iteration 2032, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:11] {3343} INFO -  at 261.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:11] {3166} INFO - iteration 2033, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:11] {3343} INFO -  at 261.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:11] {3166} INFO - iteration 2034, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:11] {3343} INFO -  at 261.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:11] {3166} INFO - iteration 2035, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:11] {3343} INFO -  at 261.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:11] {3166} INFO - iteration 2036, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:11] {3343} INFO -  at 261.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:11] {3166} INFO - iteration 2037, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:11] {3343} INFO -  at 261.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:11] {3166} INFO - iteration 2038, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:12] {3343} INFO -  at 262.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:12] {3166} INFO - iteration 2039, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:12] {3343} INFO -  at 262.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:12] {3166} INFO - iteration 2040, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:12] {3343} INFO -  at 262.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:12] {3166} INFO - iteration 2041, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:12] {3343} INFO -  at 262.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:12] {3166} INFO - iteration 2042, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:12] {3343} INFO -  at 262.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:12] {3166} INFO - iteration 2043, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:12] {3343} INFO -  at 262.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:12] {3166} INFO - iteration 2044, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:12] {3343} INFO -  at 262.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:12] {3166} INFO - iteration 2045, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:13] {3343} INFO -  at 263.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:13] {3166} INFO - iteration 2046, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:13] {3343} INFO -  at 263.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:13] {3166} INFO - iteration 2047, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:13] {3343} INFO -  at 263.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:13] {3166} INFO - iteration 2048, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:13] {3343} INFO -  at 263.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:13] {3166} INFO - iteration 2049, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:13] {3343} INFO -  at 263.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:13] {3166} INFO - iteration 2050, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:13] {3343} INFO -  at 263.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:13] {3166} INFO - iteration 2051, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:14] {3343} INFO -  at 263.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:14] {3166} INFO - iteration 2052, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:14] {3343} INFO -  at 264.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:14] {3166} INFO - iteration 2053, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:14] {3343} INFO -  at 264.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:14] {3166} INFO - iteration 2054, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:14] {3343} INFO -  at 264.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:14] {3166} INFO - iteration 2055, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:14] {3343} INFO -  at 264.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:14] {3166} INFO - iteration 2056, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:14] {3343} INFO -  at 264.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:14] {3166} INFO - iteration 2057, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:14] {3343} INFO -  at 264.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:14] {3166} INFO - iteration 2058, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:15] {3343} INFO -  at 264.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:15] {3166} INFO - iteration 2059, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:15] {3343} INFO -  at 265.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:15] {3166} INFO - iteration 2060, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:15] {3343} INFO -  at 265.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:15] {3166} INFO - iteration 2061, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:15] {3343} INFO -  at 265.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:15] {3166} INFO - iteration 2062, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:15] {3343} INFO -  at 265.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:15] {3166} INFO - iteration 2063, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:15] {3343} INFO -  at 265.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:15] {3166} INFO - iteration 2064, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:15] {3343} INFO -  at 265.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:15] {3166} INFO - iteration 2065, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:16] {3343} INFO -  at 266.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:16] {3166} INFO - iteration 2066, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:16] {3343} INFO -  at 266.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:16] {3166} INFO - iteration 2067, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:16] {3343} INFO -  at 266.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:16] {3166} INFO - iteration 2068, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:16] {3343} INFO -  at 266.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:16] {3166} INFO - iteration 2069, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:16] {3343} INFO -  at 266.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:16] {3166} INFO - iteration 2070, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:16] {3343} INFO -  at 266.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:16] {3166} INFO - iteration 2071, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:16] {3343} INFO -  at 266.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:16] {3166} INFO - iteration 2072, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:17] {3343} INFO -  at 266.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:17] {3166} INFO - iteration 2073, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:17] {3343} INFO -  at 267.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:17] {3166} INFO - iteration 2074, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:17] {3343} INFO -  at 267.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:17] {3166} INFO - iteration 2075, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:17] {3343} INFO -  at 267.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:17] {3166} INFO - iteration 2076, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:17] {3343} INFO -  at 267.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:17] {3166} INFO - iteration 2077, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:17] {3343} INFO -  at 267.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:17] {3166} INFO - iteration 2078, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:17] {3343} INFO -  at 267.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:17] {3166} INFO - iteration 2079, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:18] {3343} INFO -  at 268.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:18] {3166} INFO - iteration 2080, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:18] {3343} INFO -  at 268.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:18] {3166} INFO - iteration 2081, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:18] {3343} INFO -  at 268.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:18] {3166} INFO - iteration 2082, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:18] {3343} INFO -  at 268.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:18] {3166} INFO - iteration 2083, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:18] {3343} INFO -  at 268.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:18] {3166} INFO - iteration 2084, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:18] {3343} INFO -  at 268.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:18] {3166} INFO - iteration 2085, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:18] {3343} INFO -  at 268.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:18] {3166} INFO - iteration 2086, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:19] {3343} INFO -  at 268.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:19] {3166} INFO - iteration 2087, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:19] {3343} INFO -  at 269.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:19] {3166} INFO - iteration 2088, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:19] {3343} INFO -  at 269.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:19] {3166} INFO - iteration 2089, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:19] {3343} INFO -  at 269.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:19] {3166} INFO - iteration 2090, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:19] {3343} INFO -  at 269.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:19] {3166} INFO - iteration 2091, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:19] {3343} INFO -  at 269.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:19] {3166} INFO - iteration 2092, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:19] {3343} INFO -  at 269.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:19] {3166} INFO - iteration 2093, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:20] {3343} INFO -  at 270.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:20] {3166} INFO - iteration 2094, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:20] {3343} INFO -  at 270.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:20] {3166} INFO - iteration 2095, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:20] {3343} INFO -  at 270.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:20] {3166} INFO - iteration 2096, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:20] {3343} INFO -  at 270.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:20] {3166} INFO - iteration 2097, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:20] {3343} INFO -  at 270.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:20] {3166} INFO - iteration 2098, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:20] {3343} INFO -  at 270.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:20] {3166} INFO - iteration 2099, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:20] {3343} INFO -  at 270.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:20] {3166} INFO - iteration 2100, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:21] {3343} INFO -  at 271.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:21] {3166} INFO - iteration 2101, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:21] {3343} INFO -  at 271.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:21] {3166} INFO - iteration 2102, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:21] {3343} INFO -  at 271.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:21] {3166} INFO - iteration 2103, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:21] {3343} INFO -  at 271.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:21] {3166} INFO - iteration 2104, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:21] {3343} INFO -  at 271.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:21] {3166} INFO - iteration 2105, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:21] {3343} INFO -  at 271.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:21] {3166} INFO - iteration 2106, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:21] {3343} INFO -  at 271.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:21] {3166} INFO - iteration 2107, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:22] {3343} INFO -  at 272.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:22] {3166} INFO - iteration 2108, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:22] {3343} INFO -  at 272.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:22] {3166} INFO - iteration 2109, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:22] {3343} INFO -  at 272.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:22] {3166} INFO - iteration 2110, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:22] {3343} INFO -  at 272.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:22] {3166} INFO - iteration 2111, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:22] {3343} INFO -  at 272.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:22] {3166} INFO - iteration 2112, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:22] {3343} INFO -  at 272.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:22] {3166} INFO - iteration 2113, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:23] {3343} INFO -  at 273.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:23] {3166} INFO - iteration 2114, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:23] {3343} INFO -  at 273.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:23] {3166} INFO - iteration 2115, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:23] {3343} INFO -  at 273.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:23] {3166} INFO - iteration 2116, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:23] {3343} INFO -  at 273.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:23] {3166} INFO - iteration 2117, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:23] {3343} INFO -  at 273.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:23] {3166} INFO - iteration 2118, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:23] {3343} INFO -  at 273.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:23] {3166} INFO - iteration 2119, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:23] {3343} INFO -  at 273.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:23] {3166} INFO - iteration 2120, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:24] {3343} INFO -  at 274.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:24] {3166} INFO - iteration 2121, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:24] {3343} INFO -  at 274.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:24] {3166} INFO - iteration 2122, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:24] {3343} INFO -  at 274.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:24] {3166} INFO - iteration 2123, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:24] {3343} INFO -  at 274.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:24] {3166} INFO - iteration 2124, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:24] {3343} INFO -  at 274.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:24] {3166} INFO - iteration 2125, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:24] {3343} INFO -  at 274.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:24] {3166} INFO - iteration 2126, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:24] {3343} INFO -  at 274.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:24] {3166} INFO - iteration 2127, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:25] {3343} INFO -  at 275.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:25] {3166} INFO - iteration 2128, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:25] {3343} INFO -  at 275.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:25] {3166} INFO - iteration 2129, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:25] {3343} INFO -  at 275.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:25] {3166} INFO - iteration 2130, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:25] {3343} INFO -  at 275.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:25] {3166} INFO - iteration 2131, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:25] {3343} INFO -  at 275.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:25] {3166} INFO - iteration 2132, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:25] {3343} INFO -  at 275.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:25] {3166} INFO - iteration 2133, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:25] {3343} INFO -  at 275.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:25] {3166} INFO - iteration 2134, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:26] {3343} INFO -  at 276.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:26] {3166} INFO - iteration 2135, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:26] {3343} INFO -  at 276.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:26] {3166} INFO - iteration 2136, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:26] {3343} INFO -  at 276.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:26] {3166} INFO - iteration 2137, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:26] {3343} INFO -  at 276.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:26] {3166} INFO - iteration 2138, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:26] {3343} INFO -  at 276.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:26] {3166} INFO - iteration 2139, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:26] {3343} INFO -  at 276.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:26] {3166} INFO - iteration 2140, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:26] {3343} INFO -  at 276.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:26] {3166} INFO - iteration 2141, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:27] {3343} INFO -  at 277.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:27] {3166} INFO - iteration 2142, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:27] {3343} INFO -  at 277.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:27] {3166} INFO - iteration 2143, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:27] {3343} INFO -  at 277.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:27] {3166} INFO - iteration 2144, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:27] {3343} INFO -  at 277.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:27] {3166} INFO - iteration 2145, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:27] {3343} INFO -  at 277.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:27] {3166} INFO - iteration 2146, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:27] {3343} INFO -  at 277.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:27] {3166} INFO - iteration 2147, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:27] {3343} INFO -  at 277.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:27] {3166} INFO - iteration 2148, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:27] {3343} INFO -  at 277.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:27] {3166} INFO - iteration 2149, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:28] {3343} INFO -  at 278.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:28] {3166} INFO - iteration 2150, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:28] {3343} INFO -  at 278.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:28] {3166} INFO - iteration 2151, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:28] {3343} INFO -  at 278.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:28] {3166} INFO - iteration 2152, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:28] {3343} INFO -  at 278.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:28] {3166} INFO - iteration 2153, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:28] {3343} INFO -  at 278.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:28] {3166} INFO - iteration 2154, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:28] {3343} INFO -  at 278.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:28] {3166} INFO - iteration 2155, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:28] {3343} INFO -  at 278.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:28] {3166} INFO - iteration 2156, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:29] {3343} INFO -  at 279.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:29] {3166} INFO - iteration 2157, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:29] {3343} INFO -  at 279.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:29] {3166} INFO - iteration 2158, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:29] {3343} INFO -  at 279.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:29] {3166} INFO - iteration 2159, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:29] {3343} INFO -  at 279.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:29] {3166} INFO - iteration 2160, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:29] {3343} INFO -  at 279.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:29] {3166} INFO - iteration 2161, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:29] {3343} INFO -  at 279.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:29] {3166} INFO - iteration 2162, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:29] {3343} INFO -  at 279.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:29] {3166} INFO - iteration 2163, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:29] {3343} INFO -  at 279.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:29] {3166} INFO - iteration 2164, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:30] {3343} INFO -  at 280.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:30] {3166} INFO - iteration 2165, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:30] {3343} INFO -  at 280.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:30] {3166} INFO - iteration 2166, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:30] {3343} INFO -  at 280.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:30] {3166} INFO - iteration 2167, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:30] {3343} INFO -  at 280.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:30] {3166} INFO - iteration 2168, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:30] {3343} INFO -  at 280.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:30] {3166} INFO - iteration 2169, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:30] {3343} INFO -  at 280.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:30] {3166} INFO - iteration 2170, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:30] {3343} INFO -  at 280.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:30] {3166} INFO - iteration 2171, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:31] {3343} INFO -  at 281.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:31] {3166} INFO - iteration 2172, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:31] {3343} INFO -  at 281.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:31] {3166} INFO - iteration 2173, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:31] {3343} INFO -  at 281.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:31] {3166} INFO - iteration 2174, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:31] {3343} INFO -  at 281.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:31] {3166} INFO - iteration 2175, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:31] {3343} INFO -  at 281.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:31] {3166} INFO - iteration 2176, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:31] {3343} INFO -  at 281.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:31] {3166} INFO - iteration 2177, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:31] {3343} INFO -  at 281.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:31] {3166} INFO - iteration 2178, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:31] {3343} INFO -  at 281.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:31] {3166} INFO - iteration 2179, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:31] {3343} INFO -  at 281.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:31] {3166} INFO - iteration 2180, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:32] {3343} INFO -  at 282.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:32] {3166} INFO - iteration 2181, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:32] {3343} INFO -  at 282.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:32] {3166} INFO - iteration 2182, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:32] {3343} INFO -  at 282.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:32] {3166} INFO - iteration 2183, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:32] {3343} INFO -  at 282.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:32] {3166} INFO - iteration 2184, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:32] {3343} INFO -  at 282.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:32] {3166} INFO - iteration 2185, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:32] {3343} INFO -  at 282.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:32] {3166} INFO - iteration 2186, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:32] {3343} INFO -  at 282.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:32] {3166} INFO - iteration 2187, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:33] {3343} INFO -  at 283.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:33] {3166} INFO - iteration 2188, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:33] {3343} INFO -  at 283.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:33] {3166} INFO - iteration 2189, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:33] {3343} INFO -  at 283.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:33] {3166} INFO - iteration 2190, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:33] {3343} INFO -  at 283.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:33] {3166} INFO - iteration 2191, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:33] {3343} INFO -  at 283.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:33] {3166} INFO - iteration 2192, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:33] {3343} INFO -  at 283.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:33] {3166} INFO - iteration 2193, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:33] {3343} INFO -  at 283.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:33] {3166} INFO - iteration 2194, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:33] {3343} INFO -  at 283.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:33] {3166} INFO - iteration 2195, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:33] {3343} INFO -  at 283.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:33] {3166} INFO - iteration 2196, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:33] {3343} INFO -  at 283.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:33] {3166} INFO - iteration 2197, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:34] {3343} INFO -  at 283.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:34] {3166} INFO - iteration 2198, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:34] {3343} INFO -  at 284.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:34] {3166} INFO - iteration 2199, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:34] {3343} INFO -  at 284.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:34] {3166} INFO - iteration 2200, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:34] {3343} INFO -  at 284.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:34] {3166} INFO - iteration 2201, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:34] {3343} INFO -  at 284.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:34] {3166} INFO - iteration 2202, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:34] {3343} INFO -  at 284.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:34] {3166} INFO - iteration 2203, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:34] {3343} INFO -  at 284.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:34] {3166} INFO - iteration 2204, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:34] {3343} INFO -  at 284.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:34] {3166} INFO - iteration 2205, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:34] {3343} INFO -  at 284.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:34] {3166} INFO - iteration 2206, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:34] {3343} INFO -  at 284.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:34] {3166} INFO - iteration 2207, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:34] {3343} INFO -  at 284.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:34] {3166} INFO - iteration 2208, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:35] {3343} INFO -  at 285.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:35] {3166} INFO - iteration 2209, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:35] {3343} INFO -  at 285.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:35] {3166} INFO - iteration 2210, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:35] {3343} INFO -  at 285.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:35] {3166} INFO - iteration 2211, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:35] {3343} INFO -  at 285.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:35] {3166} INFO - iteration 2212, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:35] {3343} INFO -  at 285.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:35] {3166} INFO - iteration 2213, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:35] {3343} INFO -  at 285.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:35] {3166} INFO - iteration 2214, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:35] {3343} INFO -  at 285.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:35] {3166} INFO - iteration 2215, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:35] {3343} INFO -  at 285.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:35] {3166} INFO - iteration 2216, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:35] {3343} INFO -  at 285.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:35] {3166} INFO - iteration 2217, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:35] {3343} INFO -  at 285.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:35] {3166} INFO - iteration 2218, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:36] {3343} INFO -  at 286.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:36] {3166} INFO - iteration 2219, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:36] {3343} INFO -  at 286.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:36] {3166} INFO - iteration 2220, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:36] {3343} INFO -  at 286.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:36] {3166} INFO - iteration 2221, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:36] {3343} INFO -  at 286.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:36] {3166} INFO - iteration 2222, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:36] {3343} INFO -  at 286.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:36] {3166} INFO - iteration 2223, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:36] {3343} INFO -  at 286.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:36] {3166} INFO - iteration 2224, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:36] {3343} INFO -  at 286.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:36] {3166} INFO - iteration 2225, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:36] {3343} INFO -  at 286.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:36] {3166} INFO - iteration 2226, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:36] {3343} INFO -  at 286.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:36] {3166} INFO - iteration 2227, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:36] {3343} INFO -  at 286.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:36] {3166} INFO - iteration 2228, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:36] {3343} INFO -  at 286.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:36] {3166} INFO - iteration 2229, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:37] {3343} INFO -  at 287.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:37] {3166} INFO - iteration 2230, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:37] {3343} INFO -  at 287.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:37] {3166} INFO - iteration 2231, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:37] {3343} INFO -  at 287.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:37] {3166} INFO - iteration 2232, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:37] {3343} INFO -  at 287.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:37] {3166} INFO - iteration 2233, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:37] {3343} INFO -  at 287.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:37] {3166} INFO - iteration 2234, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:37] {3343} INFO -  at 287.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:37] {3166} INFO - iteration 2235, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:37] {3343} INFO -  at 287.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:37] {3166} INFO - iteration 2236, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:37] {3343} INFO -  at 287.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:37] {3166} INFO - iteration 2237, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:37] {3343} INFO -  at 287.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:37] {3166} INFO - iteration 2238, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:37] {3343} INFO -  at 287.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:37] {3166} INFO - iteration 2239, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:37] {3343} INFO -  at 287.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:37] {3166} INFO - iteration 2240, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:37] {3343} INFO -  at 287.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:37] {3166} INFO - iteration 2241, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:38] {3343} INFO -  at 288.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:38] {3166} INFO - iteration 2242, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:38] {3343} INFO -  at 288.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:38] {3166} INFO - iteration 2243, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:38] {3343} INFO -  at 288.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:38] {3166} INFO - iteration 2244, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:38] {3343} INFO -  at 288.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:38] {3166} INFO - iteration 2245, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:38] {3343} INFO -  at 288.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:38] {3166} INFO - iteration 2246, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:38] {3343} INFO -  at 288.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:38] {3166} INFO - iteration 2247, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:38] {3343} INFO -  at 288.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:38] {3166} INFO - iteration 2248, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:38] {3343} INFO -  at 288.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:38] {3166} INFO - iteration 2249, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:38] {3343} INFO -  at 288.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:38] {3166} INFO - iteration 2250, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:38] {3343} INFO -  at 288.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:38] {3166} INFO - iteration 2251, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:38] {3343} INFO -  at 288.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:38] {3166} INFO - iteration 2252, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:39] {3343} INFO -  at 289.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:39] {3166} INFO - iteration 2253, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:39] {3343} INFO -  at 289.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:39] {3166} INFO - iteration 2254, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:39] {3343} INFO -  at 289.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:39] {3166} INFO - iteration 2255, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:39] {3343} INFO -  at 289.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:39] {3166} INFO - iteration 2256, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:39] {3343} INFO -  at 289.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:39] {3166} INFO - iteration 2257, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:39] {3343} INFO -  at 289.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:39] {3166} INFO - iteration 2258, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:39] {3343} INFO -  at 289.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:39] {3166} INFO - iteration 2259, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:39] {3343} INFO -  at 289.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:39] {3166} INFO - iteration 2260, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:39] {3343} INFO -  at 289.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:39] {3166} INFO - iteration 2261, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:39] {3343} INFO -  at 289.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:39] {3166} INFO - iteration 2262, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:39] {3343} INFO -  at 289.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:39] {3166} INFO - iteration 2263, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:39] {3343} INFO -  at 289.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:39] {3166} INFO - iteration 2264, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:40] {3343} INFO -  at 290.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:40] {3166} INFO - iteration 2265, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:40] {3343} INFO -  at 290.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:40] {3166} INFO - iteration 2266, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:40] {3343} INFO -  at 290.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:40] {3166} INFO - iteration 2267, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:40] {3343} INFO -  at 290.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:40] {3166} INFO - iteration 2268, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:40] {3343} INFO -  at 290.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:40] {3166} INFO - iteration 2269, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:40] {3343} INFO -  at 290.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:40] {3166} INFO - iteration 2270, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:40] {3343} INFO -  at 290.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:40] {3166} INFO - iteration 2271, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:40] {3343} INFO -  at 290.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:40] {3166} INFO - iteration 2272, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:40] {3343} INFO -  at 290.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:40] {3166} INFO - iteration 2273, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:40] {3343} INFO -  at 290.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:40] {3166} INFO - iteration 2274, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:40] {3343} INFO -  at 290.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:40] {3166} INFO - iteration 2275, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:41] {3343} INFO -  at 291.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:41] {3166} INFO - iteration 2276, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:41] {3343} INFO -  at 291.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:41] {3166} INFO - iteration 2277, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:41] {3343} INFO -  at 291.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269

[flaml.automl: 04-23 11:24:41] {3166} INFO - iteration 2278, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:41] {3343} INFO -  at 291.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:41] {3166} INFO - iteration 2279, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:41] {3343} INFO -  at 291.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:41] {3166} INFO - iteration 2280, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:41] {3343} INFO -  at 291.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:41] {3166} INFO - iteration 2281, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:41] {3343} INFO -  at 291.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:41] {3166} INFO - iteration 2282, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:41] {3343} INFO -  at 291.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:41] {3166} INFO - iteration 2283, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:41] {3343} INFO -  at 291.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:41] {3166} INFO - iteration 2284, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:41] {3343} INFO -  at 291.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:41] {3166} INFO - iteration 2285, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:42] {3343} INFO -  at 291.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:42] {3166} INFO - iteration 2286, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:42] {3343} INFO -  at 292.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:42] {3166} INFO - iteration 2287, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:42] {3343} INFO -  at 292.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:42] {3166} INFO - iteration 2288, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:42] {3343} INFO -  at 292.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:42] {3166} INFO - iteration 2289, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:42] {3343} INFO -  at 292.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:42] {3166} INFO - iteration 2290, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:42] {3343} INFO -  at 292.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:42] {3166} INFO - iteration 2291, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:42] {3343} INFO -  at 292.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:42] {3166} INFO - iteration 2292, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:42] {3343} INFO -  at 292.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:42] {3166} INFO - iteration 2293, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:42] {3343} INFO -  at 292.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:42] {3166} INFO - iteration 2294, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:43] {3343} INFO -  at 293.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:43] {3166} INFO - iteration 2295, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:43] {3343} INFO -  at 293.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:43] {3166} INFO - iteration 2296, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:43] {3343} INFO -  at 293.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:43] {3166} INFO - iteration 2297, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:43] {3343} INFO -  at 293.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:43] {3166} INFO - iteration 2298, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:43] {3343} INFO -  at 293.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:43] {3166} INFO - iteration 2299, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:44] {3343} INFO -  at 294.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:44] {3166} INFO - iteration 2300, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:44] {3343} INFO -  at 294.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:44] {3166} INFO - iteration 2301, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:44] {3343} INFO -  at 294.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:44] {3166} INFO - iteration 2302, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:44] {3343} INFO -  at 294.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:44] {3166} INFO - iteration 2303, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:44] {3343} INFO -  at 294.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:44] {3166} INFO - iteration 2304, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:44] {3343} INFO -  at 294.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:44] {3166} INFO - iteration 2305, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:45] {3343} INFO -  at 294.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:45] {3166} INFO - iteration 2306, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:45] {3343} INFO -  at 295.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:45] {3166} INFO - iteration 2307, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:45] {3343} INFO -  at 295.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:45] {3166} INFO - iteration 2308, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:45] {3343} INFO -  at 295.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:45] {3166} INFO - iteration 2309, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:45] {3343} INFO -  at 295.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:45] {3166} INFO - iteration 2310, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:45] {3343} INFO -  at 295.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:45] {3166} INFO - iteration 2311, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:45] {3343} INFO -  at 295.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:45] {3166} INFO - iteration 2312, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:45] {3343} INFO -  at 295.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:45] {3166} INFO - iteration 2313, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:46] {3343} INFO -  at 296.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:46] {3166} INFO - iteration 2314, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:46] {3343} INFO -  at 296.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:46] {3166} INFO - iteration 2315, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:46] {3343} INFO -  at 296.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:46] {3166} INFO - iteration 2316, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:46] {3343} INFO -  at 296.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:46] {3166} INFO - iteration 2317, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:46] {3343} INFO -  at 296.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:46] {3166} INFO - iteration 2318, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:46] {3343} INFO -  at 296.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:46] {3166} INFO - iteration 2319, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:46] {3343} INFO -  at 296.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:46] {3166} INFO - iteration 2320, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:46] {3343} INFO -  at 296.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:46] {3166} INFO - iteration 2321, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:47] {3343} INFO -  at 297.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:47] {3166} INFO - iteration 2322, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:47] {3343} INFO -  at 297.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:47] {3166} INFO - iteration 2323, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:47] {3343} INFO -  at 297.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:47] {3166} INFO - iteration 2324, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:47] {3343} INFO -  at 297.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:47] {3166} INFO - iteration 2325, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:47] {3343} INFO -  at 297.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:47] {3166} INFO - iteration 2326, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:47] {3343} INFO -  at 297.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:47] {3166} INFO - iteration 2327, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:47] {3343} INFO -  at 297.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:47] {3166} INFO - iteration 2328, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:47] {3343} INFO -  at 297.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:47] {3166} INFO - iteration 2329, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:47] {3343} INFO -  at 297.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:47] {3166} INFO - iteration 2330, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:47] {3343} INFO -  at 297.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:47] {3166} INFO - iteration 2331, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:47] {3343} INFO -  at 297.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:47] {3166} INFO - iteration 2332, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:48] {3343} INFO -  at 297.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:48] {3166} INFO - iteration 2333, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:48] {3343} INFO -  at 298.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:48] {3166} INFO - iteration 2334, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:48] {3343} INFO -  at 298.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:48] {3166} INFO - iteration 2335, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:48] {3343} INFO -  at 298.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:48] {3166} INFO - iteration 2336, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:48] {3343} INFO -  at 298.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:48] {3166} INFO - iteration 2337, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:48] {3343} INFO -  at 298.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:48] {3166} INFO - iteration 2338, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:48] {3343} INFO -  at 298.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:48] {3166} INFO - iteration 2339, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:48] {3343} INFO -  at 298.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:48] {3166} INFO - iteration 2340, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:48] {3343} INFO -  at 298.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:48] {3166} INFO - iteration 2341, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:48] {3343} INFO -  at 298.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:48] {3166} INFO - iteration 2342, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:48] {3343} INFO -  at 298.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:48] {3166} INFO - iteration 2343, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:48] {3343} INFO -  at 298.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:48] {3166} INFO - iteration 2344, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:49] {3343} INFO -  at 299.0s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:49] {3166} INFO - iteration 2345, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:49] {3343} INFO -  at 299.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:49] {3166} INFO - iteration 2346, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:49] {3343} INFO -  at 299.1s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:49] {3166} INFO - iteration 2347, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:49] {3343} INFO -  at 299.2s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:49] {3166} INFO - iteration 2348, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:49] {3343} INFO -  at 299.3s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:49] {3166} INFO - iteration 2349, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:49] {3343} INFO -  at 299.4s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:49] {3166} INFO - iteration 2350, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:49] {3343} INFO -  at 299.5s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:49] {3166} INFO - iteration 2351, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:49] {3343} INFO -  at 299.6s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:49] {3166} INFO - iteration 2352, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:49] {3343} INFO -  at 299.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:49] {3166} INFO - iteration 2353, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:49] {3343} INFO -  at 299.7s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:49] {3166} INFO - iteration 2354, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:49] {3343} INFO -  at 299.8s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:49] {3166} INFO - iteration 2355, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:49] {3343} INFO -  at 299.9s,	estimator rf's best error=81.3269,	best estimator rf's best error=81.3269
[flaml.automl: 04-23 11:24:50] {3602} INFO - retrain rf for 0.1s
[flaml.automl: 04-23 11:24:50] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.6208203442428368, max_leaf_nodes=459,
                      n_estimators=19, n_jobs=-1)
[flaml.automl: 04-23 11:24:50] {2901} INFO - fit succeeded
[flaml.automl: 04-23 11:24:50] {2902} INFO - Time taken to find the best model: 151.29160976409912
[flaml.automl: 04-23 11:24:50] {2599} INFO - task = regression
[flaml.automl: 04-23 11:24:50] {2601} INFO - Data split method: uniform
[flaml.automl: 04-23 11:24:50] {2604} INFO - Evaluation method: holdout
[flaml.automl: 04-23 11:24:50] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 04-23 11:24:50] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 04-23 11:24:50] {3166} INFO - iteration 0, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:50] {3296} INFO - Estimated sufficient time budget=467s. Estimated necessary time budget=0s.
[flaml.automl: 04-23 11:24:50] {3343} INFO -  at 0.1s,	estimator rf's best error=139.3047,	best estimator rf's best error=139.3047
[flaml.automl: 04-23 11:24:50] {3166} INFO - iteration 1, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:50] {3343} INFO -  at 0.2s,	estimator rf's best error=113.4293,	best estimator rf's best error=113.4293
[flaml.automl: 04-23 11:24:50] {3166} INFO - iteration 2, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

0.72 0.5 0.43

[flaml.automl: 04-23 11:24:50] {3343} INFO -  at 0.2s,	estimator rf's best error=113.4293,	best estimator rf's best error=113.4293
[flaml.automl: 04-23 11:24:50] {3166} INFO - iteration 3, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:50] {3343} INFO -  at 0.3s,	estimator rf's best error=100.4852,	best estimator rf's best error=100.4852
[flaml.automl: 04-23 11:24:50] {3166} INFO - iteration 4, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:50] {3343} INFO -  at 0.3s,	estimator rf's best error=93.6881,	best estimator rf's best error=93.6881
[flaml.automl: 04-23 11:24:50] {3166} INFO - iteration 5, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:50] {3343} INFO -  at 0.4s,	estimator rf's best error=93.6881,	best estimator rf's best error=93.6881
[flaml.automl: 04-23 11:24:50] {3166} INFO - iteration 6, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:50] {3343} INFO -  at 0.4s,	estimator rf's best error=93.6881,	best estimator rf's best error=93.6881
[flaml.automl: 04-23 11:24:50] {3166} INFO - iteration 7, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:50] {3343} INFO -  at 0.5s,	estimator rf's best error=93.6881,	best estimator rf's best error=93.6881
[flaml.automl: 04-23 11:24:50] {3166} INFO - iteration 8, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:50] {3343} INFO -  at 0.6s,	estimator rf's best error=91.4864,	best estimator rf's best error=91.4864
[flaml.automl: 04-23 11:24:50] {3166} INFO - iteration 9, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:50] {3343} INFO -  at 0.7s,	estimator rf's best error=91.4864,	best estimator rf's best error=91.4864
[flaml.automl: 04-23 11:24:50] {3166} INFO - iteration 10, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:50] {3343} INFO -  at 0.7s,	estimator rf's best error=91.4864,	best estimator rf's best error=91.4864
[flaml.automl: 04-23 11:24:50] {3166} INFO - iteration 11, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:50] {3343} INFO -  at 0.8s,	estimator rf's best error=91.4864,	best estimator rf's best error=91.4864
[flaml.automl: 04-23 11:24:50] {3166} INFO - iteration 12, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:51] {3343} INFO -  at 0.9s,	estimator rf's best error=91.4864,	best estimator rf's best error=91.4864
[flaml.automl: 04-23 11:24:51] {3166} INFO - iteration 13, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:51] {3343} INFO -  at 1.0s,	estimator rf's best error=88.4459,	best estimator rf's best error=88.4459
[flaml.automl: 04-23 11:24:51] {3166} INFO - iteration 14, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:51] {3343} INFO -  at 1.1s,	estimator rf's best error=88.4459,	best estimator rf's best error=88.4459
[flaml.automl: 04-23 11:24:51] {3166} INFO - iteration 15, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:51] {3343} INFO -  at 1.3s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:51] {3166} INFO - iteration 16, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:51] {3343} INFO -  at 1.4s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:51] {3166} INFO - iteration 17, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:52] {3343} INFO -  at 2.2s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:52] {3166} INFO - iteration 18, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:53] {3343} INFO -  at 3.0s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:53] {3166} INFO - iteration 19, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:53] {3343} INFO -  at 3.2s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:53] {3166} INFO - iteration 20, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:54] {3343} INFO -  at 3.9s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:54] {3166} INFO - iteration 21, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:54] {3343} INFO -  at 4.2s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:54] {3166} INFO - iteration 22, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:54] {3343} INFO -  at 4.4s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:54] {3166} INFO - iteration 23, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:55] {3343} INFO -  at 5.2s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:55] {3166} INFO - iteration 24, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:55] {3343} INFO -  at 5.6s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:55] {3166} INFO - iteration 25, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:56] {3343} INFO -  at 5.9s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:56] {3166} INFO - iteration 26, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:56] {3343} INFO -  at 6.6s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:56] {3166} INFO - iteration 27, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:56] {3343} INFO -  at 6.7s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:56] {3166} INFO - iteration 28, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:24:57] {3343} INFO -  at 7.0s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:57] {3166} INFO - iteration 29, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:57] {3343} INFO -  at 7.3s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:57] {3166} INFO - iteration 30, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:57] {3343} INFO -  at 7.6s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:57] {3166} INFO - iteration 31, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:58] {3343} INFO -  at 8.0s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:58] {3166} INFO - iteration 32, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:58] {3343} INFO -  at 8.4s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:58] {3166} INFO - iteration 33, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:58] {3343} INFO -  at 8.7s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:58] {3166} INFO - iteration 34, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:59] {3343} INFO -  at 9.3s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:59] {3166} INFO - iteration 35, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:59] {3343} INFO -  at 9.5s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:59] {3166} INFO - iteration 36, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:24:59] {3343} INFO -  at 9.7s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:24:59] {3166} INFO - iteration 37, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:00] {3343} INFO -  at 10.2s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:25:00] {3166} INFO - iteration 38, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:00] {3343} INFO -  at 10.7s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:25:00] {3166} INFO - iteration 39, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:01] {3343} INFO -  at 11.0s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:25:01] {3166} INFO - iteration 40, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:01] {3343} INFO -  at 11.4s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:25:01] {3166} INFO - iteration 41, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:01] {3343} INFO -  at 11.7s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:25:01] {3166} INFO - iteration 42, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:02] {3343} INFO -  at 12.0s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:25:02] {3166} INFO - iteration 43, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:02] {3343} INFO -  at 12.2s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:25:02] {3166} INFO - iteration 44, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:02] {3343} INFO -  at 12.5s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:25:02] {3166} INFO - iteration 45, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:02] {3343} INFO -  at 12.8s,	estimator rf's best error=83.2630,	best estimator rf's best error=83.2630
[flaml.automl: 04-23 11:25:02] {3166} INFO - iteration 46, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:03] {3343} INFO -  at 13.1s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:03] {3166} INFO - iteration 47, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:03] {3343} INFO -  at 13.4s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:03] {3166} INFO - iteration 48, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:03] {3343} INFO -  at 13.7s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:03] {3166} INFO - iteration 49, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:04] {3343} INFO -  at 14.5s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:04] {3166} INFO - iteration 50, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:05] {3343} INFO -  at 15.1s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:05] {3166} INFO - iteration 51, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:05] {3343} INFO -  at 15.4s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:05] {3166} INFO - iteration 52, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:05] {3343} INFO -  at 15.8s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:05] {3166} INFO - iteration 53, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:06] {3343} INFO -  at 16.1s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:06] {3166} INFO - iteration 54, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:06] {3343} INFO -  at 16.3s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:06] {3166} INFO - iteration 55, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:06] {3343} INFO -  at 16.8s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:06] {3166} INFO - iteration 56, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:07] {3343} INFO -  at 17.3s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:07] {3166} INFO - iteration 57, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:07] {3343} INFO -  at 17.5s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:07] {3166} INFO - iteration 58, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:08] {3343} INFO -  at 18.0s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:08] {3166} INFO - iteration 59, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:08] {3343} INFO -  at 18.2s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:08] {3166} INFO - iteration 60, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:08] {3343} INFO -  at 18.6s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:08] {3166} INFO - iteration 61, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:09] {3343} INFO -  at 19.0s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:09] {3166} INFO - iteration 62, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:09] {3343} INFO -  at 19.8s,	estimator rf's best error=83.1954,	best estimator rf's best error=83.1954
[flaml.automl: 04-23 11:25:09] {3166} INFO - iteration 63, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:10] {3343} INFO -  at 20.0s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:10] {3166} INFO - iteration 64, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:10] {3343} INFO -  at 20.2s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:10] {3166} INFO - iteration 65, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:10] {3343} INFO -  at 20.6s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:10] {3166} INFO - iteration 66, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:10] {3343} INFO -  at 20.8s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:10] {3166} INFO - iteration 67, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:11] {3343} INFO -  at 21.1s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:11] {3166} INFO - iteration 68, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:11] {3343} INFO -  at 21.3s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:11] {3166} INFO - iteration 69, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:11] {3343} INFO -  at 21.6s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:11] {3166} INFO - iteration 70, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:12] {3343} INFO -  at 22.2s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:12] {3166} INFO - iteration 71, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:12] {3343} INFO -  at 22.4s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:12] {3166} INFO - iteration 72, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:12] {3343} INFO -  at 22.7s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:12] {3166} INFO - iteration 73, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:13] {3343} INFO -  at 23.2s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:13] {3166} INFO - iteration 74, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:13] {3343} INFO -  at 23.5s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:13] {3166} INFO - iteration 75, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:13] {3343} INFO -  at 23.7s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:13] {3166} INFO - iteration 76, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:14] {3343} INFO -  at 23.9s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:14] {3166} INFO - iteration 77, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:14] {3343} INFO -  at 24.1s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:14] {3166} INFO - iteration 78, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:14] {3343} INFO -  at 24.3s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:14] {3166} INFO - iteration 79, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:14] {3343} INFO -  at 24.6s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:14] {3166} INFO - iteration 80, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:14] {3343} INFO -  at 24.8s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:14] {3166} INFO - iteration 81, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:15] {3343} INFO -  at 25.1s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:15] {3166} INFO - iteration 82, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:15] {3343} INFO -  at 25.3s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:15] {3166} INFO - iteration 83, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:15] {3343} INFO -  at 25.5s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:15] {3166} INFO - iteration 84, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:15] {3343} INFO -  at 25.7s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:15] {3166} INFO - iteration 85, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:16] {3343} INFO -  at 26.1s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:16] {3166} INFO - iteration 86, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:16] {3343} INFO -  at 26.4s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:16] {3166} INFO - iteration 87, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:16] {3343} INFO -  at 26.6s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:16] {3166} INFO - iteration 88, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:16] {3343} INFO -  at 26.8s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:16] {3166} INFO - iteration 89, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:17] {3343} INFO -  at 27.2s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:17] {3166} INFO - iteration 90, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:17] {3343} INFO -  at 27.6s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:17] {3166} INFO - iteration 91, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:17] {3343} INFO -  at 27.9s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:17] {3166} INFO - iteration 92, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:18] {3343} INFO -  at 28.1s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:18] {3166} INFO - iteration 93, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:18] {3343} INFO -  at 28.5s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:18] {3166} INFO - iteration 94, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:18] {3343} INFO -  at 28.9s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:18] {3166} INFO - iteration 95, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:19] {3343} INFO -  at 29.2s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:19] {3166} INFO - iteration 96, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:19] {3343} INFO -  at 29.6s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:19] {3166} INFO - iteration 97, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:19] {3343} INFO -  at 29.8s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:19] {3166} INFO - iteration 98, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:20] {3343} INFO -  at 30.1s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:20] {3166} INFO - iteration 99, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:20] {3343} INFO -  at 30.6s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:20] {3166} INFO - iteration 100, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:21] {3343} INFO -  at 31.0s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:21] {3166} INFO - iteration 101, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:21] {3343} INFO -  at 31.5s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:21] {3166} INFO - iteration 102, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:21] {3343} INFO -  at 31.9s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:21] {3166} INFO - iteration 103, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:22] {3343} INFO -  at 32.1s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:22] {3166} INFO - iteration 104, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:22] {3343} INFO -  at 32.5s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:22] {3166} INFO - iteration 105, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:22] {3343} INFO -  at 32.8s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:22] {3166} INFO - iteration 106, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:23] {3343} INFO -  at 33.0s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:23] {3166} INFO - iteration 107, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:23] {3343} INFO -  at 33.7s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:23] {3166} INFO - iteration 108, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:24] {3343} INFO -  at 34.1s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:24] {3166} INFO - iteration 109, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:24] {3343} INFO -  at 34.5s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:24] {3166} INFO - iteration 110, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:25] {3343} INFO -  at 35.5s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:25] {3166} INFO - iteration 111, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:25] {3343} INFO -  at 35.8s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:25] {3166} INFO - iteration 112, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:26] {3343} INFO -  at 36.2s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:26] {3166} INFO - iteration 113, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:26] {3343} INFO -  at 36.4s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:26] {3166} INFO - iteration 114, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:26] {3343} INFO -  at 36.7s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:26] {3166} INFO - iteration 115, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:27] {3343} INFO -  at 37.0s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:27] {3166} INFO - iteration 116, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:27] {3343} INFO -  at 37.2s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:27] {3166} INFO - iteration 117, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:27] {3343} INFO -  at 37.6s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:27] {3166} INFO - iteration 118, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:27] {3343} INFO -  at 37.8s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:27] {3166} INFO - iteration 119, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:28] {3343} INFO -  at 38.2s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:28] {3166} INFO - iteration 120, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:28] {3343} INFO -  at 38.4s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:28] {3166} INFO - iteration 121, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:28] {3343} INFO -  at 38.8s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:28] {3166} INFO - iteration 122, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:29] {3343} INFO -  at 39.1s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:29] {3166} INFO - iteration 123, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:29] {3343} INFO -  at 39.3s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:29] {3166} INFO - iteration 124, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:29] {3343} INFO -  at 39.7s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:29] {3166} INFO - iteration 125, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:29] {3343} INFO -  at 39.9s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:29] {3166} INFO - iteration 126, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:30] {3343} INFO -  at 40.2s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:30] {3166} INFO - iteration 127, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:30] {3343} INFO -  at 40.5s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:30] {3166} INFO - iteration 128, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:30] {3343} INFO -  at 40.7s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:30] {3166} INFO - iteration 129, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:31] {3343} INFO -  at 41.1s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:31] {3166} INFO - iteration 130, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:31] {3343} INFO -  at 41.5s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:31] {3166} INFO - iteration 131, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:31] {3343} INFO -  at 41.7s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:31] {3166} INFO - iteration 132, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:32] {3343} INFO -  at 42.0s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:32] {3166} INFO - iteration 133, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:32] {3343} INFO -  at 42.3s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:32] {3166} INFO - iteration 134, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:32] {3343} INFO -  at 42.5s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:32] {3166} INFO - iteration 135, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:32] {3343} INFO -  at 42.8s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:32] {3166} INFO - iteration 136, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:33] {3343} INFO -  at 43.2s,	estimator rf's best error=82.4268,	best estimator rf's best error=82.4268
[flaml.automl: 04-23 11:25:33] {3166} INFO - iteration 137, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:33] {3343} INFO -  at 43.4s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:33] {3166} INFO - iteration 138, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:33] {3343} INFO -  at 43.6s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:33] {3166} INFO - iteration 139, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:33] {3343} INFO -  at 43.9s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:33] {3166} INFO - iteration 140, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:34] {3343} INFO -  at 44.1s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:34] {3166} INFO - iteration 141, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:34] {3343} INFO -  at 44.3s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:34] {3166} INFO - iteration 142, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:34] {3343} INFO -  at 44.6s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:34] {3166} INFO - iteration 143, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:34] {3343} INFO -  at 44.8s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:34] {3166} INFO - iteration 144, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:35] {3343} INFO -  at 45.0s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:35] {3166} INFO - iteration 145, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:35] {3343} INFO -  at 45.2s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:35] {3166} INFO - iteration 146, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:35] {3343} INFO -  at 45.4s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:35] {3166} INFO - iteration 147, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:35] {3343} INFO -  at 45.7s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:35] {3166} INFO - iteration 148, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:36] {3343} INFO -  at 45.9s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:36] {3166} INFO - iteration 149, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:36] {3343} INFO -  at 46.1s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:36] {3166} INFO - iteration 150, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:36] {3343} INFO -  at 46.4s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:36] {3166} INFO - iteration 151, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:36] {3343} INFO -  at 46.6s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:36] {3166} INFO - iteration 152, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:36] {3343} INFO -  at 46.8s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:36] {3166} INFO - iteration 153, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:37] {3343} INFO -  at 47.0s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:37] {3166} INFO - iteration 154, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:37] {3343} INFO -  at 47.3s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:37] {3166} INFO - iteration 155, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:37] {3343} INFO -  at 47.4s,	estimator rf's best error=82.1175,	best estimator rf's best error=82.1175
[flaml.automl: 04-23 11:25:37] {3166} INFO - iteration 156, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:37] {3343} INFO -  at 47.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:37] {3166} INFO - iteration 157, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:37] {3343} INFO -  at 47.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:37] {3166} INFO - iteration 158, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:38] {3343} INFO -  at 48.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:38] {3166} INFO - iteration 159, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:38] {3343} INFO -  at 48.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:38] {3166} INFO - iteration 160, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:38] {3343} INFO -  at 48.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:38] {3166} INFO - iteration 161, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:38] {3343} INFO -  at 48.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:38] {3166} INFO - iteration 162, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:39] {3343} INFO -  at 49.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:39] {3166} INFO - iteration 163, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:39] {3343} INFO -  at 49.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:39] {3166} INFO - iteration 164, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:39] {3343} INFO -  at 49.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:39] {3166} INFO - iteration 165, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:39] {3343} INFO -  at 49.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:39] {3166} INFO - iteration 166, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:40] {3343} INFO -  at 50.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:40] {3166} INFO - iteration 167, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:40] {3343} INFO -  at 50.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:40] {3166} INFO - iteration 168, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:40] {3343} INFO -  at 50.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:40] {3166} INFO - iteration 169, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:41] {3343} INFO -  at 50.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:41] {3166} INFO - iteration 170, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:41] {3343} INFO -  at 51.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:41] {3166} INFO - iteration 171, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:41] {3343} INFO -  at 51.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:41] {3166} INFO - iteration 172, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:41] {3343} INFO -  at 51.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:41] {3166} INFO - iteration 173, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:42] {3343} INFO -  at 52.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:42] {3166} INFO - iteration 174, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:42] {3343} INFO -  at 52.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:42] {3166} INFO - iteration 175, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:42] {3343} INFO -  at 52.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:42] {3166} INFO - iteration 176, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:42] {3343} INFO -  at 52.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:42] {3166} INFO - iteration 177, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:43] {3343} INFO -  at 53.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:43] {3166} INFO - iteration 178, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:43] {3343} INFO -  at 53.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:43] {3166} INFO - iteration 179, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:43] {3343} INFO -  at 53.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:43] {3166} INFO - iteration 180, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:44] {3343} INFO -  at 53.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:44] {3166} INFO - iteration 181, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:44] {3343} INFO -  at 54.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:44] {3166} INFO - iteration 182, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:44] {3343} INFO -  at 54.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:44] {3166} INFO - iteration 183, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:44] {3343} INFO -  at 54.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:44] {3166} INFO - iteration 184, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:45] {3343} INFO -  at 55.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:45] {3166} INFO - iteration 185, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:45] {3343} INFO -  at 55.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:45] {3166} INFO - iteration 186, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:45] {3343} INFO -  at 55.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:45] {3166} INFO - iteration 187, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:45] {3343} INFO -  at 55.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:45] {3166} INFO - iteration 188, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:46] {3343} INFO -  at 55.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:46] {3166} INFO - iteration 189, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:46] {3343} INFO -  at 56.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:46] {3166} INFO - iteration 190, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:46] {3343} INFO -  at 56.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:46] {3166} INFO - iteration 191, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:46] {3343} INFO -  at 56.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:46] {3166} INFO - iteration 192, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:46] {3343} INFO -  at 56.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:46] {3166} INFO - iteration 193, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:47] {3343} INFO -  at 57.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:47] {3166} INFO - iteration 194, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:47] {3343} INFO -  at 57.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:47] {3166} INFO - iteration 195, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:47] {3343} INFO -  at 57.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:47] {3166} INFO - iteration 196, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:48] {3343} INFO -  at 57.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:48] {3166} INFO - iteration 197, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:48] {3343} INFO -  at 58.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:48] {3166} INFO - iteration 198, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:48] {3343} INFO -  at 58.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:48] {3166} INFO - iteration 199, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:48] {3343} INFO -  at 58.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:48] {3166} INFO - iteration 200, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:48] {3343} INFO -  at 58.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:48] {3166} INFO - iteration 201, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:49] {3343} INFO -  at 59.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:49] {3166} INFO - iteration 202, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:49] {3343} INFO -  at 59.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:49] {3166} INFO - iteration 203, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:49] {3343} INFO -  at 59.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:49] {3166} INFO - iteration 204, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:50] {3343} INFO -  at 59.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:50] {3166} INFO - iteration 205, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:50] {3343} INFO -  at 60.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:50] {3166} INFO - iteration 206, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:50] {3343} INFO -  at 60.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:50] {3166} INFO - iteration 207, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:50] {3343} INFO -  at 60.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:50] {3166} INFO - iteration 208, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:51] {3343} INFO -  at 61.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:51] {3166} INFO - iteration 209, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:51] {3343} INFO -  at 61.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:51] {3166} INFO - iteration 210, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:51] {3343} INFO -  at 61.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:51] {3166} INFO - iteration 211, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:51] {3343} INFO -  at 61.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:51] {3166} INFO - iteration 212, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:52] {3343} INFO -  at 62.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:52] {3166} INFO - iteration 213, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:52] {3343} INFO -  at 62.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:52] {3166} INFO - iteration 214, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:52] {3343} INFO -  at 62.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:52] {3166} INFO - iteration 215, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:53] {3343} INFO -  at 62.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:53] {3166} INFO - iteration 216, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:53] {3343} INFO -  at 63.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:53] {3166} INFO - iteration 217, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:53] {3343} INFO -  at 63.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:53] {3166} INFO - iteration 218, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:53] {3343} INFO -  at 63.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:53] {3166} INFO - iteration 219, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:53] {3343} INFO -  at 63.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:53] {3166} INFO - iteration 220, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:54] {3343} INFO -  at 64.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:54] {3166} INFO - iteration 221, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:54] {3343} INFO -  at 64.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:54] {3166} INFO - iteration 222, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:54] {3343} INFO -  at 64.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:54] {3166} INFO - iteration 223, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:54] {3343} INFO -  at 64.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712

[flaml.automl: 04-23 11:25:54] {3166} INFO - iteration 224, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:54] {3343} INFO -  at 64.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:54] {3166} INFO - iteration 225, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:55] {3343} INFO -  at 65.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:55] {3166} INFO - iteration 226, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:55] {3343} INFO -  at 65.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:55] {3166} INFO - iteration 227, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:55] {3343} INFO -  at 65.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:55] {3166} INFO - iteration 228, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:55] {3343} INFO -  at 65.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:55] {3166} INFO - iteration 229, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:56] {3343} INFO -  at 65.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:56] {3166} INFO - iteration 230, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:56] {3343} INFO -  at 66.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:56] {3166} INFO - iteration 231, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:56] {3343} INFO -  at 66.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:56] {3166} INFO - iteration 232, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:56] {3343} INFO -  at 66.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:56] {3166} INFO - iteration 233, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:56] {3343} INFO -  at 66.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:56] {3166} INFO - iteration 234, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:56] {3343} INFO -  at 66.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:56] {3166} INFO - iteration 235, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:57] {3343} INFO -  at 67.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:57] {3166} INFO - iteration 236, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:57] {3343} INFO -  at 67.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:57] {3166} INFO - iteration 237, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:57] {3343} INFO -  at 67.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:57] {3166} INFO - iteration 238, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:57] {3343} INFO -  at 67.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:57] {3166} INFO - iteration 239, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:57] {3343} INFO -  at 67.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:57] {3166} INFO - iteration 240, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:58] {3343} INFO -  at 67.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:58] {3166} INFO - iteration 241, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:58] {3343} INFO -  at 68.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:58] {3166} INFO - iteration 242, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:58] {3343} INFO -  at 68.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:58] {3166} INFO - iteration 243, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:58] {3343} INFO -  at 68.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:58] {3166} INFO - iteration 244, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:58] {3343} INFO -  at 68.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:58] {3166} INFO - iteration 245, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:59] {3343} INFO -  at 68.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:59] {3166} INFO - iteration 246, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:59] {3343} INFO -  at 69.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:59] {3166} INFO - iteration 247, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:59] {3343} INFO -  at 69.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:59] {3166} INFO - iteration 248, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:25:59] {3343} INFO -  at 69.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:59] {3166} INFO - iteration 249, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:25:59] {3343} INFO -  at 69.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:25:59] {3166} INFO - iteration 250, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:00] {3343} INFO -  at 69.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:00] {3166} INFO - iteration 251, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:00] {3343} INFO -  at 70.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:00] {3166} INFO - iteration 252, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:00] {3343} INFO -  at 70.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:00] {3166} INFO - iteration 253, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:00] {3343} INFO -  at 70.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:00] {3166} INFO - iteration 254, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:00] {3343} INFO -  at 70.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:00] {3166} INFO - iteration 255, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:01] {3343} INFO -  at 70.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:01] {3166} INFO - iteration 256, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:01] {3343} INFO -  at 71.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:01] {3166} INFO - iteration 257, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:01] {3343} INFO -  at 71.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:01] {3166} INFO - iteration 258, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:01] {3343} INFO -  at 71.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:01] {3166} INFO - iteration 259, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:01] {3343} INFO -  at 71.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:01] {3166} INFO - iteration 260, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:02] {3343} INFO -  at 71.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:02] {3166} INFO - iteration 261, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:02] {3343} INFO -  at 72.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:02] {3166} INFO - iteration 262, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:02] {3343} INFO -  at 72.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:02] {3166} INFO - iteration 263, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:02] {3343} INFO -  at 72.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:02] {3166} INFO - iteration 264, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:02] {3343} INFO -  at 72.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:02] {3166} INFO - iteration 265, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:03] {3343} INFO -  at 72.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:03] {3166} INFO - iteration 266, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:03] {3343} INFO -  at 73.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:03] {3166} INFO - iteration 267, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:03] {3343} INFO -  at 73.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:03] {3166} INFO - iteration 268, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:03] {3343} INFO -  at 73.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:03] {3166} INFO - iteration 269, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:03] {3343} INFO -  at 73.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:03] {3166} INFO - iteration 270, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:04] {3343} INFO -  at 73.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:04] {3166} INFO - iteration 271, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:04] {3343} INFO -  at 74.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:04] {3166} INFO - iteration 272, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:04] {3343} INFO -  at 74.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:04] {3166} INFO - iteration 273, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:04] {3343} INFO -  at 74.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:04] {3166} INFO - iteration 274, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:04] {3343} INFO -  at 74.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:04] {3166} INFO - iteration 275, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:05] {3343} INFO -  at 74.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:05] {3166} INFO - iteration 276, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:05] {3343} INFO -  at 75.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:05] {3166} INFO - iteration 277, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:05] {3343} INFO -  at 75.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:05] {3166} INFO - iteration 278, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:05] {3343} INFO -  at 75.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:05] {3166} INFO - iteration 279, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:05] {3343} INFO -  at 75.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:05] {3166} INFO - iteration 280, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:06] {3343} INFO -  at 75.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:06] {3166} INFO - iteration 281, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:06] {3343} INFO -  at 76.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:06] {3166} INFO - iteration 282, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:06] {3343} INFO -  at 76.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:06] {3166} INFO - iteration 283, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:06] {3343} INFO -  at 76.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:06] {3166} INFO - iteration 284, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:06] {3343} INFO -  at 76.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:06] {3166} INFO - iteration 285, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:07] {3343} INFO -  at 76.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:07] {3166} INFO - iteration 286, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:07] {3343} INFO -  at 77.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:07] {3166} INFO - iteration 287, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:07] {3343} INFO -  at 77.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:07] {3166} INFO - iteration 288, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:07] {3343} INFO -  at 77.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712

[flaml.automl: 04-23 11:26:07] {3166} INFO - iteration 289, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:07] {3343} INFO -  at 77.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:07] {3166} INFO - iteration 290, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:08] {3343} INFO -  at 77.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:08] {3166} INFO - iteration 291, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:08] {3343} INFO -  at 78.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:08] {3166} INFO - iteration 292, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:08] {3343} INFO -  at 78.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:08] {3166} INFO - iteration 293, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:08] {3343} INFO -  at 78.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:08] {3166} INFO - iteration 294, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:08] {3343} INFO -  at 78.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:08] {3166} INFO - iteration 295, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:08] {3343} INFO -  at 78.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:08] {3166} INFO - iteration 296, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:09] {3343} INFO -  at 79.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:09] {3166} INFO - iteration 297, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:09] {3343} INFO -  at 79.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:09] {3166} INFO - iteration 298, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:09] {3343} INFO -  at 79.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:09] {3166} INFO - iteration 299, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:09] {3343} INFO -  at 79.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:09] {3166} INFO - iteration 300, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:10] {3343} INFO -  at 80.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:10] {3166} INFO - iteration 301, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:10] {3343} INFO -  at 80.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:10] {3166} INFO - iteration 302, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:10] {3343} INFO -  at 80.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:10] {3166} INFO - iteration 303, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:10] {3343} INFO -  at 80.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:10] {3166} INFO - iteration 304, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:11] {3343} INFO -  at 81.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:11] {3166} INFO - iteration 305, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:11] {3343} INFO -  at 81.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:11] {3166} INFO - iteration 306, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:11] {3343} INFO -  at 81.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:11] {3166} INFO - iteration 307, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:11] {3343} INFO -  at 81.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:11] {3166} INFO - iteration 308, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:12] {3343} INFO -  at 81.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:12] {3166} INFO - iteration 309, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:12] {3343} INFO -  at 82.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:12] {3166} INFO - iteration 310, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:12] {3343} INFO -  at 82.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:12] {3166} INFO - iteration 311, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:12] {3343} INFO -  at 82.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:12] {3166} INFO - iteration 312, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:12] {3343} INFO -  at 82.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:12] {3166} INFO - iteration 313, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:13] {3343} INFO -  at 82.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:13] {3166} INFO - iteration 314, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:13] {3343} INFO -  at 83.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:13] {3166} INFO - iteration 315, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:13] {3343} INFO -  at 83.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:13] {3166} INFO - iteration 316, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:13] {3343} INFO -  at 83.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:13] {3166} INFO - iteration 317, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:14] {3343} INFO -  at 84.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:14] {3166} INFO - iteration 318, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:14] {3343} INFO -  at 84.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:14] {3166} INFO - iteration 319, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:14] {3343} INFO -  at 84.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:14] {3166} INFO - iteration 320, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:15] {3343} INFO -  at 85.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:15] {3166} INFO - iteration 321, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:15] {3343} INFO -  at 85.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:15] {3166} INFO - iteration 322, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:15] {3343} INFO -  at 85.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:15] {3166} INFO - iteration 323, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:15] {3343} INFO -  at 85.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:15] {3166} INFO - iteration 324, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:16] {3343} INFO -  at 86.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:16] {3166} INFO - iteration 325, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:16] {3343} INFO -  at 86.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:16] {3166} INFO - iteration 326, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:16] {3343} INFO -  at 86.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:16] {3166} INFO - iteration 327, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:16] {3343} INFO -  at 86.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712

[flaml.automl: 04-23 11:26:16] {3166} INFO - iteration 328, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:16] {3343} INFO -  at 86.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:16] {3166} INFO - iteration 329, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:17] {3343} INFO -  at 86.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:17] {3166} INFO - iteration 330, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:17] {3343} INFO -  at 87.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:17] {3166} INFO - iteration 331, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:17] {3343} INFO -  at 87.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:17] {3166} INFO - iteration 332, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:17] {3343} INFO -  at 87.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:17] {3166} INFO - iteration 333, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:17] {3343} INFO -  at 87.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:17] {3166} INFO - iteration 334, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:17] {3343} INFO -  at 87.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:17] {3166} INFO - iteration 335, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:18] {3343} INFO -  at 88.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:18] {3166} INFO - iteration 336, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:18] {3343} INFO -  at 88.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:18] {3166} INFO - iteration 337, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:18] {3343} INFO -  at 88.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:18] {3166} INFO - iteration 338, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:18] {3343} INFO -  at 88.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:18] {3166} INFO - iteration 339, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:18] {3343} INFO -  at 88.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:18] {3166} INFO - iteration 340, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:19] {3343} INFO -  at 89.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:19] {3166} INFO - iteration 341, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:19] {3343} INFO -  at 89.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:19] {3166} INFO - iteration 342, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:19] {3343} INFO -  at 89.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:19] {3166} INFO - iteration 343, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:19] {3343} INFO -  at 89.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:19] {3166} INFO - iteration 344, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:20] {3343} INFO -  at 90.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:20] {3166} INFO - iteration 345, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:20] {3343} INFO -  at 90.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:20] {3166} INFO - iteration 346, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:20] {3343} INFO -  at 90.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:20] {3166} INFO - iteration 347, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:20] {3343} INFO -  at 90.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:20] {3166} INFO - iteration 348, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:21] {3343} INFO -  at 91.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:21] {3166} INFO - iteration 349, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:21] {3343} INFO -  at 91.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:21] {3166} INFO - iteration 350, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:21] {3343} INFO -  at 91.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:21] {3166} INFO - iteration 351, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:21] {3343} INFO -  at 91.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:21] {3166} INFO - iteration 352, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:22] {3343} INFO -  at 91.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:22] {3166} INFO - iteration 353, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:22] {3343} INFO -  at 92.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712

[flaml.automl: 04-23 11:26:22] {3166} INFO - iteration 354, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:22] {3343} INFO -  at 92.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:22] {3166} INFO - iteration 355, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:22] {3343} INFO -  at 92.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:22] {3166} INFO - iteration 356, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:22] {3343} INFO -  at 92.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:22] {3166} INFO - iteration 357, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:22] {3343} INFO -  at 92.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:22] {3166} INFO - iteration 358, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:23] {3343} INFO -  at 93.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:23] {3166} INFO - iteration 359, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:23] {3343} INFO -  at 93.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:23] {3166} INFO - iteration 360, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:23] {3343} INFO -  at 93.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:23] {3166} INFO - iteration 361, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:23] {3343} INFO -  at 93.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:23] {3166} INFO - iteration 362, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:23] {3343} INFO -  at 93.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:23] {3166} INFO - iteration 363, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:23] {3343} INFO -  at 93.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:23] {3166} INFO - iteration 364, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:24] {3343} INFO -  at 94.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:24] {3166} INFO - iteration 365, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:24] {3343} INFO -  at 94.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:24] {3166} INFO - iteration 366, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:24] {3343} INFO -  at 94.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:24] {3166} INFO - iteration 367, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:24] {3343} INFO -  at 94.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:24] {3166} INFO - iteration 368, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:25] {3343} INFO -  at 94.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:25] {3166} INFO - iteration 369, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:25] {3343} INFO -  at 95.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:25] {3166} INFO - iteration 370, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:25] {3343} INFO -  at 95.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:25] {3166} INFO - iteration 371, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:25] {3343} INFO -  at 95.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:25] {3166} INFO - iteration 372, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:25] {3343} INFO -  at 95.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:25] {3166} INFO - iteration 373, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:26] {3343} INFO -  at 96.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:26] {3166} INFO - iteration 374, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:26] {3343} INFO -  at 96.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:26] {3166} INFO - iteration 375, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:26] {3343} INFO -  at 96.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:26] {3166} INFO - iteration 376, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:27] {3343} INFO -  at 97.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:27] {3166} INFO - iteration 377, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:27] {3343} INFO -  at 97.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:27] {3166} INFO - iteration 378, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:27] {3343} INFO -  at 97.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:27] {3166} INFO - iteration 379, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:27] {3343} INFO -  at 97.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:27] {3166} INFO - iteration 380, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:28] {3343} INFO -  at 98.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:28] {3166} INFO - iteration 381, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:28] {3343} INFO -  at 98.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:28] {3166} INFO - iteration 382, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:28] {3343} INFO -  at 98.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:28] {3166} INFO - iteration 383, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:28] {3343} INFO -  at 98.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:28] {3166} INFO - iteration 384, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:29] {3343} INFO -  at 99.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:29] {3166} INFO - iteration 385, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:29] {3343} INFO -  at 99.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:29] {3166} INFO - iteration 386, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:29] {3343} INFO -  at 99.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:29] {3166} INFO - iteration 387, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:29] {3343} INFO -  at 99.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:29] {3166} INFO - iteration 388, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:30] {3343} INFO -  at 100.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:30] {3166} INFO - iteration 389, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:30] {3343} INFO -  at 100.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:30] {3166} INFO - iteration 390, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:30] {3343} INFO -  at 100.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:30] {3166} INFO - iteration 391, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:30] {3343} INFO -  at 100.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:30] {3166} INFO - iteration 392, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:31] {3343} INFO -  at 101.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:31] {3166} INFO - iteration 393, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:31] {3343} INFO -  at 101.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:31] {3166} INFO - iteration 394, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:31] {3343} INFO -  at 101.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:31] {3166} INFO - iteration 395, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:32] {3343} INFO -  at 102.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:32] {3166} INFO - iteration 396, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:32] {3343} INFO -  at 102.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:32] {3166} INFO - iteration 397, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:32] {3343} INFO -  at 102.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:32] {3166} INFO - iteration 398, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:32] {3343} INFO -  at 102.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:32] {3166} INFO - iteration 399, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:33] {3343} INFO -  at 103.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:33] {3166} INFO - iteration 400, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:33] {3343} INFO -  at 103.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:33] {3166} INFO - iteration 401, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:33] {3343} INFO -  at 103.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:33] {3166} INFO - iteration 402, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:33] {3343} INFO -  at 103.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:33] {3166} INFO - iteration 403, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:34] {3343} INFO -  at 104.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:34] {3166} INFO - iteration 404, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:34] {3343} INFO -  at 104.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:34] {3166} INFO - iteration 405, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:34] {3343} INFO -  at 104.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:34] {3166} INFO - iteration 406, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:34] {3343} INFO -  at 104.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:34] {3166} INFO - iteration 407, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:35] {3343} INFO -  at 105.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:35] {3166} INFO - iteration 408, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:35] {3343} INFO -  at 105.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:35] {3166} INFO - iteration 409, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:35] {3343} INFO -  at 105.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:35] {3166} INFO - iteration 410, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:35] {3343} INFO -  at 105.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:35] {3166} INFO - iteration 411, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:36] {3343} INFO -  at 106.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:36] {3166} INFO - iteration 412, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:36] {3343} INFO -  at 106.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:36] {3166} INFO - iteration 413, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:36] {3343} INFO -  at 106.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:36] {3166} INFO - iteration 414, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:36] {3343} INFO -  at 106.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:36] {3166} INFO - iteration 415, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:37] {3343} INFO -  at 107.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:37] {3166} INFO - iteration 416, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:37] {3343} INFO -  at 107.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:37] {3166} INFO - iteration 417, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:37] {3343} INFO -  at 107.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:37] {3166} INFO - iteration 418, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:38] {3343} INFO -  at 108.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:38] {3166} INFO - iteration 419, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:38] {3343} INFO -  at 108.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:38] {3166} INFO - iteration 420, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:38] {3343} INFO -  at 108.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:38] {3166} INFO - iteration 421, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:38] {3343} INFO -  at 108.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:38] {3166} INFO - iteration 422, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:39] {3343} INFO -  at 108.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:39] {3166} INFO - iteration 423, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:39] {3343} INFO -  at 109.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:39] {3166} INFO - iteration 424, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:39] {3343} INFO -  at 109.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:39] {3166} INFO - iteration 425, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:39] {3343} INFO -  at 109.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:39] {3166} INFO - iteration 426, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:39] {3343} INFO -  at 109.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:39] {3166} INFO - iteration 427, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:40] {3343} INFO -  at 110.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:40] {3166} INFO - iteration 428, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:40] {3343} INFO -  at 110.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:40] {3166} INFO - iteration 429, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:40] {3343} INFO -  at 110.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:40] {3166} INFO - iteration 430, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:40] {3343} INFO -  at 110.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:40] {3166} INFO - iteration 431, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:40] {3343} INFO -  at 110.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:40] {3166} INFO - iteration 432, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:41] {3343} INFO -  at 111.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:41] {3166} INFO - iteration 433, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:41] {3343} INFO -  at 111.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:41] {3166} INFO - iteration 434, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:41] {3343} INFO -  at 111.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:41] {3166} INFO - iteration 435, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:41] {3343} INFO -  at 111.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:41] {3166} INFO - iteration 436, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:41] {3343} INFO -  at 111.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:41] {3166} INFO - iteration 437, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:41] {3343} INFO -  at 111.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:41] {3166} INFO - iteration 438, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:42] {3343} INFO -  at 112.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:42] {3166} INFO - iteration 439, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:42] {3343} INFO -  at 112.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:42] {3166} INFO - iteration 440, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:42] {3343} INFO -  at 112.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:42] {3166} INFO - iteration 441, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:42] {3343} INFO -  at 112.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:42] {3166} INFO - iteration 442, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:42] {3343} INFO -  at 112.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:42] {3166} INFO - iteration 443, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:42] {3343} INFO -  at 112.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:42] {3166} INFO - iteration 444, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:43] {3343} INFO -  at 113.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:43] {3166} INFO - iteration 445, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:43] {3343} INFO -  at 113.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:43] {3166} INFO - iteration 446, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:43] {3343} INFO -  at 113.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:43] {3166} INFO - iteration 447, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:43] {3343} INFO -  at 113.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:43] {3166} INFO - iteration 448, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:43] {3343} INFO -  at 113.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:43] {3166} INFO - iteration 449, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:44] {3343} INFO -  at 114.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:44] {3166} INFO - iteration 450, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:44] {3343} INFO -  at 114.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:44] {3166} INFO - iteration 451, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:44] {3343} INFO -  at 114.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:44] {3166} INFO - iteration 452, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:44] {3343} INFO -  at 114.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:44] {3166} INFO - iteration 453, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:44] {3343} INFO -  at 114.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:44] {3166} INFO - iteration 454, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:44] {3343} INFO -  at 114.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:44] {3166} INFO - iteration 455, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:45] {3343} INFO -  at 115.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:45] {3166} INFO - iteration 456, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:45] {3343} INFO -  at 115.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:45] {3166} INFO - iteration 457, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:45] {3343} INFO -  at 115.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:45] {3166} INFO - iteration 458, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:45] {3343} INFO -  at 115.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:45] {3166} INFO - iteration 459, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:45] {3343} INFO -  at 115.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:45] {3166} INFO - iteration 460, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:46] {3343} INFO -  at 116.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:46] {3166} INFO - iteration 461, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:46] {3343} INFO -  at 116.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:46] {3166} INFO - iteration 462, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:46] {3343} INFO -  at 116.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:46] {3166} INFO - iteration 463, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:46] {3343} INFO -  at 116.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:46] {3166} INFO - iteration 464, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:46] {3343} INFO -  at 116.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:46] {3166} INFO - iteration 465, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:46] {3343} INFO -  at 116.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:46] {3166} INFO - iteration 466, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:47] {3343} INFO -  at 117.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:47] {3166} INFO - iteration 467, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:47] {3343} INFO -  at 117.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:47] {3166} INFO - iteration 468, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:47] {3343} INFO -  at 117.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:47] {3166} INFO - iteration 469, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:47] {3343} INFO -  at 117.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:47] {3166} INFO - iteration 470, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:47] {3343} INFO -  at 117.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:47] {3166} INFO - iteration 471, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:47] {3343} INFO -  at 117.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:47] {3166} INFO - iteration 472, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:48] {3343} INFO -  at 118.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:48] {3166} INFO - iteration 473, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:48] {3343} INFO -  at 118.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:48] {3166} INFO - iteration 474, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:48] {3343} INFO -  at 118.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:48] {3166} INFO - iteration 475, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:48] {3343} INFO -  at 118.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:48] {3166} INFO - iteration 476, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:48] {3343} INFO -  at 118.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:48] {3166} INFO - iteration 477, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:48] {3343} INFO -  at 118.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:48] {3166} INFO - iteration 478, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:49] {3343} INFO -  at 119.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:49] {3166} INFO - iteration 479, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:49] {3343} INFO -  at 119.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:49] {3166} INFO - iteration 480, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:49] {3343} INFO -  at 119.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:49] {3166} INFO - iteration 481, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:49] {3343} INFO -  at 119.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:49] {3166} INFO - iteration 482, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:49] {3343} INFO -  at 119.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:49] {3166} INFO - iteration 483, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:49] {3343} INFO -  at 119.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:49] {3166} INFO - iteration 484, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:50] {3343} INFO -  at 120.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:50] {3166} INFO - iteration 485, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:50] {3343} INFO -  at 120.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:50] {3166} INFO - iteration 486, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:50] {3343} INFO -  at 120.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:50] {3166} INFO - iteration 487, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:50] {3343} INFO -  at 120.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:50] {3166} INFO - iteration 488, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:50] {3343} INFO -  at 120.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:50] {3166} INFO - iteration 489, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:51] {3343} INFO -  at 121.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:51] {3166} INFO - iteration 490, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:51] {3343} INFO -  at 121.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:51] {3166} INFO - iteration 491, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:51] {3343} INFO -  at 121.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:51] {3166} INFO - iteration 492, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:51] {3343} INFO -  at 121.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:51] {3166} INFO - iteration 493, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:52] {3343} INFO -  at 122.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:52] {3166} INFO - iteration 494, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:52] {3343} INFO -  at 122.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:52] {3166} INFO - iteration 495, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:52] {3343} INFO -  at 122.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:52] {3166} INFO - iteration 496, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:52] {3343} INFO -  at 122.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:52] {3166} INFO - iteration 497, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:53] {3343} INFO -  at 123.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:53] {3166} INFO - iteration 498, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:53] {3343} INFO -  at 123.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:53] {3166} INFO - iteration 499, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:53] {3343} INFO -  at 123.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:53] {3166} INFO - iteration 500, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:53] {3343} INFO -  at 123.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:53] {3166} INFO - iteration 501, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:53] {3343} INFO -  at 123.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:53] {3166} INFO - iteration 502, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:54] {3343} INFO -  at 124.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:54] {3166} INFO - iteration 503, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:54] {3343} INFO -  at 124.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:54] {3166} INFO - iteration 504, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:54] {3343} INFO -  at 124.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:54] {3166} INFO - iteration 505, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:54] {3343} INFO -  at 124.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:54] {3166} INFO - iteration 506, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:54] {3343} INFO -  at 124.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:54] {3166} INFO - iteration 507, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:54] {3343} INFO -  at 124.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:54] {3166} INFO - iteration 508, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:55] {3343} INFO -  at 125.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:55] {3166} INFO - iteration 509, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:55] {3343} INFO -  at 125.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:55] {3166} INFO - iteration 510, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:55] {3343} INFO -  at 125.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:55] {3166} INFO - iteration 511, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:55] {3343} INFO -  at 125.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:55] {3166} INFO - iteration 512, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:55] {3343} INFO -  at 125.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:55] {3166} INFO - iteration 513, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:55] {3343} INFO -  at 125.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:55] {3166} INFO - iteration 514, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:56] {3343} INFO -  at 126.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:56] {3166} INFO - iteration 515, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:56] {3343} INFO -  at 126.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:56] {3166} INFO - iteration 516, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:56] {3343} INFO -  at 126.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:56] {3166} INFO - iteration 517, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:56] {3343} INFO -  at 126.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:56] {3166} INFO - iteration 518, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:56] {3343} INFO -  at 126.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:56] {3166} INFO - iteration 519, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:56] {3343} INFO -  at 126.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:56] {3166} INFO - iteration 520, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:57] {3343} INFO -  at 127.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:57] {3166} INFO - iteration 521, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:57] {3343} INFO -  at 127.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:57] {3166} INFO - iteration 522, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:57] {3343} INFO -  at 127.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:57] {3166} INFO - iteration 523, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:57] {3343} INFO -  at 127.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:57] {3166} INFO - iteration 524, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:57] {3343} INFO -  at 127.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:57] {3166} INFO - iteration 525, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:57] {3343} INFO -  at 127.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:57] {3166} INFO - iteration 526, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:58] {3343} INFO -  at 128.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:58] {3166} INFO - iteration 527, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:58] {3343} INFO -  at 128.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:58] {3166} INFO - iteration 528, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:58] {3343} INFO -  at 128.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:58] {3166} INFO - iteration 529, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:58] {3343} INFO -  at 128.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:58] {3166} INFO - iteration 530, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:58] {3343} INFO -  at 128.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:58] {3166} INFO - iteration 531, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:58] {3343} INFO -  at 128.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:58] {3166} INFO - iteration 532, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:59] {3343} INFO -  at 129.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:59] {3166} INFO - iteration 533, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:59] {3343} INFO -  at 129.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:59] {3166} INFO - iteration 534, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:59] {3343} INFO -  at 129.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:59] {3166} INFO - iteration 535, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:26:59] {3343} INFO -  at 129.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:59] {3166} INFO - iteration 536, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:59] {3343} INFO -  at 129.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:59] {3166} INFO - iteration 537, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:26:59] {3343} INFO -  at 129.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:26:59] {3166} INFO - iteration 538, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:00] {3343} INFO -  at 130.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:00] {3166} INFO - iteration 539, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:00] {3343} INFO -  at 130.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:00] {3166} INFO - iteration 540, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:00] {3343} INFO -  at 130.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:00] {3166} INFO - iteration 541, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:00] {3343} INFO -  at 130.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:00] {3166} INFO - iteration 542, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:00] {3343} INFO -  at 130.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:00] {3166} INFO - iteration 543, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:00] {3343} INFO -  at 130.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:00] {3166} INFO - iteration 544, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:01] {3343} INFO -  at 131.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:01] {3166} INFO - iteration 545, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:01] {3343} INFO -  at 131.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:01] {3166} INFO - iteration 546, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:01] {3343} INFO -  at 131.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:01] {3166} INFO - iteration 547, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:01] {3343} INFO -  at 131.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:01] {3166} INFO - iteration 548, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:01] {3343} INFO -  at 131.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:01] {3166} INFO - iteration 549, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:01] {3343} INFO -  at 131.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:01] {3166} INFO - iteration 550, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:02] {3343} INFO -  at 132.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:02] {3166} INFO - iteration 551, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:02] {3343} INFO -  at 132.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:02] {3166} INFO - iteration 552, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:02] {3343} INFO -  at 132.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:02] {3166} INFO - iteration 553, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:02] {3343} INFO -  at 132.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:02] {3166} INFO - iteration 554, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:02] {3343} INFO -  at 132.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:02] {3166} INFO - iteration 555, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:02] {3343} INFO -  at 132.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:02] {3166} INFO - iteration 556, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:03] {3343} INFO -  at 133.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:03] {3166} INFO - iteration 557, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:03] {3343} INFO -  at 133.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:03] {3166} INFO - iteration 558, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:03] {3343} INFO -  at 133.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:03] {3166} INFO - iteration 559, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:03] {3343} INFO -  at 133.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:03] {3166} INFO - iteration 560, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:03] {3343} INFO -  at 133.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:03] {3166} INFO - iteration 561, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:03] {3343} INFO -  at 133.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:03] {3166} INFO - iteration 562, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:04] {3343} INFO -  at 134.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:04] {3166} INFO - iteration 563, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:04] {3343} INFO -  at 134.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:04] {3166} INFO - iteration 564, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:04] {3343} INFO -  at 134.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:04] {3166} INFO - iteration 565, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:04] {3343} INFO -  at 134.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:04] {3166} INFO - iteration 566, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:04] {3343} INFO -  at 134.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:04] {3166} INFO - iteration 567, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:04] {3343} INFO -  at 134.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:04] {3166} INFO - iteration 568, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:05] {3343} INFO -  at 134.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:05] {3166} INFO - iteration 569, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:05] {3343} INFO -  at 135.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:05] {3166} INFO - iteration 570, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:05] {3343} INFO -  at 135.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:05] {3166} INFO - iteration 571, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:05] {3343} INFO -  at 135.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:05] {3166} INFO - iteration 572, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:05] {3343} INFO -  at 135.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:05] {3166} INFO - iteration 573, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:05] {3343} INFO -  at 135.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:05] {3166} INFO - iteration 574, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:06] {3343} INFO -  at 135.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:06] {3166} INFO - iteration 575, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:06] {3343} INFO -  at 136.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:06] {3166} INFO - iteration 576, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:06] {3343} INFO -  at 136.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:06] {3166} INFO - iteration 577, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:06] {3343} INFO -  at 136.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:06] {3166} INFO - iteration 578, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:06] {3343} INFO -  at 136.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:06] {3166} INFO - iteration 579, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:06] {3343} INFO -  at 136.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:06] {3166} INFO - iteration 580, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:07] {3343} INFO -  at 136.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:07] {3166} INFO - iteration 581, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:07] {3343} INFO -  at 137.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:07] {3166} INFO - iteration 582, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:07] {3343} INFO -  at 137.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:07] {3166} INFO - iteration 583, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:07] {3343} INFO -  at 137.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:07] {3166} INFO - iteration 584, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:07] {3343} INFO -  at 137.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:07] {3166} INFO - iteration 585, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:07] {3343} INFO -  at 137.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:07] {3166} INFO - iteration 586, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:08] {3343} INFO -  at 137.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:08] {3166} INFO - iteration 587, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:08] {3343} INFO -  at 138.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:08] {3166} INFO - iteration 588, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:08] {3343} INFO -  at 138.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:08] {3166} INFO - iteration 589, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:08] {3343} INFO -  at 138.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:08] {3166} INFO - iteration 590, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:08] {3343} INFO -  at 138.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:08] {3166} INFO - iteration 591, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:08] {3343} INFO -  at 138.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:08] {3166} INFO - iteration 592, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:09] {3343} INFO -  at 139.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:09] {3166} INFO - iteration 593, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:09] {3343} INFO -  at 139.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:09] {3166} INFO - iteration 594, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:09] {3343} INFO -  at 139.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:09] {3166} INFO - iteration 595, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:09] {3343} INFO -  at 139.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:09] {3166} INFO - iteration 596, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:09] {3343} INFO -  at 139.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:09] {3166} INFO - iteration 597, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:09] {3343} INFO -  at 139.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:09] {3166} INFO - iteration 598, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:10] {3343} INFO -  at 139.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:10] {3166} INFO - iteration 599, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:10] {3343} INFO -  at 140.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:10] {3166} INFO - iteration 600, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:10] {3343} INFO -  at 140.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:10] {3166} INFO - iteration 601, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:10] {3343} INFO -  at 140.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:10] {3166} INFO - iteration 602, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:10] {3343} INFO -  at 140.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:10] {3166} INFO - iteration 603, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:10] {3343} INFO -  at 140.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:10] {3166} INFO - iteration 604, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:10] {3343} INFO -  at 140.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:10] {3166} INFO - iteration 605, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:11] {3343} INFO -  at 141.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:11] {3166} INFO - iteration 606, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:11] {3343} INFO -  at 141.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:11] {3166} INFO - iteration 607, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:11] {3343} INFO -  at 141.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:11] {3166} INFO - iteration 608, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:11] {3343} INFO -  at 141.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:11] {3166} INFO - iteration 609, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:11] {3343} INFO -  at 141.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:11] {3166} INFO - iteration 610, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:11] {3343} INFO -  at 141.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:11] {3166} INFO - iteration 611, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:12] {3343} INFO -  at 142.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:12] {3166} INFO - iteration 612, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:12] {3343} INFO -  at 142.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:12] {3166} INFO - iteration 613, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:12] {3343} INFO -  at 142.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:12] {3166} INFO - iteration 614, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:12] {3343} INFO -  at 142.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:12] {3166} INFO - iteration 615, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:12] {3343} INFO -  at 142.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:12] {3166} INFO - iteration 616, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:12] {3343} INFO -  at 142.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:12] {3166} INFO - iteration 617, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:13] {3343} INFO -  at 143.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:13] {3166} INFO - iteration 618, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:13] {3343} INFO -  at 143.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:13] {3166} INFO - iteration 619, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:13] {3343} INFO -  at 143.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:13] {3166} INFO - iteration 620, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:13] {3343} INFO -  at 143.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:13] {3166} INFO - iteration 621, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:13] {3343} INFO -  at 143.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:13] {3166} INFO - iteration 622, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:13] {3343} INFO -  at 143.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:13] {3166} INFO - iteration 623, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:14] {3343} INFO -  at 144.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:14] {3166} INFO - iteration 624, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:14] {3343} INFO -  at 144.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:14] {3166} INFO - iteration 625, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:14] {3343} INFO -  at 144.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:14] {3166} INFO - iteration 626, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:14] {3343} INFO -  at 144.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:14] {3166} INFO - iteration 627, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:14] {3343} INFO -  at 144.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:14] {3166} INFO - iteration 628, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:14] {3343} INFO -  at 144.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:14] {3166} INFO - iteration 629, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:15] {3343} INFO -  at 144.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:15] {3166} INFO - iteration 630, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:15] {3343} INFO -  at 145.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:15] {3166} INFO - iteration 631, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:15] {3343} INFO -  at 145.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:15] {3166} INFO - iteration 632, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:15] {3343} INFO -  at 145.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:15] {3166} INFO - iteration 633, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:15] {3343} INFO -  at 145.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:15] {3166} INFO - iteration 634, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:15] {3343} INFO -  at 145.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:15] {3166} INFO - iteration 635, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:15] {3343} INFO -  at 145.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:15] {3166} INFO - iteration 636, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:16] {3343} INFO -  at 146.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:16] {3166} INFO - iteration 637, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:16] {3343} INFO -  at 146.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:16] {3166} INFO - iteration 638, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:16] {3343} INFO -  at 146.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:16] {3166} INFO - iteration 639, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:16] {3343} INFO -  at 146.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:16] {3166} INFO - iteration 640, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:16] {3343} INFO -  at 146.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:16] {3166} INFO - iteration 641, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:16] {3343} INFO -  at 146.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:16] {3166} INFO - iteration 642, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:17] {3343} INFO -  at 147.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:17] {3166} INFO - iteration 643, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:17] {3343} INFO -  at 147.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:17] {3166} INFO - iteration 644, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:17] {3343} INFO -  at 147.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:17] {3166} INFO - iteration 645, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:17] {3343} INFO -  at 147.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:17] {3166} INFO - iteration 646, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:17] {3343} INFO -  at 147.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:17] {3166} INFO - iteration 647, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:17] {3343} INFO -  at 147.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:17] {3166} INFO - iteration 648, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:18] {3343} INFO -  at 148.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:18] {3166} INFO - iteration 649, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:18] {3343} INFO -  at 148.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:18] {3166} INFO - iteration 650, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:18] {3343} INFO -  at 148.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:18] {3166} INFO - iteration 651, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:18] {3343} INFO -  at 148.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:18] {3166} INFO - iteration 652, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:18] {3343} INFO -  at 148.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:18] {3166} INFO - iteration 653, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:18] {3343} INFO -  at 148.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:18] {3166} INFO - iteration 654, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:19] {3343} INFO -  at 148.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:19] {3166} INFO - iteration 655, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:19] {3343} INFO -  at 149.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:19] {3166} INFO - iteration 656, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:19] {3343} INFO -  at 149.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:19] {3166} INFO - iteration 657, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:19] {3343} INFO -  at 149.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:19] {3166} INFO - iteration 658, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:19] {3343} INFO -  at 149.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:19] {3166} INFO - iteration 659, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:19] {3343} INFO -  at 149.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:19] {3166} INFO - iteration 660, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:19] {3343} INFO -  at 149.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:19] {3166} INFO - iteration 661, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:20] {3343} INFO -  at 150.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:20] {3166} INFO - iteration 662, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:20] {3343} INFO -  at 150.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:20] {3166} INFO - iteration 663, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:20] {3343} INFO -  at 150.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:20] {3166} INFO - iteration 664, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:20] {3343} INFO -  at 150.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:20] {3166} INFO - iteration 665, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:20] {3343} INFO -  at 150.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:20] {3166} INFO - iteration 666, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:20] {3343} INFO -  at 150.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:20] {3166} INFO - iteration 667, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:21] {3343} INFO -  at 151.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:21] {3166} INFO - iteration 668, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:21] {3343} INFO -  at 151.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:21] {3166} INFO - iteration 669, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:21] {3343} INFO -  at 151.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:21] {3166} INFO - iteration 670, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:21] {3343} INFO -  at 151.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:21] {3166} INFO - iteration 671, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:21] {3343} INFO -  at 151.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:21] {3166} INFO - iteration 672, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:21] {3343} INFO -  at 151.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:21] {3166} INFO - iteration 673, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:22] {3343} INFO -  at 152.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:22] {3166} INFO - iteration 674, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:22] {3343} INFO -  at 152.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:22] {3166} INFO - iteration 675, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:22] {3343} INFO -  at 152.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:22] {3166} INFO - iteration 676, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:22] {3343} INFO -  at 152.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:22] {3166} INFO - iteration 677, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:22] {3343} INFO -  at 152.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:22] {3166} INFO - iteration 678, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:22] {3343} INFO -  at 152.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:22] {3166} INFO - iteration 679, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:23] {3343} INFO -  at 152.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:23] {3166} INFO - iteration 680, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:23] {3343} INFO -  at 153.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:23] {3166} INFO - iteration 681, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:23] {3343} INFO -  at 153.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:23] {3166} INFO - iteration 682, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:23] {3343} INFO -  at 153.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:23] {3166} INFO - iteration 683, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:23] {3343} INFO -  at 153.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:23] {3166} INFO - iteration 684, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:23] {3343} INFO -  at 153.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:23] {3166} INFO - iteration 685, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:23] {3343} INFO -  at 153.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:23] {3166} INFO - iteration 686, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:24] {3343} INFO -  at 154.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:24] {3166} INFO - iteration 687, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:24] {3343} INFO -  at 154.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:24] {3166} INFO - iteration 688, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:24] {3343} INFO -  at 154.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:24] {3166} INFO - iteration 689, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:24] {3343} INFO -  at 154.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:24] {3166} INFO - iteration 690, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:24] {3343} INFO -  at 154.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:24] {3166} INFO - iteration 691, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:25] {3343} INFO -  at 155.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:25] {3166} INFO - iteration 692, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:25] {3343} INFO -  at 155.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:25] {3166} INFO - iteration 693, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:25] {3343} INFO -  at 155.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:25] {3166} INFO - iteration 694, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:25] {3343} INFO -  at 155.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:25] {3166} INFO - iteration 695, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:25] {3343} INFO -  at 155.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:25] {3166} INFO - iteration 696, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:25] {3343} INFO -  at 155.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:25] {3166} INFO - iteration 697, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:26] {3343} INFO -  at 155.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:26] {3166} INFO - iteration 698, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:26] {3343} INFO -  at 156.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:26] {3166} INFO - iteration 699, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:26] {3343} INFO -  at 156.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:26] {3166} INFO - iteration 700, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:26] {3343} INFO -  at 156.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:26] {3166} INFO - iteration 701, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:26] {3343} INFO -  at 156.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:26] {3166} INFO - iteration 702, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:26] {3343} INFO -  at 156.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:26] {3166} INFO - iteration 703, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:27] {3343} INFO -  at 156.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:27] {3166} INFO - iteration 704, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:27] {3343} INFO -  at 157.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:27] {3166} INFO - iteration 705, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:27] {3343} INFO -  at 157.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:27] {3166} INFO - iteration 706, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:27] {3343} INFO -  at 157.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:27] {3166} INFO - iteration 707, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:27] {3343} INFO -  at 157.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:27] {3166} INFO - iteration 708, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:27] {3343} INFO -  at 157.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:27] {3166} INFO - iteration 709, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:28] {3343} INFO -  at 157.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:28] {3166} INFO - iteration 710, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:28] {3343} INFO -  at 158.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:28] {3166} INFO - iteration 711, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:28] {3343} INFO -  at 158.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:28] {3166} INFO - iteration 712, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:28] {3343} INFO -  at 158.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:28] {3166} INFO - iteration 713, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:28] {3343} INFO -  at 158.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:28] {3166} INFO - iteration 714, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:28] {3343} INFO -  at 158.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:28] {3166} INFO - iteration 715, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:29] {3343} INFO -  at 158.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:29] {3166} INFO - iteration 716, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:29] {3343} INFO -  at 159.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:29] {3166} INFO - iteration 717, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:29] {3343} INFO -  at 159.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:29] {3166} INFO - iteration 718, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:29] {3343} INFO -  at 159.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:29] {3166} INFO - iteration 719, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:29] {3343} INFO -  at 159.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:29] {3166} INFO - iteration 720, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:29] {3343} INFO -  at 159.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:29] {3166} INFO - iteration 721, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:29] {3343} INFO -  at 159.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:30] {3166} INFO - iteration 722, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:30] {3343} INFO -  at 160.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:30] {3166} INFO - iteration 723, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:30] {3343} INFO -  at 160.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:30] {3166} INFO - iteration 724, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:30] {3343} INFO -  at 160.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:30] {3166} INFO - iteration 725, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:30] {3343} INFO -  at 160.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:30] {3166} INFO - iteration 726, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:30] {3343} INFO -  at 160.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:30] {3166} INFO - iteration 727, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:30] {3343} INFO -  at 160.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:30] {3166} INFO - iteration 728, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:31] {3343} INFO -  at 161.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:31] {3166} INFO - iteration 729, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:31] {3343} INFO -  at 161.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:31] {3166} INFO - iteration 730, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:31] {3343} INFO -  at 161.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:31] {3166} INFO - iteration 731, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:31] {3343} INFO -  at 161.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:31] {3166} INFO - iteration 732, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:31] {3343} INFO -  at 161.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:31] {3166} INFO - iteration 733, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:31] {3343} INFO -  at 161.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:31] {3166} INFO - iteration 734, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:32] {3343} INFO -  at 161.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:32] {3166} INFO - iteration 735, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:32] {3343} INFO -  at 162.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:32] {3166} INFO - iteration 736, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:32] {3343} INFO -  at 162.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:32] {3166} INFO - iteration 737, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:32] {3343} INFO -  at 162.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:32] {3166} INFO - iteration 738, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:32] {3343} INFO -  at 162.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:32] {3166} INFO - iteration 739, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:32] {3343} INFO -  at 162.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:32] {3166} INFO - iteration 740, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:33] {3343} INFO -  at 162.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:33] {3166} INFO - iteration 741, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:33] {3343} INFO -  at 163.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:33] {3166} INFO - iteration 742, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:33] {3343} INFO -  at 163.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:33] {3166} INFO - iteration 743, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:33] {3343} INFO -  at 163.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:33] {3166} INFO - iteration 744, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:33] {3343} INFO -  at 163.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:33] {3166} INFO - iteration 745, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:33] {3343} INFO -  at 163.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:33] {3166} INFO - iteration 746, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:34] {3343} INFO -  at 163.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:34] {3166} INFO - iteration 747, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:34] {3343} INFO -  at 164.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:34] {3166} INFO - iteration 748, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:34] {3343} INFO -  at 164.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:34] {3166} INFO - iteration 749, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:34] {3343} INFO -  at 164.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:34] {3166} INFO - iteration 750, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:34] {3343} INFO -  at 164.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:34] {3166} INFO - iteration 751, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:34] {3343} INFO -  at 164.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:34] {3166} INFO - iteration 752, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:34] {3343} INFO -  at 164.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:34] {3166} INFO - iteration 753, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:35] {3343} INFO -  at 165.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:35] {3166} INFO - iteration 754, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:35] {3343} INFO -  at 165.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:35] {3166} INFO - iteration 755, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:35] {3343} INFO -  at 165.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:35] {3166} INFO - iteration 756, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:35] {3343} INFO -  at 165.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:35] {3166} INFO - iteration 757, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:35] {3343} INFO -  at 165.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:35] {3166} INFO - iteration 758, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:35] {3343} INFO -  at 165.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:35] {3166} INFO - iteration 759, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:36] {3343} INFO -  at 166.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:36] {3166} INFO - iteration 760, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:36] {3343} INFO -  at 166.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:36] {3166} INFO - iteration 761, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:36] {3343} INFO -  at 166.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:36] {3166} INFO - iteration 762, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:36] {3343} INFO -  at 166.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:36] {3166} INFO - iteration 763, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:36] {3343} INFO -  at 166.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:36] {3166} INFO - iteration 764, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:36] {3343} INFO -  at 166.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:36] {3166} INFO - iteration 765, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:37] {3343} INFO -  at 166.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:37] {3166} INFO - iteration 766, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:37] {3343} INFO -  at 167.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:37] {3166} INFO - iteration 767, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:37] {3343} INFO -  at 167.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:37] {3166} INFO - iteration 768, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:37] {3343} INFO -  at 167.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:37] {3166} INFO - iteration 769, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:37] {3343} INFO -  at 167.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:37] {3166} INFO - iteration 770, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:37] {3343} INFO -  at 167.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:37] {3166} INFO - iteration 771, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:37] {3343} INFO -  at 167.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:37] {3166} INFO - iteration 772, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:38] {3343} INFO -  at 168.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:38] {3166} INFO - iteration 773, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:38] {3343} INFO -  at 168.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:38] {3166} INFO - iteration 774, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:38] {3343} INFO -  at 168.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:38] {3166} INFO - iteration 775, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:38] {3343} INFO -  at 168.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:38] {3166} INFO - iteration 776, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:38] {3343} INFO -  at 168.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:38] {3166} INFO - iteration 777, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:38] {3343} INFO -  at 168.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:38] {3166} INFO - iteration 778, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:39] {3343} INFO -  at 169.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:39] {3166} INFO - iteration 779, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:39] {3343} INFO -  at 169.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:39] {3166} INFO - iteration 780, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:39] {3343} INFO -  at 169.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:39] {3166} INFO - iteration 781, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:39] {3343} INFO -  at 169.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:39] {3166} INFO - iteration 782, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:39] {3343} INFO -  at 169.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:39] {3166} INFO - iteration 783, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:39] {3343} INFO -  at 169.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:39] {3166} INFO - iteration 784, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:40] {3343} INFO -  at 170.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:40] {3166} INFO - iteration 785, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:40] {3343} INFO -  at 170.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:40] {3166} INFO - iteration 786, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:40] {3343} INFO -  at 170.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:40] {3166} INFO - iteration 787, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:40] {3343} INFO -  at 170.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:40] {3166} INFO - iteration 788, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:40] {3343} INFO -  at 170.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:40] {3166} INFO - iteration 789, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:40] {3343} INFO -  at 170.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:40] {3166} INFO - iteration 790, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:41] {3343} INFO -  at 171.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:41] {3166} INFO - iteration 791, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:41] {3343} INFO -  at 171.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:41] {3166} INFO - iteration 792, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:41] {3343} INFO -  at 171.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:41] {3166} INFO - iteration 793, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:41] {3343} INFO -  at 171.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:41] {3166} INFO - iteration 794, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:41] {3343} INFO -  at 171.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:41] {3166} INFO - iteration 795, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:41] {3343} INFO -  at 171.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:41] {3166} INFO - iteration 796, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:42] {3343} INFO -  at 172.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:42] {3166} INFO - iteration 797, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:42] {3343} INFO -  at 172.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:42] {3166} INFO - iteration 798, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:42] {3343} INFO -  at 172.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:42] {3166} INFO - iteration 799, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:42] {3343} INFO -  at 172.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:42] {3166} INFO - iteration 800, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:42] {3343} INFO -  at 172.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:42] {3166} INFO - iteration 801, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:42] {3343} INFO -  at 172.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:42] {3166} INFO - iteration 802, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:43] {3343} INFO -  at 172.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:43] {3166} INFO - iteration 803, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:43] {3343} INFO -  at 173.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:43] {3166} INFO - iteration 804, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:43] {3343} INFO -  at 173.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:43] {3166} INFO - iteration 805, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:43] {3343} INFO -  at 173.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:43] {3166} INFO - iteration 806, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:43] {3343} INFO -  at 173.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:43] {3166} INFO - iteration 807, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:43] {3343} INFO -  at 173.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:43] {3166} INFO - iteration 808, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:43] {3343} INFO -  at 173.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:43] {3166} INFO - iteration 809, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:44] {3343} INFO -  at 174.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:44] {3166} INFO - iteration 810, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:44] {3343} INFO -  at 174.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:44] {3166} INFO - iteration 811, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:44] {3343} INFO -  at 174.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:44] {3166} INFO - iteration 812, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:44] {3343} INFO -  at 174.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:44] {3166} INFO - iteration 813, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:44] {3343} INFO -  at 174.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:44] {3166} INFO - iteration 814, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:45] {3343} INFO -  at 174.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:45] {3166} INFO - iteration 815, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:45] {3343} INFO -  at 175.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:45] {3166} INFO - iteration 816, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:45] {3343} INFO -  at 175.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:45] {3166} INFO - iteration 817, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:45] {3343} INFO -  at 175.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:45] {3166} INFO - iteration 818, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:45] {3343} INFO -  at 175.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:45] {3166} INFO - iteration 819, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:45] {3343} INFO -  at 175.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:45] {3166} INFO - iteration 820, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:46] {3343} INFO -  at 175.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:46] {3166} INFO - iteration 821, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:46] {3343} INFO -  at 176.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:46] {3166} INFO - iteration 822, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:46] {3343} INFO -  at 176.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:46] {3166} INFO - iteration 823, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:46] {3343} INFO -  at 176.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:46] {3166} INFO - iteration 824, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:46] {3343} INFO -  at 176.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:46] {3166} INFO - iteration 825, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:46] {3343} INFO -  at 176.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:46] {3166} INFO - iteration 826, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:46] {3343} INFO -  at 176.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:46] {3166} INFO - iteration 827, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:47] {3343} INFO -  at 177.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:47] {3166} INFO - iteration 828, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:47] {3343} INFO -  at 177.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:47] {3166} INFO - iteration 829, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:47] {3343} INFO -  at 177.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:47] {3166} INFO - iteration 830, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:47] {3343} INFO -  at 177.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:47] {3166} INFO - iteration 831, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:47] {3343} INFO -  at 177.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:47] {3166} INFO - iteration 832, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:47] {3343} INFO -  at 177.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:47] {3166} INFO - iteration 833, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:48] {3343} INFO -  at 177.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:48] {3166} INFO - iteration 834, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:48] {3343} INFO -  at 178.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:48] {3166} INFO - iteration 835, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:48] {3343} INFO -  at 178.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:48] {3166} INFO - iteration 836, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:48] {3343} INFO -  at 178.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:48] {3166} INFO - iteration 837, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:48] {3343} INFO -  at 178.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:48] {3166} INFO - iteration 838, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:48] {3343} INFO -  at 178.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:48] {3166} INFO - iteration 839, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:49] {3343} INFO -  at 178.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:49] {3166} INFO - iteration 840, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:49] {3343} INFO -  at 179.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:49] {3166} INFO - iteration 841, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:49] {3343} INFO -  at 179.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:49] {3166} INFO - iteration 842, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:49] {3343} INFO -  at 179.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:49] {3166} INFO - iteration 843, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:49] {3343} INFO -  at 179.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:49] {3166} INFO - iteration 844, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:49] {3343} INFO -  at 179.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:49] {3166} INFO - iteration 845, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:49] {3343} INFO -  at 179.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:49] {3166} INFO - iteration 846, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:50] {3343} INFO -  at 180.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:50] {3166} INFO - iteration 847, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:50] {3343} INFO -  at 180.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:50] {3166} INFO - iteration 848, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:50] {3343} INFO -  at 180.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:50] {3166} INFO - iteration 849, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:50] {3343} INFO -  at 180.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:50] {3166} INFO - iteration 850, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:50] {3343} INFO -  at 180.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:50] {3166} INFO - iteration 851, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:50] {3343} INFO -  at 180.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:50] {3166} INFO - iteration 852, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:51] {3343} INFO -  at 181.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:51] {3166} INFO - iteration 853, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:51] {3343} INFO -  at 181.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:51] {3166} INFO - iteration 854, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:51] {3343} INFO -  at 181.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:51] {3166} INFO - iteration 855, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:51] {3343} INFO -  at 181.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:51] {3166} INFO - iteration 856, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:51] {3343} INFO -  at 181.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:51] {3166} INFO - iteration 857, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:51] {3343} INFO -  at 181.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:51] {3166} INFO - iteration 858, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:52] {3343} INFO -  at 181.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:52] {3166} INFO - iteration 859, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:52] {3343} INFO -  at 182.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:52] {3166} INFO - iteration 860, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:52] {3343} INFO -  at 182.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:52] {3166} INFO - iteration 861, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:52] {3343} INFO -  at 182.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:52] {3166} INFO - iteration 862, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:52] {3343} INFO -  at 182.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:52] {3166} INFO - iteration 863, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:52] {3343} INFO -  at 182.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:52] {3166} INFO - iteration 864, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:53] {3343} INFO -  at 182.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:53] {3166} INFO - iteration 865, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:53] {3343} INFO -  at 183.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:53] {3166} INFO - iteration 866, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:53] {3343} INFO -  at 183.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:53] {3166} INFO - iteration 867, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:53] {3343} INFO -  at 183.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:53] {3166} INFO - iteration 868, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:53] {3343} INFO -  at 183.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:53] {3166} INFO - iteration 869, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:53] {3343} INFO -  at 183.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:53] {3166} INFO - iteration 870, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:53] {3343} INFO -  at 183.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:53] {3166} INFO - iteration 871, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:54] {3343} INFO -  at 184.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:54] {3166} INFO - iteration 872, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:54] {3343} INFO -  at 184.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:54] {3166} INFO - iteration 873, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:54] {3343} INFO -  at 184.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712

[flaml.automl: 04-23 11:27:54] {3166} INFO - iteration 874, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:54] {3343} INFO -  at 184.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:54] {3166} INFO - iteration 875, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:54] {3343} INFO -  at 184.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:54] {3166} INFO - iteration 876, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:54] {3343} INFO -  at 184.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:54] {3166} INFO - iteration 877, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:55] {3343} INFO -  at 185.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:55] {3166} INFO - iteration 878, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:55] {3343} INFO -  at 185.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:55] {3166} INFO - iteration 879, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:55] {3343} INFO -  at 185.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:55] {3166} INFO - iteration 880, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:55] {3343} INFO -  at 185.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:55] {3166} INFO - iteration 881, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:55] {3343} INFO -  at 185.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:55] {3166} INFO - iteration 882, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:55] {3343} INFO -  at 185.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:55] {3166} INFO - iteration 883, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:56] {3343} INFO -  at 185.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:56] {3166} INFO - iteration 884, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:56] {3343} INFO -  at 186.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:56] {3166} INFO - iteration 885, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:56] {3343} INFO -  at 186.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:56] {3166} INFO - iteration 886, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:56] {3343} INFO -  at 186.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:56] {3166} INFO - iteration 887, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:56] {3343} INFO -  at 186.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:56] {3166} INFO - iteration 888, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:56] {3343} INFO -  at 186.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:56] {3166} INFO - iteration 889, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:56] {3343} INFO -  at 186.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:56] {3166} INFO - iteration 890, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:57] {3343} INFO -  at 187.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:57] {3166} INFO - iteration 891, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:57] {3343} INFO -  at 187.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:57] {3166} INFO - iteration 892, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:57] {3343} INFO -  at 187.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:57] {3166} INFO - iteration 893, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:57] {3343} INFO -  at 187.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:57] {3166} INFO - iteration 894, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:57] {3343} INFO -  at 187.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:57] {3166} INFO - iteration 895, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:57] {3343} INFO -  at 187.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:57] {3166} INFO - iteration 896, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:58] {3343} INFO -  at 188.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:58] {3166} INFO - iteration 897, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:58] {3343} INFO -  at 188.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:58] {3166} INFO - iteration 898, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:58] {3343} INFO -  at 188.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:58] {3166} INFO - iteration 899, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:27:58] {3343} INFO -  at 188.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:58] {3166} INFO - iteration 900, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:58] {3343} INFO -  at 188.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:58] {3166} INFO - iteration 901, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:58] {3343} INFO -  at 188.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:58] {3166} INFO - iteration 902, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:59] {3343} INFO -  at 188.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:59] {3166} INFO - iteration 903, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:59] {3343} INFO -  at 189.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:59] {3166} INFO - iteration 904, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:59] {3343} INFO -  at 189.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:59] {3166} INFO - iteration 905, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:59] {3343} INFO -  at 189.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:59] {3166} INFO - iteration 906, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:59] {3343} INFO -  at 189.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:59] {3166} INFO - iteration 907, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:27:59] {3343} INFO -  at 189.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:27:59] {3166} INFO - iteration 908, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:00] {3343} INFO -  at 190.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:00] {3166} INFO - iteration 909, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:00] {3343} INFO -  at 190.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:00] {3166} INFO - iteration 910, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:00] {3343} INFO -  at 190.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:00] {3166} INFO - iteration 911, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:00] {3343} INFO -  at 190.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:00] {3166} INFO - iteration 912, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:00] {3343} INFO -  at 190.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:00] {3166} INFO - iteration 913, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:00] {3343} INFO -  at 190.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:00] {3166} INFO - iteration 914, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:01] {3343} INFO -  at 191.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:01] {3166} INFO - iteration 915, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:01] {3343} INFO -  at 191.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:01] {3166} INFO - iteration 916, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:01] {3343} INFO -  at 191.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:01] {3166} INFO - iteration 917, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:01] {3343} INFO -  at 191.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:01] {3166} INFO - iteration 918, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:01] {3343} INFO -  at 191.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:01] {3166} INFO - iteration 919, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:01] {3343} INFO -  at 191.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:01] {3166} INFO - iteration 920, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:02] {3343} INFO -  at 192.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:02] {3166} INFO - iteration 921, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:02] {3343} INFO -  at 192.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:02] {3166} INFO - iteration 922, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:02] {3343} INFO -  at 192.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:02] {3166} INFO - iteration 923, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:02] {3343} INFO -  at 192.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:02] {3166} INFO - iteration 924, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:02] {3343} INFO -  at 192.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:02] {3166} INFO - iteration 925, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:03] {3343} INFO -  at 192.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:03] {3166} INFO - iteration 926, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:03] {3343} INFO -  at 193.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:03] {3166} INFO - iteration 927, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:03] {3343} INFO -  at 193.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:03] {3166} INFO - iteration 928, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:03] {3343} INFO -  at 193.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:03] {3166} INFO - iteration 929, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:03] {3343} INFO -  at 193.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:03] {3166} INFO - iteration 930, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:04] {3343} INFO -  at 194.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:04] {3166} INFO - iteration 931, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:04] {3343} INFO -  at 194.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:04] {3166} INFO - iteration 932, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:04] {3343} INFO -  at 194.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:04] {3166} INFO - iteration 933, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:04] {3343} INFO -  at 194.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:04] {3166} INFO - iteration 934, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:05] {3343} INFO -  at 194.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:05] {3166} INFO - iteration 935, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:05] {3343} INFO -  at 195.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:05] {3166} INFO - iteration 936, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:05] {3343} INFO -  at 195.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:05] {3166} INFO - iteration 937, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:05] {3343} INFO -  at 195.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:05] {3166} INFO - iteration 938, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:06] {3343} INFO -  at 195.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:06] {3166} INFO - iteration 939, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:06] {3343} INFO -  at 196.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:06] {3166} INFO - iteration 940, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:06] {3343} INFO -  at 196.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:06] {3166} INFO - iteration 941, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:06] {3343} INFO -  at 196.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:06] {3166} INFO - iteration 942, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:06] {3343} INFO -  at 196.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:06] {3166} INFO - iteration 943, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:06] {3343} INFO -  at 196.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:06] {3166} INFO - iteration 944, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:07] {3343} INFO -  at 197.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:07] {3166} INFO - iteration 945, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:07] {3343} INFO -  at 197.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:07] {3166} INFO - iteration 946, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:07] {3343} INFO -  at 197.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:07] {3166} INFO - iteration 947, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:07] {3343} INFO -  at 197.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:07] {3166} INFO - iteration 948, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:07] {3343} INFO -  at 197.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:07] {3166} INFO - iteration 949, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:07] {3343} INFO -  at 197.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:07] {3166} INFO - iteration 950, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:08] {3343} INFO -  at 198.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:08] {3166} INFO - iteration 951, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:08] {3343} INFO -  at 198.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:08] {3166} INFO - iteration 952, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:08] {3343} INFO -  at 198.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:08] {3166} INFO - iteration 953, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:08] {3343} INFO -  at 198.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:08] {3166} INFO - iteration 954, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:09] {3343} INFO -  at 198.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:09] {3166} INFO - iteration 955, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:09] {3343} INFO -  at 199.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:09] {3166} INFO - iteration 956, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:09] {3343} INFO -  at 199.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:09] {3166} INFO - iteration 957, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:09] {3343} INFO -  at 199.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:09] {3166} INFO - iteration 958, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:10] {3343} INFO -  at 200.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:10] {3166} INFO - iteration 959, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:10] {3343} INFO -  at 200.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:10] {3166} INFO - iteration 960, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:10] {3343} INFO -  at 200.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:10] {3166} INFO - iteration 961, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:10] {3343} INFO -  at 200.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:10] {3166} INFO - iteration 962, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:11] {3343} INFO -  at 201.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:11] {3166} INFO - iteration 963, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:11] {3343} INFO -  at 201.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:11] {3166} INFO - iteration 964, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:11] {3343} INFO -  at 201.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:11] {3166} INFO - iteration 965, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:11] {3343} INFO -  at 201.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:11] {3166} INFO - iteration 966, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:12] {3343} INFO -  at 202.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:12] {3166} INFO - iteration 967, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:12] {3343} INFO -  at 202.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:12] {3166} INFO - iteration 968, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:12] {3343} INFO -  at 202.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:12] {3166} INFO - iteration 969, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:12] {3343} INFO -  at 202.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:12] {3166} INFO - iteration 970, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:13] {3343} INFO -  at 203.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:13] {3166} INFO - iteration 971, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:13] {3343} INFO -  at 203.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:13] {3166} INFO - iteration 972, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:13] {3343} INFO -  at 203.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:13] {3166} INFO - iteration 973, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:13] {3343} INFO -  at 203.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:13] {3166} INFO - iteration 974, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:14] {3343} INFO -  at 204.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:14] {3166} INFO - iteration 975, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:14] {3343} INFO -  at 204.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:14] {3166} INFO - iteration 976, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:14] {3343} INFO -  at 204.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:14] {3166} INFO - iteration 977, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:14] {3343} INFO -  at 204.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:14] {3166} INFO - iteration 978, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:14] {3343} INFO -  at 204.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:14] {3166} INFO - iteration 979, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:14] {3343} INFO -  at 204.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:14] {3166} INFO - iteration 980, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:15] {3343} INFO -  at 205.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:15] {3166} INFO - iteration 981, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:15] {3343} INFO -  at 205.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:15] {3166} INFO - iteration 982, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:15] {3343} INFO -  at 205.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:15] {3166} INFO - iteration 983, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:15] {3343} INFO -  at 205.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:15] {3166} INFO - iteration 984, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:15] {3343} INFO -  at 205.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:15] {3166} INFO - iteration 985, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:16] {3343} INFO -  at 205.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:16] {3166} INFO - iteration 986, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:16] {3343} INFO -  at 206.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:16] {3166} INFO - iteration 987, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:16] {3343} INFO -  at 206.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:16] {3166} INFO - iteration 988, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:16] {3343} INFO -  at 206.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:16] {3166} INFO - iteration 989, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:16] {3343} INFO -  at 206.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:16] {3166} INFO - iteration 990, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:16] {3343} INFO -  at 206.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:16] {3166} INFO - iteration 991, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:17] {3343} INFO -  at 207.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:17] {3166} INFO - iteration 992, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:17] {3343} INFO -  at 207.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:17] {3166} INFO - iteration 993, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:17] {3343} INFO -  at 207.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:17] {3166} INFO - iteration 994, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:17] {3343} INFO -  at 207.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:17] {3166} INFO - iteration 995, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:17] {3343} INFO -  at 207.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:17] {3166} INFO - iteration 996, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:17] {3343} INFO -  at 207.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:17] {3166} INFO - iteration 997, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:18] {3343} INFO -  at 208.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:18] {3166} INFO - iteration 998, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:18] {3343} INFO -  at 208.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:18] {3166} INFO - iteration 999, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:18] {3343} INFO -  at 208.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:18] {3166} INFO - iteration 1000, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:18] {3343} INFO -  at 208.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:18] {3166} INFO - iteration 1001, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:18] {3343} INFO -  at 208.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:18] {3166} INFO - iteration 1002, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:19] {3343} INFO -  at 209.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:19] {3166} INFO - iteration 1003, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:19] {3343} INFO -  at 209.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:19] {3166} INFO - iteration 1004, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:19] {3343} INFO -  at 209.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:19] {3166} INFO - iteration 1005, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:19] {3343} INFO -  at 209.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:19] {3166} INFO - iteration 1006, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:20] {3343} INFO -  at 209.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:20] {3166} INFO - iteration 1007, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:20] {3343} INFO -  at 210.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:20] {3166} INFO - iteration 1008, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:20] {3343} INFO -  at 210.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:20] {3166} INFO - iteration 1009, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:20] {3343} INFO -  at 210.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:20] {3166} INFO - iteration 1010, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:20] {3343} INFO -  at 210.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:20] {3166} INFO - iteration 1011, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:21] {3343} INFO -  at 211.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:21] {3166} INFO - iteration 1012, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:21] {3343} INFO -  at 211.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:21] {3166} INFO - iteration 1013, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:21] {3343} INFO -  at 211.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:21] {3166} INFO - iteration 1014, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:22] {3343} INFO -  at 212.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:22] {3166} INFO - iteration 1015, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:22] {3343} INFO -  at 212.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:22] {3166} INFO - iteration 1016, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:22] {3343} INFO -  at 212.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:22] {3166} INFO - iteration 1017, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:23] {3343} INFO -  at 213.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:23] {3166} INFO - iteration 1018, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:23] {3343} INFO -  at 213.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:23] {3166} INFO - iteration 1019, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:23] {3343} INFO -  at 213.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:23] {3166} INFO - iteration 1020, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:24] {3343} INFO -  at 214.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:24] {3166} INFO - iteration 1021, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:24] {3343} INFO -  at 214.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:24] {3166} INFO - iteration 1022, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:24] {3343} INFO -  at 214.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:24] {3166} INFO - iteration 1023, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:25] {3343} INFO -  at 215.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:25] {3166} INFO - iteration 1024, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:25] {3343} INFO -  at 215.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:25] {3166} INFO - iteration 1025, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:25] {3343} INFO -  at 215.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:25] {3166} INFO - iteration 1026, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:25] {3343} INFO -  at 215.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:25] {3166} INFO - iteration 1027, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:26] {3343} INFO -  at 216.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:26] {3166} INFO - iteration 1028, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:26] {3343} INFO -  at 216.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:26] {3166} INFO - iteration 1029, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:26] {3343} INFO -  at 216.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:26] {3166} INFO - iteration 1030, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:27] {3343} INFO -  at 216.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:27] {3166} INFO - iteration 1031, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:27] {3343} INFO -  at 217.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:27] {3166} INFO - iteration 1032, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:27] {3343} INFO -  at 217.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:27] {3166} INFO - iteration 1033, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:27] {3343} INFO -  at 217.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:27] {3166} INFO - iteration 1034, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:27] {3343} INFO -  at 217.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:27] {3166} INFO - iteration 1035, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:28] {3343} INFO -  at 218.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:28] {3166} INFO - iteration 1036, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:28] {3343} INFO -  at 218.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:28] {3166} INFO - iteration 1037, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:28] {3343} INFO -  at 218.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:28] {3166} INFO - iteration 1038, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:28] {3343} INFO -  at 218.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:28] {3166} INFO - iteration 1039, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:29] {3343} INFO -  at 218.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:29] {3166} INFO - iteration 1040, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:29] {3343} INFO -  at 219.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:29] {3166} INFO - iteration 1041, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:29] {3343} INFO -  at 219.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:29] {3166} INFO - iteration 1042, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:29] {3343} INFO -  at 219.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:29] {3166} INFO - iteration 1043, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:30] {3343} INFO -  at 220.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:30] {3166} INFO - iteration 1044, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:30] {3343} INFO -  at 220.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:30] {3166} INFO - iteration 1045, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:30] {3343} INFO -  at 220.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:30] {3166} INFO - iteration 1046, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:30] {3343} INFO -  at 220.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:30] {3166} INFO - iteration 1047, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:31] {3343} INFO -  at 221.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:31] {3166} INFO - iteration 1048, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:31] {3343} INFO -  at 221.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:31] {3166} INFO - iteration 1049, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:31] {3343} INFO -  at 221.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:31] {3166} INFO - iteration 1050, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:31] {3343} INFO -  at 221.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:31] {3166} INFO - iteration 1051, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:31] {3343} INFO -  at 221.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:31] {3166} INFO - iteration 1052, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:31] {3343} INFO -  at 221.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:31] {3166} INFO - iteration 1053, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:32] {3343} INFO -  at 222.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:32] {3166} INFO - iteration 1054, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:32] {3343} INFO -  at 222.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:32] {3166} INFO - iteration 1055, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:32] {3343} INFO -  at 222.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712

[flaml.automl: 04-23 11:28:32] {3166} INFO - iteration 1056, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:32] {3343} INFO -  at 222.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:32] {3166} INFO - iteration 1057, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:33] {3343} INFO -  at 222.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:33] {3166} INFO - iteration 1058, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:33] {3343} INFO -  at 223.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:33] {3166} INFO - iteration 1059, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:33] {3343} INFO -  at 223.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:33] {3166} INFO - iteration 1060, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:33] {3343} INFO -  at 223.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:33] {3166} INFO - iteration 1061, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:33] {3343} INFO -  at 223.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:33] {3166} INFO - iteration 1062, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:33] {3343} INFO -  at 223.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:33] {3166} INFO - iteration 1063, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:34] {3343} INFO -  at 223.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:34] {3166} INFO - iteration 1064, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:34] {3343} INFO -  at 224.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:34] {3166} INFO - iteration 1065, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:34] {3343} INFO -  at 224.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:34] {3166} INFO - iteration 1066, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:34] {3343} INFO -  at 224.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:34] {3166} INFO - iteration 1067, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:34] {3343} INFO -  at 224.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:34] {3166} INFO - iteration 1068, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:34] {3343} INFO -  at 224.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:34] {3166} INFO - iteration 1069, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:35] {3343} INFO -  at 224.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:35] {3166} INFO - iteration 1070, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:35] {3343} INFO -  at 225.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:35] {3166} INFO - iteration 1071, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:35] {3343} INFO -  at 225.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:35] {3166} INFO - iteration 1072, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:35] {3343} INFO -  at 225.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:35] {3166} INFO - iteration 1073, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:35] {3343} INFO -  at 225.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:35] {3166} INFO - iteration 1074, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:35] {3343} INFO -  at 225.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:35] {3166} INFO - iteration 1075, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:36] {3343} INFO -  at 226.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:36] {3166} INFO - iteration 1076, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:36] {3343} INFO -  at 226.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:36] {3166} INFO - iteration 1077, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:36] {3343} INFO -  at 226.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:36] {3166} INFO - iteration 1078, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:36] {3343} INFO -  at 226.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:36] {3166} INFO - iteration 1079, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:36] {3343} INFO -  at 226.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:36] {3166} INFO - iteration 1080, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:36] {3343} INFO -  at 226.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:36] {3166} INFO - iteration 1081, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:37] {3343} INFO -  at 226.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:37] {3166} INFO - iteration 1082, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:37] {3343} INFO -  at 227.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:37] {3166} INFO - iteration 1083, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:37] {3343} INFO -  at 227.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:37] {3166} INFO - iteration 1084, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:37] {3343} INFO -  at 227.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:37] {3166} INFO - iteration 1085, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:37] {3343} INFO -  at 227.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:37] {3166} INFO - iteration 1086, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:37] {3343} INFO -  at 227.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:37] {3166} INFO - iteration 1087, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:37] {3343} INFO -  at 227.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:37] {3166} INFO - iteration 1088, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:38] {3343} INFO -  at 228.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:38] {3166} INFO - iteration 1089, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:38] {3343} INFO -  at 228.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:38] {3166} INFO - iteration 1090, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:38] {3343} INFO -  at 228.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:38] {3166} INFO - iteration 1091, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:38] {3343} INFO -  at 228.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:38] {3166} INFO - iteration 1092, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:38] {3343} INFO -  at 228.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:38] {3166} INFO - iteration 1093, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:38] {3343} INFO -  at 228.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:38] {3166} INFO - iteration 1094, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:39] {3343} INFO -  at 229.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:39] {3166} INFO - iteration 1095, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:39] {3343} INFO -  at 229.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:39] {3166} INFO - iteration 1096, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:39] {3343} INFO -  at 229.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:39] {3166} INFO - iteration 1097, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:39] {3343} INFO -  at 229.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:39] {3166} INFO - iteration 1098, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:39] {3343} INFO -  at 229.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:39] {3166} INFO - iteration 1099, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:39] {3343} INFO -  at 229.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:39] {3166} INFO - iteration 1100, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:40] {3343} INFO -  at 230.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:40] {3166} INFO - iteration 1101, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:40] {3343} INFO -  at 230.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:40] {3166} INFO - iteration 1102, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:40] {3343} INFO -  at 230.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:40] {3166} INFO - iteration 1103, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:40] {3343} INFO -  at 230.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:40] {3166} INFO - iteration 1104, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:40] {3343} INFO -  at 230.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:40] {3166} INFO - iteration 1105, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:40] {3343} INFO -  at 230.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:40] {3166} INFO - iteration 1106, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:41] {3343} INFO -  at 231.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:41] {3166} INFO - iteration 1107, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:41] {3343} INFO -  at 231.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:41] {3166} INFO - iteration 1108, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:41] {3343} INFO -  at 231.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:41] {3166} INFO - iteration 1109, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:41] {3343} INFO -  at 231.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:41] {3166} INFO - iteration 1110, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:41] {3343} INFO -  at 231.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:41] {3166} INFO - iteration 1111, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:41] {3343} INFO -  at 231.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:41] {3166} INFO - iteration 1112, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:42] {3343} INFO -  at 232.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:42] {3166} INFO - iteration 1113, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:42] {3343} INFO -  at 232.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:42] {3166} INFO - iteration 1114, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:42] {3343} INFO -  at 232.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:42] {3166} INFO - iteration 1115, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:42] {3343} INFO -  at 232.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:42] {3166} INFO - iteration 1116, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:42] {3343} INFO -  at 232.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:42] {3166} INFO - iteration 1117, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:43] {3343} INFO -  at 232.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:43] {3166} INFO - iteration 1118, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:43] {3343} INFO -  at 233.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:43] {3166} INFO - iteration 1119, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:43] {3343} INFO -  at 233.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:43] {3166} INFO - iteration 1120, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:43] {3343} INFO -  at 233.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:43] {3166} INFO - iteration 1121, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:43] {3343} INFO -  at 233.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:43] {3166} INFO - iteration 1122, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:43] {3343} INFO -  at 233.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:43] {3166} INFO - iteration 1123, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:44] {3343} INFO -  at 233.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:44] {3166} INFO - iteration 1124, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:44] {3343} INFO -  at 234.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:44] {3166} INFO - iteration 1125, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:44] {3343} INFO -  at 234.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:44] {3166} INFO - iteration 1126, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:44] {3343} INFO -  at 234.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:44] {3166} INFO - iteration 1127, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:44] {3343} INFO -  at 234.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:44] {3166} INFO - iteration 1128, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:44] {3343} INFO -  at 234.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:44] {3166} INFO - iteration 1129, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:45] {3343} INFO -  at 234.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:45] {3166} INFO - iteration 1130, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:45] {3343} INFO -  at 235.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:45] {3166} INFO - iteration 1131, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:45] {3343} INFO -  at 235.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:45] {3166} INFO - iteration 1132, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:45] {3343} INFO -  at 235.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:45] {3166} INFO - iteration 1133, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:45] {3343} INFO -  at 235.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:45] {3166} INFO - iteration 1134, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:45] {3343} INFO -  at 235.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:45] {3166} INFO - iteration 1135, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:46] {3343} INFO -  at 236.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:46] {3166} INFO - iteration 1136, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:46] {3343} INFO -  at 236.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:46] {3166} INFO - iteration 1137, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:46] {3343} INFO -  at 236.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:46] {3166} INFO - iteration 1138, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:46] {3343} INFO -  at 236.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:46] {3166} INFO - iteration 1139, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:46] {3343} INFO -  at 236.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:46] {3166} INFO - iteration 1140, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:47] {3343} INFO -  at 236.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:47] {3166} INFO - iteration 1141, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:47] {3343} INFO -  at 237.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:47] {3166} INFO - iteration 1142, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:47] {3343} INFO -  at 237.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:47] {3166} INFO - iteration 1143, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:47] {3343} INFO -  at 237.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:47] {3166} INFO - iteration 1144, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:48] {3343} INFO -  at 237.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:48] {3166} INFO - iteration 1145, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:48] {3343} INFO -  at 238.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:48] {3166} INFO - iteration 1146, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:48] {3343} INFO -  at 238.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:48] {3166} INFO - iteration 1147, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:48] {3343} INFO -  at 238.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:48] {3166} INFO - iteration 1148, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:48] {3343} INFO -  at 238.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:48] {3166} INFO - iteration 1149, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:49] {3343} INFO -  at 239.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:49] {3166} INFO - iteration 1150, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:49] {3343} INFO -  at 239.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:49] {3166} INFO - iteration 1151, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:49] {3343} INFO -  at 239.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:49] {3166} INFO - iteration 1152, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:49] {3343} INFO -  at 239.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:50] {3166} INFO - iteration 1153, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:50] {3343} INFO -  at 240.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:50] {3166} INFO - iteration 1154, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:50] {3343} INFO -  at 240.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:50] {3166} INFO - iteration 1155, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:50] {3343} INFO -  at 240.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:50] {3166} INFO - iteration 1156, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:50] {3343} INFO -  at 240.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:50] {3166} INFO - iteration 1157, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:50] {3343} INFO -  at 240.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:50] {3166} INFO - iteration 1158, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:51] {3343} INFO -  at 241.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:51] {3166} INFO - iteration 1159, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:51] {3343} INFO -  at 241.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:51] {3166} INFO - iteration 1160, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:51] {3343} INFO -  at 241.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:51] {3166} INFO - iteration 1161, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:51] {3343} INFO -  at 241.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:51] {3166} INFO - iteration 1162, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:52] {3343} INFO -  at 242.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:52] {3166} INFO - iteration 1163, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:52] {3343} INFO -  at 242.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:52] {3166} INFO - iteration 1164, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:52] {3343} INFO -  at 242.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:52] {3166} INFO - iteration 1165, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:52] {3343} INFO -  at 242.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:52] {3166} INFO - iteration 1166, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:53] {3343} INFO -  at 243.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:53] {3166} INFO - iteration 1167, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:53] {3343} INFO -  at 243.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:53] {3166} INFO - iteration 1168, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:53] {3343} INFO -  at 243.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:53] {3166} INFO - iteration 1169, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:53] {3343} INFO -  at 243.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:53] {3166} INFO - iteration 1170, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:54] {3343} INFO -  at 244.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:54] {3166} INFO - iteration 1171, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:54] {3343} INFO -  at 244.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:54] {3166} INFO - iteration 1172, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:54] {3343} INFO -  at 244.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:54] {3166} INFO - iteration 1173, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:54] {3343} INFO -  at 244.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:54] {3166} INFO - iteration 1174, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:54] {3343} INFO -  at 244.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:54] {3166} INFO - iteration 1175, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:55] {3343} INFO -  at 245.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:55] {3166} INFO - iteration 1176, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:55] {3343} INFO -  at 245.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:55] {3166} INFO - iteration 1177, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:55] {3343} INFO -  at 245.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:55] {3166} INFO - iteration 1178, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:55] {3343} INFO -  at 245.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:55] {3166} INFO - iteration 1179, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:55] {3343} INFO -  at 245.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:55] {3166} INFO - iteration 1180, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:56] {3343} INFO -  at 246.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:56] {3166} INFO - iteration 1181, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:56] {3343} INFO -  at 246.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:56] {3166} INFO - iteration 1182, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:56] {3343} INFO -  at 246.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:56] {3166} INFO - iteration 1183, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:56] {3343} INFO -  at 246.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:56] {3166} INFO - iteration 1184, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:57] {3343} INFO -  at 246.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:57] {3166} INFO - iteration 1185, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:28:57] {3343} INFO -  at 247.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:57] {3166} INFO - iteration 1186, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:57] {3343} INFO -  at 247.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:57] {3166} INFO - iteration 1187, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:57] {3343} INFO -  at 247.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:57] {3166} INFO - iteration 1188, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:57] {3343} INFO -  at 247.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:57] {3166} INFO - iteration 1189, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:58] {3343} INFO -  at 248.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:58] {3166} INFO - iteration 1190, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:58] {3343} INFO -  at 248.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:58] {3166} INFO - iteration 1191, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:58] {3343} INFO -  at 248.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:58] {3166} INFO - iteration 1192, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:58] {3343} INFO -  at 248.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:58] {3166} INFO - iteration 1193, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:58] {3343} INFO -  at 248.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:58] {3166} INFO - iteration 1194, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:59] {3343} INFO -  at 249.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:59] {3166} INFO - iteration 1195, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:59] {3343} INFO -  at 249.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:59] {3166} INFO - iteration 1196, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:59] {3343} INFO -  at 249.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:59] {3166} INFO - iteration 1197, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:28:59] {3343} INFO -  at 249.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:28:59] {3166} INFO - iteration 1198, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:00] {3343} INFO -  at 250.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:00] {3166} INFO - iteration 1199, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:00] {3343} INFO -  at 250.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:00] {3166} INFO - iteration 1200, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:00] {3343} INFO -  at 250.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:00] {3166} INFO - iteration 1201, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:00] {3343} INFO -  at 250.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:00] {3166} INFO - iteration 1202, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:00] {3343} INFO -  at 250.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:00] {3166} INFO - iteration 1203, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:01] {3343} INFO -  at 251.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:01] {3166} INFO - iteration 1204, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:01] {3343} INFO -  at 251.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:01] {3166} INFO - iteration 1205, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:01] {3343} INFO -  at 251.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:01] {3166} INFO - iteration 1206, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:01] {3343} INFO -  at 251.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:01] {3166} INFO - iteration 1207, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:01] {3343} INFO -  at 251.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:01] {3166} INFO - iteration 1208, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:02] {3343} INFO -  at 251.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:02] {3166} INFO - iteration 1209, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:02] {3343} INFO -  at 252.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:02] {3166} INFO - iteration 1210, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:02] {3343} INFO -  at 252.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:02] {3166} INFO - iteration 1211, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:02] {3343} INFO -  at 252.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:02] {3166} INFO - iteration 1212, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:02] {3343} INFO -  at 252.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:02] {3166} INFO - iteration 1213, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:02] {3343} INFO -  at 252.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:02] {3166} INFO - iteration 1214, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:03] {3343} INFO -  at 252.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:03] {3166} INFO - iteration 1215, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:03] {3343} INFO -  at 253.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:03] {3166} INFO - iteration 1216, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:03] {3343} INFO -  at 253.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:03] {3166} INFO - iteration 1217, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:03] {3343} INFO -  at 253.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:03] {3166} INFO - iteration 1218, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:03] {3343} INFO -  at 253.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:03] {3166} INFO - iteration 1219, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:03] {3343} INFO -  at 253.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:03] {3166} INFO - iteration 1220, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:04] {3343} INFO -  at 253.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:04] {3166} INFO - iteration 1221, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:04] {3343} INFO -  at 254.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:04] {3166} INFO - iteration 1222, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:04] {3343} INFO -  at 254.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:04] {3166} INFO - iteration 1223, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:04] {3343} INFO -  at 254.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:04] {3166} INFO - iteration 1224, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:04] {3343} INFO -  at 254.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712

[flaml.automl: 04-23 11:29:04] {3166} INFO - iteration 1225, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:05] {3343} INFO -  at 255.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:05] {3166} INFO - iteration 1226, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:05] {3343} INFO -  at 255.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:05] {3166} INFO - iteration 1227, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:05] {3343} INFO -  at 255.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:05] {3166} INFO - iteration 1228, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:05] {3343} INFO -  at 255.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:05] {3166} INFO - iteration 1229, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:05] {3343} INFO -  at 255.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:05] {3166} INFO - iteration 1230, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:06] {3343} INFO -  at 255.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:06] {3166} INFO - iteration 1231, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:06] {3343} INFO -  at 256.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:06] {3166} INFO - iteration 1232, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:06] {3343} INFO -  at 256.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:06] {3166} INFO - iteration 1233, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:06] {3343} INFO -  at 256.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:06] {3166} INFO - iteration 1234, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:07] {3343} INFO -  at 256.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:07] {3166} INFO - iteration 1235, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:07] {3343} INFO -  at 257.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:07] {3166} INFO - iteration 1236, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:07] {3343} INFO -  at 257.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:07] {3166} INFO - iteration 1237, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:07] {3343} INFO -  at 257.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:07] {3166} INFO - iteration 1238, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:08] {3343} INFO -  at 258.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:08] {3166} INFO - iteration 1239, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:08] {3343} INFO -  at 258.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:08] {3166} INFO - iteration 1240, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:08] {3343} INFO -  at 258.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:08] {3166} INFO - iteration 1241, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:09] {3343} INFO -  at 259.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:09] {3166} INFO - iteration 1242, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:09] {3343} INFO -  at 259.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:09] {3166} INFO - iteration 1243, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:09] {3343} INFO -  at 259.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:09] {3166} INFO - iteration 1244, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:09] {3343} INFO -  at 259.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:09] {3166} INFO - iteration 1245, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:10] {3343} INFO -  at 260.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:10] {3166} INFO - iteration 1246, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:10] {3343} INFO -  at 260.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:10] {3166} INFO - iteration 1247, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:10] {3343} INFO -  at 260.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:10] {3166} INFO - iteration 1248, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:11] {3343} INFO -  at 261.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:11] {3166} INFO - iteration 1249, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:11] {3343} INFO -  at 261.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:11] {3166} INFO - iteration 1250, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:11] {3343} INFO -  at 261.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:11] {3166} INFO - iteration 1251, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:12] {3343} INFO -  at 261.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:12] {3166} INFO - iteration 1252, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:12] {3343} INFO -  at 262.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:12] {3166} INFO - iteration 1253, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:12] {3343} INFO -  at 262.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:12] {3166} INFO - iteration 1254, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:12] {3343} INFO -  at 262.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:12] {3166} INFO - iteration 1255, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:12] {3343} INFO -  at 262.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:12] {3166} INFO - iteration 1256, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:13] {3343} INFO -  at 263.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:13] {3166} INFO - iteration 1257, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:13] {3343} INFO -  at 263.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:13] {3166} INFO - iteration 1258, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:13] {3343} INFO -  at 263.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:13] {3166} INFO - iteration 1259, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:13] {3343} INFO -  at 263.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:13] {3166} INFO - iteration 1260, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:14] {3343} INFO -  at 264.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:14] {3166} INFO - iteration 1261, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:14] {3343} INFO -  at 264.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:14] {3166} INFO - iteration 1262, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:14] {3343} INFO -  at 264.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:14] {3166} INFO - iteration 1263, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:14] {3343} INFO -  at 264.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:14] {3166} INFO - iteration 1264, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:15] {3343} INFO -  at 265.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:15] {3166} INFO - iteration 1265, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:15] {3343} INFO -  at 265.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:15] {3166} INFO - iteration 1266, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:15] {3343} INFO -  at 265.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:15] {3166} INFO - iteration 1267, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:15] {3343} INFO -  at 265.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:15] {3166} INFO - iteration 1268, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:16] {3343} INFO -  at 266.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:16] {3166} INFO - iteration 1269, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:16] {3343} INFO -  at 266.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:16] {3166} INFO - iteration 1270, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:16] {3343} INFO -  at 266.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:16] {3166} INFO - iteration 1271, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:16] {3343} INFO -  at 266.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:16] {3166} INFO - iteration 1272, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:17] {3343} INFO -  at 267.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:17] {3166} INFO - iteration 1273, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:17] {3343} INFO -  at 267.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:17] {3166} INFO - iteration 1274, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:17] {3343} INFO -  at 267.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:17] {3166} INFO - iteration 1275, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:17] {3343} INFO -  at 267.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:17] {3166} INFO - iteration 1276, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:18] {3343} INFO -  at 268.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:18] {3166} INFO - iteration 1277, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:18] {3343} INFO -  at 268.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:18] {3166} INFO - iteration 1278, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:18] {3343} INFO -  at 268.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:18] {3166} INFO - iteration 1279, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:18] {3343} INFO -  at 268.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:18] {3166} INFO - iteration 1280, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:19] {3343} INFO -  at 269.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:19] {3166} INFO - iteration 1281, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:19] {3343} INFO -  at 269.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:19] {3166} INFO - iteration 1282, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:19] {3343} INFO -  at 269.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:19] {3166} INFO - iteration 1283, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:19] {3343} INFO -  at 269.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:19] {3166} INFO - iteration 1284, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:20] {3343} INFO -  at 270.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:20] {3166} INFO - iteration 1285, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:20] {3343} INFO -  at 270.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:20] {3166} INFO - iteration 1286, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:20] {3343} INFO -  at 270.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:20] {3166} INFO - iteration 1287, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:20] {3343} INFO -  at 270.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:20] {3166} INFO - iteration 1288, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:21] {3343} INFO -  at 271.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:21] {3166} INFO - iteration 1289, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:21] {3343} INFO -  at 271.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:21] {3166} INFO - iteration 1290, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:21] {3343} INFO -  at 271.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:21] {3166} INFO - iteration 1291, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:21] {3343} INFO -  at 271.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:21] {3166} INFO - iteration 1292, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:22] {3343} INFO -  at 272.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:22] {3166} INFO - iteration 1293, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:22] {3343} INFO -  at 272.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:22] {3166} INFO - iteration 1294, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:22] {3343} INFO -  at 272.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:22] {3166} INFO - iteration 1295, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:22] {3343} INFO -  at 272.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:22] {3166} INFO - iteration 1296, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:23] {3343} INFO -  at 272.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:23] {3166} INFO - iteration 1297, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:23] {3343} INFO -  at 273.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:23] {3166} INFO - iteration 1298, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:23] {3343} INFO -  at 273.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:23] {3166} INFO - iteration 1299, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:23] {3343} INFO -  at 273.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:23] {3166} INFO - iteration 1300, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:23] {3343} INFO -  at 273.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:23] {3166} INFO - iteration 1301, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:24] {3343} INFO -  at 274.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:24] {3166} INFO - iteration 1302, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:24] {3343} INFO -  at 274.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:24] {3166} INFO - iteration 1303, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:24] {3343} INFO -  at 274.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:24] {3166} INFO - iteration 1304, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:24] {3343} INFO -  at 274.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:24] {3166} INFO - iteration 1305, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:25] {3343} INFO -  at 275.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:25] {3166} INFO - iteration 1306, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:25] {3343} INFO -  at 275.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:25] {3166} INFO - iteration 1307, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:25] {3343} INFO -  at 275.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:25] {3166} INFO - iteration 1308, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:25] {3343} INFO -  at 275.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:25] {3166} INFO - iteration 1309, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:26] {3343} INFO -  at 276.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:26] {3166} INFO - iteration 1310, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:26] {3343} INFO -  at 276.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:26] {3166} INFO - iteration 1311, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:26] {3343} INFO -  at 276.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:26] {3166} INFO - iteration 1312, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:26] {3343} INFO -  at 276.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:26] {3166} INFO - iteration 1313, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:27] {3343} INFO -  at 277.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:27] {3166} INFO - iteration 1314, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:27] {3343} INFO -  at 277.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:27] {3166} INFO - iteration 1315, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:27] {3343} INFO -  at 277.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:27] {3166} INFO - iteration 1316, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:27] {3343} INFO -  at 277.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:27] {3166} INFO - iteration 1317, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:28] {3343} INFO -  at 278.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:28] {3166} INFO - iteration 1318, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:28] {3343} INFO -  at 278.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:28] {3166} INFO - iteration 1319, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:28] {3343} INFO -  at 278.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:28] {3166} INFO - iteration 1320, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:28] {3343} INFO -  at 278.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:28] {3166} INFO - iteration 1321, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:29] {3343} INFO -  at 279.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:29] {3166} INFO - iteration 1322, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:29] {3343} INFO -  at 279.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:29] {3166} INFO - iteration 1323, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:29] {3343} INFO -  at 279.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:29] {3166} INFO - iteration 1324, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:29] {3343} INFO -  at 279.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:29] {3166} INFO - iteration 1325, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:30] {3343} INFO -  at 280.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:30] {3166} INFO - iteration 1326, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:30] {3343} INFO -  at 280.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:30] {3166} INFO - iteration 1327, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:30] {3343} INFO -  at 280.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:30] {3166} INFO - iteration 1328, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:30] {3343} INFO -  at 280.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:30] {3166} INFO - iteration 1329, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:31] {3343} INFO -  at 281.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:31] {3166} INFO - iteration 1330, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:31] {3343} INFO -  at 281.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:31] {3166} INFO - iteration 1331, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:31] {3343} INFO -  at 281.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:31] {3166} INFO - iteration 1332, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:31] {3343} INFO -  at 281.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:31] {3166} INFO - iteration 1333, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:32] {3343} INFO -  at 282.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:32] {3166} INFO - iteration 1334, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:32] {3343} INFO -  at 282.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:32] {3166} INFO - iteration 1335, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:32] {3343} INFO -  at 282.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:32] {3166} INFO - iteration 1336, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:33] {3343} INFO -  at 282.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:33] {3166} INFO - iteration 1337, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:33] {3343} INFO -  at 283.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:33] {3166} INFO - iteration 1338, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:33] {3343} INFO -  at 283.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:33] {3166} INFO - iteration 1339, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:33] {3343} INFO -  at 283.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:33] {3166} INFO - iteration 1340, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:33] {3343} INFO -  at 283.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:33] {3166} INFO - iteration 1341, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:34] {3343} INFO -  at 284.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:34] {3166} INFO - iteration 1342, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:34] {3343} INFO -  at 284.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:34] {3166} INFO - iteration 1343, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:34] {3343} INFO -  at 284.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:34] {3166} INFO - iteration 1344, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:34] {3343} INFO -  at 284.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:34] {3166} INFO - iteration 1345, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:35] {3343} INFO -  at 285.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:35] {3166} INFO - iteration 1346, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:35] {3343} INFO -  at 285.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:35] {3166} INFO - iteration 1347, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:35] {3343} INFO -  at 285.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:35] {3166} INFO - iteration 1348, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:35] {3343} INFO -  at 285.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:35] {3166} INFO - iteration 1349, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:36] {3343} INFO -  at 286.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:36] {3166} INFO - iteration 1350, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:36] {3343} INFO -  at 286.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:36] {3166} INFO - iteration 1351, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:36] {3343} INFO -  at 286.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:36] {3166} INFO - iteration 1352, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:36] {3343} INFO -  at 286.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:36] {3166} INFO - iteration 1353, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:37] {3343} INFO -  at 287.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:37] {3166} INFO - iteration 1354, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:37] {3343} INFO -  at 287.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:37] {3166} INFO - iteration 1355, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:37] {3343} INFO -  at 287.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:37] {3166} INFO - iteration 1356, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:37] {3343} INFO -  at 287.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:37] {3166} INFO - iteration 1357, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:38] {3343} INFO -  at 288.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:38] {3166} INFO - iteration 1358, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:38] {3343} INFO -  at 288.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:38] {3166} INFO - iteration 1359, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:38] {3343} INFO -  at 288.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:38] {3166} INFO - iteration 1360, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:38] {3343} INFO -  at 288.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:38] {3166} INFO - iteration 1361, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:39] {3343} INFO -  at 289.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:39] {3166} INFO - iteration 1362, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:39] {3343} INFO -  at 289.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:39] {3166} INFO - iteration 1363, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:39] {3343} INFO -  at 289.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:39] {3166} INFO - iteration 1364, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:39] {3343} INFO -  at 289.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:39] {3166} INFO - iteration 1365, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:40] {3343} INFO -  at 289.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:40] {3166} INFO - iteration 1366, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:40] {3343} INFO -  at 290.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:40] {3166} INFO - iteration 1367, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:40] {3343} INFO -  at 290.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:40] {3166} INFO - iteration 1368, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:40] {3343} INFO -  at 290.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:40] {3166} INFO - iteration 1369, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:40] {3343} INFO -  at 290.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:40] {3166} INFO - iteration 1370, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:41] {3343} INFO -  at 290.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:41] {3166} INFO - iteration 1371, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:41] {3343} INFO -  at 291.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:41] {3166} INFO - iteration 1372, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:41] {3343} INFO -  at 291.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:41] {3166} INFO - iteration 1373, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:41] {3343} INFO -  at 291.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:41] {3166} INFO - iteration 1374, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:41] {3343} INFO -  at 291.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:41] {3166} INFO - iteration 1375, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:41] {3343} INFO -  at 291.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:41] {3166} INFO - iteration 1376, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:42] {3343} INFO -  at 292.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:42] {3166} INFO - iteration 1377, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:42] {3343} INFO -  at 292.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:42] {3166} INFO - iteration 1378, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:42] {3343} INFO -  at 292.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:42] {3166} INFO - iteration 1379, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:42] {3343} INFO -  at 292.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:42] {3166} INFO - iteration 1380, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:43] {3343} INFO -  at 293.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:43] {3166} INFO - iteration 1381, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:43] {3343} INFO -  at 293.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:43] {3166} INFO - iteration 1382, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:43] {3343} INFO -  at 293.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:43] {3166} INFO - iteration 1383, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:43] {3343} INFO -  at 293.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:43] {3166} INFO - iteration 1384, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:43] {3343} INFO -  at 293.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:43] {3166} INFO - iteration 1385, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:44] {3343} INFO -  at 293.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:44] {3166} INFO - iteration 1386, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:44] {3343} INFO -  at 294.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:44] {3166} INFO - iteration 1387, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:44] {3343} INFO -  at 294.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:44] {3166} INFO - iteration 1388, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:44] {3343} INFO -  at 294.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:44] {3166} INFO - iteration 1389, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:44] {3343} INFO -  at 294.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:44] {3166} INFO - iteration 1390, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:45] {3343} INFO -  at 295.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:45] {3166} INFO - iteration 1391, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:45] {3343} INFO -  at 295.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:45] {3166} INFO - iteration 1392, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:45] {3343} INFO -  at 295.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:45] {3166} INFO - iteration 1393, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:45] {3343} INFO -  at 295.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:45] {3166} INFO - iteration 1394, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:45] {3343} INFO -  at 295.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:45] {3166} INFO - iteration 1395, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:46] {3343} INFO -  at 296.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:46] {3166} INFO - iteration 1396, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:46] {3343} INFO -  at 296.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:46] {3166} INFO - iteration 1397, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:46] {3343} INFO -  at 296.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:46] {3166} INFO - iteration 1398, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:46] {3343} INFO -  at 296.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:46] {3166} INFO - iteration 1399, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:46] {3343} INFO -  at 296.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:46] {3166} INFO - iteration 1400, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:47] {3343} INFO -  at 297.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:47] {3166} INFO - iteration 1401, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:47] {3343} INFO -  at 297.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:47] {3166} INFO - iteration 1402, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:47] {3343} INFO -  at 297.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:47] {3166} INFO - iteration 1403, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:47] {3343} INFO -  at 297.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:47] {3166} INFO - iteration 1404, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:47] {3343} INFO -  at 297.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:47] {3166} INFO - iteration 1405, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:48] {3343} INFO -  at 298.1s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:48] {3166} INFO - iteration 1406, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:48] {3343} INFO -  at 298.3s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712

[flaml.automl: 04-23 11:29:48] {3166} INFO - iteration 1407, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:48] {3343} INFO -  at 298.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:48] {3166} INFO - iteration 1408, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:48] {3343} INFO -  at 298.6s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:48] {3166} INFO - iteration 1409, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:48] {3343} INFO -  at 298.8s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:48] {3166} INFO - iteration 1410, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:49] {3343} INFO -  at 299.0s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:49] {3166} INFO - iteration 1411, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:49] {3343} INFO -  at 299.2s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:49] {3166} INFO - iteration 1412, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:49] {3343} INFO -  at 299.4s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:49] {3166} INFO - iteration 1413, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:49] {3343} INFO -  at 299.5s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:49] {3166} INFO - iteration 1414, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:49] {3343} INFO -  at 299.7s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:49] {3166} INFO - iteration 1415, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:49] {3343} INFO -  at 299.9s,	estimator rf's best error=80.2712,	best estimator rf's best error=80.2712
[flaml.automl: 04-23 11:29:50] {3602} INFO - retrain rf for 0.2s
[flaml.automl: 04-23 11:29:50] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.5541178286357259, max_leaf_nodes=740,
                      n_estimators=44, n_jobs=-1)
[flaml.automl: 04-23 11:29:50] {2901} INFO - fit succeeded
[flaml.automl: 04-23 11:29:50] {2902} INFO - Time taken to find the best model: 47.67833209037781
[flaml.automl: 04-23 11:29:50] {2599} INFO - task = regression
[flaml.automl: 04-23 11:29:50] {2601} INFO - Data split method: uniform
[flaml.automl: 04-23 11:29:50] {2604} INFO - Evaluation method: holdout
[flaml.automl: 04-23 11:29:50] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 04-23 11:29:50] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 04-23 11:29:50] {3166} INFO - iteration 0, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:50] {3296} INFO - Estimated sufficient time budget=355s. Estimated necessary time budget=0s.
[flaml.automl: 04-23 11:29:50] {3343} INFO -  at 0.1s,	estimator rf's best error=127.9134,	best estimator rf's best error=127.9134
[flaml.automl: 04-23 11:29:50] {3166} INFO - iteration 1, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:50] {3343} INFO -  at 0.1s,	estimator rf's best error=102.2450,	best estimator rf's best error=102.2450
[flaml.automl: 04-23 11:29:50] {3166} INFO - iteration 2, current learner rf

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:50] {3343} INFO -  at 0.1s,	estimator rf's best error=102.2450,	best estimator rf's best error=102.2450
[flaml.automl: 04-23 11:29:50] {3166} INFO - iteration 3, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

0.91 0.81 0.26

[flaml.automl: 04-23 11:29:50] {3343} INFO -  at 0.2s,	estimator rf's best error=87.5090,	best estimator rf's best error=87.5090
[flaml.automl: 04-23 11:29:50] {3166} INFO - iteration 4, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:50] {3343} INFO -  at 0.3s,	estimator rf's best error=83.4677,	best estimator rf's best error=83.4677
[flaml.automl: 04-23 11:29:50] {3166} INFO - iteration 5, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:50] {3343} INFO -  at 0.4s,	estimator rf's best error=83.4677,	best estimator rf's best error=83.4677
[flaml.automl: 04-23 11:29:50] {3166} INFO - iteration 6, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:50] {3343} INFO -  at 0.5s,	estimator rf's best error=83.4677,	best estimator rf's best error=83.4677
[flaml.automl: 04-23 11:29:50] {3166} INFO - iteration 7, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:50] {3343} INFO -  at 0.6s,	estimator rf's best error=83.4677,	best estimator rf's best error=83.4677
[flaml.automl: 04-23 11:29:50] {3166} INFO - iteration 8, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:50] {3343} INFO -  at 0.8s,	estimator rf's best error=80.9276,	best estimator rf's best error=80.9276
[flaml.automl: 04-23 11:29:50] {3166} INFO - iteration 9, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:51] {3343} INFO -  at 0.8s,	estimator rf's best error=80.9276,	best estimator rf's best error=80.9276
[flaml.automl: 04-23 11:29:51] {3166} INFO - iteration 10, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:51] {3343} INFO -  at 0.9s,	estimator rf's best error=80.9276,	best estimator rf's best error=80.9276
[flaml.automl: 04-23 11:29:51] {3166} INFO - iteration 11, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:51] {3343} INFO -  at 1.1s,	estimator rf's best error=80.9276,	best estimator rf's best error=80.9276
[flaml.automl: 04-23 11:29:51] {3166} INFO - iteration 12, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:51] {3343} INFO -  at 1.2s,	estimator rf's best error=80.9276,	best estimator rf's best error=80.9276
[flaml.automl: 04-23 11:29:51] {3166} INFO - iteration 13, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:51] {3343} INFO -  at 1.5s,	estimator rf's best error=80.9276,	best estimator rf's best error=80.9276
[flaml.automl: 04-23 11:29:51] {3166} INFO - iteration 14, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:51] {3343} INFO -  at 1.6s,	estimator rf's best error=80.9276,	best estimator rf's best error=80.9276
[flaml.automl: 04-23 11:29:51] {3166} INFO - iteration 15, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:51] {3343} INFO -  at 1.7s,	estimator rf's best error=78.0198,	best estimator rf's best error=78.0198
[flaml.automl: 04-23 11:29:51] {3166} INFO - iteration 16, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:52] {3343} INFO -  at 1.8s,	estimator rf's best error=78.0198,	best estimator rf's best error=78.0198
[flaml.automl: 04-23 11:29:52] {3166} INFO - iteration 17, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:52] {3343} INFO -  at 2.0s,	estimator rf's best error=78.0080,	best estimator rf's best error=78.0080
[flaml.automl: 04-23 11:29:52] {3166} INFO - iteration 18, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:52] {3343} INFO -  at 2.4s,	estimator rf's best error=78.0080,	best estimator rf's best error=78.0080
[flaml.automl: 04-23 11:29:52] {3166} INFO - iteration 19, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:52] {3343} INFO -  at 2.6s,	estimator rf's best error=78.0080,	best estimator rf's best error=78.0080
[flaml.automl: 04-23 11:29:52] {3166} INFO - iteration 20, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:53] {3343} INFO -  at 3.2s,	estimator rf's best error=78.0080,	best estimator rf's best error=78.0080
[flaml.automl: 04-23 11:29:53] {3166} INFO - iteration 21, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:53] {3343} INFO -  at 3.3s,	estimator rf's best error=78.0080,	best estimator rf's best error=78.0080
[flaml.automl: 04-23 11:29:53] {3166} INFO - iteration 22, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:53] {3343} INFO -  at 3.4s,	estimator rf's best error=78.0080,	best estimator rf's best error=78.0080
[flaml.automl: 04-23 11:29:53] {3166} INFO - iteration 23, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:54] {3343} INFO -  at 3.9s,	estimator rf's best error=78.0080,	best estimator rf's best error=78.0080
[flaml.automl: 04-23 11:29:54] {3166} INFO - iteration 24, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:54] {3343} INFO -  at 4.1s,	estimator rf's best error=78.0080,	best estimator rf's best error=78.0080
[flaml.automl: 04-23 11:29:54] {3166} INFO - iteration 25, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:54] {3343} INFO -  at 4.3s,	estimator rf's best error=78.0080,	best estimator rf's best error=78.0080
[flaml.automl: 04-23 11:29:54] {3166} INFO - iteration 26, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:54] {3343} INFO -  at 4.7s,	estimator rf's best error=77.0587,	best estimator rf's best error=77.0587
[flaml.automl: 04-23 11:29:54] {3166} INFO - iteration 27, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:55] {3343} INFO -  at 4.9s,	estimator rf's best error=77.0587,	best estimator rf's best error=77.0587
[flaml.automl: 04-23 11:29:55] {3166} INFO - iteration 28, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:55] {3343} INFO -  at 5.2s,	estimator rf's best error=77.0587,	best estimator rf's best error=77.0587
[flaml.automl: 04-23 11:29:55] {3166} INFO - iteration 29, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:29:55] {3343} INFO -  at 5.5s,	estimator rf's best error=77.0587,	best estimator rf's best error=77.0587
[flaml.automl: 04-23 11:29:55] {3166} INFO - iteration 30, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:55] {3343} INFO -  at 5.7s,	estimator rf's best error=77.0587,	best estimator rf's best error=77.0587
[flaml.automl: 04-23 11:29:55] {3166} INFO - iteration 31, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:56] {3343} INFO -  at 6.4s,	estimator rf's best error=77.0587,	best estimator rf's best error=77.0587
[flaml.automl: 04-23 11:29:56] {3166} INFO - iteration 32, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:56] {3343} INFO -  at 6.8s,	estimator rf's best error=77.0587,	best estimator rf's best error=77.0587
[flaml.automl: 04-23 11:29:56] {3166} INFO - iteration 33, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:57] {3343} INFO -  at 7.1s,	estimator rf's best error=77.0587,	best estimator rf's best error=77.0587
[flaml.automl: 04-23 11:29:57] {3166} INFO - iteration 34, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:58] {3343} INFO -  at 7.9s,	estimator rf's best error=77.0587,	best estimator rf's best error=77.0587
[flaml.automl: 04-23 11:29:58] {3166} INFO - iteration 35, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:58] {3343} INFO -  at 8.1s,	estimator rf's best error=77.0587,	best estimator rf's best error=77.0587
[flaml.automl: 04-23 11:29:58] {3166} INFO - iteration 36, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:58] {3343} INFO -  at 8.3s,	estimator rf's best error=77.0587,	best estimator rf's best error=77.0587
[flaml.automl: 04-23 11:29:58] {3166} INFO - iteration 37, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:59] {3343} INFO -  at 9.1s,	estimator rf's best error=77.0587,	best estimator rf's best error=77.0587
[flaml.automl: 04-23 11:29:59] {3166} INFO - iteration 38, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:29:59] {3343} INFO -  at 9.7s,	estimator rf's best error=76.8178,	best estimator rf's best error=76.8178
[flaml.automl: 04-23 11:29:59] {3166} INFO - iteration 39, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:00] {3343} INFO -  at 10.1s,	estimator rf's best error=76.8178,	best estimator rf's best error=76.8178
[flaml.automl: 04-23 11:30:00] {3166} INFO - iteration 40, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:01] {3343} INFO -  at 11.2s,	estimator rf's best error=76.8178,	best estimator rf's best error=76.8178
[flaml.automl: 04-23 11:30:01] {3166} INFO - iteration 41, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:01] {3343} INFO -  at 11.6s,	estimator rf's best error=76.8178,	best estimator rf's best error=76.8178
[flaml.automl: 04-23 11:30:01] {3166} INFO - iteration 42, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:02] {3343} INFO -  at 12.2s,	estimator rf's best error=76.2492,	best estimator rf's best error=76.2492
[flaml.automl: 04-23 11:30:02] {3166} INFO - iteration 43, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:03] {3343} INFO -  at 13.1s,	estimator rf's best error=76.2492,	best estimator rf's best error=76.2492
[flaml.automl: 04-23 11:30:03] {3166} INFO - iteration 44, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:03] {3343} INFO -  at 13.8s,	estimator rf's best error=76.2492,	best estimator rf's best error=76.2492
[flaml.automl: 04-23 11:30:03] {3166} INFO - iteration 45, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:04] {3343} INFO -  at 14.8s,	estimator rf's best error=76.2492,	best estimator rf's best error=76.2492
[flaml.automl: 04-23 11:30:04] {3166} INFO - iteration 46, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:06] {3343} INFO -  at 16.2s,	estimator rf's best error=76.2492,	best estimator rf's best error=76.2492
[flaml.automl: 04-23 11:30:06] {3166} INFO - iteration 47, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:06] {3343} INFO -  at 16.6s,	estimator rf's best error=76.2492,	best estimator rf's best error=76.2492
[flaml.automl: 04-23 11:30:06] {3166} INFO - iteration 48, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:07] {3343} INFO -  at 16.8s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:07] {3166} INFO - iteration 49, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:07] {3343} INFO -  at 17.4s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:07] {3166} INFO - iteration 50, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:08] {3343} INFO -  at 18.2s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:08] {3166} INFO - iteration 51, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:08] {3343} INFO -  at 18.4s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:08] {3166} INFO - iteration 52, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:08] {3343} INFO -  at 18.8s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:08] {3166} INFO - iteration 53, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:09] {3343} INFO -  at 18.9s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:09] {3166} INFO - iteration 54, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:09] {3343} INFO -  at 19.1s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:09] {3166} INFO - iteration 55, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:09] {3343} INFO -  at 19.6s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:09] {3166} INFO - iteration 56, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:10] {3343} INFO -  at 20.1s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:10] {3166} INFO - iteration 57, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:10] {3343} INFO -  at 20.3s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:10] {3166} INFO - iteration 58, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:10] {3343} INFO -  at 20.7s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:10] {3166} INFO - iteration 59, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:11] {3343} INFO -  at 20.9s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:11] {3166} INFO - iteration 60, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:11] {3343} INFO -  at 21.1s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:11] {3166} INFO - iteration 61, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:11] {3343} INFO -  at 21.4s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:11] {3166} INFO - iteration 62, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:12] {3343} INFO -  at 21.9s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:12] {3166} INFO - iteration 63, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:12] {3343} INFO -  at 22.1s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:12] {3166} INFO - iteration 64, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:12] {3343} INFO -  at 22.4s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:12] {3166} INFO - iteration 65, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:12] {3343} INFO -  at 22.7s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:12] {3166} INFO - iteration 66, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:13] {3343} INFO -  at 22.9s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:13] {3166} INFO - iteration 67, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:13] {3343} INFO -  at 23.2s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:13] {3166} INFO - iteration 68, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:13] {3343} INFO -  at 23.4s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:13] {3166} INFO - iteration 69, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:14] {3343} INFO -  at 23.9s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:14] {3166} INFO - iteration 70, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:14] {3343} INFO -  at 24.3s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:14] {3166} INFO - iteration 71, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:14] {3343} INFO -  at 24.6s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:14] {3166} INFO - iteration 72, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:15] {3343} INFO -  at 24.9s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:15] {3166} INFO - iteration 73, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:15] {3343} INFO -  at 25.4s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:15] {3166} INFO - iteration 74, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:15] {3343} INFO -  at 25.7s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:15] {3166} INFO - iteration 75, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:16] {3343} INFO -  at 26.0s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:16] {3166} INFO - iteration 76, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:16] {3343} INFO -  at 26.3s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:16] {3166} INFO - iteration 77, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:16] {3343} INFO -  at 26.6s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:16] {3166} INFO - iteration 78, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:17] {3343} INFO -  at 26.8s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:17] {3166} INFO - iteration 79, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:17] {3343} INFO -  at 27.3s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:17] {3166} INFO - iteration 80, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:17] {3343} INFO -  at 27.6s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:17] {3166} INFO - iteration 81, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:18] {3343} INFO -  at 28.0s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:18] {3166} INFO - iteration 82, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:18] {3343} INFO -  at 28.3s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:18] {3166} INFO - iteration 83, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:18] {3343} INFO -  at 28.5s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:18] {3166} INFO - iteration 84, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:18] {3343} INFO -  at 28.7s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:18] {3166} INFO - iteration 85, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:19] {3343} INFO -  at 29.2s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:19] {3166} INFO - iteration 86, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:19] {3343} INFO -  at 29.6s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:19] {3166} INFO - iteration 87, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:20] {3343} INFO -  at 29.8s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:20] {3166} INFO - iteration 88, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:20] {3343} INFO -  at 30.0s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:20] {3166} INFO - iteration 89, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:20] {3343} INFO -  at 30.3s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:20] {3166} INFO - iteration 90, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:20] {3343} INFO -  at 30.6s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:20] {3166} INFO - iteration 91, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:21] {3343} INFO -  at 30.9s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:21] {3166} INFO - iteration 92, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:21] {3343} INFO -  at 31.1s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:21] {3166} INFO - iteration 93, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:21] {3343} INFO -  at 31.4s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:21] {3166} INFO - iteration 94, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:21] {3343} INFO -  at 31.7s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:21] {3166} INFO - iteration 95, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:22] {3343} INFO -  at 32.0s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:22] {3166} INFO - iteration 96, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:22] {3343} INFO -  at 32.3s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:22] {3166} INFO - iteration 97, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:22] {3343} INFO -  at 32.5s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:22] {3166} INFO - iteration 98, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:22] {3343} INFO -  at 32.7s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:22] {3166} INFO - iteration 99, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:23] {3343} INFO -  at 33.1s,	estimator rf's best error=75.6772,	best estimator rf's best error=75.6772
[flaml.automl: 04-23 11:30:23] {3166} INFO - iteration 100, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:23] {3343} INFO -  at 33.2s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:23] {3166} INFO - iteration 101, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:23] {3343} INFO -  at 33.5s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:23] {3166} INFO - iteration 102, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:24] {3343} INFO -  at 33.9s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:24] {3166} INFO - iteration 103, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:24] {3343} INFO -  at 34.0s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:24] {3166} INFO - iteration 104, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:24] {3343} INFO -  at 34.3s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:24] {3166} INFO - iteration 105, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:24] {3343} INFO -  at 34.5s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:24] {3166} INFO - iteration 106, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:24] {3343} INFO -  at 34.7s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:24] {3166} INFO - iteration 107, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:25] {3343} INFO -  at 35.3s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:25] {3166} INFO - iteration 108, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:25] {3343} INFO -  at 35.6s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:25] {3166} INFO - iteration 109, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:26] {3343} INFO -  at 36.0s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:26] {3166} INFO - iteration 110, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:26] {3343} INFO -  at 36.3s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:26] {3166} INFO - iteration 111, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:26] {3343} INFO -  at 36.6s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:26] {3166} INFO - iteration 112, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:27] {3343} INFO -  at 36.9s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:27] {3166} INFO - iteration 113, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:27] {3343} INFO -  at 37.0s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:27] {3166} INFO - iteration 114, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:27] {3343} INFO -  at 37.2s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:27] {3166} INFO - iteration 115, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:27] {3343} INFO -  at 37.4s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:27] {3166} INFO - iteration 116, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:27] {3343} INFO -  at 37.6s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:27] {3166} INFO - iteration 117, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:28] {3343} INFO -  at 38.0s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:28] {3166} INFO - iteration 118, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:28] {3343} INFO -  at 38.1s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:28] {3166} INFO - iteration 119, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:28] {3343} INFO -  at 38.4s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:28] {3166} INFO - iteration 120, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:28] {3343} INFO -  at 38.7s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:28] {3166} INFO - iteration 121, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:29] {3343} INFO -  at 39.0s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:29] {3166} INFO - iteration 122, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:29] {3343} INFO -  at 39.3s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:29] {3166} INFO - iteration 123, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:29] {3343} INFO -  at 39.5s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:29] {3166} INFO - iteration 124, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:30] {3343} INFO -  at 39.8s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:30] {3166} INFO - iteration 125, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:30] {3343} INFO -  at 40.0s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:30] {3166} INFO - iteration 126, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:30] {3343} INFO -  at 40.1s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:30] {3166} INFO - iteration 127, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:30] {3343} INFO -  at 40.3s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:30] {3166} INFO - iteration 128, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:30] {3343} INFO -  at 40.5s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:30] {3166} INFO - iteration 129, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:31] {3343} INFO -  at 40.8s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:31] {3166} INFO - iteration 130, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:31] {3343} INFO -  at 41.1s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:31] {3166} INFO - iteration 131, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:31] {3343} INFO -  at 41.2s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:31] {3166} INFO - iteration 132, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:31] {3343} INFO -  at 41.4s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:31] {3166} INFO - iteration 133, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:31] {3343} INFO -  at 41.6s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451

[flaml.automl: 04-23 11:30:31] {3166} INFO - iteration 134, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:31] {3343} INFO -  at 41.7s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:31] {3166} INFO - iteration 135, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:32] {3343} INFO -  at 41.9s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:32] {3166} INFO - iteration 136, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:32] {3343} INFO -  at 42.2s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:32] {3166} INFO - iteration 137, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:32] {3343} INFO -  at 42.3s,	estimator rf's best error=75.5451,	best estimator rf's best error=75.5451
[flaml.automl: 04-23 11:30:32] {3166} INFO - iteration 138, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:32] {3343} INFO -  at 42.5s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:32] {3166} INFO - iteration 139, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:32] {3343} INFO -  at 42.7s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:32] {3166} INFO - iteration 140, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:33] {3343} INFO -  at 42.9s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:33] {3166} INFO - iteration 141, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:33] {3343} INFO -  at 43.0s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:33] {3166} INFO - iteration 142, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:33] {3343} INFO -  at 43.2s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:33] {3166} INFO - iteration 143, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:33] {3343} INFO -  at 43.4s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:33] {3166} INFO - iteration 144, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:33] {3343} INFO -  at 43.6s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:33] {3166} INFO - iteration 145, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:33] {3343} INFO -  at 43.7s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:33] {3166} INFO - iteration 146, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:34] {3343} INFO -  at 43.9s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:34] {3166} INFO - iteration 147, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:34] {3343} INFO -  at 44.1s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:34] {3166} INFO - iteration 148, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:34] {3343} INFO -  at 44.3s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:34] {3166} INFO - iteration 149, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:34] {3343} INFO -  at 44.5s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:34] {3166} INFO - iteration 150, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:34] {3343} INFO -  at 44.7s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:34] {3166} INFO - iteration 151, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:35] {3343} INFO -  at 44.8s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:35] {3166} INFO - iteration 152, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:35] {3343} INFO -  at 45.0s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:35] {3166} INFO - iteration 153, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:35] {3343} INFO -  at 45.2s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:35] {3166} INFO - iteration 154, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:35] {3343} INFO -  at 45.4s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:35] {3166} INFO - iteration 155, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:35] {3343} INFO -  at 45.5s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:35] {3166} INFO - iteration 156, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:35] {3343} INFO -  at 45.7s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:35] {3166} INFO - iteration 157, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:36] {3343} INFO -  at 45.9s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:36] {3166} INFO - iteration 158, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:36] {3343} INFO -  at 46.0s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:36] {3166} INFO - iteration 159, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:36] {3343} INFO -  at 46.3s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:36] {3166} INFO - iteration 160, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:36] {3343} INFO -  at 46.5s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:36] {3166} INFO - iteration 161, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:36] {3343} INFO -  at 46.6s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:36] {3166} INFO - iteration 162, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:37] {3343} INFO -  at 46.8s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:37] {3166} INFO - iteration 163, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:37] {3343} INFO -  at 47.0s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:37] {3166} INFO - iteration 164, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:37] {3343} INFO -  at 47.2s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:37] {3166} INFO - iteration 165, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:37] {3343} INFO -  at 47.3s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:37] {3166} INFO - iteration 166, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:37] {3343} INFO -  at 47.5s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:37] {3166} INFO - iteration 167, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:37] {3343} INFO -  at 47.7s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:37] {3166} INFO - iteration 168, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:38] {3343} INFO -  at 47.9s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:38] {3166} INFO - iteration 169, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:38] {3343} INFO -  at 48.0s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:38] {3166} INFO - iteration 170, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:38] {3343} INFO -  at 48.2s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:38] {3166} INFO - iteration 171, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:38] {3343} INFO -  at 48.4s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:38] {3166} INFO - iteration 172, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:38] {3343} INFO -  at 48.5s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901

[flaml.automl: 04-23 11:30:38] {3166} INFO - iteration 173, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:38] {3343} INFO -  at 48.7s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:38] {3166} INFO - iteration 174, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:39] {3343} INFO -  at 48.8s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:39] {3166} INFO - iteration 175, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:39] {3343} INFO -  at 49.0s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:39] {3166} INFO - iteration 176, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:39] {3343} INFO -  at 49.2s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:39] {3166} INFO - iteration 177, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:39] {3343} INFO -  at 49.4s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:39] {3166} INFO - iteration 178, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:39] {3343} INFO -  at 49.5s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:39] {3166} INFO - iteration 179, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:39] {3343} INFO -  at 49.7s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:39] {3166} INFO - iteration 180, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:40] {3343} INFO -  at 49.9s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:40] {3166} INFO - iteration 181, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:40] {3343} INFO -  at 50.0s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:40] {3166} INFO - iteration 182, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:40] {3343} INFO -  at 50.2s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:40] {3166} INFO - iteration 183, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:40] {3343} INFO -  at 50.4s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:40] {3166} INFO - iteration 184, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:40] {3343} INFO -  at 50.6s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:40] {3166} INFO - iteration 185, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:40] {3343} INFO -  at 50.7s,	estimator rf's best error=75.3901,	best estimator rf's best error=75.3901
[flaml.automl: 04-23 11:30:40] {3166} INFO - iteration 186, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:41] {3343} INFO -  at 50.9s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:41] {3166} INFO - iteration 187, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:41] {3343} INFO -  at 51.1s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:41] {3166} INFO - iteration 188, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:41] {3343} INFO -  at 51.3s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:41] {3166} INFO - iteration 189, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:41] {3343} INFO -  at 51.5s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:41] {3166} INFO - iteration 190, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:41] {3343} INFO -  at 51.7s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:41] {3166} INFO - iteration 191, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:42] {3343} INFO -  at 51.9s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:42] {3166} INFO - iteration 192, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:42] {3343} INFO -  at 52.0s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:42] {3166} INFO - iteration 193, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:42] {3343} INFO -  at 52.3s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:42] {3166} INFO - iteration 194, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:42] {3343} INFO -  at 52.5s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:42] {3166} INFO - iteration 195, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:42] {3343} INFO -  at 52.7s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:42] {3166} INFO - iteration 196, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:43] {3343} INFO -  at 52.9s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:43] {3166} INFO - iteration 197, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:43] {3343} INFO -  at 53.1s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:43] {3166} INFO - iteration 198, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:43] {3343} INFO -  at 53.4s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:43] {3166} INFO - iteration 199, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:43] {3343} INFO -  at 53.6s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:43] {3166} INFO - iteration 200, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:43] {3343} INFO -  at 53.7s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:43] {3166} INFO - iteration 201, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:44] {3343} INFO -  at 54.0s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:44] {3166} INFO - iteration 202, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:44] {3343} INFO -  at 54.1s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:44] {3166} INFO - iteration 203, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:44] {3343} INFO -  at 54.5s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:44] {3166} INFO - iteration 204, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:44] {3343} INFO -  at 54.7s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:44] {3166} INFO - iteration 205, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:45] {3343} INFO -  at 54.9s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:45] {3166} INFO - iteration 206, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:45] {3343} INFO -  at 55.1s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:45] {3166} INFO - iteration 207, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:45] {3343} INFO -  at 55.3s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:45] {3166} INFO - iteration 208, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:45] {3343} INFO -  at 55.5s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:45] {3166} INFO - iteration 209, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:45] {3343} INFO -  at 55.7s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:45] {3166} INFO - iteration 210, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:46] {3343} INFO -  at 55.9s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:46] {3166} INFO - iteration 211, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:46] {3343} INFO -  at 56.1s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743

[flaml.automl: 04-23 11:30:46] {3166} INFO - iteration 212, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:46] {3343} INFO -  at 56.3s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:46] {3166} INFO - iteration 213, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:46] {3343} INFO -  at 56.4s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:46] {3166} INFO - iteration 214, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:46] {3343} INFO -  at 56.7s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:46] {3166} INFO - iteration 215, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:47] {3343} INFO -  at 56.8s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:47] {3166} INFO - iteration 216, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:47] {3343} INFO -  at 57.0s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:47] {3166} INFO - iteration 217, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:47] {3343} INFO -  at 57.2s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:47] {3166} INFO - iteration 218, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:47] {3343} INFO -  at 57.4s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:47] {3166} INFO - iteration 219, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:47] {3343} INFO -  at 57.6s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:47] {3166} INFO - iteration 220, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:47] {3343} INFO -  at 57.8s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:47] {3166} INFO - iteration 221, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:48] {3343} INFO -  at 58.0s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:48] {3166} INFO - iteration 222, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:48] {3343} INFO -  at 58.2s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:48] {3166} INFO - iteration 223, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:48] {3343} INFO -  at 58.4s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:48] {3166} INFO - iteration 224, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:48] {3343} INFO -  at 58.7s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:48] {3166} INFO - iteration 225, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:49] {3343} INFO -  at 59.0s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:49] {3166} INFO - iteration 226, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:49] {3343} INFO -  at 59.2s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:49] {3166} INFO - iteration 227, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:49] {3343} INFO -  at 59.5s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:49] {3166} INFO - iteration 228, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:49] {3343} INFO -  at 59.7s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:49] {3166} INFO - iteration 229, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:50] {3343} INFO -  at 59.9s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:50] {3166} INFO - iteration 230, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:50] {3343} INFO -  at 60.2s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:50] {3166} INFO - iteration 231, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:50] {3343} INFO -  at 60.4s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:50] {3166} INFO - iteration 232, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:50] {3343} INFO -  at 60.7s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:50] {3166} INFO - iteration 233, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:51] {3343} INFO -  at 60.9s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:51] {3166} INFO - iteration 234, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:51] {3343} INFO -  at 61.3s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:51] {3166} INFO - iteration 235, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:51] {3343} INFO -  at 61.4s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:51] {3166} INFO - iteration 236, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:51] {3343} INFO -  at 61.6s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:51] {3166} INFO - iteration 237, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:52] {3343} INFO -  at 61.9s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:52] {3166} INFO - iteration 238, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:52] {3343} INFO -  at 62.0s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:52] {3166} INFO - iteration 239, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:52] {3343} INFO -  at 62.4s,	estimator rf's best error=75.3743,	best estimator rf's best error=75.3743
[flaml.automl: 04-23 11:30:52] {3166} INFO - iteration 240, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:52] {3343} INFO -  at 62.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:52] {3166} INFO - iteration 241, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:53] {3343} INFO -  at 62.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:53] {3166} INFO - iteration 242, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:53] {3343} INFO -  at 63.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:53] {3166} INFO - iteration 243, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:53] {3343} INFO -  at 63.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:53] {3166} INFO - iteration 244, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:53] {3343} INFO -  at 63.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:53] {3166} INFO - iteration 245, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:54] {3343} INFO -  at 63.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:54] {3166} INFO - iteration 246, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:54] {3343} INFO -  at 64.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:54] {3166} INFO - iteration 247, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:54] {3343} INFO -  at 64.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:54] {3166} INFO - iteration 248, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:54] {3343} INFO -  at 64.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:54] {3166} INFO - iteration 249, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:55] {3343} INFO -  at 65.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:55] {3166} INFO - iteration 250, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:55] {3343} INFO -  at 65.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:55] {3166} INFO - iteration 251, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:55] {3343} INFO -  at 65.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:55] {3166} INFO - iteration 252, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:55] {3343} INFO -  at 65.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:55] {3166} INFO - iteration 253, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:56] {3343} INFO -  at 65.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:56] {3166} INFO - iteration 254, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:56] {3343} INFO -  at 66.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:56] {3166} INFO - iteration 255, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:56] {3343} INFO -  at 66.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:56] {3166} INFO - iteration 256, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:56] {3343} INFO -  at 66.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:56] {3166} INFO - iteration 257, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:56] {3343} INFO -  at 66.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:56] {3166} INFO - iteration 258, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:57] {3343} INFO -  at 67.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:57] {3166} INFO - iteration 259, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:57] {3343} INFO -  at 67.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:57] {3166} INFO - iteration 260, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:57] {3343} INFO -  at 67.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:57] {3166} INFO - iteration 261, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:57] {3343} INFO -  at 67.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:57] {3166} INFO - iteration 262, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:57] {3343} INFO -  at 67.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:57] {3166} INFO - iteration 263, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:30:57] {3343} INFO -  at 67.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:57] {3166} INFO - iteration 264, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:58] {3343} INFO -  at 68.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:58] {3166} INFO - iteration 265, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:58] {3343} INFO -  at 68.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:58] {3166} INFO - iteration 266, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:58] {3343} INFO -  at 68.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:58] {3166} INFO - iteration 267, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:58] {3343} INFO -  at 68.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:58] {3166} INFO - iteration 268, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:58] {3343} INFO -  at 68.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:58] {3166} INFO - iteration 269, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:59] {3343} INFO -  at 68.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:59] {3166} INFO - iteration 270, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:59] {3343} INFO -  at 69.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:59] {3166} INFO - iteration 271, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:59] {3343} INFO -  at 69.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:59] {3166} INFO - iteration 272, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:59] {3343} INFO -  at 69.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:59] {3166} INFO - iteration 273, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:59] {3343} INFO -  at 69.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:59] {3166} INFO - iteration 274, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:30:59] {3343} INFO -  at 69.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:30:59] {3166} INFO - iteration 275, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:00] {3343} INFO -  at 69.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:00] {3166} INFO - iteration 276, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:00] {3343} INFO -  at 70.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:00] {3166} INFO - iteration 277, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:00] {3343} INFO -  at 70.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:00] {3166} INFO - iteration 278, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:00] {3343} INFO -  at 70.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:00] {3166} INFO - iteration 279, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:00] {3343} INFO -  at 70.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:00] {3166} INFO - iteration 280, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:01] {3343} INFO -  at 70.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:01] {3166} INFO - iteration 281, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:01] {3343} INFO -  at 71.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:01] {3166} INFO - iteration 282, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:01] {3343} INFO -  at 71.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:01] {3166} INFO - iteration 283, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:01] {3343} INFO -  at 71.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:01] {3166} INFO - iteration 284, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:01] {3343} INFO -  at 71.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:01] {3166} INFO - iteration 285, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:01] {3343} INFO -  at 71.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:01] {3166} INFO - iteration 286, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:02] {3343} INFO -  at 71.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:02] {3166} INFO - iteration 287, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:02] {3343} INFO -  at 72.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:02] {3166} INFO - iteration 288, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:02] {3343} INFO -  at 72.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:02] {3166} INFO - iteration 289, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:02] {3343} INFO -  at 72.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:02] {3166} INFO - iteration 290, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:02] {3343} INFO -  at 72.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:02] {3166} INFO - iteration 291, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:03] {3343} INFO -  at 73.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:03] {3166} INFO - iteration 292, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:03] {3343} INFO -  at 73.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:03] {3166} INFO - iteration 293, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:03] {3343} INFO -  at 73.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:03] {3166} INFO - iteration 294, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:04] {3343} INFO -  at 74.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:04] {3166} INFO - iteration 295, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:04] {3343} INFO -  at 74.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:04] {3166} INFO - iteration 296, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:04] {3343} INFO -  at 74.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:04] {3166} INFO - iteration 297, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:04] {3343} INFO -  at 74.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:05] {3166} INFO - iteration 298, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:05] {3343} INFO -  at 75.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:05] {3166} INFO - iteration 299, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:05] {3343} INFO -  at 75.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:05] {3166} INFO - iteration 300, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:05] {3343} INFO -  at 75.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:05] {3166} INFO - iteration 301, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:05] {3343} INFO -  at 75.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:05] {3166} INFO - iteration 302, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:06] {3343} INFO -  at 76.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:06] {3166} INFO - iteration 303, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:06] {3343} INFO -  at 76.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:06] {3166} INFO - iteration 304, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:06] {3343} INFO -  at 76.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:06] {3166} INFO - iteration 305, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:07] {3343} INFO -  at 76.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:07] {3166} INFO - iteration 306, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:07] {3343} INFO -  at 77.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:07] {3166} INFO - iteration 307, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:07] {3343} INFO -  at 77.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:07] {3166} INFO - iteration 308, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:07] {3343} INFO -  at 77.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:07] {3166} INFO - iteration 309, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:07] {3343} INFO -  at 77.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:07] {3166} INFO - iteration 310, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:08] {3343} INFO -  at 77.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:08] {3166} INFO - iteration 311, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:08] {3343} INFO -  at 78.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:08] {3166} INFO - iteration 312, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:08] {3343} INFO -  at 78.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:08] {3166} INFO - iteration 313, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:08] {3343} INFO -  at 78.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:08] {3166} INFO - iteration 314, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:08] {3343} INFO -  at 78.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:08] {3166} INFO - iteration 315, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:08] {3343} INFO -  at 78.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:08] {3166} INFO - iteration 316, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:09] {3343} INFO -  at 78.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:09] {3166} INFO - iteration 317, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:09] {3343} INFO -  at 79.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:09] {3166} INFO - iteration 318, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:09] {3343} INFO -  at 79.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:09] {3166} INFO - iteration 319, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:09] {3343} INFO -  at 79.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:09] {3166} INFO - iteration 320, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:09] {3343} INFO -  at 79.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:09] {3166} INFO - iteration 321, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:10] {3343} INFO -  at 80.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:10] {3166} INFO - iteration 322, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:10] {3343} INFO -  at 80.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:10] {3166} INFO - iteration 323, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:10] {3343} INFO -  at 80.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:10] {3166} INFO - iteration 324, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:10] {3343} INFO -  at 80.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:10] {3166} INFO - iteration 325, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:11] {3343} INFO -  at 81.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:11] {3166} INFO - iteration 326, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:11] {3343} INFO -  at 81.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:11] {3166} INFO - iteration 327, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:11] {3343} INFO -  at 81.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:11] {3166} INFO - iteration 328, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:11] {3343} INFO -  at 81.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964

[flaml.automl: 04-23 11:31:11] {3166} INFO - iteration 329, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:11] {3343} INFO -  at 81.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:11] {3166} INFO - iteration 330, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:12] {3343} INFO -  at 81.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:12] {3166} INFO - iteration 331, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:12] {3343} INFO -  at 82.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:12] {3166} INFO - iteration 332, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:12] {3343} INFO -  at 82.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:12] {3166} INFO - iteration 333, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:12] {3343} INFO -  at 82.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:12] {3166} INFO - iteration 334, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:12] {3343} INFO -  at 82.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:12] {3166} INFO - iteration 335, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:13] {3343} INFO -  at 82.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:13] {3166} INFO - iteration 336, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:13] {3343} INFO -  at 83.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:13] {3166} INFO - iteration 337, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:13] {3343} INFO -  at 83.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:13] {3166} INFO - iteration 338, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:13] {3343} INFO -  at 83.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:13] {3166} INFO - iteration 339, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:14] {3343} INFO -  at 83.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:14] {3166} INFO - iteration 340, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:14] {3343} INFO -  at 84.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:14] {3166} INFO - iteration 341, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:14] {3343} INFO -  at 84.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:14] {3166} INFO - iteration 342, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:14] {3343} INFO -  at 84.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:14] {3166} INFO - iteration 343, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:15] {3343} INFO -  at 84.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:15] {3166} INFO - iteration 344, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:15] {3343} INFO -  at 85.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:15] {3166} INFO - iteration 345, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:15] {3343} INFO -  at 85.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:15] {3166} INFO - iteration 346, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:15] {3343} INFO -  at 85.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:15] {3166} INFO - iteration 347, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:15] {3343} INFO -  at 85.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:15] {3166} INFO - iteration 348, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:16] {3343} INFO -  at 85.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:16] {3166} INFO - iteration 349, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:16] {3343} INFO -  at 85.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:16] {3166} INFO - iteration 350, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:16] {3343} INFO -  at 86.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:16] {3166} INFO - iteration 351, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:16] {3343} INFO -  at 86.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:16] {3166} INFO - iteration 352, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:16] {3343} INFO -  at 86.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:16] {3166} INFO - iteration 353, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:16] {3343} INFO -  at 86.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:16] {3166} INFO - iteration 354, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:17] {3343} INFO -  at 86.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:17] {3166} INFO - iteration 355, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:17] {3343} INFO -  at 87.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:17] {3166} INFO - iteration 356, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:17] {3343} INFO -  at 87.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:17] {3166} INFO - iteration 357, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:17] {3343} INFO -  at 87.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:17] {3166} INFO - iteration 358, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:18] {3343} INFO -  at 87.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:18] {3166} INFO - iteration 359, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:18] {3343} INFO -  at 88.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:18] {3166} INFO - iteration 360, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:18] {3343} INFO -  at 88.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:18] {3166} INFO - iteration 361, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:18] {3343} INFO -  at 88.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:18] {3166} INFO - iteration 362, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:18] {3343} INFO -  at 88.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:18] {3166} INFO - iteration 363, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:19] {3343} INFO -  at 89.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:19] {3166} INFO - iteration 364, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:19] {3343} INFO -  at 89.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:19] {3166} INFO - iteration 365, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:19] {3343} INFO -  at 89.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:19] {3166} INFO - iteration 366, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:19] {3343} INFO -  at 89.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:19] {3166} INFO - iteration 367, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:19] {3343} INFO -  at 89.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:19] {3166} INFO - iteration 368, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:20] {3343} INFO -  at 89.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:20] {3166} INFO - iteration 369, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:20] {3343} INFO -  at 90.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:20] {3166} INFO - iteration 370, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:20] {3343} INFO -  at 90.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:20] {3166} INFO - iteration 371, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:20] {3343} INFO -  at 90.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:20] {3166} INFO - iteration 372, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:20] {3343} INFO -  at 90.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:20] {3166} INFO - iteration 373, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:20] {3343} INFO -  at 90.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:20] {3166} INFO - iteration 374, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:21] {3343} INFO -  at 91.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:21] {3166} INFO - iteration 375, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:21] {3343} INFO -  at 91.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:21] {3166} INFO - iteration 376, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:21] {3343} INFO -  at 91.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:21] {3166} INFO - iteration 377, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:21] {3343} INFO -  at 91.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:21] {3166} INFO - iteration 378, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:22] {3343} INFO -  at 91.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:22] {3166} INFO - iteration 379, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:22] {3343} INFO -  at 92.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:22] {3166} INFO - iteration 380, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:22] {3343} INFO -  at 92.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964

[flaml.automl: 04-23 11:31:22] {3166} INFO - iteration 381, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:22] {3343} INFO -  at 92.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:22] {3166} INFO - iteration 382, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:23] {3343} INFO -  at 92.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:23] {3166} INFO - iteration 383, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:23] {3343} INFO -  at 93.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:23] {3166} INFO - iteration 384, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:23] {3343} INFO -  at 93.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:23] {3166} INFO - iteration 385, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:23] {3343} INFO -  at 93.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:23] {3166} INFO - iteration 386, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:23] {3343} INFO -  at 93.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:23] {3166} INFO - iteration 387, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:24] {3343} INFO -  at 93.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:24] {3166} INFO - iteration 388, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:24] {3343} INFO -  at 94.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:24] {3166} INFO - iteration 389, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:24] {3343} INFO -  at 94.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:24] {3166} INFO - iteration 390, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:24] {3343} INFO -  at 94.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:24] {3166} INFO - iteration 391, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:24] {3343} INFO -  at 94.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:24] {3166} INFO - iteration 392, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:25] {3343} INFO -  at 95.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:25] {3166} INFO - iteration 393, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:25] {3343} INFO -  at 95.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964

[flaml.automl: 04-23 11:31:25] {3166} INFO - iteration 394, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:25] {3343} INFO -  at 95.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:25] {3166} INFO - iteration 395, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:25] {3343} INFO -  at 95.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:25] {3166} INFO - iteration 396, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:26] {3343} INFO -  at 96.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:26] {3166} INFO - iteration 397, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:26] {3343} INFO -  at 96.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:26] {3166} INFO - iteration 398, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:26] {3343} INFO -  at 96.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:26] {3166} INFO - iteration 399, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:26] {3343} INFO -  at 96.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:26] {3166} INFO - iteration 400, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:27] {3343} INFO -  at 97.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:27] {3166} INFO - iteration 401, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:27] {3343} INFO -  at 97.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:27] {3166} INFO - iteration 402, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:27] {3343} INFO -  at 97.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:27] {3166} INFO - iteration 403, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:27] {3343} INFO -  at 97.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:27] {3166} INFO - iteration 404, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:28] {3343} INFO -  at 97.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:28] {3166} INFO - iteration 405, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:28] {3343} INFO -  at 98.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:28] {3166} INFO - iteration 406, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:28] {3343} INFO -  at 98.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:28] {3166} INFO - iteration 407, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:28] {3343} INFO -  at 98.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:28] {3166} INFO - iteration 408, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:29] {3343} INFO -  at 98.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:29] {3166} INFO - iteration 409, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:29] {3343} INFO -  at 99.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:29] {3166} INFO - iteration 410, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:29] {3343} INFO -  at 99.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:29] {3166} INFO - iteration 411, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:29] {3343} INFO -  at 99.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:29] {3166} INFO - iteration 412, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:29] {3343} INFO -  at 99.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:29] {3166} INFO - iteration 413, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:30] {3343} INFO -  at 99.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:30] {3166} INFO - iteration 414, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:30] {3343} INFO -  at 100.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:30] {3166} INFO - iteration 415, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:30] {3343} INFO -  at 100.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:30] {3166} INFO - iteration 416, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:30] {3343} INFO -  at 100.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:30] {3166} INFO - iteration 417, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:30] {3343} INFO -  at 100.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:30] {3166} INFO - iteration 418, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:31] {3343} INFO -  at 100.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:31] {3166} INFO - iteration 419, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:31] {3343} INFO -  at 101.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:31] {3166} INFO - iteration 420, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:31] {3343} INFO -  at 101.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:31] {3166} INFO - iteration 421, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:31] {3343} INFO -  at 101.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:31] {3166} INFO - iteration 422, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:31] {3343} INFO -  at 101.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:31] {3166} INFO - iteration 423, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:32] {3343} INFO -  at 101.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:32] {3166} INFO - iteration 424, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:32] {3343} INFO -  at 102.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:32] {3166} INFO - iteration 425, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:32] {3343} INFO -  at 102.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:32] {3166} INFO - iteration 426, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:32] {3343} INFO -  at 102.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:32] {3166} INFO - iteration 427, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:33] {3343} INFO -  at 102.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:33] {3166} INFO - iteration 428, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:33] {3343} INFO -  at 103.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:33] {3166} INFO - iteration 429, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:33] {3343} INFO -  at 103.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:33] {3166} INFO - iteration 430, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:33] {3343} INFO -  at 103.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:33] {3166} INFO - iteration 431, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:34] {3343} INFO -  at 103.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:34] {3166} INFO - iteration 432, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:34] {3343} INFO -  at 104.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964

[flaml.automl: 04-23 11:31:34] {3166} INFO - iteration 433, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:34] {3343} INFO -  at 104.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:34] {3166} INFO - iteration 434, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:34] {3343} INFO -  at 104.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:34] {3166} INFO - iteration 435, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:34] {3343} INFO -  at 104.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:34] {3166} INFO - iteration 436, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:35] {3343} INFO -  at 104.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:35] {3166} INFO - iteration 437, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:35] {3343} INFO -  at 105.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:35] {3166} INFO - iteration 438, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:35] {3343} INFO -  at 105.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:35] {3166} INFO - iteration 439, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:35] {3343} INFO -  at 105.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:35] {3166} INFO - iteration 440, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:35] {3343} INFO -  at 105.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:35] {3166} INFO - iteration 441, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:36] {3343} INFO -  at 106.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:36] {3166} INFO - iteration 442, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:36] {3343} INFO -  at 106.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:36] {3166} INFO - iteration 443, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:37] {3343} INFO -  at 107.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:37] {3166} INFO - iteration 444, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:37] {3343} INFO -  at 107.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:37] {3166} INFO - iteration 445, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:37] {3343} INFO -  at 107.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:37] {3166} INFO - iteration 446, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:37] {3343} INFO -  at 107.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:37] {3166} INFO - iteration 447, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:37] {3343} INFO -  at 107.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:37] {3166} INFO - iteration 448, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:38] {3343} INFO -  at 107.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:38] {3166} INFO - iteration 449, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:38] {3343} INFO -  at 108.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:38] {3166} INFO - iteration 450, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:38] {3343} INFO -  at 108.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:38] {3166} INFO - iteration 451, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:38] {3343} INFO -  at 108.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:38] {3166} INFO - iteration 452, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:38] {3343} INFO -  at 108.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:38] {3166} INFO - iteration 453, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:38] {3343} INFO -  at 108.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:38] {3166} INFO - iteration 454, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:39] {3343} INFO -  at 109.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:39] {3166} INFO - iteration 455, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:39] {3343} INFO -  at 109.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:39] {3166} INFO - iteration 456, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:39] {3343} INFO -  at 109.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:39] {3166} INFO - iteration 457, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:39] {3343} INFO -  at 109.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:39] {3166} INFO - iteration 458, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:39] {3343} INFO -  at 109.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:39] {3166} INFO - iteration 459, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:40] {3343} INFO -  at 109.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:40] {3166} INFO - iteration 460, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:40] {3343} INFO -  at 110.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:40] {3166} INFO - iteration 461, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:40] {3343} INFO -  at 110.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:40] {3166} INFO - iteration 462, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:40] {3343} INFO -  at 110.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:40] {3166} INFO - iteration 463, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:40] {3343} INFO -  at 110.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:40] {3166} INFO - iteration 464, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:41] {3343} INFO -  at 110.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:41] {3166} INFO - iteration 465, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:41] {3343} INFO -  at 111.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:41] {3166} INFO - iteration 466, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:41] {3343} INFO -  at 111.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:41] {3166} INFO - iteration 467, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:41] {3343} INFO -  at 111.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:41] {3166} INFO - iteration 468, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:41] {3343} INFO -  at 111.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:41] {3166} INFO - iteration 469, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:41] {3343} INFO -  at 111.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:41] {3166} INFO - iteration 470, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:42] {3343} INFO -  at 112.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:42] {3166} INFO - iteration 471, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:42] {3343} INFO -  at 112.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:42] {3166} INFO - iteration 472, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:42] {3343} INFO -  at 112.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:42] {3166} INFO - iteration 473, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:42] {3343} INFO -  at 112.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:42] {3166} INFO - iteration 474, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:42] {3343} INFO -  at 112.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:42] {3166} INFO - iteration 475, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:43] {3343} INFO -  at 113.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:43] {3166} INFO - iteration 476, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:43] {3343} INFO -  at 113.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:43] {3166} INFO - iteration 477, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:44] {3343} INFO -  at 114.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:44] {3166} INFO - iteration 478, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:44] {3343} INFO -  at 114.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:44] {3166} INFO - iteration 479, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:45] {3343} INFO -  at 115.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:45] {3166} INFO - iteration 480, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:45] {3343} INFO -  at 115.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:45] {3166} INFO - iteration 481, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:45] {3343} INFO -  at 115.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:45] {3166} INFO - iteration 482, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:46] {3343} INFO -  at 115.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:46] {3166} INFO - iteration 483, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:46] {3343} INFO -  at 116.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:46] {3166} INFO - iteration 484, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:46] {3343} INFO -  at 116.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:46] {3166} INFO - iteration 485, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:47] {3343} INFO -  at 117.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:47] {3166} INFO - iteration 486, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:47] {3343} INFO -  at 117.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:47] {3166} INFO - iteration 487, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:47] {3343} INFO -  at 117.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:47] {3166} INFO - iteration 488, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:48] {3343} INFO -  at 118.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:48] {3166} INFO - iteration 489, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:48] {3343} INFO -  at 118.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:48] {3166} INFO - iteration 490, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:48] {3343} INFO -  at 118.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:48] {3166} INFO - iteration 491, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:48] {3343} INFO -  at 118.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:48] {3166} INFO - iteration 492, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:49] {3343} INFO -  at 118.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:49] {3166} INFO - iteration 493, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:49] {3343} INFO -  at 119.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:49] {3166} INFO - iteration 494, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:49] {3343} INFO -  at 119.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:49] {3166} INFO - iteration 495, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:49] {3343} INFO -  at 119.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:49] {3166} INFO - iteration 496, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:49] {3343} INFO -  at 119.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:49] {3166} INFO - iteration 497, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:50] {3343} INFO -  at 120.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:50] {3166} INFO - iteration 498, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:50] {3343} INFO -  at 120.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:50] {3166} INFO - iteration 499, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:50] {3343} INFO -  at 120.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:50] {3166} INFO - iteration 500, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:50] {3343} INFO -  at 120.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:50] {3166} INFO - iteration 501, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:51] {3343} INFO -  at 121.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:51] {3166} INFO - iteration 502, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:51] {3343} INFO -  at 121.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:51] {3166} INFO - iteration 503, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:51] {3343} INFO -  at 121.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:51] {3166} INFO - iteration 504, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:51] {3343} INFO -  at 121.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:51] {3166} INFO - iteration 505, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:52] {3343} INFO -  at 121.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:52] {3166} INFO - iteration 506, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:52] {3343} INFO -  at 122.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:52] {3166} INFO - iteration 507, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:52] {3343} INFO -  at 122.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:52] {3166} INFO - iteration 508, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:52] {3343} INFO -  at 122.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:52] {3166} INFO - iteration 509, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:53] {3343} INFO -  at 122.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:53] {3166} INFO - iteration 510, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:53] {3343} INFO -  at 123.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:53] {3166} INFO - iteration 511, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:53] {3343} INFO -  at 123.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:53] {3166} INFO - iteration 512, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:53] {3343} INFO -  at 123.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:53] {3166} INFO - iteration 513, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:54] {3343} INFO -  at 124.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:54] {3166} INFO - iteration 514, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:54] {3343} INFO -  at 124.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:54] {3166} INFO - iteration 515, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:54] {3343} INFO -  at 124.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:54] {3166} INFO - iteration 516, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:55] {3343} INFO -  at 124.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:55] {3166} INFO - iteration 517, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:55] {3343} INFO -  at 125.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:55] {3166} INFO - iteration 518, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:55] {3343} INFO -  at 125.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:55] {3166} INFO - iteration 519, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:55] {3343} INFO -  at 125.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:55] {3166} INFO - iteration 520, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:56] {3343} INFO -  at 125.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:56] {3166} INFO - iteration 521, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:56] {3343} INFO -  at 126.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:56] {3166} INFO - iteration 522, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:56] {3343} INFO -  at 126.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:56] {3166} INFO - iteration 523, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:31:56] {3343} INFO -  at 126.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:56] {3166} INFO - iteration 524, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:57] {3343} INFO -  at 126.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:57] {3166} INFO - iteration 525, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:57] {3343} INFO -  at 127.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:57] {3166} INFO - iteration 526, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:57] {3343} INFO -  at 127.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:57] {3166} INFO - iteration 527, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:58] {3343} INFO -  at 127.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:58] {3166} INFO - iteration 528, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:58] {3343} INFO -  at 128.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:58] {3166} INFO - iteration 529, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:58] {3343} INFO -  at 128.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:58] {3166} INFO - iteration 530, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:58] {3343} INFO -  at 128.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:58] {3166} INFO - iteration 531, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:58] {3343} INFO -  at 128.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:58] {3166} INFO - iteration 532, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:59] {3343} INFO -  at 129.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:59] {3166} INFO - iteration 533, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:59] {3343} INFO -  at 129.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:59] {3166} INFO - iteration 534, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:59] {3343} INFO -  at 129.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:59] {3166} INFO - iteration 535, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:31:59] {3343} INFO -  at 129.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:31:59] {3166} INFO - iteration 536, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:32:00] {3343} INFO -  at 130.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:00] {3166} INFO - iteration 537, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:00] {3343} INFO -  at 130.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:00] {3166} INFO - iteration 538, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:00] {3343} INFO -  at 130.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:00] {3166} INFO - iteration 539, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:00] {3343} INFO -  at 130.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:00] {3166} INFO - iteration 540, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:01] {3343} INFO -  at 131.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:01] {3166} INFO - iteration 541, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:01] {3343} INFO -  at 131.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:01] {3166} INFO - iteration 542, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:01] {3343} INFO -  at 131.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:01] {3166} INFO - iteration 543, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:02] {3343} INFO -  at 131.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:02] {3166} INFO - iteration 544, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:02] {3343} INFO -  at 132.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:02] {3166} INFO - iteration 545, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:02] {3343} INFO -  at 132.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:02] {3166} INFO - iteration 546, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:03] {3343} INFO -  at 132.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:03] {3166} INFO - iteration 547, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:03] {3343} INFO -  at 133.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:03] {3166} INFO - iteration 548, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:03] {3343} INFO -  at 133.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:03] {3166} INFO - iteration 549, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:32:03] {3343} INFO -  at 133.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:03] {3166} INFO - iteration 550, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:04] {3343} INFO -  at 134.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:04] {3166} INFO - iteration 551, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:04] {3343} INFO -  at 134.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:04] {3166} INFO - iteration 552, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:04] {3343} INFO -  at 134.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:04] {3166} INFO - iteration 553, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:05] {3343} INFO -  at 134.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:05] {3166} INFO - iteration 554, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:05] {3343} INFO -  at 135.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:05] {3166} INFO - iteration 555, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:05] {3343} INFO -  at 135.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:05] {3166} INFO - iteration 556, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:05] {3343} INFO -  at 135.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:05] {3166} INFO - iteration 557, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:06] {3343} INFO -  at 136.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:06] {3166} INFO - iteration 558, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:06] {3343} INFO -  at 136.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:06] {3166} INFO - iteration 559, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:06] {3343} INFO -  at 136.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:06] {3166} INFO - iteration 560, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:07] {3343} INFO -  at 136.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:07] {3166} INFO - iteration 561, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:07] {3343} INFO -  at 137.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:07] {3166} INFO - iteration 562, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:32:07] {3343} INFO -  at 137.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:07] {3166} INFO - iteration 563, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:08] {3343} INFO -  at 138.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:08] {3166} INFO - iteration 564, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:08] {3343} INFO -  at 138.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:08] {3166} INFO - iteration 565, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:08] {3343} INFO -  at 138.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:08] {3166} INFO - iteration 566, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:09] {3343} INFO -  at 139.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:09] {3166} INFO - iteration 567, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:09] {3343} INFO -  at 139.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:09] {3166} INFO - iteration 568, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:10] {3343} INFO -  at 139.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:10] {3166} INFO - iteration 569, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:10] {3343} INFO -  at 140.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:10] {3166} INFO - iteration 570, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:10] {3343} INFO -  at 140.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:10] {3166} INFO - iteration 571, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:11] {3343} INFO -  at 140.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:11] {3166} INFO - iteration 572, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:11] {3343} INFO -  at 141.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:11] {3166} INFO - iteration 573, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:12] {3343} INFO -  at 141.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:12] {3166} INFO - iteration 574, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:12] {3343} INFO -  at 142.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:12] {3166} INFO - iteration 575, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:32:12] {3343} INFO -  at 142.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:12] {3166} INFO - iteration 576, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:13] {3343} INFO -  at 143.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:13] {3166} INFO - iteration 577, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:13] {3343} INFO -  at 143.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:13] {3166} INFO - iteration 578, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:14] {3343} INFO -  at 143.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:14] {3166} INFO - iteration 579, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:14] {3343} INFO -  at 144.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:14] {3166} INFO - iteration 580, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:14] {3343} INFO -  at 144.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:14] {3166} INFO - iteration 581, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:14] {3343} INFO -  at 144.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:14] {3166} INFO - iteration 582, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:15] {3343} INFO -  at 145.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:15] {3166} INFO - iteration 583, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:15] {3343} INFO -  at 145.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:15] {3166} INFO - iteration 584, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:15] {3343} INFO -  at 145.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:15] {3166} INFO - iteration 585, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:16] {3343} INFO -  at 145.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:16] {3166} INFO - iteration 586, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:16] {3343} INFO -  at 146.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:16] {3166} INFO - iteration 587, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:16] {3343} INFO -  at 146.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:16] {3166} INFO - iteration 588, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:32:17] {3343} INFO -  at 146.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:17] {3166} INFO - iteration 589, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:17] {3343} INFO -  at 147.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:17] {3166} INFO - iteration 590, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:17] {3343} INFO -  at 147.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:17] {3166} INFO - iteration 591, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:18] {3343} INFO -  at 148.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:18] {3166} INFO - iteration 592, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:18] {3343} INFO -  at 148.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:18] {3166} INFO - iteration 593, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:18] {3343} INFO -  at 148.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:18] {3166} INFO - iteration 594, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:19] {3343} INFO -  at 148.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:19] {3166} INFO - iteration 595, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:19] {3343} INFO -  at 149.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:19] {3166} INFO - iteration 596, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:19] {3343} INFO -  at 149.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:19] {3166} INFO - iteration 597, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:20] {3343} INFO -  at 150.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:20] {3166} INFO - iteration 598, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:21] {3343} INFO -  at 150.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:21] {3166} INFO - iteration 599, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:21] {3343} INFO -  at 151.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:21] {3166} INFO - iteration 600, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:21] {3343} INFO -  at 151.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:21] {3166} INFO - iteration 601, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:32:22] {3343} INFO -  at 151.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:22] {3166} INFO - iteration 602, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:22] {3343} INFO -  at 152.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:22] {3166} INFO - iteration 603, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:22] {3343} INFO -  at 152.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:22] {3166} INFO - iteration 604, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:23] {3343} INFO -  at 153.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:23] {3166} INFO - iteration 605, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:23] {3343} INFO -  at 153.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:23] {3166} INFO - iteration 606, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:23] {3343} INFO -  at 153.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:23] {3166} INFO - iteration 607, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:24] {3343} INFO -  at 154.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:24] {3166} INFO - iteration 608, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:24] {3343} INFO -  at 154.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:24] {3166} INFO - iteration 609, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:24] {3343} INFO -  at 154.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:24] {3166} INFO - iteration 610, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:25] {3343} INFO -  at 154.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:25] {3166} INFO - iteration 611, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:25] {3343} INFO -  at 155.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:25] {3166} INFO - iteration 612, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:25] {3343} INFO -  at 155.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:25] {3166} INFO - iteration 613, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:25] {3343} INFO -  at 155.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:25] {3166} INFO - iteration 614, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:32:26] {3343} INFO -  at 155.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:26] {3166} INFO - iteration 615, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:26] {3343} INFO -  at 156.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:26] {3166} INFO - iteration 616, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:26] {3343} INFO -  at 156.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:26] {3166} INFO - iteration 617, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:26] {3343} INFO -  at 156.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:26] {3166} INFO - iteration 618, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:27] {3343} INFO -  at 157.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:27] {3166} INFO - iteration 619, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:27] {3343} INFO -  at 157.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:27] {3166} INFO - iteration 620, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:27] {3343} INFO -  at 157.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:27] {3166} INFO - iteration 621, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:27] {3343} INFO -  at 157.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:27] {3166} INFO - iteration 622, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:28] {3343} INFO -  at 158.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:28] {3166} INFO - iteration 623, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:28] {3343} INFO -  at 158.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:28] {3166} INFO - iteration 624, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:28] {3343} INFO -  at 158.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:28] {3166} INFO - iteration 625, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:28] {3343} INFO -  at 158.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:28] {3166} INFO - iteration 626, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:29] {3343} INFO -  at 159.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:29] {3166} INFO - iteration 627, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:32:29] {3343} INFO -  at 159.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:29] {3166} INFO - iteration 628, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:29] {3343} INFO -  at 159.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:29] {3166} INFO - iteration 629, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:29] {3343} INFO -  at 159.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:30] {3166} INFO - iteration 630, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:30] {3343} INFO -  at 160.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:30] {3166} INFO - iteration 631, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:30] {3343} INFO -  at 160.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:30] {3166} INFO - iteration 632, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:30] {3343} INFO -  at 160.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:30] {3166} INFO - iteration 633, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:31] {3343} INFO -  at 160.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:31] {3166} INFO - iteration 634, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:31] {3343} INFO -  at 161.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:31] {3166} INFO - iteration 635, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:31] {3343} INFO -  at 161.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:31] {3166} INFO - iteration 636, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:31] {3343} INFO -  at 161.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:31] {3166} INFO - iteration 637, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:32] {3343} INFO -  at 162.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:32] {3166} INFO - iteration 638, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:32] {3343} INFO -  at 162.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:32] {3166} INFO - iteration 639, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:32] {3343} INFO -  at 162.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:32] {3166} INFO - iteration 640, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:32:32] {3343} INFO -  at 162.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:32] {3166} INFO - iteration 641, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:33] {3343} INFO -  at 163.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:33] {3166} INFO - iteration 642, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:33] {3343} INFO -  at 163.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:33] {3166} INFO - iteration 643, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:33] {3343} INFO -  at 163.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:33] {3166} INFO - iteration 644, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:34] {3343} INFO -  at 164.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:34] {3166} INFO - iteration 645, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:34] {3343} INFO -  at 164.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:34] {3166} INFO - iteration 646, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:34] {3343} INFO -  at 164.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:34] {3166} INFO - iteration 647, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:35] {3343} INFO -  at 164.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:35] {3166} INFO - iteration 648, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:35] {3343} INFO -  at 165.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:35] {3166} INFO - iteration 649, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:35] {3343} INFO -  at 165.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:35] {3166} INFO - iteration 650, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:36] {3343} INFO -  at 165.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:36] {3166} INFO - iteration 651, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:36] {3343} INFO -  at 166.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:36] {3166} INFO - iteration 652, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:37] {3343} INFO -  at 166.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:37] {3166} INFO - iteration 653, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:32:37] {3343} INFO -  at 167.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:37] {3166} INFO - iteration 654, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:38] {3343} INFO -  at 168.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:38] {3166} INFO - iteration 655, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:38] {3343} INFO -  at 168.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:38] {3166} INFO - iteration 656, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:39] {3343} INFO -  at 168.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:39] {3166} INFO - iteration 657, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:39] {3343} INFO -  at 169.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:39] {3166} INFO - iteration 658, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:39] {3343} INFO -  at 169.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:39] {3166} INFO - iteration 659, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:40] {3343} INFO -  at 170.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:40] {3166} INFO - iteration 660, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:40] {3343} INFO -  at 170.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:40] {3166} INFO - iteration 661, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:40] {3343} INFO -  at 170.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:40] {3166} INFO - iteration 662, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:41] {3343} INFO -  at 170.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:41] {3166} INFO - iteration 663, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:41] {3343} INFO -  at 171.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:41] {3166} INFO - iteration 664, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:41] {3343} INFO -  at 171.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:41] {3166} INFO - iteration 665, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:41] {3343} INFO -  at 171.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:41] {3166} INFO - iteration 666, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:32:42] {3343} INFO -  at 172.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:42] {3166} INFO - iteration 667, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:42] {3343} INFO -  at 172.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:42] {3166} INFO - iteration 668, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:43] {3343} INFO -  at 172.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:43] {3166} INFO - iteration 669, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:43] {3343} INFO -  at 173.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:43] {3166} INFO - iteration 670, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:43] {3343} INFO -  at 173.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:43] {3166} INFO - iteration 671, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:44] {3343} INFO -  at 174.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:44] {3166} INFO - iteration 672, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:44] {3343} INFO -  at 174.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:44] {3166} INFO - iteration 673, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:44] {3343} INFO -  at 174.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:44] {3166} INFO - iteration 674, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:44] {3343} INFO -  at 174.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:44] {3166} INFO - iteration 675, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:45] {3343} INFO -  at 175.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:45] {3166} INFO - iteration 676, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:45] {3343} INFO -  at 175.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:45] {3166} INFO - iteration 677, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:45] {3343} INFO -  at 175.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:45] {3166} INFO - iteration 678, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:45] {3343} INFO -  at 175.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:45] {3166} INFO - iteration 679, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:46] {3343} INFO -  at 175.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964

[flaml.automl: 04-23 11:32:46] {3166} INFO - iteration 680, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:46] {3343} INFO -  at 176.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:46] {3166} INFO - iteration 681, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:46] {3343} INFO -  at 176.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:46] {3166} INFO - iteration 682, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:46] {3343} INFO -  at 176.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:46] {3166} INFO - iteration 683, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:47] {3343} INFO -  at 177.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:47] {3166} INFO - iteration 684, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:47] {3343} INFO -  at 177.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:47] {3166} INFO - iteration 685, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:47] {3343} INFO -  at 177.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:47] {3166} INFO - iteration 686, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:48] {3343} INFO -  at 177.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:48] {3166} INFO - iteration 687, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:48] {3343} INFO -  at 178.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:48] {3166} INFO - iteration 688, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:48] {3343} INFO -  at 178.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:48] {3166} INFO - iteration 689, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:48] {3343} INFO -  at 178.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:48] {3166} INFO - iteration 690, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:49] {3343} INFO -  at 178.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:49] {3166} INFO - iteration 691, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:49] {3343} INFO -  at 179.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:49] {3166} INFO - iteration 692, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:49] {3343} INFO -  at 179.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964

[flaml.automl: 04-23 11:32:49] {3166} INFO - iteration 693, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:49] {3343} INFO -  at 179.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:49] {3166} INFO - iteration 694, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:49] {3343} INFO -  at 179.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:49] {3166} INFO - iteration 695, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:50] {3343} INFO -  at 179.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:50] {3166} INFO - iteration 696, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:50] {3343} INFO -  at 180.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:50] {3166} INFO - iteration 697, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:50] {3343} INFO -  at 180.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:50] {3166} INFO - iteration 698, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:50] {3343} INFO -  at 180.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:50] {3166} INFO - iteration 699, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:51] {3343} INFO -  at 180.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:51] {3166} INFO - iteration 700, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:51] {3343} INFO -  at 181.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:51] {3166} INFO - iteration 701, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:51] {3343} INFO -  at 181.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:51] {3166} INFO - iteration 702, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:51] {3343} INFO -  at 181.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:51] {3166} INFO - iteration 703, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:51] {3343} INFO -  at 181.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:51] {3166} INFO - iteration 704, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:52] {3343} INFO -  at 181.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:52] {3166} INFO - iteration 705, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:52] {3343} INFO -  at 182.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964

[flaml.automl: 04-23 11:32:52] {3166} INFO - iteration 706, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:52] {3343} INFO -  at 182.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:52] {3166} INFO - iteration 707, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:52] {3343} INFO -  at 182.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:52] {3166} INFO - iteration 708, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:52] {3343} INFO -  at 182.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:52] {3166} INFO - iteration 709, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:53] {3343} INFO -  at 182.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:53] {3166} INFO - iteration 710, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:53] {3343} INFO -  at 183.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:53] {3166} INFO - iteration 711, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:53] {3343} INFO -  at 183.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:53] {3166} INFO - iteration 712, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:53] {3343} INFO -  at 183.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:53] {3166} INFO - iteration 713, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:53] {3343} INFO -  at 183.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:53] {3166} INFO - iteration 714, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:54] {3343} INFO -  at 183.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:54] {3166} INFO - iteration 715, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:54] {3343} INFO -  at 184.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:54] {3166} INFO - iteration 716, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:54] {3343} INFO -  at 184.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:54] {3166} INFO - iteration 717, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:54] {3343} INFO -  at 184.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:54] {3166} INFO - iteration 718, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:32:54] {3343} INFO -  at 184.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:54] {3166} INFO - iteration 719, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:55] {3343} INFO -  at 184.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:55] {3166} INFO - iteration 720, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:55] {3343} INFO -  at 185.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:55] {3166} INFO - iteration 721, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:55] {3343} INFO -  at 185.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:55] {3166} INFO - iteration 722, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:55] {3343} INFO -  at 185.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:55] {3166} INFO - iteration 723, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:55] {3343} INFO -  at 185.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:55] {3166} INFO - iteration 724, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:56] {3343} INFO -  at 185.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:56] {3166} INFO - iteration 725, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:56] {3343} INFO -  at 186.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:56] {3166} INFO - iteration 726, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:56] {3343} INFO -  at 186.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:56] {3166} INFO - iteration 727, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:56] {3343} INFO -  at 186.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:56] {3166} INFO - iteration 728, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:57] {3343} INFO -  at 186.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:57] {3166} INFO - iteration 729, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:57] {3343} INFO -  at 187.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:57] {3166} INFO - iteration 730, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:57] {3343} INFO -  at 187.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:57] {3166} INFO - iteration 731, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:32:57] {3343} INFO -  at 187.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:57] {3166} INFO - iteration 732, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:58] {3343} INFO -  at 187.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:58] {3166} INFO - iteration 733, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:58] {3343} INFO -  at 188.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:58] {3166} INFO - iteration 734, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:58] {3343} INFO -  at 188.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:58] {3166} INFO - iteration 735, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:59] {3343} INFO -  at 188.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:59] {3166} INFO - iteration 736, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:59] {3343} INFO -  at 189.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:59] {3166} INFO - iteration 737, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:59] {3343} INFO -  at 189.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:59] {3166} INFO - iteration 738, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:32:59] {3343} INFO -  at 189.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:32:59] {3166} INFO - iteration 739, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:00] {3343} INFO -  at 189.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:00] {3166} INFO - iteration 740, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:00] {3343} INFO -  at 190.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:00] {3166} INFO - iteration 741, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:00] {3343} INFO -  at 190.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:00] {3166} INFO - iteration 742, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:00] {3343} INFO -  at 190.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:00] {3166} INFO - iteration 743, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:01] {3343} INFO -  at 190.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:01] {3166} INFO - iteration 744, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:01] {3343} INFO -  at 191.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:01] {3166} INFO - iteration 745, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:01] {3343} INFO -  at 191.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:01] {3166} INFO - iteration 746, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:01] {3343} INFO -  at 191.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:01] {3166} INFO - iteration 747, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:02] {3343} INFO -  at 191.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:02] {3166} INFO - iteration 748, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:02] {3343} INFO -  at 192.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:02] {3166} INFO - iteration 749, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:02] {3343} INFO -  at 192.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:02] {3166} INFO - iteration 750, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:02] {3343} INFO -  at 192.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:02] {3166} INFO - iteration 751, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:03] {3343} INFO -  at 192.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:03] {3166} INFO - iteration 752, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:03] {3343} INFO -  at 193.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:03] {3166} INFO - iteration 753, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:03] {3343} INFO -  at 193.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:03] {3166} INFO - iteration 754, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:03] {3343} INFO -  at 193.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:03] {3166} INFO - iteration 755, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:04] {3343} INFO -  at 193.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:04] {3166} INFO - iteration 756, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:04] {3343} INFO -  at 194.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:04] {3166} INFO - iteration 757, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:04] {3343} INFO -  at 194.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:04] {3166} INFO - iteration 758, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:04] {3343} INFO -  at 194.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:04] {3166} INFO - iteration 759, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:05] {3343} INFO -  at 194.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:05] {3166} INFO - iteration 760, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:05] {3343} INFO -  at 195.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:05] {3166} INFO - iteration 761, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:05] {3343} INFO -  at 195.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:05] {3166} INFO - iteration 762, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:05] {3343} INFO -  at 195.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:05] {3166} INFO - iteration 763, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:05] {3343} INFO -  at 195.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:05] {3166} INFO - iteration 764, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:06] {3343} INFO -  at 196.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:06] {3166} INFO - iteration 765, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:06] {3343} INFO -  at 196.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:06] {3166} INFO - iteration 766, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:07] {3343} INFO -  at 196.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:07] {3166} INFO - iteration 767, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:07] {3343} INFO -  at 197.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:07] {3166} INFO - iteration 768, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:07] {3343} INFO -  at 197.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:07] {3166} INFO - iteration 769, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:07] {3343} INFO -  at 197.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:07] {3166} INFO - iteration 770, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:08] {3343} INFO -  at 198.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:08] {3166} INFO - iteration 771, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:08] {3343} INFO -  at 198.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:08] {3166} INFO - iteration 772, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:08] {3343} INFO -  at 198.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:08] {3166} INFO - iteration 773, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:08] {3343} INFO -  at 198.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:08] {3166} INFO - iteration 774, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:09] {3343} INFO -  at 198.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:09] {3166} INFO - iteration 775, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:09] {3343} INFO -  at 199.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:09] {3166} INFO - iteration 776, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:09] {3343} INFO -  at 199.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:09] {3166} INFO - iteration 777, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:09] {3343} INFO -  at 199.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:09] {3166} INFO - iteration 778, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:09] {3343} INFO -  at 199.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:09] {3166} INFO - iteration 779, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:09] {3343} INFO -  at 199.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:09] {3166} INFO - iteration 780, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:10] {3343} INFO -  at 199.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:10] {3166} INFO - iteration 781, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:10] {3343} INFO -  at 200.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:10] {3166} INFO - iteration 782, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:10] {3343} INFO -  at 200.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:10] {3166} INFO - iteration 783, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:10] {3343} INFO -  at 200.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:10] {3166} INFO - iteration 784, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:11] {3343} INFO -  at 200.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:11] {3166} INFO - iteration 785, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:11] {3343} INFO -  at 201.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:11] {3166} INFO - iteration 786, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:11] {3343} INFO -  at 201.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:11] {3166} INFO - iteration 787, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:11] {3343} INFO -  at 201.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:11] {3166} INFO - iteration 788, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:12] {3343} INFO -  at 201.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:12] {3166} INFO - iteration 789, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:12] {3343} INFO -  at 202.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:12] {3166} INFO - iteration 790, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:12] {3343} INFO -  at 202.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:12] {3166} INFO - iteration 791, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:12] {3343} INFO -  at 202.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:12] {3166} INFO - iteration 792, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:13] {3343} INFO -  at 202.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:13] {3166} INFO - iteration 793, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:13] {3343} INFO -  at 203.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:13] {3166} INFO - iteration 794, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:13] {3343} INFO -  at 203.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:13] {3166} INFO - iteration 795, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:13] {3343} INFO -  at 203.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:13] {3166} INFO - iteration 796, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:14] {3343} INFO -  at 203.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964

[flaml.automl: 04-23 11:33:14] {3166} INFO - iteration 797, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:14] {3343} INFO -  at 204.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:14] {3166} INFO - iteration 798, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:14] {3343} INFO -  at 204.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:14] {3166} INFO - iteration 799, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:14] {3343} INFO -  at 204.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:14] {3166} INFO - iteration 800, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:14] {3343} INFO -  at 204.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:14] {3166} INFO - iteration 801, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:15] {3343} INFO -  at 204.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:15] {3166} INFO - iteration 802, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:15] {3343} INFO -  at 205.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:15] {3166} INFO - iteration 803, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:15] {3343} INFO -  at 205.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:15] {3166} INFO - iteration 804, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:15] {3343} INFO -  at 205.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:15] {3166} INFO - iteration 805, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:16] {3343} INFO -  at 206.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:16] {3166} INFO - iteration 806, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:16] {3343} INFO -  at 206.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:16] {3166} INFO - iteration 807, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:16] {3343} INFO -  at 206.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:16] {3166} INFO - iteration 808, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:17] {3343} INFO -  at 206.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:17] {3166} INFO - iteration 809, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:17] {3343} INFO -  at 207.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:17] {3166} INFO - iteration 810, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:17] {3343} INFO -  at 207.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:17] {3166} INFO - iteration 811, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:17] {3343} INFO -  at 207.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:17] {3166} INFO - iteration 812, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:18] {3343} INFO -  at 207.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:18] {3166} INFO - iteration 813, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:18] {3343} INFO -  at 208.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:18] {3166} INFO - iteration 814, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:18] {3343} INFO -  at 208.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:18] {3166} INFO - iteration 815, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:18] {3343} INFO -  at 208.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:18] {3166} INFO - iteration 816, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:19] {3343} INFO -  at 208.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:19] {3166} INFO - iteration 817, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:19] {3343} INFO -  at 209.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:19] {3166} INFO - iteration 818, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:19] {3343} INFO -  at 209.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:19] {3166} INFO - iteration 819, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:19] {3343} INFO -  at 209.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:19] {3166} INFO - iteration 820, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:19] {3343} INFO -  at 209.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:19] {3166} INFO - iteration 821, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:20] {3343} INFO -  at 210.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:20] {3166} INFO - iteration 822, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:20] {3343} INFO -  at 210.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:20] {3166} INFO - iteration 823, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:20] {3343} INFO -  at 210.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:20] {3166} INFO - iteration 824, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:20] {3343} INFO -  at 210.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:20] {3166} INFO - iteration 825, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:21] {3343} INFO -  at 211.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:21] {3166} INFO - iteration 826, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:21] {3343} INFO -  at 211.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:21] {3166} INFO - iteration 827, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:21] {3343} INFO -  at 211.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:21] {3166} INFO - iteration 828, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:21] {3343} INFO -  at 211.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:21] {3166} INFO - iteration 829, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:22] {3343} INFO -  at 212.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:22] {3166} INFO - iteration 830, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:22] {3343} INFO -  at 212.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:22] {3166} INFO - iteration 831, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:22] {3343} INFO -  at 212.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:22] {3166} INFO - iteration 832, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:23] {3343} INFO -  at 212.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:23] {3166} INFO - iteration 833, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:23] {3343} INFO -  at 213.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:23] {3166} INFO - iteration 834, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:23] {3343} INFO -  at 213.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:23] {3166} INFO - iteration 835, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:23] {3343} INFO -  at 213.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:23] {3166} INFO - iteration 836, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:23] {3343} INFO -  at 213.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:23] {3166} INFO - iteration 837, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:24] {3343} INFO -  at 214.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:24] {3166} INFO - iteration 838, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:24] {3343} INFO -  at 214.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:24] {3166} INFO - iteration 839, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:24] {3343} INFO -  at 214.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:24] {3166} INFO - iteration 840, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:24] {3343} INFO -  at 214.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:24] {3166} INFO - iteration 841, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:25] {3343} INFO -  at 214.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:25] {3166} INFO - iteration 842, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:25] {3343} INFO -  at 215.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:25] {3166} INFO - iteration 843, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:25] {3343} INFO -  at 215.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:25] {3166} INFO - iteration 844, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:25] {3343} INFO -  at 215.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:25] {3166} INFO - iteration 845, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:26] {3343} INFO -  at 215.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:26] {3166} INFO - iteration 846, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:26] {3343} INFO -  at 216.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:26] {3166} INFO - iteration 847, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:26] {3343} INFO -  at 216.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:26] {3166} INFO - iteration 848, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:26] {3343} INFO -  at 216.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:26] {3166} INFO - iteration 849, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:27] {3343} INFO -  at 216.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:27] {3166} INFO - iteration 850, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:27] {3343} INFO -  at 217.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:27] {3166} INFO - iteration 851, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:27] {3343} INFO -  at 217.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:27] {3166} INFO - iteration 852, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:27] {3343} INFO -  at 217.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:27] {3166} INFO - iteration 853, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:28] {3343} INFO -  at 217.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:28] {3166} INFO - iteration 854, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:28] {3343} INFO -  at 218.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:28] {3166} INFO - iteration 855, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:28] {3343} INFO -  at 218.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:28] {3166} INFO - iteration 856, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:28] {3343} INFO -  at 218.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:28] {3166} INFO - iteration 857, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:29] {3343} INFO -  at 218.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:29] {3166} INFO - iteration 858, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:29] {3343} INFO -  at 219.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:29] {3166} INFO - iteration 859, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:29] {3343} INFO -  at 219.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:29] {3166} INFO - iteration 860, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:29] {3343} INFO -  at 219.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:29] {3166} INFO - iteration 861, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:29] {3343} INFO -  at 219.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:29] {3166} INFO - iteration 862, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:30] {3343} INFO -  at 220.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:30] {3166} INFO - iteration 863, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:30] {3343} INFO -  at 220.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:30] {3166} INFO - iteration 864, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:30] {3343} INFO -  at 220.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:30] {3166} INFO - iteration 865, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:31] {3343} INFO -  at 220.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:31] {3166} INFO - iteration 866, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:31] {3343} INFO -  at 221.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:31] {3166} INFO - iteration 867, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:31] {3343} INFO -  at 221.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:31] {3166} INFO - iteration 868, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:31] {3343} INFO -  at 221.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:31] {3166} INFO - iteration 869, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:32] {3343} INFO -  at 221.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:32] {3166} INFO - iteration 870, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:32] {3343} INFO -  at 222.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:32] {3166} INFO - iteration 871, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:32] {3343} INFO -  at 222.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:32] {3166} INFO - iteration 872, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:32] {3343} INFO -  at 222.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:32] {3166} INFO - iteration 873, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:33] {3343} INFO -  at 222.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:33] {3166} INFO - iteration 874, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:33] {3343} INFO -  at 223.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:33] {3166} INFO - iteration 875, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:33] {3343} INFO -  at 223.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:33] {3166} INFO - iteration 876, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:33] {3343} INFO -  at 223.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:33] {3166} INFO - iteration 877, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:34] {3343} INFO -  at 223.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:34] {3166} INFO - iteration 878, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:34] {3343} INFO -  at 224.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:34] {3166} INFO - iteration 879, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:34] {3343} INFO -  at 224.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:34] {3166} INFO - iteration 880, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:34] {3343} INFO -  at 224.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:34] {3166} INFO - iteration 881, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:35] {3343} INFO -  at 224.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:35] {3166} INFO - iteration 882, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:35] {3343} INFO -  at 225.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:35] {3166} INFO - iteration 883, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:35] {3343} INFO -  at 225.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:35] {3166} INFO - iteration 884, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:35] {3343} INFO -  at 225.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:35] {3166} INFO - iteration 885, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:35] {3343} INFO -  at 225.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:35] {3166} INFO - iteration 886, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:36] {3343} INFO -  at 226.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:36] {3166} INFO - iteration 887, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:36] {3343} INFO -  at 226.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964

[flaml.automl: 04-23 11:33:36] {3166} INFO - iteration 888, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:36] {3343} INFO -  at 226.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:36] {3166} INFO - iteration 889, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:36] {3343} INFO -  at 226.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:36] {3166} INFO - iteration 890, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:37] {3343} INFO -  at 226.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:37] {3166} INFO - iteration 891, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:37] {3343} INFO -  at 227.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:37] {3166} INFO - iteration 892, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:37] {3343} INFO -  at 227.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:37] {3166} INFO - iteration 893, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:37] {3343} INFO -  at 227.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:37] {3166} INFO - iteration 894, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:38] {3343} INFO -  at 227.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:38] {3166} INFO - iteration 895, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:38] {3343} INFO -  at 228.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:38] {3166} INFO - iteration 896, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:38] {3343} INFO -  at 228.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:38] {3166} INFO - iteration 897, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:38] {3343} INFO -  at 228.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:38] {3166} INFO - iteration 898, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:39] {3343} INFO -  at 228.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:39] {3166} INFO - iteration 899, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:39] {3343} INFO -  at 229.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:39] {3166} INFO - iteration 900, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:39] {3343} INFO -  at 229.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:39] {3166} INFO - iteration 901, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:39] {3343} INFO -  at 229.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:39] {3166} INFO - iteration 902, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:39] {3343} INFO -  at 229.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:39] {3166} INFO - iteration 903, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:40] {3343} INFO -  at 230.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:40] {3166} INFO - iteration 904, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:40] {3343} INFO -  at 230.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:40] {3166} INFO - iteration 905, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:40] {3343} INFO -  at 230.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:40] {3166} INFO - iteration 906, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:41] {3343} INFO -  at 230.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:41] {3166} INFO - iteration 907, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:41] {3343} INFO -  at 231.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:41] {3166} INFO - iteration 908, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:41] {3343} INFO -  at 231.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:41] {3166} INFO - iteration 909, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:41] {3343} INFO -  at 231.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:41] {3166} INFO - iteration 910, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:42] {3343} INFO -  at 231.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:42] {3166} INFO - iteration 911, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:42] {3343} INFO -  at 232.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:42] {3166} INFO - iteration 912, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:42] {3343} INFO -  at 232.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:42] {3166} INFO - iteration 913, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:42] {3343} INFO -  at 232.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:42] {3166} INFO - iteration 914, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:43] {3343} INFO -  at 232.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:43] {3166} INFO - iteration 915, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:43] {3343} INFO -  at 233.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:43] {3166} INFO - iteration 916, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:43] {3343} INFO -  at 233.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:43] {3166} INFO - iteration 917, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:44] {3343} INFO -  at 233.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:44] {3166} INFO - iteration 918, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:44] {3343} INFO -  at 234.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:44] {3166} INFO - iteration 919, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:44] {3343} INFO -  at 234.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:44] {3166} INFO - iteration 920, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:44] {3343} INFO -  at 234.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:44] {3166} INFO - iteration 921, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:45] {3343} INFO -  at 234.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:45] {3166} INFO - iteration 922, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:45] {3343} INFO -  at 235.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:45] {3166} INFO - iteration 923, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:45] {3343} INFO -  at 235.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:45] {3166} INFO - iteration 924, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:45] {3343} INFO -  at 235.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:45] {3166} INFO - iteration 925, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:46] {3343} INFO -  at 235.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:46] {3166} INFO - iteration 926, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:46] {3343} INFO -  at 236.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:46] {3166} INFO - iteration 927, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:46] {3343} INFO -  at 236.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:46] {3166} INFO - iteration 928, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:46] {3343} INFO -  at 236.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:46] {3166} INFO - iteration 929, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:46] {3343} INFO -  at 236.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:46] {3166} INFO - iteration 930, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:47] {3343} INFO -  at 237.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:47] {3166} INFO - iteration 931, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:47] {3343} INFO -  at 237.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:47] {3166} INFO - iteration 932, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:47] {3343} INFO -  at 237.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:47] {3166} INFO - iteration 933, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:47] {3343} INFO -  at 237.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:47] {3166} INFO - iteration 934, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:48] {3343} INFO -  at 237.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:48] {3166} INFO - iteration 935, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:48] {3343} INFO -  at 238.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:48] {3166} INFO - iteration 936, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:48] {3343} INFO -  at 238.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:48] {3166} INFO - iteration 937, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:48] {3343} INFO -  at 238.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:48] {3166} INFO - iteration 938, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:49] {3343} INFO -  at 238.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:49] {3166} INFO - iteration 939, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:49] {3343} INFO -  at 239.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:49] {3166} INFO - iteration 940, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:49] {3343} INFO -  at 239.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:49] {3166} INFO - iteration 941, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:49] {3343} INFO -  at 239.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:49] {3166} INFO - iteration 942, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:50] {3343} INFO -  at 239.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:50] {3166} INFO - iteration 943, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:50] {3343} INFO -  at 240.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:50] {3166} INFO - iteration 944, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:50] {3343} INFO -  at 240.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:50] {3166} INFO - iteration 945, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:50] {3343} INFO -  at 240.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:50] {3166} INFO - iteration 946, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:51] {3343} INFO -  at 240.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:51] {3166} INFO - iteration 947, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:51] {3343} INFO -  at 241.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:51] {3166} INFO - iteration 948, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:51] {3343} INFO -  at 241.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:51] {3166} INFO - iteration 949, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:51] {3343} INFO -  at 241.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:51] {3166} INFO - iteration 950, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:51] {3343} INFO -  at 241.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:51] {3166} INFO - iteration 951, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:52] {3343} INFO -  at 241.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:52] {3166} INFO - iteration 952, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:52] {3343} INFO -  at 242.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:52] {3166} INFO - iteration 953, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:52] {3343} INFO -  at 242.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:52] {3166} INFO - iteration 954, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:52] {3343} INFO -  at 242.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:52] {3166} INFO - iteration 955, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:53] {3343} INFO -  at 243.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:53] {3166} INFO - iteration 956, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:53] {3343} INFO -  at 243.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:53] {3166} INFO - iteration 957, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:53] {3343} INFO -  at 243.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:53] {3166} INFO - iteration 958, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:53] {3343} INFO -  at 243.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:53] {3166} INFO - iteration 959, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:54] {3343} INFO -  at 243.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:54] {3166} INFO - iteration 960, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:54] {3343} INFO -  at 244.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:54] {3166} INFO - iteration 961, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:54] {3343} INFO -  at 244.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:54] {3166} INFO - iteration 962, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:54] {3343} INFO -  at 244.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:54] {3166} INFO - iteration 963, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:55] {3343} INFO -  at 244.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:55] {3166} INFO - iteration 964, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:55] {3343} INFO -  at 245.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:55] {3166} INFO - iteration 965, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:55] {3343} INFO -  at 245.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:55] {3166} INFO - iteration 966, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:55] {3343} INFO -  at 245.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:55] {3166} INFO - iteration 967, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:56] {3343} INFO -  at 245.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:56] {3166} INFO - iteration 968, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:56] {3343} INFO -  at 246.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:56] {3166} INFO - iteration 969, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:56] {3343} INFO -  at 246.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:56] {3166} INFO - iteration 970, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:56] {3343} INFO -  at 246.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:56] {3166} INFO - iteration 971, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:57] {3343} INFO -  at 246.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:57] {3166} INFO - iteration 972, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:57] {3343} INFO -  at 247.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:57] {3166} INFO - iteration 973, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:57] {3343} INFO -  at 247.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:57] {3166} INFO - iteration 974, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:57] {3343} INFO -  at 247.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:57] {3166} INFO - iteration 975, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:57] {3343} INFO -  at 247.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:57] {3166} INFO - iteration 976, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:57] {3343} INFO -  at 247.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:57] {3166} INFO - iteration 977, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:58] {3343} INFO -  at 247.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:58] {3166} INFO - iteration 978, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:33:58] {3343} INFO -  at 248.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:58] {3166} INFO - iteration 979, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:58] {3343} INFO -  at 248.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:58] {3166} INFO - iteration 980, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:58] {3343} INFO -  at 248.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:58] {3166} INFO - iteration 981, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:58] {3343} INFO -  at 248.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:58] {3166} INFO - iteration 982, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:59] {3343} INFO -  at 249.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:59] {3166} INFO - iteration 983, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:59] {3343} INFO -  at 249.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:59] {3166} INFO - iteration 984, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:59] {3343} INFO -  at 249.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:59] {3166} INFO - iteration 985, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:33:59] {3343} INFO -  at 249.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:33:59] {3166} INFO - iteration 986, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:00] {3343} INFO -  at 249.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:00] {3166} INFO - iteration 987, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:00] {3343} INFO -  at 250.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:00] {3166} INFO - iteration 988, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:00] {3343} INFO -  at 250.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:00] {3166} INFO - iteration 989, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:00] {3343} INFO -  at 250.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:00] {3166} INFO - iteration 990, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:01] {3343} INFO -  at 250.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:01] {3166} INFO - iteration 991, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:01] {3343} INFO -  at 251.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:01] {3166} INFO - iteration 992, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:01] {3343} INFO -  at 251.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:01] {3166} INFO - iteration 993, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:01] {3343} INFO -  at 251.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:01] {3166} INFO - iteration 994, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:02] {3343} INFO -  at 251.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:02] {3166} INFO - iteration 995, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:02] {3343} INFO -  at 252.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:02] {3166} INFO - iteration 996, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:02] {3343} INFO -  at 252.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:02] {3166} INFO - iteration 997, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:02] {3343} INFO -  at 252.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:02] {3166} INFO - iteration 998, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:03] {3343} INFO -  at 252.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:03] {3166} INFO - iteration 999, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:03] {3343} INFO -  at 253.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:03] {3166} INFO - iteration 1000, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:03] {3343} INFO -  at 253.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:03] {3166} INFO - iteration 1001, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:03] {3343} INFO -  at 253.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:03] {3166} INFO - iteration 1002, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:04] {3343} INFO -  at 253.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:04] {3166} INFO - iteration 1003, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:04] {3343} INFO -  at 254.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:04] {3166} INFO - iteration 1004, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:04] {3343} INFO -  at 254.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:04] {3166} INFO - iteration 1005, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:04] {3343} INFO -  at 254.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:04] {3166} INFO - iteration 1006, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:05] {3343} INFO -  at 254.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:05] {3166} INFO - iteration 1007, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:05] {3343} INFO -  at 255.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:05] {3166} INFO - iteration 1008, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:05] {3343} INFO -  at 255.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:05] {3166} INFO - iteration 1009, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:05] {3343} INFO -  at 255.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:05] {3166} INFO - iteration 1010, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:05] {3343} INFO -  at 255.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:05] {3166} INFO - iteration 1011, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:06] {3343} INFO -  at 256.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:06] {3166} INFO - iteration 1012, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:06] {3343} INFO -  at 256.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:06] {3166} INFO - iteration 1013, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:06] {3343} INFO -  at 256.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:06] {3166} INFO - iteration 1014, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:06] {3343} INFO -  at 256.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:06] {3166} INFO - iteration 1015, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:07] {3343} INFO -  at 257.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:07] {3166} INFO - iteration 1016, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:07] {3343} INFO -  at 257.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:07] {3166} INFO - iteration 1017, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:07] {3343} INFO -  at 257.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:07] {3166} INFO - iteration 1018, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:07] {3343} INFO -  at 257.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:07] {3166} INFO - iteration 1019, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:08] {3343} INFO -  at 257.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:08] {3166} INFO - iteration 1020, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:08] {3343} INFO -  at 258.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:08] {3166} INFO - iteration 1021, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:08] {3343} INFO -  at 258.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:08] {3166} INFO - iteration 1022, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:08] {3343} INFO -  at 258.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:08] {3166} INFO - iteration 1023, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:09] {3343} INFO -  at 258.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:09] {3166} INFO - iteration 1024, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:09] {3343} INFO -  at 259.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:09] {3166} INFO - iteration 1025, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:09] {3343} INFO -  at 259.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:09] {3166} INFO - iteration 1026, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:10] {3343} INFO -  at 259.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:10] {3166} INFO - iteration 1027, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:10] {3343} INFO -  at 260.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:10] {3166} INFO - iteration 1028, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:10] {3343} INFO -  at 260.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:10] {3166} INFO - iteration 1029, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:10] {3343} INFO -  at 260.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:10] {3166} INFO - iteration 1030, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:11] {3343} INFO -  at 260.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:11] {3166} INFO - iteration 1031, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:11] {3343} INFO -  at 261.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:11] {3166} INFO - iteration 1032, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:11] {3343} INFO -  at 261.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:11] {3166} INFO - iteration 1033, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:11] {3343} INFO -  at 261.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:11] {3166} INFO - iteration 1034, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:12] {3343} INFO -  at 261.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:12] {3166} INFO - iteration 1035, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:12] {3343} INFO -  at 262.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:12] {3166} INFO - iteration 1036, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:12] {3343} INFO -  at 262.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:12] {3166} INFO - iteration 1037, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:13] {3343} INFO -  at 262.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:13] {3166} INFO - iteration 1038, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:13] {3343} INFO -  at 263.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:13] {3166} INFO - iteration 1039, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:13] {3343} INFO -  at 263.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:13] {3166} INFO - iteration 1040, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:13] {3343} INFO -  at 263.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:13] {3166} INFO - iteration 1041, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:14] {3343} INFO -  at 263.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:14] {3166} INFO - iteration 1042, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:14] {3343} INFO -  at 264.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:14] {3166} INFO - iteration 1043, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:14] {3343} INFO -  at 264.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:14] {3166} INFO - iteration 1044, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:14] {3343} INFO -  at 264.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:14] {3166} INFO - iteration 1045, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:15] {3343} INFO -  at 264.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:15] {3166} INFO - iteration 1046, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:15] {3343} INFO -  at 265.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:15] {3166} INFO - iteration 1047, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:15] {3343} INFO -  at 265.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:15] {3166} INFO - iteration 1048, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:15] {3343} INFO -  at 265.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:15] {3166} INFO - iteration 1049, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:16] {3343} INFO -  at 266.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:16] {3166} INFO - iteration 1050, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:16] {3343} INFO -  at 266.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:16] {3166} INFO - iteration 1051, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:16] {3343} INFO -  at 266.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:16] {3166} INFO - iteration 1052, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:16] {3343} INFO -  at 266.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:16] {3166} INFO - iteration 1053, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:17] {3343} INFO -  at 267.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:17] {3166} INFO - iteration 1054, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:17] {3343} INFO -  at 267.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:17] {3166} INFO - iteration 1055, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:17] {3343} INFO -  at 267.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:17] {3166} INFO - iteration 1056, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:17] {3343} INFO -  at 267.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:17] {3166} INFO - iteration 1057, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:18] {3343} INFO -  at 267.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:18] {3166} INFO - iteration 1058, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:18] {3343} INFO -  at 268.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:18] {3166} INFO - iteration 1059, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:18] {3343} INFO -  at 268.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:18] {3166} INFO - iteration 1060, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:18] {3343} INFO -  at 268.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:18] {3166} INFO - iteration 1061, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:19] {3343} INFO -  at 268.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:19] {3166} INFO - iteration 1062, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:19] {3343} INFO -  at 269.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:19] {3166} INFO - iteration 1063, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:19] {3343} INFO -  at 269.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:19] {3166} INFO - iteration 1064, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:19] {3343} INFO -  at 269.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:19] {3166} INFO - iteration 1065, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:20] {3343} INFO -  at 269.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:20] {3166} INFO - iteration 1066, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:20] {3343} INFO -  at 270.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:20] {3166} INFO - iteration 1067, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:20] {3343} INFO -  at 270.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:20] {3166} INFO - iteration 1068, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:20] {3343} INFO -  at 270.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:20] {3166} INFO - iteration 1069, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:20] {3343} INFO -  at 270.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:20] {3166} INFO - iteration 1070, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:20] {3343} INFO -  at 270.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:20] {3166} INFO - iteration 1071, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:21] {3343} INFO -  at 271.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:21] {3166} INFO - iteration 1072, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:21] {3343} INFO -  at 271.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:21] {3166} INFO - iteration 1073, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:21] {3343} INFO -  at 271.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:21] {3166} INFO - iteration 1074, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:21] {3343} INFO -  at 271.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:21] {3166} INFO - iteration 1075, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:21] {3343} INFO -  at 271.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:21] {3166} INFO - iteration 1076, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:22] {3343} INFO -  at 271.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:22] {3166} INFO - iteration 1077, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:22] {3343} INFO -  at 272.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:22] {3166} INFO - iteration 1078, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:22] {3343} INFO -  at 272.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:22] {3166} INFO - iteration 1079, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:22] {3343} INFO -  at 272.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:22] {3166} INFO - iteration 1080, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:22] {3343} INFO -  at 272.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:22] {3166} INFO - iteration 1081, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:23] {3343} INFO -  at 272.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:23] {3166} INFO - iteration 1082, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:23] {3343} INFO -  at 273.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964

[flaml.automl: 04-23 11:34:23] {3166} INFO - iteration 1083, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:23] {3343} INFO -  at 273.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:23] {3166} INFO - iteration 1084, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:23] {3343} INFO -  at 273.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:23] {3166} INFO - iteration 1085, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:23] {3343} INFO -  at 273.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:23] {3166} INFO - iteration 1086, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:24] {3343} INFO -  at 273.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:24] {3166} INFO - iteration 1087, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:24] {3343} INFO -  at 274.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:24] {3166} INFO - iteration 1088, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:24] {3343} INFO -  at 274.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:24] {3166} INFO - iteration 1089, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:24] {3343} INFO -  at 274.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:24] {3166} INFO - iteration 1090, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:24] {3343} INFO -  at 274.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:24] {3166} INFO - iteration 1091, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:24] {3343} INFO -  at 274.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:24] {3166} INFO - iteration 1092, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:25] {3343} INFO -  at 275.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:25] {3166} INFO - iteration 1093, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:25] {3343} INFO -  at 275.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:25] {3166} INFO - iteration 1094, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:25] {3343} INFO -  at 275.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:25] {3166} INFO - iteration 1095, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:25] {3343} INFO -  at 275.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:25] {3166} INFO - iteration 1096, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:25] {3343} INFO -  at 275.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:25] {3166} INFO - iteration 1097, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:26] {3343} INFO -  at 276.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:26] {3166} INFO - iteration 1098, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:26] {3343} INFO -  at 276.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:26] {3166} INFO - iteration 1099, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:26] {3343} INFO -  at 276.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:26] {3166} INFO - iteration 1100, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:26] {3343} INFO -  at 276.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:26] {3166} INFO - iteration 1101, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:26] {3343} INFO -  at 276.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:26] {3166} INFO - iteration 1102, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:27] {3343} INFO -  at 276.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:27] {3166} INFO - iteration 1103, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:27] {3343} INFO -  at 277.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:27] {3166} INFO - iteration 1104, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:27] {3343} INFO -  at 277.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:27] {3166} INFO - iteration 1105, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:27] {3343} INFO -  at 277.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:27] {3166} INFO - iteration 1106, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:27] {3343} INFO -  at 277.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:27] {3166} INFO - iteration 1107, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:27] {3343} INFO -  at 277.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:27] {3166} INFO - iteration 1108, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:28] {3343} INFO -  at 278.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:28] {3166} INFO - iteration 1109, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:28] {3343} INFO -  at 278.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:28] {3166} INFO - iteration 1110, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:28] {3343} INFO -  at 278.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:28] {3166} INFO - iteration 1111, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:28] {3343} INFO -  at 278.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:28] {3166} INFO - iteration 1112, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:29] {3343} INFO -  at 278.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:29] {3166} INFO - iteration 1113, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:29] {3343} INFO -  at 279.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:29] {3166} INFO - iteration 1114, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:29] {3343} INFO -  at 279.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:29] {3166} INFO - iteration 1115, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:29] {3343} INFO -  at 279.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:29] {3166} INFO - iteration 1116, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:29] {3343} INFO -  at 279.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:29] {3166} INFO - iteration 1117, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:29] {3343} INFO -  at 279.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:29] {3166} INFO - iteration 1118, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:30] {3343} INFO -  at 279.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:30] {3166} INFO - iteration 1119, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:30] {3343} INFO -  at 280.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:30] {3166} INFO - iteration 1120, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:30] {3343} INFO -  at 280.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:30] {3166} INFO - iteration 1121, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:30] {3343} INFO -  at 280.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:30] {3166} INFO - iteration 1122, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:30] {3343} INFO -  at 280.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:30] {3166} INFO - iteration 1123, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:30] {3343} INFO -  at 280.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:30] {3166} INFO - iteration 1124, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:31] {3343} INFO -  at 280.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:31] {3166} INFO - iteration 1125, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:31] {3343} INFO -  at 281.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:31] {3166} INFO - iteration 1126, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:31] {3343} INFO -  at 281.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:31] {3166} INFO - iteration 1127, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:31] {3343} INFO -  at 281.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:31] {3166} INFO - iteration 1128, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:31] {3343} INFO -  at 281.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:31] {3166} INFO - iteration 1129, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:31] {3343} INFO -  at 281.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:31] {3166} INFO - iteration 1130, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:32] {3343} INFO -  at 281.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:32] {3166} INFO - iteration 1131, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:32] {3343} INFO -  at 282.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:32] {3166} INFO - iteration 1132, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:32] {3343} INFO -  at 282.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:32] {3166} INFO - iteration 1133, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:32] {3343} INFO -  at 282.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:32] {3166} INFO - iteration 1134, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:32] {3343} INFO -  at 282.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:32] {3166} INFO - iteration 1135, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:32] {3343} INFO -  at 282.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:32] {3166} INFO - iteration 1136, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:33] {3343} INFO -  at 282.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:33] {3166} INFO - iteration 1137, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:33] {3343} INFO -  at 283.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:33] {3166} INFO - iteration 1138, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:33] {3343} INFO -  at 283.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:33] {3166} INFO - iteration 1139, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:33] {3343} INFO -  at 283.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:33] {3166} INFO - iteration 1140, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:33] {3343} INFO -  at 283.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:33] {3166} INFO - iteration 1141, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:33] {3343} INFO -  at 283.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:33] {3166} INFO - iteration 1142, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:34] {3343} INFO -  at 283.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:34] {3166} INFO - iteration 1143, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:34] {3343} INFO -  at 284.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:34] {3166} INFO - iteration 1144, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:34] {3343} INFO -  at 284.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:34] {3166} INFO - iteration 1145, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:34] {3343} INFO -  at 284.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:34] {3166} INFO - iteration 1146, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:34] {3343} INFO -  at 284.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:34] {3166} INFO - iteration 1147, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:34] {3343} INFO -  at 284.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:35] {3166} INFO - iteration 1148, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:35] {3343} INFO -  at 285.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:35] {3166} INFO - iteration 1149, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:35] {3343} INFO -  at 285.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:35] {3166} INFO - iteration 1150, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:35] {3343} INFO -  at 285.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:35] {3166} INFO - iteration 1151, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:35] {3343} INFO -  at 285.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:35] {3166} INFO - iteration 1152, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:35] {3343} INFO -  at 285.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:35] {3166} INFO - iteration 1153, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:36] {3343} INFO -  at 285.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:36] {3166} INFO - iteration 1154, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:36] {3343} INFO -  at 286.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:36] {3166} INFO - iteration 1155, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:36] {3343} INFO -  at 286.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:36] {3166} INFO - iteration 1156, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:36] {3343} INFO -  at 286.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:36] {3166} INFO - iteration 1157, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:37] {3343} INFO -  at 286.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:37] {3166} INFO - iteration 1158, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:37] {3343} INFO -  at 287.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:37] {3166} INFO - iteration 1159, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:37] {3343} INFO -  at 287.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:37] {3166} INFO - iteration 1160, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:37] {3343} INFO -  at 287.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:37] {3166} INFO - iteration 1161, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:37] {3343} INFO -  at 287.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:37] {3166} INFO - iteration 1162, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:37] {3343} INFO -  at 287.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:37] {3166} INFO - iteration 1163, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:38] {3343} INFO -  at 287.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:38] {3166} INFO - iteration 1164, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:38] {3343} INFO -  at 288.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:38] {3166} INFO - iteration 1165, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:38] {3343} INFO -  at 288.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:38] {3166} INFO - iteration 1166, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:38] {3343} INFO -  at 288.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:38] {3166} INFO - iteration 1167, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:38] {3343} INFO -  at 288.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:38] {3166} INFO - iteration 1168, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:39] {3343} INFO -  at 288.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:39] {3166} INFO - iteration 1169, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:39] {3343} INFO -  at 289.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:39] {3166} INFO - iteration 1170, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:39] {3343} INFO -  at 289.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:39] {3166} INFO - iteration 1171, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:39] {3343} INFO -  at 289.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:39] {3166} INFO - iteration 1172, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:39] {3343} INFO -  at 289.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:39] {3166} INFO - iteration 1173, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:39] {3343} INFO -  at 289.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:39] {3166} INFO - iteration 1174, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:40] {3343} INFO -  at 290.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:40] {3166} INFO - iteration 1175, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:40] {3343} INFO -  at 290.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:40] {3166} INFO - iteration 1176, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:40] {3343} INFO -  at 290.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:40] {3166} INFO - iteration 1177, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:41] {3343} INFO -  at 290.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:41] {3166} INFO - iteration 1178, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:41] {3343} INFO -  at 291.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:41] {3166} INFO - iteration 1179, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:41] {3343} INFO -  at 291.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:41] {3166} INFO - iteration 1180, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:41] {3343} INFO -  at 291.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:41] {3166} INFO - iteration 1181, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:41] {3343} INFO -  at 291.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:41] {3166} INFO - iteration 1182, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:42] {3343} INFO -  at 291.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:42] {3166} INFO - iteration 1183, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:42] {3343} INFO -  at 292.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:42] {3166} INFO - iteration 1184, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:42] {3343} INFO -  at 292.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:42] {3166} INFO - iteration 1185, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:42] {3343} INFO -  at 292.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:42] {3166} INFO - iteration 1186, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:42] {3343} INFO -  at 292.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:42] {3166} INFO - iteration 1187, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:42] {3343} INFO -  at 292.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:42] {3166} INFO - iteration 1188, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:43] {3343} INFO -  at 292.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:43] {3166} INFO - iteration 1189, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:43] {3343} INFO -  at 293.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:43] {3166} INFO - iteration 1190, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:43] {3343} INFO -  at 293.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:43] {3166} INFO - iteration 1191, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:43] {3343} INFO -  at 293.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:43] {3166} INFO - iteration 1192, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:44] {3343} INFO -  at 293.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:44] {3166} INFO - iteration 1193, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:44] {3343} INFO -  at 294.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:44] {3166} INFO - iteration 1194, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:44] {3343} INFO -  at 294.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:44] {3166} INFO - iteration 1195, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:44] {3343} INFO -  at 294.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:44] {3166} INFO - iteration 1196, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:44] {3343} INFO -  at 294.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:44] {3166} INFO - iteration 1197, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:45] {3343} INFO -  at 294.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:45] {3166} INFO - iteration 1198, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:45] {3343} INFO -  at 295.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:45] {3166} INFO - iteration 1199, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:45] {3343} INFO -  at 295.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964

[flaml.automl: 04-23 11:34:45] {3166} INFO - iteration 1200, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:45] {3343} INFO -  at 295.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:45] {3166} INFO - iteration 1201, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:45] {3343} INFO -  at 295.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:45] {3166} INFO - iteration 1202, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:46] {3343} INFO -  at 295.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:46] {3166} INFO - iteration 1203, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:46] {3343} INFO -  at 296.0s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:46] {3166} INFO - iteration 1204, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:46] {3343} INFO -  at 296.2s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:46] {3166} INFO - iteration 1205, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:46] {3343} INFO -  at 296.4s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:46] {3166} INFO - iteration 1206, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:46] {3343} INFO -  at 296.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:46] {3166} INFO - iteration 1207, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:47] {3343} INFO -  at 296.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:47] {3166} INFO - iteration 1208, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:47] {3343} INFO -  at 297.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:47] {3166} INFO - iteration 1209, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:47] {3343} INFO -  at 297.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:47] {3166} INFO - iteration 1210, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:47] {3343} INFO -  at 297.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:47] {3166} INFO - iteration 1211, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:47] {3343} INFO -  at 297.7s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:47] {3166} INFO - iteration 1212, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:48] {3343} INFO -  at 297.9s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:48] {3166} INFO - iteration 1213, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:48] {3343} INFO -  at 298.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:48] {3166} INFO - iteration 1214, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:48] {3343} INFO -  at 298.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:48] {3166} INFO - iteration 1215, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:48] {3343} INFO -  at 298.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:48] {3166} INFO - iteration 1216, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:48] {3343} INFO -  at 298.6s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:48] {3166} INFO - iteration 1217, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:49] {3343} INFO -  at 298.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:49] {3166} INFO - iteration 1218, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:49] {3343} INFO -  at 299.1s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:49] {3166} INFO - iteration 1219, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:49] {3343} INFO -  at 299.3s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:49] {3166} INFO - iteration 1220, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:49] {3343} INFO -  at 299.5s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:49] {3166} INFO - iteration 1221, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:50] {3343} INFO -  at 299.8s,	estimator rf's best error=75.1964,	best estimator rf's best error=75.1964
[flaml.automl: 04-23 11:34:50] {3602} INFO - retrain rf for 0.2s
[flaml.automl: 04-23 11:34:50] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.9439387899044492, max_leaf_nodes=1212,
                      n_estimators=31, n_jobs=-1)
[flaml.automl: 04-23 11:34:50] {2901} INFO - fit succeeded
[flaml.automl: 04-23 11:34:50] {2902} INFO - Time taken to find the best model: 62.65661978721619
[flaml.automl: 04-23 11:34:50] {2599} INFO - task = regression
[flaml.automl: 04-23 11:34:50] {2601} INFO - Data split method: uniform
[flaml.automl: 04-23 11:34:50] {2604} INFO - Evaluation method: holdout
[flaml.automl: 04-23 11:34:50] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 04-23 11:34:50] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 04-23 11:34:50] {3166} INFO - iteration 0, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:50] {3296} INFO - Estimated sufficient time budget=349s. Estimated necessary time budget=0s.
[flaml.automl: 04-23 11:34:50] {3343} INFO -  at 0.1s,	estimator rf's best error=138.3053,	best estimator rf's best error=138.3053
[flaml.automl: 04-23 11:34:50] {3166} INFO - iteration 1, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:50] {3343} INFO -  at 0.1s,	estimator rf's best error=117.1958,	best estimator rf's best error=117.1958

[flaml.automl: 04-23 11:34:50] {3166} INFO - iteration 2, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:50] {3343} INFO -  at 0.2s,	estimator rf's best error=117.1958,	best estimator rf's best error=117.1958
[flaml.automl: 04-23 11:34:50] {3166} INFO - iteration 3, current learner rf

0.93 0.85 0.29

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:50] {3343} INFO -  at 0.3s,	estimator rf's best error=104.7648,	best estimator rf's best error=104.7648
[flaml.automl: 04-23 11:34:50] {3166} INFO - iteration 4, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:50] {3343} INFO -  at 0.3s,	estimator rf's best error=102.8686,	best estimator rf's best error=102.8686
[flaml.automl: 04-23 11:34:50] {3166} INFO - iteration 5, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:50] {3343} INFO -  at 0.4s,	estimator rf's best error=102.8686,	best estimator rf's best error=102.8686
[flaml.automl: 04-23 11:34:50] {3166} INFO - iteration 6, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:50] {3343} INFO -  at 0.4s,	estimator rf's best error=95.3401,	best estimator rf's best error=95.3401
[flaml.automl: 04-23 11:34:50] {3166} INFO - iteration 7, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:50] {3343} INFO -  at 0.5s,	estimator rf's best error=95.3401,	best estimator rf's best error=95.3401
[flaml.automl: 04-23 11:34:50] {3166} INFO - iteration 8, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:50] {3343} INFO -  at 0.6s,	estimator rf's best error=91.3748,	best estimator rf's best error=91.3748
[flaml.automl: 04-23 11:34:50] {3166} INFO - iteration 9, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:50] {3343} INFO -  at 0.6s,	estimator rf's best error=91.3748,	best estimator rf's best error=91.3748
[flaml.automl: 04-23 11:34:50] {3166} INFO - iteration 10, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:50] {3343} INFO -  at 0.7s,	estimator rf's best error=91.3748,	best estimator rf's best error=91.3748
[flaml.automl: 04-23 11:34:50] {3166} INFO - iteration 11, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:51] {3343} INFO -  at 1.0s,	estimator rf's best error=91.3748,	best estimator rf's best error=91.3748
[flaml.automl: 04-23 11:34:51] {3166} INFO - iteration 12, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:51] {3343} INFO -  at 1.0s,	estimator rf's best error=91.3748,	best estimator rf's best error=91.3748
[flaml.automl: 04-23 11:34:51] {3166} INFO - iteration 13, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:51] {3343} INFO -  at 1.2s,	estimator rf's best error=90.7944,	best estimator rf's best error=90.7944
[flaml.automl: 04-23 11:34:51] {3166} INFO - iteration 14, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:51] {3343} INFO -  at 1.4s,	estimator rf's best error=90.7944,	best estimator rf's best error=90.7944
[flaml.automl: 04-23 11:34:51] {3166} INFO - iteration 15, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:51] {3343} INFO -  at 1.7s,	estimator rf's best error=88.1826,	best estimator rf's best error=88.1826
[flaml.automl: 04-23 11:34:51] {3166} INFO - iteration 16, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:52] {3343} INFO -  at 1.8s,	estimator rf's best error=88.1826,	best estimator rf's best error=88.1826
[flaml.automl: 04-23 11:34:52] {3166} INFO - iteration 17, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:52] {3343} INFO -  at 2.8s,	estimator rf's best error=88.1826,	best estimator rf's best error=88.1826
[flaml.automl: 04-23 11:34:52] {3166} INFO - iteration 18, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:53] {3343} INFO -  at 3.5s,	estimator rf's best error=86.7995,	best estimator rf's best error=86.7995
[flaml.automl: 04-23 11:34:53] {3166} INFO - iteration 19, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:54] {3343} INFO -  at 3.8s,	estimator rf's best error=86.7995,	best estimator rf's best error=86.7995
[flaml.automl: 04-23 11:34:54] {3166} INFO - iteration 20, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:55] {3343} INFO -  at 5.0s,	estimator rf's best error=86.7995,	best estimator rf's best error=86.7995
[flaml.automl: 04-23 11:34:55] {3166} INFO - iteration 21, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:55] {3343} INFO -  at 5.2s,	estimator rf's best error=86.7995,	best estimator rf's best error=86.7995
[flaml.automl: 04-23 11:34:55] {3166} INFO - iteration 22, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:55] {3343} INFO -  at 5.5s,	estimator rf's best error=86.7995,	best estimator rf's best error=86.7995
[flaml.automl: 04-23 11:34:55] {3166} INFO - iteration 23, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:56] {3343} INFO -  at 6.6s,	estimator rf's best error=86.7995,	best estimator rf's best error=86.7995
[flaml.automl: 04-23 11:34:56] {3166} INFO - iteration 24, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:57] {3343} INFO -  at 7.3s,	estimator rf's best error=86.7995,	best estimator rf's best error=86.7995
[flaml.automl: 04-23 11:34:57] {3166} INFO - iteration 25, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:57] {3343} INFO -  at 7.8s,	estimator rf's best error=86.7995,	best estimator rf's best error=86.7995
[flaml.automl: 04-23 11:34:57] {3166} INFO - iteration 26, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:59] {3343} INFO -  at 8.9s,	estimator rf's best error=86.7995,	best estimator rf's best error=86.7995
[flaml.automl: 04-23 11:34:59] {3166} INFO - iteration 27, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:34:59] {3343} INFO -  at 9.1s,	estimator rf's best error=86.7995,	best estimator rf's best error=86.7995
[flaml.automl: 04-23 11:34:59] {3166} INFO - iteration 28, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:34:59] {3343} INFO -  at 9.8s,	estimator rf's best error=86.7995,	best estimator rf's best error=86.7995
[flaml.automl: 04-23 11:34:59] {3166} INFO - iteration 29, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:00] {3343} INFO -  at 10.2s,	estimator rf's best error=86.7995,	best estimator rf's best error=86.7995
[flaml.automl: 04-23 11:35:00] {3166} INFO - iteration 30, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:00] {3343} INFO -  at 10.6s,	estimator rf's best error=86.7896,	best estimator rf's best error=86.7896
[flaml.automl: 04-23 11:35:00] {3166} INFO - iteration 31, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:01] {3343} INFO -  at 11.2s,	estimator rf's best error=86.5227,	best estimator rf's best error=86.5227
[flaml.automl: 04-23 11:35:01] {3166} INFO - iteration 32, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:02] {3343} INFO -  at 11.8s,	estimator rf's best error=86.5227,	best estimator rf's best error=86.5227
[flaml.automl: 04-23 11:35:02] {3166} INFO - iteration 33, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:02] {3343} INFO -  at 12.3s,	estimator rf's best error=86.5227,	best estimator rf's best error=86.5227
[flaml.automl: 04-23 11:35:02] {3166} INFO - iteration 34, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:03] {3343} INFO -  at 13.2s,	estimator rf's best error=86.5227,	best estimator rf's best error=86.5227
[flaml.automl: 04-23 11:35:03] {3166} INFO - iteration 35, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:03] {3343} INFO -  at 13.5s,	estimator rf's best error=86.5227,	best estimator rf's best error=86.5227
[flaml.automl: 04-23 11:35:03] {3166} INFO - iteration 36, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:03] {3343} INFO -  at 13.8s,	estimator rf's best error=86.5227,	best estimator rf's best error=86.5227
[flaml.automl: 04-23 11:35:03] {3166} INFO - iteration 37, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:05] {3343} INFO -  at 14.8s,	estimator rf's best error=86.4983,	best estimator rf's best error=86.4983
[flaml.automl: 04-23 11:35:05] {3166} INFO - iteration 38, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:07] {3343} INFO -  at 17.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:07] {3166} INFO - iteration 39, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:08] {3343} INFO -  at 17.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:08] {3166} INFO - iteration 40, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:10] {3343} INFO -  at 20.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:10] {3166} INFO - iteration 41, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:35:11] {3343} INFO -  at 21.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:11] {3166} INFO - iteration 42, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:12] {3343} INFO -  at 22.5s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:12] {3166} INFO - iteration 43, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:14] {3343} INFO -  at 24.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:14] {3166} INFO - iteration 44, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:16] {3343} INFO -  at 26.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:16] {3166} INFO - iteration 45, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:18] {3343} INFO -  at 28.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:18] {3166} INFO - iteration 46, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:22] {3343} INFO -  at 31.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:22] {3166} INFO - iteration 47, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:22] {3343} INFO -  at 32.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:22] {3166} INFO - iteration 48, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:24] {3343} INFO -  at 33.8s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:24] {3166} INFO - iteration 49, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:27] {3343} INFO -  at 37.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:27] {3166} INFO - iteration 50, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:30] {3343} INFO -  at 40.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:30] {3166} INFO - iteration 51, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:31] {3343} INFO -  at 41.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:31] {3166} INFO - iteration 52, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:33] {3343} INFO -  at 43.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:33] {3166} INFO - iteration 53, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:34] {3343} INFO -  at 44.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:34] {3166} INFO - iteration 54, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:35:35] {3343} INFO -  at 45.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:35] {3166} INFO - iteration 55, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:37] {3343} INFO -  at 47.3s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:37] {3166} INFO - iteration 56, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:39] {3343} INFO -  at 49.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:39] {3166} INFO - iteration 57, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:40] {3343} INFO -  at 50.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:40] {3166} INFO - iteration 58, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:41] {3343} INFO -  at 51.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:41] {3166} INFO - iteration 59, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:42] {3343} INFO -  at 52.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:42] {3166} INFO - iteration 60, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:43] {3343} INFO -  at 53.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:43] {3166} INFO - iteration 61, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:44] {3343} INFO -  at 54.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:44] {3166} INFO - iteration 62, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:47] {3343} INFO -  at 57.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:47] {3166} INFO - iteration 63, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:48] {3343} INFO -  at 58.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:48] {3166} INFO - iteration 64, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:50] {3343} INFO -  at 59.8s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:50] {3166} INFO - iteration 65, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:51] {3343} INFO -  at 61.5s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:51] {3166} INFO - iteration 66, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:52] {3343} INFO -  at 62.5s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:52] {3166} INFO - iteration 67, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:35:54] {3343} INFO -  at 64.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:54] {3166} INFO - iteration 68, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:55] {3343} INFO -  at 65.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:55] {3166} INFO - iteration 69, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:57] {3343} INFO -  at 67.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:57] {3166} INFO - iteration 70, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:35:59] {3343} INFO -  at 69.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:35:59] {3166} INFO - iteration 71, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:00] {3343} INFO -  at 70.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:00] {3166} INFO - iteration 72, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:01] {3343} INFO -  at 71.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:01] {3166} INFO - iteration 73, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:04] {3343} INFO -  at 74.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:04] {3166} INFO - iteration 74, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:04] {3343} INFO -  at 74.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:04] {3166} INFO - iteration 75, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:06] {3343} INFO -  at 76.3s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:06] {3166} INFO - iteration 76, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:08] {3343} INFO -  at 78.3s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:08] {3166} INFO - iteration 77, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:09] {3343} INFO -  at 79.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:09] {3166} INFO - iteration 78, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:10] {3343} INFO -  at 80.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:10] {3166} INFO - iteration 79, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:12] {3343} INFO -  at 82.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:12] {3166} INFO - iteration 80, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:36:14] {3343} INFO -  at 83.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:14] {3166} INFO - iteration 81, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:16] {3343} INFO -  at 86.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:16] {3166} INFO - iteration 82, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:17] {3343} INFO -  at 87.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:17] {3166} INFO - iteration 83, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:19] {3343} INFO -  at 89.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:19] {3166} INFO - iteration 84, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:20] {3343} INFO -  at 90.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:20] {3166} INFO - iteration 85, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:23] {3343} INFO -  at 93.3s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:23] {3166} INFO - iteration 86, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:25] {3343} INFO -  at 95.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:25] {3166} INFO - iteration 87, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:26] {3343} INFO -  at 96.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:26] {3166} INFO - iteration 88, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:27] {3343} INFO -  at 97.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:27] {3166} INFO - iteration 89, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:31] {3343} INFO -  at 101.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:31] {3166} INFO - iteration 90, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:33] {3343} INFO -  at 103.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:33] {3166} INFO - iteration 91, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:35] {3343} INFO -  at 105.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:35] {3166} INFO - iteration 92, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:36] {3343} INFO -  at 106.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:36] {3166} INFO - iteration 93, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:36:37] {3343} INFO -  at 107.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:37] {3166} INFO - iteration 94, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:39] {3343} INFO -  at 109.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:39] {3166} INFO - iteration 95, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:40] {3343} INFO -  at 110.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:40] {3166} INFO - iteration 96, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:43] {3343} INFO -  at 112.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:43] {3166} INFO - iteration 97, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:44] {3343} INFO -  at 114.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:44] {3166} INFO - iteration 98, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:45] {3343} INFO -  at 114.8s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:45] {3166} INFO - iteration 99, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:47] {3343} INFO -  at 116.8s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:47] {3166} INFO - iteration 100, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:48] {3343} INFO -  at 118.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:48] {3166} INFO - iteration 101, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:50] {3343} INFO -  at 119.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:50] {3166} INFO - iteration 102, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:53] {3343} INFO -  at 123.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:53] {3166} INFO - iteration 103, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:54] {3343} INFO -  at 123.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:54] {3166} INFO - iteration 104, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:56] {3343} INFO -  at 126.3s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:56] {3166} INFO - iteration 105, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:36:57] {3343} INFO -  at 127.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:57] {3166} INFO - iteration 106, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:36:58] {3343} INFO -  at 128.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:36:58] {3166} INFO - iteration 107, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:01] {3343} INFO -  at 131.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:01] {3166} INFO - iteration 108, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:02] {3343} INFO -  at 132.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:02] {3166} INFO - iteration 109, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:05] {3343} INFO -  at 134.8s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:05] {3166} INFO - iteration 110, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:06] {3343} INFO -  at 136.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:06] {3166} INFO - iteration 111, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:07] {3343} INFO -  at 136.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:07] {3166} INFO - iteration 112, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:08] {3343} INFO -  at 138.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:08] {3166} INFO - iteration 113, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:09] {3343} INFO -  at 139.5s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:09] {3166} INFO - iteration 114, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:11] {3343} INFO -  at 140.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:11] {3166} INFO - iteration 115, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:12] {3343} INFO -  at 142.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:12] {3166} INFO - iteration 116, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:13] {3343} INFO -  at 143.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:13] {3166} INFO - iteration 117, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:16] {3343} INFO -  at 145.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:16] {3166} INFO - iteration 118, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:16] {3343} INFO -  at 146.8s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:16] {3166} INFO - iteration 119, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:37:19] {3343} INFO -  at 149.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:19] {3166} INFO - iteration 120, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:19] {3343} INFO -  at 149.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:19] {3166} INFO - iteration 121, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:21] {3343} INFO -  at 151.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:21] {3166} INFO - iteration 122, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:23] {3343} INFO -  at 153.5s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:23] {3166} INFO - iteration 123, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:24] {3343} INFO -  at 154.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:24] {3166} INFO - iteration 124, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:26] {3343} INFO -  at 156.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:26] {3166} INFO - iteration 125, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:27] {3343} INFO -  at 157.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:27] {3166} INFO - iteration 126, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:28] {3343} INFO -  at 158.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:28] {3166} INFO - iteration 127, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:30] {3343} INFO -  at 159.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:30] {3166} INFO - iteration 128, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:31] {3343} INFO -  at 161.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:31] {3166} INFO - iteration 129, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:33] {3343} INFO -  at 162.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:33] {3166} INFO - iteration 130, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:35] {3343} INFO -  at 165.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:35] {3166} INFO - iteration 131, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:36] {3343} INFO -  at 166.3s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:36] {3166} INFO - iteration 132, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:37:37] {3343} INFO -  at 167.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:37] {3166} INFO - iteration 133, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:38] {3343} INFO -  at 168.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:38] {3166} INFO - iteration 134, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:39] {3343} INFO -  at 169.3s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:39] {3166} INFO - iteration 135, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:41] {3343} INFO -  at 170.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:41] {3166} INFO - iteration 136, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:43] {3343} INFO -  at 173.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:43] {3166} INFO - iteration 137, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:44] {3343} INFO -  at 174.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:44] {3166} INFO - iteration 138, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:45] {3343} INFO -  at 175.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:45] {3166} INFO - iteration 139, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:47] {3343} INFO -  at 177.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:47] {3166} INFO - iteration 140, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:49] {3343} INFO -  at 179.5s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:49] {3166} INFO - iteration 141, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:50] {3343} INFO -  at 180.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:50] {3166} INFO - iteration 142, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:53] {3343} INFO -  at 182.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:53] {3166} INFO - iteration 143, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:54] {3343} INFO -  at 184.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:54] {3166} INFO - iteration 144, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:56] {3343} INFO -  at 186.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:56] {3166} INFO - iteration 145, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:37:57] {3343} INFO -  at 187.3s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:57] {3166} INFO - iteration 146, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:37:58] {3343} INFO -  at 188.8s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:37:58] {3166} INFO - iteration 147, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:00] {3343} INFO -  at 190.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:00] {3166} INFO - iteration 148, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:01] {3343} INFO -  at 191.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:01] {3166} INFO - iteration 149, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:03] {3343} INFO -  at 192.8s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:03] {3166} INFO - iteration 150, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:05] {3343} INFO -  at 194.8s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:05] {3166} INFO - iteration 151, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:06] {3343} INFO -  at 195.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:06] {3166} INFO - iteration 152, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:07] {3343} INFO -  at 197.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:07] {3166} INFO - iteration 153, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:08] {3343} INFO -  at 198.5s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:08] {3166} INFO - iteration 154, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:10] {3343} INFO -  at 200.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:10] {3166} INFO - iteration 155, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:11] {3343} INFO -  at 201.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:11] {3166} INFO - iteration 156, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:13] {3343} INFO -  at 203.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:13] {3166} INFO - iteration 157, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:14] {3343} INFO -  at 204.3s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:14] {3166} INFO - iteration 158, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:38:15] {3343} INFO -  at 205.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:15] {3166} INFO - iteration 159, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:16] {3343} INFO -  at 206.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:16] {3166} INFO - iteration 160, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:18] {3343} INFO -  at 208.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:18] {3166} INFO - iteration 161, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:19] {3343} INFO -  at 209.3s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:19] {3166} INFO - iteration 162, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:20] {3343} INFO -  at 210.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:20] {3166} INFO - iteration 163, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:22] {3343} INFO -  at 211.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:22] {3166} INFO - iteration 164, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:23] {3343} INFO -  at 213.5s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:23] {3166} INFO - iteration 165, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:24] {3343} INFO -  at 214.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:24] {3166} INFO - iteration 166, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:26] {3343} INFO -  at 216.3s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:26] {3166} INFO - iteration 167, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:27] {3343} INFO -  at 217.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:27] {3166} INFO - iteration 168, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:28] {3343} INFO -  at 218.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:28] {3166} INFO - iteration 169, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:30] {3343} INFO -  at 220.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:30] {3166} INFO - iteration 170, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:31] {3343} INFO -  at 221.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:31] {3166} INFO - iteration 171, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:38:33] {3343} INFO -  at 223.5s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:33] {3166} INFO - iteration 172, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:35] {3343} INFO -  at 225.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:35] {3166} INFO - iteration 173, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:36] {3343} INFO -  at 226.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:36] {3166} INFO - iteration 174, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:37] {3343} INFO -  at 227.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:37] {3166} INFO - iteration 175, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:40] {3343} INFO -  at 229.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:40] {3166} INFO - iteration 176, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:41] {3343} INFO -  at 231.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:41] {3166} INFO - iteration 177, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:43] {3343} INFO -  at 233.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:43] {3166} INFO - iteration 178, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:44] {3343} INFO -  at 234.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:44] {3166} INFO - iteration 179, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:45] {3343} INFO -  at 235.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:45] {3166} INFO - iteration 180, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:47] {3343} INFO -  at 237.3s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:47] {3166} INFO - iteration 181, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:48] {3343} INFO -  at 238.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:48] {3166} INFO - iteration 182, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:49] {3343} INFO -  at 239.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:49] {3166} INFO - iteration 183, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:51] {3343} INFO -  at 241.3s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:51] {3166} INFO - iteration 184, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:38:52] {3343} INFO -  at 242.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:52] {3166} INFO - iteration 185, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:53] {3343} INFO -  at 243.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:53] {3166} INFO - iteration 186, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:55] {3343} INFO -  at 245.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:55] {3166} INFO - iteration 187, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:56] {3343} INFO -  at 246.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:56] {3166} INFO - iteration 188, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:58] {3343} INFO -  at 247.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:58] {3166} INFO - iteration 189, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:38:59] {3343} INFO -  at 248.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:38:59] {3166} INFO - iteration 190, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:00] {3343} INFO -  at 250.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:00] {3166} INFO - iteration 191, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:01] {3343} INFO -  at 251.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:01] {3166} INFO - iteration 192, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:02] {3343} INFO -  at 252.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:02] {3166} INFO - iteration 193, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:04] {3343} INFO -  at 254.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:04] {3166} INFO - iteration 194, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:06] {3343} INFO -  at 256.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:06] {3166} INFO - iteration 195, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:08] {3343} INFO -  at 257.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:08] {3166} INFO - iteration 196, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:09] {3343} INFO -  at 258.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:09] {3166} INFO - iteration 197, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:39:10] {3343} INFO -  at 259.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:10] {3166} INFO - iteration 198, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:12] {3343} INFO -  at 262.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:12] {3166} INFO - iteration 199, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:14] {3343} INFO -  at 264.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:14] {3166} INFO - iteration 200, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:15] {3343} INFO -  at 265.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:15] {3166} INFO - iteration 201, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:17] {3343} INFO -  at 267.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:17] {3166} INFO - iteration 202, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:19] {3343} INFO -  at 269.2s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:19] {3166} INFO - iteration 203, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:21] {3343} INFO -  at 271.3s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:21] {3166} INFO - iteration 204, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:22] {3343} INFO -  at 272.7s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:22] {3166} INFO - iteration 205, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:24] {3343} INFO -  at 274.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:24] {3166} INFO - iteration 206, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:26] {3343} INFO -  at 275.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:26] {3166} INFO - iteration 207, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:28] {3343} INFO -  at 278.1s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:28] {3166} INFO - iteration 208, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:30] {3343} INFO -  at 279.8s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:30] {3166} INFO - iteration 209, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:31] {3343} INFO -  at 280.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:31] {3166} INFO - iteration 210, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:39:32] {3343} INFO -  at 282.5s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:32] {3166} INFO - iteration 211, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:34] {3343} INFO -  at 283.8s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:34] {3166} INFO - iteration 212, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:35] {3343} INFO -  at 285.4s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:35] {3166} INFO - iteration 213, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:37] {3343} INFO -  at 286.8s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:37] {3166} INFO - iteration 214, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:38] {3343} INFO -  at 288.5s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:38] {3166} INFO - iteration 215, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:39] {3343} INFO -  at 289.5s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:39] {3166} INFO - iteration 216, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:41] {3343} INFO -  at 290.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:41] {3166} INFO - iteration 217, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:42] {3343} INFO -  at 292.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:42] {3166} INFO - iteration 218, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:43] {3343} INFO -  at 293.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:43] {3166} INFO - iteration 219, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:44] {3343} INFO -  at 294.6s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:44] {3166} INFO - iteration 220, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:46] {3343} INFO -  at 295.9s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:46] {3166} INFO - iteration 221, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:46] {3343} INFO -  at 296.5s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:46] {3166} INFO - iteration 222, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:48] {3343} INFO -  at 298.0s,	estimator rf's best error=85.8862,	best estimator rf's best error=85.8862
[flaml.automl: 04-23 11:39:49] {3602} INFO - retrain rf for 1.3s
[flaml.automl: 04-23 11:39:49] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.4139484528695115, max_leaf_nodes=1408,
                      n_estimators=463, n_jobs=-1)

[flaml.automl: 04-23 11:39:49] {2901} INFO - fit succeeded
[flaml.automl: 04-23 11:39:49] {2902} INFO - Time taken to find the best model: 16.96868586540222
[flaml.automl: 04-23 11:39:49] {2599} INFO - task = regression
[flaml.automl: 04-23 11:39:49] {2601} INFO - Data split method: uniform
[flaml.automl: 04-23 11:39:49] {2604} INFO - Evaluation method: holdout
[flaml.automl: 04-23 11:39:49] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 04-23 11:39:49] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 04-23 11:39:49] {3166} INFO - iteration 0, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:49] {3296} INFO - Estimated sufficient time budget=289s. Estimated necessary time budget=0s.
[flaml.automl: 04-23 11:39:49] {3343} INFO -  at 0.1s,	estimator rf's best error=140.5329,	best estimator rf's best error=140.5329
[flaml.automl: 04-23 11:39:49] {3166} INFO - iteration 1, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:49] {3343} INFO -  at 0.1s,	estimator rf's best error=119.6815,	best estimator rf's best error=119.6815
[flaml.automl: 04-23 11:39:49] {3166} INFO - iteration 2, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:49] {3343} INFO -  at 0.1s,	estimator rf's best error=119.6815,	best estimator rf's best error=119.6815
[flaml.automl: 04-23 11:39:49] {3166} INFO - iteration 3, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:49] {3343} INFO -  at 0.2s,	estimator rf's best error=108.8138,	best estimator rf's best error=108.8138

0.97 0.93 0.18

[flaml.automl: 04-23 11:39:49] {3166} INFO - iteration 4, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:49] {3343} INFO -  at 0.3s,	estimator rf's best error=107.4803,	best estimator rf's best error=107.4803
[flaml.automl: 04-23 11:39:49] {3166} INFO - iteration 5, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:49] {3343} INFO -  at 0.3s,	estimator rf's best error=107.4803,	best estimator rf's best error=107.4803
[flaml.automl: 04-23 11:39:49] {3166} INFO - iteration 6, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:49] {3343} INFO -  at 0.4s,	estimator rf's best error=105.7004,	best estimator rf's best error=105.7004
[flaml.automl: 04-23 11:39:49] {3166} INFO - iteration 7, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:50] {3343} INFO -  at 0.4s,	estimator rf's best error=105.7004,	best estimator rf's best error=105.7004
[flaml.automl: 04-23 11:39:50] {3166} INFO - iteration 8, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:50] {3343} INFO -  at 0.5s,	estimator rf's best error=100.4225,	best estimator rf's best error=100.4225
[flaml.automl: 04-23 11:39:50] {3166} INFO - iteration 9, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:50] {3343} INFO -  at 0.6s,	estimator rf's best error=100.4225,	best estimator rf's best error=100.4225
[flaml.automl: 04-23 11:39:50] {3166} INFO - iteration 10, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:50] {3343} INFO -  at 0.6s,	estimator rf's best error=100.4225,	best estimator rf's best error=100.4225
[flaml.automl: 04-23 11:39:50] {3166} INFO - iteration 11, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:50] {3343} INFO -  at 0.8s,	estimator rf's best error=100.0989,	best estimator rf's best error=100.0989
[flaml.automl: 04-23 11:39:50] {3166} INFO - iteration 12, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:50] {3343} INFO -  at 0.9s,	estimator rf's best error=100.0989,	best estimator rf's best error=100.0989
[flaml.automl: 04-23 11:39:50] {3166} INFO - iteration 13, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:50] {3343} INFO -  at 1.2s,	estimator rf's best error=97.8843,	best estimator rf's best error=97.8843
[flaml.automl: 04-23 11:39:50] {3166} INFO - iteration 14, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:50] {3343} INFO -  at 1.4s,	estimator rf's best error=97.8843,	best estimator rf's best error=97.8843
[flaml.automl: 04-23 11:39:50] {3166} INFO - iteration 15, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:51] {3343} INFO -  at 2.2s,	estimator rf's best error=96.0038,	best estimator rf's best error=96.0038
[flaml.automl: 04-23 11:39:51] {3166} INFO - iteration 16, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:39:52] {3343} INFO -  at 2.6s,	estimator rf's best error=96.0038,	best estimator rf's best error=96.0038
[flaml.automl: 04-23 11:39:52] {3166} INFO - iteration 17, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:54] {3343} INFO -  at 4.8s,	estimator rf's best error=95.8962,	best estimator rf's best error=95.8962
[flaml.automl: 04-23 11:39:54] {3166} INFO - iteration 18, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:39:57] {3343} INFO -  at 7.7s,	estimator rf's best error=95.0002,	best estimator rf's best error=95.0002
[flaml.automl: 04-23 11:39:57] {3166} INFO - iteration 19, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:02] {3343} INFO -  at 13.0s,	estimator rf's best error=95.0002,	best estimator rf's best error=95.0002
[flaml.automl: 04-23 11:40:02] {3166} INFO - iteration 20, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:04] {3343} INFO -  at 14.5s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:04] {3166} INFO - iteration 21, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:04] {3343} INFO -  at 15.1s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:04] {3166} INFO - iteration 22, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:07] {3343} INFO -  at 18.2s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:07] {3166} INFO - iteration 23, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:09] {3343} INFO -  at 19.6s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:09] {3166} INFO - iteration 24, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:10] {3343} INFO -  at 21.0s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:10] {3166} INFO - iteration 25, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:13] {3343} INFO -  at 24.1s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:13] {3166} INFO - iteration 26, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:14] {3343} INFO -  at 24.8s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:14] {3166} INFO - iteration 27, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:15] {3343} INFO -  at 26.2s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:15] {3166} INFO - iteration 28, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:17] {3343} INFO -  at 27.8s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:17] {3166} INFO - iteration 29, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:40:18] {3343} INFO -  at 28.6s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:18] {3166} INFO - iteration 30, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:20] {3343} INFO -  at 30.8s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:20] {3166} INFO - iteration 31, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:21] {3343} INFO -  at 32.2s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:21] {3166} INFO - iteration 32, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:23] {3343} INFO -  at 33.4s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:23] {3166} INFO - iteration 33, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:25] {3343} INFO -  at 36.4s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:25] {3166} INFO - iteration 34, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:26] {3343} INFO -  at 37.0s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:26] {3166} INFO - iteration 35, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:27] {3343} INFO -  at 37.8s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:27] {3166} INFO - iteration 36, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:28] {3343} INFO -  at 38.9s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:28] {3166} INFO - iteration 37, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:31] {3343} INFO -  at 41.5s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:31] {3166} INFO - iteration 38, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:32] {3343} INFO -  at 42.4s,	estimator rf's best error=93.7255,	best estimator rf's best error=93.7255
[flaml.automl: 04-23 11:40:32] {3166} INFO - iteration 39, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:33] {3343} INFO -  at 44.2s,	estimator rf's best error=93.4208,	best estimator rf's best error=93.4208
[flaml.automl: 04-23 11:40:33] {3166} INFO - iteration 40, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:35] {3343} INFO -  at 45.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:35] {3166} INFO - iteration 41, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:36] {3343} INFO -  at 46.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:36] {3166} INFO - iteration 42, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:40:37] {3343} INFO -  at 48.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:37] {3166} INFO - iteration 43, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:39] {3343} INFO -  at 49.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:39] {3166} INFO - iteration 44, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:40] {3343} INFO -  at 50.9s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:40] {3166} INFO - iteration 45, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:42] {3343} INFO -  at 53.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:42] {3166} INFO - iteration 46, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:43] {3343} INFO -  at 53.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:43] {3166} INFO - iteration 47, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:43] {3343} INFO -  at 54.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:43] {3166} INFO - iteration 48, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:45] {3343} INFO -  at 56.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:45] {3166} INFO - iteration 49, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:48] {3343} INFO -  at 58.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:48] {3166} INFO - iteration 50, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:48] {3343} INFO -  at 59.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:48] {3166} INFO - iteration 51, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:50] {3343} INFO -  at 60.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:50] {3166} INFO - iteration 52, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:50] {3343} INFO -  at 61.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:50] {3166} INFO - iteration 53, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:51] {3343} INFO -  at 62.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:51] {3166} INFO - iteration 54, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:54] {3343} INFO -  at 64.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:54] {3166} INFO - iteration 55, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:40:57] {3343} INFO -  at 67.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:57] {3166} INFO - iteration 56, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:58] {3343} INFO -  at 68.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:58] {3166} INFO - iteration 57, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:40:59] {3343} INFO -  at 69.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:40:59] {3166} INFO - iteration 58, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:00] {3343} INFO -  at 70.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:00] {3166} INFO - iteration 59, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:00] {3343} INFO -  at 71.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:00] {3166} INFO - iteration 60, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:02] {3343} INFO -  at 72.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:02] {3166} INFO - iteration 61, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:04] {3343} INFO -  at 75.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:04] {3166} INFO - iteration 62, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:05] {3343} INFO -  at 76.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:05] {3166} INFO - iteration 63, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:07] {3343} INFO -  at 77.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:07] {3166} INFO - iteration 64, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:08] {3343} INFO -  at 78.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:08] {3166} INFO - iteration 65, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:09] {3343} INFO -  at 79.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:09] {3166} INFO - iteration 66, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:11] {3343} INFO -  at 81.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:11] {3166} INFO - iteration 67, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:11] {3343} INFO -  at 82.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:11] {3166} INFO - iteration 68, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:41:13] {3343} INFO -  at 83.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:13] {3166} INFO - iteration 69, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:14] {3343} INFO -  at 85.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:14] {3166} INFO - iteration 70, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:15] {3343} INFO -  at 85.9s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:15] {3166} INFO - iteration 71, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:16] {3343} INFO -  at 86.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:16] {3166} INFO - iteration 72, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:17] {3343} INFO -  at 88.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:17] {3166} INFO - iteration 73, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:18] {3343} INFO -  at 89.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:18] {3166} INFO - iteration 74, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:19] {3343} INFO -  at 89.9s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:19] {3166} INFO - iteration 75, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:20] {3343} INFO -  at 90.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:20] {3166} INFO - iteration 76, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:21] {3343} INFO -  at 91.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:21] {3166} INFO - iteration 77, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:22] {3343} INFO -  at 92.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:22] {3166} INFO - iteration 78, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:23] {3343} INFO -  at 93.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:23] {3166} INFO - iteration 79, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:24] {3343} INFO -  at 94.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:24] {3166} INFO - iteration 80, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:25] {3343} INFO -  at 95.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:25] {3166} INFO - iteration 81, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:41:26] {3343} INFO -  at 96.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:26] {3166} INFO - iteration 82, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:27] {3343} INFO -  at 97.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:27] {3166} INFO - iteration 83, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:27] {3343} INFO -  at 98.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:27] {3166} INFO - iteration 84, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:30] {3343} INFO -  at 101.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:30] {3166} INFO - iteration 85, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:32] {3343} INFO -  at 103.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:32] {3166} INFO - iteration 86, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:33] {3343} INFO -  at 104.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:33] {3166} INFO - iteration 87, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:34] {3343} INFO -  at 104.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:34] {3166} INFO - iteration 88, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:35] {3343} INFO -  at 106.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:35] {3166} INFO - iteration 89, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:36] {3343} INFO -  at 107.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:36] {3166} INFO - iteration 90, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:37] {3343} INFO -  at 108.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:37] {3166} INFO - iteration 91, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:38] {3343} INFO -  at 109.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:38] {3166} INFO - iteration 92, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:39] {3343} INFO -  at 110.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:39] {3166} INFO - iteration 93, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:40] {3343} INFO -  at 111.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:40] {3166} INFO - iteration 94, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:41:41] {3343} INFO -  at 111.9s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:41] {3166} INFO - iteration 95, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:43] {3343} INFO -  at 113.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:43] {3166} INFO - iteration 96, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:43] {3343} INFO -  at 114.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:43] {3166} INFO - iteration 97, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:45] {3343} INFO -  at 115.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:45] {3166} INFO - iteration 98, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:45] {3343} INFO -  at 116.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:45] {3166} INFO - iteration 99, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:47] {3343} INFO -  at 117.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:47] {3166} INFO - iteration 100, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:47] {3343} INFO -  at 118.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:47] {3166} INFO - iteration 101, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:50] {3343} INFO -  at 120.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:50] {3166} INFO - iteration 102, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:51] {3343} INFO -  at 121.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:51] {3166} INFO - iteration 103, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:53] {3343} INFO -  at 123.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:53] {3166} INFO - iteration 104, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:54] {3343} INFO -  at 124.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:54] {3166} INFO - iteration 105, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:54] {3343} INFO -  at 125.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:54] {3166} INFO - iteration 106, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:56] {3343} INFO -  at 127.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:56] {3166} INFO - iteration 107, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:41:57] {3343} INFO -  at 127.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:57] {3166} INFO - iteration 108, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:58] {3343} INFO -  at 128.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:58] {3166} INFO - iteration 109, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:41:59] {3343} INFO -  at 129.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:41:59] {3166} INFO - iteration 110, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:00] {3343} INFO -  at 130.9s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:00] {3166} INFO - iteration 111, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:01] {3343} INFO -  at 132.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:01] {3166} INFO - iteration 112, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:02] {3343} INFO -  at 132.9s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:02] {3166} INFO - iteration 113, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:03] {3343} INFO -  at 134.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:03] {3166} INFO - iteration 114, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:04] {3343} INFO -  at 135.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:04] {3166} INFO - iteration 115, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:05] {3343} INFO -  at 135.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:05] {3166} INFO - iteration 116, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:06] {3343} INFO -  at 137.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:06] {3166} INFO - iteration 117, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:07] {3343} INFO -  at 137.9s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:07] {3166} INFO - iteration 118, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:09] {3343} INFO -  at 139.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:09] {3166} INFO - iteration 119, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:09] {3343} INFO -  at 140.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:09] {3166} INFO - iteration 120, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:42:11] {3343} INFO -  at 142.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:11] {3166} INFO - iteration 121, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:13] {3343} INFO -  at 143.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:13] {3166} INFO - iteration 122, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:13] {3343} INFO -  at 144.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:13] {3166} INFO - iteration 123, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:15] {3343} INFO -  at 145.9s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:15] {3166} INFO - iteration 124, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:16] {3343} INFO -  at 146.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:16] {3166} INFO - iteration 125, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:17] {3343} INFO -  at 147.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:17] {3166} INFO - iteration 126, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:18] {3343} INFO -  at 148.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:18] {3166} INFO - iteration 127, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:19] {3343} INFO -  at 149.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:19] {3166} INFO - iteration 128, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:20] {3343} INFO -  at 151.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:20] {3166} INFO - iteration 129, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:22] {3343} INFO -  at 152.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:22] {3166} INFO - iteration 130, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:22] {3343} INFO -  at 153.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:22] {3166} INFO - iteration 131, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:23] {3343} INFO -  at 154.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:23] {3166} INFO - iteration 132, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:24] {3343} INFO -  at 155.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:24] {3166} INFO - iteration 133, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:42:25] {3343} INFO -  at 156.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:25] {3166} INFO - iteration 134, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:26] {3343} INFO -  at 157.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:26] {3166} INFO - iteration 135, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:28] {3343} INFO -  at 158.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:28] {3166} INFO - iteration 136, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:29] {3343} INFO -  at 159.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:29] {3166} INFO - iteration 137, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:29] {3343} INFO -  at 160.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:29] {3166} INFO - iteration 138, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:31] {3343} INFO -  at 161.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:31] {3166} INFO - iteration 139, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:32] {3343} INFO -  at 162.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:32] {3166} INFO - iteration 140, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:32] {3343} INFO -  at 163.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:32] {3166} INFO - iteration 141, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:34] {3343} INFO -  at 164.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:34] {3166} INFO - iteration 142, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:34] {3343} INFO -  at 165.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:34] {3166} INFO - iteration 143, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:35] {3343} INFO -  at 166.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:35] {3166} INFO - iteration 144, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:36] {3343} INFO -  at 167.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:36] {3166} INFO - iteration 145, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:38] {3343} INFO -  at 168.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:38] {3166} INFO - iteration 146, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:42:39] {3343} INFO -  at 169.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:39] {3166} INFO - iteration 147, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:39] {3343} INFO -  at 170.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:39] {3166} INFO - iteration 148, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:41] {3343} INFO -  at 171.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:41] {3166} INFO - iteration 149, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:42] {3343} INFO -  at 172.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:42] {3166} INFO - iteration 150, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:43] {3343} INFO -  at 173.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:43] {3166} INFO - iteration 151, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:44] {3343} INFO -  at 175.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:44] {3166} INFO - iteration 152, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:45] {3343} INFO -  at 176.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:45] {3166} INFO - iteration 153, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:47] {3343} INFO -  at 177.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:47] {3166} INFO - iteration 154, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:48] {3343} INFO -  at 178.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:48] {3166} INFO - iteration 155, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:49] {3343} INFO -  at 180.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:49] {3166} INFO - iteration 156, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:50] {3343} INFO -  at 181.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:50] {3166} INFO - iteration 157, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:51] {3343} INFO -  at 182.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:51] {3166} INFO - iteration 158, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:53] {3343} INFO -  at 183.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:53] {3166} INFO - iteration 159, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:42:55] {3343} INFO -  at 185.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:55] {3166} INFO - iteration 160, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:56] {3343} INFO -  at 186.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:56] {3166} INFO - iteration 161, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:57] {3343} INFO -  at 187.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:57] {3166} INFO - iteration 162, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:58] {3343} INFO -  at 189.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:58] {3166} INFO - iteration 163, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:42:59] {3343} INFO -  at 190.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:42:59] {3166} INFO - iteration 164, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:01] {3343} INFO -  at 191.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:01] {3166} INFO - iteration 165, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:02] {3343} INFO -  at 192.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:02] {3166} INFO - iteration 166, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:03] {3343} INFO -  at 193.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:03] {3166} INFO - iteration 167, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:04] {3343} INFO -  at 194.9s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:04] {3166} INFO - iteration 168, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:05] {3343} INFO -  at 195.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:05] {3166} INFO - iteration 169, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:06] {3343} INFO -  at 196.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:06] {3166} INFO - iteration 170, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:07] {3343} INFO -  at 198.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:07] {3166} INFO - iteration 171, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:08] {3343} INFO -  at 199.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:08] {3166} INFO - iteration 172, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:43:09] {3343} INFO -  at 200.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:09] {3166} INFO - iteration 173, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:10] {3343} INFO -  at 201.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:10] {3166} INFO - iteration 174, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:12] {3343} INFO -  at 202.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:12] {3166} INFO - iteration 175, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:13] {3343} INFO -  at 203.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:13] {3166} INFO - iteration 176, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:14] {3343} INFO -  at 204.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:14] {3166} INFO - iteration 177, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:15] {3343} INFO -  at 205.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:15] {3166} INFO - iteration 178, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:16] {3343} INFO -  at 207.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:16] {3166} INFO - iteration 179, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:18] {3343} INFO -  at 208.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:18] {3166} INFO - iteration 180, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:18] {3343} INFO -  at 209.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:18] {3166} INFO - iteration 181, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:19] {3343} INFO -  at 210.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:19] {3166} INFO - iteration 182, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:21] {3343} INFO -  at 211.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:21] {3166} INFO - iteration 183, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:22] {3343} INFO -  at 212.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:22] {3166} INFO - iteration 184, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:23] {3343} INFO -  at 213.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:23] {3166} INFO - iteration 185, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:43:24] {3343} INFO -  at 214.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:24] {3166} INFO - iteration 186, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:25] {3343} INFO -  at 215.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:25] {3166} INFO - iteration 187, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:26] {3343} INFO -  at 216.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:26] {3166} INFO - iteration 188, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:27] {3343} INFO -  at 217.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:27] {3166} INFO - iteration 189, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:28] {3343} INFO -  at 218.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:28] {3166} INFO - iteration 190, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:29] {3343} INFO -  at 219.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:29] {3166} INFO - iteration 191, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:29] {3343} INFO -  at 220.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:29] {3166} INFO - iteration 192, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:32] {3343} INFO -  at 222.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:32] {3166} INFO - iteration 193, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:33] {3343} INFO -  at 224.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:33] {3166} INFO - iteration 194, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:34] {3343} INFO -  at 225.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:34] {3166} INFO - iteration 195, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:36] {3343} INFO -  at 226.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:36] {3166} INFO - iteration 196, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:37] {3343} INFO -  at 227.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:37] {3166} INFO - iteration 197, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:39] {3343} INFO -  at 229.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:39] {3166} INFO - iteration 198, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:43:40] {3343} INFO -  at 230.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:40] {3166} INFO - iteration 199, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:41] {3343} INFO -  at 232.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:41] {3166} INFO - iteration 200, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:43] {3343} INFO -  at 233.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:43] {3166} INFO - iteration 201, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:44] {3343} INFO -  at 234.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:44] {3166} INFO - iteration 202, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:45] {3343} INFO -  at 236.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:45] {3166} INFO - iteration 203, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:46] {3343} INFO -  at 237.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:46] {3166} INFO - iteration 204, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:47] {3343} INFO -  at 238.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:47] {3166} INFO - iteration 205, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:48] {3343} INFO -  at 239.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:48] {3166} INFO - iteration 206, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:49] {3343} INFO -  at 240.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:49] {3166} INFO - iteration 207, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:50] {3343} INFO -  at 241.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:50] {3166} INFO - iteration 208, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:51] {3343} INFO -  at 242.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:51] {3166} INFO - iteration 209, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:53] {3343} INFO -  at 243.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:53] {3166} INFO - iteration 210, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:54] {3343} INFO -  at 244.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:54] {3166} INFO - iteration 211, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:43:55] {3343} INFO -  at 245.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:55] {3166} INFO - iteration 212, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:56] {3343} INFO -  at 246.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:56] {3166} INFO - iteration 213, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:57] {3343} INFO -  at 248.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:57] {3166} INFO - iteration 214, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:58] {3343} INFO -  at 248.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:58] {3166} INFO - iteration 215, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:43:59] {3343} INFO -  at 250.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:43:59] {3166} INFO - iteration 216, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:00] {3343} INFO -  at 251.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:00] {3166} INFO - iteration 217, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:01] {3343} INFO -  at 252.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:01] {3166} INFO - iteration 218, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:02] {3343} INFO -  at 253.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:02] {3166} INFO - iteration 219, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:03] {3343} INFO -  at 254.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:03] {3166} INFO - iteration 220, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:04] {3343} INFO -  at 255.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:04] {3166} INFO - iteration 221, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:05] {3343} INFO -  at 256.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:05] {3166} INFO - iteration 222, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:07] {3343} INFO -  at 257.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:07] {3166} INFO - iteration 223, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:08] {3343} INFO -  at 258.8s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:08] {3166} INFO - iteration 224, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:44:09] {3343} INFO -  at 259.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:09] {3166} INFO - iteration 225, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:10] {3343} INFO -  at 260.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:10] {3166} INFO - iteration 226, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:11] {3343} INFO -  at 262.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:11] {3166} INFO - iteration 227, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:13] {3343} INFO -  at 263.9s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:13] {3166} INFO - iteration 228, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:14] {3343} INFO -  at 264.9s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:14] {3166} INFO - iteration 229, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:15] {3343} INFO -  at 266.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:15] {3166} INFO - iteration 230, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:16] {3343} INFO -  at 267.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:16] {3166} INFO - iteration 231, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:18] {3343} INFO -  at 268.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:18] {3166} INFO - iteration 232, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:18] {3343} INFO -  at 269.4s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:18] {3166} INFO - iteration 233, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:20] {3343} INFO -  at 270.9s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:20] {3166} INFO - iteration 234, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:21] {3343} INFO -  at 271.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:21] {3166} INFO - iteration 235, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:22] {3343} INFO -  at 272.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:22] {3166} INFO - iteration 236, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:23] {3343} INFO -  at 274.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:23] {3166} INFO - iteration 237, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:44:24] {3343} INFO -  at 274.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:24] {3166} INFO - iteration 238, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:25] {3343} INFO -  at 276.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:25] {3166} INFO - iteration 239, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:26] {3343} INFO -  at 277.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:26] {3166} INFO - iteration 240, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:28] {3343} INFO -  at 278.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:28] {3166} INFO - iteration 241, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:29] {3343} INFO -  at 279.6s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:29] {3166} INFO - iteration 242, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:31] {3343} INFO -  at 281.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:31] {3166} INFO - iteration 243, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:32] {3343} INFO -  at 282.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:32] {3166} INFO - iteration 244, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:33] {3343} INFO -  at 284.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:33] {3166} INFO - iteration 245, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:35] {3343} INFO -  at 286.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:35] {3166} INFO - iteration 246, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:36] {3343} INFO -  at 287.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:36] {3166} INFO - iteration 247, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:37] {3343} INFO -  at 288.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:37] {3166} INFO - iteration 248, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:39] {3343} INFO -  at 289.7s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:39] {3166} INFO - iteration 249, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:40] {3343} INFO -  at 291.0s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:40] {3166} INFO - iteration 250, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:44:41] {3343} INFO -  at 292.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:41] {3166} INFO - iteration 251, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:42] {3343} INFO -  at 293.1s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:42] {3166} INFO - iteration 252, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:43] {3343} INFO -  at 294.2s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:43] {3166} INFO - iteration 253, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:45] {3343} INFO -  at 295.5s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:45] {3166} INFO - iteration 254, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:46] {3343} INFO -  at 297.3s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:46] {3166} INFO - iteration 255, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:48] {3343} INFO -  at 298.9s,	estimator rf's best error=92.7697,	best estimator rf's best error=92.7697
[flaml.automl: 04-23 11:44:50] {3602} INFO - retrain rf for 2.3s
[flaml.automl: 04-23 11:44:50] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.35895158457150717, max_leaf_nodes=1445,
                      n_estimators=386, n_jobs=-1)
[flaml.automl: 04-23 11:44:50] {2901} INFO - fit succeeded
[flaml.automl: 04-23 11:44:50] {2902} INFO - Time taken to find the best model: 45.631338119506836
[flaml.automl: 04-23 11:44:51] {2599} INFO - task = regression
[flaml.automl: 04-23 11:44:51] {2601} INFO - Data split method: uniform
[flaml.automl: 04-23 11:44:51] {2604} INFO - Evaluation method: holdout
[flaml.automl: 04-23 11:44:51] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 04-23 11:44:51] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 04-23 11:44:51] {3166} INFO - iteration 0, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:51] {3296} INFO - Estimated sufficient time budget=584s. Estimated necessary time budget=1s.
[flaml.automl: 04-23 11:44:51] {3343} INFO -  at 0.1s,	estimator rf's best error=149.4678,	best estimator rf's best error=149.4678
[flaml.automl: 04-23 11:44:51] {3166} INFO - iteration 1, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:51] {3343} INFO -  at 0.2s,	estimator rf's best error=123.7475,	best estimator rf's best error=123.7475
[flaml.automl: 04-23 11:44:51] {3166} INFO - iteration 2, current learner rf

0.99 0.97 0.14

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:51] {3343} INFO -  at 0.3s,	estimator rf's best error=123.7475,	best estimator rf's best error=123.7475
[flaml.automl: 04-23 11:44:51] {3166} INFO - iteration 3, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:51] {3343} INFO -  at 0.4s,	estimator rf's best error=113.1838,	best estimator rf's best error=113.1838
[flaml.automl: 04-23 11:44:51] {3166} INFO - iteration 4, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:51] {3343} INFO -  at 0.5s,	estimator rf's best error=113.0793,	best estimator rf's best error=113.0793
[flaml.automl: 04-23 11:44:51] {3166} INFO - iteration 5, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:51] {3343} INFO -  at 0.7s,	estimator rf's best error=113.0793,	best estimator rf's best error=113.0793
[flaml.automl: 04-23 11:44:51] {3166} INFO - iteration 6, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:51] {3343} INFO -  at 0.8s,	estimator rf's best error=113.0793,	best estimator rf's best error=113.0793
[flaml.automl: 04-23 11:44:51] {3166} INFO - iteration 7, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:51] {3343} INFO -  at 0.9s,	estimator rf's best error=113.0793,	best estimator rf's best error=113.0793
[flaml.automl: 04-23 11:44:51] {3166} INFO - iteration 8, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:52] {3343} INFO -  at 1.0s,	estimator rf's best error=109.4589,	best estimator rf's best error=109.4589
[flaml.automl: 04-23 11:44:52] {3166} INFO - iteration 9, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:52] {3343} INFO -  at 1.1s,	estimator rf's best error=109.4589,	best estimator rf's best error=109.4589
[flaml.automl: 04-23 11:44:52] {3166} INFO - iteration 10, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:52] {3343} INFO -  at 1.2s,	estimator rf's best error=109.4589,	best estimator rf's best error=109.4589
[flaml.automl: 04-23 11:44:52] {3166} INFO - iteration 11, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:52] {3343} INFO -  at 1.4s,	estimator rf's best error=109.4589,	best estimator rf's best error=109.4589
[flaml.automl: 04-23 11:44:52] {3166} INFO - iteration 12, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:52] {3343} INFO -  at 1.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:52] {3166} INFO - iteration 13, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:52] {3343} INFO -  at 1.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:52] {3166} INFO - iteration 14, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:44:52] {3343} INFO -  at 1.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:52] {3166} INFO - iteration 15, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:52] {3343} INFO -  at 1.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:52] {3166} INFO - iteration 16, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:53] {3343} INFO -  at 2.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:53] {3166} INFO - iteration 17, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:53] {3343} INFO -  at 2.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:53] {3166} INFO - iteration 18, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:53] {3343} INFO -  at 2.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:53] {3166} INFO - iteration 19, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:53] {3343} INFO -  at 2.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:53] {3166} INFO - iteration 20, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:53] {3343} INFO -  at 2.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:53] {3166} INFO - iteration 21, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:53] {3343} INFO -  at 2.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:53] {3166} INFO - iteration 22, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:53] {3343} INFO -  at 2.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:53] {3166} INFO - iteration 23, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:53] {3343} INFO -  at 2.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:53] {3166} INFO - iteration 24, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:53] {3343} INFO -  at 2.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:53] {3166} INFO - iteration 25, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:53] {3343} INFO -  at 2.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:53] {3166} INFO - iteration 26, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:53] {3343} INFO -  at 2.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:53] {3166} INFO - iteration 27, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:44:54] {3343} INFO -  at 3.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:54] {3166} INFO - iteration 28, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:54] {3343} INFO -  at 3.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:54] {3166} INFO - iteration 29, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:54] {3343} INFO -  at 3.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:54] {3166} INFO - iteration 30, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:54] {3343} INFO -  at 3.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:54] {3166} INFO - iteration 31, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:54] {3343} INFO -  at 3.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:54] {3166} INFO - iteration 32, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:54] {3343} INFO -  at 3.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:54] {3166} INFO - iteration 33, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:54] {3343} INFO -  at 3.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:54] {3166} INFO - iteration 34, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:54] {3343} INFO -  at 3.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:54] {3166} INFO - iteration 35, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:54] {3343} INFO -  at 3.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:54] {3166} INFO - iteration 36, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:54] {3343} INFO -  at 3.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:54] {3166} INFO - iteration 37, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:54] {3343} INFO -  at 3.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:54] {3166} INFO - iteration 38, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:55] {3343} INFO -  at 4.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:55] {3166} INFO - iteration 39, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:55] {3343} INFO -  at 4.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:55] {3166} INFO - iteration 40, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:55] {3343} INFO -  at 4.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588

[flaml.automl: 04-23 11:44:55] {3166} INFO - iteration 41, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:55] {3343} INFO -  at 4.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:55] {3166} INFO - iteration 42, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:55] {3343} INFO -  at 4.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:55] {3166} INFO - iteration 43, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:55] {3343} INFO -  at 4.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:55] {3166} INFO - iteration 44, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:55] {3343} INFO -  at 4.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:55] {3166} INFO - iteration 45, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:55] {3343} INFO -  at 4.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:55] {3166} INFO - iteration 46, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:55] {3343} INFO -  at 4.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:55] {3166} INFO - iteration 47, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:55] {3343} INFO -  at 4.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:55] {3166} INFO - iteration 48, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:55] {3343} INFO -  at 5.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:55] {3166} INFO - iteration 49, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:56] {3343} INFO -  at 5.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:56] {3166} INFO - iteration 50, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:56] {3343} INFO -  at 5.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:56] {3166} INFO - iteration 51, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:56] {3343} INFO -  at 5.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:56] {3166} INFO - iteration 52, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:56] {3343} INFO -  at 5.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:56] {3166} INFO - iteration 53, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:44:56] {3343} INFO -  at 5.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:56] {3166} INFO - iteration 54, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:56] {3343} INFO -  at 5.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:56] {3166} INFO - iteration 55, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:56] {3343} INFO -  at 5.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:56] {3166} INFO - iteration 56, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:56] {3343} INFO -  at 5.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:56] {3166} INFO - iteration 57, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:56] {3343} INFO -  at 5.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:56] {3166} INFO - iteration 58, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 59, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 60, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 61, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 62, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 63, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 64, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 65, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 66, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 67, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 68, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 69, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 70, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 71, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 72, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 73, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 74, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 6.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 75, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:57] {3343} INFO -  at 7.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:57] {3166} INFO - iteration 76, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 77, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 78, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 79, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 80, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 81, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 82, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 83, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 84, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 85, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 86, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 87, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 88, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 89, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 90, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 91, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 92, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 7.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 93, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:58] {3343} INFO -  at 8.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:58] {3166} INFO - iteration 94, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 95, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 96, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 97, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 98, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 99, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 100, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 101, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 102, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 103, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 104, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 105, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 106, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 107, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 108, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 109, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:44:59] {3343} INFO -  at 8.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:44:59] {3166} INFO - iteration 110, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 111, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 112, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 113, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 114, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 115, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 116, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 117, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 118, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 119, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 120, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 121, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 122, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 123, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 124, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 125, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 126, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:00] {3343} INFO -  at 9.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:00] {3166} INFO - iteration 127, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:01] {3343} INFO -  at 10.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:01] {3166} INFO - iteration 128, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:01] {3343} INFO -  at 10.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:01] {3166} INFO - iteration 129, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:01] {3343} INFO -  at 10.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:01] {3166} INFO - iteration 130, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:01] {3343} INFO -  at 10.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:01] {3166} INFO - iteration 131, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:01] {3343} INFO -  at 10.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:01] {3166} INFO - iteration 132, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:01] {3343} INFO -  at 10.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:01] {3166} INFO - iteration 133, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:01] {3343} INFO -  at 10.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:01] {3166} INFO - iteration 134, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:01] {3343} INFO -  at 10.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:01] {3166} INFO - iteration 135, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:01] {3343} INFO -  at 10.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:01] {3166} INFO - iteration 136, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:01] {3343} INFO -  at 10.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:01] {3166} INFO - iteration 137, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:02] {3343} INFO -  at 11.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:02] {3166} INFO - iteration 138, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:02] {3343} INFO -  at 11.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:02] {3166} INFO - iteration 139, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:02] {3343} INFO -  at 11.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:02] {3166} INFO - iteration 140, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:02] {3343} INFO -  at 11.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:02] {3166} INFO - iteration 141, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:02] {3343} INFO -  at 11.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:02] {3166} INFO - iteration 142, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:02] {3343} INFO -  at 11.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:02] {3166} INFO - iteration 143, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:02] {3343} INFO -  at 11.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:02] {3166} INFO - iteration 144, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:02] {3343} INFO -  at 11.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:02] {3166} INFO - iteration 145, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:02] {3343} INFO -  at 11.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:02] {3166} INFO - iteration 146, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:02] {3343} INFO -  at 11.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:02] {3166} INFO - iteration 147, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:03] {3343} INFO -  at 12.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:03] {3166} INFO - iteration 148, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:03] {3343} INFO -  at 12.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:03] {3166} INFO - iteration 149, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:03] {3343} INFO -  at 12.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:03] {3166} INFO - iteration 150, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:03] {3343} INFO -  at 12.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:03] {3166} INFO - iteration 151, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:03] {3343} INFO -  at 12.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:03] {3166} INFO - iteration 152, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:03] {3343} INFO -  at 12.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:03] {3166} INFO - iteration 153, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:03] {3343} INFO -  at 12.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:03] {3166} INFO - iteration 154, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:03] {3343} INFO -  at 12.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:03] {3166} INFO - iteration 155, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:03] {3343} INFO -  at 12.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:03] {3166} INFO - iteration 156, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:03] {3343} INFO -  at 12.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:03] {3166} INFO - iteration 157, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:03] {3343} INFO -  at 12.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:03] {3166} INFO - iteration 158, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:03] {3343} INFO -  at 12.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:03] {3166} INFO - iteration 159, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:04] {3343} INFO -  at 13.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:04] {3166} INFO - iteration 160, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:04] {3343} INFO -  at 13.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:04] {3166} INFO - iteration 161, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:04] {3343} INFO -  at 13.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:04] {3166} INFO - iteration 162, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:04] {3343} INFO -  at 13.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:04] {3166} INFO - iteration 163, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:04] {3343} INFO -  at 13.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:04] {3166} INFO - iteration 164, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:04] {3343} INFO -  at 13.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:04] {3166} INFO - iteration 165, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:04] {3343} INFO -  at 13.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:04] {3166} INFO - iteration 166, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:04] {3343} INFO -  at 13.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:04] {3166} INFO - iteration 167, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:04] {3343} INFO -  at 13.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:04] {3166} INFO - iteration 168, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:04] {3343} INFO -  at 13.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:04] {3166} INFO - iteration 169, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:04] {3343} INFO -  at 14.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:04] {3166} INFO - iteration 170, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 14.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 171, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 14.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 172, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 14.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 173, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 14.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 174, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 14.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 175, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 14.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 176, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 14.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 177, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 14.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 178, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 14.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 179, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 14.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 180, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 14.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 181, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 14.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 182, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 14.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 183, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 14.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 184, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:05] {3343} INFO -  at 15.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:05] {3166} INFO - iteration 185, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:06] {3343} INFO -  at 15.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:06] {3166} INFO - iteration 186, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:06] {3343} INFO -  at 15.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:06] {3166} INFO - iteration 187, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:06] {3343} INFO -  at 15.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:06] {3166} INFO - iteration 188, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:06] {3343} INFO -  at 15.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:06] {3166} INFO - iteration 189, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:06] {3343} INFO -  at 15.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:06] {3166} INFO - iteration 190, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:06] {3343} INFO -  at 15.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:06] {3166} INFO - iteration 191, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:06] {3343} INFO -  at 15.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:06] {3166} INFO - iteration 192, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:06] {3343} INFO -  at 15.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:06] {3166} INFO - iteration 193, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:06] {3343} INFO -  at 15.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:06] {3166} INFO - iteration 194, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:06] {3343} INFO -  at 15.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:06] {3166} INFO - iteration 195, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:06] {3343} INFO -  at 15.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:06] {3166} INFO - iteration 196, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:06] {3343} INFO -  at 15.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:06] {3166} INFO - iteration 197, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:06] {3343} INFO -  at 15.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:06] {3166} INFO - iteration 198, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:06] {3343} INFO -  at 16.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:06] {3166} INFO - iteration 199, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:07] {3343} INFO -  at 16.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:07] {3166} INFO - iteration 200, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:07] {3343} INFO -  at 16.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:07] {3166} INFO - iteration 201, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:07] {3343} INFO -  at 16.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:07] {3166} INFO - iteration 202, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:07] {3343} INFO -  at 16.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:07] {3166} INFO - iteration 203, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:07] {3343} INFO -  at 16.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:07] {3166} INFO - iteration 204, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:07] {3343} INFO -  at 16.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:07] {3166} INFO - iteration 205, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:07] {3343} INFO -  at 16.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:07] {3166} INFO - iteration 206, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:07] {3343} INFO -  at 16.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:07] {3166} INFO - iteration 207, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:07] {3343} INFO -  at 16.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:07] {3166} INFO - iteration 208, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:07] {3343} INFO -  at 16.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:07] {3166} INFO - iteration 209, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:07] {3343} INFO -  at 16.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:07] {3166} INFO - iteration 210, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:07] {3343} INFO -  at 16.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:07] {3166} INFO - iteration 211, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:07] {3343} INFO -  at 16.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:07] {3166} INFO - iteration 212, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:07] {3343} INFO -  at 17.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:07] {3166} INFO - iteration 213, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:08] {3343} INFO -  at 17.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:08] {3166} INFO - iteration 214, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:08] {3343} INFO -  at 17.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:08] {3166} INFO - iteration 215, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:08] {3343} INFO -  at 17.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:08] {3166} INFO - iteration 216, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:08] {3343} INFO -  at 17.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:08] {3166} INFO - iteration 217, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:08] {3343} INFO -  at 17.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:08] {3166} INFO - iteration 218, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:08] {3343} INFO -  at 17.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:08] {3166} INFO - iteration 219, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:08] {3343} INFO -  at 17.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:08] {3166} INFO - iteration 220, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:08] {3343} INFO -  at 17.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:08] {3166} INFO - iteration 221, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:08] {3343} INFO -  at 17.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:08] {3166} INFO - iteration 222, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:08] {3343} INFO -  at 17.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:08] {3166} INFO - iteration 223, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:08] {3343} INFO -  at 17.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:08] {3166} INFO - iteration 224, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:08] {3343} INFO -  at 17.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:08] {3166} INFO - iteration 225, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:08] {3343} INFO -  at 17.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:08] {3166} INFO - iteration 226, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:08] {3343} INFO -  at 17.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:08] {3166} INFO - iteration 227, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 228, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 229, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 230, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 231, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 232, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 233, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 234, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 235, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 236, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 237, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 238, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 239, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 240, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 241, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 18.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 242, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:09] {3343} INFO -  at 19.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:09] {3166} INFO - iteration 243, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 244, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 245, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 246, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 247, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 248, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 249, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 250, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 251, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 252, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 253, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 254, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 255, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 256, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 257, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 258, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 259, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:10] {3343} INFO -  at 19.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:10] {3166} INFO - iteration 260, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 261, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 262, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 263, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 264, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 265, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 266, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 267, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 268, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 269, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 270, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 271, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 272, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 273, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 274, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 275, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 276, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 277, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 278, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:11] {3343} INFO -  at 20.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:11] {3166} INFO - iteration 279, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 280, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 281, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 282, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 283, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 284, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 285, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 286, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 287, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 288, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 289, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 290, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 291, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 292, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 293, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 294, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 295, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 296, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 297, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:12] {3343} INFO -  at 21.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:12] {3166} INFO - iteration 298, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 299, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 300, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 301, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 302, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 303, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 304, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 305, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 306, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 307, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 308, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 309, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 310, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 311, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 312, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 313, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 314, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 315, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 22.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 316, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:13] {3343} INFO -  at 23.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:13] {3166} INFO - iteration 317, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 318, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 319, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 320, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 321, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 322, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 323, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 324, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 325, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 326, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 327, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 328, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 329, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 330, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 331, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 23.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 332, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:14] {3343} INFO -  at 24.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:14] {3166} INFO - iteration 333, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 334, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 335, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 336, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 337, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 338, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 339, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 340, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 341, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 342, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 343, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 344, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 345, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 346, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 347, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 348, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:15] {3343} INFO -  at 24.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:15] {3166} INFO - iteration 349, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 25.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 350, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 25.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 351, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 25.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 352, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 25.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 353, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 25.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 354, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 25.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 355, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 25.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 356, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 25.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 357, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 25.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 358, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 25.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 359, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 25.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 360, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 25.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 361, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 25.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 362, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 25.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 363, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:16] {3343} INFO -  at 26.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:16] {3166} INFO - iteration 364, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 365, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 366, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 367, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 368, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 369, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 370, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 371, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 372, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 373, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 374, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 375, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 376, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 377, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 378, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588

[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 379, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:17] {3343} INFO -  at 26.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:17] {3166} INFO - iteration 380, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 381, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 382, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 383, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 384, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 385, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 386, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 387, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 388, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 389, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 390, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 391, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 392, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 393, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 394, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 395, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 396, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 397, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 398, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 399, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:18] {3343} INFO -  at 27.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:18] {3166} INFO - iteration 400, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 401, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 402, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 403, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 404, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 405, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 406, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 407, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 408, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 409, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 410, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 411, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 412, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 413, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 414, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 415, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 416, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 28.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 417, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:19] {3343} INFO -  at 29.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:19] {3166} INFO - iteration 418, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 419, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 420, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 421, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 422, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 423, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 424, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 425, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 426, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 427, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 428, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 429, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 430, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 431, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 432, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 433, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 434, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 435, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 29.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 436, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:20] {3343} INFO -  at 30.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:20] {3166} INFO - iteration 437, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 438, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 439, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 440, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 441, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 442, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 443, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 444, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 445, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 446, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 447, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 448, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 449, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 450, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 451, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 452, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 453, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 454, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 455, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:21] {3343} INFO -  at 30.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:21] {3166} INFO - iteration 456, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 457, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 458, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 459, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 460, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 461, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 462, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 463, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 464, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 465, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 466, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 467, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 468, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 469, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 470, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 471, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 472, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 473, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:22] {3343} INFO -  at 31.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:22] {3166} INFO - iteration 474, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 475, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 476, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 477, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 478, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 479, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 480, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 481, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 482, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 483, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 484, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 485, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 486, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 487, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 488, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 489, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 490, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 491, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 492, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:23] {3343} INFO -  at 32.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:23] {3166} INFO - iteration 493, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 494, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 495, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 496, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 497, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 498, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 499, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 500, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 501, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 502, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 503, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 504, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 505, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 506, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 507, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 508, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 509, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 510, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 511, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 33.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 512, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:24] {3343} INFO -  at 34.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:24] {3166} INFO - iteration 513, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 514, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 515, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 516, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 517, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 518, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 519, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 520, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 521, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 522, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 523, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 524, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 525, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 526, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 527, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 528, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 529, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 530, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 531, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:25] {3343} INFO -  at 34.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:25] {3166} INFO - iteration 532, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 533, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 534, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 535, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 536, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 537, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 538, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 539, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 540, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 541, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 542, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 543, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 544, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 545, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 546, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 547, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 548, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 549, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 550, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 551, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 35.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 552, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:26] {3343} INFO -  at 36.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:26] {3166} INFO - iteration 553, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 554, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 555, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 556, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 557, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 558, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 559, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 560, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 561, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 562, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 563, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 564, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 565, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 566, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 567, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 568, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 36.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 569, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:27] {3343} INFO -  at 37.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:27] {3166} INFO - iteration 570, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 571, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 572, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 573, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 574, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 575, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 576, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 577, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 578, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 579, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 580, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 581, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 582, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 583, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 584, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 585, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 586, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 37.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588

[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 587, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:28] {3343} INFO -  at 38.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:28] {3166} INFO - iteration 588, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 589, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 590, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 591, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 592, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 593, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 594, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 595, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 596, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 597, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 598, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 599, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 600, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 601, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 602, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 603, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 604, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:29] {3343} INFO -  at 38.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:29] {3166} INFO - iteration 605, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 606, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 607, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 608, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 609, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 610, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 611, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 612, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 613, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 614, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 615, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 616, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 617, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 618, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 619, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 620, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 621, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 622, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 623, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:30] {3343} INFO -  at 39.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:30] {3166} INFO - iteration 624, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 625, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 626, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 627, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 628, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 629, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 630, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 631, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 632, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 633, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 634, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 635, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 636, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 637, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 638, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 639, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 640, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 641, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 642, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:31] {3343} INFO -  at 40.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:31] {3166} INFO - iteration 643, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 644, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 645, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 646, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 647, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 648, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 649, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 650, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 651, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 652, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 653, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 654, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 655, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 656, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 657, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 658, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 659, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 660, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 661, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 41.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 662, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:32] {3343} INFO -  at 42.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:32] {3166} INFO - iteration 663, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 664, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 665, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 666, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 667, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 668, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 669, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 670, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 671, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 672, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 673, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 674, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 675, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 676, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 677, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 678, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 679, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:33] {3343} INFO -  at 42.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:33] {3166} INFO - iteration 680, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 681, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 682, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 683, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 684, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 685, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 686, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 687, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 688, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 689, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 690, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 691, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 692, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 693, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 694, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 695, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 696, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 697, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 698, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:34] {3343} INFO -  at 43.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:34] {3166} INFO - iteration 699, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 700, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 701, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 702, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 703, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 704, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 705, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 706, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 707, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 708, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 709, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 710, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 711, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 712, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 713, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 714, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 715, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 716, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 717, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:35] {3343} INFO -  at 44.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:35] {3166} INFO - iteration 718, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 719, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 720, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 721, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 722, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 723, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 724, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 725, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 726, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 727, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 728, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 729, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 730, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 731, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 732, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 733, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 734, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 735, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 736, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 45.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 737, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:36] {3343} INFO -  at 46.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:36] {3166} INFO - iteration 738, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 739, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 740, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 741, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 742, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 743, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 744, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 745, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 746, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 747, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 748, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 749, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 750, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 751, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 752, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 753, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 754, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 755, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 756, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 757, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:37] {3343} INFO -  at 46.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:37] {3166} INFO - iteration 758, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 759, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 760, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 761, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 762, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 763, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 764, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 765, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 766, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 767, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 768, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 769, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 770, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 771, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 772, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 773, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 774, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 775, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 776, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 47.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 777, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:38] {3343} INFO -  at 48.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:38] {3166} INFO - iteration 778, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 779, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 780, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 781, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 782, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 783, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 784, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 785, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 786, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 787, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 788, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 789, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 790, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 791, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 792, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 793, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 794, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 795, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 796, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 797, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:39] {3343} INFO -  at 48.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:39] {3166} INFO - iteration 798, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 799, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 800, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 801, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 802, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 803, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 804, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 805, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 806, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 807, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 808, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 809, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 810, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 811, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 812, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 813, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 814, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 815, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 816, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:40] {3343} INFO -  at 49.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:40] {3166} INFO - iteration 817, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 818, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 819, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 820, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 821, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 822, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 823, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 824, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 825, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 826, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 827, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 828, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 829, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 830, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 831, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 832, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 833, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:41] {3343} INFO -  at 50.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:41] {3166} INFO - iteration 834, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:42] {3343} INFO -  at 51.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:42] {3166} INFO - iteration 835, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:42] {3343} INFO -  at 51.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:42] {3166} INFO - iteration 836, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:42] {3343} INFO -  at 51.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:42] {3166} INFO - iteration 837, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:42] {3343} INFO -  at 51.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:42] {3166} INFO - iteration 838, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:42] {3343} INFO -  at 51.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:42] {3166} INFO - iteration 839, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:42] {3343} INFO -  at 51.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:42] {3166} INFO - iteration 840, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:42] {3343} INFO -  at 51.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:42] {3166} INFO - iteration 841, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:42] {3343} INFO -  at 51.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:42] {3166} INFO - iteration 842, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:42] {3343} INFO -  at 51.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:42] {3166} INFO - iteration 843, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:42] {3343} INFO -  at 51.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:42] {3166} INFO - iteration 844, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:42] {3343} INFO -  at 51.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:42] {3166} INFO - iteration 845, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:43] {3343} INFO -  at 52.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:43] {3166} INFO - iteration 846, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:43] {3343} INFO -  at 52.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588

[flaml.automl: 04-23 11:45:43] {3166} INFO - iteration 847, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:43] {3343} INFO -  at 52.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:43] {3166} INFO - iteration 848, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:43] {3343} INFO -  at 52.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:43] {3166} INFO - iteration 849, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:43] {3343} INFO -  at 52.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:43] {3166} INFO - iteration 850, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:43] {3343} INFO -  at 52.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:43] {3166} INFO - iteration 851, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:43] {3343} INFO -  at 52.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:43] {3166} INFO - iteration 852, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:43] {3343} INFO -  at 52.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:43] {3166} INFO - iteration 853, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:43] {3343} INFO -  at 52.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:43] {3166} INFO - iteration 854, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:43] {3343} INFO -  at 52.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:43] {3166} INFO - iteration 855, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:43] {3343} INFO -  at 52.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:43] {3166} INFO - iteration 856, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:43] {3343} INFO -  at 52.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:43] {3166} INFO - iteration 857, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:44] {3343} INFO -  at 53.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:44] {3166} INFO - iteration 858, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:44] {3343} INFO -  at 53.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:44] {3166} INFO - iteration 859, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:44] {3343} INFO -  at 53.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588

[flaml.automl: 04-23 11:45:44] {3166} INFO - iteration 860, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:44] {3343} INFO -  at 53.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:44] {3166} INFO - iteration 861, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:44] {3343} INFO -  at 53.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:44] {3166} INFO - iteration 862, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:44] {3343} INFO -  at 53.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:44] {3166} INFO - iteration 863, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:44] {3343} INFO -  at 53.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:44] {3166} INFO - iteration 864, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:44] {3343} INFO -  at 53.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:44] {3166} INFO - iteration 865, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:44] {3343} INFO -  at 53.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:44] {3166} INFO - iteration 866, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:44] {3343} INFO -  at 53.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:44] {3166} INFO - iteration 867, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:44] {3343} INFO -  at 53.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:44] {3166} INFO - iteration 868, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:45] {3343} INFO -  at 54.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:45] {3166} INFO - iteration 869, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:45] {3343} INFO -  at 54.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:45] {3166} INFO - iteration 870, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:45] {3343} INFO -  at 54.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:45] {3166} INFO - iteration 871, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:45] {3343} INFO -  at 54.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:45] {3166} INFO - iteration 872, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:45] {3343} INFO -  at 54.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:45] {3166} INFO - iteration 873, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:45] {3343} INFO -  at 54.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:45] {3166} INFO - iteration 874, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:45] {3343} INFO -  at 54.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:45] {3166} INFO - iteration 875, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:46] {3343} INFO -  at 55.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:46] {3166} INFO - iteration 876, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:46] {3343} INFO -  at 55.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:46] {3166} INFO - iteration 877, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:46] {3343} INFO -  at 55.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:46] {3166} INFO - iteration 878, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:46] {3343} INFO -  at 55.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:46] {3166} INFO - iteration 879, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:46] {3343} INFO -  at 55.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:46] {3166} INFO - iteration 880, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:46] {3343} INFO -  at 55.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:46] {3166} INFO - iteration 881, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:46] {3343} INFO -  at 55.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:46] {3166} INFO - iteration 882, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:46] {3343} INFO -  at 55.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:46] {3166} INFO - iteration 883, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:47] {3343} INFO -  at 56.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:47] {3166} INFO - iteration 884, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:47] {3343} INFO -  at 56.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:47] {3166} INFO - iteration 885, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:47] {3343} INFO -  at 56.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:47] {3166} INFO - iteration 886, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:47] {3343} INFO -  at 56.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:47] {3166} INFO - iteration 887, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:47] {3343} INFO -  at 56.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:47] {3166} INFO - iteration 888, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:47] {3343} INFO -  at 56.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:47] {3166} INFO - iteration 889, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:47] {3343} INFO -  at 56.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:47] {3166} INFO - iteration 890, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:47] {3343} INFO -  at 56.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:47] {3166} INFO - iteration 891, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:47] {3343} INFO -  at 56.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:47] {3166} INFO - iteration 892, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:47] {3343} INFO -  at 56.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:47] {3166} INFO - iteration 893, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 894, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 895, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 896, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 897, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 898, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 899, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 900, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 901, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 902, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 903, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 904, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 905, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 906, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 907, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 908, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 909, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:48] {3343} INFO -  at 57.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:48] {3166} INFO - iteration 910, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:49] {3343} INFO -  at 58.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:49] {3166} INFO - iteration 911, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:49] {3343} INFO -  at 58.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:49] {3166} INFO - iteration 912, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:49] {3343} INFO -  at 58.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:49] {3166} INFO - iteration 913, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:49] {3343} INFO -  at 58.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:49] {3166} INFO - iteration 914, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:49] {3343} INFO -  at 58.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:49] {3166} INFO - iteration 915, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:49] {3343} INFO -  at 58.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:49] {3166} INFO - iteration 916, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:49] {3343} INFO -  at 58.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:49] {3166} INFO - iteration 917, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:49] {3343} INFO -  at 58.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:49] {3166} INFO - iteration 918, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:49] {3343} INFO -  at 58.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:49] {3166} INFO - iteration 919, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:49] {3343} INFO -  at 58.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:49] {3166} INFO - iteration 920, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:49] {3343} INFO -  at 58.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:49] {3166} INFO - iteration 921, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:50] {3343} INFO -  at 59.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:50] {3166} INFO - iteration 922, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:50] {3343} INFO -  at 59.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:50] {3166} INFO - iteration 923, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:50] {3343} INFO -  at 59.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:50] {3166} INFO - iteration 924, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:50] {3343} INFO -  at 59.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:50] {3166} INFO - iteration 925, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:50] {3343} INFO -  at 59.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:50] {3166} INFO - iteration 926, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:50] {3343} INFO -  at 59.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:50] {3166} INFO - iteration 927, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:50] {3343} INFO -  at 59.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:50] {3166} INFO - iteration 928, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:50] {3343} INFO -  at 59.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:50] {3166} INFO - iteration 929, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:50] {3343} INFO -  at 59.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:50] {3166} INFO - iteration 930, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 931, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 932, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 933, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 934, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 935, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 936, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 937, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 938, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 939, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 940, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 941, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 942, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 943, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 944, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 60.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 945, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:51] {3343} INFO -  at 61.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:51] {3166} INFO - iteration 946, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:52] {3343} INFO -  at 61.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:52] {3166} INFO - iteration 947, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:52] {3343} INFO -  at 61.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:52] {3166} INFO - iteration 948, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:52] {3343} INFO -  at 61.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:52] {3166} INFO - iteration 949, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:52] {3343} INFO -  at 61.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:52] {3166} INFO - iteration 950, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:52] {3343} INFO -  at 61.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:52] {3166} INFO - iteration 951, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:52] {3343} INFO -  at 61.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:52] {3166} INFO - iteration 952, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:52] {3343} INFO -  at 61.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:52] {3166} INFO - iteration 953, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:52] {3343} INFO -  at 61.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:52] {3166} INFO - iteration 954, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:52] {3343} INFO -  at 61.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:52] {3166} INFO - iteration 955, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:52] {3343} INFO -  at 61.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:52] {3166} INFO - iteration 956, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:52] {3343} INFO -  at 61.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:52] {3166} INFO - iteration 957, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:52] {3343} INFO -  at 61.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:52] {3166} INFO - iteration 958, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:52] {3343} INFO -  at 61.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:52] {3166} INFO - iteration 959, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:52] {3343} INFO -  at 61.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:52] {3166} INFO - iteration 960, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:53] {3343} INFO -  at 62.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:53] {3166} INFO - iteration 961, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:53] {3343} INFO -  at 62.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:53] {3166} INFO - iteration 962, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:53] {3343} INFO -  at 62.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:53] {3166} INFO - iteration 963, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:53] {3343} INFO -  at 62.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:53] {3166} INFO - iteration 964, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:53] {3343} INFO -  at 62.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:53] {3166} INFO - iteration 965, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:53] {3343} INFO -  at 62.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:53] {3166} INFO - iteration 966, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:53] {3343} INFO -  at 62.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:53] {3166} INFO - iteration 967, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:53] {3343} INFO -  at 62.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:53] {3166} INFO - iteration 968, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:53] {3343} INFO -  at 62.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:53] {3166} INFO - iteration 969, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:53] {3343} INFO -  at 62.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:53] {3166} INFO - iteration 970, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:53] {3343} INFO -  at 62.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:53] {3166} INFO - iteration 971, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:53] {3343} INFO -  at 62.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:53] {3166} INFO - iteration 972, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:53] {3343} INFO -  at 62.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:53] {3166} INFO - iteration 973, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:54] {3343} INFO -  at 63.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:54] {3166} INFO - iteration 974, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:54] {3343} INFO -  at 63.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:54] {3166} INFO - iteration 975, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:54] {3343} INFO -  at 63.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:54] {3166} INFO - iteration 976, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:54] {3343} INFO -  at 63.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:54] {3166} INFO - iteration 977, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:54] {3343} INFO -  at 63.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:54] {3166} INFO - iteration 978, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:54] {3343} INFO -  at 63.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:54] {3166} INFO - iteration 979, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:54] {3343} INFO -  at 63.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:54] {3166} INFO - iteration 980, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:54] {3343} INFO -  at 63.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:54] {3166} INFO - iteration 981, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:54] {3343} INFO -  at 63.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:54] {3166} INFO - iteration 982, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:54] {3343} INFO -  at 63.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:54] {3166} INFO - iteration 983, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:54] {3343} INFO -  at 63.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:54] {3166} INFO - iteration 984, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:54] {3343} INFO -  at 63.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:54] {3166} INFO - iteration 985, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:54] {3343} INFO -  at 63.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:54] {3166} INFO - iteration 986, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:54] {3343} INFO -  at 63.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:54] {3166} INFO - iteration 987, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:55] {3343} INFO -  at 64.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:55] {3166} INFO - iteration 988, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:55] {3343} INFO -  at 64.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:55] {3166} INFO - iteration 989, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:55] {3343} INFO -  at 64.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:55] {3166} INFO - iteration 990, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:55] {3343} INFO -  at 64.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:55] {3166} INFO - iteration 991, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:55] {3343} INFO -  at 64.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:55] {3166} INFO - iteration 992, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:55] {3343} INFO -  at 64.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:55] {3166} INFO - iteration 993, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:55] {3343} INFO -  at 64.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:55] {3166} INFO - iteration 994, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:56] {3343} INFO -  at 65.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:56] {3166} INFO - iteration 995, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:56] {3343} INFO -  at 65.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:56] {3166} INFO - iteration 996, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:56] {3343} INFO -  at 65.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:56] {3166} INFO - iteration 997, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:56] {3343} INFO -  at 65.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:56] {3166} INFO - iteration 998, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:56] {3343} INFO -  at 65.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:56] {3166} INFO - iteration 999, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:57] {3343} INFO -  at 66.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:57] {3166} INFO - iteration 1000, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:57] {3343} INFO -  at 66.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:57] {3166} INFO - iteration 1001, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:57] {3343} INFO -  at 66.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:57] {3166} INFO - iteration 1002, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:57] {3343} INFO -  at 66.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:57] {3166} INFO - iteration 1003, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:57] {3343} INFO -  at 66.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:57] {3166} INFO - iteration 1004, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:57] {3343} INFO -  at 66.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:57] {3166} INFO - iteration 1005, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:57] {3343} INFO -  at 66.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:57] {3166} INFO - iteration 1006, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:57] {3343} INFO -  at 66.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:57] {3166} INFO - iteration 1007, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:57] {3343} INFO -  at 66.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:57] {3166} INFO - iteration 1008, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:57] {3343} INFO -  at 66.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:57] {3166} INFO - iteration 1009, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:57] {3343} INFO -  at 66.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:57] {3166} INFO - iteration 1010, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:57] {3343} INFO -  at 66.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:57] {3166} INFO - iteration 1011, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:57] {3343} INFO -  at 66.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:57] {3166} INFO - iteration 1012, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:58] {3343} INFO -  at 67.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:58] {3166} INFO - iteration 1013, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:58] {3343} INFO -  at 67.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:58] {3166} INFO - iteration 1014, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:58] {3343} INFO -  at 67.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:58] {3166} INFO - iteration 1015, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:58] {3343} INFO -  at 67.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:58] {3166} INFO - iteration 1016, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:58] {3343} INFO -  at 67.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:58] {3166} INFO - iteration 1017, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:58] {3343} INFO -  at 67.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:58] {3166} INFO - iteration 1018, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:58] {3343} INFO -  at 67.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:58] {3166} INFO - iteration 1019, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:58] {3343} INFO -  at 67.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:58] {3166} INFO - iteration 1020, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:58] {3343} INFO -  at 67.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:58] {3166} INFO - iteration 1021, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:58] {3343} INFO -  at 67.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:58] {3166} INFO - iteration 1022, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:58] {3343} INFO -  at 67.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:58] {3166} INFO - iteration 1023, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:58] {3343} INFO -  at 67.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:58] {3166} INFO - iteration 1024, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:58] {3343} INFO -  at 67.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:58] {3166} INFO - iteration 1025, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:59] {3343} INFO -  at 68.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:59] {3166} INFO - iteration 1026, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:59] {3343} INFO -  at 68.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:59] {3166} INFO - iteration 1027, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:59] {3343} INFO -  at 68.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:59] {3166} INFO - iteration 1028, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:45:59] {3343} INFO -  at 68.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:59] {3166} INFO - iteration 1029, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:59] {3343} INFO -  at 68.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:59] {3166} INFO - iteration 1030, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:59] {3343} INFO -  at 68.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:59] {3166} INFO - iteration 1031, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:59] {3343} INFO -  at 68.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:59] {3166} INFO - iteration 1032, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:59] {3343} INFO -  at 68.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:59] {3166} INFO - iteration 1033, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:59] {3343} INFO -  at 68.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:59] {3166} INFO - iteration 1034, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:59] {3343} INFO -  at 68.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:59] {3166} INFO - iteration 1035, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:45:59] {3343} INFO -  at 68.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:45:59] {3166} INFO - iteration 1036, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:00] {3343} INFO -  at 69.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:00] {3166} INFO - iteration 1037, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:00] {3343} INFO -  at 69.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:00] {3166} INFO - iteration 1038, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:00] {3343} INFO -  at 69.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:00] {3166} INFO - iteration 1039, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:00] {3343} INFO -  at 69.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:00] {3166} INFO - iteration 1040, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:00] {3343} INFO -  at 69.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:00] {3166} INFO - iteration 1041, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:46:00] {3343} INFO -  at 69.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:00] {3166} INFO - iteration 1042, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:00] {3343} INFO -  at 69.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:00] {3166} INFO - iteration 1043, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:00] {3343} INFO -  at 69.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:00] {3166} INFO - iteration 1044, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:01] {3343} INFO -  at 70.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:01] {3166} INFO - iteration 1045, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:01] {3343} INFO -  at 70.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:01] {3166} INFO - iteration 1046, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:01] {3343} INFO -  at 70.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:01] {3166} INFO - iteration 1047, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:01] {3343} INFO -  at 70.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:01] {3166} INFO - iteration 1048, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:01] {3343} INFO -  at 70.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:01] {3166} INFO - iteration 1049, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:01] {3343} INFO -  at 70.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:01] {3166} INFO - iteration 1050, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:01] {3343} INFO -  at 70.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:01] {3166} INFO - iteration 1051, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:01] {3343} INFO -  at 70.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:01] {3166} INFO - iteration 1052, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:01] {3343} INFO -  at 70.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:01] {3166} INFO - iteration 1053, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:01] {3343} INFO -  at 70.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:01] {3166} INFO - iteration 1054, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:01] {3343} INFO -  at 70.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588

[flaml.automl: 04-23 11:46:01] {3166} INFO - iteration 1055, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:01] {3343} INFO -  at 70.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:01] {3166} INFO - iteration 1056, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:01] {3343} INFO -  at 71.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:01] {3166} INFO - iteration 1057, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1058, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1059, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1060, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1061, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1062, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1063, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1064, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1065, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1066, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1067, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1068, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1069, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1070, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1071, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1072, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:02] {3343} INFO -  at 71.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:02] {3166} INFO - iteration 1073, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1074, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1075, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1076, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1077, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1078, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1079, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1080, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1081, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1082, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1083, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1084, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1085, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1086, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1087, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:03] {3343} INFO -  at 72.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:03] {3166} INFO - iteration 1088, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1089, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1090, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1091, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1092, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1093, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1094, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1095, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1096, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1097, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1098, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1099, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1100, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1101, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1102, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 73.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1103, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:04] {3343} INFO -  at 74.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:04] {3166} INFO - iteration 1104, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:05] {3343} INFO -  at 74.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:05] {3166} INFO - iteration 1105, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:05] {3343} INFO -  at 74.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:05] {3166} INFO - iteration 1106, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:46:05] {3343} INFO -  at 74.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:05] {3166} INFO - iteration 1107, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:05] {3343} INFO -  at 74.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:05] {3166} INFO - iteration 1108, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:05] {3343} INFO -  at 74.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:05] {3166} INFO - iteration 1109, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:05] {3343} INFO -  at 74.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:05] {3166} INFO - iteration 1110, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:05] {3343} INFO -  at 74.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:05] {3166} INFO - iteration 1111, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:05] {3343} INFO -  at 74.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:05] {3166} INFO - iteration 1112, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:05] {3343} INFO -  at 74.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:05] {3166} INFO - iteration 1113, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:05] {3343} INFO -  at 74.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:05] {3166} INFO - iteration 1114, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:06] {3343} INFO -  at 75.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:06] {3166} INFO - iteration 1115, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:06] {3343} INFO -  at 75.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:06] {3166} INFO - iteration 1116, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:06] {3343} INFO -  at 75.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:06] {3166} INFO - iteration 1117, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:06] {3343} INFO -  at 75.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:06] {3166} INFO - iteration 1118, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:06] {3343} INFO -  at 75.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:06] {3166} INFO - iteration 1119, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:46:06] {3343} INFO -  at 75.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:06] {3166} INFO - iteration 1120, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:06] {3343} INFO -  at 75.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:06] {3166} INFO - iteration 1121, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:06] {3343} INFO -  at 75.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:06] {3166} INFO - iteration 1122, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:06] {3343} INFO -  at 75.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:06] {3166} INFO - iteration 1123, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:06] {3343} INFO -  at 75.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:06] {3166} INFO - iteration 1124, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:06] {3343} INFO -  at 75.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:06] {3166} INFO - iteration 1125, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1126, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1127, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1128, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1129, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1130, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1131, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1132, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1133, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1134, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1135, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1136, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1137, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1138, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1139, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1140, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:07] {3343} INFO -  at 76.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:07] {3166} INFO - iteration 1141, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:08] {3343} INFO -  at 77.0s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:08] {3166} INFO - iteration 1142, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:08] {3343} INFO -  at 77.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:08] {3166} INFO - iteration 1143, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:08] {3343} INFO -  at 77.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:08] {3166} INFO - iteration 1144, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:08] {3343} INFO -  at 77.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:08] {3166} INFO - iteration 1145, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:46:08] {3343} INFO -  at 77.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:08] {3166} INFO - iteration 1146, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:08] {3343} INFO -  at 77.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:08] {3166} INFO - iteration 1147, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:08] {3343} INFO -  at 77.4s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:08] {3166} INFO - iteration 1148, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:08] {3343} INFO -  at 77.5s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:08] {3166} INFO - iteration 1149, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:08] {3343} INFO -  at 77.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:08] {3166} INFO - iteration 1150, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:08] {3343} INFO -  at 77.6s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:08] {3166} INFO - iteration 1151, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:08] {3343} INFO -  at 77.7s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:08] {3166} INFO - iteration 1152, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:08] {3343} INFO -  at 77.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:08] {3166} INFO - iteration 1153, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:08] {3343} INFO -  at 77.8s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:08] {3166} INFO - iteration 1154, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:08] {3343} INFO -  at 77.9s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:08] {3166} INFO - iteration 1155, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:09] {3343} INFO -  at 78.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:09] {3166} INFO - iteration 1156, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:09] {3343} INFO -  at 78.1s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:09] {3166} INFO - iteration 1157, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]
[flaml.automl: 04-23 11:46:09] {3343} INFO -  at 78.2s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:09] {3166} INFO - iteration 1158, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

[flaml.automl: 04-23 11:46:09] {3343} INFO -  at 78.3s,	estimator rf's best error=105.3588,	best estimator rf's best error=105.3588
[flaml.automl: 04-23 11:46:09] {3166} INFO - iteration 1159, current learner rf
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flaml/automl.py:294: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  sampled_y_train = self.y_train[:sample_size]

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
fig= plt.figure(figsize=(5.3,3.5))
ax = fig.add_axes([0,0,1,1])
x= ['Pred1', 'Pred2', 'Pred3','Pred4','Pred5','Pred6','Pred7']
students1=rmse
students2= [48,32,22,18,16]
plt.hlines([rmse_r], -0.5, 6.8, color='orange', linewidth=2)
x = np.arange(7)
wid= 0.7
graph1=ax.bar(x,students1,wid, color='#00BFFF', alpha=1)
#graph2=ax.bar(x+0.2,students2,wid, color='#00BFFF', alpha=1)
#plt.legend(['15min','60min'],title='Data resolution')
i= 0
for p in graph1:
    width = p.get_width()
    height = p.get_height()
    x, y = p.get_xy()
    plt.text(x+width/2,
             y+height+0.02,
             str(students1[i]),
             ha='center',
             weight='bold',fontsize=10, color='#00BFFF', alpha=1)
    i+=1

ax.set_xticks([0,1,2,3,4,5,6])
ax.set_xticklabels(['Pred1', 'Pred2', 'Pred3','Pred4','Pred5','Pred6','Pred7'])
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.yticks(np.arange(0,0.7, step=0.1))

#plt.xlabel('Tolerance,Tc (%)', fontsize=19)
plt.ylabel('NRMSE', fontsize=19)
plt.setp(ax.spines.values(), linewidth=1.4)
plt.title("CO-FLAML-RF",fontsize=18)
plt.savefig("Pred_CO_FLAML_RF.pdf", format="pdf", bbox_inches="tight")
plt.show()

X=CO_Data[['Net Signal','Lab1','Temp','RH','Month','Day_of_week','Hour']]
y=CO_Data['Ref']
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size = 0.2,shuffle=True)

# Initialize an AutoML instance
automl = AutoML()
# Specify automl goal and constraint
automl_settings = {
    "time_budget": 1440,  # in seconds
    "metric": 'rmse',
    "eval_method":'holdout',
    "task": 'regression',
    "log_file_name": "california.log",
}

Pred=[]
rmse=[]
model=[]
RS=[]
R=[]
for i in range(10):
    X_Train, X_Test, y_Train, y_Test =train_test_split(X_train,y_train,test_size = 0.2,shuffle=True)
    # Train with labeled input data
    automl.fit(X_train=X_Train.drop(['Lab1'], axis=1), y_train=y_Train,**automl_settings,estimator_list=["rf"])
    pred=automl.predict(X_test.drop(['Lab1'], axis=1))
    R2=round(sm.r2_score(y_test, pred), 2)
    r=round(np.corrcoef(y_test, pred)[0, 1],2)
    RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),5)
    #print(r,R2,RMSE)
    # Predict
    #print(automl.predict(X_test))
    # Print the best model
    #print(automl.model.estimator)
    Pred.append(pred)
    rmse.append(RMSE)
    model.append(automl.model.estimator)
    RS.append(R2)
    R.append(r)

print(np.round(np.mean(R),2),np.round(np.mean(RS),2),np.round(np.mean(rmse),2))

In [ ]:
print(np.round(np.mean(R),2),np.round(np.mean(RS),2),np.round(np.mean(rmse),2))

Pred=[]
rmse=[]
model=[]
for i in range(20):
    X_Train, X_Test, y_Train, y_Test =train_test_split(X_train,y_train,test_size = 0.2,shuffle=True)
    # Train with labeled input data
    automl.fit(X_train=X_Train.drop(['Lab1'], axis=1), y_train=y_Train,**automl_settings,estimator_list=["xgboost"])
    pred=automl.predict(X_test.drop(['Lab1'], axis=1))
    R2=round(sm.r2_score(y_test, pred), 2)
    r=round(np.corrcoef(y_test, pred)[0, 1],2)
    RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),5)
    print(r,R2,RMSE)
    # Predict
    #print(automl.predict(X_test))
    # Print the best model
    print(automl.model.estimator)
    Pred.append(pred)
    rmse.append(RMSE)
    model.append(automl.model.estimator)

Sorted_pred=[]
sort_index = np.argsort(rmse)
for i in sort_index:
    Sorted_pred.append(Pred[i])
ind=[i for i in range(len(y_test))]
import matplotlib.pyplot as plt
fig= plt.figure(figsize=(7,5))
plt.plot(ind[:200],y_test[:200], color='blue',linewidth=1.5)
plt.plot(ind[:200],Sorted_pred[1][:200],color='salmon',linewidth=1.5)
plt.plot(ind[:200],Sorted_pred[17][:200],color='teal',linewidth=1.5)
plt.legend(['Actual','p10','p90'],loc = 2, bbox_to_anchor = (0.75,1), fontsize=12)
#plt.plot(ind[:200],Sorted_pred[4][:200],color='black',linewidth=0.2)
#plt.fill_between(np.array(ind[:200]), np.array(Sorted_pred[0][:200]), np.array(Sorted_pred[4][:200]), 
                 #color='blue', alpha=0.15)
#plt.plot(ind,Pred[2],color='darkgoldenrod')
#plt.plot(ind,Pred[3],color='magenta')
#plt.plot(ind,Pred[4],color='purple')
plt.xlabel('Observation number',fontsize=16)
plt.ylabel('Concentraton (ppb)',fontsize=16)
plt.title('CO-XGBoost',fontsize=16)
plt.savefig("co_xgboost.pdf", format="pdf", bbox_inches="tight")

Pred=[]
rmse=[]
model=[]
for i in range(20):
    X_Train, X_Test, y_Train, y_Test =train_test_split(X_train,y_train,test_size = 0.2,shuffle=True)
    # Train with labeled input data
    automl.fit(X_train=X_Train.drop(['Lab1'], axis=1), y_train=y_Train,**automl_settings,estimator_list=["xgb_limitdepth"])
    pred=automl.predict(X_test.drop(['Lab1'], axis=1))
    R2=round(sm.r2_score(y_test, pred), 2)
    r=round(np.corrcoef(y_test, pred)[0, 1],2)
    RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),5)
    print(r,R2,RMSE)
    # Predict
    #print(automl.predict(X_test))
    # Print the best model
    print(automl.model.estimator)
    Pred.append(pred)
    rmse.append(RMSE)
    model.append(automl.model.estimator)

Sorted_pred=[]
sort_index = np.argsort(rmse)
for i in sort_index:
    Sorted_pred.append(Pred[i])
ind=[i for i in range(len(y_test))]
import matplotlib.pyplot as plt
fig= plt.figure(figsize=(7,5))
plt.plot(ind[:200],y_test[:200], color='blue',linewidth=1.5)
plt.plot(ind[:200],Sorted_pred[1][:200],color='salmon',linewidth=1.5)
plt.plot(ind[:200],Sorted_pred[17][:200],color='teal',linewidth=1.5)
plt.legend(['Actual','p10','p90'],loc = 2, bbox_to_anchor = (0.75,1), fontsize=12)
#plt.plot(ind[:200],Sorted_pred[4][:200],color='black',linewidth=0.2)
#plt.fill_between(np.array(ind[:200]), np.array(Sorted_pred[0][:200]), np.array(Sorted_pred[4][:200]), 
                 #color='blue', alpha=0.15)
#plt.plot(ind,Pred[2],color='darkgoldenrod')
#plt.plot(ind,Pred[3],color='magenta')
#plt.plot(ind,Pred[4],color='purple')
plt.xlabel('Observation number',fontsize=16)
plt.ylabel('Concentraton (ppb)',fontsize=16)
plt.title('CO-CO-LDXGBooost',fontsize=16)
plt.savefig("co_ldxgboost.pdf", format="pdf", bbox_inches="tight")

Sorted_pred=[]
sort_index = np.argsort(rmse)
for i in sort_index:
    Sorted_pred.append(Pred[i])
ind=[i for i in range(len(y_test))]
import matplotlib.pyplot as plt
fig= plt.figure(figsize=(7,5))
plt.plot(ind[:200],y_test[:200], color='blue',linewidth=1.5)
plt.plot(ind[:200],Sorted_pred[1][:200],color='salmon',linewidth=1.5)
plt.plot(ind[:200],Sorted_pred[17][:200],color='teal',linewidth=1.5)
plt.legend(['Actual','p10','p90'],loc = 2, bbox_to_anchor = (0.75,1), fontsize=12)
#plt.plot(ind[:200],Sorted_pred[4][:200],color='black',linewidth=0.2)
#plt.fill_between(np.array(ind[:200]), np.array(Sorted_pred[0][:200]), np.array(Sorted_pred[4][:200]), 
                 #color='blue', alpha=0.15)
#plt.plot(ind,Pred[2],color='darkgoldenrod')
#plt.plot(ind,Pred[3],color='magenta')
#plt.plot(ind,Pred[4],color='purple')
plt.xlabel('Observation number',fontsize=16)
plt.ylabel('Concentraton (ppb)',fontsize=16)
plt.title('CO-LDXGBooost',fontsize=16)
plt.savefig("co_ldxgboost.pdf", format="pdf", bbox_inches="tight")

Pred=[]
rmse=[]
model=[]
for i in range(20):
    X_Train, X_Test, y_Train, y_Test =train_test_split(X_train,y_train,test_size = 0.2,shuffle=True)
    # Train with labeled input data
    automl.fit(X_train=X_Train.drop(['Lab1'], axis=1), y_train=y_Train,**automl_settings,estimator_list=["extra_tree"])
    pred=automl.predict(X_test.drop(['Lab1'], axis=1))
    R2=round(sm.r2_score(y_test, pred), 2)
    r=round(np.corrcoef(y_test, pred)[0, 1],2)
    RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),5)
    print(r,R2,RMSE)
    # Predict
    #print(automl.predict(X_test))
    # Print the best model
    print(automl.model.estimator)
    Pred.append(pred)
    rmse.append(RMSE)
    model.append(automl.model.estimator)

Sorted_pred=[]
sort_index = np.argsort(rmse)
for i in sort_index:
    Sorted_pred.append(Pred[i])
ind=[i for i in range(len(y_test))]
import matplotlib.pyplot as plt
fig= plt.figure(figsize=(7,5))
plt.plot(ind[:200],y_test[:200], color='blue',linewidth=1.5)
plt.plot(ind[:200],Sorted_pred[1][:200],color='salmon',linewidth=1.5)
plt.plot(ind[:200],Sorted_pred[17][:200],color='teal',linewidth=1.5)
plt.legend(['Actual','p10','p90'],loc = 2, bbox_to_anchor = (0.75,1), fontsize=12)
#plt.plot(ind[:200],Sorted_pred[4][:200],color='black',linewidth=0.2)
#plt.fill_between(np.array(ind[:200]), np.array(Sorted_pred[0][:200]), np.array(Sorted_pred[4][:200]), 
                 #color='blue', alpha=0.15)
#plt.plot(ind,Pred[2],color='darkgoldenrod')
#plt.plot(ind,Pred[3],color='magenta')
#plt.plot(ind,Pred[4],color='purple')
plt.xlabel('Observation number',fontsize=16)
plt.ylabel('Concentraton (ppb)',fontsize=16)
plt.title('CO-Extra Tree',fontsize=16)
plt.savefig("co_extra_tree.pdf", format="pdf", bbox_inches="tight")

from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
  
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel':  ['rbf']} 
  
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
grid.fit(X_train.drop(['Lab1'], axis=1), y_train)

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

from flaml.model import SKLearnEstimator

from flaml.model import SKLearnEstimator
# SKLearnEstimator is derived from BaseEstimator
import numpy as np

class RandomForestRegressor(SKLearnEstimator):
    def __init__(self, task="binary", **config):
        super().__init__(task, **config)

        if task in CLASSIFICATION:
            from sklearn.ensemble import RandomForestClassifier

            self.estimator_class =RandomForestClassifier 
        else:
            from sklearn.ensemble import RandomForestRegressor

            self.estimator_class =RandomForestRegressor

    @classmethod
    def search_space(cls, data_size, task):
        space = {
            "n_estimators": {
                "domain": {"domain": tune.loguniform(lower=100, upper=20000)},
                "low_cost_init_value": 100,
            },
            "max_features": {
                "domain": tune.loguniform(lower=0.1, upper=1),
                "low_cost_init_value": 0.1,
            },
            "max_leaf_nodes": {
                "domain": tune.lograndint(lower=100, upper=2500),
                "low_cost_init_value": 100,},
            "min_samples_split": {"domain": tune.lograndint(lower=1, upper=20),
            "init_value": 20,},
            
            "min_samples_leaf": {
                "domain": tune.lograndint(lower=1, upper=20),
                "init_value": 20,
            },
        }
        return space

from flaml import AutoML
from flaml import tune
automl = AutoML()
automl.add_learner("rfr",RandomForestRegressor )

automl_settings = {
    "time_budget": 1000,  # in seconds
    "metric": 'rmse',
    "task": 'regression',
    "log_file_name": "california.log",
}
# Train with labeled input data
automl.fit(X_train=X_train.drop(['Lab1'], axis=1), y_train=y_train,**automl_settings,estimator_list=["rfr"])
pred=automl.predict(X_test.drop(['Lab1'], axis=1))
R2=round(sm.r2_score(y_test, pred), 2)
r=round(np.corrcoef(y_test, pred)[0, 1],2)
RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),2)
print(r,R2,RMSE)

#  NO2 DATA

X=NO2_Data[['Net Signal','Lab1','Temp','RH','Month','Day_of_week','Hour','Ref_O3']]#'Ref_O3'
y=NO2_Data['Ref']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
#len(X_test)
X.shape

from flaml import AutoML
from sklearn.datasets import fetch_california_housing

# Initialize an AutoML instance
automl = AutoML()
# Specify automl goal and constraint
automl_settings = {
    "time_budget": 200,  # in seconds
    "metric": 'rmse',
    "task": 'regression',
    "log_file_name": "california.log",
}
# Train with labeled input data
automl.fit(X_train=X_train.drop(['Lab1'], axis=1), y_train=y_train,**automl_settings,estimator_list=["xgboost"])
pred=automl.predict(X_test.drop(['Lab1'], axis=1))
R2=round(sm.r2_score(y_test, pred), 2)
r=round(np.corrcoef(y_test, pred)[0, 1],2)
RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),2)
print(r,R2,RMSE)
# Predict
#print(automl.predict(X_test))
# Print the best model
print(automl.model.estimator)

from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
  
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel':  ['rbf', 'poly', 'sigmoid']} 
  
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
grid.fit(X_train.drop(['Lab1'], axis=1), y_train)

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

# O3 DATA

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error as mae
import sklearn.metrics as sm
import matplotlib.pyplot as plt
#,'Ref_CO','Ref_NO2','Ref_SO2'
X=O3_Data[['Net Signal','Lab1','Temp','RH','Month','Day_of_week','Hour','Ref_NO2']]#,'Ref_NO2'
y=O3_Data['Ref']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
len(X)

from flaml import AutoML
from sklearn.datasets import fetch_california_housing

# Initialize an AutoML instance
automl = AutoML()
# Specify automl goal and constraint
automl_settings = {
    "time_budget": 200,  # in seconds
    "metric": 'rmse',
    "task": 'regression',
    "log_file_name": "california.log",
}
# Train with labeled input data
automl.fit(X_train=X_train.drop(['Lab1'], axis=1), y_train=y_train,**automl_settings,estimator_list=["xgboost"])
pred=automl.predict(X_test.drop(['Lab1'], axis=1))
R2=round(sm.r2_score(y_test, pred), 2)
r=round(np.corrcoef(y_test, pred)[0, 1],2)
RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),2)
print(r,R2,RMSE)
# Predict
#print(automl.predict(X_test))
# Print the best model
print(automl.model.estimator)

# SO2 DATA

In [ ]:
import pandas as pd
Ref=pd.read_csv('Ref.csv')
Ref["CO"] = 1000 * Ref["CO"]
Ref['Date'] = pd.to_datetime(Ref['Date_Time'])
Ref=Ref.set_index('Date')
Ref.drop('Date_Time',axis = 1, inplace = True)
Ref=Ref.resample('5min').mean()
Ref=Ref[76463:137376]
Ref_CO=Ref['CO'].to_list()
Ref_NO2=Ref['NO2'].to_list()
Ref_SO2=Ref['SO2'].to_list()
Ref_O3=Ref['O3'].to_list()

In [ ]:
import pandas as pd
import scipy.io
import numpy as np
data = pd.read_csv('Conc_SO2.txt', header = None,low_memory=False)
data.columns=['Lab2','Temp','RH','Time','Ref']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_SO2=data
Data_so2=data
#signal=np.array(WE)-np.array(AE)
#Data_SO2['Net Signal']=signal
Data_SO2['Month']=Data_SO2.index.month
Data_SO2['Day_of_week']=Data_SO2.index.dayofweek
Data_SO2['Day']=Data_SO2.index.day
Data_SO2['Hour']=Data_SO2.index.hour
SO2_Data=Data_SO2
SO2_Data=SO2_Data.resample('5min').mean()
SO2_Data=SO2_Data[(SO2_Data[SO2_Data.columns] >= 0).all(axis=1)]
SO2_Data=SO2_Data.dropna() 
data = pd.read_csv('SO2.txt', header = None,low_memory=False)
data.columns=['WE','AE','Temp','RH','Time']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_SO2=data
Data_SO2['Ref']=Ref_SO2
WE=Data_SO2['WE'].to_list()
AE=Data_SO2['AE'].to_list()
signal=np.array(WE)-np.array(AE)
Data_SO2['Lab2']=Data_so2['Lab2'].to_list()
Data_SO2['Net Signal']=signal
Data_SO2['Month']=Data_SO2.index.month
Data_SO2['Day_of_week']=Data_SO2.index.dayofweek
Data_SO2['Day']=Data_SO2.index.day
Data_SO2['Hour']=Data_SO2.index.hour
SO2_Data=Data_SO2
SO2_Data.shape

In [ ]:
SO2_Data=SO2_Data[(SO2_Data[SO2_Data.columns] >= 0).all(axis=1)]
SO2_Data=SO2_Data.dropna()
SO2_Data=SO2_Data.resample('h').mean()
SO2_Data=SO2_Data.dropna()
SO2_Data.head()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error as mae
import sklearn.metrics as sm
import matplotlib.pyplot as plt
#'Ref_CO','Ref_NO2','Ref_O3',
X=SO2_Data[['Net Signal','Lab2','Temp','RH','Month','Day_of_week','Hour']]
y=SO2_Data['Ref']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
len(X)

from flaml import AutoML
from sklearn.datasets import fetch_california_housing

# Initialize an AutoML instance
automl = AutoML()
# Specify automl goal and constraint
automl_settings = {
    "time_budget": 200,  # in seconds
    "metric": 'rmse',
    "task": 'regression',
    "log_file_name": "california.log",
}
# Train with labeled input data
automl.fit(X_train=X_train.drop(['Lab2'], axis=1), y_train=y_train,**automl_settings,estimator_list=["xgboost"])
pred=automl.predict(X_test.drop(['Lab2'], axis=1))
R2=round(sm.r2_score(y_test, pred), 2)
r=round(np.corrcoef(y_test, pred)[0, 1],2)
RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),2)
print(r,R2,RMSE)
# Predict
#print(automl.predict(X_test))
# Print the best model
print(automl.model.estimator)

from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
  
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel':  ['rbf', 'poly', 'sigmoid']} 
  
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
grid.fit(X_train.drop(['Lab2'], axis=1), y_train)

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

In [1]:
import pandas as pd
from pandas import MultiIndex, Int16Dtype
Ref=pd.read_csv('Ref.csv')
Ref["CO"] = 1000 * Ref["CO"]
Ref['Date'] = pd.to_datetime(Ref['Date_Time'])
Ref=Ref.set_index('Date')
Ref.drop('Date_Time',axis = 1, inplace = True)
Ref=Ref.resample('5min').mean()
Ref=Ref[76463:137376]
Ref_CO=Ref['CO'].to_list()
Ref_NO2=Ref['NO2'].to_list()
Ref_SO2=Ref['SO2'].to_list()
Ref_O3=Ref['O3'].to_list()

In [2]:
import random
import pandas as pd
import scipy.io
import numpy as np
data = pd.read_csv('CO.txt', header = None,low_memory=False)
data.columns=['WE','AE','Temp','RH','Time']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_CO=data
Data_CO['Ref']=Ref_CO
index_names = Data_CO[ (Data_CO['WE'] >1000)].index
Data_CO.drop(index_names, inplace = True)
WE=Data_CO['WE'].to_list()
AE=Data_CO['AE'].to_list()
signal=np.array(WE)-np.array(AE)
Data_CO['Net Signal']=signal
Data_CO['Month']=Data_CO.index.month
Data_CO['Day_of_week']=Data_CO.index.dayofweek
Data_CO['Day']=Data_CO.index.day
Data_CO['Hour']=Data_CO.index.hour
CO_Data=Data_CO
CO_Data=CO_Data[(CO_Data[CO_Data.columns] >= 0).all(axis=1)]
CO_Data=CO_Data.dropna()
data = pd.read_csv('Conc_CO.txt', header = None,low_memory=False)
data.columns=['Lab1','Temp','RH','Time','Ref']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_CO=data
Data_CO.drop(index_names, inplace = True)
signal=np.array(WE)-np.array(AE)
Data_CO['Net Signal']=signal
Data_CO['Month']=Data_CO.index.month
Data_CO['Day_of_week']=Data_CO.index.dayofweek
Data_CO['Day']=Data_CO.index.day
Data_CO['Hour']=Data_CO.index.hour
CO_Data=Data_CO
CO_Data=CO_Data[(CO_Data[CO_Data.columns] >= 0).all(axis=1)]
CO_Data=CO_Data.dropna()
CO_Data=CO_Data.resample('h').mean()
CO_Data=CO_Data.dropna()
CO_Data.tail()

,Lab1,Temp,RH,Ref,Net Signal,Month,Day_of_week,Day,Hour
Date,,,,,,,,,
2020-04-30 19:00:00,242.060716,18.870796,71.072939,188.915151,91.471325,4.0,3.0,30.0,19.0
2020-04-30 20:00:00,218.655079,18.056864,75.132153,178.704750,84.176485,4.0,3.0,30.0,20.0
2020-04-30 21:00:00,194.147868,17.090891,81.315038,161.421792,73.858294,4.0,3.0,30.0,21.0
2020-04-30 22:00:00,206.432889,16.714085,82.568155,197.744043,83.279611,4.0,3.0,30.0,22.0
2020-04-30 23:00:00,173.577429,16.365121,83.662401,162.157636,68.669099,4.0,3.0,30.0,23.0

In [3]:
import pandas as pd
import scipy.io
import numpy as np
data = pd.read_csv('O3.txt', header = None,low_memory=False)
data.columns=['AE','WE','Temp','RH','Time']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_O3=data
Data_O3['Ref']=Ref_O3
WE=Data_O3['WE'].to_list()
AE=Data_O3['AE'].to_list()
signal=np.array(WE)-np.array(AE)
Data_O3['Net Signal']=signal
Data_O3['Month']=Data_O3.index.month
Data_O3['Day_of_week']=Data_O3.index.dayofweek
Data_O3['Day']=Data_O3.index.day
Data_O3['Hour']=Data_O3.index.hour
O3_Data=Data_O3
O3_Data=O3_Data[(O3_Data[O3_Data.columns] >= 0).all(axis=1)]
O3_Data=O3_Data.dropna()
data = pd.read_csv('Conc_O3.txt', header = None,low_memory=False)
data.columns=['Lab1','Temp','RH','Time','Ref']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_O3=data
signal=np.array(WE)-np.array(AE)
Data_O3['Net Signal']=signal
Data_O3['Month']=Data_O3.index.month
Data_O3['Day_of_week']=Data_O3.index.dayofweek
Data_O3['Day']=Data_O3.index.day
Data_O3['Hour']=Data_O3.index.hour
O3_Data=Data_O3
O3_Data=O3_Data[(O3_Data[O3_Data.columns] >= 0).all(axis=1)]
O3_Data=O3_Data.dropna() 
O3_Data=O3_Data.resample('h').mean()
O3_Data=O3_Data.dropna()
O3_Data.head()

ref_O3=Data_O3['Ref'].to_list()
len(ref_O3)

60913

In [4]:
import pandas as pd
import scipy.io
import numpy as np
data = pd.read_csv('NO2.txt', header = None,low_memory=False)
data.columns=['WE','AE','Temp','RH','Time']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_NO2=data
Data_NO2['Ref']=Ref_NO2
WE=Data_NO2['WE'].to_list()
AE=Data_NO2['AE'].to_list()
signal=np.array(WE)-np.array(AE)
Data_NO2['Net Signal']=signal
Data_NO2['Month']=Data_NO2.index.month
Data_NO2['Day_of_week']=Data_NO2.index.dayofweek
Data_NO2['Day']=Data_NO2.index.day
Data_NO2['Hour']=Data_NO2.index.hour
NO2_Data=Data_NO2
NO2_Data=NO2_Data[(NO2_Data[NO2_Data.columns] >= 0).all(axis=1)]
NO2_Data=NO2_Data.dropna()
data = pd.read_csv('Conc_NO2.txt', header = None,low_memory=False)
data.columns=['Lab1','Temp','RH','Time','Ref']
Time=data['Time'].to_list()
time=[]
subscript = str.maketrans("0123456789", "₀₁₂₃₄₅₆₇₈₉") 
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_NO2=data
signal=np.array(WE)-np.array(AE)
Data_NO2['Net Signal']=signal
Data_NO2['Month']=Data_NO2.index.month
Data_NO2['Day_of_week']=Data_NO2.index.dayofweek
Data_NO2['Day']=Data_NO2.index.day
Data_NO2['Hour']=Data_NO2.index.hour
Data_NO2['Ref_O3']=ref_O3
NO2_Data=Data_NO2
NO2_Data=NO2_Data[(NO2_Data[NO2_Data.columns] >= 0).all(axis=1)]
NO2_Data=NO2_Data.dropna()
NO2_Data=NO2_Data.resample('h').mean()
NO2_Data=NO2_Data.dropna()

In [5]:
import pandas as pd
import scipy.io
import numpy as np
data = pd.read_csv('O3.txt', header = None,low_memory=False)
data.columns=['AE','WE','Temp','RH','Time']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_O3=data
Data_O3['Ref']=Ref_O3
WE=Data_O3['WE'].to_list()
AE=Data_O3['AE'].to_list()
signal=np.array(WE)-np.array(AE)
Data_O3['Net Signal']=signal
Data_O3['Month']=Data_O3.index.month
Data_O3['Day_of_week']=Data_O3.index.dayofweek
Data_O3['Day']=Data_O3.index.day
Data_O3['Hour']=Data_O3.index.hour
O3_Data=Data_O3
O3_Data=O3_Data[(O3_Data[O3_Data.columns] >= 0).all(axis=1)]
O3_Data=O3_Data.dropna()
data = pd.read_csv('Conc_O3.txt', header = None,low_memory=False)
data.columns=['Lab1','Temp','RH','Time','Ref']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_O3=data
signal=np.array(WE)-np.array(AE)
Data_O3['Net Signal']=signal
Data_O3['Month']=Data_O3.index.month
Data_O3['Day_of_week']=Data_O3.index.dayofweek
Data_O3['Day']=Data_O3.index.day
Data_O3['Hour']=Data_O3.index.hour
ref_NO2=Data_NO2['Ref'].to_list()
Data_O3['Ref_NO2']=ref_NO2
O3_Data=Data_O3
O3_Data=O3_Data[(O3_Data[O3_Data.columns] >= 0).all(axis=1)]
O3_Data=O3_Data.dropna()
O3_Data=O3_Data.resample('h').mean()
O3_Data=O3_Data.dropna()
O3_Data.head()

,Lab1,Temp,RH,Ref,Net Signal,Month,Day_of_week,Day,Hour,Ref_NO2
Date,,,,,,,,,,
2019-10-02 11:00:00,621.625704,26.378438,58.063437,46.094860,3.605625,10.0,2.0,2.0,11.0,15.230400
2019-10-02 12:00:00,725.154408,25.795055,48.256857,57.532808,13.865109,10.0,2.0,2.0,12.0,5.384051
2019-10-07 10:00:00,108.196313,32.344264,37.260757,47.259008,11.447809,10.0,0.0,7.0,10.0,4.255772
2019-10-07 11:00:00,135.822676,34.926112,35.013036,42.114260,10.075221,10.0,0.0,7.0,11.0,16.268034
2019-10-07 12:00:00,203.757758,36.201221,31.829282,45.701366,7.624153,10.0,0.0,7.0,12.0,12.770444

# CO DATA

In [6]:
from sktime.performance_metrics.forecasting import sMAPE, smape_loss
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error as mae
import sklearn.metrics as sm
import matplotlib.pyplot as plt
from flaml import AutoML
from sklearn.datasets import fetch_california_housing
#'Ref_NO2','Ref_SO2','Ref_O3',
#,'Month','Day_of_week','Day','Hour'
X=CO_Data[['Net Signal','Lab1','Temp','RH','Month','Day_of_week','Hour']]
y=CO_Data['Ref']
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size = 0.2,shuffle=True)
#train_test_split(X, y, test_size = 0.2)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/xgboost/compat.py:93: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index

In [7]:
# Initialize an AutoML instance
automl = AutoML()
# Specify automl goal and constraint
automl_settings = {
    "time_budget": 1440,  # in seconds
    "metric": 'rmse',
    "task": 'regression',
    "log_file_name": "california.log",
}

Pred=[]
rmse=[]
model=[]
RS=[]
R=[]
for i in range(10):
    X_Train, X_Test, y_Train, y_Test =train_test_split(X_train,y_train,test_size = 0.2,shuffle=True)
    # Train with labeled input data
    automl.fit(X_train=X_Train.drop(['Lab1'], axis=1), y_train=y_Train,**automl_settings,estimator_list=["rf"])
    pred=automl.predict(X_test.drop(['Lab1'], axis=1))
    R2=round(sm.r2_score(y_test, pred), 2)
    r=round(np.corrcoef(y_test, pred)[0, 1],2)
    RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),5)
    #print(r,R2,RMSE)
    # Predict
    #print(automl.predict(X_test))
    # Print the best model
    #print(automl.model.estimator)
    Pred.append(pred)
    rmse.append(RMSE)
    model.append(automl.model.estimator)
    RS.append(R2)
    R.append(r)

print(np.round(np.mean(R),2),np.round(np.mean(RS),2),np.round(np.mean(rmse),2))

[flaml.automl: 12-15 00:33:49] {2599} INFO - task = regression
[flaml.automl: 12-15 00:33:49] {2601} INFO - Data split method: uniform
[flaml.automl: 12-15 00:33:49] {2604} INFO - Evaluation method: cv
[flaml.automl: 12-15 00:33:49] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 12-15 00:33:49] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 12-15 00:33:49] {3166} INFO - iteration 0, current learner rf
[flaml.automl: 12-15 00:33:50] {3296} INFO - Estimated sufficient time budget=11522s. Estimated necessary time budget=12s.
[flaml.automl: 12-15 00:33:50] {3343} INFO -  at 1.5s,	estimator rf's best error=165.4297,	best estimator rf's best error=165.4297
[flaml.automl: 12-15 00:33:50] {3166} INFO - iteration 1, current learner rf
[flaml.automl: 12-15 00:33:51] {3343} INFO -  at 2.6s,	estimator rf's best error=150.6053,	best estimator rf's best error=150.6053
[flaml.automl: 12-15 00:33:51] {3166} INFO - iteration 2, current learner rf
[flaml.automl: 12-15 00:33:52] {3343} INFO -  at 3.6s,	estimator rf's best error=150.6053,	best estimator rf's best error=150.6053
[flaml.automl: 12-15 00:33:52] {3166} INFO - iteration 3, current learner rf
[flaml.automl: 12-15 00:33:54] {3343} INFO -  at 4.9s,	estimator rf's best error=141.9314,	best estimator rf's best error=141.9314
[flaml.automl: 12-15 00:33:54] {3166} INFO - iteration 4, current learner rf
[flaml.automl: 12-15 00:33:55] {3343} INFO -  at 6.6s,	estimator rf's best error=139.5006,	best estimator rf's best error=139.5006
[flaml.automl: 12-15 00:33:55] {3166} INFO - iteration 5, current learner rf
[flaml.automl: 12-15 00:33:57] {3343} INFO -  at 7.8s,	estimator rf's best error=139.5006,	best estimator rf's best error=139.5006
[flaml.automl: 12-15 00:33:57] {3166} INFO - iteration 6, current learner rf
[flaml.automl: 12-15 00:33:58] {3343} INFO -  at 8.9s,	estimator rf's best error=136.0077,	best estimator rf's best error=136.0077
[flaml.automl: 12-15 00:33:58] {3166} INFO - iteration 7, current learner rf
[flaml.automl: 12-15 00:33:59] {3343} INFO -  at 10.6s,	estimator rf's best error=136.0077,	best estimator rf's best error=136.0077
[flaml.automl: 12-15 00:33:59] {3166} INFO - iteration 8, current learner rf
[flaml.automl: 12-15 00:34:01] {3343} INFO -  at 11.9s,	estimator rf's best error=129.7791,	best estimator rf's best error=129.7791
[flaml.automl: 12-15 00:34:01] {3166} INFO - iteration 9, current learner rf
[flaml.automl: 12-15 00:34:02] {3343} INFO -  at 13.2s,	estimator rf's best error=129.7791,	best estimator rf's best error=129.7791
[flaml.automl: 12-15 00:34:02] {3166} INFO - iteration 10, current learner rf
[flaml.automl: 12-15 00:34:03] {3343} INFO -  at 14.3s,	estimator rf's best error=129.7791,	best estimator rf's best error=129.7791
[flaml.automl: 12-15 00:34:03] {3166} INFO - iteration 11, current learner rf
[flaml.automl: 12-15 00:34:06] {3343} INFO -  at 17.1s,	estimator rf's best error=127.0288,	best estimator rf's best error=127.0288
[flaml.automl: 12-15 00:34:06] {3166} INFO - iteration 12, current learner rf
[flaml.automl: 12-15 00:34:07] {3343} INFO -  at 18.5s,	estimator rf's best error=127.0288,	best estimator rf's best error=127.0288
[flaml.automl: 12-15 00:34:07] {3166} INFO - iteration 13, current learner rf
[flaml.automl: 12-15 00:34:12] {3343} INFO -  at 23.0s,	estimator rf's best error=125.0984,	best estimator rf's best error=125.0984
[flaml.automl: 12-15 00:34:12] {3166} INFO - iteration 14, current learner rf
[flaml.automl: 12-15 00:34:15] {3343} INFO -  at 26.6s,	estimator rf's best error=125.0984,	best estimator rf's best error=125.0984
[flaml.automl: 12-15 00:34:15] {3166} INFO - iteration 15, current learner rf
[flaml.automl: 12-15 00:34:27] {3343} INFO -  at 38.3s,	estimator rf's best error=122.5199,	best estimator rf's best error=122.5199
[flaml.automl: 12-15 00:34:27] {3166} INFO - iteration 16, current learner rf
[flaml.automl: 12-15 00:34:33] {3343} INFO -  at 43.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:34:33] {3166} INFO - iteration 17, current learner rf
[flaml.automl: 12-15 00:34:40] {3343} INFO -  at 51.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:34:40] {3166} INFO - iteration 18, current learner rf
[flaml.automl: 12-15 00:34:42] {3343} INFO -  at 53.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:34:42] {3166} INFO - iteration 19, current learner rf
[flaml.automl: 12-15 00:34:50] {3343} INFO -  at 61.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:34:50] {3166} INFO - iteration 20, current learner rf
[flaml.automl: 12-15 00:34:52] {3343} INFO -  at 62.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:34:52] {3166} INFO - iteration 21, current learner rf
[flaml.automl: 12-15 00:34:54] {3343} INFO -  at 64.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:34:54] {3166} INFO - iteration 22, current learner rf
[flaml.automl: 12-15 00:35:02] {3343} INFO -  at 73.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:02] {3166} INFO - iteration 23, current learner rf
[flaml.automl: 12-15 00:35:06] {3343} INFO -  at 76.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:06] {3166} INFO - iteration 24, current learner rf
[flaml.automl: 12-15 00:35:08] {3343} INFO -  at 78.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:08] {3166} INFO - iteration 25, current learner rf
[flaml.automl: 12-15 00:35:12] {3343} INFO -  at 82.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:12] {3166} INFO - iteration 26, current learner rf
[flaml.automl: 12-15 00:35:13] {3343} INFO -  at 84.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:13] {3166} INFO - iteration 27, current learner rf
[flaml.automl: 12-15 00:35:15] {3343} INFO -  at 86.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:15] {3166} INFO - iteration 28, current learner rf
[flaml.automl: 12-15 00:35:17] {3343} INFO -  at 88.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:17] {3166} INFO - iteration 29, current learner rf
[flaml.automl: 12-15 00:35:19] {3343} INFO -  at 90.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:19] {3166} INFO - iteration 30, current learner rf
[flaml.automl: 12-15 00:35:23] {3343} INFO -  at 93.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:23] {3166} INFO - iteration 31, current learner rf
[flaml.automl: 12-15 00:35:26] {3343} INFO -  at 96.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:26] {3166} INFO - iteration 32, current learner rf
[flaml.automl: 12-15 00:35:28] {3343} INFO -  at 98.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:28] {3166} INFO - iteration 33, current learner rf
[flaml.automl: 12-15 00:35:32] {3343} INFO -  at 103.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:32] {3166} INFO - iteration 34, current learner rf
[flaml.automl: 12-15 00:35:34] {3343} INFO -  at 104.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:34] {3166} INFO - iteration 35, current learner rf
[flaml.automl: 12-15 00:35:35] {3343} INFO -  at 106.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:35] {3166} INFO - iteration 36, current learner rf
[flaml.automl: 12-15 00:35:40] {3343} INFO -  at 111.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974

[flaml.automl: 12-15 00:35:40] {3166} INFO - iteration 37, current learner rf
[flaml.automl: 12-15 00:35:45] {3343} INFO -  at 115.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:45] {3166} INFO - iteration 38, current learner rf
[flaml.automl: 12-15 00:35:46] {3343} INFO -  at 117.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:46] {3166} INFO - iteration 39, current learner rf
[flaml.automl: 12-15 00:35:50] {3343} INFO -  at 121.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:50] {3166} INFO - iteration 40, current learner rf
[flaml.automl: 12-15 00:35:53] {3343} INFO -  at 123.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:53] {3166} INFO - iteration 41, current learner rf
[flaml.automl: 12-15 00:35:55] {3343} INFO -  at 126.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:55] {3166} INFO - iteration 42, current learner rf
[flaml.automl: 12-15 00:35:59] {3343} INFO -  at 130.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:35:59] {3166} INFO - iteration 43, current learner rf
[flaml.automl: 12-15 00:36:02] {3343} INFO -  at 133.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:36:02] {3166} INFO - iteration 44, current learner rf
[flaml.automl: 12-15 00:36:07] {3343} INFO -  at 137.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:36:07] {3166} INFO - iteration 45, current learner rf
[flaml.automl: 12-15 00:36:13] {3343} INFO -  at 144.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:36:13] {3166} INFO - iteration 46, current learner rf
[flaml.automl: 12-15 00:36:16] {3343} INFO -  at 147.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:36:16] {3166} INFO - iteration 47, current learner rf
[flaml.automl: 12-15 00:36:19] {3343} INFO -  at 150.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:36:19] {3166} INFO - iteration 48, current learner rf
[flaml.automl: 12-15 00:36:26] {3343} INFO -  at 156.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:36:26] {3166} INFO - iteration 49, current learner rf
[flaml.automl: 12-15 00:36:32] {3343} INFO -  at 163.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:36:32] {3166} INFO - iteration 50, current learner rf
[flaml.automl: 12-15 00:36:34] {3343} INFO -  at 165.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:36:34] {3166} INFO - iteration 51, current learner rf
[flaml.automl: 12-15 00:36:40] {3343} INFO -  at 171.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:36:40] {3166} INFO - iteration 52, current learner rf
[flaml.automl: 12-15 00:36:43] {3343} INFO -  at 174.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:36:43] {3166} INFO - iteration 53, current learner rf
[flaml.automl: 12-15 00:36:46] {3343} INFO -  at 176.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:36:46] {3166} INFO - iteration 54, current learner rf
[flaml.automl: 12-15 00:36:51] {3343} INFO -  at 181.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:36:51] {3166} INFO - iteration 55, current learner rf
[flaml.automl: 12-15 00:36:57] {3343} INFO -  at 187.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:36:57] {3166} INFO - iteration 56, current learner rf
[flaml.automl: 12-15 00:36:59] {3343} INFO -  at 190.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:36:59] {3166} INFO - iteration 57, current learner rf
[flaml.automl: 12-15 00:37:05] {3343} INFO -  at 196.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:37:05] {3166} INFO - iteration 58, current learner rf
[flaml.automl: 12-15 00:37:08] {3343} INFO -  at 198.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:37:08] {3166} INFO - iteration 59, current learner rf
[flaml.automl: 12-15 00:37:11] {3343} INFO -  at 202.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:37:11] {3166} INFO - iteration 60, current learner rf
[flaml.automl: 12-15 00:37:18] {3343} INFO -  at 208.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:37:18] {3166} INFO - iteration 61, current learner rf
[flaml.automl: 12-15 00:37:24] {3343} INFO -  at 215.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:37:24] {3166} INFO - iteration 62, current learner rf
[flaml.automl: 12-15 00:37:26] {3343} INFO -  at 217.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:37:26] {3166} INFO - iteration 63, current learner rf
[flaml.automl: 12-15 00:37:29] {3343} INFO -  at 220.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:37:29] {3166} INFO - iteration 64, current learner rf
[flaml.automl: 12-15 00:37:33] {3343} INFO -  at 224.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:37:33] {3166} INFO - iteration 65, current learner rf
[flaml.automl: 12-15 00:37:36] {3343} INFO -  at 227.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:37:36] {3166} INFO - iteration 66, current learner rf
[flaml.automl: 12-15 00:37:42] {3343} INFO -  at 232.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:37:42] {3166} INFO - iteration 67, current learner rf
[flaml.automl: 12-15 00:37:45] {3343} INFO -  at 236.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:37:45] {3166} INFO - iteration 68, current learner rf
[flaml.automl: 12-15 00:37:50] {3343} INFO -  at 241.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:37:50] {3166} INFO - iteration 69, current learner rf
[flaml.automl: 12-15 00:37:55] {3343} INFO -  at 245.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:37:55] {3166} INFO - iteration 70, current learner rf
[flaml.automl: 12-15 00:37:58] {3343} INFO -  at 248.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:37:58] {3166} INFO - iteration 71, current learner rf
[flaml.automl: 12-15 00:38:01] {3343} INFO -  at 251.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:01] {3166} INFO - iteration 72, current learner rf
[flaml.automl: 12-15 00:38:06] {3343} INFO -  at 257.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:06] {3166} INFO - iteration 73, current learner rf
[flaml.automl: 12-15 00:38:10] {3343} INFO -  at 261.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:10] {3166} INFO - iteration 74, current learner rf
[flaml.automl: 12-15 00:38:14] {3343} INFO -  at 265.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:14] {3166} INFO - iteration 75, current learner rf
[flaml.automl: 12-15 00:38:17] {3343} INFO -  at 267.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974

[flaml.automl: 12-15 00:38:17] {3166} INFO - iteration 76, current learner rf
[flaml.automl: 12-15 00:38:21] {3343} INFO -  at 272.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:21] {3166} INFO - iteration 77, current learner rf
[flaml.automl: 12-15 00:38:25] {3343} INFO -  at 276.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:25] {3166} INFO - iteration 78, current learner rf
[flaml.automl: 12-15 00:38:29] {3343} INFO -  at 280.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:29] {3166} INFO - iteration 79, current learner rf
[flaml.automl: 12-15 00:38:32] {3343} INFO -  at 283.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:32] {3166} INFO - iteration 80, current learner rf
[flaml.automl: 12-15 00:38:37] {3343} INFO -  at 287.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:37] {3166} INFO - iteration 81, current learner rf
[flaml.automl: 12-15 00:38:40] {3343} INFO -  at 291.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:40] {3166} INFO - iteration 82, current learner rf
[flaml.automl: 12-15 00:38:44] {3343} INFO -  at 294.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:44] {3166} INFO - iteration 83, current learner rf
[flaml.automl: 12-15 00:38:46] {3343} INFO -  at 297.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:46] {3166} INFO - iteration 84, current learner rf
[flaml.automl: 12-15 00:38:51] {3343} INFO -  at 302.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:51] {3166} INFO - iteration 85, current learner rf
[flaml.automl: 12-15 00:38:56] {3343} INFO -  at 307.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:56] {3166} INFO - iteration 86, current learner rf
[flaml.automl: 12-15 00:38:59] {3343} INFO -  at 310.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:38:59] {3166} INFO - iteration 87, current learner rf
[flaml.automl: 12-15 00:39:01] {3343} INFO -  at 312.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:01] {3166} INFO - iteration 88, current learner rf
[flaml.automl: 12-15 00:39:06] {3343} INFO -  at 317.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:06] {3166} INFO - iteration 89, current learner rf
[flaml.automl: 12-15 00:39:10] {3343} INFO -  at 321.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:10] {3166} INFO - iteration 90, current learner rf
[flaml.automl: 12-15 00:39:13] {3343} INFO -  at 324.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:13] {3166} INFO - iteration 91, current learner rf
[flaml.automl: 12-15 00:39:16] {3343} INFO -  at 327.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:16] {3166} INFO - iteration 92, current learner rf
[flaml.automl: 12-15 00:39:19] {3343} INFO -  at 330.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:19] {3166} INFO - iteration 93, current learner rf
[flaml.automl: 12-15 00:39:23] {3343} INFO -  at 334.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:23] {3166} INFO - iteration 94, current learner rf
[flaml.automl: 12-15 00:39:26] {3343} INFO -  at 337.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:26] {3166} INFO - iteration 95, current learner rf
[flaml.automl: 12-15 00:39:31] {3343} INFO -  at 342.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:31] {3166} INFO - iteration 96, current learner rf
[flaml.automl: 12-15 00:39:34] {3343} INFO -  at 344.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:34] {3166} INFO - iteration 97, current learner rf
[flaml.automl: 12-15 00:39:36] {3343} INFO -  at 347.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:36] {3166} INFO - iteration 98, current learner rf
[flaml.automl: 12-15 00:39:41] {3343} INFO -  at 352.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:41] {3166} INFO - iteration 99, current learner rf
[flaml.automl: 12-15 00:39:44] {3343} INFO -  at 355.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:44] {3166} INFO - iteration 100, current learner rf
[flaml.automl: 12-15 00:39:48] {3343} INFO -  at 359.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:48] {3166} INFO - iteration 101, current learner rf
[flaml.automl: 12-15 00:39:53] {3343} INFO -  at 364.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:54] {3166} INFO - iteration 102, current learner rf
[flaml.automl: 12-15 00:39:56] {3343} INFO -  at 366.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:39:56] {3166} INFO - iteration 103, current learner rf
[flaml.automl: 12-15 00:40:01] {3343} INFO -  at 372.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:01] {3166} INFO - iteration 104, current learner rf
[flaml.automl: 12-15 00:40:03] {3343} INFO -  at 374.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:03] {3166} INFO - iteration 105, current learner rf
[flaml.automl: 12-15 00:40:06] {3343} INFO -  at 377.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:06] {3166} INFO - iteration 106, current learner rf
[flaml.automl: 12-15 00:40:11] {3343} INFO -  at 382.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:11] {3166} INFO - iteration 107, current learner rf
[flaml.automl: 12-15 00:40:14] {3343} INFO -  at 385.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:14] {3166} INFO - iteration 108, current learner rf
[flaml.automl: 12-15 00:40:19] {3343} INFO -  at 389.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:19] {3166} INFO - iteration 109, current learner rf
[flaml.automl: 12-15 00:40:21] {3343} INFO -  at 392.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:21] {3166} INFO - iteration 110, current learner rf
[flaml.automl: 12-15 00:40:26] {3343} INFO -  at 397.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:26] {3166} INFO - iteration 111, current learner rf
[flaml.automl: 12-15 00:40:30] {3343} INFO -  at 400.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:30] {3166} INFO - iteration 112, current learner rf
[flaml.automl: 12-15 00:40:33] {3343} INFO -  at 403.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:33] {3166} INFO - iteration 113, current learner rf
[flaml.automl: 12-15 00:40:37] {3343} INFO -  at 407.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:37] {3166} INFO - iteration 114, current learner rf
[flaml.automl: 12-15 00:40:40] {3343} INFO -  at 411.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974

[flaml.automl: 12-15 00:40:40] {3166} INFO - iteration 115, current learner rf
[flaml.automl: 12-15 00:40:42] {3343} INFO -  at 413.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:42] {3166} INFO - iteration 116, current learner rf
[flaml.automl: 12-15 00:40:48] {3343} INFO -  at 419.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:48] {3166} INFO - iteration 117, current learner rf
[flaml.automl: 12-15 00:40:50] {3343} INFO -  at 421.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:50] {3166} INFO - iteration 118, current learner rf
[flaml.automl: 12-15 00:40:56] {3343} INFO -  at 427.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:56] {3166} INFO - iteration 119, current learner rf
[flaml.automl: 12-15 00:40:59] {3343} INFO -  at 429.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:40:59] {3166} INFO - iteration 120, current learner rf
[flaml.automl: 12-15 00:41:03] {3343} INFO -  at 434.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:03] {3166} INFO - iteration 121, current learner rf
[flaml.automl: 12-15 00:41:07] {3343} INFO -  at 438.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:07] {3166} INFO - iteration 122, current learner rf
[flaml.automl: 12-15 00:41:10] {3343} INFO -  at 441.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:10] {3166} INFO - iteration 123, current learner rf
[flaml.automl: 12-15 00:41:15] {3343} INFO -  at 446.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:15] {3166} INFO - iteration 124, current learner rf
[flaml.automl: 12-15 00:41:18] {3343} INFO -  at 448.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:18] {3166} INFO - iteration 125, current learner rf
[flaml.automl: 12-15 00:41:22] {3343} INFO -  at 453.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:22] {3166} INFO - iteration 126, current learner rf
[flaml.automl: 12-15 00:41:26] {3343} INFO -  at 456.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:26] {3166} INFO - iteration 127, current learner rf
[flaml.automl: 12-15 00:41:28] {3343} INFO -  at 458.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:28] {3166} INFO - iteration 128, current learner rf
[flaml.automl: 12-15 00:41:33] {3343} INFO -  at 464.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:33] {3166} INFO - iteration 129, current learner rf
[flaml.automl: 12-15 00:41:38] {3343} INFO -  at 469.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:38] {3166} INFO - iteration 130, current learner rf
[flaml.automl: 12-15 00:41:41] {3343} INFO -  at 471.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:41] {3166} INFO - iteration 131, current learner rf
[flaml.automl: 12-15 00:41:46] {3343} INFO -  at 476.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:46] {3166} INFO - iteration 132, current learner rf
[flaml.automl: 12-15 00:41:48] {3343} INFO -  at 479.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:48] {3166} INFO - iteration 133, current learner rf
[flaml.automl: 12-15 00:41:51] {3343} INFO -  at 482.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:51] {3166} INFO - iteration 134, current learner rf
[flaml.automl: 12-15 00:41:55] {3343} INFO -  at 486.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:41:55] {3166} INFO - iteration 135, current learner rf
[flaml.automl: 12-15 00:42:01] {3343} INFO -  at 491.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:01] {3166} INFO - iteration 136, current learner rf
[flaml.automl: 12-15 00:42:03] {3343} INFO -  at 494.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:03] {3166} INFO - iteration 137, current learner rf
[flaml.automl: 12-15 00:42:07] {3343} INFO -  at 497.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:07] {3166} INFO - iteration 138, current learner rf
[flaml.automl: 12-15 00:42:10] {3343} INFO -  at 501.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:10] {3166} INFO - iteration 139, current learner rf
[flaml.automl: 12-15 00:42:14] {3343} INFO -  at 504.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:14] {3166} INFO - iteration 140, current learner rf
[flaml.automl: 12-15 00:42:17] {3343} INFO -  at 508.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:17] {3166} INFO - iteration 141, current learner rf
[flaml.automl: 12-15 00:42:22] {3343} INFO -  at 513.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:22] {3166} INFO - iteration 142, current learner rf
[flaml.automl: 12-15 00:42:25] {3343} INFO -  at 515.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:25] {3166} INFO - iteration 143, current learner rf
[flaml.automl: 12-15 00:42:29] {3343} INFO -  at 520.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:29] {3166} INFO - iteration 144, current learner rf
[flaml.automl: 12-15 00:42:31] {3343} INFO -  at 522.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:31] {3166} INFO - iteration 145, current learner rf
[flaml.automl: 12-15 00:42:35] {3343} INFO -  at 526.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:35] {3166} INFO - iteration 146, current learner rf
[flaml.automl: 12-15 00:42:38] {3343} INFO -  at 529.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:38] {3166} INFO - iteration 147, current learner rf
[flaml.automl: 12-15 00:42:41] {3343} INFO -  at 532.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:41] {3166} INFO - iteration 148, current learner rf
[flaml.automl: 12-15 00:42:45] {3343} INFO -  at 535.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:45] {3166} INFO - iteration 149, current learner rf
[flaml.automl: 12-15 00:42:49] {3343} INFO -  at 539.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:49] {3166} INFO - iteration 150, current learner rf
[flaml.automl: 12-15 00:42:51] {3343} INFO -  at 542.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:51] {3166} INFO - iteration 151, current learner rf
[flaml.automl: 12-15 00:42:55] {3343} INFO -  at 545.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:55] {3166} INFO - iteration 152, current learner rf
[flaml.automl: 12-15 00:42:58] {3343} INFO -  at 548.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:42:58] {3166} INFO - iteration 153, current learner rf
[flaml.automl: 12-15 00:43:02] {3343} INFO -  at 553.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974

[flaml.automl: 12-15 00:43:02] {3166} INFO - iteration 154, current learner rf
[flaml.automl: 12-15 00:43:06] {3343} INFO -  at 557.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:06] {3166} INFO - iteration 155, current learner rf
[flaml.automl: 12-15 00:43:09] {3343} INFO -  at 560.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:09] {3166} INFO - iteration 156, current learner rf
[flaml.automl: 12-15 00:43:12] {3343} INFO -  at 562.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:12] {3166} INFO - iteration 157, current learner rf
[flaml.automl: 12-15 00:43:15] {3343} INFO -  at 565.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:15] {3166} INFO - iteration 158, current learner rf
[flaml.automl: 12-15 00:43:18] {3343} INFO -  at 569.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:18] {3166} INFO - iteration 159, current learner rf
[flaml.automl: 12-15 00:43:24] {3343} INFO -  at 574.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:24] {3166} INFO - iteration 160, current learner rf
[flaml.automl: 12-15 00:43:27] {3343} INFO -  at 577.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:27] {3166} INFO - iteration 161, current learner rf
[flaml.automl: 12-15 00:43:30] {3343} INFO -  at 581.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:30] {3166} INFO - iteration 162, current learner rf
[flaml.automl: 12-15 00:43:33] {3343} INFO -  at 584.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:33] {3166} INFO - iteration 163, current learner rf
[flaml.automl: 12-15 00:43:38] {3343} INFO -  at 588.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:38] {3166} INFO - iteration 164, current learner rf
[flaml.automl: 12-15 00:43:41] {3343} INFO -  at 592.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:41] {3166} INFO - iteration 165, current learner rf
[flaml.automl: 12-15 00:43:45] {3343} INFO -  at 595.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:45] {3166} INFO - iteration 166, current learner rf
[flaml.automl: 12-15 00:43:47] {3343} INFO -  at 598.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:47] {3166} INFO - iteration 167, current learner rf
[flaml.automl: 12-15 00:43:51] {3343} INFO -  at 601.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:51] {3166} INFO - iteration 168, current learner rf
[flaml.automl: 12-15 00:43:54] {3343} INFO -  at 605.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:54] {3166} INFO - iteration 169, current learner rf
[flaml.automl: 12-15 00:43:57] {3343} INFO -  at 607.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:43:57] {3166} INFO - iteration 170, current learner rf
[flaml.automl: 12-15 00:44:01] {3343} INFO -  at 612.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:01] {3166} INFO - iteration 171, current learner rf
[flaml.automl: 12-15 00:44:03] {3343} INFO -  at 614.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:03] {3166} INFO - iteration 172, current learner rf
[flaml.automl: 12-15 00:44:08] {3343} INFO -  at 619.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:08] {3166} INFO - iteration 173, current learner rf
[flaml.automl: 12-15 00:44:11] {3343} INFO -  at 621.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:11] {3166} INFO - iteration 174, current learner rf
[flaml.automl: 12-15 00:44:14] {3343} INFO -  at 625.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:14] {3166} INFO - iteration 175, current learner rf
[flaml.automl: 12-15 00:44:17] {3343} INFO -  at 628.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:17] {3166} INFO - iteration 176, current learner rf
[flaml.automl: 12-15 00:44:21] {3343} INFO -  at 632.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:21] {3166} INFO - iteration 177, current learner rf
[flaml.automl: 12-15 00:44:24] {3343} INFO -  at 634.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:24] {3166} INFO - iteration 178, current learner rf
[flaml.automl: 12-15 00:44:28] {3343} INFO -  at 639.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:28] {3166} INFO - iteration 179, current learner rf
[flaml.automl: 12-15 00:44:32] {3343} INFO -  at 643.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:32] {3166} INFO - iteration 180, current learner rf
[flaml.automl: 12-15 00:44:35] {3343} INFO -  at 645.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:35] {3166} INFO - iteration 181, current learner rf
[flaml.automl: 12-15 00:44:38] {3343} INFO -  at 648.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:38] {3166} INFO - iteration 182, current learner rf
[flaml.automl: 12-15 00:44:41] {3343} INFO -  at 652.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:41] {3166} INFO - iteration 183, current learner rf
[flaml.automl: 12-15 00:44:45] {3343} INFO -  at 656.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:45] {3166} INFO - iteration 184, current learner rf
[flaml.automl: 12-15 00:44:48] {3343} INFO -  at 659.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:48] {3166} INFO - iteration 185, current learner rf
[flaml.automl: 12-15 00:44:52] {3343} INFO -  at 662.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:52] {3166} INFO - iteration 186, current learner rf
[flaml.automl: 12-15 00:44:55] {3343} INFO -  at 666.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:55] {3166} INFO - iteration 187, current learner rf
[flaml.automl: 12-15 00:44:58] {3343} INFO -  at 669.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:44:58] {3166} INFO - iteration 188, current learner rf
[flaml.automl: 12-15 00:45:01] {3343} INFO -  at 672.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:45:01] {3166} INFO - iteration 189, current learner rf
[flaml.automl: 12-15 00:45:04] {3343} INFO -  at 675.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:45:04] {3166} INFO - iteration 190, current learner rf
[flaml.automl: 12-15 00:45:08] {3343} INFO -  at 679.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:45:08] {3166} INFO - iteration 191, current learner rf
[flaml.automl: 12-15 00:45:13] {3343} INFO -  at 684.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:45:13] {3166} INFO - iteration 192, current learner rf
[flaml.automl: 12-15 00:45:23] {3343} INFO -  at 693.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974

[flaml.automl: 12-15 00:45:23] {3166} INFO - iteration 193, current learner rf
[flaml.automl: 12-15 00:45:30] {3343} INFO -  at 701.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:45:30] {3166} INFO - iteration 194, current learner rf
[flaml.automl: 12-15 00:45:37] {3343} INFO -  at 707.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:45:37] {3166} INFO - iteration 195, current learner rf
[flaml.automl: 12-15 00:45:44] {3343} INFO -  at 715.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:45:44] {3166} INFO - iteration 196, current learner rf
[flaml.automl: 12-15 00:45:51] {3343} INFO -  at 721.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:45:51] {3166} INFO - iteration 197, current learner rf
[flaml.automl: 12-15 00:45:57] {3343} INFO -  at 728.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:45:57] {3166} INFO - iteration 198, current learner rf
[flaml.automl: 12-15 00:46:03] {3343} INFO -  at 734.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:46:03] {3166} INFO - iteration 199, current learner rf
[flaml.automl: 12-15 00:46:10] {3343} INFO -  at 740.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:46:10] {3166} INFO - iteration 200, current learner rf
[flaml.automl: 12-15 00:46:18] {3343} INFO -  at 749.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:46:18] {3166} INFO - iteration 201, current learner rf
[flaml.automl: 12-15 00:46:23] {3343} INFO -  at 753.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:46:23] {3166} INFO - iteration 202, current learner rf
[flaml.automl: 12-15 00:46:31] {3343} INFO -  at 762.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:46:31] {3166} INFO - iteration 203, current learner rf
[flaml.automl: 12-15 00:46:39] {3343} INFO -  at 770.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:46:39] {3166} INFO - iteration 204, current learner rf
[flaml.automl: 12-15 00:46:45] {3343} INFO -  at 775.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:46:45] {3166} INFO - iteration 205, current learner rf
[flaml.automl: 12-15 00:46:51] {3343} INFO -  at 781.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:46:51] {3166} INFO - iteration 206, current learner rf
[flaml.automl: 12-15 00:46:58] {3343} INFO -  at 789.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:46:58] {3166} INFO - iteration 207, current learner rf
[flaml.automl: 12-15 00:47:06] {3343} INFO -  at 797.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:47:06] {3166} INFO - iteration 208, current learner rf
[flaml.automl: 12-15 00:47:12] {3343} INFO -  at 802.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:47:12] {3166} INFO - iteration 209, current learner rf
[flaml.automl: 12-15 00:47:19] {3343} INFO -  at 809.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:47:19] {3166} INFO - iteration 210, current learner rf
[flaml.automl: 12-15 00:47:26] {3343} INFO -  at 816.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:47:26] {3166} INFO - iteration 211, current learner rf
[flaml.automl: 12-15 00:47:33] {3343} INFO -  at 824.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:47:33] {3166} INFO - iteration 212, current learner rf
[flaml.automl: 12-15 00:47:40] {3343} INFO -  at 831.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:47:40] {3166} INFO - iteration 213, current learner rf
[flaml.automl: 12-15 00:47:47] {3343} INFO -  at 838.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:47:47] {3166} INFO - iteration 214, current learner rf
[flaml.automl: 12-15 00:47:53] {3343} INFO -  at 844.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:47:53] {3166} INFO - iteration 215, current learner rf
[flaml.automl: 12-15 00:48:01] {3343} INFO -  at 851.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:48:01] {3166} INFO - iteration 216, current learner rf
[flaml.automl: 12-15 00:48:07] {3343} INFO -  at 858.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:48:07] {3166} INFO - iteration 217, current learner rf
[flaml.automl: 12-15 00:48:14] {3343} INFO -  at 864.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:48:14] {3166} INFO - iteration 218, current learner rf
[flaml.automl: 12-15 00:48:20] {3343} INFO -  at 870.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:48:20] {3166} INFO - iteration 219, current learner rf
[flaml.automl: 12-15 00:48:26] {3343} INFO -  at 877.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:48:26] {3166} INFO - iteration 220, current learner rf
[flaml.automl: 12-15 00:48:33] {3343} INFO -  at 884.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:48:33] {3166} INFO - iteration 221, current learner rf
[flaml.automl: 12-15 00:48:41] {3343} INFO -  at 892.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:48:41] {3166} INFO - iteration 222, current learner rf
[flaml.automl: 12-15 00:48:47] {3343} INFO -  at 898.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:48:47] {3166} INFO - iteration 223, current learner rf
[flaml.automl: 12-15 00:48:52] {3343} INFO -  at 903.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:48:52] {3166} INFO - iteration 224, current learner rf
[flaml.automl: 12-15 00:49:00] {3343} INFO -  at 911.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:49:00] {3166} INFO - iteration 225, current learner rf
[flaml.automl: 12-15 00:49:05] {3343} INFO -  at 916.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:49:05] {3166} INFO - iteration 226, current learner rf
[flaml.automl: 12-15 00:49:14] {3343} INFO -  at 925.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:49:14] {3166} INFO - iteration 227, current learner rf
[flaml.automl: 12-15 00:49:22] {3343} INFO -  at 933.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:49:22] {3166} INFO - iteration 228, current learner rf
[flaml.automl: 12-15 00:49:29] {3343} INFO -  at 939.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:49:29] {3166} INFO - iteration 229, current learner rf
[flaml.automl: 12-15 00:49:36] {3343} INFO -  at 947.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:49:36] {3166} INFO - iteration 230, current learner rf
[flaml.automl: 12-15 00:49:41] {3343} INFO -  at 952.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:49:41] {3166} INFO - iteration 231, current learner rf
[flaml.automl: 12-15 00:49:49] {3343} INFO -  at 960.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974

[flaml.automl: 12-15 00:49:49] {3166} INFO - iteration 232, current learner rf
[flaml.automl: 12-15 00:49:57] {3343} INFO -  at 967.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:49:57] {3166} INFO - iteration 233, current learner rf
[flaml.automl: 12-15 00:50:05] {3343} INFO -  at 975.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:50:05] {3166} INFO - iteration 234, current learner rf
[flaml.automl: 12-15 00:50:10] {3343} INFO -  at 981.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:50:10] {3166} INFO - iteration 235, current learner rf
[flaml.automl: 12-15 00:50:15] {3343} INFO -  at 986.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:50:15] {3166} INFO - iteration 236, current learner rf
[flaml.automl: 12-15 00:50:23] {3343} INFO -  at 994.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:50:23] {3166} INFO - iteration 237, current learner rf
[flaml.automl: 12-15 00:50:28] {3343} INFO -  at 999.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:50:28] {3166} INFO - iteration 238, current learner rf
[flaml.automl: 12-15 00:50:37] {3343} INFO -  at 1008.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:50:37] {3166} INFO - iteration 239, current learner rf
[flaml.automl: 12-15 00:50:43] {3343} INFO -  at 1013.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:50:43] {3166} INFO - iteration 240, current learner rf
[flaml.automl: 12-15 00:50:51] {3343} INFO -  at 1022.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:50:51] {3166} INFO - iteration 241, current learner rf
[flaml.automl: 12-15 00:50:56] {3343} INFO -  at 1027.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:50:56] {3166} INFO - iteration 242, current learner rf
[flaml.automl: 12-15 00:51:04] {3343} INFO -  at 1035.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:51:04] {3166} INFO - iteration 243, current learner rf
[flaml.automl: 12-15 00:51:09] {3343} INFO -  at 1040.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:51:09] {3166} INFO - iteration 244, current learner rf
[flaml.automl: 12-15 00:51:17] {3343} INFO -  at 1048.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:51:17] {3166} INFO - iteration 245, current learner rf
[flaml.automl: 12-15 00:51:26] {3343} INFO -  at 1057.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:51:26] {3166} INFO - iteration 246, current learner rf
[flaml.automl: 12-15 00:51:32] {3343} INFO -  at 1062.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:51:32] {3166} INFO - iteration 247, current learner rf
[flaml.automl: 12-15 00:51:36] {3343} INFO -  at 1067.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:51:36] {3166} INFO - iteration 248, current learner rf
[flaml.automl: 12-15 00:51:43] {3343} INFO -  at 1074.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:51:43] {3166} INFO - iteration 249, current learner rf
[flaml.automl: 12-15 00:51:51] {3343} INFO -  at 1081.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:51:51] {3166} INFO - iteration 250, current learner rf
[flaml.automl: 12-15 00:51:57] {3343} INFO -  at 1088.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:51:57] {3166} INFO - iteration 251, current learner rf
[flaml.automl: 12-15 00:52:06] {3343} INFO -  at 1097.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:52:06] {3166} INFO - iteration 252, current learner rf
[flaml.automl: 12-15 00:52:12] {3343} INFO -  at 1103.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:52:12] {3166} INFO - iteration 253, current learner rf
[flaml.automl: 12-15 00:52:17] {3343} INFO -  at 1108.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:52:17] {3166} INFO - iteration 254, current learner rf
[flaml.automl: 12-15 00:52:24] {3343} INFO -  at 1114.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:52:24] {3166} INFO - iteration 255, current learner rf
[flaml.automl: 12-15 00:52:30] {3343} INFO -  at 1121.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:52:30] {3166} INFO - iteration 256, current learner rf
[flaml.automl: 12-15 00:52:38] {3343} INFO -  at 1128.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:52:38] {3166} INFO - iteration 257, current learner rf
[flaml.automl: 12-15 00:52:47] {3343} INFO -  at 1138.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:52:47] {3166} INFO - iteration 258, current learner rf
[flaml.automl: 12-15 00:52:54] {3343} INFO -  at 1144.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:52:54] {3166} INFO - iteration 259, current learner rf
[flaml.automl: 12-15 00:53:01] {3343} INFO -  at 1152.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:53:01] {3166} INFO - iteration 260, current learner rf
[flaml.automl: 12-15 00:53:06] {3343} INFO -  at 1156.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:53:06] {3166} INFO - iteration 261, current learner rf
[flaml.automl: 12-15 00:53:12] {3343} INFO -  at 1163.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:53:12] {3166} INFO - iteration 262, current learner rf
[flaml.automl: 12-15 00:53:19] {3343} INFO -  at 1170.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:53:19] {3166} INFO - iteration 263, current learner rf
[flaml.automl: 12-15 00:53:29] {3343} INFO -  at 1179.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:53:29] {3166} INFO - iteration 264, current learner rf
[flaml.automl: 12-15 00:53:35] {3343} INFO -  at 1186.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:53:35] {3166} INFO - iteration 265, current learner rf
[flaml.automl: 12-15 00:53:43] {3343} INFO -  at 1193.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:53:43] {3166} INFO - iteration 266, current learner rf
[flaml.automl: 12-15 00:53:48] {3343} INFO -  at 1199.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:53:48] {3166} INFO - iteration 267, current learner rf
[flaml.automl: 12-15 00:53:55] {3343} INFO -  at 1206.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:53:55] {3166} INFO - iteration 268, current learner rf
[flaml.automl: 12-15 00:54:02] {3343} INFO -  at 1212.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:54:02] {3166} INFO - iteration 269, current learner rf
[flaml.automl: 12-15 00:54:07] {3343} INFO -  at 1218.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:54:07] {3166} INFO - iteration 270, current learner rf
[flaml.automl: 12-15 00:54:15] {3343} INFO -  at 1226.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974

[flaml.automl: 12-15 00:54:15] {3166} INFO - iteration 271, current learner rf
[flaml.automl: 12-15 00:54:24] {3343} INFO -  at 1234.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:54:24] {3166} INFO - iteration 272, current learner rf
[flaml.automl: 12-15 00:54:29] {3343} INFO -  at 1240.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:54:29] {3166} INFO - iteration 273, current learner rf
[flaml.automl: 12-15 00:54:35] {3343} INFO -  at 1246.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:54:35] {3166} INFO - iteration 274, current learner rf
[flaml.automl: 12-15 00:54:42] {3343} INFO -  at 1253.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:54:42] {3166} INFO - iteration 275, current learner rf
[flaml.automl: 12-15 00:54:48] {3343} INFO -  at 1259.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:54:48] {3166} INFO - iteration 276, current learner rf
[flaml.automl: 12-15 00:54:57] {3343} INFO -  at 1267.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:54:57] {3166} INFO - iteration 277, current learner rf
[flaml.automl: 12-15 00:55:06] {3343} INFO -  at 1277.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:55:06] {3166} INFO - iteration 278, current learner rf
[flaml.automl: 12-15 00:55:12] {3343} INFO -  at 1283.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:55:12] {3166} INFO - iteration 279, current learner rf
[flaml.automl: 12-15 00:55:21] {3343} INFO -  at 1291.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:55:21] {3166} INFO - iteration 280, current learner rf
[flaml.automl: 12-15 00:55:26] {3343} INFO -  at 1296.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:55:26] {3166} INFO - iteration 281, current learner rf
[flaml.automl: 12-15 00:55:34] {3343} INFO -  at 1305.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:55:34] {3166} INFO - iteration 282, current learner rf
[flaml.automl: 12-15 00:55:40] {3343} INFO -  at 1311.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:55:40] {3166} INFO - iteration 283, current learner rf
[flaml.automl: 12-15 00:55:50] {3343} INFO -  at 1320.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:55:50] {3166} INFO - iteration 284, current learner rf
[flaml.automl: 12-15 00:55:56] {3343} INFO -  at 1327.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:55:56] {3166} INFO - iteration 285, current learner rf
[flaml.automl: 12-15 00:56:01] {3343} INFO -  at 1332.3s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:56:01] {3166} INFO - iteration 286, current learner rf
[flaml.automl: 12-15 00:56:09] {3343} INFO -  at 1340.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:56:09] {3166} INFO - iteration 287, current learner rf
[flaml.automl: 12-15 00:56:15] {3343} INFO -  at 1346.6s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:56:15] {3166} INFO - iteration 288, current learner rf
[flaml.automl: 12-15 00:56:24] {3343} INFO -  at 1354.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:56:24] {3166} INFO - iteration 289, current learner rf
[flaml.automl: 12-15 00:56:29] {3343} INFO -  at 1360.0s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:56:29] {3166} INFO - iteration 290, current learner rf
[flaml.automl: 12-15 00:56:35] {3343} INFO -  at 1366.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:56:35] {3166} INFO - iteration 291, current learner rf
[flaml.automl: 12-15 00:56:45] {3343} INFO -  at 1375.9s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:56:45] {3166} INFO - iteration 292, current learner rf
[flaml.automl: 12-15 00:56:51] {3343} INFO -  at 1381.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:56:51] {3166} INFO - iteration 293, current learner rf
[flaml.automl: 12-15 00:56:58] {3343} INFO -  at 1389.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:56:58] {3166} INFO - iteration 294, current learner rf
[flaml.automl: 12-15 00:57:03] {3343} INFO -  at 1394.5s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:57:03] {3166} INFO - iteration 295, current learner rf
[flaml.automl: 12-15 00:57:10] {3343} INFO -  at 1401.4s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:57:10] {3166} INFO - iteration 296, current learner rf
[flaml.automl: 12-15 00:57:16] {3343} INFO -  at 1406.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:57:16] {3166} INFO - iteration 297, current learner rf
[flaml.automl: 12-15 00:57:22] {3343} INFO -  at 1412.8s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:57:22] {3166} INFO - iteration 298, current learner rf
[flaml.automl: 12-15 00:57:29] {3343} INFO -  at 1419.7s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:57:29] {3166} INFO - iteration 299, current learner rf
[flaml.automl: 12-15 00:57:36] {3343} INFO -  at 1427.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:57:36] {3166} INFO - iteration 300, current learner rf
[flaml.automl: 12-15 00:57:39] {3343} INFO -  at 1430.1s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:57:39] {3166} INFO - iteration 301, current learner rf
[flaml.automl: 12-15 00:57:47] {3343} INFO -  at 1438.2s,	estimator rf's best error=121.2974,	best estimator rf's best error=121.2974
[flaml.automl: 12-15 00:57:49] {3602} INFO - retrain rf for 1.7s
[flaml.automl: 12-15 00:57:49] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.5710587567245761, max_leaf_nodes=897,
                      n_estimators=51, n_jobs=-1)
[flaml.automl: 12-15 00:57:49] {2901} INFO - fit succeeded
[flaml.automl: 12-15 00:57:49] {2902} INFO - Time taken to find the best model: 43.73516893386841
[flaml.automl: 12-15 00:57:49] {2599} INFO - task = regression
[flaml.automl: 12-15 00:57:49] {2601} INFO - Data split method: uniform
[flaml.automl: 12-15 00:57:49] {2604} INFO - Evaluation method: cv
[flaml.automl: 12-15 00:57:49] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 12-15 00:57:49] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 12-15 00:57:49] {3166} INFO - iteration 0, current learner rf
[flaml.automl: 12-15 00:57:51] {3296} INFO - Estimated sufficient time budget=13326s. Estimated necessary time budget=13s.
[flaml.automl: 12-15 00:57:51] {3343} INFO -  at 1.7s,	estimator rf's best error=167.8154,	best estimator rf's best error=167.8154
[flaml.automl: 12-15 00:57:51] {3166} INFO - iteration 1, current learner rf
[flaml.automl: 12-15 00:57:52] {3343} INFO -  at 3.3s,	estimator rf's best error=148.9328,	best estimator rf's best error=148.9328
[flaml.automl: 12-15 00:57:52] {3166} INFO - iteration 2, current learner rf
[flaml.automl: 12-15 00:57:54] {3343} INFO -  at 4.7s,	estimator rf's best error=148.9328,	best estimator rf's best error=148.9328
[flaml.automl: 12-15 00:57:54] {3166} INFO - iteration 3, current learner rf

[flaml.automl: 12-15 00:57:55] {3343} INFO -  at 6.5s,	estimator rf's best error=136.7349,	best estimator rf's best error=136.7349
[flaml.automl: 12-15 00:57:55] {3166} INFO - iteration 4, current learner rf
[flaml.automl: 12-15 00:57:57] {3343} INFO -  at 8.1s,	estimator rf's best error=134.3413,	best estimator rf's best error=134.3413
[flaml.automl: 12-15 00:57:57] {3166} INFO - iteration 5, current learner rf
[flaml.automl: 12-15 00:57:59] {3343} INFO -  at 10.2s,	estimator rf's best error=134.3310,	best estimator rf's best error=134.3310
[flaml.automl: 12-15 00:57:59] {3166} INFO - iteration 6, current learner rf
[flaml.automl: 12-15 00:58:01] {3343} INFO -  at 11.9s,	estimator rf's best error=133.4731,	best estimator rf's best error=133.4731
[flaml.automl: 12-15 00:58:01] {3166} INFO - iteration 7, current learner rf
[flaml.automl: 12-15 00:58:03] {3343} INFO -  at 14.0s,	estimator rf's best error=133.4731,	best estimator rf's best error=133.4731
[flaml.automl: 12-15 00:58:03] {3166} INFO - iteration 8, current learner rf
[flaml.automl: 12-15 00:58:06] {3343} INFO -  at 16.9s,	estimator rf's best error=128.1190,	best estimator rf's best error=128.1190
[flaml.automl: 12-15 00:58:06] {3166} INFO - iteration 9, current learner rf
[flaml.automl: 12-15 00:58:07] {3343} INFO -  at 18.6s,	estimator rf's best error=128.1190,	best estimator rf's best error=128.1190
[flaml.automl: 12-15 00:58:07] {3166} INFO - iteration 10, current learner rf
[flaml.automl: 12-15 00:58:09] {3343} INFO -  at 20.4s,	estimator rf's best error=128.1190,	best estimator rf's best error=128.1190
[flaml.automl: 12-15 00:58:09] {3166} INFO - iteration 11, current learner rf
[flaml.automl: 12-15 00:58:15] {3343} INFO -  at 25.7s,	estimator rf's best error=128.1190,	best estimator rf's best error=128.1190
[flaml.automl: 12-15 00:58:15] {3166} INFO - iteration 12, current learner rf
[flaml.automl: 12-15 00:58:16] {3343} INFO -  at 27.4s,	estimator rf's best error=128.1190,	best estimator rf's best error=128.1190
[flaml.automl: 12-15 00:58:16] {3166} INFO - iteration 13, current learner rf
[flaml.automl: 12-15 00:58:23] {3343} INFO -  at 33.7s,	estimator rf's best error=123.7703,	best estimator rf's best error=123.7703
[flaml.automl: 12-15 00:58:23] {3166} INFO - iteration 14, current learner rf
[flaml.automl: 12-15 00:58:26] {3343} INFO -  at 36.6s,	estimator rf's best error=123.7703,	best estimator rf's best error=123.7703
[flaml.automl: 12-15 00:58:26] {3166} INFO - iteration 15, current learner rf
[flaml.automl: 12-15 00:58:34] {3343} INFO -  at 44.6s,	estimator rf's best error=121.7231,	best estimator rf's best error=121.7231
[flaml.automl: 12-15 00:58:34] {3166} INFO - iteration 16, current learner rf
[flaml.automl: 12-15 00:58:37] {3343} INFO -  at 47.7s,	estimator rf's best error=121.7231,	best estimator rf's best error=121.7231
[flaml.automl: 12-15 00:58:37] {3166} INFO - iteration 17, current learner rf
[flaml.automl: 12-15 00:59:00] {3343} INFO -  at 71.3s,	estimator rf's best error=121.3983,	best estimator rf's best error=121.3983
[flaml.automl: 12-15 00:59:00] {3166} INFO - iteration 18, current learner rf
[flaml.automl: 12-15 00:59:50] {3343} INFO -  at 121.2s,	estimator rf's best error=120.4266,	best estimator rf's best error=120.4266
[flaml.automl: 12-15 00:59:50] {3166} INFO - iteration 19, current learner rf
[flaml.automl: 12-15 01:00:13] {3343} INFO -  at 144.0s,	estimator rf's best error=120.4266,	best estimator rf's best error=120.4266
[flaml.automl: 12-15 01:00:13] {3166} INFO - iteration 20, current learner rf
[flaml.automl: 12-15 01:01:54] {3343} INFO -  at 245.1s,	estimator rf's best error=120.4266,	best estimator rf's best error=120.4266
[flaml.automl: 12-15 01:01:54] {3166} INFO - iteration 21, current learner rf
[flaml.automl: 12-15 01:02:17] {3343} INFO -  at 268.4s,	estimator rf's best error=120.4266,	best estimator rf's best error=120.4266
[flaml.automl: 12-15 01:02:17] {3166} INFO - iteration 22, current learner rf
[flaml.automl: 12-15 01:02:40] {3343} INFO -  at 291.3s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:02:40] {3166} INFO - iteration 23, current learner rf
[flaml.automl: 12-15 01:03:31] {3343} INFO -  at 342.0s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:03:31] {3166} INFO - iteration 24, current learner rf
[flaml.automl: 12-15 01:03:59] {3343} INFO -  at 370.5s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:03:59] {3166} INFO - iteration 25, current learner rf
[flaml.automl: 12-15 01:04:22] {3343} INFO -  at 392.8s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:04:22] {3166} INFO - iteration 26, current learner rf
[flaml.automl: 12-15 01:05:10] {3343} INFO -  at 441.0s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:05:10] {3166} INFO - iteration 27, current learner rf
[flaml.automl: 12-15 01:05:20] {3343} INFO -  at 451.4s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:05:20] {3166} INFO - iteration 28, current learner rf
[flaml.automl: 12-15 01:05:45] {3343} INFO -  at 475.8s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:05:45] {3166} INFO - iteration 29, current learner rf
[flaml.automl: 12-15 01:06:07] {3343} INFO -  at 498.0s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:06:07] {3166} INFO - iteration 30, current learner rf
[flaml.automl: 12-15 01:06:20] {3343} INFO -  at 511.4s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:06:20] {3166} INFO - iteration 31, current learner rf
[flaml.automl: 12-15 01:07:02] {3343} INFO -  at 553.4s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:07:02] {3166} INFO - iteration 32, current learner rf
[flaml.automl: 12-15 01:07:29] {3343} INFO -  at 580.1s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:07:29] {3166} INFO - iteration 33, current learner rf
[flaml.automl: 12-15 01:07:49] {3343} INFO -  at 600.2s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:07:49] {3166} INFO - iteration 34, current learner rf
[flaml.automl: 12-15 01:08:41] {3343} INFO -  at 651.6s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:08:41] {3166} INFO - iteration 35, current learner rf
[flaml.automl: 12-15 01:08:52] {3343} INFO -  at 662.6s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:08:52] {3166} INFO - iteration 36, current learner rf
[flaml.automl: 12-15 01:09:04] {3343} INFO -  at 675.6s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:09:04] {3166} INFO - iteration 37, current learner rf
[flaml.automl: 12-15 01:09:47] {3343} INFO -  at 718.1s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:09:47] {3166} INFO - iteration 38, current learner rf
[flaml.automl: 12-15 01:10:28] {3343} INFO -  at 759.5s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:10:28] {3166} INFO - iteration 39, current learner rf
[flaml.automl: 12-15 01:10:42] {3343} INFO -  at 773.0s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:10:42] {3166} INFO - iteration 40, current learner rf
[flaml.automl: 12-15 01:11:18] {3343} INFO -  at 808.7s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:11:18] {3166} INFO - iteration 41, current learner rf
[flaml.automl: 12-15 01:11:32] {3343} INFO -  at 823.5s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:11:32] {3166} INFO - iteration 42, current learner rf

[flaml.automl: 12-15 01:11:52] {3343} INFO -  at 842.7s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:11:52] {3166} INFO - iteration 43, current learner rf
[flaml.automl: 12-15 01:12:20] {3343} INFO -  at 871.2s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:12:20] {3166} INFO - iteration 44, current learner rf
[flaml.automl: 12-15 01:12:38] {3343} INFO -  at 888.8s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:12:38] {3166} INFO - iteration 45, current learner rf
[flaml.automl: 12-15 01:13:05] {3343} INFO -  at 916.3s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:13:05] {3166} INFO - iteration 46, current learner rf
[flaml.automl: 12-15 01:13:53] {3343} INFO -  at 964.0s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:13:53] {3166} INFO - iteration 47, current learner rf
[flaml.automl: 12-15 01:14:03] {3343} INFO -  at 973.9s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:14:03] {3166} INFO - iteration 48, current learner rf
[flaml.automl: 12-15 01:14:17] {3343} INFO -  at 987.8s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:14:17] {3166} INFO - iteration 49, current learner rf
[flaml.automl: 12-15 01:15:00] {3343} INFO -  at 1031.4s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:15:00] {3166} INFO - iteration 50, current learner rf
[flaml.automl: 12-15 01:15:40] {3343} INFO -  at 1071.2s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:15:40] {3166} INFO - iteration 51, current learner rf
[flaml.automl: 12-15 01:15:54] {3343} INFO -  at 1085.4s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:15:54] {3166} INFO - iteration 52, current learner rf
[flaml.automl: 12-15 01:16:29] {3343} INFO -  at 1119.7s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:16:29] {3166} INFO - iteration 53, current learner rf
[flaml.automl: 12-15 01:16:44] {3343} INFO -  at 1135.6s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:16:45] {3166} INFO - iteration 54, current learner rf
[flaml.automl: 12-15 01:16:59] {3343} INFO -  at 1150.1s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:16:59] {3166} INFO - iteration 55, current learner rf
[flaml.automl: 12-15 01:17:33] {3343} INFO -  at 1184.4s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:17:33] {3166} INFO - iteration 56, current learner rf
[flaml.automl: 12-15 01:18:10] {3343} INFO -  at 1220.8s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:18:10] {3166} INFO - iteration 57, current learner rf
[flaml.automl: 12-15 01:18:24] {3343} INFO -  at 1234.7s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:18:24] {3166} INFO - iteration 58, current learner rf
[flaml.automl: 12-15 01:18:57] {3343} INFO -  at 1267.8s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:18:57] {3166} INFO - iteration 59, current learner rf
[flaml.automl: 12-15 01:19:14] {3343} INFO -  at 1285.1s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:19:14] {3166} INFO - iteration 60, current learner rf
[flaml.automl: 12-15 01:19:32] {3343} INFO -  at 1303.3s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:19:32] {3166} INFO - iteration 61, current learner rf
[flaml.automl: 12-15 01:20:01] {3343} INFO -  at 1331.7s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:20:01] {3166} INFO - iteration 62, current learner rf
[flaml.automl: 12-15 01:20:46] {3343} INFO -  at 1377.0s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:20:46] {3166} INFO - iteration 63, current learner rf
[flaml.automl: 12-15 01:20:57] {3343} INFO -  at 1388.2s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:20:57] {3166} INFO - iteration 64, current learner rf
[flaml.automl: 12-15 01:21:20] {3343} INFO -  at 1411.0s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:21:20] {3166} INFO - iteration 65, current learner rf
[flaml.automl: 12-15 01:21:44] {3343} INFO -  at 1435.1s,	estimator rf's best error=120.1859,	best estimator rf's best error=120.1859
[flaml.automl: 12-15 01:21:48] {3602} INFO - retrain rf for 4.3s
[flaml.automl: 12-15 01:21:48] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.5736638129264788, max_leaf_nodes=788,
                      n_estimators=160, n_jobs=-1)
[flaml.automl: 12-15 01:21:48] {2901} INFO - fit succeeded
[flaml.automl: 12-15 01:21:48] {2902} INFO - Time taken to find the best model: 291.28847074508667
[flaml.automl: 12-15 01:21:49] {2599} INFO - task = regression
[flaml.automl: 12-15 01:21:49] {2601} INFO - Data split method: uniform
[flaml.automl: 12-15 01:21:49] {2604} INFO - Evaluation method: cv
[flaml.automl: 12-15 01:21:49] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 12-15 01:21:49] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 12-15 01:21:49] {3166} INFO - iteration 0, current learner rf
[flaml.automl: 12-15 01:21:50] {3296} INFO - Estimated sufficient time budget=10150s. Estimated necessary time budget=10s.
[flaml.automl: 12-15 01:21:50] {3343} INFO -  at 1.3s,	estimator rf's best error=161.6575,	best estimator rf's best error=161.6575
[flaml.automl: 12-15 01:21:50] {3166} INFO - iteration 1, current learner rf
[flaml.automl: 12-15 01:21:51] {3343} INFO -  at 2.8s,	estimator rf's best error=147.4638,	best estimator rf's best error=147.4638
[flaml.automl: 12-15 01:21:51] {3166} INFO - iteration 2, current learner rf
[flaml.automl: 12-15 01:21:53] {3343} INFO -  at 4.4s,	estimator rf's best error=147.4638,	best estimator rf's best error=147.4638
[flaml.automl: 12-15 01:21:53] {3166} INFO - iteration 3, current learner rf
[flaml.automl: 12-15 01:21:55] {3343} INFO -  at 6.3s,	estimator rf's best error=138.9493,	best estimator rf's best error=138.9493
[flaml.automl: 12-15 01:21:55] {3166} INFO - iteration 4, current learner rf
[flaml.automl: 12-15 01:21:57] {3343} INFO -  at 8.2s,	estimator rf's best error=135.1192,	best estimator rf's best error=135.1192
[flaml.automl: 12-15 01:21:57] {3166} INFO - iteration 5, current learner rf
[flaml.automl: 12-15 01:21:59] {3343} INFO -  at 10.3s,	estimator rf's best error=135.1192,	best estimator rf's best error=135.1192
[flaml.automl: 12-15 01:21:59] {3166} INFO - iteration 6, current learner rf
[flaml.automl: 12-15 01:22:01] {3343} INFO -  at 12.2s,	estimator rf's best error=135.1192,	best estimator rf's best error=135.1192
[flaml.automl: 12-15 01:22:01] {3166} INFO - iteration 7, current learner rf
[flaml.automl: 12-15 01:22:03] {3343} INFO -  at 14.4s,	estimator rf's best error=135.1192,	best estimator rf's best error=135.1192
[flaml.automl: 12-15 01:22:03] {3166} INFO - iteration 8, current learner rf
[flaml.automl: 12-15 01:22:05] {3343} INFO -  at 16.9s,	estimator rf's best error=131.2509,	best estimator rf's best error=131.2509
[flaml.automl: 12-15 01:22:05] {3166} INFO - iteration 9, current learner rf
[flaml.automl: 12-15 01:22:07] {3343} INFO -  at 18.4s,	estimator rf's best error=131.2509,	best estimator rf's best error=131.2509
[flaml.automl: 12-15 01:22:07] {3166} INFO - iteration 10, current learner rf
[flaml.automl: 12-15 01:22:09] {3343} INFO -  at 20.6s,	estimator rf's best error=130.9160,	best estimator rf's best error=130.9160

[flaml.automl: 12-15 01:22:09] {3166} INFO - iteration 11, current learner rf
[flaml.automl: 12-15 01:22:11] {3343} INFO -  at 22.2s,	estimator rf's best error=130.9160,	best estimator rf's best error=130.9160
[flaml.automl: 12-15 01:22:11] {3166} INFO - iteration 12, current learner rf
[flaml.automl: 12-15 01:22:13] {3343} INFO -  at 24.4s,	estimator rf's best error=127.0413,	best estimator rf's best error=127.0413
[flaml.automl: 12-15 01:22:13] {3166} INFO - iteration 13, current learner rf
[flaml.automl: 12-15 01:22:15] {3343} INFO -  at 26.2s,	estimator rf's best error=127.0413,	best estimator rf's best error=127.0413
[flaml.automl: 12-15 01:22:15] {3166} INFO - iteration 14, current learner rf
[flaml.automl: 12-15 01:22:19] {3343} INFO -  at 30.1s,	estimator rf's best error=127.0413,	best estimator rf's best error=127.0413
[flaml.automl: 12-15 01:22:19] {3166} INFO - iteration 15, current learner rf
[flaml.automl: 12-15 01:22:20] {3343} INFO -  at 31.8s,	estimator rf's best error=127.0413,	best estimator rf's best error=127.0413
[flaml.automl: 12-15 01:22:20] {3166} INFO - iteration 16, current learner rf
[flaml.automl: 12-15 01:22:26] {3343} INFO -  at 37.1s,	estimator rf's best error=126.0078,	best estimator rf's best error=126.0078
[flaml.automl: 12-15 01:22:26] {3166} INFO - iteration 17, current learner rf
[flaml.automl: 12-15 01:22:35] {3343} INFO -  at 46.5s,	estimator rf's best error=123.6809,	best estimator rf's best error=123.6809
[flaml.automl: 12-15 01:22:35] {3166} INFO - iteration 18, current learner rf
[flaml.automl: 12-15 01:22:58] {3343} INFO -  at 69.4s,	estimator rf's best error=123.6809,	best estimator rf's best error=123.6809
[flaml.automl: 12-15 01:22:58] {3166} INFO - iteration 19, current learner rf
[flaml.automl: 12-15 01:23:03] {3343} INFO -  at 74.6s,	estimator rf's best error=123.6809,	best estimator rf's best error=123.6809
[flaml.automl: 12-15 01:23:03] {3166} INFO - iteration 20, current learner rf
[flaml.automl: 12-15 01:23:07] {3343} INFO -  at 78.9s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:23:07] {3166} INFO - iteration 21, current learner rf
[flaml.automl: 12-15 01:23:18] {3343} INFO -  at 89.7s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:23:18] {3166} INFO - iteration 22, current learner rf
[flaml.automl: 12-15 01:23:25] {3343} INFO -  at 96.0s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:23:25] {3166} INFO - iteration 23, current learner rf
[flaml.automl: 12-15 01:23:29] {3343} INFO -  at 100.0s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:23:29] {3166} INFO - iteration 24, current learner rf
[flaml.automl: 12-15 01:23:40] {3343} INFO -  at 111.5s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:23:40] {3166} INFO - iteration 25, current learner rf
[flaml.automl: 12-15 01:23:43] {3343} INFO -  at 114.4s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:23:43] {3166} INFO - iteration 26, current learner rf
[flaml.automl: 12-15 01:23:48] {3343} INFO -  at 119.5s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:23:48] {3166} INFO - iteration 27, current learner rf
[flaml.automl: 12-15 01:23:52] {3343} INFO -  at 123.8s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:23:52] {3166} INFO - iteration 28, current learner rf
[flaml.automl: 12-15 01:23:55] {3343} INFO -  at 126.6s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:23:55] {3166} INFO - iteration 29, current learner rf
[flaml.automl: 12-15 01:24:06] {3343} INFO -  at 137.1s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:24:06] {3166} INFO - iteration 30, current learner rf
[flaml.automl: 12-15 01:24:11] {3343} INFO -  at 142.4s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:24:11] {3166} INFO - iteration 31, current learner rf
[flaml.automl: 12-15 01:24:15] {3343} INFO -  at 146.3s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:24:15] {3166} INFO - iteration 32, current learner rf
[flaml.automl: 12-15 01:24:27] {3343} INFO -  at 158.8s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:24:27] {3166} INFO - iteration 33, current learner rf
[flaml.automl: 12-15 01:24:30] {3343} INFO -  at 161.4s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:24:30] {3166} INFO - iteration 34, current learner rf
[flaml.automl: 12-15 01:24:32] {3343} INFO -  at 163.9s,	estimator rf's best error=123.4633,	best estimator rf's best error=123.4633
[flaml.automl: 12-15 01:24:32] {3166} INFO - iteration 35, current learner rf
[flaml.automl: 12-15 01:24:43] {3343} INFO -  at 174.4s,	estimator rf's best error=122.1347,	best estimator rf's best error=122.1347
[flaml.automl: 12-15 01:24:43] {3166} INFO - iteration 36, current learner rf
[flaml.automl: 12-15 01:25:00] {3343} INFO -  at 191.5s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:25:00] {3166} INFO - iteration 37, current learner rf
[flaml.automl: 12-15 01:25:29] {3343} INFO -  at 220.1s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:25:29] {3166} INFO - iteration 38, current learner rf
[flaml.automl: 12-15 01:25:39] {3343} INFO -  at 230.6s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:25:39] {3166} INFO - iteration 39, current learner rf
[flaml.automl: 12-15 01:25:51] {3343} INFO -  at 242.9s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:25:51] {3166} INFO - iteration 40, current learner rf
[flaml.automl: 12-15 01:26:13] {3343} INFO -  at 264.2s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:26:13] {3166} INFO - iteration 41, current learner rf
[flaml.automl: 12-15 01:26:26] {3343} INFO -  at 277.9s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:26:26] {3166} INFO - iteration 42, current learner rf
[flaml.automl: 12-15 01:26:50] {3343} INFO -  at 301.0s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:26:50] {3166} INFO - iteration 43, current learner rf
[flaml.automl: 12-15 01:27:22] {3343} INFO -  at 333.9s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:27:22] {3166} INFO - iteration 44, current learner rf
[flaml.automl: 12-15 01:27:32] {3343} INFO -  at 343.5s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:27:32] {3166} INFO - iteration 45, current learner rf
[flaml.automl: 12-15 01:27:42] {3343} INFO -  at 353.5s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:27:42] {3166} INFO - iteration 46, current learner rf
[flaml.automl: 12-15 01:28:13] {3343} INFO -  at 384.8s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:28:13] {3166} INFO - iteration 47, current learner rf
[flaml.automl: 12-15 01:28:43] {3343} INFO -  at 414.9s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:28:43] {3166} INFO - iteration 48, current learner rf
[flaml.automl: 12-15 01:28:54] {3343} INFO -  at 425.0s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:28:54] {3166} INFO - iteration 49, current learner rf
[flaml.automl: 12-15 01:29:17] {3343} INFO -  at 448.8s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052

[flaml.automl: 12-15 01:29:17] {3166} INFO - iteration 50, current learner rf
[flaml.automl: 12-15 01:29:30] {3343} INFO -  at 461.5s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:29:30] {3166} INFO - iteration 51, current learner rf
[flaml.automl: 12-15 01:29:43] {3343} INFO -  at 474.9s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:29:43] {3166} INFO - iteration 52, current learner rf
[flaml.automl: 12-15 01:30:13] {3343} INFO -  at 504.7s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:30:13] {3166} INFO - iteration 53, current learner rf
[flaml.automl: 12-15 01:30:43] {3343} INFO -  at 534.7s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:30:43] {3166} INFO - iteration 54, current learner rf
[flaml.automl: 12-15 01:30:53] {3343} INFO -  at 544.8s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:30:53] {3166} INFO - iteration 55, current learner rf
[flaml.automl: 12-15 01:31:18] {3343} INFO -  at 569.5s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:31:18] {3166} INFO - iteration 56, current learner rf
[flaml.automl: 12-15 01:31:28] {3343} INFO -  at 579.8s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:31:28] {3166} INFO - iteration 57, current learner rf
[flaml.automl: 12-15 01:31:43] {3343} INFO -  at 594.9s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:31:43] {3166} INFO - iteration 58, current learner rf
[flaml.automl: 12-15 01:32:05] {3343} INFO -  at 616.4s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:32:05] {3166} INFO - iteration 59, current learner rf
[flaml.automl: 12-15 01:32:44] {3343} INFO -  at 655.0s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:32:44] {3166} INFO - iteration 60, current learner rf
[flaml.automl: 12-15 01:32:54] {3343} INFO -  at 665.0s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:32:54] {3166} INFO - iteration 61, current learner rf
[flaml.automl: 12-15 01:33:08] {3343} INFO -  at 679.8s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:33:08] {3166} INFO - iteration 62, current learner rf
[flaml.automl: 12-15 01:33:26] {3343} INFO -  at 697.9s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:33:26] {3166} INFO - iteration 63, current learner rf
[flaml.automl: 12-15 01:33:39] {3343} INFO -  at 710.6s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:33:39] {3166} INFO - iteration 64, current learner rf
[flaml.automl: 12-15 01:34:04] {3343} INFO -  at 735.0s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:34:04] {3166} INFO - iteration 65, current learner rf
[flaml.automl: 12-15 01:34:15] {3343} INFO -  at 746.2s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:34:15] {3166} INFO - iteration 66, current learner rf
[flaml.automl: 12-15 01:34:38] {3343} INFO -  at 769.7s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:34:38] {3166} INFO - iteration 67, current learner rf
[flaml.automl: 12-15 01:35:02] {3343} INFO -  at 793.0s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:35:02] {3166} INFO - iteration 68, current learner rf
[flaml.automl: 12-15 01:35:14] {3343} INFO -  at 805.0s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:35:14] {3166} INFO - iteration 69, current learner rf
[flaml.automl: 12-15 01:35:23] {3343} INFO -  at 814.9s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:35:23] {3166} INFO - iteration 70, current learner rf
[flaml.automl: 12-15 01:35:52] {3343} INFO -  at 843.4s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:35:52] {3166} INFO - iteration 71, current learner rf
[flaml.automl: 12-15 01:36:10] {3343} INFO -  at 861.2s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:36:10] {3166} INFO - iteration 72, current learner rf
[flaml.automl: 12-15 01:36:24] {3343} INFO -  at 875.0s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:36:24] {3166} INFO - iteration 73, current learner rf
[flaml.automl: 12-15 01:36:39] {3343} INFO -  at 890.8s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:36:39] {3166} INFO - iteration 74, current learner rf
[flaml.automl: 12-15 01:36:59] {3343} INFO -  at 910.5s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:36:59] {3166} INFO - iteration 75, current learner rf
[flaml.automl: 12-15 01:37:10] {3343} INFO -  at 921.9s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:37:10] {3166} INFO - iteration 76, current learner rf
[flaml.automl: 12-15 01:37:32] {3343} INFO -  at 943.6s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:37:32] {3166} INFO - iteration 77, current learner rf
[flaml.automl: 12-15 01:37:47] {3343} INFO -  at 958.2s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:37:47] {3166} INFO - iteration 78, current learner rf
[flaml.automl: 12-15 01:38:07] {3343} INFO -  at 978.9s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:38:07] {3166} INFO - iteration 79, current learner rf
[flaml.automl: 12-15 01:38:25] {3343} INFO -  at 996.5s,	estimator rf's best error=121.5052,	best estimator rf's best error=121.5052
[flaml.automl: 12-15 01:38:25] {3166} INFO - iteration 80, current learner rf
[flaml.automl: 12-15 01:38:41] {3343} INFO -  at 1012.1s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:38:41] {3166} INFO - iteration 81, current learner rf
[flaml.automl: 12-15 01:38:50] {3343} INFO -  at 1021.6s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:38:50] {3166} INFO - iteration 82, current learner rf
[flaml.automl: 12-15 01:39:20] {3343} INFO -  at 1051.1s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:39:20] {3166} INFO - iteration 83, current learner rf
[flaml.automl: 12-15 01:39:44] {3343} INFO -  at 1075.2s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:39:44] {3166} INFO - iteration 84, current learner rf
[flaml.automl: 12-15 01:39:53] {3343} INFO -  at 1084.9s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:39:53] {3166} INFO - iteration 85, current learner rf
[flaml.automl: 12-15 01:40:04] {3343} INFO -  at 1095.9s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:40:04] {3166} INFO - iteration 86, current learner rf
[flaml.automl: 12-15 01:40:29] {3343} INFO -  at 1120.0s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:40:29] {3166} INFO - iteration 87, current learner rf
[flaml.automl: 12-15 01:40:44] {3343} INFO -  at 1135.2s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:40:44] {3166} INFO - iteration 88, current learner rf
[flaml.automl: 12-15 01:41:00] {3343} INFO -  at 1151.4s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155

[flaml.automl: 12-15 01:41:00] {3166} INFO - iteration 89, current learner rf
[flaml.automl: 12-15 01:41:15] {3343} INFO -  at 1166.5s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:41:15] {3166} INFO - iteration 90, current learner rf
[flaml.automl: 12-15 01:41:33] {3343} INFO -  at 1184.9s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:41:33] {3166} INFO - iteration 91, current learner rf
[flaml.automl: 12-15 01:41:49] {3343} INFO -  at 1200.7s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:41:49] {3166} INFO - iteration 92, current learner rf
[flaml.automl: 12-15 01:42:07] {3343} INFO -  at 1218.5s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:42:07] {3166} INFO - iteration 93, current learner rf
[flaml.automl: 12-15 01:42:28] {3343} INFO -  at 1239.2s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:42:28] {3166} INFO - iteration 94, current learner rf
[flaml.automl: 12-15 01:42:37] {3343} INFO -  at 1248.4s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:42:37] {3166} INFO - iteration 95, current learner rf
[flaml.automl: 12-15 01:42:48] {3343} INFO -  at 1259.9s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:42:48] {3166} INFO - iteration 96, current learner rf
[flaml.automl: 12-15 01:43:12] {3343} INFO -  at 1283.7s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:43:12] {3166} INFO - iteration 97, current learner rf
[flaml.automl: 12-15 01:43:26] {3343} INFO -  at 1297.7s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:43:26] {3166} INFO - iteration 98, current learner rf
[flaml.automl: 12-15 01:43:45] {3343} INFO -  at 1316.1s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:43:45] {3166} INFO - iteration 99, current learner rf
[flaml.automl: 12-15 01:44:08] {3343} INFO -  at 1339.3s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:44:08] {3166} INFO - iteration 100, current learner rf
[flaml.automl: 12-15 01:44:16] {3343} INFO -  at 1347.8s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:44:16] {3166} INFO - iteration 101, current learner rf
[flaml.automl: 12-15 01:44:41] {3343} INFO -  at 1372.1s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:44:41] {3166} INFO - iteration 102, current learner rf
[flaml.automl: 12-15 01:44:52] {3343} INFO -  at 1383.3s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:44:52] {3166} INFO - iteration 103, current learner rf
[flaml.automl: 12-15 01:45:02] {3343} INFO -  at 1393.4s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:45:02] {3166} INFO - iteration 104, current learner rf
[flaml.automl: 12-15 01:45:30] {3343} INFO -  at 1421.5s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:45:30] {3166} INFO - iteration 105, current learner rf
[flaml.automl: 12-15 01:45:33] {3343} INFO -  at 1424.7s,	estimator rf's best error=120.9155,	best estimator rf's best error=120.9155
[flaml.automl: 12-15 01:45:37] {3602} INFO - retrain rf for 4.2s
[flaml.automl: 12-15 01:45:37] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.6153571441593795, max_leaf_nodes=1251,
                      n_estimators=101, n_jobs=-1)
[flaml.automl: 12-15 01:45:37] {2901} INFO - fit succeeded
[flaml.automl: 12-15 01:45:37] {2902} INFO - Time taken to find the best model: 1012.1193869113922
[flaml.automl: 12-15 01:45:37] {2913} WARNING - Time taken to find the best model is 70% of the provided time budget and not all estimators' hyperparameter search converged. Consider increasing the time budget.
[flaml.automl: 12-15 01:45:38] {2599} INFO - task = regression
[flaml.automl: 12-15 01:45:38] {2601} INFO - Data split method: uniform
[flaml.automl: 12-15 01:45:38] {2604} INFO - Evaluation method: cv
[flaml.automl: 12-15 01:45:38] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 12-15 01:45:38] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 12-15 01:45:38] {3166} INFO - iteration 0, current learner rf
[flaml.automl: 12-15 01:45:40] {3296} INFO - Estimated sufficient time budget=16541s. Estimated necessary time budget=17s.
[flaml.automl: 12-15 01:45:40] {3343} INFO -  at 2.1s,	estimator rf's best error=158.6583,	best estimator rf's best error=158.6583
[flaml.automl: 12-15 01:45:40] {3166} INFO - iteration 1, current learner rf
[flaml.automl: 12-15 01:45:41] {3343} INFO -  at 3.5s,	estimator rf's best error=138.2398,	best estimator rf's best error=138.2398
[flaml.automl: 12-15 01:45:41] {3166} INFO - iteration 2, current learner rf
[flaml.automl: 12-15 01:45:43] {3343} INFO -  at 5.1s,	estimator rf's best error=138.2398,	best estimator rf's best error=138.2398
[flaml.automl: 12-15 01:45:43] {3166} INFO - iteration 3, current learner rf
[flaml.automl: 12-15 01:45:45] {3343} INFO -  at 7.2s,	estimator rf's best error=133.8998,	best estimator rf's best error=133.8998
[flaml.automl: 12-15 01:45:45] {3166} INFO - iteration 4, current learner rf
[flaml.automl: 12-15 01:45:46] {3343} INFO -  at 8.7s,	estimator rf's best error=127.9449,	best estimator rf's best error=127.9449
[flaml.automl: 12-15 01:45:46] {3166} INFO - iteration 5, current learner rf
[flaml.automl: 12-15 01:45:48] {3343} INFO -  at 10.3s,	estimator rf's best error=127.9449,	best estimator rf's best error=127.9449
[flaml.automl: 12-15 01:45:48] {3166} INFO - iteration 6, current learner rf
[flaml.automl: 12-15 01:45:49] {3343} INFO -  at 11.8s,	estimator rf's best error=126.1310,	best estimator rf's best error=126.1310
[flaml.automl: 12-15 01:45:49] {3166} INFO - iteration 7, current learner rf
[flaml.automl: 12-15 01:45:51] {3343} INFO -  at 13.8s,	estimator rf's best error=126.1310,	best estimator rf's best error=126.1310
[flaml.automl: 12-15 01:45:51] {3166} INFO - iteration 8, current learner rf
[flaml.automl: 12-15 01:45:54] {3343} INFO -  at 16.7s,	estimator rf's best error=122.9185,	best estimator rf's best error=122.9185
[flaml.automl: 12-15 01:45:54] {3166} INFO - iteration 9, current learner rf
[flaml.automl: 12-15 01:45:56] {3343} INFO -  at 18.3s,	estimator rf's best error=122.9185,	best estimator rf's best error=122.9185
[flaml.automl: 12-15 01:45:56] {3166} INFO - iteration 10, current learner rf
[flaml.automl: 12-15 01:45:58] {3343} INFO -  at 20.1s,	estimator rf's best error=122.9185,	best estimator rf's best error=122.9185
[flaml.automl: 12-15 01:45:58] {3166} INFO - iteration 11, current learner rf
[flaml.automl: 12-15 01:46:03] {3343} INFO -  at 25.5s,	estimator rf's best error=117.9305,	best estimator rf's best error=117.9305
[flaml.automl: 12-15 01:46:03] {3166} INFO - iteration 12, current learner rf
[flaml.automl: 12-15 01:46:06] {3343} INFO -  at 28.1s,	estimator rf's best error=117.9305,	best estimator rf's best error=117.9305
[flaml.automl: 12-15 01:46:06] {3166} INFO - iteration 13, current learner rf
[flaml.automl: 12-15 01:46:16] {3343} INFO -  at 38.2s,	estimator rf's best error=117.9305,	best estimator rf's best error=117.9305
[flaml.automl: 12-15 01:46:16] {3166} INFO - iteration 14, current learner rf
[flaml.automl: 12-15 01:46:19] {3343} INFO -  at 41.2s,	estimator rf's best error=117.9305,	best estimator rf's best error=117.9305
[flaml.automl: 12-15 01:46:19] {3166} INFO - iteration 15, current learner rf
[flaml.automl: 12-15 01:46:27] {3343} INFO -  at 48.9s,	estimator rf's best error=116.4964,	best estimator rf's best error=116.4964
[flaml.automl: 12-15 01:46:27] {3166} INFO - iteration 16, current learner rf
[flaml.automl: 12-15 01:46:29] {3343} INFO -  at 51.7s,	estimator rf's best error=116.4964,	best estimator rf's best error=116.4964

[flaml.automl: 12-15 01:46:29] {3166} INFO - iteration 17, current learner rf
[flaml.automl: 12-15 01:46:51] {3343} INFO -  at 73.0s,	estimator rf's best error=116.3416,	best estimator rf's best error=116.3416
[flaml.automl: 12-15 01:46:51] {3166} INFO - iteration 18, current learner rf
[flaml.automl: 12-15 01:47:36] {3343} INFO -  at 118.1s,	estimator rf's best error=116.3416,	best estimator rf's best error=116.3416
[flaml.automl: 12-15 01:47:36] {3166} INFO - iteration 19, current learner rf
[flaml.automl: 12-15 01:47:43] {3343} INFO -  at 125.7s,	estimator rf's best error=116.3416,	best estimator rf's best error=116.3416
[flaml.automl: 12-15 01:47:43] {3166} INFO - iteration 20, current learner rf
[flaml.automl: 12-15 01:48:22] {3343} INFO -  at 164.1s,	estimator rf's best error=116.3416,	best estimator rf's best error=116.3416
[flaml.automl: 12-15 01:48:22] {3166} INFO - iteration 21, current learner rf
[flaml.automl: 12-15 01:48:31] {3343} INFO -  at 173.6s,	estimator rf's best error=116.3416,	best estimator rf's best error=116.3416
[flaml.automl: 12-15 01:48:31] {3166} INFO - iteration 22, current learner rf
[flaml.automl: 12-15 01:48:40] {3343} INFO -  at 182.1s,	estimator rf's best error=116.3416,	best estimator rf's best error=116.3416
[flaml.automl: 12-15 01:48:40] {3166} INFO - iteration 23, current learner rf
[flaml.automl: 12-15 01:49:18] {3343} INFO -  at 220.7s,	estimator rf's best error=116.3416,	best estimator rf's best error=116.3416
[flaml.automl: 12-15 01:49:18] {3166} INFO - iteration 24, current learner rf
[flaml.automl: 12-15 01:49:42] {3343} INFO -  at 244.5s,	estimator rf's best error=116.3416,	best estimator rf's best error=116.3416
[flaml.automl: 12-15 01:49:42] {3166} INFO - iteration 25, current learner rf
[flaml.automl: 12-15 01:49:59] {3343} INFO -  at 261.5s,	estimator rf's best error=116.3416,	best estimator rf's best error=116.3416
[flaml.automl: 12-15 01:49:59] {3166} INFO - iteration 26, current learner rf
[flaml.automl: 12-15 01:50:36] {3343} INFO -  at 298.6s,	estimator rf's best error=115.7393,	best estimator rf's best error=115.7393
[flaml.automl: 12-15 01:50:36] {3166} INFO - iteration 27, current learner rf
[flaml.automl: 12-15 01:50:56] {3343} INFO -  at 318.5s,	estimator rf's best error=115.7393,	best estimator rf's best error=115.7393
[flaml.automl: 12-15 01:50:56] {3166} INFO - iteration 28, current learner rf
[flaml.automl: 12-15 01:51:31] {3343} INFO -  at 353.5s,	estimator rf's best error=115.7393,	best estimator rf's best error=115.7393
[flaml.automl: 12-15 01:51:31] {3166} INFO - iteration 29, current learner rf
[flaml.automl: 12-15 01:52:06] {3343} INFO -  at 388.0s,	estimator rf's best error=115.7393,	best estimator rf's best error=115.7393
[flaml.automl: 12-15 01:52:06] {3166} INFO - iteration 30, current learner rf
[flaml.automl: 12-15 01:52:23] {3343} INFO -  at 405.0s,	estimator rf's best error=115.7393,	best estimator rf's best error=115.7393
[flaml.automl: 12-15 01:52:23] {3166} INFO - iteration 31, current learner rf
[flaml.automl: 12-15 01:53:30] {3343} INFO -  at 472.3s,	estimator rf's best error=115.7393,	best estimator rf's best error=115.7393
[flaml.automl: 12-15 01:53:30] {3166} INFO - iteration 32, current learner rf
[flaml.automl: 12-15 01:54:11] {3343} INFO -  at 513.2s,	estimator rf's best error=115.7393,	best estimator rf's best error=115.7393
[flaml.automl: 12-15 01:54:11] {3166} INFO - iteration 33, current learner rf
[flaml.automl: 12-15 01:54:41] {3343} INFO -  at 543.1s,	estimator rf's best error=115.7393,	best estimator rf's best error=115.7393
[flaml.automl: 12-15 01:54:41] {3166} INFO - iteration 34, current learner rf
[flaml.automl: 12-15 01:56:04] {3343} INFO -  at 626.6s,	estimator rf's best error=115.7393,	best estimator rf's best error=115.7393
[flaml.automl: 12-15 01:56:04] {3166} INFO - iteration 35, current learner rf
[flaml.automl: 12-15 01:56:20] {3343} INFO -  at 642.0s,	estimator rf's best error=115.7393,	best estimator rf's best error=115.7393
[flaml.automl: 12-15 01:56:20] {3166} INFO - iteration 36, current learner rf
[flaml.automl: 12-15 01:56:34] {3343} INFO -  at 656.0s,	estimator rf's best error=115.7393,	best estimator rf's best error=115.7393
[flaml.automl: 12-15 01:56:34] {3166} INFO - iteration 37, current learner rf
[flaml.automl: 12-15 01:57:47] {3343} INFO -  at 729.1s,	estimator rf's best error=115.6617,	best estimator rf's best error=115.6617
[flaml.automl: 12-15 01:57:47] {3166} INFO - iteration 38, current learner rf
[flaml.automl: 12-15 02:00:10] {3343} INFO -  at 872.7s,	estimator rf's best error=115.0375,	best estimator rf's best error=115.0375
[flaml.automl: 12-15 02:00:10] {3166} INFO - iteration 39, current learner rf
[flaml.automl: 12-15 02:01:18] {3343} INFO -  at 940.1s,	estimator rf's best error=115.0375,	best estimator rf's best error=115.0375
[flaml.automl: 12-15 02:01:18] {3166} INFO - iteration 40, current learner rf
[flaml.automl: 12-15 02:05:13] {3343} INFO -  at 1174.9s,	estimator rf's best error=115.0375,	best estimator rf's best error=115.0375
[flaml.automl: 12-15 02:05:13] {3166} INFO - iteration 41, current learner rf
[flaml.automl: 12-15 02:05:54] {3343} INFO -  at 1216.5s,	estimator rf's best error=115.0375,	best estimator rf's best error=115.0375
[flaml.automl: 12-15 02:05:54] {3166} INFO - iteration 42, current learner rf
[flaml.automl: 12-15 02:06:27] {3343} INFO -  at 1249.6s,	estimator rf's best error=115.0375,	best estimator rf's best error=115.0375
[flaml.automl: 12-15 02:06:27] {3166} INFO - iteration 43, current learner rf
[flaml.automl: 12-15 02:07:20] {3343} INFO -  at 1302.3s,	estimator rf's best error=115.0375,	best estimator rf's best error=115.0375
[flaml.automl: 12-15 02:07:47] {3602} INFO - retrain rf for 26.7s
[flaml.automl: 12-15 02:07:47] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.514132143280216, max_leaf_nodes=699,
                      n_estimators=867, n_jobs=-1)
[flaml.automl: 12-15 02:07:47] {2901} INFO - fit succeeded
[flaml.automl: 12-15 02:07:47] {2902} INFO - Time taken to find the best model: 872.6579940319061
[flaml.automl: 12-15 02:07:48] {2599} INFO - task = regression
[flaml.automl: 12-15 02:07:48] {2601} INFO - Data split method: uniform
[flaml.automl: 12-15 02:07:48] {2604} INFO - Evaluation method: cv
[flaml.automl: 12-15 02:07:48] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 12-15 02:07:48] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 12-15 02:07:48] {3166} INFO - iteration 0, current learner rf
[flaml.automl: 12-15 02:07:50] {3296} INFO - Estimated sufficient time budget=17699s. Estimated necessary time budget=18s.
[flaml.automl: 12-15 02:07:50] {3343} INFO -  at 2.1s,	estimator rf's best error=163.3359,	best estimator rf's best error=163.3359
[flaml.automl: 12-15 02:07:50] {3166} INFO - iteration 1, current learner rf
[flaml.automl: 12-15 02:07:51] {3343} INFO -  at 3.4s,	estimator rf's best error=146.5563,	best estimator rf's best error=146.5563
[flaml.automl: 12-15 02:07:51] {3166} INFO - iteration 2, current learner rf
[flaml.automl: 12-15 02:07:53] {3343} INFO -  at 4.9s,	estimator rf's best error=146.5563,	best estimator rf's best error=146.5563
[flaml.automl: 12-15 02:07:53] {3166} INFO - iteration 3, current learner rf
[flaml.automl: 12-15 02:07:55] {3343} INFO -  at 6.9s,	estimator rf's best error=137.8891,	best estimator rf's best error=137.8891
[flaml.automl: 12-15 02:07:55] {3166} INFO - iteration 4, current learner rf
[flaml.automl: 12-15 02:07:57] {3343} INFO -  at 8.9s,	estimator rf's best error=136.3330,	best estimator rf's best error=136.3330
[flaml.automl: 12-15 02:07:57] {3166} INFO - iteration 5, current learner rf
[flaml.automl: 12-15 02:07:58] {3343} INFO -  at 10.4s,	estimator rf's best error=136.3330,	best estimator rf's best error=136.3330
[flaml.automl: 12-15 02:07:58] {3166} INFO - iteration 6, current learner rf
[flaml.automl: 12-15 02:08:00] {3343} INFO -  at 12.0s,	estimator rf's best error=129.7257,	best estimator rf's best error=129.7257
[flaml.automl: 12-15 02:08:00] {3166} INFO - iteration 7, current learner rf
[flaml.automl: 12-15 02:08:02] {3343} INFO -  at 13.7s,	estimator rf's best error=129.7257,	best estimator rf's best error=129.7257

[flaml.automl: 12-15 02:08:02] {3166} INFO - iteration 8, current learner rf
[flaml.automl: 12-15 02:08:04] {3343} INFO -  at 15.9s,	estimator rf's best error=124.0091,	best estimator rf's best error=124.0091
[flaml.automl: 12-15 02:08:04] {3166} INFO - iteration 9, current learner rf
[flaml.automl: 12-15 02:08:06] {3343} INFO -  at 17.6s,	estimator rf's best error=124.0091,	best estimator rf's best error=124.0091
[flaml.automl: 12-15 02:08:06] {3166} INFO - iteration 10, current learner rf
[flaml.automl: 12-15 02:08:08] {3343} INFO -  at 19.5s,	estimator rf's best error=124.0091,	best estimator rf's best error=124.0091
[flaml.automl: 12-15 02:08:08] {3166} INFO - iteration 11, current learner rf
[flaml.automl: 12-15 02:08:12] {3343} INFO -  at 23.8s,	estimator rf's best error=123.1204,	best estimator rf's best error=123.1204
[flaml.automl: 12-15 02:08:12] {3166} INFO - iteration 12, current learner rf
[flaml.automl: 12-15 02:08:14] {3343} INFO -  at 26.1s,	estimator rf's best error=123.1204,	best estimator rf's best error=123.1204
[flaml.automl: 12-15 02:08:14] {3166} INFO - iteration 13, current learner rf
[flaml.automl: 12-15 02:08:24] {3343} INFO -  at 35.5s,	estimator rf's best error=122.2115,	best estimator rf's best error=122.2115
[flaml.automl: 12-15 02:08:24] {3166} INFO - iteration 14, current learner rf
[flaml.automl: 12-15 02:08:30] {3343} INFO -  at 41.7s,	estimator rf's best error=122.2115,	best estimator rf's best error=122.2115
[flaml.automl: 12-15 02:08:30] {3166} INFO - iteration 15, current learner rf
[flaml.automl: 12-15 02:08:50] {3343} INFO -  at 61.7s,	estimator rf's best error=120.8505,	best estimator rf's best error=120.8505
[flaml.automl: 12-15 02:08:50] {3166} INFO - iteration 16, current learner rf
[flaml.automl: 12-15 02:08:57] {3343} INFO -  at 68.7s,	estimator rf's best error=120.8505,	best estimator rf's best error=120.8505
[flaml.automl: 12-15 02:08:57] {3166} INFO - iteration 17, current learner rf
[flaml.automl: 12-15 02:09:44] {3343} INFO -  at 116.2s,	estimator rf's best error=120.6827,	best estimator rf's best error=120.6827
[flaml.automl: 12-15 02:09:44] {3166} INFO - iteration 18, current learner rf
[flaml.automl: 12-15 02:11:21] {3343} INFO -  at 213.3s,	estimator rf's best error=120.3062,	best estimator rf's best error=120.3062
[flaml.automl: 12-15 02:11:21] {3166} INFO - iteration 19, current learner rf
[flaml.automl: 12-15 02:13:58] {3343} INFO -  at 370.3s,	estimator rf's best error=120.2036,	best estimator rf's best error=120.2036
[flaml.automl: 12-15 02:13:58] {3166} INFO - iteration 20, current learner rf
[flaml.automl: 12-15 02:15:37] {3343} INFO -  at 468.5s,	estimator rf's best error=120.1759,	best estimator rf's best error=120.1759
[flaml.automl: 12-15 02:15:37] {3166} INFO - iteration 21, current learner rf
[flaml.automl: 12-15 02:16:20] {3343} INFO -  at 512.2s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:16:20] {3166} INFO - iteration 22, current learner rf
[flaml.automl: 12-15 02:17:58] {3343} INFO -  at 609.9s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:17:58] {3166} INFO - iteration 23, current learner rf
[flaml.automl: 12-15 02:18:55] {3343} INFO -  at 666.7s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:18:55] {3166} INFO - iteration 24, current learner rf
[flaml.automl: 12-15 02:19:33] {3343} INFO -  at 705.4s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:19:33] {3166} INFO - iteration 25, current learner rf
[flaml.automl: 12-15 02:21:04] {3343} INFO -  at 795.5s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:21:04] {3166} INFO - iteration 26, current learner rf
[flaml.automl: 12-15 02:21:27] {3343} INFO -  at 819.0s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:21:27] {3166} INFO - iteration 27, current learner rf
[flaml.automl: 12-15 02:22:08] {3343} INFO -  at 860.2s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:22:08] {3166} INFO - iteration 28, current learner rf
[flaml.automl: 12-15 02:22:53] {3343} INFO -  at 904.7s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:22:53] {3166} INFO - iteration 29, current learner rf
[flaml.automl: 12-15 02:23:14] {3343} INFO -  at 926.0s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:23:14] {3166} INFO - iteration 30, current learner rf
[flaml.automl: 12-15 02:24:39] {3343} INFO -  at 1010.6s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:24:39] {3166} INFO - iteration 31, current learner rf
[flaml.automl: 12-15 02:25:36] {3343} INFO -  at 1067.9s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:25:36] {3166} INFO - iteration 32, current learner rf
[flaml.automl: 12-15 02:26:16] {3343} INFO -  at 1108.3s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:26:16] {3166} INFO - iteration 33, current learner rf
[flaml.automl: 12-15 02:27:50] {3343} INFO -  at 1202.1s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:27:50] {3166} INFO - iteration 34, current learner rf
[flaml.automl: 12-15 02:28:14] {3343} INFO -  at 1226.4s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:28:14] {3166} INFO - iteration 35, current learner rf
[flaml.automl: 12-15 02:28:36] {3343} INFO -  at 1247.9s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:28:36] {3166} INFO - iteration 36, current learner rf
[flaml.automl: 12-15 02:29:28] {3343} INFO -  at 1299.7s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:29:28] {3166} INFO - iteration 37, current learner rf
[flaml.automl: 12-15 02:30:43] {3343} INFO -  at 1375.0s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:30:43] {3166} INFO - iteration 38, current learner rf
[flaml.automl: 12-15 02:30:50] {3343} INFO -  at 1381.7s,	estimator rf's best error=119.4914,	best estimator rf's best error=119.4914
[flaml.automl: 12-15 02:30:50] {3166} INFO - iteration 39, current learner rf
[flaml.automl: 12-15 02:31:54] {3343} INFO -  at 1445.9s,	estimator rf's best error=116.0899,	best estimator rf's best error=116.0899
[flaml.automl: 12-15 02:32:11] {3602} INFO - retrain rf for 17.2s
[flaml.automl: 12-15 02:32:11] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.5988580313553274, max_leaf_nodes=911,
                      n_estimators=474, n_jobs=-1)
[flaml.automl: 12-15 02:32:11] {2901} INFO - fit succeeded
[flaml.automl: 12-15 02:32:11] {2902} INFO - Time taken to find the best model: 1445.8696949481964
[flaml.automl: 12-15 02:32:11] {2913} WARNING - Time taken to find the best model is 100% of the provided time budget and not all estimators' hyperparameter search converged. Consider increasing the time budget.
[flaml.automl: 12-15 02:32:12] {2599} INFO - task = regression
[flaml.automl: 12-15 02:32:12] {2601} INFO - Data split method: uniform
[flaml.automl: 12-15 02:32:12] {2604} INFO - Evaluation method: cv
[flaml.automl: 12-15 02:32:12] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 12-15 02:32:12] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 12-15 02:32:12] {3166} INFO - iteration 0, current learner rf
[flaml.automl: 12-15 02:32:14] {3296} INFO - Estimated sufficient time budget=17292s. Estimated necessary time budget=17s.
[flaml.automl: 12-15 02:32:14] {3343} INFO -  at 2.0s,	estimator rf's best error=163.3634,	best estimator rf's best error=163.3634
[flaml.automl: 12-15 02:32:14] {3166} INFO - iteration 1, current learner rf
[flaml.automl: 12-15 02:32:16] {3343} INFO -  at 3.8s,	estimator rf's best error=144.2746,	best estimator rf's best error=144.2746

[flaml.automl: 12-15 02:32:16] {3166} INFO - iteration 2, current learner rf
[flaml.automl: 12-15 02:32:17] {3343} INFO -  at 5.3s,	estimator rf's best error=144.2746,	best estimator rf's best error=144.2746
[flaml.automl: 12-15 02:32:17] {3166} INFO - iteration 3, current learner rf
[flaml.automl: 12-15 02:32:19] {3343} INFO -  at 7.6s,	estimator rf's best error=135.2723,	best estimator rf's best error=135.2723
[flaml.automl: 12-15 02:32:19] {3166} INFO - iteration 4, current learner rf
[flaml.automl: 12-15 02:32:22] {3343} INFO -  at 9.8s,	estimator rf's best error=130.7326,	best estimator rf's best error=130.7326
[flaml.automl: 12-15 02:32:22] {3166} INFO - iteration 5, current learner rf
[flaml.automl: 12-15 02:32:23] {3343} INFO -  at 11.5s,	estimator rf's best error=130.6158,	best estimator rf's best error=130.6158
[flaml.automl: 12-15 02:32:23] {3166} INFO - iteration 6, current learner rf
[flaml.automl: 12-15 02:32:25] {3343} INFO -  at 13.1s,	estimator rf's best error=128.2196,	best estimator rf's best error=128.2196
[flaml.automl: 12-15 02:32:25] {3166} INFO - iteration 7, current learner rf
[flaml.automl: 12-15 02:32:27] {3343} INFO -  at 15.6s,	estimator rf's best error=128.2196,	best estimator rf's best error=128.2196
[flaml.automl: 12-15 02:32:27] {3166} INFO - iteration 8, current learner rf
[flaml.automl: 12-15 02:32:30] {3343} INFO -  at 18.1s,	estimator rf's best error=121.7373,	best estimator rf's best error=121.7373
[flaml.automl: 12-15 02:32:30] {3166} INFO - iteration 9, current learner rf
[flaml.automl: 12-15 02:32:31] {3343} INFO -  at 19.6s,	estimator rf's best error=121.7373,	best estimator rf's best error=121.7373
[flaml.automl: 12-15 02:32:31] {3166} INFO - iteration 10, current learner rf
[flaml.automl: 12-15 02:32:33] {3343} INFO -  at 21.0s,	estimator rf's best error=121.7373,	best estimator rf's best error=121.7373
[flaml.automl: 12-15 02:32:33] {3166} INFO - iteration 11, current learner rf
[flaml.automl: 12-15 02:32:40] {3343} INFO -  at 28.1s,	estimator rf's best error=121.7373,	best estimator rf's best error=121.7373
[flaml.automl: 12-15 02:32:40] {3166} INFO - iteration 12, current learner rf
[flaml.automl: 12-15 02:32:42] {3343} INFO -  at 30.2s,	estimator rf's best error=121.7373,	best estimator rf's best error=121.7373
[flaml.automl: 12-15 02:32:42] {3166} INFO - iteration 13, current learner rf
[flaml.automl: 12-15 02:32:47] {3343} INFO -  at 34.9s,	estimator rf's best error=118.3266,	best estimator rf's best error=118.3266
[flaml.automl: 12-15 02:32:47] {3166} INFO - iteration 14, current learner rf
[flaml.automl: 12-15 02:32:50] {3343} INFO -  at 37.9s,	estimator rf's best error=118.3266,	best estimator rf's best error=118.3266
[flaml.automl: 12-15 02:32:50] {3166} INFO - iteration 15, current learner rf
[flaml.automl: 12-15 02:32:59] {3343} INFO -  at 47.2s,	estimator rf's best error=116.2495,	best estimator rf's best error=116.2495
[flaml.automl: 12-15 02:32:59] {3166} INFO - iteration 16, current learner rf
[flaml.automl: 12-15 02:33:03] {3343} INFO -  at 51.3s,	estimator rf's best error=116.2495,	best estimator rf's best error=116.2495
[flaml.automl: 12-15 02:33:03] {3166} INFO - iteration 17, current learner rf
[flaml.automl: 12-15 02:33:23] {3343} INFO -  at 71.7s,	estimator rf's best error=116.1009,	best estimator rf's best error=116.1009
[flaml.automl: 12-15 02:33:23] {3166} INFO - iteration 18, current learner rf
[flaml.automl: 12-15 02:34:16] {3343} INFO -  at 123.8s,	estimator rf's best error=114.9529,	best estimator rf's best error=114.9529
[flaml.automl: 12-15 02:34:16] {3166} INFO - iteration 19, current learner rf
[flaml.automl: 12-15 02:34:38] {3343} INFO -  at 146.5s,	estimator rf's best error=114.9529,	best estimator rf's best error=114.9529
[flaml.automl: 12-15 02:34:38] {3166} INFO - iteration 20, current learner rf
[flaml.automl: 12-15 02:36:14] {3343} INFO -  at 242.6s,	estimator rf's best error=114.9529,	best estimator rf's best error=114.9529
[flaml.automl: 12-15 02:36:14] {3166} INFO - iteration 21, current learner rf
[flaml.automl: 12-15 02:36:36] {3343} INFO -  at 264.6s,	estimator rf's best error=114.9529,	best estimator rf's best error=114.9529
[flaml.automl: 12-15 02:36:36] {3166} INFO - iteration 22, current learner rf
[flaml.automl: 12-15 02:37:01] {3343} INFO -  at 289.6s,	estimator rf's best error=114.9529,	best estimator rf's best error=114.9529
[flaml.automl: 12-15 02:37:01] {3166} INFO - iteration 23, current learner rf
[flaml.automl: 12-15 02:38:42] {3343} INFO -  at 390.3s,	estimator rf's best error=114.9529,	best estimator rf's best error=114.9529
[flaml.automl: 12-15 02:38:42] {3166} INFO - iteration 24, current learner rf
[flaml.automl: 12-15 02:39:40] {3343} INFO -  at 447.8s,	estimator rf's best error=114.9529,	best estimator rf's best error=114.9529
[flaml.automl: 12-15 02:39:40] {3166} INFO - iteration 25, current learner rf
[flaml.automl: 12-15 02:40:22] {3343} INFO -  at 490.6s,	estimator rf's best error=114.9529,	best estimator rf's best error=114.9529
[flaml.automl: 12-15 02:40:22] {3166} INFO - iteration 26, current learner rf
[flaml.automl: 12-15 02:42:08] {3343} INFO -  at 596.6s,	estimator rf's best error=114.9529,	best estimator rf's best error=114.9529
[flaml.automl: 12-15 02:42:08] {3166} INFO - iteration 27, current learner rf
[flaml.automl: 12-15 02:42:33] {3343} INFO -  at 621.7s,	estimator rf's best error=114.9529,	best estimator rf's best error=114.9529
[flaml.automl: 12-15 02:42:33] {3166} INFO - iteration 28, current learner rf
[flaml.automl: 12-15 02:43:24] {3343} INFO -  at 672.6s,	estimator rf's best error=114.9529,	best estimator rf's best error=114.9529
[flaml.automl: 12-15 02:43:24] {3166} INFO - iteration 29, current learner rf
[flaml.automl: 12-15 02:44:15] {3343} INFO -  at 723.0s,	estimator rf's best error=114.9529,	best estimator rf's best error=114.9529
[flaml.automl: 12-15 02:44:15] {3166} INFO - iteration 30, current learner rf
[flaml.automl: 12-15 02:44:43] {3343} INFO -  at 751.2s,	estimator rf's best error=114.9529,	best estimator rf's best error=114.9529
[flaml.automl: 12-15 02:44:43] {3166} INFO - iteration 31, current learner rf
[flaml.automl: 12-15 02:46:05] {3343} INFO -  at 833.2s,	estimator rf's best error=114.4650,	best estimator rf's best error=114.4650
[flaml.automl: 12-15 02:46:05] {3166} INFO - iteration 32, current learner rf
[flaml.automl: 12-15 02:47:37] {3343} INFO -  at 925.6s,	estimator rf's best error=114.4650,	best estimator rf's best error=114.4650
[flaml.automl: 12-15 02:47:37] {3166} INFO - iteration 33, current learner rf
[flaml.automl: 12-15 02:48:51] {3343} INFO -  at 998.7s,	estimator rf's best error=114.4650,	best estimator rf's best error=114.4650
[flaml.automl: 12-15 02:48:51] {3166} INFO - iteration 34, current learner rf
[flaml.automl: 12-15 02:50:54] {3343} INFO -  at 1122.4s,	estimator rf's best error=114.4650,	best estimator rf's best error=114.4650
[flaml.automl: 12-15 02:50:54] {3166} INFO - iteration 35, current learner rf
[flaml.automl: 12-15 02:51:33] {3343} INFO -  at 1160.9s,	estimator rf's best error=114.4650,	best estimator rf's best error=114.4650
[flaml.automl: 12-15 02:51:33] {3166} INFO - iteration 36, current learner rf
[flaml.automl: 12-15 02:52:18] {3343} INFO -  at 1206.2s,	estimator rf's best error=114.4650,	best estimator rf's best error=114.4650
[flaml.automl: 12-15 02:52:18] {3166} INFO - iteration 37, current learner rf
[flaml.automl: 12-15 02:53:38] {3343} INFO -  at 1286.3s,	estimator rf's best error=114.4650,	best estimator rf's best error=114.4650
[flaml.automl: 12-15 02:53:38] {3166} INFO - iteration 38, current learner rf
[flaml.automl: 12-15 02:55:34] {3343} INFO -  at 1402.1s,	estimator rf's best error=114.4650,	best estimator rf's best error=114.4650
[flaml.automl: 12-15 02:55:53] {3602} INFO - retrain rf for 18.8s
[flaml.automl: 12-15 02:55:53] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.5745817548895322, max_leaf_nodes=887,
                      n_estimators=566, n_jobs=-1)
[flaml.automl: 12-15 02:55:53] {2901} INFO - fit succeeded
[flaml.automl: 12-15 02:55:53] {2902} INFO - Time taken to find the best model: 833.1668028831482

[flaml.automl: 12-15 02:55:54] {2599} INFO - task = regression
[flaml.automl: 12-15 02:55:54] {2601} INFO - Data split method: uniform
[flaml.automl: 12-15 02:55:54] {2604} INFO - Evaluation method: cv
[flaml.automl: 12-15 02:55:54] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 12-15 02:55:54] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 12-15 02:55:54] {3166} INFO - iteration 0, current learner rf
[flaml.automl: 12-15 02:55:55] {3296} INFO - Estimated sufficient time budget=15169s. Estimated necessary time budget=15s.
[flaml.automl: 12-15 02:55:55] {3343} INFO -  at 1.9s,	estimator rf's best error=167.7586,	best estimator rf's best error=167.7586
[flaml.automl: 12-15 02:55:55] {3166} INFO - iteration 1, current learner rf
[flaml.automl: 12-15 02:55:57] {3343} INFO -  at 3.5s,	estimator rf's best error=148.8587,	best estimator rf's best error=148.8587
[flaml.automl: 12-15 02:55:57] {3166} INFO - iteration 2, current learner rf
[flaml.automl: 12-15 02:55:59] {3343} INFO -  at 5.2s,	estimator rf's best error=148.8587,	best estimator rf's best error=148.8587
[flaml.automl: 12-15 02:55:59] {3166} INFO - iteration 3, current learner rf
[flaml.automl: 12-15 02:56:01] {3343} INFO -  at 7.9s,	estimator rf's best error=139.5694,	best estimator rf's best error=139.5694
[flaml.automl: 12-15 02:56:01] {3166} INFO - iteration 4, current learner rf
[flaml.automl: 12-15 02:56:03] {3343} INFO -  at 9.8s,	estimator rf's best error=136.3621,	best estimator rf's best error=136.3621
[flaml.automl: 12-15 02:56:03] {3166} INFO - iteration 5, current learner rf
[flaml.automl: 12-15 02:56:05] {3343} INFO -  at 11.6s,	estimator rf's best error=136.3621,	best estimator rf's best error=136.3621
[flaml.automl: 12-15 02:56:05] {3166} INFO - iteration 6, current learner rf
[flaml.automl: 12-15 02:56:07] {3343} INFO -  at 13.3s,	estimator rf's best error=135.0428,	best estimator rf's best error=135.0428
[flaml.automl: 12-15 02:56:07] {3166} INFO - iteration 7, current learner rf
[flaml.automl: 12-15 02:56:08] {3343} INFO -  at 14.6s,	estimator rf's best error=132.3332,	best estimator rf's best error=132.3332
[flaml.automl: 12-15 02:56:08] {3166} INFO - iteration 8, current learner rf
[flaml.automl: 12-15 02:56:10] {3343} INFO -  at 16.6s,	estimator rf's best error=129.7305,	best estimator rf's best error=129.7305
[flaml.automl: 12-15 02:56:10] {3166} INFO - iteration 9, current learner rf
[flaml.automl: 12-15 02:56:12] {3343} INFO -  at 18.6s,	estimator rf's best error=129.7305,	best estimator rf's best error=129.7305
[flaml.automl: 12-15 02:56:12] {3166} INFO - iteration 10, current learner rf
[flaml.automl: 12-15 02:56:16] {3343} INFO -  at 22.8s,	estimator rf's best error=129.7305,	best estimator rf's best error=129.7305
[flaml.automl: 12-15 02:56:16] {3166} INFO - iteration 11, current learner rf
[flaml.automl: 12-15 02:56:18] {3343} INFO -  at 25.0s,	estimator rf's best error=129.7305,	best estimator rf's best error=129.7305
[flaml.automl: 12-15 02:56:18] {3166} INFO - iteration 12, current learner rf
[flaml.automl: 12-15 02:56:23] {3343} INFO -  at 29.7s,	estimator rf's best error=125.3023,	best estimator rf's best error=125.3023
[flaml.automl: 12-15 02:56:23] {3166} INFO - iteration 13, current learner rf
[flaml.automl: 12-15 02:56:26] {3343} INFO -  at 32.4s,	estimator rf's best error=125.3023,	best estimator rf's best error=125.3023
[flaml.automl: 12-15 02:56:26] {3166} INFO - iteration 14, current learner rf
[flaml.automl: 12-15 02:56:33] {3343} INFO -  at 39.6s,	estimator rf's best error=124.3001,	best estimator rf's best error=124.3001
[flaml.automl: 12-15 02:56:33] {3166} INFO - iteration 15, current learner rf
[flaml.automl: 12-15 02:56:38] {3343} INFO -  at 44.8s,	estimator rf's best error=124.3001,	best estimator rf's best error=124.3001
[flaml.automl: 12-15 02:56:38] {3166} INFO - iteration 16, current learner rf
[flaml.automl: 12-15 02:56:57] {3343} INFO -  at 63.9s,	estimator rf's best error=124.3001,	best estimator rf's best error=124.3001
[flaml.automl: 12-15 02:56:57] {3166} INFO - iteration 17, current learner rf
[flaml.automl: 12-15 02:57:13] {3343} INFO -  at 79.5s,	estimator rf's best error=122.5664,	best estimator rf's best error=122.5664
[flaml.automl: 12-15 02:57:13] {3166} INFO - iteration 18, current learner rf
[flaml.automl: 12-15 02:57:50] {3343} INFO -  at 116.4s,	estimator rf's best error=122.5664,	best estimator rf's best error=122.5664
[flaml.automl: 12-15 02:57:50] {3166} INFO - iteration 19, current learner rf
[flaml.automl: 12-15 02:57:59] {3343} INFO -  at 125.7s,	estimator rf's best error=122.5664,	best estimator rf's best error=122.5664
[flaml.automl: 12-15 02:57:59] {3166} INFO - iteration 20, current learner rf
[flaml.automl: 12-15 02:58:07] {3343} INFO -  at 133.7s,	estimator rf's best error=122.5664,	best estimator rf's best error=122.5664
[flaml.automl: 12-15 02:58:07] {3166} INFO - iteration 21, current learner rf
[flaml.automl: 12-15 02:58:42] {3343} INFO -  at 168.9s,	estimator rf's best error=121.7754,	best estimator rf's best error=121.7754
[flaml.automl: 12-15 02:58:42] {3166} INFO - iteration 22, current learner rf
[flaml.automl: 12-15 02:59:33] {3343} INFO -  at 219.3s,	estimator rf's best error=121.7754,	best estimator rf's best error=121.7754
[flaml.automl: 12-15 02:59:33] {3166} INFO - iteration 23, current learner rf
[flaml.automl: 12-15 03:00:10] {3343} INFO -  at 256.7s,	estimator rf's best error=121.7754,	best estimator rf's best error=121.7754
[flaml.automl: 12-15 03:00:10] {3166} INFO - iteration 24, current learner rf
[flaml.automl: 12-15 03:01:32] {3343} INFO -  at 338.1s,	estimator rf's best error=121.7754,	best estimator rf's best error=121.7754
[flaml.automl: 12-15 03:01:32] {3166} INFO - iteration 25, current learner rf
[flaml.automl: 12-15 03:01:50] {3343} INFO -  at 356.5s,	estimator rf's best error=121.7754,	best estimator rf's best error=121.7754
[flaml.automl: 12-15 03:01:50] {3166} INFO - iteration 26, current learner rf
[flaml.automl: 12-15 03:02:27] {3343} INFO -  at 393.5s,	estimator rf's best error=121.7754,	best estimator rf's best error=121.7754
[flaml.automl: 12-15 03:02:27] {3166} INFO - iteration 27, current learner rf
[flaml.automl: 12-15 03:03:05] {3343} INFO -  at 431.6s,	estimator rf's best error=121.7754,	best estimator rf's best error=121.7754
[flaml.automl: 12-15 03:03:05] {3166} INFO - iteration 28, current learner rf
[flaml.automl: 12-15 03:03:26] {3343} INFO -  at 453.0s,	estimator rf's best error=121.7754,	best estimator rf's best error=121.7754
[flaml.automl: 12-15 03:03:26] {3166} INFO - iteration 29, current learner rf
[flaml.automl: 12-15 03:04:35] {3343} INFO -  at 521.4s,	estimator rf's best error=121.4211,	best estimator rf's best error=121.4211
[flaml.automl: 12-15 03:04:35] {3166} INFO - iteration 30, current learner rf
[flaml.automl: 12-15 03:06:01] {3343} INFO -  at 607.3s,	estimator rf's best error=121.4211,	best estimator rf's best error=121.4211
[flaml.automl: 12-15 03:06:01] {3166} INFO - iteration 31, current learner rf
[flaml.automl: 12-15 03:07:02] {3343} INFO -  at 668.7s,	estimator rf's best error=121.4211,	best estimator rf's best error=121.4211
[flaml.automl: 12-15 03:07:02] {3166} INFO - iteration 32, current learner rf
[flaml.automl: 12-15 03:08:32] {3343} INFO -  at 758.9s,	estimator rf's best error=121.4211,	best estimator rf's best error=121.4211
[flaml.automl: 12-15 03:08:32] {3166} INFO - iteration 33, current learner rf
[flaml.automl: 12-15 03:08:57] {3343} INFO -  at 784.1s,	estimator rf's best error=121.4211,	best estimator rf's best error=121.4211
[flaml.automl: 12-15 03:08:58] {3166} INFO - iteration 34, current learner rf
[flaml.automl: 12-15 03:09:24] {3343} INFO -  at 810.4s,	estimator rf's best error=121.4211,	best estimator rf's best error=121.4211
[flaml.automl: 12-15 03:09:24] {3166} INFO - iteration 35, current learner rf
[flaml.automl: 12-15 03:12:24] {3343} INFO -  at 990.6s,	estimator rf's best error=121.4211,	best estimator rf's best error=121.4211
[flaml.automl: 12-15 03:12:24] {3166} INFO - iteration 36, current learner rf
[flaml.automl: 12-15 03:13:16] {3343} INFO -  at 1042.8s,	estimator rf's best error=121.4211,	best estimator rf's best error=121.4211

[flaml.automl: 12-15 03:13:16] {3166} INFO - iteration 37, current learner rf
[flaml.automl: 12-15 03:13:44] {3343} INFO -  at 1070.4s,	estimator rf's best error=121.4211,	best estimator rf's best error=121.4211
[flaml.automl: 12-15 03:13:44] {3166} INFO - iteration 38, current learner rf
[flaml.automl: 12-15 03:16:01] {3343} INFO -  at 1207.2s,	estimator rf's best error=121.4211,	best estimator rf's best error=121.4211
[flaml.automl: 12-15 03:16:01] {3166} INFO - iteration 39, current learner rf
[flaml.automl: 12-15 03:16:39] {3343} INFO -  at 1245.6s,	estimator rf's best error=121.4211,	best estimator rf's best error=121.4211
[flaml.automl: 12-15 03:16:39] {3166} INFO - iteration 40, current learner rf
[flaml.automl: 12-15 03:17:27] {3343} INFO -  at 1294.0s,	estimator rf's best error=121.4211,	best estimator rf's best error=121.4211
[flaml.automl: 12-15 03:17:27] {3166} INFO - iteration 41, current learner rf
[flaml.automl: 12-15 03:17:56] {3343} INFO -  at 1322.1s,	estimator rf's best error=121.4211,	best estimator rf's best error=121.4211
[flaml.automl: 12-15 03:17:56] {3166} INFO - iteration 42, current learner rf
[flaml.automl: 12-15 03:18:46] {3343} INFO -  at 1372.1s,	estimator rf's best error=121.4211,	best estimator rf's best error=121.4211
[flaml.automl: 12-15 03:19:00] {3602} INFO - retrain rf for 14.8s
[flaml.automl: 12-15 03:19:00] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.6251052493163362, max_leaf_nodes=922,
                      n_estimators=465, n_jobs=-1)
[flaml.automl: 12-15 03:19:00] {2901} INFO - fit succeeded
[flaml.automl: 12-15 03:19:00] {2902} INFO - Time taken to find the best model: 521.3559401035309
[flaml.automl: 12-15 03:19:01] {2599} INFO - task = regression
[flaml.automl: 12-15 03:19:01] {2601} INFO - Data split method: uniform
[flaml.automl: 12-15 03:19:01] {2604} INFO - Evaluation method: cv
[flaml.automl: 12-15 03:19:01] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 12-15 03:19:01] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 12-15 03:19:01] {3166} INFO - iteration 0, current learner rf
[flaml.automl: 12-15 03:19:03] {3296} INFO - Estimated sufficient time budget=17914s. Estimated necessary time budget=18s.
[flaml.automl: 12-15 03:19:03] {3343} INFO -  at 2.1s,	estimator rf's best error=155.8754,	best estimator rf's best error=155.8754
[flaml.automl: 12-15 03:19:03] {3166} INFO - iteration 1, current learner rf
[flaml.automl: 12-15 03:19:05] {3343} INFO -  at 3.8s,	estimator rf's best error=135.5362,	best estimator rf's best error=135.5362
[flaml.automl: 12-15 03:19:05] {3166} INFO - iteration 2, current learner rf
[flaml.automl: 12-15 03:19:06] {3343} INFO -  at 5.4s,	estimator rf's best error=135.5362,	best estimator rf's best error=135.5362
[flaml.automl: 12-15 03:19:06] {3166} INFO - iteration 3, current learner rf
[flaml.automl: 12-15 03:19:08] {3343} INFO -  at 7.3s,	estimator rf's best error=129.9443,	best estimator rf's best error=129.9443
[flaml.automl: 12-15 03:19:08] {3166} INFO - iteration 4, current learner rf
[flaml.automl: 12-15 03:19:10] {3343} INFO -  at 9.2s,	estimator rf's best error=125.4040,	best estimator rf's best error=125.4040
[flaml.automl: 12-15 03:19:10] {3166} INFO - iteration 5, current learner rf
[flaml.automl: 12-15 03:19:12] {3343} INFO -  at 11.1s,	estimator rf's best error=125.4040,	best estimator rf's best error=125.4040
[flaml.automl: 12-15 03:19:12] {3166} INFO - iteration 6, current learner rf
[flaml.automl: 12-15 03:19:14] {3343} INFO -  at 12.5s,	estimator rf's best error=124.5148,	best estimator rf's best error=124.5148
[flaml.automl: 12-15 03:19:14] {3166} INFO - iteration 7, current learner rf
[flaml.automl: 12-15 03:19:15] {3343} INFO -  at 14.0s,	estimator rf's best error=122.8385,	best estimator rf's best error=122.8385
[flaml.automl: 12-15 03:19:15] {3166} INFO - iteration 8, current learner rf
[flaml.automl: 12-15 03:19:18] {3343} INFO -  at 16.8s,	estimator rf's best error=122.5477,	best estimator rf's best error=122.5477
[flaml.automl: 12-15 03:19:18] {3166} INFO - iteration 9, current learner rf
[flaml.automl: 12-15 03:19:20] {3343} INFO -  at 19.3s,	estimator rf's best error=122.5477,	best estimator rf's best error=122.5477
[flaml.automl: 12-15 03:19:20] {3166} INFO - iteration 10, current learner rf
[flaml.automl: 12-15 03:19:24] {3343} INFO -  at 23.2s,	estimator rf's best error=121.6152,	best estimator rf's best error=121.6152
[flaml.automl: 12-15 03:19:24] {3166} INFO - iteration 11, current learner rf
[flaml.automl: 12-15 03:19:27] {3343} INFO -  at 26.4s,	estimator rf's best error=121.6152,	best estimator rf's best error=121.6152
[flaml.automl: 12-15 03:19:27] {3166} INFO - iteration 12, current learner rf
[flaml.automl: 12-15 03:19:36] {3343} INFO -  at 34.9s,	estimator rf's best error=116.3753,	best estimator rf's best error=116.3753
[flaml.automl: 12-15 03:19:36] {3166} INFO - iteration 13, current learner rf
[flaml.automl: 12-15 03:19:43] {3343} INFO -  at 41.8s,	estimator rf's best error=116.3753,	best estimator rf's best error=116.3753
[flaml.automl: 12-15 03:19:43] {3166} INFO - iteration 14, current learner rf
[flaml.automl: 12-15 03:19:58] {3343} INFO -  at 57.2s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:19:58] {3166} INFO - iteration 15, current learner rf
[flaml.automl: 12-15 03:20:06] {3343} INFO -  at 65.3s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:20:06] {3166} INFO - iteration 16, current learner rf
[flaml.automl: 12-15 03:20:50] {3343} INFO -  at 108.5s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:20:50] {3166} INFO - iteration 17, current learner rf
[flaml.automl: 12-15 03:21:27] {3343} INFO -  at 146.4s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:21:27] {3166} INFO - iteration 18, current learner rf
[flaml.automl: 12-15 03:21:36] {3343} INFO -  at 155.4s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:21:36] {3166} INFO - iteration 19, current learner rf
[flaml.automl: 12-15 03:22:10] {3343} INFO -  at 189.3s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:22:10] {3166} INFO - iteration 20, current learner rf
[flaml.automl: 12-15 03:22:18] {3343} INFO -  at 196.7s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:22:18] {3166} INFO - iteration 21, current learner rf
[flaml.automl: 12-15 03:22:26] {3343} INFO -  at 205.0s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:22:26] {3166} INFO - iteration 22, current learner rf
[flaml.automl: 12-15 03:23:02] {3343} INFO -  at 241.2s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:23:02] {3166} INFO - iteration 23, current learner rf
[flaml.automl: 12-15 03:23:25] {3343} INFO -  at 263.5s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:23:25] {3166} INFO - iteration 24, current learner rf
[flaml.automl: 12-15 03:23:38] {3343} INFO -  at 277.1s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:23:38] {3166} INFO - iteration 25, current learner rf
[flaml.automl: 12-15 03:24:08] {3343} INFO -  at 307.0s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:24:08] {3166} INFO - iteration 26, current learner rf
[flaml.automl: 12-15 03:24:18] {3343} INFO -  at 317.1s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:24:18] {3166} INFO - iteration 27, current learner rf
[flaml.automl: 12-15 03:24:34] {3343} INFO -  at 333.3s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:24:34] {3166} INFO - iteration 28, current learner rf
[flaml.automl: 12-15 03:24:50] {3343} INFO -  at 348.5s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659

[flaml.automl: 12-15 03:24:50] {3166} INFO - iteration 29, current learner rf
[flaml.automl: 12-15 03:25:01] {3343} INFO -  at 359.7s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:25:01] {3166} INFO - iteration 30, current learner rf
[flaml.automl: 12-15 03:25:28] {3343} INFO -  at 387.3s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:25:28] {3166} INFO - iteration 31, current learner rf
[flaml.automl: 12-15 03:25:49] {3343} INFO -  at 407.9s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:25:49] {3166} INFO - iteration 32, current learner rf
[flaml.automl: 12-15 03:26:04] {3343} INFO -  at 422.9s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:26:04] {3166} INFO - iteration 33, current learner rf
[flaml.automl: 12-15 03:26:39] {3343} INFO -  at 458.4s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:26:39] {3166} INFO - iteration 34, current learner rf
[flaml.automl: 12-15 03:26:48] {3343} INFO -  at 466.5s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:26:48] {3166} INFO - iteration 35, current learner rf
[flaml.automl: 12-15 03:26:57] {3343} INFO -  at 476.3s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:26:57] {3166} INFO - iteration 36, current learner rf
[flaml.automl: 12-15 03:27:27] {3343} INFO -  at 506.0s,	estimator rf's best error=112.8659,	best estimator rf's best error=112.8659
[flaml.automl: 12-15 03:27:27] {3166} INFO - iteration 37, current learner rf
[flaml.automl: 12-15 03:27:55] {3343} INFO -  at 533.8s,	estimator rf's best error=112.7874,	best estimator rf's best error=112.7874
[flaml.automl: 12-15 03:27:55] {3166} INFO - iteration 38, current learner rf
[flaml.automl: 12-15 03:28:11] {3343} INFO -  at 549.5s,	estimator rf's best error=112.7874,	best estimator rf's best error=112.7874
[flaml.automl: 12-15 03:28:11] {3166} INFO - iteration 39, current learner rf
[flaml.automl: 12-15 03:28:53] {3343} INFO -  at 591.9s,	estimator rf's best error=112.7874,	best estimator rf's best error=112.7874
[flaml.automl: 12-15 03:28:53] {3166} INFO - iteration 40, current learner rf
[flaml.automl: 12-15 03:29:11] {3343} INFO -  at 610.0s,	estimator rf's best error=112.7874,	best estimator rf's best error=112.7874
[flaml.automl: 12-15 03:29:11] {3166} INFO - iteration 41, current learner rf
[flaml.automl: 12-15 03:29:37] {3343} INFO -  at 635.5s,	estimator rf's best error=112.7874,	best estimator rf's best error=112.7874
[flaml.automl: 12-15 03:29:37] {3166} INFO - iteration 42, current learner rf
[flaml.automl: 12-15 03:30:13] {3343} INFO -  at 671.9s,	estimator rf's best error=112.7874,	best estimator rf's best error=112.7874
[flaml.automl: 12-15 03:30:13] {3166} INFO - iteration 43, current learner rf
[flaml.automl: 12-15 03:30:34] {3343} INFO -  at 692.8s,	estimator rf's best error=112.7874,	best estimator rf's best error=112.7874
[flaml.automl: 12-15 03:30:34] {3166} INFO - iteration 44, current learner rf
[flaml.automl: 12-15 03:31:06] {3343} INFO -  at 725.1s,	estimator rf's best error=112.7874,	best estimator rf's best error=112.7874
[flaml.automl: 12-15 03:31:06] {3166} INFO - iteration 45, current learner rf
[flaml.automl: 12-15 03:31:41] {3343} INFO -  at 759.5s,	estimator rf's best error=112.4368,	best estimator rf's best error=112.4368
[flaml.automl: 12-15 03:31:41] {3166} INFO - iteration 46, current learner rf
[flaml.automl: 12-15 03:32:08] {3343} INFO -  at 787.4s,	estimator rf's best error=112.4368,	best estimator rf's best error=112.4368
[flaml.automl: 12-15 03:32:08] {3166} INFO - iteration 47, current learner rf
[flaml.automl: 12-15 03:32:33] {3343} INFO -  at 812.1s,	estimator rf's best error=112.4368,	best estimator rf's best error=112.4368
[flaml.automl: 12-15 03:32:33] {3166} INFO - iteration 48, current learner rf
[flaml.automl: 12-15 03:34:17] {3343} INFO -  at 916.3s,	estimator rf's best error=112.4368,	best estimator rf's best error=112.4368
[flaml.automl: 12-15 03:34:17] {3166} INFO - iteration 49, current learner rf
[flaml.automl: 12-15 03:35:46] {3343} INFO -  at 1004.6s,	estimator rf's best error=112.4368,	best estimator rf's best error=112.4368
[flaml.automl: 12-15 03:35:46] {3166} INFO - iteration 50, current learner rf
[flaml.automl: 12-15 03:36:12] {3343} INFO -  at 1030.7s,	estimator rf's best error=112.4368,	best estimator rf's best error=112.4368
[flaml.automl: 12-15 03:36:12] {3166} INFO - iteration 51, current learner rf
[flaml.automl: 12-15 03:37:17] {3343} INFO -  at 1095.7s,	estimator rf's best error=112.4368,	best estimator rf's best error=112.4368
[flaml.automl: 12-15 03:37:17] {3166} INFO - iteration 52, current learner rf
[flaml.automl: 12-15 03:37:49] {3343} INFO -  at 1128.4s,	estimator rf's best error=112.4368,	best estimator rf's best error=112.4368
[flaml.automl: 12-15 03:37:49] {3166} INFO - iteration 53, current learner rf
[flaml.automl: 12-15 03:38:21] {3343} INFO -  at 1159.5s,	estimator rf's best error=112.4368,	best estimator rf's best error=112.4368
[flaml.automl: 12-15 03:38:21] {3166} INFO - iteration 54, current learner rf
[flaml.automl: 12-15 03:39:17] {3343} INFO -  at 1216.1s,	estimator rf's best error=112.4368,	best estimator rf's best error=112.4368
[flaml.automl: 12-15 03:39:17] {3166} INFO - iteration 55, current learner rf
[flaml.automl: 12-15 03:40:37] {3343} INFO -  at 1295.6s,	estimator rf's best error=112.4368,	best estimator rf's best error=112.4368
[flaml.automl: 12-15 03:40:37] {3166} INFO - iteration 56, current learner rf
[flaml.automl: 12-15 03:41:04] {3343} INFO -  at 1322.5s,	estimator rf's best error=112.4368,	best estimator rf's best error=112.4368
[flaml.automl: 12-15 03:41:04] {3166} INFO - iteration 57, current learner rf
[flaml.automl: 12-15 03:42:13] {3343} INFO -  at 1391.7s,	estimator rf's best error=112.4368,	best estimator rf's best error=112.4368
[flaml.automl: 12-15 03:42:13] {3166} INFO - iteration 58, current learner rf
[flaml.automl: 12-15 03:42:47] {3343} INFO -  at 1425.6s,	estimator rf's best error=112.4368,	best estimator rf's best error=112.4368
[flaml.automl: 12-15 03:42:53] {3602} INFO - retrain rf for 6.8s
[flaml.automl: 12-15 03:42:53] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.5516799270578389, max_leaf_nodes=543,
                      n_estimators=263, n_jobs=-1)
[flaml.automl: 12-15 03:42:53] {2901} INFO - fit succeeded
[flaml.automl: 12-15 03:42:53] {2902} INFO - Time taken to find the best model: 759.5053768157959
[flaml.automl: 12-15 03:42:54] {2599} INFO - task = regression
[flaml.automl: 12-15 03:42:54] {2601} INFO - Data split method: uniform
[flaml.automl: 12-15 03:42:54] {2604} INFO - Evaluation method: cv
[flaml.automl: 12-15 03:42:54] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 12-15 03:42:54] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 12-15 03:42:54] {3166} INFO - iteration 0, current learner rf
[flaml.automl: 12-15 03:42:55] {3296} INFO - Estimated sufficient time budget=14788s. Estimated necessary time budget=15s.
[flaml.automl: 12-15 03:42:55] {3343} INFO -  at 1.7s,	estimator rf's best error=166.1364,	best estimator rf's best error=166.1364
[flaml.automl: 12-15 03:42:55] {3166} INFO - iteration 1, current learner rf
[flaml.automl: 12-15 03:42:57] {3343} INFO -  at 3.6s,	estimator rf's best error=147.9651,	best estimator rf's best error=147.9651
[flaml.automl: 12-15 03:42:57] {3166} INFO - iteration 2, current learner rf
[flaml.automl: 12-15 03:42:59] {3343} INFO -  at 5.2s,	estimator rf's best error=147.9651,	best estimator rf's best error=147.9651
[flaml.automl: 12-15 03:42:59] {3166} INFO - iteration 3, current learner rf
[flaml.automl: 12-15 03:43:01] {3343} INFO -  at 6.9s,	estimator rf's best error=138.5697,	best estimator rf's best error=138.5697
[flaml.automl: 12-15 03:43:01] {3166} INFO - iteration 4, current learner rf
[flaml.automl: 12-15 03:43:02] {3343} INFO -  at 8.2s,	estimator rf's best error=135.6817,	best estimator rf's best error=135.6817

[flaml.automl: 12-15 03:43:02] {3166} INFO - iteration 5, current learner rf
[flaml.automl: 12-15 03:43:03] {3343} INFO -  at 9.7s,	estimator rf's best error=135.6817,	best estimator rf's best error=135.6817
[flaml.automl: 12-15 03:43:03] {3166} INFO - iteration 6, current learner rf
[flaml.automl: 12-15 03:43:05] {3343} INFO -  at 11.5s,	estimator rf's best error=132.7943,	best estimator rf's best error=132.7943
[flaml.automl: 12-15 03:43:05] {3166} INFO - iteration 7, current learner rf
[flaml.automl: 12-15 03:43:07] {3343} INFO -  at 13.4s,	estimator rf's best error=132.7943,	best estimator rf's best error=132.7943
[flaml.automl: 12-15 03:43:07] {3166} INFO - iteration 8, current learner rf
[flaml.automl: 12-15 03:43:10] {3343} INFO -  at 16.0s,	estimator rf's best error=126.5557,	best estimator rf's best error=126.5557
[flaml.automl: 12-15 03:43:10] {3166} INFO - iteration 9, current learner rf
[flaml.automl: 12-15 03:43:12] {3343} INFO -  at 18.7s,	estimator rf's best error=126.5557,	best estimator rf's best error=126.5557
[flaml.automl: 12-15 03:43:12] {3166} INFO - iteration 10, current learner rf
[flaml.automl: 12-15 03:43:14] {3343} INFO -  at 20.2s,	estimator rf's best error=126.5557,	best estimator rf's best error=126.5557
[flaml.automl: 12-15 03:43:14] {3166} INFO - iteration 11, current learner rf
[flaml.automl: 12-15 03:43:19] {3343} INFO -  at 25.0s,	estimator rf's best error=125.6076,	best estimator rf's best error=125.6076
[flaml.automl: 12-15 03:43:19] {3166} INFO - iteration 12, current learner rf
[flaml.automl: 12-15 03:43:21] {3343} INFO -  at 27.5s,	estimator rf's best error=125.6076,	best estimator rf's best error=125.6076
[flaml.automl: 12-15 03:43:21] {3166} INFO - iteration 13, current learner rf
[flaml.automl: 12-15 03:43:30] {3343} INFO -  at 36.1s,	estimator rf's best error=124.3005,	best estimator rf's best error=124.3005
[flaml.automl: 12-15 03:43:30] {3166} INFO - iteration 14, current learner rf
[flaml.automl: 12-15 03:43:35] {3343} INFO -  at 40.9s,	estimator rf's best error=124.3005,	best estimator rf's best error=124.3005
[flaml.automl: 12-15 03:43:35] {3166} INFO - iteration 15, current learner rf
[flaml.automl: 12-15 03:43:53] {3343} INFO -  at 58.8s,	estimator rf's best error=121.7652,	best estimator rf's best error=121.7652
[flaml.automl: 12-15 03:43:53] {3166} INFO - iteration 16, current learner rf
[flaml.automl: 12-15 03:44:01] {3343} INFO -  at 67.0s,	estimator rf's best error=121.7652,	best estimator rf's best error=121.7652
[flaml.automl: 12-15 03:44:01] {3166} INFO - iteration 17, current learner rf
[flaml.automl: 12-15 03:44:47] {3343} INFO -  at 113.5s,	estimator rf's best error=121.7652,	best estimator rf's best error=121.7652
[flaml.automl: 12-15 03:44:47] {3166} INFO - iteration 18, current learner rf
[flaml.automl: 12-15 03:45:24] {3343} INFO -  at 150.4s,	estimator rf's best error=121.7652,	best estimator rf's best error=121.7652
[flaml.automl: 12-15 03:45:24] {3166} INFO - iteration 19, current learner rf
[flaml.automl: 12-15 03:45:32] {3343} INFO -  at 157.8s,	estimator rf's best error=121.7652,	best estimator rf's best error=121.7652
[flaml.automl: 12-15 03:45:32] {3166} INFO - iteration 20, current learner rf
[flaml.automl: 12-15 03:46:09] {3343} INFO -  at 194.7s,	estimator rf's best error=121.7652,	best estimator rf's best error=121.7652
[flaml.automl: 12-15 03:46:09] {3166} INFO - iteration 21, current learner rf
[flaml.automl: 12-15 03:46:17] {3343} INFO -  at 203.4s,	estimator rf's best error=121.7652,	best estimator rf's best error=121.7652
[flaml.automl: 12-15 03:46:17] {3166} INFO - iteration 22, current learner rf
[flaml.automl: 12-15 03:46:25] {3343} INFO -  at 211.3s,	estimator rf's best error=121.7652,	best estimator rf's best error=121.7652
[flaml.automl: 12-15 03:46:25] {3166} INFO - iteration 23, current learner rf
[flaml.automl: 12-15 03:47:08] {3343} INFO -  at 254.1s,	estimator rf's best error=121.5577,	best estimator rf's best error=121.5577
[flaml.automl: 12-15 03:47:08] {3166} INFO - iteration 24, current learner rf
[flaml.automl: 12-15 03:47:57] {3343} INFO -  at 302.8s,	estimator rf's best error=121.5577,	best estimator rf's best error=121.5577
[flaml.automl: 12-15 03:47:57] {3166} INFO - iteration 25, current learner rf
[flaml.automl: 12-15 03:48:29] {3343} INFO -  at 335.3s,	estimator rf's best error=121.5577,	best estimator rf's best error=121.5577
[flaml.automl: 12-15 03:48:29] {3166} INFO - iteration 26, current learner rf
[flaml.automl: 12-15 03:50:18] {3343} INFO -  at 444.2s,	estimator rf's best error=121.5577,	best estimator rf's best error=121.5577
[flaml.automl: 12-15 03:50:18] {3166} INFO - iteration 27, current learner rf
[flaml.automl: 12-15 03:50:36] {3343} INFO -  at 462.3s,	estimator rf's best error=121.5577,	best estimator rf's best error=121.5577
[flaml.automl: 12-15 03:50:36] {3166} INFO - iteration 28, current learner rf
[flaml.automl: 12-15 03:51:14] {3343} INFO -  at 500.6s,	estimator rf's best error=121.5577,	best estimator rf's best error=121.5577
[flaml.automl: 12-15 03:51:14] {3166} INFO - iteration 29, current learner rf
[flaml.automl: 12-15 03:51:57] {3343} INFO -  at 543.1s,	estimator rf's best error=121.5577,	best estimator rf's best error=121.5577
[flaml.automl: 12-15 03:51:57] {3166} INFO - iteration 30, current learner rf
[flaml.automl: 12-15 03:52:15] {3343} INFO -  at 561.3s,	estimator rf's best error=121.5577,	best estimator rf's best error=121.5577
[flaml.automl: 12-15 03:52:15] {3166} INFO - iteration 31, current learner rf
[flaml.automl: 12-15 03:53:47] {3343} INFO -  at 652.8s,	estimator rf's best error=121.4679,	best estimator rf's best error=121.4679
[flaml.automl: 12-15 03:53:47] {3166} INFO - iteration 32, current learner rf
[flaml.automl: 12-15 03:55:50] {3343} INFO -  at 776.1s,	estimator rf's best error=121.4679,	best estimator rf's best error=121.4679
[flaml.automl: 12-15 03:55:50] {3166} INFO - iteration 33, current learner rf
[flaml.automl: 12-15 03:57:03] {3343} INFO -  at 848.9s,	estimator rf's best error=121.4679,	best estimator rf's best error=121.4679
[flaml.automl: 12-15 03:57:03] {3166} INFO - iteration 34, current learner rf
[flaml.automl: 12-15 04:00:37] {3343} INFO -  at 1063.5s,	estimator rf's best error=121.4679,	best estimator rf's best error=121.4679
[flaml.automl: 12-15 04:00:37] {3166} INFO - iteration 35, current learner rf
[flaml.automl: 12-15 04:01:03] {3343} INFO -  at 1089.4s,	estimator rf's best error=121.4679,	best estimator rf's best error=121.4679
[flaml.automl: 12-15 04:01:03] {3166} INFO - iteration 36, current learner rf
[flaml.automl: 12-15 04:01:31] {3343} INFO -  at 1117.0s,	estimator rf's best error=121.4679,	best estimator rf's best error=121.4679
[flaml.automl: 12-15 04:01:31] {3166} INFO - iteration 37, current learner rf
[flaml.automl: 12-15 04:05:12] {3343} INFO -  at 1338.0s,	estimator rf's best error=121.4679,	best estimator rf's best error=121.4679
[flaml.automl: 12-15 04:05:12] {3166} INFO - iteration 38, current learner rf
[flaml.automl: 12-15 04:05:35] {3343} INFO -  at 1361.1s,	estimator rf's best error=121.4679,	best estimator rf's best error=121.4679
[flaml.automl: 12-15 04:05:55] {3602} INFO - retrain rf for 19.6s
[flaml.automl: 12-15 04:05:55] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.5627639991480824, max_leaf_nodes=985,
                      n_estimators=596, n_jobs=-1)
[flaml.automl: 12-15 04:05:55] {2901} INFO - fit succeeded
[flaml.automl: 12-15 04:05:55] {2902} INFO - Time taken to find the best model: 652.7848529815674
[flaml.automl: 12-15 04:05:56] {2599} INFO - task = regression
[flaml.automl: 12-15 04:05:56] {2601} INFO - Data split method: uniform
[flaml.automl: 12-15 04:05:56] {2604} INFO - Evaluation method: cv
[flaml.automl: 12-15 04:05:56] {2726} INFO - Minimizing error metric: rmse
[flaml.automl: 12-15 04:05:56] {2870} INFO - List of ML learners in AutoML Run: ['rf']
[flaml.automl: 12-15 04:05:56] {3166} INFO - iteration 0, current learner rf
[flaml.automl: 12-15 04:05:57] {3296} INFO - Estimated sufficient time budget=16259s. Estimated necessary time budget=16s.
[flaml.automl: 12-15 04:05:57] {3343} INFO -  at 2.1s,	estimator rf's best error=166.8864,	best estimator rf's best error=166.8864

[flaml.automl: 12-15 04:05:57] {3166} INFO - iteration 1, current learner rf
[flaml.automl: 12-15 04:05:59] {3343} INFO -  at 3.5s,	estimator rf's best error=146.7174,	best estimator rf's best error=146.7174
[flaml.automl: 12-15 04:05:59] {3166} INFO - iteration 2, current learner rf
[flaml.automl: 12-15 04:06:00] {3343} INFO -  at 4.8s,	estimator rf's best error=146.7174,	best estimator rf's best error=146.7174
[flaml.automl: 12-15 04:06:00] {3166} INFO - iteration 3, current learner rf
[flaml.automl: 12-15 04:06:02] {3343} INFO -  at 6.8s,	estimator rf's best error=136.8752,	best estimator rf's best error=136.8752
[flaml.automl: 12-15 04:06:02] {3166} INFO - iteration 4, current learner rf
[flaml.automl: 12-15 04:06:04] {3343} INFO -  at 8.5s,	estimator rf's best error=134.8240,	best estimator rf's best error=134.8240
[flaml.automl: 12-15 04:06:04] {3166} INFO - iteration 5, current learner rf
[flaml.automl: 12-15 04:06:05] {3343} INFO -  at 9.9s,	estimator rf's best error=134.8240,	best estimator rf's best error=134.8240
[flaml.automl: 12-15 04:06:05] {3166} INFO - iteration 6, current learner rf
[flaml.automl: 12-15 04:06:07] {3343} INFO -  at 11.8s,	estimator rf's best error=132.8154,	best estimator rf's best error=132.8154
[flaml.automl: 12-15 04:06:07] {3166} INFO - iteration 7, current learner rf
[flaml.automl: 12-15 04:06:09] {3343} INFO -  at 14.0s,	estimator rf's best error=132.8154,	best estimator rf's best error=132.8154
[flaml.automl: 12-15 04:06:09] {3166} INFO - iteration 8, current learner rf
[flaml.automl: 12-15 04:06:12] {3343} INFO -  at 16.5s,	estimator rf's best error=126.5853,	best estimator rf's best error=126.5853
[flaml.automl: 12-15 04:06:12] {3166} INFO - iteration 9, current learner rf
[flaml.automl: 12-15 04:06:14] {3343} INFO -  at 19.2s,	estimator rf's best error=126.5853,	best estimator rf's best error=126.5853
[flaml.automl: 12-15 04:06:14] {3166} INFO - iteration 10, current learner rf
[flaml.automl: 12-15 04:06:16] {3343} INFO -  at 21.2s,	estimator rf's best error=126.5853,	best estimator rf's best error=126.5853
[flaml.automl: 12-15 04:06:16] {3166} INFO - iteration 11, current learner rf
[flaml.automl: 12-15 04:06:21] {3343} INFO -  at 26.1s,	estimator rf's best error=122.0651,	best estimator rf's best error=122.0651
[flaml.automl: 12-15 04:06:21] {3166} INFO - iteration 12, current learner rf
[flaml.automl: 12-15 04:06:23] {3343} INFO -  at 27.9s,	estimator rf's best error=122.0651,	best estimator rf's best error=122.0651
[flaml.automl: 12-15 04:06:23] {3166} INFO - iteration 13, current learner rf
[flaml.automl: 12-15 04:06:33] {3343} INFO -  at 38.2s,	estimator rf's best error=122.0651,	best estimator rf's best error=122.0651
[flaml.automl: 12-15 04:06:33] {3166} INFO - iteration 14, current learner rf
[flaml.automl: 12-15 04:06:37] {3343} INFO -  at 41.2s,	estimator rf's best error=122.0651,	best estimator rf's best error=122.0651
[flaml.automl: 12-15 04:06:37] {3166} INFO - iteration 15, current learner rf
[flaml.automl: 12-15 04:06:43] {3343} INFO -  at 48.0s,	estimator rf's best error=120.7953,	best estimator rf's best error=120.7953
[flaml.automl: 12-15 04:06:43] {3166} INFO - iteration 16, current learner rf
[flaml.automl: 12-15 04:06:47] {3343} INFO -  at 51.6s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:06:47] {3166} INFO - iteration 17, current learner rf
[flaml.automl: 12-15 04:06:53] {3343} INFO -  at 57.3s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:06:53] {3166} INFO - iteration 18, current learner rf
[flaml.automl: 12-15 04:06:55] {3343} INFO -  at 59.4s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:06:55] {3166} INFO - iteration 19, current learner rf
[flaml.automl: 12-15 04:07:02] {3343} INFO -  at 67.0s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:02] {3166} INFO - iteration 20, current learner rf
[flaml.automl: 12-15 04:07:04] {3343} INFO -  at 69.1s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:04] {3166} INFO - iteration 21, current learner rf
[flaml.automl: 12-15 04:07:07] {3343} INFO -  at 71.3s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:07] {3166} INFO - iteration 22, current learner rf
[flaml.automl: 12-15 04:07:13] {3343} INFO -  at 78.2s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:13] {3166} INFO - iteration 23, current learner rf
[flaml.automl: 12-15 04:07:17] {3343} INFO -  at 81.6s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:17] {3166} INFO - iteration 24, current learner rf
[flaml.automl: 12-15 04:07:19] {3343} INFO -  at 84.0s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:19] {3166} INFO - iteration 25, current learner rf
[flaml.automl: 12-15 04:07:26] {3343} INFO -  at 90.9s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:26] {3166} INFO - iteration 26, current learner rf
[flaml.automl: 12-15 04:07:28] {3343} INFO -  at 93.1s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:28] {3166} INFO - iteration 27, current learner rf
[flaml.automl: 12-15 04:07:33] {3343} INFO -  at 97.7s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:33] {3166} INFO - iteration 28, current learner rf
[flaml.automl: 12-15 04:07:36] {3343} INFO -  at 100.9s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:36] {3166} INFO - iteration 29, current learner rf
[flaml.automl: 12-15 04:07:38] {3343} INFO -  at 103.1s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:38] {3166} INFO - iteration 30, current learner rf
[flaml.automl: 12-15 04:07:43] {3343} INFO -  at 108.1s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:43] {3166} INFO - iteration 31, current learner rf
[flaml.automl: 12-15 04:07:46] {3343} INFO -  at 110.9s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:46] {3166} INFO - iteration 32, current learner rf
[flaml.automl: 12-15 04:07:50] {3343} INFO -  at 114.5s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:50] {3166} INFO - iteration 33, current learner rf
[flaml.automl: 12-15 04:07:57] {3343} INFO -  at 121.4s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:57] {3166} INFO - iteration 34, current learner rf
[flaml.automl: 12-15 04:07:59] {3343} INFO -  at 123.8s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:07:59] {3166} INFO - iteration 35, current learner rf
[flaml.automl: 12-15 04:08:01] {3343} INFO -  at 126.2s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:08:01] {3166} INFO - iteration 36, current learner rf
[flaml.automl: 12-15 04:08:06] {3343} INFO -  at 130.5s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:08:06] {3166} INFO - iteration 37, current learner rf
[flaml.automl: 12-15 04:08:12] {3343} INFO -  at 136.2s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:08:12] {3166} INFO - iteration 38, current learner rf
[flaml.automl: 12-15 04:08:13] {3343} INFO -  at 137.9s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:08:13] {3166} INFO - iteration 39, current learner rf
[flaml.automl: 12-15 04:08:18] {3343} INFO -  at 142.3s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:08:18] {3166} INFO - iteration 40, current learner rf

[flaml.automl: 12-15 04:08:20] {3343} INFO -  at 144.3s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:08:20] {3166} INFO - iteration 41, current learner rf
[flaml.automl: 12-15 04:08:23] {3343} INFO -  at 147.7s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:08:23] {3166} INFO - iteration 42, current learner rf
[flaml.automl: 12-15 04:08:27] {3343} INFO -  at 151.3s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:08:27] {3166} INFO - iteration 43, current learner rf
[flaml.automl: 12-15 04:08:29] {3343} INFO -  at 154.1s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:08:29] {3166} INFO - iteration 44, current learner rf
[flaml.automl: 12-15 04:08:33] {3343} INFO -  at 157.3s,	estimator rf's best error=120.0876,	best estimator rf's best error=120.0876
[flaml.automl: 12-15 04:08:33] {3166} INFO - iteration 45, current learner rf
[flaml.automl: 12-15 04:08:39] {3343} INFO -  at 163.9s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:08:39] {3166} INFO - iteration 46, current learner rf
[flaml.automl: 12-15 04:08:42] {3343} INFO -  at 167.1s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:08:42] {3166} INFO - iteration 47, current learner rf
[flaml.automl: 12-15 04:08:45] {3343} INFO -  at 169.8s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:08:45] {3166} INFO - iteration 48, current learner rf
[flaml.automl: 12-15 04:08:52] {3343} INFO -  at 177.0s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:08:52] {3166} INFO - iteration 49, current learner rf
[flaml.automl: 12-15 04:09:02] {3343} INFO -  at 186.6s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:09:02] {3166} INFO - iteration 50, current learner rf
[flaml.automl: 12-15 04:09:04] {3343} INFO -  at 189.1s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:09:04] {3166} INFO - iteration 51, current learner rf
[flaml.automl: 12-15 04:09:12] {3343} INFO -  at 196.8s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:09:12] {3166} INFO - iteration 52, current learner rf
[flaml.automl: 12-15 04:09:16] {3343} INFO -  at 200.3s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:09:16] {3166} INFO - iteration 53, current learner rf
[flaml.automl: 12-15 04:09:19] {3343} INFO -  at 204.1s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:09:19] {3166} INFO - iteration 54, current learner rf
[flaml.automl: 12-15 04:09:27] {3343} INFO -  at 211.6s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:09:27] {3166} INFO - iteration 55, current learner rf
[flaml.automl: 12-15 04:09:35] {3343} INFO -  at 219.8s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:09:35] {3166} INFO - iteration 56, current learner rf
[flaml.automl: 12-15 04:09:40] {3343} INFO -  at 224.5s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:09:40] {3166} INFO - iteration 57, current learner rf
[flaml.automl: 12-15 04:09:48] {3343} INFO -  at 232.2s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:09:48] {3166} INFO - iteration 58, current learner rf
[flaml.automl: 12-15 04:09:51] {3343} INFO -  at 236.1s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:09:51] {3166} INFO - iteration 59, current learner rf
[flaml.automl: 12-15 04:09:55] {3343} INFO -  at 240.0s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:09:55] {3166} INFO - iteration 60, current learner rf
[flaml.automl: 12-15 04:10:02] {3343} INFO -  at 246.5s,	estimator rf's best error=119.7191,	best estimator rf's best error=119.7191
[flaml.automl: 12-15 04:10:02] {3166} INFO - iteration 61, current learner rf
[flaml.automl: 12-15 04:10:12] {3343} INFO -  at 256.8s,	estimator rf's best error=119.5183,	best estimator rf's best error=119.5183
[flaml.automl: 12-15 04:10:12] {3166} INFO - iteration 62, current learner rf
[flaml.automl: 12-15 04:10:18] {3343} INFO -  at 262.6s,	estimator rf's best error=119.5183,	best estimator rf's best error=119.5183
[flaml.automl: 12-15 04:10:18] {3166} INFO - iteration 63, current learner rf
[flaml.automl: 12-15 04:10:26] {3343} INFO -  at 270.5s,	estimator rf's best error=119.5183,	best estimator rf's best error=119.5183
[flaml.automl: 12-15 04:10:26] {3166} INFO - iteration 64, current learner rf
[flaml.automl: 12-15 04:10:36] {3343} INFO -  at 280.4s,	estimator rf's best error=119.5183,	best estimator rf's best error=119.5183
[flaml.automl: 12-15 04:10:36] {3166} INFO - iteration 65, current learner rf
[flaml.automl: 12-15 04:10:43] {3343} INFO -  at 287.9s,	estimator rf's best error=119.5183,	best estimator rf's best error=119.5183
[flaml.automl: 12-15 04:10:43] {3166} INFO - iteration 66, current learner rf
[flaml.automl: 12-15 04:10:57] {3343} INFO -  at 301.5s,	estimator rf's best error=119.5183,	best estimator rf's best error=119.5183
[flaml.automl: 12-15 04:10:57] {3166} INFO - iteration 67, current learner rf
[flaml.automl: 12-15 04:11:03] {3343} INFO -  at 307.6s,	estimator rf's best error=119.5183,	best estimator rf's best error=119.5183
[flaml.automl: 12-15 04:11:03] {3166} INFO - iteration 68, current learner rf
[flaml.automl: 12-15 04:11:15] {3343} INFO -  at 320.0s,	estimator rf's best error=119.5183,	best estimator rf's best error=119.5183
[flaml.automl: 12-15 04:11:15] {3166} INFO - iteration 69, current learner rf
[flaml.automl: 12-15 04:11:28] {3343} INFO -  at 332.2s,	estimator rf's best error=119.5183,	best estimator rf's best error=119.5183
[flaml.automl: 12-15 04:11:28] {3166} INFO - iteration 70, current learner rf
[flaml.automl: 12-15 04:11:35] {3343} INFO -  at 339.7s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:11:35] {3166} INFO - iteration 71, current learner rf
[flaml.automl: 12-15 04:11:40] {3343} INFO -  at 344.3s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:11:40] {3166} INFO - iteration 72, current learner rf
[flaml.automl: 12-15 04:11:50] {3343} INFO -  at 355.2s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:11:50] {3166} INFO - iteration 73, current learner rf
[flaml.automl: 12-15 04:11:59] {3343} INFO -  at 363.6s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:11:59] {3166} INFO - iteration 74, current learner rf
[flaml.automl: 12-15 04:12:08] {3343} INFO -  at 372.9s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:12:08] {3166} INFO - iteration 75, current learner rf
[flaml.automl: 12-15 04:12:15] {3343} INFO -  at 379.5s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:12:15] {3166} INFO - iteration 76, current learner rf
[flaml.automl: 12-15 04:12:22] {3343} INFO -  at 386.6s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:12:22] {3166} INFO - iteration 77, current learner rf
[flaml.automl: 12-15 04:12:28] {3343} INFO -  at 392.9s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:12:28] {3166} INFO - iteration 78, current learner rf
[flaml.automl: 12-15 04:12:37] {3343} INFO -  at 402.2s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:12:37] {3166} INFO - iteration 79, current learner rf

[flaml.automl: 12-15 04:12:44] {3343} INFO -  at 408.7s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:12:44] {3166} INFO - iteration 80, current learner rf
[flaml.automl: 12-15 04:12:55] {3343} INFO -  at 419.5s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:12:55] {3166} INFO - iteration 81, current learner rf
[flaml.automl: 12-15 04:13:01] {3343} INFO -  at 426.1s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:13:01] {3166} INFO - iteration 82, current learner rf
[flaml.automl: 12-15 04:13:08] {3343} INFO -  at 432.4s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:13:08] {3166} INFO - iteration 83, current learner rf
[flaml.automl: 12-15 04:13:12] {3343} INFO -  at 436.9s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:13:12] {3166} INFO - iteration 84, current learner rf
[flaml.automl: 12-15 04:13:27] {3343} INFO -  at 451.2s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:13:27] {3166} INFO - iteration 85, current learner rf
[flaml.automl: 12-15 04:13:37] {3343} INFO -  at 462.1s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:13:37] {3166} INFO - iteration 86, current learner rf
[flaml.automl: 12-15 04:13:43] {3343} INFO -  at 467.8s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:13:43] {3166} INFO - iteration 87, current learner rf
[flaml.automl: 12-15 04:13:48] {3343} INFO -  at 472.7s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:13:48] {3166} INFO - iteration 88, current learner rf
[flaml.automl: 12-15 04:13:59] {3343} INFO -  at 483.9s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:13:59] {3166} INFO - iteration 89, current learner rf
[flaml.automl: 12-15 04:14:09] {3343} INFO -  at 493.6s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:14:09] {3166} INFO - iteration 90, current learner rf
[flaml.automl: 12-15 04:14:15] {3343} INFO -  at 499.8s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:14:15] {3166} INFO - iteration 91, current learner rf
[flaml.automl: 12-15 04:14:22] {3343} INFO -  at 506.8s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:14:22] {3166} INFO - iteration 92, current learner rf
[flaml.automl: 12-15 04:14:30] {3343} INFO -  at 514.5s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:14:30] {3166} INFO - iteration 93, current learner rf
[flaml.automl: 12-15 04:14:36] {3343} INFO -  at 521.0s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:14:36] {3166} INFO - iteration 94, current learner rf
[flaml.automl: 12-15 04:14:46] {3343} INFO -  at 530.6s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:14:46] {3166} INFO - iteration 95, current learner rf
[flaml.automl: 12-15 04:14:56] {3343} INFO -  at 540.8s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:14:56] {3166} INFO - iteration 96, current learner rf
[flaml.automl: 12-15 04:15:01] {3343} INFO -  at 546.0s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:15:01] {3166} INFO - iteration 97, current learner rf
[flaml.automl: 12-15 04:15:06] {3343} INFO -  at 551.0s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:15:06] {3166} INFO - iteration 98, current learner rf
[flaml.automl: 12-15 04:15:16] {3343} INFO -  at 560.4s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:15:16] {3166} INFO - iteration 99, current learner rf
[flaml.automl: 12-15 04:15:22] {3343} INFO -  at 566.9s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:15:22] {3166} INFO - iteration 100, current learner rf
[flaml.automl: 12-15 04:15:32] {3343} INFO -  at 577.0s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:15:32] {3166} INFO - iteration 101, current learner rf
[flaml.automl: 12-15 04:15:44] {3343} INFO -  at 588.6s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:15:44] {3166} INFO - iteration 102, current learner rf
[flaml.automl: 12-15 04:15:48] {3343} INFO -  at 592.8s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:15:48] {3166} INFO - iteration 103, current learner rf
[flaml.automl: 12-15 04:15:58] {3343} INFO -  at 602.7s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:15:58] {3166} INFO - iteration 104, current learner rf
[flaml.automl: 12-15 04:16:05] {3343} INFO -  at 609.3s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:16:05] {3166} INFO - iteration 105, current learner rf
[flaml.automl: 12-15 04:16:10] {3343} INFO -  at 614.3s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:16:10] {3166} INFO - iteration 106, current learner rf
[flaml.automl: 12-15 04:16:21] {3343} INFO -  at 626.0s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:16:21] {3166} INFO - iteration 107, current learner rf
[flaml.automl: 12-15 04:16:27] {3343} INFO -  at 631.3s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:16:27] {3166} INFO - iteration 108, current learner rf
[flaml.automl: 12-15 04:16:35] {3343} INFO -  at 639.5s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:16:35] {3166} INFO - iteration 109, current learner rf
[flaml.automl: 12-15 04:16:41] {3343} INFO -  at 645.8s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:16:41] {3166} INFO - iteration 110, current learner rf
[flaml.automl: 12-15 04:16:51] {3343} INFO -  at 655.8s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:16:51] {3166} INFO - iteration 111, current learner rf
[flaml.automl: 12-15 04:17:01] {3343} INFO -  at 665.2s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:17:01] {3166} INFO - iteration 112, current learner rf
[flaml.automl: 12-15 04:17:06] {3343} INFO -  at 670.6s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:17:06] {3166} INFO - iteration 113, current learner rf
[flaml.automl: 12-15 04:17:11] {3343} INFO -  at 676.2s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:17:11] {3166} INFO - iteration 114, current learner rf
[flaml.automl: 12-15 04:17:18] {3343} INFO -  at 682.8s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:17:18] {3166} INFO - iteration 115, current learner rf
[flaml.automl: 12-15 04:17:24] {3343} INFO -  at 688.7s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:17:24] {3166} INFO - iteration 116, current learner rf
[flaml.automl: 12-15 04:17:35] {3343} INFO -  at 700.2s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:17:35] {3166} INFO - iteration 117, current learner rf
[flaml.automl: 12-15 04:17:40] {3343} INFO -  at 704.9s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:17:40] {3166} INFO - iteration 118, current learner rf

[flaml.automl: 12-15 04:17:51] {3343} INFO -  at 715.7s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:17:51] {3166} INFO - iteration 119, current learner rf
[flaml.automl: 12-15 04:17:56] {3343} INFO -  at 720.6s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:17:56] {3166} INFO - iteration 120, current learner rf
[flaml.automl: 12-15 04:18:08] {3343} INFO -  at 732.6s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:18:08] {3166} INFO - iteration 121, current learner rf
[flaml.automl: 12-15 04:18:18] {3343} INFO -  at 742.4s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:18:18] {3166} INFO - iteration 122, current learner rf
[flaml.automl: 12-15 04:18:25] {3343} INFO -  at 749.4s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:18:25] {3166} INFO - iteration 123, current learner rf
[flaml.automl: 12-15 04:18:33] {3343} INFO -  at 757.6s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:18:33] {3166} INFO - iteration 124, current learner rf
[flaml.automl: 12-15 04:18:38] {3343} INFO -  at 762.4s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:18:38] {3166} INFO - iteration 125, current learner rf
[flaml.automl: 12-15 04:18:46] {3343} INFO -  at 770.2s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:18:46] {3166} INFO - iteration 126, current learner rf
[flaml.automl: 12-15 04:18:52] {3343} INFO -  at 776.8s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:18:52] {3166} INFO - iteration 127, current learner rf
[flaml.automl: 12-15 04:18:57] {3343} INFO -  at 781.8s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:18:57] {3166} INFO - iteration 128, current learner rf
[flaml.automl: 12-15 04:19:08] {3343} INFO -  at 793.0s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:19:08] {3166} INFO - iteration 129, current learner rf
[flaml.automl: 12-15 04:19:18] {3343} INFO -  at 802.4s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:19:18] {3166} INFO - iteration 130, current learner rf
[flaml.automl: 12-15 04:19:23] {3343} INFO -  at 807.6s,	estimator rf's best error=119.1899,	best estimator rf's best error=119.1899
[flaml.automl: 12-15 04:19:23] {3166} INFO - iteration 131, current learner rf
[flaml.automl: 12-15 04:19:33] {3343} INFO -  at 817.3s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:19:33] {3166} INFO - iteration 132, current learner rf
[flaml.automl: 12-15 04:19:40] {3343} INFO -  at 824.9s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:19:40] {3166} INFO - iteration 133, current learner rf
[flaml.automl: 12-15 04:19:50] {3343} INFO -  at 834.5s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:19:50] {3166} INFO - iteration 134, current learner rf
[flaml.automl: 12-15 04:20:04] {3343} INFO -  at 848.8s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:20:04] {3166} INFO - iteration 135, current learner rf
[flaml.automl: 12-15 04:20:11] {3343} INFO -  at 855.9s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:20:11] {3166} INFO - iteration 136, current learner rf
[flaml.automl: 12-15 04:20:19] {3343} INFO -  at 863.4s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:20:19] {3166} INFO - iteration 137, current learner rf
[flaml.automl: 12-15 04:20:29] {3343} INFO -  at 873.7s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:20:29] {3166} INFO - iteration 138, current learner rf
[flaml.automl: 12-15 04:20:41] {3343} INFO -  at 885.7s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:20:41] {3166} INFO - iteration 139, current learner rf
[flaml.automl: 12-15 04:20:48] {3343} INFO -  at 892.5s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:20:48] {3166} INFO - iteration 140, current learner rf
[flaml.automl: 12-15 04:20:59] {3343} INFO -  at 903.9s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:20:59] {3166} INFO - iteration 141, current learner rf
[flaml.automl: 12-15 04:21:07] {3343} INFO -  at 911.6s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:21:07] {3166} INFO - iteration 142, current learner rf
[flaml.automl: 12-15 04:21:18] {3343} INFO -  at 922.2s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:21:18] {3166} INFO - iteration 143, current learner rf
[flaml.automl: 12-15 04:21:26] {3343} INFO -  at 930.7s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:21:26] {3166} INFO - iteration 144, current learner rf
[flaml.automl: 12-15 04:21:36] {3343} INFO -  at 941.1s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:21:36] {3166} INFO - iteration 145, current learner rf
[flaml.automl: 12-15 04:21:45] {3343} INFO -  at 949.6s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:21:45] {3166} INFO - iteration 146, current learner rf
[flaml.automl: 12-15 04:21:55] {3343} INFO -  at 959.3s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:21:55] {3166} INFO - iteration 147, current learner rf
[flaml.automl: 12-15 04:22:05] {3343} INFO -  at 969.4s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:22:05] {3166} INFO - iteration 148, current learner rf
[flaml.automl: 12-15 04:22:18] {3343} INFO -  at 982.8s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:22:18] {3166} INFO - iteration 149, current learner rf
[flaml.automl: 12-15 04:22:24] {3343} INFO -  at 988.8s,	estimator rf's best error=119.1115,	best estimator rf's best error=119.1115
[flaml.automl: 12-15 04:22:24] {3166} INFO - iteration 150, current learner rf
[flaml.automl: 12-15 04:22:33] {3343} INFO -  at 997.3s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:22:33] {3166} INFO - iteration 151, current learner rf
[flaml.automl: 12-15 04:22:41] {3343} INFO -  at 1006.0s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:22:41] {3166} INFO - iteration 152, current learner rf
[flaml.automl: 12-15 04:22:51] {3343} INFO -  at 1015.5s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:22:51] {3166} INFO - iteration 153, current learner rf
[flaml.automl: 12-15 04:22:59] {3343} INFO -  at 1023.3s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:22:59] {3166} INFO - iteration 154, current learner rf
[flaml.automl: 12-15 04:23:09] {3343} INFO -  at 1033.8s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:23:09] {3166} INFO - iteration 155, current learner rf
[flaml.automl: 12-15 04:23:15] {3343} INFO -  at 1039.5s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:23:15] {3166} INFO - iteration 156, current learner rf
[flaml.automl: 12-15 04:23:23] {3343} INFO -  at 1048.0s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405

[flaml.automl: 12-15 04:23:23] {3166} INFO - iteration 157, current learner rf
[flaml.automl: 12-15 04:23:32] {3343} INFO -  at 1056.5s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:23:32] {3166} INFO - iteration 158, current learner rf
[flaml.automl: 12-15 04:23:45] {3343} INFO -  at 1070.1s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:23:45] {3166} INFO - iteration 159, current learner rf
[flaml.automl: 12-15 04:23:52] {3343} INFO -  at 1076.5s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:23:52] {3166} INFO - iteration 160, current learner rf
[flaml.automl: 12-15 04:24:00] {3343} INFO -  at 1085.0s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:24:00] {3166} INFO - iteration 161, current learner rf
[flaml.automl: 12-15 04:24:09] {3343} INFO -  at 1093.5s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:24:09] {3166} INFO - iteration 162, current learner rf
[flaml.automl: 12-15 04:24:18] {3343} INFO -  at 1102.8s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:24:18] {3166} INFO - iteration 163, current learner rf
[flaml.automl: 12-15 04:24:24] {3343} INFO -  at 1108.6s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:24:24] {3166} INFO - iteration 164, current learner rf
[flaml.automl: 12-15 04:24:35] {3343} INFO -  at 1119.7s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:24:35] {3166} INFO - iteration 165, current learner rf
[flaml.automl: 12-15 04:24:41] {3343} INFO -  at 1125.8s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:24:41] {3166} INFO - iteration 166, current learner rf
[flaml.automl: 12-15 04:24:50] {3343} INFO -  at 1134.7s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:24:50] {3166} INFO - iteration 167, current learner rf
[flaml.automl: 12-15 04:24:57] {3343} INFO -  at 1142.1s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:24:57] {3166} INFO - iteration 168, current learner rf
[flaml.automl: 12-15 04:25:04] {3343} INFO -  at 1148.3s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:25:04] {3166} INFO - iteration 169, current learner rf
[flaml.automl: 12-15 04:25:15] {3343} INFO -  at 1160.0s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:25:15] {3166} INFO - iteration 170, current learner rf
[flaml.automl: 12-15 04:25:22] {3343} INFO -  at 1167.0s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:25:22] {3166} INFO - iteration 171, current learner rf
[flaml.automl: 12-15 04:25:31] {3343} INFO -  at 1176.1s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:25:31] {3166} INFO - iteration 172, current learner rf
[flaml.automl: 12-15 04:25:38] {3343} INFO -  at 1182.7s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:25:38] {3166} INFO - iteration 173, current learner rf
[flaml.automl: 12-15 04:25:48] {3343} INFO -  at 1193.0s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:25:48] {3166} INFO - iteration 174, current learner rf
[flaml.automl: 12-15 04:25:55] {3343} INFO -  at 1199.3s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:25:55] {3166} INFO - iteration 175, current learner rf
[flaml.automl: 12-15 04:26:03] {3343} INFO -  at 1207.8s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:26:03] {3166} INFO - iteration 176, current learner rf
[flaml.automl: 12-15 04:26:10] {3343} INFO -  at 1214.5s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:26:10] {3166} INFO - iteration 177, current learner rf
[flaml.automl: 12-15 04:26:21] {3343} INFO -  at 1225.2s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:26:21] {3166} INFO - iteration 178, current learner rf
[flaml.automl: 12-15 04:26:31] {3343} INFO -  at 1236.1s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:26:31] {3166} INFO - iteration 179, current learner rf
[flaml.automl: 12-15 04:26:37] {3343} INFO -  at 1241.9s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:26:37] {3166} INFO - iteration 180, current learner rf
[flaml.automl: 12-15 04:26:46] {3343} INFO -  at 1250.7s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:26:46] {3166} INFO - iteration 181, current learner rf
[flaml.automl: 12-15 04:26:55] {3343} INFO -  at 1259.9s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:26:55] {3166} INFO - iteration 182, current learner rf
[flaml.automl: 12-15 04:27:05] {3343} INFO -  at 1269.3s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:27:05] {3166} INFO - iteration 183, current learner rf
[flaml.automl: 12-15 04:27:12] {3343} INFO -  at 1276.6s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:27:12] {3166} INFO - iteration 184, current learner rf
[flaml.automl: 12-15 04:27:22] {3343} INFO -  at 1286.8s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:27:22] {3166} INFO - iteration 185, current learner rf
[flaml.automl: 12-15 04:27:28] {3343} INFO -  at 1292.5s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:27:28] {3166} INFO - iteration 186, current learner rf
[flaml.automl: 12-15 04:27:37] {3343} INFO -  at 1302.0s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:27:37] {3166} INFO - iteration 187, current learner rf
[flaml.automl: 12-15 04:27:45] {3343} INFO -  at 1309.4s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:27:45] {3166} INFO - iteration 188, current learner rf
[flaml.automl: 12-15 04:27:52] {3343} INFO -  at 1316.3s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:27:52] {3166} INFO - iteration 189, current learner rf
[flaml.automl: 12-15 04:28:02] {3343} INFO -  at 1326.7s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:28:02] {3166} INFO - iteration 190, current learner rf
[flaml.automl: 12-15 04:28:08] {3343} INFO -  at 1332.8s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:28:08] {3166} INFO - iteration 191, current learner rf
[flaml.automl: 12-15 04:28:21] {3343} INFO -  at 1345.8s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:28:21] {3166} INFO - iteration 192, current learner rf
[flaml.automl: 12-15 04:28:32] {3343} INFO -  at 1356.3s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:28:32] {3166} INFO - iteration 193, current learner rf
[flaml.automl: 12-15 04:28:39] {3343} INFO -  at 1363.5s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:28:39] {3166} INFO - iteration 194, current learner rf
[flaml.automl: 12-15 04:28:50] {3343} INFO -  at 1374.8s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:28:50] {3166} INFO - iteration 195, current learner rf
[flaml.automl: 12-15 04:28:56] {3343} INFO -  at 1381.0s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405

[flaml.automl: 12-15 04:28:56] {3166} INFO - iteration 196, current learner rf
[flaml.automl: 12-15 04:29:04] {3343} INFO -  at 1388.6s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:29:04] {3166} INFO - iteration 197, current learner rf
[flaml.automl: 12-15 04:29:11] {3343} INFO -  at 1395.6s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:29:11] {3166} INFO - iteration 198, current learner rf
[flaml.automl: 12-15 04:29:16] {3343} INFO -  at 1400.4s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:29:16] {3166} INFO - iteration 199, current learner rf
[flaml.automl: 12-15 04:29:25] {3343} INFO -  at 1410.0s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:29:25] {3166} INFO - iteration 200, current learner rf
[flaml.automl: 12-15 04:29:31] {3343} INFO -  at 1415.2s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:29:31] {3166} INFO - iteration 201, current learner rf
[flaml.automl: 12-15 04:29:41] {3343} INFO -  at 1426.1s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:29:41] {3166} INFO - iteration 202, current learner rf
[flaml.automl: 12-15 04:29:50] {3343} INFO -  at 1434.6s,	estimator rf's best error=119.0405,	best estimator rf's best error=119.0405
[flaml.automl: 12-15 04:29:52] {3602} INFO - retrain rf for 2.3s
[flaml.automl: 12-15 04:29:52] {3609} INFO - retrained model: RandomForestRegressor(max_features=0.5495236489129532, max_leaf_nodes=677,
                      n_estimators=59, n_jobs=-1)
[flaml.automl: 12-15 04:29:52] {2901} INFO - fit succeeded
[flaml.automl: 12-15 04:29:52] {2902} INFO - Time taken to find the best model: 997.3021621704102

0.93 0.86 0.3

# Initialize an AutoML instance
automl = AutoML()
# Specify automl goal and constraint
automl_settings = {
    "time_budget": 180,  # in seconds
    "metric": 'rmse',
    "task": 'regression',
    "log_file_name": "california.log",
}

Pred=[]
rmse=[]
model=[]
for i in range(20):
    X_Train, X_Test, y_Train, y_Test =train_test_split(X_train,y_train,test_size = 0.2,shuffle=True)
    # Train with labeled input data
    automl.fit(X_train=X_Train.drop(['Lab1'], axis=1), y_train=y_Train,**automl_settings,estimator_list=["xgboost"])
    pred=automl.predict(X_test.drop(['Lab1'], axis=1))
    R2=round(sm.r2_score(y_test, pred), 2)
    r=round(np.corrcoef(y_test, pred)[0, 1],2)
    RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),5)
    print(r,R2,RMSE)
    # Predict
    #print(automl.predict(X_test))
    # Print the best model
    print(automl.model.estimator)
    Pred.append(pred)
    rmse.append(RMSE)
    model.append(automl.model.estimator)

Sorted_pred=[]
sort_index = np.argsort(rmse)
for i in sort_index:
    Sorted_pred.append(Pred[i])
ind=[i for i in range(len(y_test))]
import matplotlib.pyplot as plt
fig= plt.figure(figsize=(7,5))
plt.plot(ind[:200],y_test[:200], color='blue',linewidth=1.5)
plt.plot(ind[:200],Sorted_pred[1][:200],color='salmon',linewidth=1.5)
plt.plot(ind[:200],Sorted_pred[17][:200],color='teal',linewidth=1.5)
plt.legend(['Actual','p10','p90'],loc = 2, bbox_to_anchor = (0.75,1), fontsize=12)
#plt.plot(ind[:200],Sorted_pred[4][:200],color='black',linewidth=0.2)
#plt.fill_between(np.array(ind[:200]), np.array(Sorted_pred[0][:200]), np.array(Sorted_pred[4][:200]), 
                 #color='blue', alpha=0.15)
#plt.plot(ind,Pred[2],color='darkgoldenrod')
#plt.plot(ind,Pred[3],color='magenta')
#plt.plot(ind,Pred[4],color='purple')
plt.xlabel('Observation number',fontsize=16)
plt.ylabel('Concentraton (ppb)',fontsize=16)
plt.title('CO-XGBoost',fontsize=16)
plt.savefig("co_xgboost.pdf", format="pdf", bbox_inches="tight")

In [ ]:
from flaml import AutoML
from sklearn.datasets import fetch_california_housing

# Initialize an AutoML instance
automl = AutoML()
# Specify automl goal and constraint
automl_settings = {
    "time_budget": 21600,  # in seconds
    "metric": 'rmse',
    "task": 'regression',
    "log_file_name": "california.log",
}
# Train with labeled input data
automl.fit(X_train=X_train.drop(['Lab1'], axis=1), y_train=y_train,**automl_settings,estimator_list=["xgboost"])#,estimator_list=["xgboost"]
pred=automl.predict(X_test.drop(['Lab1'], axis=1))
R2=round(sm.r2_score(y_test, pred), 2)
r=round(np.corrcoef(y_test, pred)[0, 1],2)
RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),2)
print(r,R2,RMSE)
# Predict
#print(automl.predict(X_test))
# Print the best model
print(automl.model.estimator)

from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
  
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel':  ['rbf']} 
  
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
grid.fit(X_train.drop(['Lab1'], axis=1), y_train)

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

from flaml.model import SKLearnEstimator

from flaml.model import SKLearnEstimator
# SKLearnEstimator is derived from BaseEstimator
import numpy as np

class RandomForestRegressor(SKLearnEstimator):
    def __init__(self, task="binary", **config):
        super().__init__(task, **config)

        if task in CLASSIFICATION:
            from sklearn.ensemble import RandomForestClassifier

            self.estimator_class =RandomForestClassifier 
        else:
            from sklearn.ensemble import RandomForestRegressor

            self.estimator_class =RandomForestRegressor

    @classmethod
    def search_space(cls, data_size, task):
        space = {
            "n_estimators": {
                "domain": {"domain": tune.loguniform(lower=100, upper=20000)},
                "low_cost_init_value": 100,
            },
            "max_features": {
                "domain": tune.loguniform(lower=0.1, upper=1),
                "low_cost_init_value": 0.1,
            },
            "max_leaf_nodes": {
                "domain": tune.lograndint(lower=100, upper=2500),
                "low_cost_init_value": 100,},
            "min_samples_split": {"domain": tune.lograndint(lower=1, upper=20),
            "init_value": 20,},
            
            "min_samples_leaf": {
                "domain": tune.lograndint(lower=1, upper=20),
                "init_value": 20,
            },
        }
        return space

from flaml import AutoML
from flaml import tune
automl = AutoML()
automl.add_learner("rfr",RandomForestRegressor )

automl_settings = {
    "time_budget": 1000,  # in seconds
    "metric": 'rmse',
    "task": 'regression',
    "log_file_name": "california.log",
}
# Train with labeled input data
automl.fit(X_train=X_train.drop(['Lab1'], axis=1), y_train=y_train,**automl_settings,estimator_list=["rfr"])
pred=automl.predict(X_test.drop(['Lab1'], axis=1))
R2=round(sm.r2_score(y_test, pred), 2)
r=round(np.corrcoef(y_test, pred)[0, 1],2)
RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),2)
print(r,R2,RMSE)

#  NO2 DATA

In [8]:
X=NO2_Data[['Net Signal','Lab1','Temp','RH','Month','Day_of_week','Hour','Ref_O3']]#'Ref_O3'
y=NO2_Data['Ref']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
#len(X_test)
X.shape

(3778, 8)

from flaml import AutoML
from sklearn.datasets import fetch_california_housing

# Initialize an AutoML instance
automl = AutoML()
# Specify automl goal and constraint
automl_settings = {
    "time_budget": 200,  # in seconds
    "metric": 'rmse',
    "task": 'regression',
    "log_file_name": "california.log",
}
# Train with labeled input data
automl.fit(X_train=X_train.drop(['Lab1'], axis=1), y_train=y_train,**automl_settings,estimator_list=["xgboost"])
pred=automl.predict(X_test.drop(['Lab1'], axis=1))
R2=round(sm.r2_score(y_test, pred), 2)
r=round(np.corrcoef(y_test, pred)[0, 1],2)
RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),2)
print(r,R2,RMSE)
# Predict
#print(automl.predict(X_test))
# Print the best model
print(automl.model.estimator)

from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
  
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel':  ['rbf', 'poly', 'sigmoid']} 
  
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
grid.fit(X_train.drop(['Lab1'], axis=1), y_train)

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

# O3 DATA

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error as mae
import sklearn.metrics as sm
import matplotlib.pyplot as plt
#,'Ref_CO','Ref_NO2','Ref_SO2'
X=O3_Data[['Net Signal','Lab1','Temp','RH','Month','Day_of_week','Hour','Ref_NO2']]#,'Ref_NO2'
y=O3_Data['Ref']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
len(X)

3534

from flaml import AutoML
from sklearn.datasets import fetch_california_housing

# Initialize an AutoML instance
automl = AutoML()
# Specify automl goal and constraint
automl_settings = {
    "time_budget": 200,  # in seconds
    "metric": 'rmse',
    "task": 'regression',
    "log_file_name": "california.log",
}
# Train with labeled input data
automl.fit(X_train=X_train.drop(['Lab1'], axis=1), y_train=y_train,**automl_settings,estimator_list=["xgboost"])
pred=automl.predict(X_test.drop(['Lab1'], axis=1))
R2=round(sm.r2_score(y_test, pred), 2)
r=round(np.corrcoef(y_test, pred)[0, 1],2)
RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),2)
print(r,R2,RMSE)
# Predict
#print(automl.predict(X_test))
# Print the best model
print(automl.model.estimator)

from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
  
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel':  ['rbf', 'poly', 'sigmoid']} 
  
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
grid.fit(X_train.drop(['Lab1'], axis=1), y_train)

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

# SO2 DATA

In [10]:
import pandas as pd
Ref=pd.read_csv('Ref.csv')
Ref["CO"] = 1000 * Ref["CO"]
Ref['Date'] = pd.to_datetime(Ref['Date_Time'])
Ref=Ref.set_index('Date')
Ref.drop('Date_Time',axis = 1, inplace = True)
Ref=Ref.resample('5min').mean()
Ref=Ref[76463:137376]
Ref_CO=Ref['CO'].to_list()
Ref_NO2=Ref['NO2'].to_list()
Ref_SO2=Ref['SO2'].to_list()
Ref_O3=Ref['O3'].to_list()

In [11]:
import pandas as pd
import scipy.io
import numpy as np
data = pd.read_csv('Conc_SO2.txt', header = None,low_memory=False)
data.columns=['Lab2','Temp','RH','Time','Ref']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_SO2=data
Data_so2=data
#signal=np.array(WE)-np.array(AE)
#Data_SO2['Net Signal']=signal
Data_SO2['Month']=Data_SO2.index.month
Data_SO2['Day_of_week']=Data_SO2.index.dayofweek
Data_SO2['Day']=Data_SO2.index.day
Data_SO2['Hour']=Data_SO2.index.hour
SO2_Data=Data_SO2
SO2_Data=SO2_Data.resample('5min').mean()
SO2_Data=SO2_Data[(SO2_Data[SO2_Data.columns] >= 0).all(axis=1)]
SO2_Data=SO2_Data.dropna() 
data = pd.read_csv('SO2.txt', header = None,low_memory=False)
data.columns=['WE','AE','Temp','RH','Time']
Time=data['Time'].to_list()
time=[]
for i in range(len(Time)):
    time.append(float(abs(Time[i])))
Time=np.array(time)
Date=pd.to_datetime(Time-719529,unit='d').round('s')
data['Date'] = Date.tolist()
data=data.set_index('Date')
data.drop('Time',axis = 1, inplace = True)
data=data.resample('5min').mean()
Data_SO2=data
Data_SO2['Ref']=Ref_SO2
WE=Data_SO2['WE'].to_list()
AE=Data_SO2['AE'].to_list()
signal=np.array(WE)-np.array(AE)
Data_SO2['Lab2']=Data_so2['Lab2'].to_list()
Data_SO2['Net Signal']=signal
Data_SO2['Month']=Data_SO2.index.month
Data_SO2['Day_of_week']=Data_SO2.index.dayofweek
Data_SO2['Day']=Data_SO2.index.day
Data_SO2['Hour']=Data_SO2.index.hour
SO2_Data=Data_SO2
SO2_Data.shape

(60913, 11)

In [12]:
SO2_Data=SO2_Data[(SO2_Data[SO2_Data.columns] >= 0).all(axis=1)]
SO2_Data=SO2_Data.dropna()
SO2_Data=SO2_Data.resample('h').mean()
SO2_Data=SO2_Data.dropna()
SO2_Data.head()

,WE,AE,Temp,RH,Ref,Lab2,Net Signal,Month,Day_of_week,Day,Hour
Date,,,,,,,,,,,
2019-10-10 04:00:00,344.013811,342.484305,18.332589,82.373211,1.190555,9.990807,1.529506,10.0,3.0,10.0,4.0
2019-10-10 05:00:00,347.947204,342.688948,18.160512,83.041499,1.517400,21.173371,5.258256,10.0,3.0,10.0,5.0
2019-10-10 06:00:00,349.586425,342.643169,18.294731,80.755815,1.596648,26.255508,6.943256,10.0,3.0,10.0,6.0
2019-10-10 07:00:00,348.280332,342.545156,21.874264,74.161148,1.518688,22.449829,5.735176,10.0,3.0,10.0,7.0
2019-10-10 08:00:00,352.303813,345.041354,29.141688,59.611152,1.379748,23.209242,7.262459,10.0,3.0,10.0,8.0

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error as mae
import sklearn.metrics as sm
import matplotlib.pyplot as plt
#'Ref_CO','Ref_NO2','Ref_O3',
X=SO2_Data[['Net Signal','Lab2','Temp','RH','Month','Day_of_week','Hour']]
y=SO2_Data['Ref']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
len(X)

1996

from flaml import AutoML
from sklearn.datasets import fetch_california_housing

# Initialize an AutoML instance
automl = AutoML()
# Specify automl goal and constraint
automl_settings = {
    "time_budget": 200,  # in seconds
    "metric": 'rmse',
    "task": 'regression',
    "log_file_name": "california.log",
}
# Train with labeled input data
automl.fit(X_train=X_train.drop(['Lab2'], axis=1), y_train=y_train,**automl_settings,estimator_list=["xgboost"])
pred=automl.predict(X_test.drop(['Lab2'], axis=1))
R2=round(sm.r2_score(y_test, pred), 2)
r=round(np.corrcoef(y_test, pred)[0, 1],2)
RMSE=round(np.sqrt(sm.mean_squared_error(y_test, pred))/np.mean(y),2)
print(r,R2,RMSE)
# Predict
#print(automl.predict(X_test))
# Print the best model
print(automl.model.estimator)

from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
  
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel':  ['rbf', 'poly', 'sigmoid']} 
  
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
grid.fit(X_train.drop(['Lab2'], axis=1), y_train)

# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)